<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="http://www.manh.com/ILSNET/Entity" xmlns:tns="http://www.manh.com/ILSNET/Entity" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="MultiOrderPallet" type="tns:MultiOrderPallet" />
  <xs:complexType name="MultiOrderPallet">
    <xs:sequence>
      <xs:element minOccurs="1" maxOccurs="1" name="multiOrderPalletId" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="userDef1" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="userDef2" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="userDef3" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="userDef4" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="userDef5" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="userDef6" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="wserDef7" type="xs:decimal" />
      <xs:element minOccurs="0" maxOccurs="1" name="wserDef8" type="xs:decimal" />
      <xs:element minOccurs="1" maxOccurs="1" name="warehouse" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="unbounded" name="customers" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="unbounded" name="shipmentIds" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="unbounded" name="shipTos" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="shippingLoadNum" type="xs:int" />
      <xs:element minOccurs="0" maxOccurs="1" name="carrier" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="location" type="xs:string" />
    </xs:sequence>
  </xs:complexType>
</xs:schema>