<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="DeleteManifestResponse" targetNamespace="http://www.manh.com/ILSNET/Shipping/DeleteManifestResponse"
	elementFormDefault="qualified" xmlns="http://www.manh.com/ILSNET/Shipping/DeleteManifestResponse"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	xmlns:import="http://www.manh.com/ILSNET/General/Result">
	<xs:import id="Result" schemaLocation="../General/Result.xsd" namespace="http://www.manh.com/ILSNET/General/Result" />
	<xs:element name="DeleteManifestResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Result" type="import:Result" maxOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>