<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="Address" targetNamespace="http://www.manh.com/ILSNET/General/Address"
	elementFormDefault="qualified" xmlns="http://www.manh.com/ILSNET/General/Address"
	xmlns:mstns="http://www.manh.com/ILSNET/General/Address" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:complexType name="Address">
		<xs:sequence>
			<xs:element name="Address1" type="xs:string" maxOccurs="1" />
			<xs:element name="Address2" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="Address3" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="AttentionTo" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="City" type="xs:string"  maxOccurs="1" />
			<xs:element name="Country" type="xs:string"  maxOccurs="1" />
			<xs:element name="EmailAddress" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="FaxNum" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="Name" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="PhoneNum" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="PostalCode" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="State" type="xs:string" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	<xs:element name="Address" type="Address"></xs:element>
</xs:schema>