<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="http://www.manh.com/ILSNET/Entities" xmlns:tns="http://www.manh.com/ILSNET/Entities" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Error" type="tns:Error" />
	<xs:complexType name="Error">
		<xs:sequence>
			<xs:element minOccurs="1" maxOccurs="1" name="ErrorCode" type="xs:string" />
			<xs:element minOccurs="1" maxOccurs="1" name="ErrorType" type="xs:string" />
			<xs:element minOccurs="1" maxOccurs="1" name="Message" type="xs:string" />
			<xs:element minOccurs="0" maxOccurs="unbounded" name="AdditionalError" type="tns:AdditionalError" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="AdditionalError">
		<xs:sequence>
			<xs:element minOccurs="1" maxOccurs="1" name="ErrorCode" type="xs:string" />
			<xs:element minOccurs="1" maxOccurs="1" name="ErrorType" type="xs:string" />
			<xs:element minOccurs="1" maxOccurs="1" name="Message" type="xs:string" />
		</xs:sequence>
	</xs:complexType>
</xs:schema>