<xs:schema xmlns:tns="http://www.manh.com/ILSNET/Entities" elementFormDefault="qualified" targetNamespace="http://www.manh.com/ILSNET/Entities" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="ArrayOfWorkInstruction" type="tns:ArrayOfWorkInstruction" />
  <xs:complexType name="ArrayOfWorkInstruction">
    <xs:sequence>
      <xs:element minOccurs="1" maxOccurs="unbounded" name="WorkInstruction" type="tns:WorkInstruction" />
    </xs:sequence>
  </xs:complexType>
  <xs:element name="WorkInstruction" type="tns:WorkInstruction"/>
  <xs:complexType name="WorkInstruction">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="1" name="company" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="condition" type="xs:string" />
      <xs:element minOccurs="1" maxOccurs="1" name="internalInstructionNumber" type="xs:int" />
      <xs:element minOccurs="0" maxOccurs="1" name="item" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="userDef1" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="userDef2" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="userDef3" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="userDef4" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="userDef5" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="userDef6" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="userDef7" type="xs:decimal" />
      <xs:element minOccurs="0" maxOccurs="1" name="userDef8" type="xs:decimal" />     
    </xs:sequence>
  </xs:complexType>
</xs:schema>
