<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:tns="http://www.manh.com/ILSNET/Entities" elementFormDefault="qualified" targetNamespace="http://www.manh.com/ILSNET/Entities" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="shippingContainerVasActivities" type="tns:shippingContainerVasActivities" />
  <xs:complexType name="shippingContainerVasActivities">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="Links" type="tns:Link" />
      <xs:element minOccurs="1" maxOccurs="1" name="LaborStartTime" type="xs:dateTime" />
      <xs:element minOccurs="0" maxOccurs="unbounded" name="shippingContainerVasActivity" type="tns:shippingContainerVasActivity" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="Link">
    <xs:attribute name="href" type="xs:string" />
    <xs:attribute name="type" type="xs:string" />
    <xs:attribute name="rel" type="xs:string" />
  </xs:complexType>
  <xs:complexType name="shippingContainerVasActivity">
    <xs:sequence>
      <xs:element minOccurs="1" maxOccurs="1" name="completed" type="xs:boolean" />
      <xs:element minOccurs="0" maxOccurs="1" name="createdBy" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="instructions" type="xs:string" />
      <xs:element minOccurs="1" maxOccurs="1" name="internalContainerNum" type="xs:int" />
      <xs:element minOccurs="0" maxOccurs="1" name="containerId" type="xs:string" />
      <xs:element minOccurs="1" maxOccurs="1" name="containerStatus" type="xs:int" />
      <xs:element minOccurs="0" maxOccurs="1" name="shipmentId" type="xs:string" />
      <xs:element minOccurs="1" maxOccurs="1" name="objectId" type="xs:int" />
      <xs:element minOccurs="0" maxOccurs="1" name="userDef1" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="userDef2" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="userDef3" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="userDef4" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="userDef5" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="userDef6" type="xs:string" />
      <xs:element minOccurs="1" maxOccurs="1" name="userDef7" nillable="true" type="xs:decimal" />
      <xs:element minOccurs="1" maxOccurs="1" name="userDef8" nillable="true" type="xs:decimal" />
      <xs:element minOccurs="1" maxOccurs="1" name="vasActivityObjectID" type="xs:int" />
      <xs:element minOccurs="0" maxOccurs="1" name="vasActivity" type="xs:string" />
      <xs:element minOccurs="1" maxOccurs="1" name="qcStatus" type="xs:int" />
      <xs:element minOccurs="1" maxOccurs="1" name="internalShipmentNum" type="xs:int" />
    </xs:sequence>
  </xs:complexType>
</xs:schema>