<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="GetManifestsResponse" targetNamespace="http://www.manh.com/ILSNET/Shipping/GetManifestsResponse"
	elementFormDefault="qualified" xmlns="http://www.manh.com/ILSNET/Shipping/GetManifestsResponse"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:import="http://www.manh.com/ILSNET/Shipping/Manifest"
	xmlns:import1="http://www.manh.com/ILSNET/General/Result">
	<xs:import schemaLocation="../General/Result.xsd" namespace="http://www.manh.com/ILSNET/General/Result" />
	<xs:import schemaLocation="Manifest.xsd" namespace="http://www.manh.com/ILSNET/Shipping/Manifest" />
	<xs:element name="GetManifestsResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Result" type="import1:Result" maxOccurs="1" />
				<xs:element name="Manifests" type="ManifestList" minOccurs="0" maxOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="ManifestList">
		<xs:sequence>
			<xs:element name="Manifest" type="import:Manifest" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
</xs:schema>