<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:tns="http://www.manh.com/ILSNET/Entities" elementFormDefault="qualified" targetNamespace="http://www.manh.com/ILSNET/Entities" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="itemUnitOfMeasureHttpEntityList" type="tns:itemUnitOfMeasureHttpEntityList" />
  <xs:complexType name="itemUnitOfMeasureHttpEntityList">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="itemUnitOfMeasureHttpEntity" type="tns:itemUnitOfMeasureHttpEntity" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="itemUnitOfMeasureHttpEntity">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="links" type="tns:Link" />
      <xs:element minOccurs="0" maxOccurs="1" name="company" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="conversionQty" type="xs:decimal" />
      <xs:element minOccurs="0" maxOccurs="1" name="dimensionUM" type="xs:string" />
      <xs:element minOccurs="1" maxOccurs="1" name="height" type="xs:decimal" />
      <xs:element minOccurs="1" maxOccurs="1" name="length" type="xs:decimal" />
      <xs:element minOccurs="0" maxOccurs="1" name="internalItemUM" type="xs:int" />
      <xs:element minOccurs="0" maxOccurs="1" name="item" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="quantityUM" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="sequence" type="xs:int" />
      <xs:element minOccurs="0" maxOccurs="1" name="treatFullPercent" type="xs:int" />
      <xs:element minOccurs="0" maxOccurs="1" name="weight" type="xs:decimal" />
      <xs:element minOccurs="0" maxOccurs="1" name="weightUM" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="width" type="xs:decimal" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="link">
    <xs:attribute name="href" type="xs:string" />
    <xs:attribute name="type" type="xs:string" />
    <xs:attribute name="rel" type="xs:string" />
  </xs:complexType>
</xs:schema>