<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="AddressCandidatesListCriteria" targetNamespace="http://www.manh.com/ILSNET/Shipping/AddressCandidatesListCriteria"
	elementFormDefault="qualified" xmlns="http://www.manh.com/ILSNET/Shipping/AddressCandidatesListCriteria"
	xmlns:mstns="http://www.manh.com/ILSNET/Shipping/AddressCandidatesListCriteria"
	xmlns:import="http://www.manh.com/ILSNET/General/Address" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:import id="Address" schemaLocation="../General/Address.xsd" namespace="http://www.manh.com/ILSNET/General/Address" />
	<xs:complexType name="AddressCandidatesListCriteria">
		<xs:sequence>
			<xs:element name="Addresses" type="import:Address" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	<xs:element name="AddressCandidatesListCriteria" type="AddressCandidatesListCriteria"></xs:element>
</xs:schema>