<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:tns="http://www.manh.com/ILSNET/Entities" elementFormDefault="qualified" targetNamespace="http://www.manh.com/ILSNET/Entities" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="CycleCountPlan" type="tns:CycleCountPlan" />
	<xs:complexType name="CycleCountPlan">
		<xs:sequence>
			<xs:element name="InternalPlanNum" type="xs:int" minOccurs="1" maxOccurs="1" />
			<xs:element name="CompletedDate" type="xs:dateTime" minOccurs="0" maxOccurs="1" />
			<xs:element name="CreatedDate" type="xs:dateTime" minOccurs="0" maxOccurs="1" />
			<xs:element name="GroupSize" type="xs:int" minOccurs="1" maxOccurs="1" />
			<xs:element name="MasterName" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="ProcessStamp" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="Released" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<xs:element name="RequestId" type="xs:int" minOccurs="1" maxOccurs="1" />
			<xs:element name="TotalClosed" type="xs:int" minOccurs="1" maxOccurs="1" />
			<xs:element name="TotalOneStepError" type="xs:int" minOccurs="1" maxOccurs="1" />
			<xs:element name="TotalOpen" type="xs:int" minOccurs="1" maxOccurs="1" />
			<xs:element name="TotalReviewed" type="xs:int" minOccurs="1" maxOccurs="1" />
			<xs:element name="TotalTwoStepError" type="xs:int" minOccurs="1" maxOccurs="1" />
			<xs:element name="UserDef1" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="UserDef2" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="UserDef3" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="UserDef4" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="UserDef5" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="UserDef6" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="UserDef7" type="xs:decimal" minOccurs="1" maxOccurs="1" />
			<xs:element name="UserDef8" type="xs:decimal" minOccurs="1" maxOccurs="1" />
			<xs:element name="Warehouse" type="xs:string" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>
</xs:schema>