<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="Parcel" targetNamespace="http://www.manh.com/ILSNET/Shipping/Parcel" elementFormDefault="qualified"
	xmlns="http://www.manh.com/ILSNET/Shipping/Parcel" 
	xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:import1="http://www.manh.com/ILSNET/General/UserDefinedFields"
	xmlns:import2="http://www.manh.com/ILSNET/Shipping/Accessorial">
	<xs:import id="UserDefinedFields" schemaLocation="../General/UserDefinedFields.xsd" namespace="http://www.manh.com/ILSNET/General/UserDefinedFields" />
	<xs:import id="Accessorial" schemaLocation="Accessorial.xsd" namespace="http://www.manh.com/ILSNET/Shipping/Accessorial" />
	<xs:complexType name="Parcel">
		<xs:sequence>
			<xs:element name="ContainerId" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="InternalContainerNumber" type="xs:int" minOccurs="0" maxOccurs="1" />
			<xs:element name="AccessorialCharge" type="xs:double" minOccurs="0" maxOccurs="1" />
			<xs:element name="ReturnsAccessorialCharge" type="xs:double" minOccurs="0" maxOccurs="1" />
			<xs:element name="BaseFreightCharge" type="xs:double" minOccurs="0" maxOccurs="1" />
			<xs:element name="ReturnsBaseFreightCharge" type="xs:double" minOccurs="0" maxOccurs="1" />
			<xs:element name="BundleId" type="xs:int" minOccurs="0" maxOccurs="1" />
			<xs:element name="FreightDiscount" type="xs:double" minOccurs="0" maxOccurs="1" />
			<xs:element name="ReturnsFreightDiscount" type="xs:double" minOccurs="0" maxOccurs="1" />
			<xs:element name="HundredWeight" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<xs:element name="ManifestId" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="MSN" type="xs:int" minOccurs="0" maxOccurs="1" />
			<xs:element name="ReturnsMSN" type="xs:int" minOccurs="0" maxOccurs="1" />
			<xs:element name="TotalFreightCharge" type="xs:double" minOccurs="0" maxOccurs="1" />
			<xs:element name="ReturnsTotalFreightCharge" type="xs:double" minOccurs="0" maxOccurs="1" />
			<xs:element name="TrackingNumber" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="ReturnsTrackingNumber" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="ReturnsPrintLabel" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="ReturnsCalltagFee" type="xs:double" minOccurs="0" maxOccurs="1" />
			<xs:element name="ShippingContainerUserDefinedFields" type="import1:UserDefinedFields" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>
</xs:schema>