<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:tns="http://www.manh.com/ILSNET/Entities" elementFormDefault="qualified" targetNamespace="http://www.manh.com/ILSNET/Entities" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="itemHttpEntity" type="tns:itemHttpEntity" />
  <xs:complexType name="itemHttpEntity">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="links" type="tns:Link" />
      <xs:element minOccurs="1" maxOccurs="1" name="catchWeightRequired" type="xs:bool" />
      <xs:element minOccurs="0" maxOccurs="1" name="company" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="cost" type="xs:decimal" />
      <xs:element minOccurs="0" maxOccurs="1" name="dateTimeStamp" type="xs:string" />
      <xs:element minOccurs="1" maxOccurs="1" name="department" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="description" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="division" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="itemClass" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="internalItemNumber" type="xs:int" />
      <xs:element minOccurs="0" maxOccurs="1" name="inventoryTracking" type="xs:bool" />
      <xs:element minOccurs="0" maxOccurs="1" name="itemColor" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="itemSize" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="itemStyle" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="itemValue" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="lotControlled" type="xs:bool" />
      <xs:element minOccurs="0" maxOccurs="1" name="nmfcCode" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="packingClass" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="serialNumberTracking" type="xs:bool" />
      <xs:element minOccurs="0" maxOccurs="1" name="storageTemplate" type="xs:string" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="link">
    <xs:attribute name="href" type="xs:string" />
    <xs:attribute name="type" type="xs:string" />
    <xs:attribute name="rel" type="xs:string" />
  </xs:complexType>
</xs:schema>