<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="ManifestContainerResponse" targetNamespace="http://www.manh.com/ILSNET/Shipping/ManifestContainerResponse"
	elementFormDefault="qualified" xmlns="http://www.manh.com/ILSNET/Shipping/ManifestContainerResponse"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:import="http://www.manh.com/ILSNET/General/UserDefinedFields" xmlns:import1="http://www.manh.com/ILSNET/General/Result"
	xmlns:import2="http://www.manh.com/ILSNET/Shipping/Parcel">
	<xs:import schemaLocation="../General/Result.xsd" namespace="http://www.manh.com/ILSNET/General/Result" />
	<xs:import schemaLocation="../General/UserDefinedFields.xsd" namespace="http://www.manh.com/ILSNET/General/UserDefinedFields" />
	<xs:import schemaLocation="Parcel.xsd" namespace="http://www.manh.com/ILSNET/Shipping/Parcel" />
	<xs:element name="ManifestContainerResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Result" type="import1:Result" maxOccurs="1" />
				<xs:element name="Parcels" type="ParcelList" minOccurs="0" maxOccurs="1" />
				<xs:element name="AccessorialCharge" type="xs:double" minOccurs="1" maxOccurs="1" />
				<xs:element name="BaseFreightCharge" type="xs:double" minOccurs="1" maxOccurs="1" />
				<xs:element name="FreightDiscount" type="xs:double" minOccurs="1" maxOccurs="1" />
				<xs:element name="TotalFreightCharge" type="xs:double" minOccurs="1" maxOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="ParcelList">
		<xs:sequence>
			<xs:element name="Parcel" type="import2:Parcel" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
</xs:schema>