<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="InterfaceEntity" elementFormDefault="qualified"
	xmlns="http://www.manh.com/ILSNET/Interface" xmlns:xs="http://www.w3.org/2001/XMLSchema" version ="2007">
	<xs:complexType name="InterfaceEntity">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="1" name="Action" type="xs:string" />
			<xs:element minOccurs="0" maxOccurs="1" name="CreationDateTimeStamp" type="xs:dateTime" />
			<xs:element minOccurs="0" maxOccurs="1" name="CreationProcessStamp" type="xs:string" />
			<xs:element minOccurs="0" maxOccurs="1" name="DateTimeStamp" type="xs:dateTime" />
			<xs:element minOccurs="0" maxOccurs="1" name="InterfaceRecordId" type="xs:string" />
			<xs:element minOccurs="0" maxOccurs="1" name="ProcessStamp" type="xs:string" />
			<xs:element minOccurs="0" maxOccurs="1" name="UserDef1" type="xs:string" />
			<xs:element minOccurs="0" maxOccurs="1" name="UserDef2" type="xs:string" />
			<xs:element minOccurs="0" maxOccurs="1" name="UserDef3" type="xs:string" />
			<xs:element minOccurs="0" maxOccurs="1" name="UserDef4" type="xs:string" />
			<xs:element minOccurs="0" maxOccurs="1" name="UserDef5" type="xs:string" />
			<xs:element minOccurs="0" maxOccurs="1" name="UserDef6" type="xs:string" />
			<xs:element minOccurs="0" maxOccurs="1" name="UserDef7" type="xs:decimal" />
			<xs:element minOccurs="0" maxOccurs="1" name="UserDef8" type="xs:decimal" />
			<xs:element minOccurs="0" maxOccurs="1" name="UserStamp" type="xs:string" />
		</xs:sequence>
	</xs:complexType>
</xs:schema>