<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="http://www.manh.com/ILSNET/Entities" xmlns:tns="http://www.manh.com/ILSNET/Entities" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="CycleCountQuickPlansRequest">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="CycleCountQuickPlan" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="CycleCountQuickPlan" type="tns:CycleCountQuickPlan" />
	<xs:complexType name="CycleCountQuickPlan">
		<xs:sequence>
			<xs:element name="Company" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="CountPerGroup" type="xs:int" minOccurs="0" maxOccurs="1" />
			<xs:element name="CreateWork" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<xs:element name="Department" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="Description" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="Division" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="ExpiresByDays" type="xs:int" minOccurs="0" maxOccurs="1" />
			<xs:element name="InventoryStatus" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="Item" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="ItemCategory1" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="ItemCategory2" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="ItemCategory3" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="ItemCategory4" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="ItemCategory5" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="ItemCategory6" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="ItemCategory7" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="ItemCategory8" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="ItemCategory9" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="ItemCategory10" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="ItemClass" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="ItemColor" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="ItemSize" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="ItemStyle" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="ItemUserDef1" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="ItemUserDef2" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="ItemUserDef3" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="ItemUserDef4" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="ItemUserDef5" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="ItemUserDef6" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="ItemUserDef7" type="xs:decimal" minOccurs="0" maxOccurs="1" />
			<xs:element name="ItemUserDef8" type="xs:decimal" minOccurs="0" maxOccurs="1" />
			<xs:element name="ListPrice" type="xs:decimal" minOccurs="0" maxOccurs="1" />
			<xs:element name="LocatingZone" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="Location" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="LocationType" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="Lot" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="MaximumCount" type="xs:int" minOccurs="0" maxOccurs="1" />
			<xs:element name="MultiItem" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<xs:element name="Permanent" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<xs:element name="TrackContainers" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<xs:element name="SerialNumberTracked" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<xs:element name="Warehouse" type="xs:string" minOccurs="1" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>
</xs:schema>