<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:tns="http://www.manh.com/ILSNET/Entities" elementFormDefault="qualified" targetNamespace="http://www.manh.com/ILSNET/Entities" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="rateShipmentRequest" type="tns:rateShipmentRequest" />
  <xs:complexType name="rateShipmentRequest">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="1" name="carrier" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="carrierService" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="company" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="erpOrder" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="freightBillToAddress1" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="freightBillToAddress2" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="freightBillToAddress3" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="freightBillToAttentionTo" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="freightBillToCity" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="freightBillToCountry" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="freightBillToEmailAddress" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="freightBillToFaxNum" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="freightBillToName" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="FreightBillToPhoneNum" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="freightBillToPostalCode" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="freightBillToState" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="freightTerms" type="xs:string" />
      <xs:element minOccurs="1" maxOccurs="1" name="internalShipmentNumber" type="xs:int" />
      <xs:element minOccurs="1" maxOccurs="1" name="isInternationalShipment" type="xs:boolean" />
      <xs:element minOccurs="1" maxOccurs="1" name="quantity" type="xs:decimal" />
      <xs:element minOccurs="0" maxOccurs="1" name="quantityUm" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="recipientAddress1" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="recipientAddress2" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="recipientAddress3" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="recipientAttentionTo" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="recipientCity" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="recipientCountry" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="recipientEmailAddress" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="recipientFaxNum" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="recipientName" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="recipientPhoneNum" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="recipientPostalCode" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="recipientState" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="shipmentID" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="shipperAddress1" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="shipperAddress2" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="shipperAddress3" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="shipperAttentionTo" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="shipperCity" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="shipperCountry" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="shipperEmailAddress" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="shipperFaxNum" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="shipperName" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="shipperPhoneNum" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="shipperPostalCode" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="shipperState" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="shipDate" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="shipperCode" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="userDefinedField1" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="userDefinedField2" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="userDefinedField3" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="userDefinedField4" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="userDefinedField5" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="userDefinedField6" type="xs:string" />
      <xs:element minOccurs="1" maxOccurs="1" name="userDefinedField7" type="xs:decimal" />
      <xs:element minOccurs="1" maxOccurs="1" name="userDefinedField8" type="xs:decimal" />
      <xs:element minOccurs="1" maxOccurs="1" name="volume" type="xs:decimal" />
      <xs:element minOccurs="0" maxOccurs="1" name="volumeUm" type="xs:string" />
      <xs:element minOccurs="1" maxOccurs="1" name="weight" type="xs:decimal" />
      <xs:element minOccurs="0" maxOccurs="1" name="weightUm" type="xs:string" />
    </xs:sequence>
  </xs:complexType>
</xs:schema>