<?xml version="1.0" encoding="utf-8"?>
<xs:schema
		targetNamespace="http://www.manh.com/ILSNET/Shipping"
		xmlns:tns="http://www.manh.com/ILSNET/Shipping"
		xmlns:xs="http://www.w3.org/2001/XMLSchema"
		elementFormDefault="qualified">
	<xs:include schemaLocation="ContainerReference.xsd"/>
	<xs:element name="locateShippingContainersResponse" type="tns:locateShippingContainersResponse" />
	<xs:complexType name="locateShippingContainersResponse">
		<xs:choice>
      <xs:element minOccurs="0" maxOccurs="1" name="error" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="unbounded" name="locateShippingContainerResponse" type="tns:locateShippingContainerResponse" />
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="locateShippingContainerResponse">
		<xs:all>
			<xs:element minOccurs="1" maxOccurs="1" name="containerReference" type="tns:ContainerReference" />
			<xs:element minOccurs="1" maxOccurs="1" name="location" type="xs:string" />
		</xs:all>
	</xs:complexType>
</xs:schema>
