<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="ShippingContainers-Closed" xmlns="http://www.manh.com/ILSNET/Entity" targetNamespace="http://www.manh.com/ILSNET/Entity" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="ShippingContainersClosedRequest" type="tns:ShippingContainersClosedRequest" />
	<xs:complexType name="ShippingContainersClosedRequest">
		<xs:sequence>
			<xs:element minOccurs="1" maxOccurs="1" name="Warehouse" type="xs:string" />
			<xs:element minOccurs="1" maxOccurs="1" name="ContainerId" type="xs:string" />
			<xs:element minOccurs="1" maxOccurs="1" name="Weight" type="xs:decimal" />
			<xs:element minOccurs="0" maxOccurs="1" name="SuppressZeroWeightValidation" type="xs:boolean" default="false" />
			<xs:element minOccurs="0" maxOccurs="1" name="SuppressWeightToleranceValidation" type="xs:boolean" default="false" />
      <xs:element minOccurs="0" maxOccurs="1" name="SuppressRemanifestFedExContainerValidation" type="xs:boolean" default="false" />
      <xs:element minOccurs="0" maxOccurs="1" name="SuppressVasConfirmationValidation" type="xs:boolean" default="false" />
      <xs:element minOccurs="0" maxOccurs="1" name="ProcessStartTime" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="ProcessName" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="Carrier" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="CarrierService" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="ContainerCountNumber" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="ContainerCountTotal" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="ContainerType" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="InternalShipmentNum" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="Length" type="xs:decimal" />
      <xs:element minOccurs="0" maxOccurs="1" name="Width" type="xs:decimal" />
      <xs:element minOccurs="0" maxOccurs="1" name="Height" type="xs:decimal" />
      <xs:element minOccurs="0" maxOccurs="1" name="NmfcCode" type="xs:string" />
	  <xs:element minOccurs="0" maxOccurs="1" name="TrackingNumber" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="UserDef1" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="UserDef2" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="UserDef3" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="UserDef4" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="UserDef5" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="UserDef6" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="UserDef7" type="xs:decimal" />
      <xs:element minOccurs="0" maxOccurs="1" name="UserDef8" type="xs:decimal" />
    </xs:sequence>
	</xs:complexType>
</xs:schema>