<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:tns="http://www.manh.com/ILSNET/Shipping" elementFormDefault="qualified" 
		   targetNamespace="http://www.manh.com/ILSNET/Shipping" 
		   xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:include schemaLocation ="ContainerReferenceList.xsd" />
  <xs:complexType name="containerReference">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="1" name="internalContainerNum" type="xs:int" />
      <xs:element minOccurs="0" maxOccurs="1" name="containerId" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="nestedContainerReferences" type="tns:containerReferenceList" />
    </xs:sequence>
  </xs:complexType>
</xs:schema>
