<xs:schema xmlns:tns="http://www.manh.com/ILSNET/Entities" elementFormDefault="qualified" targetNamespace="http://www.manh.com/ILSNET/Entities" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:include schemaLocation="SerialNumberDTO.xsd" />
  <xs:element name="ArrayOfPickShipmentWorkInstructionsRequest" type="tns:ArrayOfPickShipmentWorkInstructionsRequest" />
  <xs:complexType name="ArrayOfPickShipmentWorkInstructionsRequest">
    <xs:sequence>
      <xs:element minOccurs="1" maxOccurs="unbounded" name="PickShipmentWorkInstructionsRequest" type="tns:PickShipmentWorkInstructionsRequest" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="PickShipmentWorkInstructionsRequest">
    <xs:sequence>
      <xs:element minOccurs="1" maxOccurs="1" name="InternalInstructionNum" type="xs:int" />
      <xs:element minOccurs="1" maxOccurs="1" name="QuantityConfirmed" type="xs:decimal" />
      <xs:element minOccurs="0" maxOccurs="1" name="SerialNumbers" type="tns:ArrayOfString" />
      <xs:element minOccurs="0" maxOccurs="1" name="SerialNumberDTOs" type="tns:ArrayOfArrayOfSerialNumberDTO" />
      <xs:element minOccurs="0" maxOccurs="1" name="ReasonCode" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="WorkProfile" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="CatchWeights" type="tns:ArrayOfDecimal" />
      <xs:element minOccurs="0" maxOccurs="1" name="CatchWeightUMs" type="tns:ArrayOfString" />
      <xs:element minOccurs="0" maxOccurs="1" name="FromQty" type="xs:decimal" />
      <xs:element minOccurs="0" maxOccurs="1" name="ToQty" type="xs:decimal" />
      <xs:element minOccurs="0" maxOccurs="1" name="FromLoc" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="Lot" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="LogisticsUnit" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="ParentLogisticsUnit" type="xs:string" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ArrayOfString">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="string" nillable="true" type="xs:string" />
    </xs:sequence>
  </xs:complexType>
   <xs:complexType name="ArrayOfDecimal">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="decimal" type="xs:decimal" />
    </xs:sequence>
  </xs:complexType>
  </xs:schema>