<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="DeleteManifestRequest" targetNamespace="http://www.manh.com/ILSNET/Shipping/DeleteManifestRequest"
	elementFormDefault="qualified" xmlns="http://www.manh.com/ILSNET/Shipping/DeleteManifestRequest"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:import="http://www.manh.com/ILSNET/Shipping/Manifest"
	xmlns:import1="http://www.manh.com/ILSNET/General/UserDefinedFields">
	<xs:import schemaLocation="../General/UserDefinedFields.xsd" namespace="http://www.manh.com/ILSNET/General/UserDefinedFields" />
	<xs:import schemaLocation="Manifest.xsd" namespace="http://www.manh.com/ILSNET/Shipping/Manifest" />
	<xs:element name="DeleteManifestRequest">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Manifest" type="import:Manifest" minOccurs="1" maxOccurs="1" />
				<xs:element name="RatingServiceUserDefinedFields" type="import1:UserDefinedFields" maxOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>