<?xml version="1.0" encoding="utf-8"?>
<xs:schema 
		targetNamespace="http://www.manh.com/ILSNET/Shipping" 
		xmlns:tns="http://www.manh.com/ILSNET/Shipping" 
		xmlns:xs="http://www.w3.org/2001/XMLSchema"
		elementFormDefault="qualified">
	<xs:element name="transferShipmentHeadersRequest" type="tns:transferShipmentHeadersRequest" />
	<xs:complexType name="transferShipmentHeadersRequest">
		<xs:sequence>
			<xs:element minOccurs="1" maxOccurs="unbounded" name="internalShipmentNumber" type="xs:int" />
			<xs:element minOccurs="1" maxOccurs="1" name="location" type="xs:string" />
			<xs:element minOccurs="1" maxOccurs="1" name="locationRowVersion" type="xs:long" />
			<xs:element minOccurs="1" maxOccurs="1" name="WaitForComplete" type="xs: xs:boolean" /> 
		</xs:sequence>
	</xs:complexType>
</xs:schema>