<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="ContainerType" targetNamespace="http://www.manh.com/ILSNET/Interface" elementFormDefault="qualified"
	xmlns="http://www.manh.com/ILSNET/Interface" xmlns:xs="http://www.w3.org/2001/XMLSchema" version ="2007">
	<xs:include schemaLocation="InterfaceEntity.xsd" />
  <xs:complexType name="ContainerType">
    <xs:complexContent mixed="false">
      <xs:extension base="InterfaceEntity">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="1" name="Class" type="xs:string" />
          <xs:element minOccurs="0" maxOccurs="1" name="Desc" type="xs:string" />
          <xs:element minOccurs="0" maxOccurs="1" name="DimensionUm" type="xs:string" />
          <xs:element minOccurs="0" maxOccurs="1" name="FedExRatingSymbol" type="xs:string" />
          <xs:element minOccurs="0" maxOccurs="1" name="Height" type="xs:decimal" />
          <xs:element minOccurs="0" maxOccurs="1" name="Length" type="xs:decimal" />
          <xs:element minOccurs="0" maxOccurs="1" name="MaxWeight" type="xs:decimal" />
          <xs:element minOccurs="0" maxOccurs="1" name="RatingSymbol" type="xs:string" />
          <xs:element minOccurs="0" maxOccurs="1" name="Type" type="xs:string" />
          <xs:element minOccurs="0" maxOccurs="1" name="UseAsDefault" type="xs:string" />
          <xs:element minOccurs="0" maxOccurs="1" name="Volume" type="xs:decimal" />
          <xs:element minOccurs="0" maxOccurs="1" name="VolumeUm" type="xs:string" />
          <xs:element minOccurs="0" maxOccurs="1" name="Weight" type="xs:decimal" />
          <xs:element minOccurs="0" maxOccurs="1" name="WeightUm" type="xs:string" />
          <xs:element minOccurs="0" maxOccurs="1" name="WeightTolerance" type="xs:decimal" />
          <xs:element minOccurs="0" maxOccurs="1" name="Width" type="xs:decimal" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
</xs:schema>