<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="Address" targetNamespace="http://www.manh.com/ILSNET/Interface" elementFormDefault="qualified"
	xmlns="http://www.manh.com/ILSNET/Interface" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:include schemaLocation="InterfaceEntity.xsd" />
	<xs:complexType name="Address">
    <xs:complexContent mixed="false">
      <xs:extension base="InterfaceEntity">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="1" name="Active" type="xs:string" />
          <xs:element minOccurs="0" maxOccurs="1" name="Address1" type="xs:string" />
          <xs:element minOccurs="0" maxOccurs="1" name="Address2" type="xs:string" />
          <xs:element minOccurs="0" maxOccurs="1" name="Address3" type="xs:string" />
          <xs:element minOccurs="0" maxOccurs="1" name="AttentionTo" type="xs:string" />
          <xs:element minOccurs="0" maxOccurs="1" name="City" type="xs:string" />
          <xs:element minOccurs="0" maxOccurs="1" name="Consignee" type="xs:string" />
          <xs:element minOccurs="0" maxOccurs="1" name="Country" type="xs:string" />
          <xs:element minOccurs="0" maxOccurs="1" name="EmailAddress" type="xs:string" />
          <xs:element minOccurs="0" maxOccurs="1" name="FaxNum" type="xs:string" />
          <xs:element minOccurs="0" maxOccurs="1" name="Name" type="xs:string" />
          <xs:element minOccurs="0" maxOccurs="1" name="PhoneNum" type="xs:string" />
          <xs:element minOccurs="0" maxOccurs="1" name="PostalCode" type="xs:string" />
          <xs:element minOccurs="0" maxOccurs="1" name="ResidentialFlag" type="xs:string" />
          <xs:element minOccurs="0" maxOccurs="1" name="State" type="xs:string" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
</xs:schema>