<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:tns="http://www.manh.com/ILSNET/Entities" elementFormDefault="qualified" targetNamespace="http://www.manh.com/ILSNET/Entities" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="ShippingContainerVasActivitiesRequest" type="tns:ShippingContainerVasActivitiesRequest" />
  <xs:complexType name="ShippingContainerVasActivitiesRequest">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="1" name="ContainerId" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="Warehouse" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="ShipmentId" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="unbounded" name="VasActivity" type="xs:string" />
    </xs:sequence>
  </xs:complexType>
</xs:schema>