<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="Manifest" targetNamespace="http://www.manh.com/ILSNET/Shipping/Manifest"
	elementFormDefault="qualified" xmlns="http://www.manh.com/ILSNET/Shipping/Manifest"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:import="http://www.manh.com/ILSNET/General/UserDefinedFields">
	<xs:import id="UserDefinedFields" schemaLocation="../General/UserDefinedFields.xsd" namespace="http://www.manh.com/ILSNET/General/UserDefinedFields" />
	<xs:complexType name="Manifest">
		<xs:sequence>
			<xs:element name="Name" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="ShipDate" type="xs:dateTime" minOccurs="0" maxOccurs="1" />
			<xs:element name="ShipperCode" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="Warehouse" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="Status" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="ManifestSymbol" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="CarrierSymbol" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="ManifestUserDefinedFields" type="import:UserDefinedFields" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>
</xs:schema>