<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="http://www.manh.com/ILSNET/Entities" xmlns:tns="http://www.manh.com/ILSNET/Entities" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element minOccurs="1" maxOccurs="unbound"  name="LaborDetailResponse" type="tns:LaborDetailResponse" />
	<xs:complexType name="LaborDetailResponse">
		<xs:sequence>
			<xs:element name="activityScreen" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="activityType" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="actualRate" type="xs:decimal" minOccurs="0" maxOccurs="1" />
			<xs:element name="closed" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="company" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="containerID" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="dateTimeStamp" type="xs:dateTime" minOccurs="0" maxOccurs="1" />
			<xs:element name="deviceType" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="endDateTime" type="xs:dateTime" minOccurs="0" maxOccurs="1" />
			<xs:element name="equipmentType" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="FromLocation" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="goalQuantity" type="xs:decimal" minOccurs="0" maxOccurs="1" />
			<xs:element name="goalRate" type="xs:decimal" minOccurs="0" maxOccurs="1" />
			<xs:element name="internalDetailNum" type="xs:int" minOccurs="0" maxOccurs="1" />
			<xs:element name="internalNum" type="xs:int" minOccurs="0" maxOccurs="1" />
			<xs:element name="item" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="laborGroup" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="laborType" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="licensePlate" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="manual" type="xs:bool" minOccurs="0" maxOccurs="1" />
			<xs:element name="percentOfGoal" type="xs:decimal" minOccurs="0" maxOccurs="1" />
			<xs:element name="processStamp" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="processType" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="quantityUm" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="referenceId" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="sessionId" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="shift" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="startDateTime" type="xs:dateTime" minOccurs="0" maxOccurs="1" />
			<xs:element name="toLocation" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="totalActualTime" type="xs:decimal" minOccurs="0" maxOccurs="1" />
			<xs:element name="totalLaborCost" type="xs:decimal" minOccurs="0" maxOccurs="1" />
			<xs:element name="totalQuantity" type="xs:int" minOccurs="0" maxOccurs="1" />
			<xs:element name="totalTransactions" type="xs:int" minOccurs="0" maxOccurs="1" />
			<xs:element name="totalValue" type="xs:decimal" minOccurs="0" maxOccurs="1" />
			<xs:element name="totalVolume" type="xs:decimal" minOccurs="0" maxOccurs="1" />
			<xs:element name="totalWeight" type="xs:decimal" minOccurs="0" maxOccurs="1" />
			<xs:element name="userDef1" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="userDef2" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="userDef3" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="userDef4" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="userDef5" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="userDef6" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="userDef7" type="xs:decimal" minOccurs="0" maxOccurs="1" />
			<xs:element name="userDef8" type="xs:decimal" minOccurs="0" maxOccurs="1" />
			<xs:element name="userName" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="userStamp" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="volumeUm" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="wageRate" type="xs:decimal" minOccurs="0" maxOccurs="1" />
			<xs:element name="warehouse" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="waveNum" type="xs:int" minOccurs="0" maxOccurs="1" />
			<xs:element name="weightUm" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="workGroup" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="workTeam" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="workUnit" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element minOccurs="1" maxOccurs="1" name="links" type="tns:Link" /> 
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Link">
		<xs:attribute name="href" type="xs:string" /> 
		<xs:attribute name="type" type="xs:string" /> 
		<xs:attribute name="rel" type="xs:string" /> 
	</xs:complexType>
</xs:schema>