<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="AddressCandidatesList" targetNamespace="http://www.manh.com/ILSNET/Shipping/AddressCandidatesList"
	elementFormDefault="qualified" xmlns="http://www.manh.com/ILSNET/Shipping/AddressCandidatesList"
	xmlns:mstns="http://www.manh.com/ILSNET/Shipping/AddressCandidatesList"
	xmlns:import="http://www.manh.com/ILSNET/Shipping/AddressCandidates"
	xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:import id="AddressCandidates" schemaLocation="AddressCandidates.xsd" namespace="http://www.manh.com/ILSNET/Shipping/AddressCandidates" />
	<xs:complexType name="AddressCandidatesList">
		<xs:sequence>
			<xs:element name="AddressCandidates" type="import:AddressCandidates" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	<xs:element name="AddressCandidatesList" type="AddressCandidatesList"></xs:element>
</xs:schema>