<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="CarrierRateList" targetNamespace="http://www.manh.com/ILSNET/Shipping/CarrierRateList"
	elementFormDefault="qualified" xmlns="http://www.manh.com/ILSNET/Shipping/CarrierRateList"
	xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="CarrierRateList">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="CarrierRate" type="CarrierRate" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="CarrierRate">
		<xs:sequence>
			<xs:element name="Carrier" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="Service" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="GrossFreightCharge" type="xs:double" minOccurs="0" maxOccurs="1" />
			<xs:element name="NetFreightCharge" type="xs:double" minOccurs="0" maxOccurs="1" />
			<xs:element name="FreightSurcharge" type="xs:double" minOccurs="0" maxOccurs="1" />
			<xs:element name="FreightDiscount" type="xs:double" minOccurs="0" maxOccurs="1" />
			<xs:element name="DaysToDeliver" type="xs:int" minOccurs="0" maxOccurs="1" />
			<xs:element name="Error" type="xs:string" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>
</xs:schema>