<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="Item" targetNamespace="http://www.manh.com/ILSNET/Interface" elementFormDefault="qualified"
	xmlns="http://www.manh.com/ILSNET/Interface" xmlns:xs="http://www.w3.org/2001/XMLSchema" version ="2007">
	<xs:include schemaLocation="InterfaceEntity.xsd" />
	<xs:complexType name="Item">
		<xs:complexContent mixed="false">
			<xs:extension base="InterfaceEntity">
				<xs:sequence>
					<xs:element minOccurs="0" maxOccurs="1" name="Active" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="AllocationRule" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="AlternateItem" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="AppIdentifier" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="AvailableOnWeb" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="BomAction" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="CatchWeightReqd" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="Color" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="Company" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="ContCreationFullQty" type="xs:decimal" />
					<xs:element minOccurs="0" maxOccurs="1" name="ContCreationFullQtyUm" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="ContCreationInnerpackQty" type="xs:decimal" />
					<xs:element minOccurs="0" maxOccurs="1" name="Cost" type="xs:decimal" />
					<xs:element minOccurs="0" maxOccurs="1" name="CountryOfOrigin" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="DaysToExpire" type="xs:int" />
					<xs:element minOccurs="0" maxOccurs="1" name="Department" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="Desc" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="Division" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="EPCCAGECode" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="EPCCompanyPrefix" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="EPCItemReference" type="xs:string" />
          <xs:element minOccurs="0" maxOccurs="1" name="Error" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="FedExITN" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="FedExXTN" type="xs:string" />
          <xs:element minOccurs="0" maxOccurs="1" name="GtinEnabled" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="HarmCode" type="GenericConfigDetail" />
					<xs:element minOccurs="0" maxOccurs="1" name="Item" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="ItemCategories" type="Categories" />
					<xs:element minOccurs="0" maxOccurs="1" name="ItemClass" type="ItemClass" />
					<xs:element minOccurs="0" maxOccurs="1" name="ImmediateNeedsEligible" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="ImmediateNeedsLocRule" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="InboundQcAmount" type="xs:decimal" />
					<xs:element minOccurs="0" maxOccurs="1" name="InboundQcAmountType" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="InboundQcEligible" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="InboundQcLocRule" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="InboundQcUm" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="ItemTemplate" type="Template" />
					<xs:element minOccurs="0" maxOccurs="1" name="InternalItemNum" type="xs:int" />
					<xs:element minOccurs="0" maxOccurs="1" name="InventoryTracking" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="ListPrice" type="xs:decimal" />
					<xs:element minOccurs="0" maxOccurs="1" name="LocatingRule" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="LongDesc" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="LotControlled" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="LotTemplate" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="NetCost" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="NetPrice" type="xs:decimal" />
					<xs:element minOccurs="0" maxOccurs="1" name="Nmfc" type="GenericConfigDetail" />
					<xs:element minOccurs="0" maxOccurs="1" name="PackingClass" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="PreferenceCrit" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="Producer" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="SerialNumTemplate" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="SerialNumTrackInbound" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="SerialNumTrackInventory" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="SerialNumTrackOutbound" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="Size" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="StorageTemplate" type="StorageTemplate" />
					<xs:element minOccurs="0" maxOccurs="1" name="Style" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="UOMS" type="UOMList" />
					<xs:element minOccurs="0" maxOccurs="1" name="WebImg" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="WebThumbnailImg" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="XRefs" type="XRefList" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="XRef">
		<xs:complexContent mixed="false">
			<xs:extension base="InterfaceEntity">
				<xs:sequence>
					<xs:element minOccurs="0" maxOccurs="1" name="XRefAppIdentifier" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="XRefGtinEnabled" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="XRefItem" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="XRefUM" type="xs:string" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="UOM">
		<xs:complexContent mixed="false">
			<xs:extension base="InterfaceEntity">
				<xs:sequence>
					<xs:element minOccurs="0" maxOccurs="1" name="ConvQty" type="xs:decimal" />
					<xs:element minOccurs="0" maxOccurs="1" name="DimensionUm" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="EPCPackageID" type="xs:int" />
					<xs:element minOccurs="0" maxOccurs="1" name="Height" type="xs:decimal" />
					<xs:element minOccurs="0" maxOccurs="1" name="InternalItemUm" type="xs:int" />
					<xs:element minOccurs="0" maxOccurs="1" name="Length" type="xs:decimal" />
					<xs:element minOccurs="0" maxOccurs="1" name="MovementClass" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="QtyUm" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="Sequence" type="xs:int" />
					<xs:element minOccurs="0" maxOccurs="1" name="TreatAsLoose" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="TreatFullPct" type="xs:decimal" />
					<xs:element minOccurs="0" maxOccurs="1" name="Weight" type="xs:decimal" />
					<xs:element minOccurs="0" maxOccurs="1" name="WeightUm" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="Width" type="xs:decimal" />
					<xs:element minOccurs="0" maxOccurs="1" name="SlottingID" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="SlottingPalletTI" type="xs:int" />
					<xs:element minOccurs="0" maxOccurs="1" name="SlottingPalletHI" type="xs:int" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="Template">
		<xs:complexContent mixed="false">
			<xs:extension base="InterfaceEntity">
				<xs:sequence>
					<xs:element minOccurs="0" maxOccurs="1" name="Active" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="Field1Length" type="xs:int" />
					<xs:element minOccurs="0" maxOccurs="1" name="Field1Type" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="Field2Length" type="xs:int" />
					<xs:element minOccurs="0" maxOccurs="1" name="Field2Type" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="Field3Length" type="xs:int" />
					<xs:element minOccurs="0" maxOccurs="1" name="Field3Type" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="Field4Length" type="xs:int" />
					<xs:element minOccurs="0" maxOccurs="1" name="Field4Type" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="Field5Length" type="xs:int" />
					<xs:element minOccurs="0" maxOccurs="1" name="Field5Type" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="Template" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="SeperatorChar" type="xs:string" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="StorageTemplateDetail">
		<xs:complexContent mixed="false">
			<xs:extension base="InterfaceEntity">
				<xs:sequence>
					<xs:element minOccurs="0" maxOccurs="1" name="Active" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="GroupDuringUnitize" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="Sequence" type="xs:int" />
					<xs:element minOccurs="0" maxOccurs="1" name="TreatFullPct" type="xs:int" />
					<xs:element minOccurs="0" maxOccurs="1" name="Um" type="xs:string" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="StorageTemplate">
		<xs:complexContent mixed="false">
			<xs:extension base="InterfaceEntity">
				<xs:sequence>
					<xs:element minOccurs="0" maxOccurs="1" name="Active" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="Desc" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="Details" type="StorageTemplateDetailList" />
					<xs:element minOccurs="0" maxOccurs="1" name="Class" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="Template" type="xs:string" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="StorageTemplateDetailList">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="StorageTemplateDetail" nillable="true"
				type="StorageTemplateDetail" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ItemClass">
		<xs:complexContent mixed="false">
			<xs:extension base="InterfaceEntity">
				<xs:sequence>
					<xs:element minOccurs="0" maxOccurs="1" name="ItemClass" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="StorageTemplate" type="StorageTemplate" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="Categories">
		<xs:complexContent mixed="false">			
			<xs:extension base="InterfaceEntity">
				<xs:sequence>
					<xs:element minOccurs="0" maxOccurs="1" name="Category1" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="Category10" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="Category2" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="Category3" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="Category4" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="Category5" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="Category6" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="Category7" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="Category8" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="Category9" type="xs:string" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="GenericConfigDetail">
		<xs:complexContent mixed="false">
			<xs:extension base="InterfaceEntity">
				<xs:sequence>
					<xs:element minOccurs="0" maxOccurs="1" name="Active" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="Desc" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="Identifier" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="RecordType" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="SysVal1" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="SysVal2" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="SysVal3" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="SysVal4" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="SysVal5" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="SystemCreated" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="User1Val" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="User2Val" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="User3Val" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="User4Val" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="User5Val" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="User6Val" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="User7Val" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="User8Val" type="xs:string" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="UOMList">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="UOM" nillable="true" type="UOM" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="XRefList">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="XRef" nillable="true" type="XRef" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="SKU">
		<xs:complexContent mixed="false">
			<xs:extension base="Item">
				<xs:sequence>
					<xs:element minOccurs="0" maxOccurs="1" name="BaseQty" type="xs:decimal" />
					<xs:element minOccurs="0" maxOccurs="1" name="BaseQtyUm" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="ConvertedQty" type="xs:decimal" />
					<xs:element minOccurs="0" maxOccurs="1" name="ConvertedQtyUm" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="DimensionUm" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="Height" type="xs:decimal" />
					<xs:element minOccurs="0" maxOccurs="1" name="Length" type="xs:decimal" />
					<xs:element minOccurs="0" maxOccurs="1" name="Location" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="Lot" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="Quantity" type="xs:decimal" />
					<xs:element minOccurs="0" maxOccurs="1" name="QuantityUm" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="TotalListPrice" type="xs:decimal" />
					<xs:element minOccurs="0" maxOccurs="1" name="TotalValue" type="xs:decimal" />
					<xs:element minOccurs="0" maxOccurs="1" name="TotalVolume" type="xs:decimal" />
					<xs:element minOccurs="0" maxOccurs="1" name="TotalWeight" type="xs:decimal" />
					<xs:element minOccurs="0" maxOccurs="1" name="TreatAsLoose" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="Value" type="xs:decimal" />
					<xs:element minOccurs="0" maxOccurs="1" name="Volume" type="xs:decimal" />
					<xs:element minOccurs="0" maxOccurs="1" name="VolumeUm" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="Weight" type="xs:decimal" />
					<xs:element minOccurs="0" maxOccurs="1" name="WeightUm" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="Whs" type="xs:string" />
					<xs:element minOccurs="0" maxOccurs="1" name="Width" type="xs:decimal" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>