<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:tns="http://www.manh.com/ILSNET/Entities" elementFormDefault="qualified" targetNamespace="http://www.manh.com/ILSNET/Entities" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="locationInventoryAttributes" type="tns:locationInventoryAttributes" />
  <xs:complexType name="locationInventoryAttributes">
    <xs:sequence>
      <xs:element minOccurs="1" maxOccurs="1" name="attributeId" type="xs:int" />
      <xs:element minOccurs="0" maxOccurs="1" name="locInvAttribute1" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="locInvAttribute10" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="locInvAttribute11" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="locInvAttribute12" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="locInvAttribute13" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="locInvAttribute14" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="locInvAttribute15" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="locInvAttribute16" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="locInvAttribute17" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="locInvAttribute18" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="locInvAttribute19" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="locInvAttribute2" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="locInvAttribute20" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="locInvAttribute3" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="locInvAttribute4" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="locInvAttribute5" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="locInvAttribute6" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="locInvAttribute7" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="locInvAttribute8" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="locInvAttribute9" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="processStamp" type="xs:string" />
      <xs:element minOccurs="1" maxOccurs="1" name="internalLocationInv" type="xs:int" />
    </xs:sequence>
  </xs:complexType>
</xs:schema>