<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:tns="http://www.manh.com/ILSNET/Entities" elementFormDefault="qualified" targetNamespace="http://www.manh.com/ILSNET/Entities" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:import namespace="http://www.manh.com/ILSNET/Shipping" />
  <xs:element name="palletBuildingResponse" type="tns:palletBuildingResponse" />
  <xs:complexType name="palletBuildingResponse">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="1" name="palletReferences" xmlns:q1="http://www.manh.com/ILSNET/Shipping" type="q1:containerReferenceList" />
      <xs:element minOccurs="0" maxOccurs="1" name="containersNotNested" xmlns:q2="http://www.manh.com/ILSNET/Shipping" type="q2:containerReferenceList" />
    </xs:sequence>
  </xs:complexType>
</xs:schema>