<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="http://www.manh.com/ILSNET/Shipping" xmlns:tns="http://www.manh.com/ILSNET/Shipping" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:include schemaLocation="ContainerReference.xsd" />
	<xs:element name="locateShippingContainersRequest" type="tns:locateShippingContainersRequest" />
	<xs:complexType name="locateShippingContainersRequest">
		<xs:sequence>
			<xs:element minOccurs="1" maxOccurs="unbounded" name="containerReference" type="tns:ContainerReference" />
			<xs:element minOccurs="0" maxOccurs="1" name="waveNumber" type="xs:int" />
		</xs:sequence>
	</xs:complexType>
</xs:schema>