<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="http://www.manh.com/ILSNET/Entities" xmlns:tns="http://www.manh.com/ILSNET/Entities" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="LaborEvent" type="tns:LaborEvent" />
	<xs:complexType name="LaborEvent">
		<xs:sequence>
			<xs:element name="activityScreen" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="activityType" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="company" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="containerID" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="deviceType" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="endDateTime" type="xs:dateTime" minOccurs="0" maxOccurs="1" />
			<xs:element name="environment" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="equipmentType" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="fromLocation" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="internalNumber" type="xs:int" minOccurs="0" maxOccurs="1" />
			<xs:element name="item" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="laborActivity" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="laborGroup" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="licensePlate" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="processStamp" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="processType" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="quantityUm" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="referenceId" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="requestType" type="xs:int" minOccurs="0" maxOccurs="1" />
			<xs:element name="sessionId" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="shift" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="startDateTime" type="xs:dateTime" minOccurs="0" maxOccurs="1" />
			<xs:element name="status" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="toLocation" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="totalLaborCost" type="xs:int" minOccurs="0" maxOccurs="1" />
			<xs:element name="totalQuantity" type="xs:int" minOccurs="0" maxOccurs="1" />
			<xs:element name="totalTransactions" type="xs:int" minOccurs="0" maxOccurs="1" />
			<xs:element name="totalValue" type="xs:int" minOccurs="0" maxOccurs="1" />
			<xs:element name="totalVolume" type="xs:int" minOccurs="0" maxOccurs="1" />
			<xs:element name="totalWeight" type="xs:int" minOccurs="0" maxOccurs="1" />
			<xs:element name="userName" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="userStamp" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="volumeUm" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="wageRate" type="xs:int" minOccurs="0" maxOccurs="1" />
			<xs:element name="warehouse" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="waveNum" type="xs:int" minOccurs="0" maxOccurs="1" />
			<xs:element name="weightUm" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="workGroup" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="workTeam" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="workType" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="workUnit" type="xs:string" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>
</xs:schema>