<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="PrintLabelRequest" targetNamespace="http://www.manh.com/ILSNET/Shipping/PrintLabelRequest"
	elementFormDefault="qualified" xmlns="http://www.manh.com/ILSNET/Shipping/PrintLabelRequest"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:import="http://www.manh.com/ILSNET/Printing/PrintAttributes" xmlns:import1="http://www.manh.com/ILSNET/General/UserDefinedFields"
	xmlns:import2="http://www.manh.com/ILSNET/Shipping/Parcel">
	<xs:import schemaLocation="../General/UserDefinedFields.xsd" namespace="http://www.manh.com/ILSNET/General/UserDefinedFields" />
	<xs:import schemaLocation="../Printing/PrintAttributes.xsd" namespace="http://www.manh.com/ILSNET/Printing/PrintAttributes" />
	<xs:import schemaLocation="Parcel.xsd" namespace="http://www.manh.com/ILSNET/Shipping/Parcel" />
	<xs:element name="PrintLabelRequest">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="PrintAttributes" type="import:PrintAttributes" maxOccurs="1" />
				<xs:element name="Parcel" type="import2:Parcel" maxOccurs="1" />
				<xs:element name="RatingServiceUserDefinedFields" type="import1:UserDefinedFields" maxOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>