<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="CarrierRateListCriteria" targetNamespace="http://www.manh.com/ILSNET/Shipping/CarrierRateListCriteria"
	elementFormDefault="qualified" xmlns="http://www.manh.com/ILSNET/Shipping/CarrierRateListCriteria"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:import1="http://www.manh.com/ILSNET/General/Address">
	<xs:import id="Address" schemaLocation="../General/Address.xsd" namespace="http://www.manh.com/ILSNET/General/Address" />
	<xs:element name="CarrierRateListCriteria">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ShipmentId" type="xs:string" minOccurs="0" maxOccurs="1" />
				<xs:element name="InternalShipmentNum" type="xs:int" minOccurs="0" maxOccurs="1" />
				<xs:element name="Carrier" type="xs:string" minOccurs="0" maxOccurs="1" />
				<xs:element name="CarrierService" type="xs:string" minOccurs="0" maxOccurs="1" />
				<xs:element name="CarrierGroup" type="xs:string" minOccurs="0" maxOccurs="1" />
				<xs:element name="Company" type="xs:string" minOccurs="0" maxOccurs="1" />
				<xs:element name="FreightTerms" type="xs:string" minOccurs="0" maxOccurs="1" />
				<xs:element name="Customer" type="xs:string" minOccurs="0" maxOccurs="1" />
				<xs:element name="ShipTo" type="xs:string" minOccurs="0" maxOccurs="1" />
				<xs:element name="ShipToAddress" type="import1:Address" minOccurs="0" maxOccurs="1" />
				<xs:element name="TotalWeight" type="xs:double" minOccurs="0" maxOccurs="1" />
				<xs:element name="TotalVolume" type="xs:double" minOccurs="0" maxOccurs="1" />
				<xs:element name="Warehouse" type="xs:string" minOccurs="0" maxOccurs="1" />
				<xs:element name="WeightUm" type="xs:string" minOccurs="0" maxOccurs="1" />
				<xs:element name="VolumeUm" type="xs:string" minOccurs="0" maxOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>