<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:tns="http://www.manh.com/ILSNET/Entities" elementFormDefault="qualified" targetNamespace="http://www.manh.com/ILSNET/Entities" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="rateShipmentResponse" type="tns:rateShipmentResponse" />
  <xs:complexType name="rateShipmentResponse">
    <xs:sequence>
      <xs:element minOccurs="1" maxOccurs="1" name="accessorialCharge" type="xs:double" />
      <xs:element minOccurs="1" maxOccurs="1" name="baseFreightCharge" type="xs:double" />
      <xs:element minOccurs="0" maxOccurs="1" name="errorMessage" type="xs:string" />
      <xs:element minOccurs="1" maxOccurs="1" name="freightDiscount" type="xs:double" />
      <xs:element minOccurs="1" maxOccurs="1" name="internalShipmentNumber" type="xs:int" />
      <xs:element minOccurs="0" maxOccurs="1" name="shipmentID" type="xs:string" />
      <xs:element minOccurs="1" maxOccurs="1" name="totalFreightCharge" type="xs:double" />
    </xs:sequence>
  </xs:complexType>
</xs:schema>