<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="UnmanifestContainerRequest" targetNamespace="http://www.manh.com/ILSNET/Shipping/UnmanifestContainerRequest"
	elementFormDefault="qualified" xmlns="http://www.manh.com/ILSNET/Shipping/UnmanifestContainerRequest"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:import="http://www.manh.com/ILSNET/General/UserDefinedFields" xmlns:import1="http://www.manh.com/ILSNET/Shipping/Parcel">
	<xs:import schemaLocation="../General/UserDefinedFields.xsd" namespace="http://www.manh.com/ILSNET/General/UserDefinedFields" />
	<xs:import schemaLocation="Parcel.xsd" namespace="http://www.manh.com/ILSNET/Shipping/Parcel" />
	<xs:element name="UnmanifestContainerRequest">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Parcel" type="import1:Parcel" maxOccurs="1" />
				<xs:element name="RatingServiceUserDefinedFields" type="import:UserDefinedFields" maxOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>