<xs:schema xmlns:tns="http://www.manh.com/ILSNET/Entities" elementFormDefault="qualified" targetNamespace="http://www.manh.com/ILSNET/Entities" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:complexType name="ReceiptContainerHttpEntity">
    <xs:sequence>
      <xs:element name="Width" type="xs:decimal" />
      <xs:element name="Company" type="xs:string" />
      <xs:element name="ContainerClass" type="xs:string" />
      <xs:element name="ContainerId" type="xs:string" />
      <xs:element name="ContainerType" type="xs:string" />
      <xs:element name="ConvertedLocQty" type="xs:int" />
      <xs:element name="ConvertedQtyUM" type="xs:string" />
      <xs:element name="DateTimeStamp" type="xs:dateTime" />
      <xs:element name="DimensionUM" type="xs:string" />
      <xs:element name="DispositionCode" type="xs:string" />
      <xs:element name="Epc" type="xs:string" />
      <xs:element name="ExpirationDateTime" type="xs:dateTime" />
      <xs:element name="FromLocation" type="xs:string" />
      <xs:element name="FromWarehouse" type="xs:string" />
      <xs:element name="Height" type="xs:int" />
      <xs:element name="IncomingPdLoc" type="xs:string" />
      <xs:element name="InterfaceRecordId" type="xs:string" />
      <xs:element name="InternalGroupNum" type="xs:int" />
      <xs:element name="InternalLocContNum" type="xs:int" />
      <xs:element name="InternalLocInvNum" type="xs:int" />
      <xs:element name="InternalRecContNum" type="xs:int" />	
      <xs:element name="InternalReceiptLineNum" type="xs:int" />
      <xs:element name="InternalReceiptNum" type="xs:int" />
      <xs:element name="InventorySts" type="xs:string" />
      <xs:element name="Item" type="xs:string" />
      <xs:element name="ItemClass" type="xs:string" />
      <xs:element name="ItemDesc" type="xs:string" />
      <xs:element name="LaunchNum" type="xs:int" />
      <xs:element name="Length" type="xs:int" />
      <xs:element name="LocInvAttributesId" type="xs:int" />
      <xs:element name="LocatingRule" type="xs:string" />
      <xs:element name="Lot" type="xs:string" />
      <xs:element name="ManufacturedDateTime" type="xs:dateTime" />
      <xs:element name="OutgoingPdLoc" type="xs:string" />
      <xs:element name="Parent" type="xs:int" />
      <xs:element name="ProcessStamp" type="xs:string" />
      <xs:element name="QcInspection" type="xs:string" />
      <xs:element name="Quantity" type="xs:int" />
      <xs:element name="QuantityUm" type="xs:string" />
      <xs:element name="ReasonCode" type="xs:string" />
      <xs:element name="ReceiptDate" type="xs:dateTime" />
      <xs:element name="ReceiptId" type="xs:string" />
      <xs:element name="ReceiptIdType" type="xs:string" />
      <xs:element name="Status" type="xs:int" />
      <xs:element name="StatusFailed" type="xs:string" />
      <xs:element name="StatusFlowName>" type="xs:string" />
      <xs:element name="ToLocation" type="xs:string" />
      <xs:element name="ToWarehouse" type="xs:string" />
      <xs:element name="UploadInterfaceBatch" type="xs:string" />
      <xs:element name="Uri" type="xs:string" />
      <xs:element name="UsedByImmedNeed" type="xs:string" />      
      
<xs:element name="UserDef1" type="xs:string" />
      <xs:element name="UserDef2" type="xs:string" />
      <xs:element name="UserDef3" type="xs:string" />
      <xs:element name="UserDef4" type="xs:string" />
      <xs:element name="UserDef5>" type="xs:string" />
      <xs:element name="UserDef6" type="xs:string" />
      <xs:element name="UserDef7" type="xs:int" />
      <xs:element name="UserDef8" type="xs:int" />
      <xs:element name="UserStamp" type="xs:string" />
      <xs:element name="Weight" type="xs:int" />	
      <xs:element name="WeightUm" type="xs:string" />							
    </xs:sequence>
  </xs:complexType>
  <xs:element name="ErrorMessage" type="xs:string"/>
  <xs:complexType name="InternalNumsCreated">
    <xs:sequence>
      <xs:element name="int" type="xs:int" />
    </xs:sequence>
  </xs:complexType> 
</xs:schema>


