-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */





CREATE VIEW INTERFACE_ERROR_VIEW

AS

SELECT

INTERNAL_ERROR_NUMBER,
ORIGINAL_FILE_PATH,
ERROR_FILE_PATH,
ERROR_MSG,
INTERFACE_PROCESS,
INTERFACE_MODE,
USER_DEF1 AS UD_INTERFACEERROR01,
USER_DEF2 AS UD_INTERFACEERROR02,
USER_DEF3 AS UD_INTERFACEERROR03,
USER_DEF4 AS UD_INTERFACEERROR04,
USER_DEF5 AS UD_INTERFACEERROR05,
USER_DEF6 AS UD_INTERFACEERROR06,
USER_DEF7 AS UD_INTERFACEERROR07,
USER_DEF8 AS UD_INTERFACEERROR08,
USER_STAMP,
PROCESS_STAMP,
DATE_TIME_STAMP,
COMPANY,
EMAIL_SENT,
REFERENCE_ID01,
REFERENCE_ID02,
REFERENCE_ID03,
REFERENCE_ID04,
REFERENCE_ID05,
REFERENCE_ID06,
REFERENCE_ID07,
REFERENCE_ID08,
REFERENCE_ID09,
REFERENCE_ID10,
REFERENCE_ID11,
REFERENCE_ID12,
REFERENCE_ID13,
REFERENCE_ID14,
REFERENCE_ID15,
REFERENCE_ID16,
REFERENCE_ID17,
REFERENCE_ID18,
REFERENCE_ID19,
REFERENCE_ID20,
WAREHOUSE

FROM INTERFACE_ERROR