-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */







CREATE VIEW METADATA_INSIGHT_CYCLE_COUNT_PLAN_VIEW
AS 
SELECT 
CCP.INTERNAL_PLAN_NUM,
CCP.MASTER_NAME,
CCP.WAREHOUSE,
CCP.CREATED_DATE,
CCP.COMPLETED_DATE,
CCP.TOTAL_OPEN,
CCP.TOTAL_REVIEWED,
CCP.TOTAL_CLOSED,
CCP.TOTAL_ONE_STEP_ERROR,
CCP.TOTAL_TWO_STEP_ERROR,
CCP.GROUP_SIZE,
CCP.RELEASED,
CCP.USER_DEF1 AS UD_CYCLEPLAN01,
CCP.USER_DEF2 AS UD_CYCLEPLAN02,
CCP.USER_DEF3 AS UD_CYCLEPLAN03,
CCP.USER_DEF4 AS UD_CYCLEPLAN04,
CCP.USER_DEF5 AS UD_CYCLEPLAN05,
CCP.USER_DEF6 AS UD_CYCLEPLAN06,
CCP.USER_DEF7 AS UD_CYCLEPLAN07,
CCP.USER_DEF8 AS UD_CYCLEPLAN08,
CCP.USER_STAMP,
CCP.PROCESS_STAMP,
CCP.DATE_TIME_STAMP,
CCP.IN_CREATION,
CCP.REQUEST_ID,
CCP.UPDATE_CYCLECOUNTS,
CCP.NEGATIVE_ADJ_TYPE,
CCP.POSITIVE_ADJ_TYPE,
CCP.TOTAL_OPEN + CCP.TOTAL_CLOSED AS TOTAL_TRANSACTIONS,
(COALESCE(CCP.TOTAL_ONE_STEP_ERROR, 0) + COALESCE(CCP.TOTAL_TWO_STEP_ERROR, 0))  AS ERRORSTOTAL,
(CASE WHEN (CCP.TOTAL_CLOSED > 0 ) THEN ROUND(((COALESCE(CCP.TOTAL_ONE_STEP_ERROR, 0) + COALESCE(CCP.TOTAL_TWO_STEP_ERROR, 0)) / COALESCE(CCP.TOTAL_CLOSED, 0)) * 100, 3) ELSE 0 END) AS ERRORSPERCENT,
(CASE WHEN (CCP.TOTAL_OPEN + CCP.TOTAL_CLOSED > 0) THEN ROUND((CCP.TOTAL_CLOSED / (CCP.TOTAL_OPEN + CCP.TOTAL_CLOSED)) * 100, 3) ELSE 0 END) AS PERCENT_COMPLETE
FROM CYCLE_COUNT_PLAN CCP