-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */














CREATE Procedure WRK_MonitorWorkGroupChartData
@filterCriteria nVarchar(MAX),
@culture nvarchar(10)
        
AS
    Set NoCount ON
	DECLARE @warehouse as nVarchar(50);
	DECLARE @criteriaTempTable TABLE (
   filterName nVarchar(300),
   filterValue nVarchar(300))

 /* [comment omitted] */
  INSERT INTO @criteriaTempTable SELECT * FROM fn_GetMonitorFilterParameters(@filterCriteria)

  SELECT @warehouse = filterValue from @criteriaTempTable WHERE filterName = N'<literal:1>'
	
  
  SELECT N'<literal:2>' AS CHARTDATA_MonitorWorkGroup, CATEGORY = CASE WHEN  WORK_INSTRUCTION.WORK_GROUP IS NULL THEN dbo.RSCMfn_RtrvResource(N'<literal:3>',N'<literal:4>',@culture) ELSE WORK_INSTRUCTION.WORK_GROUP END, 																			
																	COUNT(DISTINCT WORK_INSTRUCTION.WORK_UNIT)AS DATA, 
																	DESCRIPTION =CASE WHEN  WORK_INSTRUCTION.WORK_GROUP IS NULL THEN NULL ELSE GENERIC_CONFIG_DETAIL.DESCRIPTION END,	
																	N'<literal:5>' AS XAXISTITLE, N'<literal:6>' AS YAXISTITLE, 1 AS NextDrillDownLevel, N'<literal:7>' AS CHARTTITLE  FROM WORK_INSTRUCTION
         LEFT OUTER JOIN GENERIC_CONFIG_DETAIL ON GENERIC_CONFIG_DETAIL.IDENTIFIER = WORK_INSTRUCTION.WORK_GROUP
  WHERE (WORK_INSTRUCTION.FROM_WHS =@warehouse OR WORK_INSTRUCTION.TO_WHS=@warehouse ) AND INSTRUCTION_TYPE =  N'<literal:8>' AND WORK_INSTRUCTION.CONDITION != N'<literal:9>'  and (GENERIC_CONFIG_DETAIL.RECORD_TYPE =N'<literal:10>' or GENERIC_CONFIG_DETAIL.RECORD_TYPE IS NULL)  GROUP BY WORK_INSTRUCTION.WORK_GROUP, GENERIC_CONFIG_DETAIL.DESCRIPTION 
  ORDER BY DATA DESC

    /* [comment omitted] */

 DECLARE @TOTAL_WORKUNIT INT=0,@TOTAL_INTERNAL_INSTRUCTION_NUM INT=0,@TOTAL_ESTIMATED_TIME NUMERIC(9,0)=0, @OPEN_INTERNAL_INSTRUCTION_NUM INT, @INPROCESS_INTERNAL_INSTRUCTION_NUM INT, @CLOSED_INTERNAL_INSTRUCTION_NUM INT;

   SELECT  @TOTAL_WORKUNIT = SUM(WORK.WORK_UNIT_COUNT),
		   @TOTAL_INTERNAL_INSTRUCTION_NUM =SUM(WORK.INSTRUCTION_NUMS_COUNT) ,
		   @TOTAL_ESTIMATED_TIME =ISNULL(SUM(WORK.ESTIMATED_TIMES), 0) , 
		   @OPEN_INTERNAL_INSTRUCTION_NUM = SUM(CASE WHEN WORK.CONDITION = N'<literal:11>' THEN WORK.INSTRUCTION_NUMS_COUNT ELSE 0 END), 
		   @INPROCESS_INTERNAL_INSTRUCTION_NUM = SUM(CASE WHEN WORK.CONDITION = N'<literal:12>' THEN WORK.INSTRUCTION_NUMS_COUNT ELSE 0 END)
	FROM(
		SELECT COUNT(DISTINCT WORK_UNIT) AS WORK_UNIT_COUNT, COUNT(INTERNAL_INSTRUCTION_NUM) AS INSTRUCTION_NUMS_COUNT, ISNULL(SUM(ESTIMATED_TIME), 0) AS ESTIMATED_TIMES, CONDITION FROM WORK_INSTRUCTION WHERE
			INSTRUCTION_TYPE =  N'<literal:13>' AND CONDITION != N'<literal:14>' AND (FROM_WHS =@warehouse OR TO_WHS=@warehouse) GROUP BY CONDITION
  )WORK

   SELECT @CLOSED_INTERNAL_INSTRUCTION_NUM = COUNT(INTERNAL_INSTRUCTION_NUM)
	FROM WORK_INSTRUCTION_VIEW
		 WHERE  INSTRUCTION_TYPE =  N'<literal:15>'  AND (FROM_WHS =@warehouse OR TO_WHS=@warehouse)		  
		  AND CONDITION =N'<literal:16>'
		  AND  DATE_TIME_STAMP >=DATEADD(HOUR, -1, GETUTCDATE())
   
   SELECT top 1 N'<literal:17>' AS N'<literal:18>', @TOTAL_WORKUNIT AS N'<literal:19>';
   SELECT top 1 N'<literal:20>' AS N'<literal:21>', @TOTAL_INTERNAL_INSTRUCTION_NUM AS N'<literal:22>';
   SELECT top 1 N'<literal:23>' AS N'<literal:24>', @TOTAL_ESTIMATED_TIME AS N'<literal:25>';
   SELECT top 1 N'<literal:26>' AS N'<literal:27>', @OPEN_INTERNAL_INSTRUCTION_NUM AS N'<literal:28>' ;	
   SELECT top 1 N'<literal:29>' AS N'<literal:30>', @INPROCESS_INTERNAL_INSTRUCTION_NUM AS N'<literal:31>' ;
   SELECT top 1 N'<literal:32>' AS N'<literal:33>',  @CLOSED_INTERNAL_INSTRUCTION_NUM AS N'<literal:34>' ;
   
   /* [comment omitted] */                  
    If @@ERROR <> 0 GoTo ErrorHandler
    Set NoCount OFF
    Return(0)
  
ErrorHandler:
    Return(@@ERROR)



	