-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
CREATE VIEW dbo.UPLOAD_ORDER_HEADER_VIEW
AS
SELECT     ACTUAL_SHIP_DATE_TIME, DATE_TIME_STAMP, INTERFACE_RECORD_ID, INTERNAL_SHIPMENT_NUM, CARRIER, CARRIER_SERVICE, 
                      SHIPPING_LOAD_NUM, SHIP_TO_STATE, CUSTOMER, SHIP_TO, SHIPMENT_ID, CUSTOMER_NAME, SHIP_TO_ADDRESS1, SHIP_TO_ADDRESS2, 
                      SHIP_TO_ADDRESS3, SHIP_TO_CITY, SHIP_TO_STATE AS Expr1, SHIP_TO_POSTAL_CODE, SHIP_TO_PHONE_NUM, SHIP_TO_COUNTRY, 
                      PLANNED_DELIVERY_DATE_TIME, USER_DEF7, PLANNED_SHIP_DATE, CUSTOMER_CATEGORY2, PRIORITY, CONSOLIDATED
FROM         dbo.UPLOAD_ORDER_HEADER
UNION
SELECT     ACTUAL_SHIP_DATE_TIME, DATE_TIME_STAMP, INTERFACE_RECORD_ID, INTERNAL_SHIPMENT_NUM, CARRIER, CARRIER_SERVICE, 
                      SHIPPING_LOAD_NUM, SHIP_TO_STATE, CUSTOMER, SHIP_TO, SHIPMENT_ID, CUSTOMER_NAME, SHIP_TO_ADDRESS1, SHIP_TO_ADDRESS2, 
                      SHIP_TO_ADDRESS3, SHIP_TO_CITY, SHIP_TO_STATE AS Expr1, SHIP_TO_POSTAL_CODE, SHIP_TO_PHONE_NUM, SHIP_TO_COUNTRY, 
                      PLANNED_DELIVERY_DATE_TIME, USER_DEF7, PLANNED_SHIP_DATE, CUSTOMER_CATEGORY2, PRIORITY, CONSOLIDATED
FROM         dbo.AR_UPLOAD_ORDER_HEADER