-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */









CREATE VIEW METADATA_INSIGHT_CYCLE_COUNT_REQUEST_VIEW
AS 
SELECT 
CCR.INTERNAL_COUNT_NUM,
CCR.INTERNAL_PLAN_NUM,
CCR.WAREHOUSE,
CCR.LOCATION,
CCR.ITEM,
CCR.COMPANY,
CCR.GROUP_NUMBER,
CCR.CREATE_DATE_TIME AS CREATEDATETIME,
CCR.CLOSED_DATE_TIME AS CLOSEDDATETIME,
CCR.COUNTED_DATE_TIME AS COUNTEDDATETIME,
CCR.COUNTED_BY_USER AS COUNTEDBYUSER,
CCR.DISCREPANCY_FOUND AS DISCREPANCYFOUND,
CCR.QUANTITY_COUNTED AS QUANTITYCOUNTED,
CCR.SYSTEM_QUANTITY AS SYSTEMQUANTITY,
CCR.LAUNCH_NUMBER,
CCR.WORK_CREATED,
CCR.INTERNAL_WORK_INSTR_NUM,
CCR.USER_DEF1,
CCR.USER_DEF2,
CCR.USER_DEF3,
CCR.USER_DEF4,
CCR.USER_DEF5,
CCR.USER_DEF6,
CCR.USER_DEF7,
CCR.USER_DEF8,
CCR.USER_STAMP,
CCR.PROCESS_STAMP,
CCR.DATE_TIME_STAMP,
CCR.ITEM_DESC,
CCR.CONDITION,
CCR.LOT,
CCR.CONTAINER_ID,
CCR.EXPIRATION_DATE,
CCR.REQUEST_UPDATED,
CCR.LOGISTICS_UNIT,
CCR.PARENT_LOGISTICS_UNIT,
CCR.IN_RECONCILIATION,
CCR.ASSIGNED_USER AS ASSIGNEDUSER,
CCR.LOC_INV_ATTRIBUTES_ID,
CCP.IN_CREATION,
CASE WHEN CCP.RELEASED = N'<literal:1>' AND (CCR.CONDITION = N'<literal:2>' AND CCR.WORK_CREATED = N'<literal:3>') THEN 1 ELSE 0 END AS Confirm,
CASE WHEN CCR.CONDITION = N'<literal:4>' OR (CCR.CONDITION = N'<literal:5>' AND CCR.WORK_CREATED = N'<literal:6>' AND CCP.RELEASED = N'<literal:7>') THEN 1 ELSE 0 END AS Reconcile
FROM CYCLE_COUNT_REQUEST CCR JOIN CYCLE_COUNT_PLAN CCP ON CCP.INTERNAL_PLAN_NUM=CCR.INTERNAL_PLAN_NUM