-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */




   


CREATE view LOCATION_INVENTORY_ATTRIBUTES_VIEW
as
select LOCATION_INVENTORY_ATTRIBUTES.*,
LOCATION_INVENTORY.ITEM,
LOCATION_INVENTORY.LOGISTICS_UNIT,
LOCATION_INVENTORY.Location,
LOCATION_INVENTORY.COMPANY,
LOCATION_INVENTORY.INTERNAL_LOCATION_INV,
LOCATION_INVENTORY.WAREHOUSE

from 
LOCATION_INVENTORY 
left  join LOCATION_INVENTORY_ATTRIBUTES ON LOCATION_INVENTORY.LOC_INV_ATTRIBUTES_ID= LOCATION_INVENTORY_ATTRIBUTES.OBJECT_ID 




