-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */







CREATE VIEW METADATA_INSIGHT_ARCHIVE_DATA_VIEW
AS
SELECT
ap.ARCHIVE_ID,
ap.ARCHIVE_NAME,
ap.ARCHIVE_PROCESS,
ap.ACTIVE,
ap.DATA_FILTER,
ap.DATE_TIME_STAMP,
ap.DAYS_HIST,
ap.DO_PATH,
ap.LAST_ARCH_DATE_TIME,
ap.PROCESS_STAMP,
ap.RUN_BY_DEFAULT,
ap.SAVE_DATA,
ap.SYSTEM_CREATED,
ap.TABLE_DO_NAME,
ap.USER_STAMP,
ap.USER_DEF1,
ap.USER_DEF2,
ap.USER_DEF3,
ap.USER_DEF4,
ap.USER_DEF5,
ap.USER_DEF6,
ap.USER_DEF7,
ap.USER_DEF8

FROM ARCHIVE_PREFERENCES ap

WHERE
ap.ACTIVE=N'<literal:1>'
