-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */




	

CREATE VIEW METADATA_INSIGHT_MOP_VIEW
AS
SELECT 
	MOP.MULTI_ORDER_PALLET_ID, 
	SC.CONTAINER_ID, 
	SC.CONTAINER_TYPE, 
	SC.CONTAINER_COUNT_TOTAL,
	SC.CONTAINER_COUNT_NUMBER, 
	(SELECT TOP 1 LOCATION FROM SHIPPING_CONTAINER WHERE PARENT = SC.INTERNAL_CONTAINER_NUM OR 
		PARENT IS NULL AND INTERNAL_CONTAINER_NUM = SC.INTERNAL_CONTAINER_NUM AND LOCATION IS NOT NULL) AS LOCATION, 
	(SELECT TOP 1 WORK_ZONE FROM SHIPPING_CONTAINER WHERE PARENT = SC.INTERNAL_CONTAINER_NUM OR
	PARENT IS NULL AND INTERNAL_CONTAINER_NUM = SC.INTERNAL_CONTAINER_NUM AND WORK_ZONE IS NOT NULL) AS WORK_ZONE, 	
	SC.VOLUME, 
	SC.WEIGHT, 
	SC.VALUE, 
	SC.STATUS,
	SC.NMFC_CODE, 
	SC.HAZARDOUS_CODE, 
	SH.SHIPMENT_ID, 
	SH.INTERNAL_SHIPMENT_NUM,
	SH.SHIPPING_LOAD_NUM, 
	SH.CARRIER, 
	SH.CARRIER_SERVICE,
	SH.CUSTOMER_NAME AS CUSTOMER,
	SH.SHIP_TO, 
	MOP.warehouse,
	SC.INTERNAL_CONTAINER_NUM,
	(cast(SC.INTERNAL_CONTAINER_NUM as nvarchar(9)) + N'<literal:1>' + cast(SH.INTERNAL_SHIPMENT_NUM as nvarchar(9))) AS ID 
FROM 
	SHIPPING_CONTAINER SC 
	INNER JOIN MULTI_ORDER_PALLET MOP ON SC.INTERNAL_MOP_NUMBER = MOP.INTERNAL_MOP_NUMBER
	INNER JOIN SHIPMENT_HEADER SH ON SC.INTERNAL_SHIPMENT_NUM = SH.INTERNAL_SHIPMENT_NUM
WHERE 
	SC.INTERNAL_MOP_NUMBER IS NOT NULL AND SC.PARENT IS NULL