-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */









CREATE VIEW METADATA_INSIGHT_TOTE_LINE_VIEW
AS
SELECT
td.OBJECT_ID,
td.TOTE_HEADER_ID,
td.WAREHOUSE,
td.ITEM,
td.ITEM_DESC,
td.COMPANY,
td.LOT,
td.QUANTITY,
td.QUANTITY_UM,
CASE WHEN SORTED_QUANTITY = -1 THEN 0 ELSE SORTED_QUANTITY END AS SORTED_QUANTITY,
td.SORTED_QTY_UM,
td.QUANTITY_TO_PACK,
td.PUT_WALL_LOCATION,
td.INTERNAL_INSTRUCTION_NUM,
td.INTERNAL_CONTAINER_NUM,
td.INTERNAL_SHIPMENT_NUM,
td.INTERNAL_SHIPMENT_LINE_NUM,
td.INTERNAL_SHIP_ALLOC_NUM,
td.LAUNCH_NUM,
td.USER_DEF1, 
td.USER_DEF2,
td.USER_DEF3,
td.USER_DEF4,
td.USER_DEF5,
td.USER_DEF6,
td.USER_DEF7,
td.USER_DEF8, 
td.PROCESS_STAMP,
td.USER_STAMP,
td.DATE_TIME_STAMP,
td.PARENT_CONTAINER_NUM,
td.SORT_COMPLETED,
td.LOCATION_CLEARED,
th.TOTE_ID,
th.CONDITION AS TOTE_CONDITION,
th.MARK_FOR_SORTING,
th.USER_ASSIGNED,
case when sc.PARENT_CONTAINER_ID IS NULL then N'<literal:1>' ELSE N'<literal:2>'END AS SORT_LEVEL

from TOTE_DETAIL td
left outer join TOTE_HEADER th on th.OBJECT_ID=td.TOTE_HEADER_ID
left outer join WORK_INSTRUCTION wi on wi.INTERNAL_INSTRUCTION_NUM= td.INTERNAL_INSTRUCTION_NUM
left outer join SHIPPING_CONTAINER sc on sc.INTERNAL_CONTAINER_NUM= td.INTERNAL_CONTAINER_NUM
left outer join SHIPMENT_ALLOC_REQUEST sar on sar.INTERNAL_SHIP_ALLOC_NUM=td.INTERNAL_SHIP_ALLOC_NUM