-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */





CREATE VIEW METADATA_INSIGHT_PROCESS_HISTORY_VIEW
AS
SELECT PH.INTERNAL_ID,
PH.WAREHOUSE,
PH.PROCESS,
PH.ACTION,
PH.ACTIVITY_DATE_TIME AS PROCESS_HISTORY_ACTIVITY_DATE_TIME,
PH.IDENTIFIER1,
PH.IDENTIFIER2,
PH.IDENTIFIER3,
PH.IDENTIFIER4,
PH.MESSAGE,
PH.USER_DEF1 AS UDPROCESSHISTORY1,
PH.USER_DEF2 AS UDPROCESSHISTORY2,
PH.USER_DEF3 AS UDPROCESSHISTORY3,
PH.USER_DEF4 AS UDPROCESSHISTORY4,
PH.USER_DEF5 AS UDPROCESSHISTORY5,
PH.USER_DEF6 AS UDPROCESSHISTORY6,
PH.USER_DEF7 AS UDPROCESSHISTORY7,
PH.USER_DEF8 AS UDPROCESSHISTORY8,
PH.USER_STAMP AS PROCESS_HISTORY_USER_STAMP,
PH.PROCESS_STAMP ,
PH.DATE_TIME_STAMP 
 FROM PROCESS_HISTORY PH