-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */





	

CREATE VIEW METADATA_INSIGHT_PUTAWAYGROUP_VIEW
AS
select 	
	PG.CLOSED,
	PG.GROUP_ID,	
	PG.DATE_TIME_STAMP,
	PG.INTERNAL_GROUP_LOC_NUM,
	PG.INTERNAL_GROUP_NUM,
	PG.PROCESS_STAMP,
	PG.USER_DEF1 AS PUT_GROUP_USERDEF1,
	PG.USER_DEF2 AS PUT_GROUP_USERDEF2,
	PG.USER_DEF3 AS PUT_GROUP_USERDEF3,
	PG.USER_DEF4 AS PUT_GROUP_USERDEF4,
	PG.USER_DEF5 AS PUT_GROUP_USERDEF5,
	PG.USER_DEF6 AS PUT_GROUP_USERDEF6,	
	PG.USER_DEF7 AS PUT_GROUP_USERDEF7,
	PG.USER_DEF8 AS PUT_GROUP_USERDEF8,
	PG.USER_NAME,
	PG.USER_STAMP,
	PG.WAREHOUSE,
	PGL.PUTAWAY_GROUP_LOCATION,
	RC.INTERNAL_REC_CONT_NUM,
	RC.RECEIPT_ID
	FROM PUTAWAY_GROUP PG 
	LEFT OUTER JOIN PUTAWAY_GROUP_LOCATION PGL ON PGL.INTERNAL_GROUP_LOC_NUM = PG.INTERNAL_GROUP_LOC_NUM
	LEFT OUTER JOIN RECEIPT_CONTAINER RC  ON PG.INTERNAL_GROUP_NUM = RC.INTERNAL_GROUP_NUM;