-- DOCUMENTATION ONLY: literals/comments removed; do not execute.

CREATE VIEW [dbo].[VIEWER_MRO] AS
select sd.REQUESTED_QTY, item, sd.ERP_ORDER, ACTUAL_SHIP_DATE_TIME, sh.SHIP_TO_ADDRESS1, sh.SHIP_TO_ADDRESS2, SHIP_TO_CITY, SHIP_TO_STATE, SHIP_TO_POSTAL_CODE, SHIP_TO_COUNTRY, INTERFACED_DATE
from AR_SHIPMENT_HEADER sh inner join AR_SHIPMENT_DETAIL sd on sh.INTERNAL_SHIPMENT_NUM = sd.INTERNAL_SHIPMENT_NUM