-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */





CREATE VIEW METADATA_INSIGHT_QUALITY_HISTORY_VIEW
AS
SELECT QH.INTERNAL_ID,
QH.warehouse AS WAREHOUSE,
QH.USER_NAME,
QH.WORK_TYPE,
QH.WORK_GROUP,
QH.WORK_TEAM,
QH.ACTIVITY_DATE_TIME AS QUALITY_HISTORY_INSIGHT_ACTIVITY_DATE_TIME,
QH.REFERENCE_TYPE,
QH.REFERENCE_LINE_NUM,
QH.REFERENCE_ORDER,
QH.INTERNAL_NUM,
QH.SHIPMENT_DTL_PICK_LIST_ID ,
QH.WORK_INSTRUCTION_NUM ,
QH.COMPANY,
QH.ITEM,
QH.REASON_CODE,
QH.USER_DEF1 AS UDQUALITYHISTORY1 ,
QH.USER_DEF2 AS UDQUALITYHISTORY2 ,
QH.USER_DEF3 AS UDQUALITYHISTORY3 ,
QH.USER_DEF4 AS UDQUALITYHISTORY4 ,
QH.USER_DEF5 AS UDQUALITYHISTORY5 ,
QH.USER_DEF6 AS UDQUALITYHISTORY6 ,
QH.USER_DEF7 AS UDQUALITYHISTORY7 ,
QH.USER_DEF8 AS UDQUALITYHISTORY8 ,
QH.USER_STAMP AS PROCESS_HISTORY_USER_STAMP,
QH.PROCESS_STAMP ,
QH.DATE_TIME_STAMP 
FROM QUALITY_HISTORY QH