-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */









CREATE PROCEDURE wm_RItem08
	@Item nvarchar(50),
	@Company nvarchar(25)
AS
	SELECT ITEM.* FROM ITEM, ITEM_CROSS_REFERENCE
	WHERE ITEM.ITEM = ITEM_CROSS_REFERENCE.ITEM
	AND (ITEM.COMPANY = ITEM_CROSS_REFERENCE.COMPANY OR ITEM.COMPANY IS NULL OR ITEM_CROSS_REFERENCE.COMPANY IS NULL)
	AND ITEM_CROSS_REFERENCE.X_REF_ITEM = @Item
	AND  (ITEM_CROSS_REFERENCE.COMPANY = @Company OR ITEM_CROSS_REFERENCE.COMPANY IS NULL OR @Company IS NULL);