-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
-- [comment omitted]
-- [comment omitted]


/* [comment omitted] */






-- [comment omitted]


CREATE PROCEDURE MetaTrans_ViewAccessorials(
@username nvarchar(30),
@culture nvarchar(10),
@internalNum int,
@internalNumType nvarchar(100))
AS

if(UPPER(@internalNumType) = N'<literal:1>')
BEGIN
	-- [comment omitted]
	SELECT 
	N'<literal:2>' AS N'<literal:3>',
    N'<literal:4>' AS N'<literal:5>',
	N'<literal:6>' as AccessorialsTemplate,
	N'<literal:7>' as EditAccessorialsTemplate,
	N'<literal:8>' as EditAccessorialsSubTemplate,		
	SHIPMENT_ID as Id, 
	ISNULL(CARRIER, N'<literal:9>') as Carrier, 
	ISNULL(CARRIER_SERVICE, N'<literal:10>') as CarrierService, 
	ISNULL(COMPANY, N'<literal:11>') as Company, 
	ISNULL((select DESCRIPTION from GENERIC_CONFIG_DETAIL where RECORD_TYPE=N'<literal:12>' and IDENTIFIER=FREIGHT_TERMS), N'<literal:13>') as FreightTerms, 
	@internalNum as InternalNum,
	@internalNumType as InternalNumType,
	WAREHOUSE as Warehouse
	FROM SHIPMENT_HEADER WHERE INTERNAL_SHIPMENT_NUM=@internalNum;
	
	-- [comment omitted]
	IF EXISTS(SELECT TOP 1 1 FROM SHIPMENT_ACCESSORIALS WHERE INTERNAL_NUM = @internalNum)
	BEGIN
		SELECT 
		N'<literal:14>' AS N'<literal:15>',
		ROW_NUMBER() OVER (ORDER BY (select N'<literal:16>')) AS N'<literal:17>',
		N'<literal:18>' as N'<literal:19>',
		SHIPMENT_ACCESSORIALS.OBJECT_ID as ObjectId,
		ACCESSORIAL_DETAIL.ACCESSORIAL_CODE as Code, 
		ACCESSORIAL_DETAIL.ACCESSORIAL_SUB_CODE AS SubCode, 
		ACCESSORIAL_HEADER.DESCRIPTION AS HeaderDesc,
		ACCESSORIAL_DETAIL.DESCRIPTION AS DetailDesc,
		ACCESSORIAL_DETAIL.OBJECT_ID AS DetailObjectId,
		CASE WHEN (UPPER(SHIPMENT_ACCESSORIALS.VALUE) = N'<literal:20>' OR UPPER(SHIPMENT_ACCESSORIALS.VALUE) = N'<literal:21>' )THEN UPPER(SHIPMENT_ACCESSORIALS.VALUE) ELSE SHIPMENT_ACCESSORIALS.VALUE END AS Value
		FROM 
		ACCESSORIAL_HEADER 
		INNER JOIN
		ACCESSORIAL_DETAIL ON ACCESSORIAL_HEADER.OBJECT_ID = ACCESSORIAL_DETAIL.HEADER_ID
		INNER JOIN 
		SHIPMENT_ACCESSORIALS ON ACCESSORIAL_DETAIL.OBJECT_ID = SHIPMENT_ACCESSORIALS.ACCESSORIAL_DETAIL_ID
		WHERE INTERNAL_NUM = @internalNum AND SHIPMENT_LEVEL= N'<literal:22>'
		GROUP BY ACCESSORIAL_DETAIL.ACCESSORIAL_CODE, ACCESSORIAL_DETAIL.ACCESSORIAL_SUB_CODE,ACCESSORIAL_HEADER.DESCRIPTION, ACCESSORIAL_DETAIL.DESCRIPTION, SHIPMENT_ACCESSORIALS.VALUE, ACCESSORIAL_DETAIL.OBJECT_ID, SHIPMENT_ACCESSORIALS.OBJECT_ID
	END
END
ELSE
BEGIN
	-- [comment omitted]
	SELECT 
	N'<literal:23>' AS N'<literal:24>',
    N'<literal:25>' AS N'<literal:26>',
	N'<literal:27>' as AccessorialsTemplate,	
	N'<literal:28>' as EditAccessorialsTemplate,	
	N'<literal:29>' as EditAccessorialsSubTemplate,	
	SHIPPING_CONTAINER.CONTAINER_ID as Id, 
	ISNULL(SHIPMENT_HEADER.CARRIER, N'<literal:30>') as Carrier, 
	ISNULL(SHIPMENT_HEADER.CARRIER_SERVICE, N'<literal:31>') as CarrierService, 
	ISNULL(SHIPMENT_HEADER.COMPANY, N'<literal:32>') as Company, 
	ISNULL((select DESCRIPTION from GENERIC_CONFIG_DETAIL where RECORD_TYPE=N'<literal:33>' and IDENTIFIER=SHIPMENT_HEADER.FREIGHT_TERMS), N'<literal:34>') as FreightTerms, 
	@internalNum as InternalNum,
	@internalNumType as InternalNumType,
	SHIPMENT_HEADER.WAREHOUSE as Warehouse
	FROM SHIPPING_CONTAINER INNER JOIN SHIPMENT_HEADER ON SHIPPING_CONTAINER.INTERNAL_SHIPMENT_NUM = SHIPMENT_HEADER.INTERNAL_SHIPMENT_NUM
	WHERE INTERNAL_CONTAINER_NUM=@internalNum;
	
	-- [comment omitted]
	IF EXISTS(SELECT TOP 1 1 FROM SHIPMENT_ACCESSORIALS WHERE INTERNAL_NUM = @internalNum)
	BEGIN
		SELECT 
		N'<literal:35>' AS N'<literal:36>',
		ROW_NUMBER() OVER (ORDER BY (select N'<literal:37>')) AS N'<literal:38>',
		N'<literal:39>' as N'<literal:40>',
		SHIPMENT_ACCESSORIALS.OBJECT_ID as ObjectId,
		ACCESSORIAL_DETAIL.ACCESSORIAL_CODE as Code, 
		ACCESSORIAL_DETAIL.ACCESSORIAL_SUB_CODE AS SubCode, 
		ACCESSORIAL_HEADER.DESCRIPTION AS HeaderDesc,
		ACCESSORIAL_DETAIL.DESCRIPTION AS DetailDesc,
		ACCESSORIAL_DETAIL.OBJECT_ID AS DetailObjectId,
		CASE WHEN (UPPER(SHIPMENT_ACCESSORIALS.VALUE) = N'<literal:41>' OR UPPER(SHIPMENT_ACCESSORIALS.VALUE) = N'<literal:42>' )THEN UPPER(SHIPMENT_ACCESSORIALS.VALUE) ELSE SHIPMENT_ACCESSORIALS.VALUE END AS Value
		FROM 
		ACCESSORIAL_HEADER 
		INNER JOIN
		ACCESSORIAL_DETAIL ON ACCESSORIAL_HEADER.OBJECT_ID = ACCESSORIAL_DETAIL.HEADER_ID
		INNER JOIN
		SHIPMENT_ACCESSORIALS ON ACCESSORIAL_DETAIL.OBJECT_ID = SHIPMENT_ACCESSORIALS.ACCESSORIAL_DETAIL_ID
		WHERE INTERNAL_NUM = @internalNum AND SHIPMENT_LEVEL= N'<literal:43>'
		GROUP BY ACCESSORIAL_DETAIL.ACCESSORIAL_CODE, ACCESSORIAL_DETAIL.ACCESSORIAL_SUB_CODE, ACCESSORIAL_HEADER.DESCRIPTION, ACCESSORIAL_DETAIL.DESCRIPTION, SHIPMENT_ACCESSORIALS.VALUE, ACCESSORIAL_DETAIL.OBJECT_ID, SHIPMENT_ACCESSORIALS.OBJECT_ID
	END
END
