-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */










CREATE procedure WRK_UpdateWorkInstruction(
	@CycleCount nchar(1),
	@InventoryAtPd nchar(1),
	@InventoryTracking nchar(1),

	@AgingDateTime nvarchar(25),
	@DateTimeStamp nvarchar(25),
	@EndDateTime nvarchar(25),
	@StartDateTime nvarchar(25),

	@ConvertedQty numeric(19,5),
	@CycleCountGroupNum numeric(9),
	@ErpOrderLineNum numeric(19,5),
	@EstimatedTime numeric(9),
	@FromQty numeric(19,5),
	@InternalContainerNum numeric(9),
	@InternalCountNum numeric(9),
	@InternalLineNum numeric(9),
	@InternalNum numeric(9),
	@InternalReqNum numeric(9),
	@LaunchNum numeric(9),
	@NumberOfChildren numeric(9),
	@ParentContainerNum numeric(9),
	@Priority numeric(3),
	@Quantity numeric(19,5),
	@Sequence numeric(5),
	@ToQty numeric(19,5),
	@TotalValue numeric(28,5),
	@TotalVolume numeric(28,5),
	@TotalWeight numeric(28,5),
	@UserDef7 numeric(19,5),
	@UserDef8 numeric(19,5),

	@Account nvarchar(25),
	@AllocationZone nvarchar(25),
	@Company nvarchar(25),
	@CompletedByUser nvarchar(30),
	@Condition nvarchar(25),
	@ContainerId nvarchar(25),
	@ConvertedQtyUm nvarchar(25),
	@EquipmentLoc nvarchar(25),
	@ErpOrder nvarchar(25),
	@FromCheckDig nvarchar(25),
	@FromLoc nvarchar(25),
	@FromTemplField1 nvarchar(25),
	@FromTemplField2 nvarchar(25),
	@FromTemplField3 nvarchar(25),
	@FromTemplField4 nvarchar(25),
	@FromTemplField5 nvarchar(25),
	@FromWhs nvarchar(25),
	@FromWorkZone nvarchar(25),
	@GroupNum nvarchar(50),
	@HoldCode nvarchar(50),
	@IncomingPdLoc nvarchar(25),
	@InstructionType nvarchar(25),
	@InternalNumType nvarchar(25),
	@Item nvarchar(50),
	@ItemDesc nvarchar(100),
	@LocatingZone nvarchar(25),
	@Lot nvarchar(25),
	@MessageId nvarchar(25),
	@OutgoingPdLoc nvarchar(25),
	@ParentContainerId nvarchar(25),
	@PickListId nvarchar(25),
	@ProcessStamp nvarchar(100),
	@QuantityUm nvarchar(25),
	@ReferenceId nvarchar(25),
	@ReferenceType nvarchar(25),
	@RelatedWorkUnit nvarchar(50),
	@TeamAssigned nvarchar(50),
	@ToCheckDig nvarchar(25),
	@ToLoc nvarchar(25),
	@ToTemplField1 nvarchar(25),
	@ToTemplField2 nvarchar(25),
	@ToTemplField3 nvarchar(25),
	@ToTemplField4 nvarchar(25),
	@ToTemplField5 nvarchar(25),
	@ToWhs nvarchar(25),
	@ToWorkZone nvarchar(25),
	@TransportContId nvarchar(25),
	@UserAssigned nvarchar(30),
	@UserDef1 nvarchar(25),
	@UserDef2 nvarchar(25),
	@UserDef3 nvarchar(25),
	@UserDef4 nvarchar(25),
	@UserDef5 nvarchar(25),
	@UserDef6 nvarchar(25),
	@UserStamp nvarchar(30),
	@VolumeUm nvarchar(25),
	@WeightUm nvarchar(25),
	@WorkGroup nvarchar(25),
	@WorkType nvarchar(25),
	@workUnit nvarchar(50),
	@logisticsUnit nvarchar(50),
	@parentLogisticsUnit nvarchar(50),
	@treeUnit numeric(9),
	@treeUnitId nvarchar(25),
	@fromLocInvAttributesId numeric(9),
	@toLocInvAttributesId numeric(9),
	@SrcIdentifier nvarchar(50),
	@MinWorkZoneSeq numeric(4),
	@MaxWorkZoneSeq numeric(4))
as
	update work_instruction set

		cycle_count = @CycleCount,
		inventory_at_pd = @InventoryAtPd,
		inventory_tracking = @InventoryTracking,

		aging_date_time = case when @AgingDateTime is null then null else convert(datetime, @AgingDateTime, 20) end,
		date_time_stamp = case when @DateTimeStamp is null then null else convert(datetime, @DateTimeStamp, 20) end,
		end_date_time = case when @EndDateTime is null then null else convert(datetime, @EndDateTime, 20) end,
		start_date_time = case when @StartDateTime is null then null else convert(datetime, @StartDateTime, 20) end,

		converted_qty = @ConvertedQty,
		cycle_count_group_num = @CycleCountGroupNum,
		erp_order_line_num = @ErpOrderLineNum,
		estimated_time = @EstimatedTime,
		from_qty = @FromQty,
		internal_container_num = @InternalContainerNum,
		internal_count_num = case when @InternalCountnum > 0 then @InternalCountNum else null end,
		internal_line_num = @InternalLineNum,
		internal_num = @InternalNum,
		internal_req_num = @InternalReqNum,
		launch_num = @LaunchNum,
		number_of_children = @NumberOfChildren,
		parent_container_num = @ParentContainerNum,
		priority = @Priority,
		quantity = @Quantity,
		sequence = @Sequence,
		to_qty = @ToQty,
		total_value = @TotalValue,
		total_volume = @TotalVolume,
		total_weight= @TotalWeight,
		user_def7 = @UserDef7,
		user_def8 = @UserDef8,

		account = @Account,
		allocation_zone = @AllocationZone,
		company = @Company,
		completed_by_user = @CompletedByUser,
		condition = @Condition,
		container_id = @ContainerId,
		converted_qty_um = @ConvertedQtyUm,
		equipment_loc = @EquipmentLoc,
		erp_order = @ErpOrder,
		from_check_dig = @FromCheckDig,
		from_loc = @FromLoc,
		from_templ_field1 = @FromTemplField1,
		from_templ_field2 = @FromTemplField2,
		from_templ_field3 = @FromTemplField3,
		from_templ_field4 = @FromTemplField4,
		from_templ_field5 = @FromTemplField5,
		from_whs = @FromWhs,
		from_work_zone = @FromWorkZone,
		group_num = @GroupNum,
		hold_code = @HoldCode,
		incoming_pd_loc = @IncomingPdLoc,
		internal_num_type = @InternalNumType,
		item = @Item,
		item_desc = @ItemDesc,
		locating_zone = @LocatingZone,
		lot = @Lot,
		message_id = @MessageId,
		outgoing_pd_loc = @OutgoingPdLoc,
		parent_container_id = @ParentContainerId,
		pick_list_id = @PickListId,
		process_stamp = @ProcessStamp,
		quantity_um = @QuantityUm,
		reference_id = @ReferenceId,
		reference_type = @ReferenceType,
		related_work_unit = @RelatedWorkUnit,
		team_assigned = @TeamAssigned,
		to_check_dig = @ToCheckDig,
		to_loc = @ToLoc,
		to_templ_field1 = @ToTemplField1,
		to_templ_field2 = @ToTemplField2,
		to_templ_field3 = @ToTemplField3,
		to_templ_field4 = @ToTemplField4,
		to_templ_field5 = @ToTemplField5,
		to_whs = @ToWhs,
		to_work_zone = @ToWorkZone,
		transport_cont_id = @TransportContId,
		user_assigned = @UserAssigned,
		user_def1 = @UserDef1,
		user_def2 = @UserDef2,
		user_def3 = @UserDef3,
		user_def4 = @UserDef4,
		user_def5 = @UserDef5,
		user_def6 = @UserDef6,
		user_stamp = @UserStamp,
		volume_um = @VolumeUm,
		weight_um = @WeightUm,
		work_group = @WorkGroup,
		work_type = @WorkType,
		logistics_unit = @logisticsUnit,
		parent_logistics_unit = @parentLogisticsUnit,
		tree_unit = @treeUnit,
		tree_unit_id = @treeUnitId ,
		from_loc_inv_attributes_id = case when @fromLocInvAttributesId > 0 then @fromLocInvAttributesId else null end,
		to_loc_inv_attributes_id = case when @toLocInvAttributesId > 0 then @toLocInvAttributesId else null end,
		src_identifier = @SrcIdentifier,
		min_work_zone_seq = @MinWorkZoneSeq,
		max_work_zone_seq = @MaxWorkZoneSeq
		where work_unit = @WorkUnit and instruction_type = N'<literal:1>'


