-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */





CREATE PROCEDURE WRK_UpdateWorkInstructionForSystemDirectedWorkUnitSelection(
@workunit nvarchar(50),
@groupNumber nvarchar(50)
)  
AS

IF(ISNULL(@WORKUNIT, N'<literal:1>') != N'<literal:2>')
	BEGIN
	
	-- [comment omitted]
	UPDATE WORK_INSTRUCTION
	SET  GROUP_NUM = @GROUPNUMBER
		,SEQUENCE = 0 
		WHERE WORK_UNIT = @WORKUNIT;
	
	-- [comment omitted]
	UPDATE WORK_INSTRUCTION SET 
	SEQUENCE =( SELECT MAX(SEQUENCE) 
	FROM WORK_INSTRUCTION
	WHERE GROUP_NUM = @GROUPNUMBER AND INTERNAL_NUM_TYPE =N'<literal:3>'
	)
	+ SORTEDWORKINSTRUCTIONS.SEQUENCENUM 
	FROM WORK_INSTRUCTION WI
	INNER JOIN 
	( 	SELECT  
		INTERNAL_INSTRUCTION_NUM
		, ROW_NUMBER()
			OVER ( ORDER BY  INTERNAL_INSTRUCTION_NUM ASC )  AS SEQUENCENUM 
		FROM  WORK_INSTRUCTION  
		WHERE  GROUP_NUM = @GROUPNUMBER  AND SEQUENCE = 0 AND INSTRUCTION_TYPE =N'<literal:4>' 
	)SORTEDWORKINSTRUCTIONS ON SORTEDWORKINSTRUCTIONS.INTERNAL_INSTRUCTION_NUM = WI.INTERNAL_INSTRUCTION_NUM AND WI.INTERNAL_NUM_TYPE =N'<literal:5>'

	END