-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */





	CREATE VIEW METADATA_INSIGHT_TPM_ORDER_LINE_STATUS_VIEW
	AS	
	SELECT 	
	OD.ERP_ORDER_LINE_NUM,
	OD.ITEM,
	OD.ITEM_DESC,
	OD.CUSTOMER,
	OD.INTERNAL_ORDER_NUM,
	OD.INTERNAL_ORDER_DTL_NUM,
	OH.ORDER_TYPE,	
	COALESCE(OD.OPEN_QTY, 0) OPEN_QTY,
	COALESCE(OD.INITIAL_QTY, 0) INITIAL_QTY,
	COALESCE(OD.SHIPPED_QTY, 0) SHIPPED_QTY,  
	OH.ERP_ORDER,
	OD.WAREHOUSE,
	OD.COMPANY,
	OD.CUSTOMER_NAME,
	OD.SHIP_TO,
	OD.ORDER_DATE,
	OD.CONDITION
	FROM ORDER_HEADER OH
	INNER JOIN ORDER_DETAIL OD
	ON OD.INTERNAL_ORDER_NUM=OH.INTERNAL_ORDER_NUM;