-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */









CREATE PROCEDURE MOVECLS_MineMovementClassAnalysisData
(	@Warehouse nvarchar(25),
	@Days int = 90,
	@Permanent nchar(1),
	@IncludeArchivedData nchar(1)
)
AS

SET NOCOUNT ON;

DECLARE	@DateFrom	DATETIME
DECLARE @DateTo		DATETIME
DECLARE	@stErrorMsg NVARCHAR(2000)
DECLARE @rowEffected Numeric(9,0)

SELECT @DateTo = DATEADD(dd, 1, DATEDIFF(dd, 0, GETUTCDATE()))
SELECT @DateFrom = @DateTo - @Days

-- [comment omitted]
if (@Warehouse is null)
begin
	set @stErrorMsg = N'<literal:1>';
	return -1;
end

-- [comment omitted]
DELETE FROM MOVEMENT_CLASS_ANALYSIS where WAREHOUSE = @Warehouse


IF UPPER(@PERMANENT) = N'<literal:2>' 
BEGIN
	INSERT INTO MOVEMENT_CLASS_ANALYSIS (ITEM, COMPANY, WAREHOUSE, LOCATION, TOTAL_QUANTITY, QUANTITY_UM, ITEM_CLASS, NUMBER_OF_HITS, NUMBER_OF_DAYS, DATE_TIME_STAMP, USER_STAMP,			PROCESS_STAMP)
	SELECT ITEM, COMPANY, WAREHOUSE, LOCATION,  sum(TOTAL_QUATITY) AS TOTAL_QUATITY, QUANTITY_UM, ITEM_CLASS,SUM(NUMBER_OF_HITS), @Days , GETUTCDATE(),N'<literal:3>',N'<literal:4>'
	FROM 
	(		 
		SELECT TH.ITEM, TH.COMPANY, TH.WAREHOUSE, TH.LOCATION,  sum(TH.QUANTITY) AS TOTAL_QUATITY, th.QUANTITY_UM, I.ITEM_CLASS,NUMBER_OF_HITS
		FROM ITEM I WITH (NOLOCK) 
		JOIN 
			( 
				SELECT TRANSACTION_HISTORY.ITEM, TRANSACTION_HISTORY.COMPANY, TRANSACTION_HISTORY.WAREHOUSE, TRANSACTION_HISTORY.LOCATION, TRANSACTION_HISTORY.QUANTITY_UM,
					sum(TRANSACTION_HISTORY.QUANTITY) as QUANTITY, COUNT(*) as NUMBER_OF_HITS
				FROM TRANSACTION_HISTORY  WITH (NOLOCK) 
				INNER JOIN LOCATION WITH (NOLOCK) 
					ON	LOCATION.LOCATION = TRANSACTION_HISTORY.LOCATION   
					AND LOCATION.WAREHOUSE = TRANSACTION_HISTORY.WAREHOUSE   
					AND LOCATION.LOCATION_CLASS = N'<literal:5>' 
				INNER JOIN LOCATION_INVENTORY LI on TRANSACTION_HISTORY.LOCATION  = LI.LOCATION AND TRANSACTION_HISTORY.WAREHOUSE = LI.WAREHOUSE
					AND ISNULL(LI.LOT,N'<literal:6>') = ISNULL(TRANSACTION_HISTORY.LOT,N'<literal:7>')
				    AND ISNULL(LI.COMPANY,N'<literal:8>') = ISNULL(TRANSACTION_HISTORY.COMPANY,N'<literal:9>')
				WHERE 
					ACTIVITY_DATE_TIME >=  @DateFrom and ACTIVITY_DATE_TIME < @DateTo
					AND DIRECTION = N'<literal:10>'   
					AND TRANSACTION_TYPE IN (40,60,100,130,120,240,250,360)
					and TRANSACTION_HISTORY.WAREHOUSE = @Warehouse
					and ( LI.PERMANENT <> N'<literal:11>')
				 GROUP BY TRANSACTION_HISTORY.ITEM, TRANSACTION_HISTORY.COMPANY, TRANSACTION_HISTORY.WAREHOUSE, TRANSACTION_HISTORY.LOCATION,TRANSACTION_HISTORY.QUANTITY_UM
			) TH  
		ON I.ITEM = TH.ITEM   AND (TH.COMPANY = I.COMPANY OR (TH.COMPANY IS NULL OR I.COMPANY IS NULL))	
		WHERE TH.WAREHOUSE = @WAREHOUSE 
		GROUP BY TH.ITEM,TH.COMPANY, TH.LOCATION,TH.WAREHOUSE, TH.QUANTITY_UM,I.ITEM_CLASS,NUMBER_OF_HITS		
		
	
		UNION
		
		SELECT TH.ITEM, TH.COMPANY, TH.WAREHOUSE, TH.LOCATION,  sum(TH.QUANTITY) AS TOTAL_QUATITY, th.QUANTITY_UM, I.ITEM_CLASS,NUMBER_OF_HITS
		FROM ITEM I WITH (NOLOCK) 
		JOIN 
			( 
				SELECT AR_TRANSACTION_HISTORY.ITEM, AR_TRANSACTION_HISTORY.COMPANY, AR_TRANSACTION_HISTORY.WAREHOUSE, AR_TRANSACTION_HISTORY.LOCATION, AR_TRANSACTION_HISTORY.QUANTITY_UM,
					sum(AR_TRANSACTION_HISTORY.QUANTITY) as QUANTITY, COUNT(*) as NUMBER_OF_HITS
				FROM AR_TRANSACTION_HISTORY  WITH (NOLOCK) 
				INNER JOIN LOCATION WITH (NOLOCK) 
					ON	LOCATION.LOCATION = AR_TRANSACTION_HISTORY.LOCATION   
					AND LOCATION.WAREHOUSE = AR_TRANSACTION_HISTORY.WAREHOUSE   
					AND LOCATION.LOCATION_CLASS = N'<literal:12>' 
				INNER JOIN LOCATION_INVENTORY LI on AR_TRANSACTION_HISTORY.LOCATION  = LI.LOCATION AND AR_TRANSACTION_HISTORY.WAREHOUSE = LI.WAREHOUSE
				    AND ISNULL(LI.LOT,N'<literal:13>') = ISNULL(AR_TRANSACTION_HISTORY.LOT,N'<literal:14>')
				    AND ISNULL(LI.COMPANY,N'<literal:15>') = ISNULL(AR_TRANSACTION_HISTORY.COMPANY,N'<literal:16>')
				WHERE 
					ACTIVITY_DATE_TIME >=  @DateFrom and ACTIVITY_DATE_TIME < @DateTo
					AND DIRECTION = N'<literal:17>'   
					AND TRANSACTION_TYPE IN (40,60,100,130,120,240,250,360)
					and AR_TRANSACTION_HISTORY.WAREHOUSE = @Warehouse
					and ( LI.PERMANENT <> N'<literal:18>')
				 GROUP BY AR_TRANSACTION_HISTORY.ITEM, AR_TRANSACTION_HISTORY.COMPANY, AR_TRANSACTION_HISTORY.WAREHOUSE, AR_TRANSACTION_HISTORY.LOCATION,AR_TRANSACTION_HISTORY.QUANTITY_UM
			) TH  
		ON I.ITEM = TH.ITEM   AND (TH.COMPANY = I.COMPANY OR (TH.COMPANY IS NULL OR I.COMPANY IS NULL))	
		WHERE TH.WAREHOUSE = @WAREHOUSE and @IncludeArchivedData = N'<literal:19>'
		GROUP BY TH.ITEM,TH.COMPANY, TH.LOCATION,TH.WAREHOUSE, TH.QUANTITY_UM,I.ITEM_CLASS,NUMBER_OF_HITS	
				
	) TransactionHistoryData
	GROUP BY ITEM,COMPANY, LOCATION,WAREHOUSE, QUANTITY_UM,ITEM_CLASS		
	
	
	
END
ELSE 
BEGIN


	INSERT INTO MOVEMENT_CLASS_ANALYSIS (ITEM, COMPANY, WAREHOUSE, LOCATION, TOTAL_QUANTITY, QUANTITY_UM, ITEM_CLASS, NUMBER_OF_HITS, NUMBER_OF_DAYS, DATE_TIME_STAMP, USER_STAMP,PROCESS_STAMP)		
	SELECT 	ITEM, COMPANY, WAREHOUSE, LOCATION,  sum(TOTAL_QUATITY) AS TOTAL_QUATITY, QUANTITY_UM, ITEM_CLASS,SUM(NUMBER_OF_HITS), @DAYS , GETUTCDATE(),N'<literal:20>',N'<literal:21>' 
	FROM
	(
		SELECT TH.ITEM, TH.COMPANY, TH.WAREHOUSE, TH.LOCATION,  sum(TH.QUANTITY) AS TOTAL_QUATITY, th.QUANTITY_UM, I.ITEM_CLASS, NUMBER_OF_HITS
		FROM ITEM I WITH (NOLOCK) 
		JOIN 
			( 
				SELECT TRANSACTION_HISTORY.ITEM, TRANSACTION_HISTORY.COMPANY, TRANSACTION_HISTORY.WAREHOUSE, TRANSACTION_HISTORY.LOCATION, QUANTITY_UM,
					sum(TRANSACTION_HISTORY.QUANTITY) as QUANTITY, COUNT(*) as NUMBER_OF_HITS
				FROM TRANSACTION_HISTORY  WITH (NOLOCK) 
				INNER JOIN LOCATION WITH (NOLOCK) 
					ON	LOCATION.LOCATION = TRANSACTION_HISTORY.LOCATION   
					AND LOCATION.WAREHOUSE = TRANSACTION_HISTORY.WAREHOUSE   
					AND LOCATION.LOCATION_CLASS = N'<literal:22>' 
				WHERE 
					ACTIVITY_DATE_TIME >=  @DateFrom and ACTIVITY_DATE_TIME < @DateTo
					AND DIRECTION = N'<literal:23>'   
					AND TRANSACTION_TYPE IN (40,60,100,130,120,240,250,360)
					and TRANSACTION_HISTORY.WAREHOUSE = @Warehouse
				 GROUP BY TRANSACTION_HISTORY.ITEM, TRANSACTION_HISTORY.COMPANY, TRANSACTION_HISTORY.WAREHOUSE, TRANSACTION_HISTORY.LOCATION,QUANTITY_UM
			) TH  
		ON I.ITEM = TH.ITEM   AND (TH.COMPANY = I.COMPANY OR (TH.COMPANY IS NULL OR I.COMPANY IS NULL))		
		WHERE TH.WAREHOUSE = @WAREHOUSE 
		GROUP BY TH.ITEM,TH.COMPANY, TH.LOCATION,TH.WAREHOUSE, TH.QUANTITY_UM,I.ITEM_CLASS,NUMBER_OF_HITS		
		
		UNION
		
		SELECT TH.ITEM, TH.COMPANY, TH.WAREHOUSE, TH.LOCATION,  sum(TH.QUANTITY) AS TOTAL_QUATITY, th.QUANTITY_UM, I.ITEM_CLASS,NUMBER_OF_HITS
		FROM ITEM I WITH (NOLOCK) 
		JOIN 
			( 
				SELECT AR_TRANSACTION_HISTORY.ITEM, AR_TRANSACTION_HISTORY.COMPANY, AR_TRANSACTION_HISTORY.WAREHOUSE, AR_TRANSACTION_HISTORY.LOCATION, QUANTITY_UM,
					sum(AR_TRANSACTION_HISTORY.QUANTITY) as QUANTITY, COUNT(*) as NUMBER_OF_HITS
				FROM AR_TRANSACTION_HISTORY  WITH (NOLOCK) 
				INNER JOIN LOCATION WITH (NOLOCK) 
					ON	LOCATION.LOCATION = AR_TRANSACTION_HISTORY.LOCATION   
					AND LOCATION.WAREHOUSE = AR_TRANSACTION_HISTORY.WAREHOUSE   
					AND LOCATION.LOCATION_CLASS = N'<literal:24>' 
				WHERE 
					ACTIVITY_DATE_TIME >=  @DateFrom and ACTIVITY_DATE_TIME < @DateTo
					AND DIRECTION = N'<literal:25>'   
					AND TRANSACTION_TYPE IN (40,60,100,130,120,240,250,360)
					and AR_TRANSACTION_HISTORY.WAREHOUSE = @Warehouse
				 GROUP BY AR_TRANSACTION_HISTORY.ITEM, AR_TRANSACTION_HISTORY.COMPANY, AR_TRANSACTION_HISTORY.WAREHOUSE, AR_TRANSACTION_HISTORY.LOCATION,QUANTITY_UM
			) TH  
		ON I.ITEM = TH.ITEM   AND (TH.COMPANY = I.COMPANY OR (TH.COMPANY IS NULL OR I.COMPANY IS NULL))		
		WHERE TH.WAREHOUSE = @WAREHOUSE and @IncludeArchivedData = N'<literal:26>'
		GROUP BY TH.ITEM,TH.COMPANY, TH.LOCATION,TH.WAREHOUSE, TH.QUANTITY_UM,I.ITEM_CLASS,NUMBER_OF_HITS		
	) TransactionHistoryData
	GROUP BY ITEM,COMPANY, LOCATION,WAREHOUSE, QUANTITY_UM,ITEM_CLASS		
END

Select  @rowEffected = @@ROWCOUNT 

IF UPPER(@PERMANENT) = N'<literal:27>' 
BEGIN
INSERT INTO MOVEMENT_CLASS_ANALYSIS (ITEM, COMPANY, WAREHOUSE, LOCATION, TOTAL_QUANTITY, QUANTITY_UM, ITEM_CLASS, NUMBER_OF_HITS, NUMBER_OF_DAYS, DATE_TIME_STAMP, USER_STAMP,PROCESS_STAMP)		
SELECT 	li.ITEM, li.COMPANY, li.WAREHOUSE, li.LOCATION,  sum(ON_HAND_QTY) AS TOTAL_QUATITY, QUANTITY_UM, ITEM_CLASS, 0 , @Days , GETUTCDATE(),N'<literal:28>',N'<literal:29>' 
from 
	location_inventory li
	inner join location loc on (loc.location =li.LOCATION and loc.warehouse =li.warehouse)
	left join item on (item.item = li.item and (item.COMPANY = li.COMPANY OR (item.COMPANY IS NULL and li.COMPANY IS NULL))) 
where 
loc.LOCATION_CLASS = N'<literal:30>'
and loc.warehouse = @Warehouse
and (li.PERMANENT <> N'<literal:31>')
and not exists (select N'<literal:32>' from MOVEMENT_CLASS_ANALYSIS mca where mca.warehouse = li.warehouse and mca.LOCATION = li.LOCATION AND mca.ITEM = li.ITEM and (mca.COMPANY = li.COMPANY OR (mca.COMPANY IS NULL AND li.COMPANY IS NULL)) )
group  by  
li.ITEM, li.COMPANY, li.WAREHOUSE, li.LOCATION, QUANTITY_UM, ITEM_CLASS
having sum(ON_HAND_QTY) >0

Select  @rowEffected = @rowEffected + @@ROWCOUNT

END
ELSE
BEGIN
INSERT INTO MOVEMENT_CLASS_ANALYSIS (ITEM, COMPANY, WAREHOUSE, LOCATION, TOTAL_QUANTITY, QUANTITY_UM, ITEM_CLASS, NUMBER_OF_HITS, NUMBER_OF_DAYS, DATE_TIME_STAMP, USER_STAMP,PROCESS_STAMP)		
SELECT 	li.ITEM, li.COMPANY, li.WAREHOUSE, li.LOCATION,  sum(ON_HAND_QTY) AS TOTAL_QUATITY, QUANTITY_UM, ITEM_CLASS, 0 , @Days , GETUTCDATE(),N'<literal:33>',N'<literal:34>' 
from 
	location_inventory li
	inner join location loc on (loc.location =li.LOCATION and loc.warehouse =li.warehouse)
	left join item on (item.item = li.item and (item.COMPANY = li.COMPANY OR (item.COMPANY IS NULL and li.COMPANY IS NULL))) 
where 
loc.LOCATION_CLASS = N'<literal:35>'
and loc.warehouse = @Warehouse

and not exists (select N'<literal:36>' from MOVEMENT_CLASS_ANALYSIS mca where mca.warehouse = li.warehouse and mca.LOCATION = li.LOCATION AND mca.ITEM = li.ITEM and (mca.COMPANY = li.COMPANY OR (mca.COMPANY IS NULL AND li.COMPANY IS NULL)) )
group  by  
li.ITEM, li.COMPANY, li.WAREHOUSE, li.LOCATION, QUANTITY_UM, ITEM_CLASS
having sum(ON_HAND_QTY) >0

Select  @rowEffected = @rowEffected + @@ROWCOUNT

END

SET NOCOUNT OFF
if (@@ERROR <> 0) select -1 else select @rowEffected
