-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */








	

CREATE PROCEDURE wm_RShippingContainer06
	@InternalContainerNum numeric(9),
	@InterfaceLinkID numeric(9)
AS
	IF(@InterfaceLinkID =0)	
	SELECT	SC.*, SD.ERP_ORDER, SD.ERP_ORDER_LINE_NUM, MOP.MULTI_ORDER_PALLET_ID
	FROM SHIPPING_CONTAINER SC
	INNER JOIN  SHIPMENT_DETAIL SD ON SC.INTERNAL_SHIPMENT_LINE_NUM = SD.INTERNAL_SHIPMENT_LINE_NUM
	LEFT OUTER JOIN MULTI_ORDER_PALLET MOP on SC.INTERNAL_MOP_NUMBER = MOP.INTERNAL_MOP_NUMBER
	WHERE 
		PARENT = @InternalContainerNum
		AND CONTAINER_TYPE = N'<literal:1>'      
	UNION
	SELECT	SC.*, SD.ERP_ORDER, SD.ERP_ORDER_LINE_NUM, MOP.MULTI_ORDER_PALLET_ID
	FROM SHIPPING_CONTAINER SC
	INNER JOIN  SHIPMENT_DETAIL SD ON SC.INTERNAL_SHIPMENT_LINE_NUM = SD.INTERNAL_SHIPMENT_LINE_NUM
	LEFT OUTER JOIN MULTI_ORDER_PALLET MOP on SC.INTERNAL_MOP_NUMBER = MOP.INTERNAL_MOP_NUMBER
	WHERE 
		INTERNAL_CONTAINER_NUM = @InternalContainerNum
		AND SC.ITEM IS NOT NULL
		AND CONTAINER_TYPE <> N'<literal:2>';
	ELSE
	SELECT	UC.*, SD.ERP_ORDER, SD.ERP_ORDER_LINE_NUM, MOP.MULTI_ORDER_PALLET_ID
	FROM UPLOAD_ORDER_CONTAINER UC
	INNER JOIN  SHIPMENT_DETAIL SD ON UC.INTERNAL_SHIPMENT_LINE_NUM = SD.INTERNAL_SHIPMENT_LINE_NUM
	LEFT OUTER JOIN MULTI_ORDER_PALLET MOP on UC.INTERNAL_MOP_NUMBER = MOP.INTERNAL_MOP_NUMBER
	WHERE 
		INTERFACE_PARENT_LINK_ID = @InternalContainerNum
		AND CONTAINER_TYPE = N'<literal:3>'  
		AND INTERFACE_LINK_ID = @InterfaceLinkID    
	UNION
	SELECT	UC.*, SD.ERP_ORDER, SD.ERP_ORDER_LINE_NUM, MOP.MULTI_ORDER_PALLET_ID
	FROM UPLOAD_ORDER_CONTAINER UC
	INNER JOIN  SHIPMENT_DETAIL SD ON UC.INTERNAL_SHIPMENT_LINE_NUM = SD.INTERNAL_SHIPMENT_LINE_NUM
	LEFT OUTER JOIN MULTI_ORDER_PALLET MOP on UC.INTERNAL_MOP_NUMBER = MOP.INTERNAL_MOP_NUMBER
	WHERE 
		INTERNAL_CONTAINER_NUM = @InternalContainerNum
		AND UC.ITEM IS NOT NULL
		AND CONTAINER_TYPE <> N'<literal:4>'
		AND INTERFACE_LINK_ID = @InterfaceLinkID;

