-- DOCUMENTATION ONLY: literals/comments removed; do not execute.

	

CREATE PROCEDURE NNR_GETNEXTGROUPNUMBER
AS
BEGIN
	DECLARE @IROWCOUNT INTEGER;
	DECLARE @NEXTNUM nvarchar(25);
	
	SET @IROWCOUNT = 1;
	
	WHILE @IROWCOUNT > 0
	BEGIN
		EXEC NNR_GETNEXTNUMBER N'<literal:1>', @NEXTNUM OUT;

		SELECT TOP 1 @IROWCOUNT = COUNT(GROUP_NUM) FROM WORK_INSTRUCTION
		WHERE
		GROUP_NUM = @NEXTNUM;

	END
	
SELECT CAST(@NEXTNUM AS NUMERIC) AS NEXTNUMVALUE;
END

