-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */











CREATE PROCEDURE WTH_DeactivateShippingLoadWork(
	@loadNum numeric(9))
AS  
BEGIN

SET NOCOUNT ON;  
  
INSERT INTO IA_WORK_INSTRUCTION(
	INTERNAL_INSTRUCTION_NUM,
	INSTRUCTION_TYPE,
	PARENT_INSTR,
	WORK_UNIT,
	SEQUENCE,
	LAUNCH_NUM,
	PRIORITY,
	CONDITION,
	HOLD_CODE,
	REFERENCE_ID,
	REFERENCE_TYPE,
	ERP_ORDER,
	ERP_ORDER_LINE_NUM,
	INTERNAL_NUM,
	INTERNAL_LINE_NUM,
	PICK_LIST_ID,
	ACCOUNT,
	WORK_TYPE,
	WORK_GROUP,
	COMPANY,
	ITEM,
	ITEM_DESC,
	FROM_QTY,
	QUANTITY,
	TO_QTY,
	QUANTITY_UM,
	TOTAL_WEIGHT,
	WEIGHT_UM,
	TOTAL_VOLUME,
	FROM_WHS,
	TO_WHS,
	VOLUME_UM,
	TOTAL_VALUE,
	FROM_LOC,
	TO_LOC,
	FROM_CHECK_DIG,
	TO_CHECK_DIG,
	FROM_WORK_ZONE,
	TO_WORK_ZONE,
	COMPLETED_BY_USER,
	TEAM_ASSIGNED,
	USER_ASSIGNED,
	ESTIMATED_TIME,
	AGING_DATE_TIME,
	START_DATE_TIME,
	END_DATE_TIME,
	NUMBER_OF_CHILDREN,
	MESSAGE_ID,
	LOT,
	USER_DEF1,
	USER_DEF2,
	USER_DEF3,
	USER_DEF4,
	USER_DEF5,
	USER_DEF6,
	USER_DEF7,
	USER_DEF8,
	USER_STAMP,
	PROCESS_STAMP,
	DATE_TIME_STAMP,
	EQUIPMENT_LOC,
	CONVERTED_QTY,
	CONVERTED_QTY_UM,
	INTERNAL_NUM_TYPE,
	INTERNAL_REQ_NUM,
	INVENTORY_TRACKING,
	LOCATING_ZONE,
	FROM_TEMPL_FIELD1,
	FROM_TEMPL_FIELD2,
	FROM_TEMPL_FIELD3,
	FROM_TEMPL_FIELD4,
	FROM_TEMPL_FIELD5,
	TO_TEMPL_FIELD1,
	TO_TEMPL_FIELD2,
	TO_TEMPL_FIELD3,
	TO_TEMPL_FIELD4,
	TO_TEMPL_FIELD5,
	ALLOCATION_ZONE,
	INTERNAL_CONTAINER_NUM,
	CONTAINER_ID,
	PARENT_CONTAINER_NUM,
	PARENT_CONTAINER_ID,
	INTERNAL_COUNT_NUM,
	CYCLE_COUNT,
	RELATED_WORK_UNIT,
	TRANSPORT_CONT_ID,
	GROUP_NUM,
	OUTGOING_PD_LOC,
	INCOMING_PD_LOC,
	INVENTORY_AT_PD,
	CYCLE_COUNT_GROUP_NUM,
	ASSIGNMENT_ID,
	LOGISTICS_UNIT,
	PARENT_LOGISTICS_UNIT,
	TREE_UNIT,
	TREE_UNIT_ID,
	LOCKED,
	SRC_IDENTIFIER)  
(SELECT WI.INTERNAL_INSTRUCTION_NUM  
      ,WI.INSTRUCTION_TYPE  
      ,WI.PARENT_INSTR  
      ,WI.WORK_UNIT  
      ,WI.SEQUENCE  
      ,WI.LAUNCH_NUM  
      ,WI.PRIORITY  
      ,WI.CONDITION  
      ,WI.HOLD_CODE  
      ,WI.REFERENCE_ID  
      ,WI.REFERENCE_TYPE  
      ,WI.ERP_ORDER  
      ,WI.ERP_ORDER_LINE_NUM  
      ,WI.INTERNAL_NUM  
      ,WI.INTERNAL_LINE_NUM  
      ,WI.PICK_LIST_ID  
      ,WI.ACCOUNT  
      ,WI.WORK_TYPE  
      ,WI.WORK_GROUP  
      ,WI.COMPANY  
      ,WI.ITEM  
      ,WI.ITEM_DESC  
      ,WI.FROM_QTY  
      ,WI.QUANTITY  
      ,WI.TO_QTY  
      ,WI.QUANTITY_UM  
      ,WI.TOTAL_WEIGHT  
      ,WI.WEIGHT_UM  
      ,WI.TOTAL_VOLUME  
      ,WI.FROM_WHS  
      ,WI.TO_WHS  
      ,WI.VOLUME_UM  
      ,WI.TOTAL_VALUE  
      ,WI.FROM_LOC  
      ,WI.TO_LOC  
      ,WI.FROM_CHECK_DIG  
      ,WI.TO_CHECK_DIG  
      ,WI.FROM_WORK_ZONE  
      ,WI.TO_WORK_ZONE  
      ,WI.COMPLETED_BY_USER  
      ,WI.TEAM_ASSIGNED  
      ,NULL  
      ,WI.ESTIMATED_TIME  
      ,WI.AGING_DATE_TIME  
      ,WI.START_DATE_TIME  
      ,WI.END_DATE_TIME  
      ,WI.NUMBER_OF_CHILDREN  
      ,WI.MESSAGE_ID  
      ,WI.LOT  
      ,WI.USER_DEF1  
      ,WI.USER_DEF2  
      ,WI.USER_DEF3  
      ,WI.USER_DEF4  
      ,WI.USER_DEF5  
      ,WI.USER_DEF6  
      ,WI.USER_DEF7  
      ,WI.USER_DEF8  
      ,WI.USER_STAMP  
      ,WI.PROCESS_STAMP  
      ,GETUTCDATE()  
      ,WI.EQUIPMENT_LOC  
      ,WI.CONVERTED_QTY  
      ,WI.CONVERTED_QTY_UM  
      ,WI.INTERNAL_NUM_TYPE  
      ,WI.INTERNAL_REQ_NUM  
      ,WI.INVENTORY_TRACKING  
      ,WI.LOCATING_ZONE  
      ,WI.FROM_TEMPL_FIELD1  
      ,WI.FROM_TEMPL_FIELD2  
      ,WI.FROM_TEMPL_FIELD3  
      ,WI.FROM_TEMPL_FIELD4  
      ,WI.FROM_TEMPL_FIELD5  
      ,WI.TO_TEMPL_FIELD1  
      ,WI.TO_TEMPL_FIELD2  
      ,WI.TO_TEMPL_FIELD3  
      ,WI.TO_TEMPL_FIELD4  
      ,WI.TO_TEMPL_FIELD5  
      ,WI.ALLOCATION_ZONE  
      ,WI.INTERNAL_CONTAINER_NUM  
      ,WI.CONTAINER_ID  
      ,WI.PARENT_CONTAINER_NUM  
      ,WI.PARENT_CONTAINER_ID  
      ,WI.INTERNAL_COUNT_NUM  
      ,WI.CYCLE_COUNT  
      ,WI.RELATED_WORK_UNIT  
      ,WI.TRANSPORT_CONT_ID  
      ,WI.GROUP_NUM  
      ,WI.OUTGOING_PD_LOC  
      ,WI.INCOMING_PD_LOC  
      ,WI.INVENTORY_AT_PD  
      ,WI.CYCLE_COUNT_GROUP_NUM  
      ,WI.ASSIGNMENT_ID  
      ,WI.LOGISTICS_UNIT  
      ,WI.PARENT_LOGISTICS_UNIT  
      ,WI.TREE_UNIT  
      ,WI.TREE_UNIT_ID  
      ,N'<literal:1>'
	  ,WI.SRC_IDENTIFIER
	FROM 
		SHIPMENT_HEADER SH 
		INNER JOIN WORK_INSTRUCTION WI 
			ON (SH.INTERNAL_SHIPMENT_NUM = WI.INTERNAL_NUM AND WI.INTERNAL_NUM_TYPE IN (N'<literal:2>', N'<literal:3>') AND WI.CONDITION = N'<literal:4>')
		LEFT OUTER JOIN WORK_INSTRUCTION PARENT ON (WI.PARENT_INSTR > 0 AND WI.PARENT_INSTR = PARENT.INTERNAL_INSTRUCTION_NUM)
	WHERE SH.SHIPPING_LOAD_NUM = @loadNum
	AND (PARENT.CONDITION IS NULL OR PARENT.CONDITION = N'<literal:5>'));  
  
	DELETE WI 
	FROM 
		SHIPMENT_HEADER SH 
		INNER JOIN WORK_INSTRUCTION WI 
			ON (SH.INTERNAL_SHIPMENT_NUM = WI.INTERNAL_NUM AND WI.INTERNAL_NUM_TYPE IN (N'<literal:6>', N'<literal:7>') AND WI.CONDITION = N'<literal:8>')
		LEFT OUTER JOIN WORK_INSTRUCTION PARENT ON (WI.PARENT_INSTR > 0 AND WI.PARENT_INSTR = PARENT.INTERNAL_INSTRUCTION_NUM)
	WHERE SH.SHIPPING_LOAD_NUM = @loadNum
	AND (PARENT.CONDITION IS NULL OR PARENT.CONDITION = N'<literal:9>');  
END;