-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */






CREATE PROCEDURE wm_RResource01
	@Group nvarchar(4),
	@Lang nvarchar(25)
AS

SELECT RESOURCE_KEY, TEXT, RESOURCE_GROUP, FIELD_LENGTH, DECIMAL_POS, RESOURCE_LANGUAGE FROM RESOURCE_FILE_CUSTOM CUSTOM WHERE RESOURCE_LANGUAGE = @Lang AND RESOURCE_GROUP = @Group

UNION

SELECT RESOURCE_KEY, TEXT, RESOURCE_GROUP, FIELD_LENGTH, DECIMAL_POS, RESOURCE_LANGUAGE FROM RESOURCE_FILE_BASE BASE WHERE RESOURCE_LANGUAGE = @Lang AND RESOURCE_GROUP = @Group 
AND RESOURCE_KEY NOT IN (SELECT RESOURCE_KEY FROM RESOURCE_FILE_CUSTOM CUSTOM WHERE RESOURCE_LANGUAGE = @Lang AND RESOURCE_GROUP = @Group) 

