-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */










CREATE PROCEDURE wm_RLocationInventoryAttributes03
	@TransHistId numeric(9)
AS
	 SELECT LIAT.* FROM TRANS_HIST_ATTRIBUTES THA INNER JOIN 
	   ( 
	      SELECT object_id,LOC_INV_ATTRIBUTE1,	LOC_INV_ATTRIBUTE2,	LOC_INV_ATTRIBUTE3,	LOC_INV_ATTRIBUTE4,	LOC_INV_ATTRIBUTE5,	LOC_INV_ATTRIBUTE6,	LOC_INV_ATTRIBUTE7,	LOC_INV_ATTRIBUTE8,	LOC_INV_ATTRIBUTE9,
	      LOC_INV_ATTRIBUTE10,	LOC_INV_ATTRIBUTE11,	LOC_INV_ATTRIBUTE12,	LOC_INV_ATTRIBUTE13,	LOC_INV_ATTRIBUTE14,	LOC_INV_ATTRIBUTE15,	LOC_INV_ATTRIBUTE16,	LOC_INV_ATTRIBUTE17,
	      LOC_INV_ATTRIBUTE18,	LOC_INV_ATTRIBUTE19,	LOC_INV_ATTRIBUTE20  FROM LOCATION_INVENTORY_ATTRIBUTES 
	      UNION
		  SELECT object_id,LOC_INV_ATTRIBUTE1,	LOC_INV_ATTRIBUTE2,	LOC_INV_ATTRIBUTE3,	LOC_INV_ATTRIBUTE4,	LOC_INV_ATTRIBUTE5,	LOC_INV_ATTRIBUTE6,	LOC_INV_ATTRIBUTE7,	LOC_INV_ATTRIBUTE8,	LOC_INV_ATTRIBUTE9,
		 LOC_INV_ATTRIBUTE10,	LOC_INV_ATTRIBUTE11,	LOC_INV_ATTRIBUTE12,	LOC_INV_ATTRIBUTE13,	LOC_INV_ATTRIBUTE14,	LOC_INV_ATTRIBUTE15,	LOC_INV_ATTRIBUTE16,	LOC_INV_ATTRIBUTE17,
		 LOC_INV_ATTRIBUTE18,	LOC_INV_ATTRIBUTE19,	LOC_INV_ATTRIBUTE20 FROM AR_LOCATION_INVENTORY_ATTRIBUTES 
		) LIAT ON THA.ATTRIBUTE_VALUE = LIAT.OBJECT_ID
		 WHERE THA.ATTRIBUTE_TYPE = N'<literal:1>'
	     AND THA.LINK_ID = @TransHistId;