-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */






CREATE VIEW METADATA_INSIGHT_USER_ACTIVITY_VIEW
AS 
SELECT
UA.GUID,
UA.USER_NAME,
UA.USER_TYPE,
GC.IDENTIFIER as USER_TYPE_IDENTIFIER,
UA.DEVICE,
UA.LOGON_DATE_TIME,
UA.LAST_ACTION_DATE_TIME,
UA.LOGOFF_DATE_TIME,
UA.LOGOFF_NOTE,
UA.USER_DEF1 AS UD_USERACTIVITY01,
UA.USER_DEF2 AS UD_USERACTIVITY02,
UA.USER_DEF3 AS UD_USERACTIVITY03,
UA.USER_DEF4 AS UD_USERACTIVITY04,
UA.USER_DEF5 AS UD_USERACTIVITY05,
UA.USER_DEF6 AS UD_USERACTIVITY06,
UA.USER_DEF7 AS UD_USERACTIVITY07,
UA.USER_DEF8 AS UD_USERACTIVITY08,
UA.USER_STAMP,
UA.PROCESS_STAMP,
UA.DATE_TIME_STAMP,
UA.EQUIPMENT_TYPE,
UA.VOCOLLECT_REGION,
UA.VOCOLLECT_ASSGNID AS VOCOLLECTASSIGNID
FROM
USER_ACTIVITY UA
LEFT JOIN GENERIC_CONFIG_DETAIL GC ON
GC.RECORD_TYPE = N'<literal:1>' AND
GC.SYS1VALUE = UA.USER_TYPE