-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */





   

CREATE VIEW METADATA_INSIGHT_VAS_VIEW
AS
SELECT 
    va.OBJECT_ID as VAS_OBJECTID,
    va.NAME AS VAS_ACTIVITY,
	scva.OBJECT_ID AS OBJECTID,
	scva.INTERNAL_CONTAINER_NUM,
	scva.INSTRUCTIONS,	
	scva.COMPLETED as CONFIRMED,		
	cont.CONTAINER_ID AS CONTAINERID,
	cont.status AS [STATUS],	
	CASE WHEN cont.QC_STATUS = 1 THEN N'<literal:1>'
	     WHEN cont.QC_STATUS = 2 THEN N'<literal:2>'
		 WHEN cont.QC_STATUS = 3 THEN N'<literal:3>'
		 ELSE N'<literal:4>' END AS QCREQUIRED,
	sh.SHIPMENT_ID AS SHIPMENTID,
	sh.INTERNAL_SHIPMENT_NUM AS INTERNAL_SHIPMENT_NUM,
	scva.COMPLETED,
	cont.WAREHOUSE
FROM VAS_ACTIVITY va  
INNER JOIN SHIPPING_CONT_VAS_ACTIVITY scva ON va.OBJECT_ID=scva.VAS_ACTIVITY_ID   
INNER JOIN SHIPPING_CONTAINER cont ON scva.INTERNAL_CONTAINER_NUM = cont.INTERNAL_CONTAINER_NUM 
INNER JOIN SHIPMENT_HEADER sh  ON cont.INTERNAL_SHIPMENT_NUM = sh.INTERNAL_SHIPMENT_NUM