-- DOCUMENTATION ONLY: literals/comments removed; do not execute.



CREATE PROCEDURE WTH_SplitWorkWithReturnInstr(
	@qty	numeric(19,5),
	@internalInstructionNum numeric(9),
	@userStamp nvarchar(30),
	@confirmMode numeric(1,0),
	@newInternalInstrNum numeric(9) output)
AS
	SET NOCOUNT ON;

	-- [comment omitted]
	-- [comment omitted]
	
	-- [comment omitted]
	declare @iError int;
	declare @iRowCount int;
	declare @stMsg nvarchar(2000);
	
	-- [comment omitted]
	if (@internalInstructionNum is null OR @internalInstructionNum <= 0 OR @qty is null OR @qty <= 0)
		return -1;
	
	/* [comment omitted] */
	INSERT INTO WORK_INSTRUCTION ( ACCOUNT, AGING_DATE_TIME, ALLOCATION_ZONE, ASSIGNMENT_ID, COMPANY, COMPLETED_BY_USER, CONDITION, CONTAINER_ID, CONVERTED_QTY, CONVERTED_QTY_UM, CYCLE_COUNT, CYCLE_COUNT_GROUP_NUM, END_DATE_TIME, EQUIPMENT_LOC, ERP_ORDER, ERP_ORDER_LINE_NUM, ESTIMATED_TIME, FROM_CHECK_DIG, FROM_LOC, FROM_LOC_INV_ATTRIBUTES_ID, FROM_QTY, FROM_TEMPL_FIELD1, FROM_TEMPL_FIELD2, FROM_TEMPL_FIELD3, FROM_TEMPL_FIELD4, FROM_TEMPL_FIELD5, FROM_WHS, FROM_WORK_ZONE, GROUP_NUM, HOLD_CODE, INCOMING_PD_LOC, INSTRUCTION_TYPE, INTERNAL_CONTAINER_NUM, INTERNAL_COUNT_NUM, INTERNAL_LINE_NUM, INTERNAL_NUM, INTERNAL_NUM_TYPE, INTERNAL_REQ_NUM, INVENTORY_AT_PD, INVENTORY_TRACKING, ITEM, ITEM_DESC, LAUNCH_NUM, LOCATING_ZONE, LOCKED, LOGISTICS_UNIT, LOT, MESSAGE_ID, NUMBER_OF_CHILDREN, OUTGOING_PD_LOC, PARENT_CONTAINER_ID, PARENT_CONTAINER_NUM, PARENT_INSTR, PARENT_LOGISTICS_UNIT, PICK_LIST_ID, PRIORITY, QUANTITY, QUANTITY_UM, REFERENCE_ID, REFERENCE_TYPE, RELATED_WORK_UNIT, SEQUENCE, SRC_IDENTIFIER, START_DATE_TIME, TEAM_ASSIGNED, TO_CHECK_DIG, TO_LOC, TO_LOC_INV_ATTRIBUTES_ID, TO_QTY, TO_TEMPL_FIELD1, TO_TEMPL_FIELD2, TO_TEMPL_FIELD3, TO_TEMPL_FIELD4, TO_TEMPL_FIELD5, TO_WHS, TO_WORK_ZONE, TOTAL_VALUE, TOTAL_VOLUME, TOTAL_WEIGHT, TRANSPORT_CONT_ID, TREE_UNIT, TREE_UNIT_ID, USER_ASSIGNED, VOLUME_UM, WEIGHT_UM, WORK_GROUP, WORK_TYPE, WORK_UNIT, USER_DEF1, USER_DEF2, USER_DEF3, USER_DEF4, USER_DEF5, USER_DEF6, USER_DEF7, USER_DEF8, USER_STAMP, PROCESS_STAMP, DATE_TIME_STAMP ) 
		SELECT ACCOUNT, AGING_DATE_TIME, ALLOCATION_ZONE, ASSIGNMENT_ID, COMPANY, COMPLETED_BY_USER, CONDITION, CONTAINER_ID, CONVERTED_QTY, CONVERTED_QTY_UM, CYCLE_COUNT, CYCLE_COUNT_GROUP_NUM, END_DATE_TIME, EQUIPMENT_LOC, ERP_ORDER, ERP_ORDER_LINE_NUM, ESTIMATED_TIME, FROM_CHECK_DIG, FROM_LOC, FROM_LOC_INV_ATTRIBUTES_ID, FROM_QTY, FROM_TEMPL_FIELD1, FROM_TEMPL_FIELD2, FROM_TEMPL_FIELD3, FROM_TEMPL_FIELD4, FROM_TEMPL_FIELD5, FROM_WHS, FROM_WORK_ZONE, GROUP_NUM, HOLD_CODE, INCOMING_PD_LOC, INSTRUCTION_TYPE, INTERNAL_CONTAINER_NUM, INTERNAL_COUNT_NUM, INTERNAL_LINE_NUM, INTERNAL_NUM, INTERNAL_NUM_TYPE, INTERNAL_REQ_NUM, INVENTORY_AT_PD, INVENTORY_TRACKING, ITEM, ITEM_DESC, LAUNCH_NUM, LOCATING_ZONE, LOCKED, LOGISTICS_UNIT, LOT, MESSAGE_ID, NUMBER_OF_CHILDREN, OUTGOING_PD_LOC, PARENT_CONTAINER_ID, PARENT_CONTAINER_NUM, PARENT_INSTR, PARENT_LOGISTICS_UNIT, PICK_LIST_ID, PRIORITY, QUANTITY, QUANTITY_UM, REFERENCE_ID, REFERENCE_TYPE, RELATED_WORK_UNIT, SEQUENCE, SRC_IDENTIFIER, START_DATE_TIME, TEAM_ASSIGNED, TO_CHECK_DIG, TO_LOC, TO_LOC_INV_ATTRIBUTES_ID, TO_QTY, TO_TEMPL_FIELD1, TO_TEMPL_FIELD2, TO_TEMPL_FIELD3, TO_TEMPL_FIELD4, TO_TEMPL_FIELD5, TO_WHS, TO_WORK_ZONE, TOTAL_VALUE, TOTAL_VOLUME, TOTAL_WEIGHT, TRANSPORT_CONT_ID, TREE_UNIT, TREE_UNIT_ID, USER_ASSIGNED, VOLUME_UM, WEIGHT_UM, WORK_GROUP, WORK_TYPE, WORK_UNIT, USER_DEF1, USER_DEF2, USER_DEF3, USER_DEF4, USER_DEF5, USER_DEF6, USER_DEF7, USER_DEF8, USER_STAMP, PROCESS_STAMP, DATE_TIME_STAMP 
		FROM WORK_INSTRUCTION
		WHERE INTERNAL_INSTRUCTION_NUM = @internalInstructionNum;
	if (@@ERROR <> 0) return -1;	

	set @newInternalInstrNum = SCOPE_IDENTITY();
	
	/* [comment omitted] */
	IF (@confirmMode <> 1)
	
	BEGIN

		/* [comment omitted] */
		UPDATE WORK_INSTRUCTION
		SET	CONVERTED_QTY = (CONVERTED_QTY / QUANTITY) * (QUANTITY - @qty),
			FROM_QTY = FROM_QTY - @qty,
			QUANTITY = QUANTITY - @qty,
			TOTAL_WEIGHT = (TOTAL_WEIGHT / QUANTITY) * (QUANTITY - @qty),
			TOTAL_VOLUME = (TOTAL_VOLUME / QUANTITY) * (QUANTITY - @qty),
			TOTAL_VALUE = (TOTAL_VALUE / QUANTITY) * (QUANTITY - @qty),
			USER_STAMP = @userStamp,
			LOCKED=N'<literal:1>',
			PROCESS_STAMP = N'<literal:2>'
		WHERE INTERNAL_INSTRUCTION_NUM = @newInternalInstrNum
		AND FROM_QTY >= @qty;
		select @iError = @@ERROR, @iRowCount = @@ROWCOUNT;
		
		if (@iError <> 0) return -1;	
			
		if (@iRowCount <= 0) 
		  begin 
			set @stMsg = N'<literal:3>' + dbo.RSCMfn_RtrvMsg(N'<literal:4>'); 
				RAISERROR(@stMsg, 18, 1); 
				return -1; 
     		end;	

		/* [comment omitted] */
		UPDATE WORK_INSTRUCTION
		SET	CONVERTED_QTY = (CONVERTED_QTY / QUANTITY) * (QUANTITY - (QUANTITY - @qty)),
			FROM_QTY = @qty,
			TO_QTY = 0,
			QUANTITY = (QUANTITY - (QUANTITY - @qty)),
			TOTAL_WEIGHT = (TOTAL_WEIGHT / QUANTITY) * (QUANTITY - (QUANTITY - @qty)),
			TOTAL_VOLUME = (TOTAL_VOLUME / QUANTITY) * (QUANTITY - (QUANTITY - @qty)),
			TOTAL_VALUE = (TOTAL_VALUE / QUANTITY) * (QUANTITY - (QUANTITY - @qty)),
			USER_STAMP = @userStamp,
			PROCESS_STAMP = N'<literal:5>',
			EQUIPMENT_LOC = NULL
		WHERE INTERNAL_INSTRUCTION_NUM = @internalInstructionNum;
		if (@@ERROR <> 0) return -1;	
		
	END
	
	/* [comment omitted] */
	ELSE
	
	BEGIN
	
		/* [comment omitted] */
		UPDATE WORK_INSTRUCTION
		SET	CONVERTED_QTY = (CONVERTED_QTY / QUANTITY) * (QUANTITY - @qty),
			FROM_QTY = 0,
			TO_QTY = TO_QTY - @qty,
			QUANTITY = QUANTITY - @qty,
			TOTAL_WEIGHT = (TOTAL_WEIGHT / QUANTITY) * (QUANTITY - @qty),
			TOTAL_VOLUME = (TOTAL_VOLUME / QUANTITY) * (QUANTITY - @qty),
			TOTAL_VALUE = (TOTAL_VALUE / QUANTITY) * (QUANTITY - @qty),
			USER_STAMP = @userStamp,
			LOCKED=N'<literal:6>',
			PROCESS_STAMP = N'<literal:7>'
		WHERE INTERNAL_INSTRUCTION_NUM = @newInternalInstrNum
		AND TO_QTY >= @qty;
		select @iError = @@ERROR, @iRowCount = @@ROWCOUNT;
		
		if (@iError <> 0) return -1;	
			
		if (@iRowCount <= 0) 
		  begin 
			set @stMsg = N'<literal:8>' + dbo.RSCMfn_RtrvMsg(N'<literal:9>'); 
				RAISERROR(@stMsg, 18, 1); 
				return -1; 
     		end;	
     	
     	/* [comment omitted] */
	
     	UPDATE WORK_INSTRUCTION
		SET	CONTAINER_ID = NULL,
			INTERNAL_CONTAINER_NUM = NULL,	
			USER_STAMP = @userStamp,
			PROCESS_STAMP = N'<literal:10>'
		WHERE INTERNAL_INSTRUCTION_NUM = @newInternalInstrNum
		AND INTERNAL_NUM_TYPE <> N'<literal:11>';			


		/* [comment omitted] */
		UPDATE WORK_INSTRUCTION
		SET	CONVERTED_QTY = (CONVERTED_QTY / QUANTITY) * (QUANTITY - (QUANTITY - @qty)),
			TO_QTY = @qty,
			QUANTITY = (QUANTITY - (QUANTITY - @qty)),
			TOTAL_WEIGHT = (TOTAL_WEIGHT / QUANTITY) * (QUANTITY - (QUANTITY - @qty)),
			TOTAL_VOLUME = (TOTAL_VOLUME / QUANTITY) * (QUANTITY - (QUANTITY - @qty)),
			TOTAL_VALUE = (TOTAL_VALUE / QUANTITY) * (QUANTITY - (QUANTITY - @qty)),
			USER_STAMP = @userStamp,
			PROCESS_STAMP = N'<literal:12>',
			EQUIPMENT_LOC = NULL
		WHERE INTERNAL_INSTRUCTION_NUM = @internalInstructionNum;
		if (@@ERROR <> 0) return -1;
		
	END;
	
	/* [comment omitted] */
	UPDATE WORK_INSTRUCTION
	SET	NUMBER_OF_CHILDREN = NUMBER_OF_CHILDREN + 1
	WHERE INTERNAL_INSTRUCTION_NUM IN
		(SELECT PARENT_INSTR FROM WORK_INSTRUCTION 
		WHERE INTERNAL_INSTRUCTION_NUM = @internalInstructionNum);
		if (@@ERROR <> 0) return -1;		

-- [comment omitted]



