-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */






CREATE VIEW METADATA_INSIGHT_WAREHOUSE_MOBILE_MENU_VIEW
AS
SELECT WM.OBJECT_ID
      ,WM.MENU_OPTION_NAME
      ,WM.MENU_RESOURCE_KEY
      ,WM.SUBMENU_NAME
      ,WM.SUBMENU_RESOURCE_KEY
      ,WM.FORM_ID
      ,WM.SEQUENCE
      ,WM.SUBMENU_AUTHORIZATION
      ,WM.SRC_IDENTIFIER
      ,WM.PARENT_OBJECT_ID
	  ,PARENT.MENU_OPTION_NAME as PARENT
	  ,CASE WHEN WM.PARENT_OBJECT_ID IS NULL THEN WM.MENU_OPTION_NAME ELSE PARENT.MENU_OPTION_NAME END AS MENU_GROUP
      ,WM.SYSTEM_CREATED
	  ,WM.ACTIVE
      ,WM.USER_DEF1 as UD_WAREHOUSEMOBILEMENU01
      ,WM.USER_DEF2 as UD_WAREHOUSEMOBILEMENU02
      ,WM.USER_DEF3 AS UD_WAREHOUSEMOBILEMENU03
      ,WM.USER_DEF4 AS UD_WAREHOUSEMOBILEMENU04
      ,WM.USER_DEF5 AS UD_WAREHOUSEMOBILEMENU05
      ,WM.USER_DEF6 AS UD_WAREHOUSEMOBILEMENU06
      ,WM.USER_DEF7 AS UD_WAREHOUSEMOBILEMENU07
      ,WM.USER_DEF8 AS UD_WAREHOUSEMOBILEMENU08
      ,WM.USER_STAMP
      ,WM.PROCESS_STAMP
      ,WM.DATE_TIME_STAMP
 FROM WAREHOUSE_MOBILE_MENU WM
 LEFT OUTER JOIN  WAREHOUSE_MOBILE_MENU PARENT
 ON WM.PARENT_OBJECT_ID = PARENT.OBJECT_ID