-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */







CREATE VIEW METADATA_INSIGHT_WAVE_VIEW
AS 
SELECT 

ls.INTERNAL_LAUNCH_NUM,
ls.LAUNCH_NAME,
ls.LAUNCH_FLOW,
ls.LAUNCH_MODE,
ls.TOTAL_SHIPMENTS,
ls.TOTAL_LINES,
ls.RELEASED,
ls.CLOSED,
ls.LAUNCH_DATE_TIME_STARTED AS WAVE_DATE_TIME_STARTED,
ls.LAUNCH_DATE_TIME_ENDED AS WAVE_DATE_TIME_ENDED,
ls.TOTAL_QTY,
ls.CURRENT_LAUNCH_STEP,
ls.LAST_LAUNCH_STEP,
ls.WAREHOUSE,
ls.LAUNCH_FILTER_NAME,
ls.AUTO_RELEASE,
ls.TOTAL_WEIGHT,
ls.WEIGHT_UM,
ls.TOTAL_VOLUME,
ls.VOLUME_UM,
ls.LAUNCH_COMMENT,
ls.USER_DEF1,
ls.USER_DEF2,
ls.USER_DEF3,
ls.USER_DEF4,
ls.USER_DEF5,
ls.USER_DEF6,
ls.USER_DEF7,
ls.USER_DEF8,
ls.USER_STAMP,
ls.PROCESS_STAMP,
ls.DATE_TIME_STAMP,
ls.WAVE_LABEL_STATUS,
ls.LABEL_MASTER_ID,
ls.LABOR_PLAN_EXEC_IN_PROGRESS,
CASE WHEN (ls.LAUNCH_DATE_TIME_STARTED IS NULL OR ls.CURRENT_LAUNCH_STEP IS NOT NULL) then N'<literal:1>' else N'<literal:2>' END AS ACTIVE,
CASE WHEN (ls.LAUNCH_DATE_TIME_STARTED IS NOT NULL AND ls.CURRENT_LAUNCH_STEP IS NULL AND ls.RELEASED <> N'<literal:3>' AND ls.LAST_LAUNCH_STEP <> N'<literal:4>') then N'<literal:5>' else N'<literal:6>' END AS COMPLETED,
CASE WHEN (ls.LAST_LAUNCH_STEP IS NOT NULL AND ls.LAST_LAUNCH_STEP = N'<literal:7>') then N'<literal:8>' else N'<literal:9>' END AS CANCELLED,
CASE WHEN (ls.LAUNCH_DATE_TIME_STARTED IS NULL OR ls.CURRENT_LAUNCH_STEP IS NOT NULL) then N'<literal:10>'
	 WHEN (ls.LAUNCH_DATE_TIME_STARTED IS NOT NULL AND ls.CURRENT_LAUNCH_STEP IS NULL AND ls.RELEASED <> N'<literal:11>' AND ls.LAST_LAUNCH_STEP <> N'<literal:12>') then N'<literal:13>'
	 WHEN RELEASED = N'<literal:14>' then N'<literal:15>'
	 WHEN (ls.LAST_LAUNCH_STEP IS NOT NULL AND ls.LAST_LAUNCH_STEP = N'<literal:16>') then N'<literal:17>'	 
	 ELSE NULL END AS WAVE_STATUS
FROM LAUNCH_STATISTICS ls