-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */





CREATE PROCEDURE SEC_GetSecurityForms(
	@userName nvarchar(30),
	@culture nvarchar(5),
	@allForms bit,
	@isManhAuthorizedUser bit,
	@restrictedFormIds nvarchar(4000)
)
AS
SET NOCOUNT ON;
BEGIN

-- [comment omitted]
SELECT @culture = COALESCE(NULLIF(@culture, N'<literal:1>'), (SELECT SYSTEM_VALUE FROM SYSTEM_CONFIG_DETAIL WHERE SYS_KEY = N'<literal:2>' AND RECORD_TYPE = N'<literal:3>')) 

-- [comment omitted]
select RESOURCE_LANGUAGE, RESOURCE_GROUP, RESOURCE_KEY, TEXT INTO #RESOURCE_FILE_CUSTOM from RESOURCE_FILE_CUSTOM where RESOURCE_GROUP=N'<literal:4>' and RESOURCE_LANGUAGE =@culture
select RESOURCE_LANGUAGE, RESOURCE_GROUP, RESOURCE_KEY, TEXT INTO #RESOURCE_FILE_BASE from RESOURCE_FILE_BASE where RESOURCE_GROUP=N'<literal:5>' and RESOURCE_LANGUAGE =@culture
select RESOURCE_LANGUAGE, RESOURCE_GROUP, RESOURCE_KEY, TEXT INTO #RESOURCE_FILE_BASEen from RESOURCE_FILE_BASE where RESOURCE_GROUP=N'<literal:6>' and RESOURCE_LANGUAGE =N'<literal:7>'
create index idx_RESOURCE_FILE_BASE_RESOURCE_KEY on #RESOURCE_FILE_BASE(RESOURCE_KEY)
create index idx_RESOURCE_FILE_BASEen_RESOURCE_KEY on #RESOURCE_FILE_BASEen(RESOURCE_KEY)

-- [comment omitted]
if @allForms = 1 -- [comment omitted]
begin
	-- [comment omitted]
	select VALUE INTO #RESTRICTED_FORMIDS from GENfn_SplitString(@restrictedFormIds,N'<literal:8>')
	
	-- [comment omitted]
	SELECT FORM_ID into #parentKey FROM FORM WHERE PARENT_KEY_NAME IN (SELECT FORM_KEY_NAME FROM FORM WHERE FORM_ID IN(N'<literal:9>',N'<literal:10>' )) OR FORM_ID IN ( N'<literal:11>',N'<literal:12>' )

	-- [comment omitted]
	select Form_id, FORM_KEY_NAME, SECURITY_LEVEL, USER_NAME, SEC_VALUES, CHECKPOINTID, CHECKPOINTVALUE, RESOURCEFILEKEY, ASSOCIATED_FORM_KEY, USER_DEF1, USER_DEF2, USER_DEF3, USER_DEF4, USER_DEF5, USER_DEF6, USER_DEF7, USER_DEF8 
	INTO #SecurityPermissionAll
	from  (select form.FORM_ID, FORM_KEY_NAME, SECURITY_LEVEL, USER_NAME, SEC_VALUES , CHECKPOINTID, CHECKPOINTVALUE, (SELECT RESOURCE_FILE_KEY FROM SECURITY_CHECKPOINT SC WHERE SC.CHECK_POINT = F.CHECKPOINTID AND FORM_ID = S.FORM_ID) AS RESOURCEFILEKEY, ASSOCIATED_FORM_KEY, S.USER_DEF1, S.USER_DEF2, S.USER_DEF3, S.USER_DEF4, S.USER_DEF5, S.USER_DEF6, S.USER_DEF7, S.USER_DEF8   
			from FORM 
			left join SECURITY S on form.FORM_ID = s.FORM_ID and s.USER_NAME = @userName
			left join SECfn_GetSecurityCheckPointByUsername(@userName) F on form.FORM_ID = f.Form_Id and(CheckPointValue not in (N'<literal:13>'))
			where form.SECURITY_ACTIVE = N'<literal:14>' 
			and form.FORM_ID NOT IN ( SELECT FORM_ID FROM #parentKey )
			AND (@isManhAuthorizedUser=1 OR Form.Form_Id NOT IN (select VALUE from #RESTRICTED_FORMIDS) )
	) securityPermission  
	where (ASSOCIATED_FORM_KEY is null or FORM_ID = (select max(FORM_ID) from FORM where ASSOCIATED_FORM_KEY = securityPermission.ASSOCIATED_FORM_KEY) ) -- [comment omitted]

	-- [comment omitted]
	select Form_id, FORM_KEY_NAME, SECURITY_LEVEL, USER_NAME, SEC_VALUES, CHECKPOINTID, CHECKPOINTVALUE, RESOURCEFILEKEY, ASSOCIATED_FORM_KEY, t.USER_DEF1, t.USER_DEF2, t.USER_DEF3, t.USER_DEF4, t.USER_DEF5, t.USER_DEF6, t.USER_DEF7, t.USER_DEF8 
	,COALESCE(rf1.TEXT, rf2.TEXT, rf3.TEXT, RESOURCEFILEKEY) ResoruceFileText
	,COALESCE(fn1.TEXT, fn2.TEXT, fn3.TEXT, FORM_KEY_NAME) FormName
	from #SecurityPermissionAll t
	left join #RESOURCE_FILE_CUSTOM rf1 on rf1.RESOURCE_KEY=RESOURCEFILEKEY
	left join #RESOURCE_FILE_BASE rf2 on rf2.RESOURCE_KEY=RESOURCEFILEKEY
	left join #RESOURCE_FILE_BASEen rf3 on rf3.RESOURCE_KEY=RESOURCEFILEKEY
	left join #RESOURCE_FILE_CUSTOM fn1 on fn1.RESOURCE_KEY=FORM_KEY_NAME
	left join #RESOURCE_FILE_BASE fn2 on fn2.RESOURCE_KEY=FORM_KEY_NAME
	left join #RESOURCE_FILE_BASEen fn3 on fn3.RESOURCE_KEY=FORM_KEY_NAME
	
	drop table #SecurityPermissionAll
	drop table #RESTRICTED_FORMIDS
	drop table #parentKey
end
else -- [comment omitted]
begin
	-- [comment omitted]
	select Form_id, FORM_KEY_NAME, SECURITY_LEVEL, USER_NAME, SEC_VALUES, CHECKPOINTID, CHECKPOINTVALUE, RESOURCEFILEKEY, ASSOCIATED_FORM_KEY, USER_DEF1, USER_DEF2, USER_DEF3, USER_DEF4, USER_DEF5, USER_DEF6, USER_DEF7, USER_DEF8 
	INTO #SecurityPermission
	from  (select form.FORM_ID, FORM_KEY_NAME, SECURITY_LEVEL, USER_NAME, SEC_VALUES , CHECKPOINTID, CHECKPOINTVALUE, (SELECT RESOURCE_FILE_KEY FROM SECURITY_CHECKPOINT SC WHERE SC.CHECK_POINT = F.CHECKPOINTID AND FORM_ID = S.FORM_ID) AS RESOURCEFILEKEY, ASSOCIATED_FORM_KEY, S.USER_DEF1, S.USER_DEF2, S.USER_DEF3, S.USER_DEF4, S.USER_DEF5, S.USER_DEF6, S.USER_DEF7, S.USER_DEF8   from SECURITY S LEFT JOIN FORM on s.FORM_ID  = form.FORM_ID, SECfn_GetSecurityCheckPointByUsername(@userName) F   WHERE USER_NAME = @userName AND (CheckPointValue not in (N'<literal:15>')) AND S.FORM_ID = F.FORM_ID  )  securityPermission
	where (ASSOCIATED_FORM_KEY is null or FORM_ID = (select max(FORM_ID) from FORM where ASSOCIATED_FORM_KEY = securityPermission.ASSOCIATED_FORM_KEY) )

	-- [comment omitted]
	select Form_id, FORM_KEY_NAME, SECURITY_LEVEL, USER_NAME, SEC_VALUES, CHECKPOINTID, CHECKPOINTVALUE, RESOURCEFILEKEY, ASSOCIATED_FORM_KEY, t.USER_DEF1, t.USER_DEF2, t.USER_DEF3, t.USER_DEF4, t.USER_DEF5, t.USER_DEF6, t.USER_DEF7, t.USER_DEF8 
	,COALESCE(rf1.TEXT, rf2.TEXT, rf3.TEXT, RESOURCEFILEKEY) ResoruceFileText
	,COALESCE(fn1.TEXT, fn2.TEXT, fn3.TEXT, FORM_KEY_NAME) FormName
	from #SecurityPermission t
	left join #RESOURCE_FILE_CUSTOM rf1 on rf1.RESOURCE_KEY=RESOURCEFILEKEY
	left join #RESOURCE_FILE_BASE rf2 on rf2.RESOURCE_KEY=RESOURCEFILEKEY
	left join #RESOURCE_FILE_BASEen rf3 on rf3.RESOURCE_KEY=RESOURCEFILEKEY
	left join #RESOURCE_FILE_CUSTOM fn1 on fn1.RESOURCE_KEY=FORM_KEY_NAME
	left join #RESOURCE_FILE_BASE fn2 on fn2.RESOURCE_KEY=FORM_KEY_NAME
	left join #RESOURCE_FILE_BASEen fn3 on fn3.RESOURCE_KEY=FORM_KEY_NAME
	drop table #SecurityPermission
end


drop table #RESOURCE_FILE_CUSTOM
drop table #RESOURCE_FILE_BASE
drop table #RESOURCE_FILE_BASEen

END;
