-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */



  
  
CREATE VIEW METADATA_INSIGHT_TPM_ORDER_CONTAINER_STATUS_VIEW  
 AS
-- [comment omitted]
SELECT SC.INTERNAL_CONTAINER_NUM, SC.CONTAINER_ID, SC.TRACKING_NUMBER, 
SC.WEIGHT, SC.STATUS, PC.CONTAINER_ID AS PARENTCONTAINERID,  
SC.WAREHOUSE,                
 SC.ITEM,                
 SC.COMPANY,                
 SC.STATUS as SHIPPING_CONTAINER_STATUS,                
 SC.PARENT_CONTAINER_ID,                
 SC.QUANTITY,
 case when SC.PARENT is null then 0 else SC.PARENT end as PARENT,                
 SH.INTERNAL_ORDER_NUM, 
 (SELECT ERP_ORDER FROM ORDER_HEADER WHERE INTERNAL_ORDER_NUM = 
 CASE WHEN SH.INTERNAL_ORDER_NUM IS NULL THEN -1 ELSE SH.INTERNAL_ORDER_NUM END)  AS ERP_ORDER,
 (SELECT ORDER_DATE FROM ORDER_HEADER WHERE INTERNAL_ORDER_NUM = 
 CASE WHEN SC.INTERNAL_ORDER_NUM IS NULL THEN -1 ELSE SC.INTERNAL_ORDER_NUM END)  AS ORDER_DATE,                   
 (select it.DESCRIPTION from item it where ISNULL(sc.ITEM,N'<literal:1>') = ISNULL(it.ITEM,N'<literal:2>')                
 AND ISNULL(sc.COMPANY,N'<literal:3>') = ISNULL(it.COMPANY,N'<literal:4>')) AS ITEM_DESC,
 CARR.INTERNET_TRACKING_LINK
FROM SHIPPING_CONTAINER SC LEFT OUTER JOIN SHIPPING_CONTAINER PC ON 
PC.INTERNAL_CONTAINER_NUM = SC.PARENT, SHIPMENT_HEADER SH 
LEFT OUTER JOIN CARRIER CARR ON SH.CARRIER = CARR.CARRIER
AND ISNULL(SH.CARRIER_SERVICE,N'<literal:5>') = ISNULL(CARR.SERVICE,N'<literal:6>') 
WHERE SC.INTERNAL_SHIPMENT_NUM = SH.INTERNAL_SHIPMENT_NUM 
AND SC.ITEM is not NULL
AND SC.CONTAINER_TYPE <> N'<literal:7>' 
AND SH.INTERNAL_ORDER_NUM IS NOT NULL
UNION
-- [comment omitted]
SELECT SC.INTERNAL_CONTAINER_NUM, SC.CONTAINER_ID, SC.TRACKING_NUMBER, SC.WEIGHT,
SC.STATUS, PC.CONTAINER_ID AS PARENTCONTAINERID,
SC.WAREHOUSE,                
 SC.ITEM,                
 SC.COMPANY,                
 SC.STATUS as SHIPPING_CONTAINER_STATUS,                
 SC.PARENT_CONTAINER_ID,                
 SC.QUANTITY,
 case when SC.PARENT is null then 0 else SC.PARENT end as PARENT,                
 SH.INTERNAL_ORDER_NUM, 
 (SELECT ERP_ORDER FROM ORDER_HEADER WHERE INTERNAL_ORDER_NUM = 
 CASE WHEN SH.INTERNAL_ORDER_NUM IS NULL THEN -1 ELSE SH.INTERNAL_ORDER_NUM END)  AS ERP_ORDER,
 (SELECT ORDER_DATE FROM ORDER_HEADER WHERE INTERNAL_ORDER_NUM = 
 CASE WHEN SC.INTERNAL_ORDER_NUM IS NULL THEN -1 ELSE SC.INTERNAL_ORDER_NUM END)  AS ORDER_DATE,                   
 (select it.DESCRIPTION from item it where ISNULL(sc.ITEM,N'<literal:8>') = ISNULL(it.ITEM,N'<literal:9>')                
 AND ISNULL(sc.COMPANY,N'<literal:10>') = ISNULL(it.COMPANY,N'<literal:11>')) AS ITEM_DESC,
 CARR.INTERNET_TRACKING_LINK
FROM SHIPPING_CONTAINER SC LEFT OUTER JOIN SHIPPING_CONTAINER PC 
ON PC.INTERNAL_CONTAINER_NUM = SC.PARENT, SHIPMENT_HEADER SH 
LEFT OUTER JOIN CARRIER CARR ON SH.CARRIER = CARR.CARRIER AND 
ISNULL(SH.CARRIER_SERVICE,N'<literal:12>') = ISNULL(CARR.SERVICE,N'<literal:13>') 
WHERE SC.INTERNAL_SHIPMENT_NUM = SH.INTERNAL_SHIPMENT_NUM  AND 
SC.ITEM is NULL AND SC.CONTAINER_TYPE <> N'<literal:14>'
AND (SELECT COUNT(*) FROM SHIPPING_CONTAINER SC1 WHERE SC1.PARENT = SC.INTERNAL_CONTAINER_NUM) > 0
AND SH.INTERNAL_ORDER_NUM IS NOT NULL
UNION
-- [comment omitted]
SELECT SC.INTERNAL_CONTAINER_NUM, SC.CONTAINER_ID, SC.TRACKING_NUMBER, SC.WEIGHT,
SC.STATUS, PC.CONTAINER_ID AS PARENTCONTAINERID,
SC.WAREHOUSE,                
 SC.ITEM,                
 SC.COMPANY,                
 SC.STATUS as SHIPPING_CONTAINER_STATUS,                
 SC.PARENT_CONTAINER_ID,                
 SC.QUANTITY,
 case when SC.PARENT is null then 0 else SC.PARENT end as PARENT,                
 SH.INTERNAL_ORDER_NUM, 
 (SELECT ERP_ORDER FROM ORDER_HEADER WHERE INTERNAL_ORDER_NUM = 
 CASE WHEN SH.INTERNAL_ORDER_NUM IS NULL THEN -1 ELSE SH.INTERNAL_ORDER_NUM END)  AS ERP_ORDER,
 (SELECT ORDER_DATE FROM ORDER_HEADER WHERE INTERNAL_ORDER_NUM = 
 CASE WHEN SC.INTERNAL_ORDER_NUM IS NULL THEN -1 ELSE SC.INTERNAL_ORDER_NUM END)  AS ORDER_DATE,                   
 (select it.DESCRIPTION from item it where ISNULL(sc.ITEM,N'<literal:15>') = ISNULL(it.ITEM,N'<literal:16>')                
 AND ISNULL(sc.COMPANY,N'<literal:17>') = ISNULL(it.COMPANY,N'<literal:18>')) AS ITEM_DESC, 
 CARR.INTERNET_TRACKING_LINK
FROM SHIPPING_CONTAINER SC LEFT OUTER JOIN SHIPPING_CONTAINER PC 
ON PC.INTERNAL_CONTAINER_NUM = SC.PARENT, SHIPMENT_HEADER SH
LEFT OUTER JOIN CARRIER CARR ON SH.CARRIER = CARR.CARRIER AND 
ISNULL(SH.CARRIER_SERVICE,N'<literal:19>') = ISNULL(CARR.SERVICE,N'<literal:20>')
WHERE SC.INTERNAL_SHIPMENT_NUM = SH.INTERNAL_SHIPMENT_NUM  
AND SC.ITEM is NULL  AND SC.CONTAINER_TYPE <> N'<literal:21>' 
AND 0 = (SELECT COUNT(*) FROM SHIPPING_CONTAINER SC1 WHERE SC1.PARENT = SC.INTERNAL_CONTAINER_NUM)
AND SH.INTERNAL_ORDER_NUM IS NOT NULL


UNION
-- [comment omitted]
SELECT SC.INTERNAL_CONTAINER_NUM, SC.CONTAINER_ID, SC.TRACKING_NUMBER, SC.WEIGHT,
SC.STATUS, PC.CONTAINER_ID AS PARENTCONTAINERID,
SC.WAREHOUSE,                
 SC.ITEM,                
 SC.COMPANY,                
 SC.STATUS as SHIPPING_CONTAINER_STATUS,                
 SC.PARENT_CONTAINER_ID,                
 SC.QUANTITY,
 case when SC.PARENT is null then 0 else SC.PARENT end as PARENT,                
 SH.INTERNAL_ORDER_NUM, 
 (SELECT ERP_ORDER FROM ORDER_HEADER WHERE INTERNAL_ORDER_NUM = 
 CASE WHEN SH.INTERNAL_ORDER_NUM IS NULL THEN -1 ELSE SH.INTERNAL_ORDER_NUM END)  AS ERP_ORDER,
 (SELECT ORDER_DATE FROM ORDER_HEADER WHERE INTERNAL_ORDER_NUM = 
 CASE WHEN SC.INTERNAL_ORDER_NUM IS NULL THEN -1 ELSE SC.INTERNAL_ORDER_NUM END)  AS ORDER_DATE,                   
 (select it.DESCRIPTION from item it where ISNULL(sc.ITEM,N'<literal:22>') = ISNULL(it.ITEM,N'<literal:23>')                
 AND ISNULL(sc.COMPANY,N'<literal:24>') = ISNULL(it.COMPANY,N'<literal:25>')) AS ITEM_DESC, 
 CARR.INTERNET_TRACKING_LINK
FROM SHIPPING_CONTAINER SC LEFT OUTER JOIN SHIPPING_CONTAINER PC 
ON PC.INTERNAL_CONTAINER_NUM = SC.PARENT, SHIPMENT_HEADER SH
LEFT OUTER JOIN CARRIER CARR ON SH.CARRIER = CARR.CARRIER AND 
ISNULL(SH.CARRIER_SERVICE,N'<literal:26>') = ISNULL(CARR.SERVICE,N'<literal:27>')
WHERE SC.INTERNAL_SHIPMENT_NUM = SH.INTERNAL_SHIPMENT_NUM  
AND SC.ITEM is NOT NULL  AND SC.CONTAINER_TYPE = N'<literal:28>' 
AND 0 = (SELECT COUNT(*) FROM SHIPPING_CONTAINER SC1 WHERE SC1.PARENT = SC.INTERNAL_CONTAINER_NUM)
AND SH.INTERNAL_ORDER_NUM IS NOT NULL

