-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */












CREATE VIEW METADATA_INSIGHT_WORK_ORDER_HEADER_VIEW
AS
SELECT 
	min(WH.INTERNAL_WORK_ORDER_NUM) AS INTERNALWORKORDERNUM,
	min(WH.WAREHOUSE) AS WHWAREHOUSE,
	min(WH.ITEM) AS WHITEM,
	NULL AS WHCOMPANY,
	min(WH.COMPANY) AS COMPANY,
	min(WH.REVISION_NUM) AS REVISIONNUM,
	min(WH.BUILD_LOCATION) AS BUILDLOCATION,
	min(WH.QTY_TO_BE_BUILT) AS QTYTOBEBUILT,
	min(WH.QTY_AVAIL_TO_BUILD) AS QTYAVAILTOBUILD,
	min(WH.QTY_BUILT) AS QTYBUILT,
	min(WH.QTY_TO_BE_BUILT) AS COMPLETE,
	min(WH.QTY_UM) AS QTYUM,
	min(WH.DUE_DATE) AS DUEDATE,
	min(WH.CREATED_DATE_TIME) AS CREATEDDATETIME,
	min(WH.RELEASED_DATE_TIME) AS RELEASEDDATETIME,
	min(WH.COMPLETION_DATE_TIME) AS COMPLETIONDATETIME,
	min(WH.PLANNED_UNIT_BUILD_TIME) AS PLANNEDUNITBUILDTIME,
	min(WH.MANUALLY_ENTERED) AS MANUALLYENTERED,
	min(WH.BUILD_INSTRUCTIONS) AS BUILDINSTRUCTIONS,
	min(WH.ITEM_CLASS) AS WHITEMCLASS,
	min(WH.ITEM_HEIGHT) AS WHITEMHEIGHT,
	min(WH.ITEM_LENGTH) AS WHITEMLENGTH,
	min(WH.ITEM_WIDTH) AS WHITEMWIDTH,
	min(WH.DIMENSION_UM) AS WHDIMENSIONUM,
	min(WH.VOLUME_UM) AS WHVOLUMEUM,
	min(WH.ITEM_WEIGHT) AS WHITEMWEIGHT,
	min(WH.WEIGHT_UM) AS WHWEIGHTUM,
	min(WH.ITEM_VALUE) AS WHITEMVALUE,
	min(WH.ITEM_SIZE) AS ITEMSIZE,
	min(WH.ITEM_COLOR) AS ITEMCOLOR,
	min(WH.ITEM_STYLE) AS ITEMSTYLE,
	min(WH.USER_DEF1) AS WOHEADERUSERDEF1,
	min(WH.USER_DEF2) AS WOHEADERUSERDEF2,
	min(WH.USER_DEF3) AS WOHEADERUSERDEF3,
	min(WH.USER_DEF4) AS WOHEADERUSERDEF4,
	min(WH.USER_DEF5) AS WOHEADERUSERDEF5,
	min(WH.USER_DEF6) AS WOHEADERUSERDEF6,
	min(WH.USER_DEF7) AS WOHEADERUSERDEF7,
	min(WH.USER_DEF8) AS WOHEADERUSERDEF8,
	min(WH.USER_STAMP) AS WHUSERSTAMP,
	min(WH.PROCESS_STAMP) AS WHPROCESSSTAMP,
	min(WH.DATE_TIME_STAMP) AS WHDATETIMESTAMP,
	min(WH.WORK_ORDER_ID) AS WORKORDERID,
	min(WH.ITEM_COST) AS ITEMCOST,
	min(WH.ITEM_DESC) AS WHITEMDESC,
	min(WH.IN_ALLOCATION) AS WHINALLOCATION,
	min(WH.IMMEDIATE_NEEDS_NOTE) AS WHIMMEDIATENEEDSNOTE,
	min(WH.CONDITION) AS CONDITION,
	min(WH.ALLOC_ATTEMPTED) AS ALLOCATTEMPTED,
	min(WH.IN_CONFIRMATION) AS INCONFIRMATION,
	min(WD.INTERNAL_WRK_ORD_LINE_NUM) AS INTERNALWRKORDLINENUM,
	min(WD.WAREHOUSE) AS WAREHOUSE,
	min(WD.ITEM) AS WDITEM,
	min(WD.COMPANY) AS WDCOMPANY,
	min(WD.BUILD_SEQUENCE) AS BUILDSEQUENCE,
	min(WD.BUILD_LEVEL) AS BUILDLEVEL,
	min(WD.QTY_NEEDED_PER_ITEM) AS QTYNEEDEDPERITEM,
	min(WD.TOTAL_QTY_NEEDED) AS TOTALQTYNEEDED,
	min(WD.TOTAL_QTY_USED) AS TOTALQTYUSED,
	min(WD.QUANTITY_UM) AS QUANTITYUM,
	min(WD.FROM_LOCATION) AS FROMLOCATION,
	min(WD.ALLOCATION_RULE) AS ALLOCATIONRULE,
	min(WD.LAUNCH_NUM) AS LAUNCHNUM,
	min(WD.WORK_CREATED) AS WORKCREATED,
	min(WD.ALLOCATED) AS ALLOCATED,
	min(WD.USER_DEF1) AS WODETAILUSERDEF1,
	min(WD.USER_DEF2) AS WODETAILUSERDEF2,
	min(WD.USER_DEF3) AS WODETAILUSERDEF3,
	min(WD.USER_DEF4) AS WODETAILUSERDEF4,
	min(WD.USER_DEF5) AS WODETAILUSERDEF5,
	min(WD.USER_DEF6) AS WODETAILUSERDEF6,
	min(WD.USER_DEF7) AS WODETAILUSERDEF7,
	min(WD.USER_DEF8) AS WODETAILUSERDEF8,
	min(WD.TOTAL_CONVERTED_QTY_NEEDED) AS TOTALCONVERTEDQTYNEEDED,
	min(WD.CONVERTED_UM) AS CONVERTEDUM,
	min(WD.ITEM_DESC) AS WDITEMDESC,
	min(WD.ITEM_HEIGHT) AS WDITEMHEIGHT,
	min(WD.ITEM_LENGTH) AS WDITEMLENGTH,
	min(WD.ITEM_WIDTH) AS WDITEMWIDTH,
	min(WD.DIMENSION_UM) AS WDDIMENSIONUM,
	min(WD.ITEM_WEIGHT) AS WDITEMWEIGHT,
	min(WD.WEIGHT_UM) AS WDWEIGHTUM,
	min(WD.VOLUME_UM) AS WDVOLUMEUM,
	min(WD.ITEM_VALUE) AS WDITEMVALUE,
	min(WD.ON_HAND_QTY) AS ONHANDQTY,
	min(WD.ITEM_CLASS) AS WDITEMCLASS,
	min(WD.IMMEDIATE_NEEDS_NOTE) AS WDIMMEDIATENEEDSNOTE,
	min(WD.IN_ALLOCATION) AS WDINALLOCATION,
	min(WD.LOT) AS LOT,
	min(WD.INC_QTY_ELIGIBLE) AS INCQTYELIGIBLE,
	min(WD.INC_QTY_TYPE) AS INCQTYTYPE,
	min(WD.INC_QTY_AMOUNT) AS INCQTYAMOUNT,
	min(WD.INC_QTY_MIN_AMOUNT) AS INCQTYMINAMOUNT,
	min(WD.ORIG_TOTAL_QTY_NEEDED) AS ORIGTOTALQTYNEEDED,
	min(WD.SIBLING_WRK_ORD_LIN_NUM) AS SIBLINGWRKORDLINNUM,
	min(WD.LOGISTICS_UNIT) AS LOGISTICSUNIT,
	min(WD.PARENT_LOGISTICS_UNIT) AS PARENTLOGISTICSUNIT,
	min(WD.USER_STAMP) AS WDUSERSTAMP,
	min(WD.PROCESS_STAMP) AS WDPROCESSSTAMP,
	min(WD.DATE_TIME_STAMP) AS WDDATETIMESTAMP,
	COUNT(DISTINCT(SD.INTERNAL_SHIPMENT_NUM)) AS DEPENDANTSHIPMENTCOUNT,
	CASE
         WHEN NOT EXISTS(SELECT ALLOCATED
                         FROM   WORK_ORDER_DETAIL 
                         WHERE  INTERNAL_WORK_ORDER_NUM=WH.INTERNAL_WORK_ORDER_NUM and ALLOCATED = N'<literal:1>') THEN N'<literal:2>'
         ELSE N'<literal:3>'
       END AS COMPONENTSALLOCATED,
	CASE
		WHEN EXISTS(SELECT ALLOCATED
                         FROM   WORK_ORDER_DETAIL 
                         WHERE  INTERNAL_WORK_ORDER_NUM=WH.INTERNAL_WORK_ORDER_NUM and ALLOCATED = N'<literal:4>') THEN N'<literal:5>'
						 ELSE N'<literal:6>' END AS DEALLOCATEALL,
SUM(WI.TO_QTY) AS TOTALTOQTY
FROM WORK_ORDER_HEADER WH 
LEFT OUTER JOIN WORK_ORDER_DETAIL WD ON WH.INTERNAL_WORK_ORDER_NUM = WD.INTERNAL_WORK_ORDER_NUM
LEFT OUTER JOIN SHIPMENT_DETAIL SD ON WH.INTERNAL_WORK_ORDER_NUM = SD.INTERNAL_WORK_ORDER_NUM
LEFT OUTER JOIN WORK_INSTRUCTION WI ON WI.INTERNAL_LINE_NUM = WD.INTERNAL_WRK_ORD_LINE_NUM
GROUP BY WH.INTERNAL_WORK_ORDER_NUM;