-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */





CREATE view METADATA_INSIGHT_TPM_ORDER_STATUS_VIEW
AS
SELECT 
OH.INTERNAL_ORDER_NUM,
OH.ERP_ORDER,
OH.ORDER_TYPE,
OH.WAREHOUSE,
OH.COMPANY,
OH.CUSTOMER_PO,
OH.CUSTOMER_NAME,
OH.CUSTOMER,
OH.CUSTOMER_POSTAL_CODE,
OH.SHIP_TO,
OH.SHIP_TO_POSTAL_CODE,
OH.ORDER_DATE,
OH.CONDITION AS ORDER_CONDITION,
OH.CONDITION_DATE_TIME,
od_totals.TOTAL_LINES,
sc_totals.TOTAL_CONTAINERS
FROM 
ORDER_HEADER AS OH
LEFT OUTER JOIN  
    (SELECT  INTERNAL_ORDER_NUM,   
     COUNT(INTERNAL_ORDER_DTL_NUM) AS TOTAL_LINES    
    FROM ORDER_DETAIL WITH (NOLOCK)  
    GROUP BY INTERNAL_ORDER_NUM) od_totals   
  ON OH.INTERNAL_ORDER_NUM = od_totals.INTERNAL_ORDER_NUM  
LEFT OUTER JOIN  
    (SELECT   
     INTERNAL_ORDER_NUM,   
     COUNT(INTERNAL_CONTAINER_NUM) AS TOTAL_CONTAINERS
     FROM SHIPPING_CONTAINER WITH (NOLOCK)  
    WHERE PARENT IS NULL  
    GROUP BY INTERNAL_ORDER_NUM) sc_totals   
  ON OH.INTERNAL_ORDER_NUM = sc_totals.INTERNAL_ORDER_NUM;