-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */







CREATE VIEW METADATA_INSIGHT_WORLD_EASE_GROUP_VIEW      
AS      
SELECT       
SC.WORLD_EASE_ID,        
SC.WORLD_EASE_GROUP_STATUS,       
SC.WAREHOUSE,  
SC.CONTAINER_ID,  
SH.SHIPMENT_ID,
(SELECT TOP 1 SCR.SHIPPER_CODE FROM SHIPPER_CROSS_REFERENCE SCR WHERE SCR.WAREHOUSE = SH.WAREHOUSE AND (SCR.COMPANY = SH.COMPANY OR SCR.COMPANY IS NULL) ORDER BY SCR.COMPANY DESC) AS N'<literal:1>',  
SH.INTERNAL_SHIPMENT_NUM   
FROM  SHIPPING_CONTAINER SC     
LEFT OUTER JOIN SHIPMENT_HEADER SH ON SH.INTERNAL_SHIPMENT_NUM = SC.INTERNAL_SHIPMENT_NUM      
WHERE  SC.WORLD_EASE_ID > 0 AND CONTAINER_ID IS NOT NULL;