-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */













CREATE PROCEDURE PM_WarehouseAlert
(
	@WAREHOUSE nvarchar(25) = NULL
)

AS
BEGIN
	SET NOCOUNT ON;

	IF @WAREHOUSE = N'<literal:1>'
	SET @WAREHOUSE = NULL;

	SELECT 
		WT.DESCRIPTION AS ALERT_TYPE, WAR.PRIORITY, COUNT(*) AS ALERTCOUNT, MAX(ACTIVITY_DATE_TIME) AS LATESTALERT
	FROM 
		WAREHOUSE_ALERT_REQUEST WAR, WAREHOUSE_ALERT WA, WAREHOUSE_ALERT_TYPE WT
	WHERE 
		WA.INTERNAL_ALERT_NUM = WAR.INTERNAL_ALERT_NUM 
		AND (WA.ACTION = N'<literal:2>' OR WA.ACTION = N'<literal:3>') 
		AND WAR.WAREHOUSE = ISNULL(@WAREHOUSE, WAR.WAREHOUSE)
		AND WAR.PROCESSED = N'<literal:4>'
		AND WAR.CLOSED_DATE_TIME IS NULL
		AND WAR.ALERT_TYPE = WT.ALERT_TYPE
	GROUP BY WAR.PRIORITY,WT.DESCRIPTION
	ORDER BY WAR.PRIORITY;
END -- [comment omitted]



