-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */





CREATE VIEW METADATA_RECEIPT_QUALITY_HISTORY
AS SELECT RQH.*,GCD.DESCRIPTION,  RH.COMPANY, RH.CARRIER_SERVICE
FROM RECEIPT_QUALITY_HISTORY RQH left join  GENERIC_CONFIG_DETAIL GCD on ( RQH.REASON_CODE = GCD.IDENTIFIER  OR RQH.REASON_CODE= GCD.DESCRIPTION)
left join RECEIPT_HEADER RH on RQH.INTERNAL_RECEIPT_NUM = RH.INTERNAL_RECEIPT_NUM
WHERE  GCD.RECORD_TYPE=N'<literal:1>'