-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */



	

CREATE PROCEDURE SHP_GetStatusFlowFromContainer(
	@internalContainerNum numeric(9))
AS
BEGIN
	WITH CTE (INTERNAL_CONTAINER_NUM, CONTAINER_TYPE, PARENT, STATUS_FLOW_NAME) AS 
	(
	SELECT INTERNAL_CONTAINER_NUM, CONTAINER_TYPE, PARENT, STATUS_FLOW_NAME FROM SHIPPING_CONTAINER SCA WHERE INTERNAL_CONTAINER_NUM = @internalContainerNum
	UNION ALL 
	SELECT SC.INTERNAL_CONTAINER_NUM, SC.CONTAINER_TYPE, SC.PARENT, SC.STATUS_FLOW_NAME FROM CTE JOIN SHIPPING_CONTAINER SC ON SC.PARENT=CTE.INTERNAL_CONTAINER_NUM
	) 
	SELECT TOP 1 CTE.STATUS_FLOW_NAME FROM CTE WHERE CTE.STATUS_FLOW_NAME IS NOT NULL 
END