-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */





CREATE VIEW METADATA_TRANS_WAVE_FLOW_VIEW
AS
SELECT
LAUNCH_FLOW_HEADER.LAUNCH_FLOW AS WAVEFLOW,
LAUNCH_FLOW_HEADER.DESCRIPTION
FROM LAUNCH_FLOW_HEADER
WHERE ACTIVE=N'<literal:1>';