-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */








CREATE VIEW METADATA_TRANS_WAVE_MASTER_VIEW
AS
SELECT DISTINCT
LAM.LAUNCH_NAME AS WAVENAME,
LAM.DESCRIPTION,
LAM.LAUNCH_FLOW AS WAVEFLOW,
LAM.AUTHORIZED_WAREHOUSES,
WMA.LAUNCH_NAME AS AUTHORIZEDWAVENAME,
WMA.WAREHOUSE AS AUTHORIZEDWAREHOUSE,
LAM.PRIORITY AS PRIORITY,
LAM.LAUNCH_MODE AS LAUNCHMODE
FROM LAUNCH_MASTER LAM
LEFT OUTER JOIN WAVE_MASTER_AUTHORIZED_WAREHOUSES WMA ON LAM.LAUNCH_NAME = WMA.LAUNCH_NAME
WHERE ACTIVE=N'<literal:1>';