-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */





CREATE VIEW MOVEMENT_CLASS_ANALYSIS_UM_VIEW AS
SELECT
   ISNULL(ITEM.INTERNAL_ITEM_NUM,
   GENERIC_CONFIG_DETAIL.OBJECT_ID)  AS OBJECT_ID,
   ITEM_UNIT_OF_MEASURE.ITEM,
   ITEM_UNIT_OF_MEASURE.COMPANY,
   ITEM_UNIT_OF_MEASURE.ITEM_CLASS,
   ITEM_UNIT_OF_MEASURE.SEQUENCE,
   ITEM_UNIT_OF_MEASURE.CONVERSION_QTY,
   ITEM_UNIT_OF_MEASURE.QUANTITY_UM,
   ITEM_UNIT_OF_MEASURE.MOVEMENT_CLS,
   ITEM_UNIT_OF_MEASURE.LENGTH,
   ITEM_UNIT_OF_MEASURE.WIDTH,
   ITEM_UNIT_OF_MEASURE.HEIGHT,
   ITEM_UNIT_OF_MEASURE.DIMENSION_UM,
   ITEM_UNIT_OF_MEASURE.WEIGHT,
   ITEM_UNIT_OF_MEASURE.WEIGHT_UM
FROM
   ITEM_UNIT_OF_MEASURE WITH(NOLOCK)  LEFT OUTER JOIN ITEM WITH(NOLOCK)  ON ITEM.ITEM=ITEM_UNIT_OF_MEASURE.ITEM
   AND (ISNULL(ITEM.COMPANY,
   N'<literal:1>') =ISNULL(ITEM_UNIT_OF_MEASURE.COMPANY,
   N'<literal:2>')  OR (ITEM.ITEM=ITEM_UNIT_OF_MEASURE.ITEM
   AND ITEM.COMPANY IS NULL) )  LEFT OUTER JOIN GENERIC_CONFIG_DETAIL WITH(NOLOCK)  ON GENERIC_CONFIG_DETAIL.IDENTIFIER=ITEM_UNIT_OF_MEASURE.ITEM_CLASS
   AND GENERIC_CONFIG_DETAIL.RECORD_TYPE=N'<literal:3>';