-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */









CREATE PROCEDURE SHP_MonitorCustomerCategoryChartData
@filterCriteria NVARCHAR(MAX),
@culture NVARCHAR(10) 
AS
    SET NOCOUNT ON
	DECLARE @warehouse as NVARCHAR(50);
	DECLARE @customerCat1 as NVARCHAR(50);
  
	DECLARE @criteriaTempTable TABLE (
   filterName NVARCHAR(300),
   filterValue NVARCHAR(300))

 /* [comment omitted] */
  INSERT INTO @criteriaTempTable SELECT * FROM fn_GetMonitorFilterParameters(@filterCriteria)

  SELECT @warehouse = filterValue FROM @criteriaTempTable WHERE filterName = N'<literal:1>'
  SELECT @customerCat1 = filterValue from @criteriaTempTable WHERE filterName = N'<literal:2>'

   DECLARE @Unassign NVARCHAR(2000);
  SET @Unassign=  dbo.RSCMfn_RtrvResource(N'<literal:3>',N'<literal:4>',@culture)

   IF(@customerCat1 = @Unassign)
	SET @customerCat1 = NULL;

SELECT N'<literal:5>' AS CHARTDATA_MonitorCustomerCategory, 
CATEGORY = CASE WHEN  CUSTOMER_NAME IS NULL THEN dbo.RSCMfn_RtrvResource(N'<literal:6>',N'<literal:7>',@culture) ELSE  CUSTOMER_NAME END,
COUNT(DISTINCT(INTERNAL_SHIPMENT_NUM)) AS N'<literal:8>' ,
DESCRIPTION = CASE WHEN  CUSTOMER_NAME IS NULL THEN NULL ELSE CUSTOMER_NAME END,
N'<literal:9>' AS XAXISTITLE, 
N'<literal:10>' AS YAXISTITLE, 
2 AS NextDrillDownLevel, 
N'<literal:11>' AS CHARTTITLE
FROM Metadata_Insight_Shipment_View WHERE WAREHOUSE=@warehouse AND 
((@customerCat1 is null AND CUSTOMER_CATEGORY1 is null ) OR CUSTOMER_CATEGORY1=@customerCat1) AND SHIPMENT_HEADER_TRAILING_STS <900 
GROUP BY CUSTOMER_NAME 
order  by COUNT(DISTINCT(INTERNAL_SHIPMENT_NUM)) DESC,CUSTOMER_NAME 

/* [comment omitted] */
DECLARE @TOTAL_SHIPMENTS INT=0,@TOTAL_SHIPPING_LOAD INT=0,@WIP_SHIPMENTS INT=0,@SHIPMENT_NOT_PICKING INT=0;

SELECT @TOTAL_SHIPMENTS = COUNT(DISTINCT(INTERNAL_SHIPMENT_NUM)) ,
	   @TOTAL_SHIPPING_LOAD =COUNT(DISTINCT(SHIPPING_LOAD_NUM)) FROM Metadata_Insight_Shipment_View WHERE WAREHOUSE=@warehouse and ((@customerCat1 is null AND CUSTOMER_CATEGORY1 is null ) OR CUSTOMER_CATEGORY1=@customerCat1) AND SHIPMENT_HEADER_TRAILING_STS <900 ;
SELECT @WIP_SHIPMENTS =COUNT(DISTINCT(INTERNAL_SHIPMENT_NUM)) FROM Metadata_Insight_Shipment_View WHERE WAREHOUSE=@warehouse  AND ((@customerCat1 is null AND CUSTOMER_CATEGORY1 is null ) OR CUSTOMER_CATEGORY1=@customerCat1) 
AND SHIPMENT_HEADER_LEADING_STS>300 AND SHIPMENT_HEADER_TRAILING_STS <700 ;
SELECT @SHIPMENT_NOT_PICKING=COUNT(DISTINCT(INTERNAL_SHIPMENT_NUM)) FROM Metadata_Insight_Shipment_View WHERE WAREHOUSE=@warehouse 
AND ((@customerCat1 is null AND CUSTOMER_CATEGORY1 is null ) OR CUSTOMER_CATEGORY1=@customerCat1)
AND SHIPMENT_HEADER_TRAILING_STS =300 AND SHIPMENT_HEADER_LEADING_STS =300;

SELECT TOP 1 N'<literal:12>' AS SUMMARYTILE_TOTAL_SHIPMENTS,  @TOTAL_SHIPMENTS AS TOTAL_SHIPMENTS;
SELECT TOP 1 N'<literal:13>' AS SUMMARYTILE_TOTAL_SHIPPING_LOADS,  @TOTAL_SHIPPING_LOAD AS TOTAL_SHIPPING_LOADS;
SELECT TOP 1 N'<literal:14>' AS SUMMARYTILE_WIP_SHIPMENTS,  @WIP_SHIPMENTS AS WIP_SHIPMENTS;
SELECT TOP 1 N'<literal:15>' AS SUMMARYTILE_SHIPMENTS_NOT_STARTED_PICKING, @SHIPMENT_NOT_PICKING AS SHIPMENTS_NOT_STARTED_PICKING;