-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */



	

CREATE PROCEDURE PMN_LoadConfirmActivity (
	@startDateTime datetime,
	@endDateTime datetime
	)
AS
 
WITH INTERVALTABLE
AS
(
	SELECT @startDateTime AS INTERVAL_DATE_TIME
	
	UNION ALL
	
	SELECT DATEADD(SS, 30, INTERVAL_DATE_TIME)
	FROM INTERVALTABLE
	WHERE DATEADD(SS, 30, INTERVAL_DATE_TIME) < @endDateTime
) 
 
SELECT INTERVALTABLE.INTERVAL_DATE_TIME, 
	ISNULL(COUNT(DISTINCT SHV.SHIPPING_LOAD_NUM), 0) AS LOADS_WITH_SHIPMENTS_CONFIRMED, 
	ISNULL(COUNT(DISTINCT SHV.INTERNAL_SHIPMENT_NUM), 0) AS SHIPMENTS_CONFIRMED, 
	SUM(ISNULL(SHV.TOTAL_LINES, 0)) AS LINES_CONFIRMED, 
	SUM(ISNULL(SHV.TOTAL_CONTAINERS, 0)) AS CONTAINERS_CONFIRMED 
FROM INTERVALTABLE 
	LEFT OUTER JOIN SHIPMENT_HEADER_VIEW SHV 
	ON SHV.ACTUAL_SHIP_DATE_TIME >= DATEADD(SS, -30, INTERVALTABLE.INTERVAL_DATE_TIME) 
	AND SHV.ACTUAL_SHIP_DATE_TIME < INTERVALTABLE.INTERVAL_DATE_TIME 
GROUP BY INTERVALTABLE.INTERVAL_DATE_TIME
ORDER BY INTERVALTABLE.INTERVAL_DATE_TIME
OPTION (MAXRECURSION 0)


