-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */





CREATE VIEW PURCHASE_ORDER_DETAIL_VIEW
AS
select 
	POD.COMPANY,	
	POD.DATE_TIME_STAMP,	
	POD.ITEM,	
	POD.ITEM_CATEGORY1,	
	POD.ITEM_CATEGORY10,	
	POD.ITEM_CATEGORY2,	
	POD.ITEM_CATEGORY3,	
	POD.ITEM_CATEGORY4,	
	POD.ITEM_CATEGORY5,	
	POD.ITEM_CATEGORY6,	
	POD.ITEM_CATEGORY7,	
	POD.ITEM_CATEGORY8,	
	POD.ITEM_CATEGORY9,	
	POD.ITEM_CLASS,	
	POD.ITEM_COLOR,	
	POD.ITEM_DEPARTMENT,	
	POD.ITEM_DESC,	
	POD.ITEM_DIMENSION_UM,	
	POD.ITEM_DIVISION,	
	POD.ITEM_HEIGHT,	
	POD.ITEM_LENGTH,	
	POD.ITEM_LIST_PRICE,	
	POD.ITEM_NET_PRICE,	
	POD.ITEM_SIZE,	
	POD.ITEM_STYLE,	
	POD.ITEM_WEIGHT,	
	POD.ITEM_WIDTH,	
	POD.LINE_NUMBER,	
	POD.OBJECT_ID,	
	POD.OPEN_QUANTITY,	
	POD.PROCESS_STAMP,	
	POD.PURCHASE_ORDER_ID,	
	POD.PURCHASE_ORDER_OBJECT_ID,	
	POD.QUANTITY_UM,	
	POD.TOTAL_QUANTITY,	
	POD.USER_DEF1,	
	POD.USER_DEF2,	
	POD.USER_DEF3,	
	POD.USER_DEF4,	
	POD.USER_DEF5,	
	POD.USER_DEF6,	
	POD.USER_DEF7,	
	POD.USER_DEF8,	
	POD.USER_STAMP,	
	POD.WEIGHT_UM,		
	POH.Warehouse
from
	PURCHASE_ORDER_DETAIL POD left outer join
	PURCHASE_ORDER_HEADER POH
	on POD.PURCHASE_ORDER_OBJECT_ID = POH.OBJECT_ID;