-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */








CREATE PROCEDURE SHP_MonitorShipmentChartData
@filterCriteria NVARCHAR(MAX),
@culture NVARCHAR(10) 
AS
    SET NOCOUNT ON
	DECLARE @warehouse as NVARCHAR(50);
	DECLARE @criteriaTempTable TABLE (
   filterName NVARCHAR(300),
   filterValue NVARCHAR(300))

 /* [comment omitted] */
  INSERT INTO @criteriaTempTable SELECT * FROM fn_GetMonitorFilterParameters(@filterCriteria)

  SELECT @warehouse = filterValue FROM @criteriaTempTable WHERE filterName = N'<literal:1>'

SELECT N'<literal:2>' AS CHARTDATA_MonitorShipment,  
CATEGORY = CASE WHEN  CUSTOMER_CATEGORY1 IS NULL THEN dbo.RSCMfn_RtrvResource(N'<literal:3>',N'<literal:4>',@culture) ELSE  CUSTOMER_CATEGORY1 END,
COUNT(DISTINCT(INTERNAL_SHIPMENT_NUM)) AS N'<literal:5>' ,
DESCRIPTION = CASE WHEN  CUSTOMER_CATEGORY1 IS NULL THEN N'<literal:6>' ELSE CUSTOMER_CATEGORY1 END,
N'<literal:7>' AS XAXISTITLE, 
N'<literal:8>' AS YAXISTITLE, 
1 AS NextDrillDownLevel, 
N'<literal:9>' AS CHARTTITLE
FROM Metadata_Insight_Shipment_View WHERE WAREHOUSE=@warehouse and SHIPMENT_HEADER_TRAILING_STS < 900  GROUP BY  CUSTOMER_CATEGORY1

/* [comment omitted] */
DECLARE @TOTAL_SHIPMENTS INT=0,@TOTAL_SHIPPING_LOAD INT=0,@WIP_SHIPMENTS INT=0,@SHIPMENT_NOT_PICKING INT=0;

SELECT @TOTAL_SHIPMENTS = COUNT(DISTINCT(INTERNAL_SHIPMENT_NUM)) ,
	   @TOTAL_SHIPPING_LOAD =COUNT(DISTINCT(SHIPPING_LOAD_NUM)) FROM Metadata_Insight_Shipment_View WHERE WAREHOUSE=@warehouse and SHIPMENT_HEADER_TRAILING_STS <900 ;
SELECT @WIP_SHIPMENTS =COUNT(DISTINCT(INTERNAL_SHIPMENT_NUM)) FROM Metadata_Insight_Shipment_View WHERE WAREHOUSE=@warehouse AND SHIPMENT_HEADER_LEADING_STS>300 AND SHIPMENT_HEADER_TRAILING_STS <700; 
SELECT @SHIPMENT_NOT_PICKING=COUNT(DISTINCT(INTERNAL_SHIPMENT_NUM)) FROM Metadata_Insight_Shipment_View WHERE WAREHOUSE=@warehouse AND SHIPMENT_HEADER_TRAILING_STS =300 AND SHIPMENT_HEADER_LEADING_STS =300;

SELECT TOP 1 N'<literal:10>' AS SUMMARYTILE_TOTAL_SHIPMENTS,  @TOTAL_SHIPMENTS AS TOTAL_SHIPMENTS;
SELECT TOP 1 N'<literal:11>' AS SUMMARYTILE_TOTAL_SHIPPING_LOADS,  @TOTAL_SHIPPING_LOAD AS TOTAL_SHIPPING_LOADS;
SELECT TOP 1 N'<literal:12>' AS SUMMARYTILE_WIP_SHIPMENTS,  @WIP_SHIPMENTS AS WIP_SHIPMENTS;
SELECT TOP 1 N'<literal:13>' AS SUMMARYTILE_SHIPMENTS_NOT_STARTED_PICKING, @SHIPMENT_NOT_PICKING AS SHIPMENTS_NOT_STARTED_PICKING;
