-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */





CREATE VIEW PURCHASE_ORDER_HEADER_VIEW
AS
select 	
	max(POH.CLOSED_DATE_TIME) AS CLOSED_DATE_TIME,
	max(POH.COMPANY) AS COMPANY,
	max(POH.CREATED_DATE_TIME) AS CREATED_DATE_TIME,
	max(POH.DATE_TIME_STAMP) AS DATE_TIME_STAMP,
	max(POH.OBJECT_ID) AS OBJECT_ID,
	max(POH.PROCESS_STAMP) AS PROCESS_STAMP,
	max(POH.PURCHASE_ORDER_ID) AS PURCHASE_ORDER_ID,
	max(POH.RECEIPT_TYPE) AS RECEIPT_TYPE,
	max(POH.SHIP_FROM) AS SHIP_FROM,
	max(POH.SHIP_FROM_ADDRESS1) AS SHIP_FROM_ADDRESS1,
	max(POH.SHIP_FROM_ADDRESS2) AS SHIP_FROM_ADDRESS2,
	max(POH.SHIP_FROM_ADDRESS3) AS SHIP_FROM_ADDRESS3,
	max(POH.SHIP_FROM_ATTENTION_TO) AS SHIP_FROM_ATTENTION_TO,
	max(POH.SHIP_FROM_CITY) AS SHIP_FROM_CITY,
	max(POH.SHIP_FROM_COUNTRY) AS SHIP_FROM_COUNTRY,
	max(POH.SHIP_FROM_EMAIL_ADDRESS) AS SHIP_FROM_EMAIL_ADDRESS,
	max(POH.SHIP_FROM_FAX_NUM) AS SHIP_FROM_FAX_NUM,
	max(POH.SHIP_FROM_NAME) AS SHIP_FROM_NAME,
	max(POH.SHIP_FROM_PHONE_NUM) AS SHIP_FROM_PHONE_NUM,
	max(POH.SHIP_FROM_POSTAL_CODE) AS SHIP_FROM_POSTAL_CODE,
	max(POH.SHIP_FROM_STATE) AS SHIP_FROM_STATE,
	max(POH.SOURCE_ADDRESS1) AS SOURCE_ADDRESS1,
	max(POH.SOURCE_ADDRESS2) AS SOURCE_ADDRESS2,
	max(POH.SOURCE_ADDRESS3) AS SOURCE_ADDRESS3,
	max(POH.SOURCE_ATTENTION_TO) AS SOURCE_ATTENTION_TO,
	max(POH.SOURCE_CITY) AS SOURCE_CITY,
	max(POH.SOURCE_COUNTRY) AS SOURCE_COUNTRY,
	max(POH.SOURCE_EMAIL_ADDRESS) AS SOURCE_EMAIL_ADDRESS,
	max(POH.SOURCE_FAX_NUM) AS SOURCE_FAX_NUM,
	max(POH.SOURCE_ID) AS SOURCE_ID,
	max(POH.SOURCE_NAME) AS SOURCE_NAME,
	max(POH.SOURCE_PHONE_NUM) AS SOURCE_PHONE_NUM,
	max(POH.SOURCE_POSTAL_CODE) AS SOURCE_POSTAL_CODE,
	max(POH.SOURCE_STATE) AS SOURCE_STATE,
	max(POH.STATUS) AS STATUS,
	max(POH.USER_DEF1) AS USER_DEF1,
	max(POH.USER_DEF2) AS USER_DEF2,
	max(POH.USER_DEF3) AS USER_DEF3,
	max(POH.USER_DEF4) AS USER_DEF4,
	max(POH.USER_DEF5) AS USER_DEF5,
	max(POH.USER_DEF6) AS USER_DEF6,
	max(POH.USER_DEF7) AS USER_DEF7,
	max(POH.USER_DEF8) AS USER_DEF8,
	max(POH.USER_STAMP) AS USER_STAMP,
	max(POH.WAREHOUSE) AS WAREHOUSE,
	count(POD.OBJECT_ID) as TOTAL_LINES,
	ISNULL(sum(POD.TOTAL_QUANTITY), 0) as TOTAL_QUANTITY,
	ISNULL(sum(POD.OPEN_QUANTITY), 0) as OPEN_QUANTITY,
	ISNULL(sum(POD.TOTAL_QUANTITY * POD.ITEM_WEIGHT), 0) as TOTAL_WEIGHT,
	ISNULL(sum(POD.TOTAL_QUANTITY * POD.ITEM_NET_PRICE), 0) as TOTAL_VALUE,
	ISNULL(sum(POD.TOTAL_QUANTITY * POD.ITEM_LENGTH * POD.ITEM_WIDTH * POD.ITEM_HEIGHT), 0) as TOTAL_VOLUME,
	max(POD.WEIGHT_UM) as WEIGHT_UM
from
	PURCHASE_ORDER_HEADER POH left outer join PURCHASE_ORDER_DETAIL POD
	on POH.OBJECT_ID = POD.PURCHASE_ORDER_OBJECT_ID
group by
	POH.OBJECT_ID;