-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */



 
  
  
CREATE VIEW METADATA_INSIGHT_TRAN_HIST_VIEW  
AS  
SELECT  
    TH.INTERNAL_ID,  
    TH.WAREHOUSE,  
    TH.TRANSACTION_TYPE,  
    TH.WORK_TYPE,  
    TH.WORK_GROUP,  
    TH.USER_NAME,  
    TH.WORK_TEAM AS WORKTEAM,  
    TH.EQUIPMENT_TYPE AS EQUIPMENTTYPE,  
    TH.LOCATION,  
    TH.ITEM,  
    TH.COMPANY,  
    TH.LOT,  
    TH.QUANTITY,  
    TH.QUANTITY_UM,  
    TH.INTERNAL_KEY_ID,  
    TH.WORK_UNIT,  
    TH.REFERENCE_ID,  
    TH.REFERENCE_LINE_NUM,  
    TH.BEFORE_IN_TRANSIT_QTY AS BEFOREINTRANSITQTY,  
    TH.BEFORE_ON_HAND_QTY AS BEFOREONHANDQTY,  
    TH.BEFORE_ALLOC_QTY AS BEFOREALLOCQTY,  
    TH.BEFORE_SUSPENSE_QTY AS BEFORESUSPENSEQTY,  
    TH.AFTER_ON_HAND_QTY AS AFTERONHANDQTY,  
    TH.AFTER_IN_TRANSIT_QTY AS AFTERINTRANSITQTY,  
    TH.AFTER_ALLOC_QTY AS AFTERALLOCQTY,  
    TH.AFTER_SUSPENSE_QTY AS AFTERSUSPENSEQTY,  
    TH.USER_DEF1 AS UDTRANSHIST01,  
    TH.USER_DEF2 AS UDTRANSHIST02,  
    TH.USER_DEF3 AS UDTRANSHIST03,  
    TH.USER_DEF4 AS UDTRANSHIST04,  
    TH.USER_DEF5 AS UDTRANSHIST05,  
    TH.USER_DEF6 AS UDTRANSHIST06,  
    TH.USER_DEF7 AS UDTRANSHIST07,  
    TH.USER_DEF8 AS UDTRANSHIST08,  
    TH.USER_STAMP AS USERSTAMP,  
    TH.PROCESS_STAMP,  
    TH.DATE_TIME_STAMP,  
    TH.REFERENCE_TYPE,  
    TH.WORK_ZONE,  
    TH.BEFORE_STS AS BEFORESTS,  
    TH.AFTER_STS AS AFTERSTS,  
    TH.UPLOAD_INTERFACE_BATCH,  
    TH.ACTIVITY_DATE_TIME AS TRANSHISTACTIVITYDATETIME,  
    TH.DIRECTION,  
    TH.ORIGINAL_LOCATION,  
    TH.CONTAINER_ID,  
    TH.BEFORE_EXPIRATION_DATE AS BEFOREEXPDATE,  
    TH.AFTER_EXPIRATION_DATE AS AFTEREXPDATE,  
    TH.TO_COMPANY AS TOCOMPANY,  
    TH.TO_WAREHOUSE AS TOWAREHOUSE,  
    TH.INTERNAL_CONTAINER_NUM,   
    TRY_CAST(THA.CATCH_WEIGHT AS NUMERIC(14,5)) AS [CATCH_WEIGHT],  
    THA.CATCH_WEIGHT_UM AS [CATCH_WEIGHT_UM],  
    SN.SERIAL_NUMBER  
FROM TRANSACTION_HISTORY TH    
OUTER APPLY (  
    SELECT  
        (CASE WHEN ATTRIBUTE_TYPE = N'<literal:1>'  
                 THEN ATTRIBUTE_VALUE END) AS SERIAL_OBJ_ID,  
        (CASE WHEN ATTRIBUTE_TYPE = N'<literal:2>'  
                 THEN ATTRIBUTE_VALUE END) AS CATCH_WEIGHT,  
        (CASE WHEN ATTRIBUTE_TYPE = N'<literal:3>'  
                 THEN ATTRIBUTE_VALUE END) AS CATCH_WEIGHT_UM  
    FROM TRANS_HIST_ATTRIBUTES  
    WHERE LINK_ID = TH.INTERNAL_ID  
) THA  

LEFT JOIN SERIAL_NUMBER_VIEW SN  

    ON THA.SERIAL_OBJ_ID = SN.OBJECT_ID;

