-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */






CREATE VIEW METADATA_TRANS_MANUAL_REPLENISHMENT_VIEW
AS
SELECT    
rpm.REPLENISHMENT_NAME AS NAME,      
rpm.DESCRIPTION,    
rpm.WAREHOUSE_AUTHORIZATION,  
rpma.WAREHOUSE AS AUTHORIZEDWAREHOUSE,  
rpma.REPLENISHMENT_NAME AS AUTHORIZEDREPLENISHMENTNAME  
FROM REPLENISHMENT_MASTER  rpm    
LEFT JOIN REPLENISHMENT_MASTER_WAREHOUSE_ACCESS rpma on rpm.REPLENISHMENT_NAME=rpma.REPLENISHMENT_NAME  
AND rpm.WAREHOUSE_AUTHORIZATION <> N'<literal:1>' 
WHERE REPLENISHMENT_MODES like N'<literal:2>'  AND Active=N'<literal:3>'