-- DOCUMENTATION ONLY: literals/comments removed; do not execute.



CREATE view TRAV_METADATA_INSIGHT_SHIPMENT_POOL_VIEW AS 
	SELECT   sh.INTERNAL_SHIPMENT_NUM, sh.WAREHOUSE, sh.SHIPPING_LOAD_NUM, sh.SHIPMENT_ID, sh.LAUNCH_STEP, sh.TRAILING_STS AS SHIPMENT_HEADER_TRAILING_STS, sh.TRAILING_STS_DATE AS SHIPMENT_HEADER_TRAILING_STS_DATE, sh.TRAILING_STS_FAILED AS SHIPMENT_HEADER_TRAILING_STS_FAILED, 
             sh.ORDER_TYPE AS SHIPMENT_HEADER_ORDER_TYPE, sh.CONSOLIDATED, sh.LEADING_STS AS SHIPMENT_HEADER_LEADING_STS, sh.LEADING_STS_DATE AS SHIPMENT_HEADER_LEADING_STS_DATE, sh.CARRIER AS SHIPMENT_HEADER_CARRIER, 
             sh.LEADING_STS_FAILED AS SHIPMENT_HEADER_LEADING_STS_FAILED, sh.COMPANY, sh.CARRIER_SERVICE, sh.CARRIER_GROUP, sh.CARRIER_TYPE, sh.FREIGHT_TERMS, sh.LIABILITY_TERMS, sh.CUSTOMER, sh.SHIP_TO, sh.ROUTE AS SHIPMENT_HEADER_ROUTE, sh.STOP, sh.SHIP_TO_ADDRESS1, 
             sh.CUSTOMER_NAME, sh.SHIP_TO_ADDRESS2, sh.SHIP_TO_ADDRESS3, sh.SHIP_TO_CITY, sh.SHIP_TO_STATE, sh.SHIP_TO_COUNTRY, sh.SHIP_TO_POSTAL_CODE, sh.SHIP_TO_PHONE_NUM, sh.SHIP_TO_FAX_NUM, sh.TOTAL_CONTAINERS, sh.TOTAL_LINES, sh.CUSTOMER_ADDRESS1, sh.LAUNCH_NUM, 
             sh.WEIGHT_UM AS SHIPMENT_HEADER_WEIGHT_UM, sh.TOTAL_WEIGHT, SUM(sh.total_weight) OVER (PARTITION BY sh.customer) AS total_customer_weight, sh.TOTAL_VOLUME, sh.VOLUME_UM AS SHIPMENT_HEADER_VOLUME_UM, sh.ROUTING_CODE, sh.TOTAL_VALUE, sh.SINGLE_ITEM_CARTONS, sh.USER_DEF1 AS SHIPMENT_HEADER_USER_DEF1, 
             sh.USER_DEF2 AS SHIPMENT_HEADER_USER_DEF2, sh.PRIORITY AS SHIPMENT_HEADER_PRIORITY, sh.USER_DEF3 AS SHIPMENT_HEADER_USER_DEF3, sh.USER_DEF4 AS SHIPMENT_HEADER_USER_DEF4, sh.USER_DEF5 AS SHIPMENT_HEADER_USER_DEF5, sh.USER_DEF6 AS SHIPMENT_HEADER_USER_DEF6, 
             sh.USER_DEF7 AS SHIPMENT_HEADER_USER_DEF7, sh.MANUALLY_ENTERED AS SHIPMENT_HEADER_MANUALLY_ENTERED, sh.USER_DEF8 AS SHIPMENT_HEADER_USER_DEF8, sh.USER_STAMP AS SHIPMENT_HEADER_USER_STAMP, sh.PROCESS_STAMP AS SHIPMENT_HEADER_PROCESS_STAMP, 
             sh.DATE_TIME_STAMP AS SHIPMENT_HEADER_DATE_TIME_STAMP, sh.BOL_NUM_ALPHA, sh.PRO_NUM_ALPHA AS SHIPMENT_HEADER_PRO_NUM_ALPHA, sh.CUSTOMER_ADDRESS3, sh.CUSTOMER_ADDRESS2, sh.CUSTOMER_ATTENTION_TO, sh.CUSTOMER_CITY, sh.CUSTOMER_STATE, sh.CUSTOMER_COUNTRY, 
             sh.CUSTOMER_POSTAL_CODE, sh.CUSTOMER_PHONE_NUM, sh.CUSTOMER_FAX_NUM, sh.CUSTOMER_EMAIL_ADDRESS, sh.SHIP_TO_NAME, sh.SHIP_TO_ATTENTION_TO, sh.SHIP_TO_EMAIL_ADDRESS, sh.REQUESTED_DELIVERY_DATE, sh.REQUESTED_DELIVERY_TYPE, sh.SCHEDULED_SHIP_DATE, 
             sh.PLANNED_SHIP_DATE, sh.ACTUAL_SHIP_DATE_TIME AS SHIPMENT_HEADER_ACTUAL_SHIP_DATE_TIME, sh.PLANNED_DELIVERY_DATE_TIME, sh.ACTUAL_DELIVERY_DATE_TIME, sh.TOTAL_QTY AS SHIPMENT_HEADER_TOTAL_QTY, sh.QUANTITY_UM, 
             sh.TOTAL_FREIGHT_CHARGE AS SHIPMENT_HEADER_TOTAL_FREIGHT_CHARGE, sh.BASE_FREIGHT_CHARGE AS SHIPMENT_HEADER_BASE_FREIGHT_CHARGE, sh.FREIGHT_DISCOUNT AS SHIPMENT_HEADER_FREIGHT_DISCOUNT, sh.ACCESSORIAL_CHARGE AS SHIPMENT_HEADER_ACCESSORIAL_CHARGE, 
             sh.CONSOLIDATION_ALLOWED, sh.INTERMEDIATE_CONSIGNEE, sh.INTERMEDIATE_NAME, sh.INTERMEDIATE_ADDRESS1, sh.INTERMEDIATE_ADDRESS2, sh.INTERMEDIATE_ADDRESS3, sh.INTERMEDIATE_ATTENTION_TO, sh.INTERMEDIATE_CITY, sh.INTERMEDIATE_STATE, sh.INTERMEDIATE_COUNTRY, 
             sh.INTERMEDIATE_POSTAL_CODE, sh.INTERMEDIATE_PHONE_NUM, sh.INTERMEDIATE_FAX_NUM, sh.INTERMEDIATE_EMAIL_ADDRESS, sh.FREIGHT_BILL_TO, sh.FREIGHT_BILL_TO_NAME, sh.FREIGHT_BILL_TO_ADDRESS1, sh.FREIGHT_BILL_TO_ADDRESS2, sh.FREIGHT_BILL_TO_ADDRESS3, 
             sh.FREIGHT_BILL_TO_ATTENTION_TO, sh.FREIGHT_BILL_TO_CITY, sh.FREIGHT_BILL_TO_STATE, sh.FREIGHT_BILL_TO_COUNTRY, sh.FREIGHT_BILL_TO_POSTAL_CODE, sh.FREIGHT_BILL_TO_PHONE_NUM, sh.FREIGHT_BILL_TO_FAX_NUM, sh.FREIGHT_BILL_TO_EMAIL_ADDRESS, 
             sh.ERP_ORDER AS SHIPMENT_HEADER_ERP_ORDER, sh.INTERNAL_ORDER_NUM, sh.EXPORT_TAX_ID, sh.PARTIES, sh.LOADING_PIER, sh.TRANSPORTATION_MODE, sh.EXPORT_PORT, sh.UNLOADING_PORT, sh.CONTAINERIZED, sh.FTZ, sh.VALIDATED_LICENSE AS SHIPMENT_HEADER_VALIDATED_LICENSE, 
             sh.LICENSE_EXP_DATE AS SHIPMENT_HEADER_LICENSE_EXP_DATE, sh.ECCN AS SHIPMENT_HEADER_ECCN, sh.AUTHORIZED_EMPL_NAME, sh.AUTHORIZED_EMPL_TITLE, sh.UPLOAD_INTERFACE_BATCH, sh.CUSTOMER_RESIDENTIAL_FLAG, sh.SHIPTO_RESIDENTIAL_FLAG, sh.REJECTION_NOTE, 
             sh.INTERFACE_RECORD_ID AS SHIPMENT_HEADER_INTERFACE_RECORD_ID, sh.CUSTOMER_CATEGORY1, sh.CUSTOMER_CATEGORY2, sh.CUSTOMER_CATEGORY3, sh.CUSTOMER_CATEGORY4, sh.CUSTOMER_CATEGORY5, sh.CUSTOMER_CATEGORY6, sh.CUSTOMER_CATEGORY7, sh.CUSTOMER_CATEGORY8, 
             sh.CUSTOMER_CATEGORY9, sh.CUSTOMER_CATEGORY10, sh.CONSOLIDATION_DOCK_LOC_AREA, sh.CONSOLIDATION_DOCK_LOC_POS, sh.PROCESS_TYPE, sh.CREATION_PROCESS_STAMP, sh.CREATION_DATE_TIME_STAMP, sh.IMMEDIATE_NEEDS_NOTE AS SHIPMENT_HEADER_IMMEDIATE_NEEDS_NOTE, 
             sh.ALLOCATE_COMPLETE, sh.ALTERNATE_EMAIL_ADDRESS, sh.STOP_SEQUENCE, sh.INTERNAL_CARRIER_NUM, sh.STORE_DISTRIBUTION AS SHIPMENT_HEADER_STORE_DISTRIBUTION, sh.TOTAL_LBR_ESTIMATE, sh.LOCKED, sh.SHIPPER_CODE, sh.IN_DELETION, sh.INVENTORY_LOAD_CONFIRMED, 
             sh.LAST_STATUS_UPLOADED AS SHIPMENT_HEADER_LAST_STATUS_UPLOADED, sh.USER_DEF9 AS SHIPMENT_HEADER_USER_DEF9, sh.USER_DEF10 AS SHIPMENT_HEADER_USER_DEF10, sh.USER_DEF11 AS SHIPMENT_HEADER_USER_DEF11, sh.USER_DEF12 AS SHIPMENT_HEADER_USER_DEF12, 
             sh.USER_DEF13 AS SHIPMENT_HEADER_USER_DEF13, sh.USER_DEF14 AS SHIPMENT_HEADER_USER_DEF14, sh.USER_DEF15 AS SHIPMENT_HEADER_USER_DEF15, sh.USER_DEF16 AS SHIPMENT_HEADER_USER_DEF16, sh.USER_DEF17_DATE_TIME AS SHIPMENT_HEADER_USER_DEF17_DATE_TIME, 
             sh.USER_DEF18_DATE_TIME AS SHIPMENT_HEADER_USER_DEF18_DATE_TIME, sh.USER_DEF19_DATE_TIME AS SHIPMENT_HEADER_USER_DEF19_DATE_TIME, sh.USER_DEF20_DATE_TIME AS SHIPMENT_HEADER_USER_DEF20_DATE_TIME, sd.INTERNAL_SHIPMENT_LINE_NUM, sd.ALLOCATION_RULE, 
             sd.STATUS_FLOW_NAME AS SHIPMENT_DETAIL_STATUS_FLOW_NAME, sd.ERP_ORDER AS SHIPMENT_DETAIL_ERP_ORDER, sd.STATUS1 AS SHIPMENT_DETAIL_STATUS1, sd.ERP_ORDER_LINE_NUM, sd.STATUS2 AS SHIPMENT_DETAIL_STATUS2, sd.STATUS3 AS SHIPMENT_DETAIL_STATUS3, 
             sd.STATUS4 AS SHIPMENT_DETAIL_STATUS4, sd.STATUS_FAILED AS SHIPMENT_DETAIL_STATUS_FAILED, sd.STATUS5 AS SHIPMENT_DETAIL_STATUS5, sd.STATUS6 AS SHIPMENT_DETAIL_STATUS6, sd.STATUS7 AS SHIPMENT_DETAIL_STATUS7, sd.STATUS8 AS SHIPMENT_DETAIL_STATUS8, 
             sd.ORDER_TYPE AS SHIPMENT_DETAIL_ORDER_TYPE, CASE WHEN
                 (SELECT   COUNT(DISTINCT ITEM)
                 FROM     SHIPMENT_DETAIL
                 WHERE   INTERNAL_SHIPMENT_NUM = sh.INTERNAL_SHIPMENT_NUM) > 1 THEN N'<literal:1>' ELSE sd.ITEM END AS ITEM, sd.STATUS9 AS SHIPMENT_DETAIL_STATUS9, sd.STATUS10 AS SHIPMENT_DETAIL_STATUS10, sd.MARK_FOR, sd.ITEM_DESC, sd.CUSTOMER_ITEM, sd.ORDER_DATE, 
             sd.COMPANY AS SHIPMENT_DETAIL_COMPANY, sd.INTERFACED_DATE, sd.REQUESTED_QTY, sd.PICK_LOC, sd.PICK_ZONE, sd.SECONDARY_PICK_LOC, sd.SECONDARY_PICK_ZONE, sd.ITEM_LENGTH, sd.ITEM_WIDTH, sd.ITEM_HEIGHT, sd.ITEM_DIMENSION_UM, sd.ITEM_DEPARTMENT, sd.ITEM_LIST_PRICE, 
             sd.ITEM_NET_PRICE, sd.ITEM_COLOR, sd.ITEM_STYLE, sd.ITEM_SIZE, sd.ORIGINAL_ITEM_ORDERED, sd.PICK_LIST_ID, sd.CUSTOMER_PO, sd.INVOICE, sd.ITEM_VOLUME, sd.PACKING_CATEGORY, sd.HAZARDOUS_CODE AS SHIPMENT_DETAIL_HAZARDOUS_CODE, sd.ITEM_DIVISION, sd.NMFC_CODE, sd.CATALOG_ID, 
             sd.MANUFACTURE_ID, sd.TOTAL_QTY AS SHIPMENT_DETAIL_TOTAL_QTY, sd.VALUE AS SHIPMENT_DETAIL_VALUE, sd.MERCHANDISE_CODE, sd.VALUE_ADD_LABEL_CODE, sd.USER_DEF1 AS SHIPMENT_DETAIL_USER_DEF1, sd.USER_DEF2 AS SHIPMENT_DETAIL_USER_DEF2, 
             sd.USER_DEF3 AS SHIPMENT_DETAIL_USER_DEF3, sd.USER_DEF4 AS SHIPMENT_DETAIL_USER_DEF4, sd.USER_DEF5 AS SHIPMENT_DETAIL_USER_DEF5, sd.USER_DEF6 AS SHIPMENT_DETAIL_USER_DEF6, sd.USER_DEF7 AS SHIPMENT_DETAIL_USER_DEF7, sd.USER_DEF8 AS SHIPMENT_DETAIL_USER_DEF8, 
             sd.USER_STAMP AS SHIPMENT_DETAIL_USER_STAMP, sd.PROCESS_STAMP AS SHIPMENT_DETAIL_PROCESS_STAMP, sd.QUANTITY_AT_STS1, sd.LOT_CONTROLLED, sd.DATE_TIME_STAMP AS SHIPMENT_DETAIL_DATE_TIME_STAMP, sd.SERIAL_NUM_REQD, sd.QUANTITY_AT_STS2, sd.CATCH_WEIGHT_REQD, 
             sd.QUANTITY_AT_STS3, sd.QUANTITY_AT_STS4, sd.QUANTITY_AT_STS5, sd.QUANTITY_AT_STS6, sd.QUANTITY_AT_STS7, sd.QUANTITY_AT_STS8, sd.QUANTITY_AT_STS9, sd.PRIORITY AS SHIPMENT_DETAIL_PRIORITY, sd.ITEM_WEIGHT, sd.QUANTITY_AT_STS10, sd.LOT AS SHIPMENT_DETAIL_LOT, sd.ITEM_CLASS, 
             sd.MARK_FOR_NAME, sd.MARK_FOR_ADDRESS1, sd.MARK_FOR_ADDRESS2, sd.MARK_FOR_ADDRESS3, sd.MARK_FOR_ATTENTION_TO, sd.MARK_FOR_CITY, sd.MARK_FOR_STATE, sd.MARK_FOR_COUNTRY, sd.MARK_FOR_POSTAL_CODE, sd.MARK_FOR_PHONE_NUM, sd.MARK_FOR_FAX_NUM, 
             sd.MARK_FOR_EMAIL_ADDRESS, sd.HARMONIZED_CODE, sd.HARMONIZED_DESC, sd.EXPORT_DESC, sd.PREFERENCE_CRIT, sd.PRODUCER, sd.NET_COST, sd.COUNTRY_OF_ORIGIN, sd.PACKING_CLASS, sd.INTERFACE_RECORD_ID AS SHIPMENT_DETAIL_INTERFACE_RECORD_ID, sd.ITEM_CATEGORY1, 
             sd.ITEM_CATEGORY2, sd.ITEM_CATEGORY3, sd.ITEM_CATEGORY4, sd.ITEM_CATEGORY5, sd.ITEM_CATEGORY6, sd.ITEM_CATEGORY7, sd.ITEM_CATEGORY8, sd.ITEM_CATEGORY9, sd.ITEM_CATEGORY10, sd.CONT_CREATION_FULL_QTY, sd.CONT_CREATION_FULL_QTY_UM, sd.CONT_CREATION_INNERPACK_QTY, 
             sd.ALLOCATE_FULL_LOC_QTY, sd.ALLOW_PCT_ALLOC, sd.MINIMUM_ALLOC_PCT, sd.MAXIMUM_ALLOC_PCT, sd.IMMEDIATE_NEEDS_NOTE AS SHIPMENT_DETAIL_IMMEDIATE_NEEDS_NOTE, sd.TREAT_AS_LOOSE, sd.PREVIOUS_WAVE_NUM, sd.BOM_ACTION, sd.INTERNAL_WORK_ORDER_NUM, 
             sd.RELATED_INTERNAL_LINE_NUM, sd.QUANTITY_NEEDED_PER_ITEM, sd.STORE_DISTRIBUTION AS SHIPMENT_DETAIL_STORE_DISTRIBUTION, sd.IMMEDIATE_NEEDS_ELIGIBLE, sd.IMMEDIATE_NEEDS_LOC_RULE, sd.LOGISTICS_UNIT AS SHIPMENT_DETAIL_LOGISTICS_UNIT, 
             sd.PARENT_LOGISTICS_UNIT AS SHIPMENT_DETAIL_PARENT_LOGISTICS_UNIT, sd.LOC_INV_ATTRIBUTES_ID, sd.ALLOCATION_REJECTED_QTY, (CASE WHEN EXISTS
                 (SELECT   TOP 1 1
                 FROM     SHIPMENT_DETAIL
                 WHERE   INTERNAL_SHIPMENT_NUM = sh.INTERNAL_SHIPMENT_NUM AND INTERNAL_WORK_ORDER_NUM IS NOT NULL) THEN N'<literal:2>' ELSE N'<literal:3>' END) AS HAS_DETAIL_LINKED_TO_WO, sd.ECCN AS SHIPMENT_DETAIL_ECCN, sd.VALIDATED_LICENSE AS SHIPMENT_DETAIL_VALIDATED_LICENSE, 
             sd.LICENSE_EXP_DATE AS SHIPMENT_DETAIL_LICENSE_EXP_DATE, CASE WHEN sh.LAUNCH_NUM > 0 THEN ls.RELEASED ELSE N'<literal:4>' END AS RELEASED, CASE WHEN sh.LAUNCH_NUM IS NOT NULL AND sh.LAUNCH_NUM > 0 THEN 1 ELSE 0 END AS WAVED, sl.in_confirmation, ls.LAUNCH_NAME, 
             ls.TOTAL_LINES AS Expr1
FROM     dbo.SHIPMENT_HEADER_VIEW AS sh LEFT OUTER JOIN
             dbo.SHIPMENT_DETAIL AS sd ON sd.INTERNAL_SHIPMENT_NUM = sh.INTERNAL_SHIPMENT_NUM LEFT OUTER JOIN
             dbo.SHIPPING_LOAD AS sl ON sl.INTERNAL_LOAD_NUM = sh.SHIPPING_LOAD_NUM LEFT OUTER JOIN
             dbo.LAUNCH_STATISTICS AS ls ON ls.INTERNAL_LAUNCH_NUM = sh.LAUNCH_NUM
WHERE   (sh.LEADING_STS < 300)

