-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
CREATE VIEW RESOURCE_FILE_BASE_CUSTOM_VIEW
AS
SELECT
	COALESCE(b.RESOURCE_KEY, c.RESOURCE_KEY) AS RESOURCE_KEY,
	COALESCE(b.RESOURCE_GROUP, c.RESOURCE_GROUP) AS RESOURCE_GROUP,
	COALESCE(b.RESOURCE_LANGUAGE, c.RESOURCE_LANGUAGE) AS RESOURCE_LANGUAGE,
	b.TEXT AS BASE_TEXT,
	b.INTERNAL_RES_FILE_NUM AS BASE_INTERNAL_RES_FILE_NUM,
	c.INTERNAL_RES_FILE_NUM AS CUSTOM_INTERNAL_RES_FILE_NUM,
	c.TEXT AS CUSTOM_TEXT,
	b.FIELD_LENGTH AS BASE_FIELD_LENGTH,
	b.DECIMAL_POS AS BASE_DECIMAL_POS
FROM RESOURCE_FILE_BASE b
FULL OUTER JOIN RESOURCE_FILE_CUSTOM c
	ON b.RESOURCE_KEY = c.RESOURCE_KEY
	AND b.RESOURCE_GROUP = c.RESOURCE_GROUP
	AND b.RESOURCE_LANGUAGE = c.RESOURCE_LANGUAGE;