-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
CREATE VIEW STANDALONE_SERVICE_PROPERTIES_VIEW 
AS
SELECT 
(SELECT TOP 1 WAREHOUSE FROM WAREHOUSE WHERE ACTIVE=N'<literal:1>') AS WAREHOUSE,
(SELECT SYSTEM_VALUE FROM SYSTEM_CONFIG_DETAIL WHERE RECORD_TYPE=N'<literal:2>' AND SYS_KEY = N'<literal:3>') AS LOAD_BALANCER_URL,
(SELECT SYSTEM_VALUE FROM SYSTEM_CONFIG_DETAIL WHERE RECORD_TYPE=CASE WHEN dbo.fn_GetFeatureEnabled(N'<literal:4>', NULL) = N'<literal:5>' THEN N'<literal:6>' ELSE N'<literal:7>' END AND SYS_KEY = N'<literal:8>') AS CONFIDENTIAL_CLIENT_ID,
(SELECT SYSTEM_VALUE FROM SYSTEM_CONFIG_DETAIL WHERE RECORD_TYPE=CASE WHEN dbo.fn_GetFeatureEnabled(N'<literal:9>', NULL) = N'<literal:10>' THEN N'<literal:11>' ELSE N'<literal:12>' END AND SYS_KEY = N'<literal:13>') AS SECRET_KEY
