-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */






	

CREATE PROCEDURE SHP_RemoveContainerGroup (
		@containerId nvarchar(25),
		@warehouse nvarchar(25),
		@user nvarchar(30)
	)
AS

	-- [comment omitted]
	UPDATE	SHIPPING_CONTAINER 
	SET		GROUP_POSITION = 0,
			GROUP_NUM = 0,
			USER_STAMP = @user,
			PROCESS_STAMP = N'<literal:1>',
			DATE_TIME_STAMP = GETUTCDATE()
	FROM	SHIPPING_CONTAINER
	WHERE	SHIPPING_CONTAINER.INTERNAL_CONTAINER_NUM IN (
				SELECT	CSC.PARENT
				FROM	SHIPPING_CONTAINER CSC, WORK_INSTRUCTION GWI, WORK_INSTRUCTION WI
				WHERE	WI.CONTAINER_ID = @containerId
					AND WI.FROM_WHS = @warehouse
					AND WI.INSTRUCTION_TYPE = N'<literal:2>' 
					AND GWI.GROUP_NUM = WI.GROUP_NUM
					AND GWI.CONDITION <> N'<literal:3>'
					AND GWI.INSTRUCTION_TYPE = N'<literal:4>' 
					AND CSC.INTERNAL_CONTAINER_NUM = GWI.INTERNAL_CONTAINER_NUM
					AND CSC.PARENT IS NOT NULL)

	-- [comment omitted]
	UPDATE 	SHIPPING_CONTAINER
	SET		GROUP_POSITION = 0,
			GROUP_NUM = 0,
			USER_STAMP = @user,
			PROCESS_STAMP = N'<literal:5>',
			DATE_TIME_STAMP = GETUTCDATE()
	FROM	SHIPPING_CONTAINER, WORK_INSTRUCTION GWI, WORK_INSTRUCTION WI
	WHERE	WI.CONTAINER_ID = @containerId
				AND WI.FROM_WHS = @warehouse
				AND WI.INSTRUCTION_TYPE = N'<literal:6>' 
				AND GWI.GROUP_NUM = WI.GROUP_NUM
				AND GWI.CONDITION <> N'<literal:7>'
				AND GWI.INSTRUCTION_TYPE = N'<literal:8>' 
				AND SHIPPING_CONTAINER.INTERNAL_CONTAINER_NUM = GWI.INTERNAL_CONTAINER_NUM
				
	-- [comment omitted]
	UPDATE	WORK_INSTRUCTION
	SET		GROUP_NUM = NULL,
			USER_STAMP = @user,
			PROCESS_STAMP = N'<literal:9>',
			DATE_TIME_STAMP = GETUTCDATE()			
	FROM	WORK_INSTRUCTION
	WHERE	WORK_INSTRUCTION.INTERNAL_INSTRUCTION_NUM IN(
				SELECT	DISTINCT GWI.INTERNAL_INSTRUCTION_NUM 
				FROM	WORK_INSTRUCTION GWI, WORK_INSTRUCTION WI
				WHERE	WI.CONTAINER_ID = @containerId
					AND WI.FROM_WHS = @warehouse
					AND WI.INSTRUCTION_TYPE = N'<literal:10>' 
					AND GWI.GROUP_NUM = WI.GROUP_NUM
					AND GWI.CONDITION <> N'<literal:11>' )
