-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */






	

CREATE VIEW TRANSACTION_HISTORY_INVENTORY_ATTRIBUTE_VIEW
AS
select  
    TH.*,
    LIA.LOC_INV_ATTRIBUTE1,
    LIA.LOC_INV_ATTRIBUTE2,
    LIA.LOC_INV_ATTRIBUTE3,
    LIA.LOC_INV_ATTRIBUTE4,
    LIA.LOC_INV_ATTRIBUTE5,
    LIA.LOC_INV_ATTRIBUTE6,
    LIA.LOC_INV_ATTRIBUTE7,
    LIA.LOC_INV_ATTRIBUTE8,
    LIA.LOC_INV_ATTRIBUTE9,
    LIA.LOC_INV_ATTRIBUTE10,
    LIA.LOC_INV_ATTRIBUTE11,
    LIA.LOC_INV_ATTRIBUTE12,
    LIA.LOC_INV_ATTRIBUTE13,
    LIA.LOC_INV_ATTRIBUTE14,
    LIA.LOC_INV_ATTRIBUTE15,
    LIA.LOC_INV_ATTRIBUTE16,
    LIA.LOC_INV_ATTRIBUTE17,
    LIA.LOC_INV_ATTRIBUTE18,
    LIA.LOC_INV_ATTRIBUTE19,
    LIA.LOC_INV_ATTRIBUTE20,
	TRY_CAST(THA_EXT.CATCH_WEIGHT AS NUMERIC(14,5)) AS CATCH_WEIGHT,  
    THA_EXT.CATCH_WEIGHT_UM  
  
FROM TRANSACTION_HISTORY TH    
OUTER APPLY    
(    
    SELECT    
        MAX(CASE WHEN ATTRIBUTE_TYPE = N'<literal:1>'   
                 THEN ATTRIBUTE_VALUE 
            END) AS CATCH_WEIGHT,
        MAX(CASE WHEN ATTRIBUTE_TYPE = N'<literal:2>'   
                 THEN ATTRIBUTE_VALUE 
            END) AS CATCH_WEIGHT_UM,
        MAX(CASE WHEN ATTRIBUTE_TYPE = N'<literal:3>' 
                 THEN ATTRIBUTE_VALUE 
            END) AS INVENTORY_ATTRIBUTES_ID
    FROM TRANS_HIST_ATTRIBUTES    
    WHERE LINK_ID = TH.INTERNAL_ID    
      AND ATTRIBUTE_TYPE IN (N'<literal:4>', N'<literal:5>', N'<literal:6>')
) THA_EXT
LEFT OUTER JOIN 
	(
	  SELECT object_id,LOC_INV_ATTRIBUTE1,	LOC_INV_ATTRIBUTE2,	LOC_INV_ATTRIBUTE3,	LOC_INV_ATTRIBUTE4,	LOC_INV_ATTRIBUTE5,	LOC_INV_ATTRIBUTE6,	LOC_INV_ATTRIBUTE7,	LOC_INV_ATTRIBUTE8,	LOC_INV_ATTRIBUTE9,
	  LOC_INV_ATTRIBUTE10,	LOC_INV_ATTRIBUTE11,	LOC_INV_ATTRIBUTE12,	LOC_INV_ATTRIBUTE13,	LOC_INV_ATTRIBUTE14,	LOC_INV_ATTRIBUTE15,	LOC_INV_ATTRIBUTE16,	LOC_INV_ATTRIBUTE17,
	  LOC_INV_ATTRIBUTE18,	LOC_INV_ATTRIBUTE19,	LOC_INV_ATTRIBUTE20  FROM LOCATION_INVENTORY_ATTRIBUTES 
	  UNION
	  SELECT object_id,LOC_INV_ATTRIBUTE1,	LOC_INV_ATTRIBUTE2,	LOC_INV_ATTRIBUTE3,	LOC_INV_ATTRIBUTE4,	LOC_INV_ATTRIBUTE5,	LOC_INV_ATTRIBUTE6,	LOC_INV_ATTRIBUTE7,	LOC_INV_ATTRIBUTE8,	LOC_INV_ATTRIBUTE9,
	  LOC_INV_ATTRIBUTE10,	LOC_INV_ATTRIBUTE11,	LOC_INV_ATTRIBUTE12,	LOC_INV_ATTRIBUTE13,	LOC_INV_ATTRIBUTE14,	LOC_INV_ATTRIBUTE15,	LOC_INV_ATTRIBUTE16,	LOC_INV_ATTRIBUTE17,
	  LOC_INV_ATTRIBUTE18,	LOC_INV_ATTRIBUTE19,	LOC_INV_ATTRIBUTE20 FROM AR_LOCATION_INVENTORY_ATTRIBUTES 

    ) LIA ON THA_EXT.INVENTORY_ATTRIBUTES_ID = LIA.OBJECT_ID; 
