-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */



	

CREATE PROCEDURE PMN_WaveActivity (
	@startDateTime datetime,
	@endDateTime datetime
	)
AS
 
WITH INTERVALTABLE
AS
(
	SELECT @startDateTime AS INTERVAL_DATE_TIME
	
	UNION ALL
	
	SELECT DATEADD(SS, 30, INTERVAL_DATE_TIME)
	FROM INTERVALTABLE
	WHERE DATEADD(SS, 30, INTERVAL_DATE_TIME) < @endDateTime
) 
 
SELECT INTERVALTABLE.INTERVAL_DATE_TIME,
	SUM(ISNULL(LS.TOTAL_SHIPMENTS, 0)) AS TOTAL_SHIPMENTS_IN_WAVE,
	SUM(ISNULL(LS.TOTAL_LINES, 0)) AS TOTAL_LINES_IN_WAVE
FROM INTERVALTABLE
LEFT OUTER JOIN LAUNCH_STATISTICS LS
	ON LS.LAUNCH_DATE_TIME_STARTED <= INTERVALTABLE.INTERVAL_DATE_TIME
	AND LS.LAUNCH_DATE_TIME_ENDED >= INTERVALTABLE.INTERVAL_DATE_TIME
GROUP BY INTERVALTABLE.INTERVAL_DATE_TIME
ORDER BY INTERVALTABLE.INTERVAL_DATE_TIME
OPTION (MAXRECURSION 0)

