-- DOCUMENTATION ONLY: literals/comments removed; do not execute.


CREATE VIEW [dbo].[SCI_SHIPMENT_HEADER_VIEW]  
AS  
SELECT 
  [INTERNAL_SHIPMENT_NUM]
, [WAREHOUSE]
, [SHIPPING_LOAD_NUM]
, [SHIPMENT_ID]
, [LAUNCH_STEP]
, [TRAILING_STS]
, [TRAILING_STS_DATE]
, [TRAILING_STS_FAILED]
, [ORDER_TYPE]
, [CONSOLIDATED]
, [LEADING_STS]
, [LEADING_STS_DATE]
, [CARRIER]
, [LEADING_STS_FAILED]
, [COMPANY]
, [CARRIER_SERVICE]
, [CARRIER_GROUP]
, [CARRIER_TYPE]
, [FREIGHT_TERMS]
, [LIABILITY_TERMS]
, [CUSTOMER]
, [SHIP_TO]
, [ROUTE]
, [STOP]
, [SHIP_TO_ADDRESS1]
, [CUSTOMER_NAME]
, [SHIP_TO_ADDRESS2]
, [SHIP_TO_ADDRESS3]
, [SHIP_TO_CITY]
, [SHIP_TO_STATE]
, [SHIP_TO_COUNTRY]
, [SHIP_TO_POSTAL_CODE]
, [SHIP_TO_PHONE_NUM]
, [SHIP_TO_FAX_NUM]
, [CUSTOMER_ADDRESS1]
, [LAUNCH_NUM]
, [WEIGHT_UM]
, [VOLUME_UM]
, [ROUTING_CODE]
, [SINGLE_ITEM_CARTONS]
, [USER_DEF1]
, [USER_DEF2]
, [PRIORITY]
, [USER_DEF3]
, [USER_DEF4]
, [USER_DEF5]
, [USER_DEF6]
, [USER_DEF7]
, [MANUALLY_ENTERED]
, [USER_DEF8]
, [USER_STAMP]
, [PROCESS_STAMP]
, [DATE_TIME_STAMP]
, [BOL_NUM_ALPHA]
, [PRO_NUM_ALPHA]
, [CUSTOMER_ADDRESS3]
, [CUSTOMER_ADDRESS2]
, [CUSTOMER_ATTENTION_TO]
, [CUSTOMER_CITY]
, [CUSTOMER_STATE]
, [CUSTOMER_COUNTRY]
, [CUSTOMER_POSTAL_CODE]
, [CUSTOMER_PHONE_NUM]
, [CUSTOMER_FAX_NUM]
, [CUSTOMER_EMAIL_ADDRESS]
, [SHIP_TO_NAME]
, [SHIP_TO_ATTENTION_TO]
, [SHIP_TO_EMAIL_ADDRESS]
, [REQUESTED_DELIVERY_DATE]
, [REQUESTED_DELIVERY_TYPE]
, [SCHEDULED_SHIP_DATE]
, [PLANNED_SHIP_DATE]
, [ACTUAL_SHIP_DATE_TIME]
, [PLANNED_DELIVERY_DATE_TIME]
, [ACTUAL_DELIVERY_DATE_TIME]
, [QUANTITY_UM]
, [TOTAL_FREIGHT_CHARGE]
, [BASE_FREIGHT_CHARGE]
, [FREIGHT_DISCOUNT]
, [ACCESSORIAL_CHARGE]
, [CONSOLIDATION_ALLOWED]
, [INTERMEDIATE_CONSIGNEE]
, [INTERMEDIATE_NAME]
, [INTERMEDIATE_ADDRESS1]
, [INTERMEDIATE_ADDRESS2]
, [INTERMEDIATE_ADDRESS3]
, [INTERMEDIATE_ATTENTION_TO]
, [INTERMEDIATE_CITY]
, [INTERMEDIATE_STATE]
, [INTERMEDIATE_COUNTRY]
, [INTERMEDIATE_POSTAL_CODE]
, [INTERMEDIATE_PHONE_NUM]
, [INTERMEDIATE_FAX_NUM]
, [INTERMEDIATE_EMAIL_ADDRESS]
, [FREIGHT_BILL_TO]
, [FREIGHT_BILL_TO_NAME]
, [FREIGHT_BILL_TO_ADDRESS1]
, [FREIGHT_BILL_TO_ADDRESS2]
, [FREIGHT_BILL_TO_ADDRESS3]
, [FREIGHT_BILL_TO_ATTENTION_TO]
, [FREIGHT_BILL_TO_CITY]
, [FREIGHT_BILL_TO_STATE]
, [FREIGHT_BILL_TO_COUNTRY]
, [FREIGHT_BILL_TO_POSTAL_CODE]
, [FREIGHT_BILL_TO_PHONE_NUM]
, [FREIGHT_BILL_TO_FAX_NUM]
, [FREIGHT_BILL_TO_EMAIL_ADDRESS]
, [ERP_ORDER]
, [INTERNAL_ORDER_NUM]
, [EXPORT_TAX_ID]
, [PARTIES]
, [LOADING_PIER]
, [TRANSPORTATION_MODE]
, [EXPORT_PORT]
, [UNLOADING_PORT]
, [CONTAINERIZED]
, [FTZ]
, [VALIDATED_LICENSE]
, [LICENSE_EXP_DATE]
, [ECCN]
, [AUTHORIZED_EMPL_NAME]
, [AUTHORIZED_EMPL_TITLE]
, [UPLOAD_INTERFACE_BATCH]
, [CUSTOMER_RESIDENTIAL_FLAG]
, [SHIPTO_RESIDENTIAL_FLAG]
, [REJECTION_NOTE]
, [INTERFACE_RECORD_ID]
, [CUSTOMER_CATEGORY1]
, [CUSTOMER_CATEGORY2]
, [CUSTOMER_CATEGORY3]
, [CUSTOMER_CATEGORY4]
, [CUSTOMER_CATEGORY5]
, [CUSTOMER_CATEGORY6]
, [CUSTOMER_CATEGORY7]
, [CUSTOMER_CATEGORY8]
, [CUSTOMER_CATEGORY9]
, [CUSTOMER_CATEGORY10]
, [CONSOLIDATION_DOCK_LOC_AREA]
, [CONSOLIDATION_DOCK_LOC_POS]
, [PROCESS_TYPE]
, [CREATION_PROCESS_STAMP]
, [CREATION_DATE_TIME_STAMP]
, [IMMEDIATE_NEEDS_NOTE]
, [ALLOCATE_COMPLETE]
, [ALTERNATE_EMAIL_ADDRESS]
, [STOP_SEQUENCE]
, [INTERNAL_CARRIER_NUM]
, [STORE_DISTRIBUTION]
, [TOTAL_LBR_ESTIMATE]
, [WEIGHT_ENTERED]
, [VOLUME_ENTERED]
, [VALUE_ENTERED]
, [LOCKED]
, [SHIPPER_CODE]
, [IN_DELETION]
, [INVENTORY_LOAD_CONFIRMED]
, [LAST_STATUS_UPLOADED]
, [USER_DEF9]
, [USER_DEF10]
, [USER_DEF11]
, [USER_DEF12]
, [USER_DEF13]
, [USER_DEF14]
, [USER_DEF15]
, [USER_DEF16]
, [USER_DEF17_DATE_TIME]
, [USER_DEF18_DATE_TIME]
, [USER_DEF19_DATE_TIME]
, [USER_DEF20_DATE_TIME]
FROM SHIPMENT_HEADER WITH(NOLOCK)  
UNION   
SELECT 
  [INTERNAL_SHIPMENT_NUM]
, [WAREHOUSE]
, [SHIPPING_LOAD_NUM]
, [SHIPMENT_ID]
, [LAUNCH_STEP]
, [TRAILING_STS]
, [TRAILING_STS_DATE]
, [TRAILING_STS_FAILED]
, [ORDER_TYPE]
, [CONSOLIDATED]
, [LEADING_STS]
, [LEADING_STS_DATE]
, [CARRIER]
, [LEADING_STS_FAILED]
, [COMPANY]
, [CARRIER_SERVICE]
, [CARRIER_GROUP]
, [CARRIER_TYPE]
, [FREIGHT_TERMS]
, [LIABILITY_TERMS]
, [CUSTOMER]
, [SHIP_TO]
, [ROUTE]
, [STOP]
, [SHIP_TO_ADDRESS1]
, [CUSTOMER_NAME]
, [SHIP_TO_ADDRESS2]
, [SHIP_TO_ADDRESS3]
, [SHIP_TO_CITY]
, [SHIP_TO_STATE]
, [SHIP_TO_COUNTRY]
, [SHIP_TO_POSTAL_CODE]
, [SHIP_TO_PHONE_NUM]
, [SHIP_TO_FAX_NUM]
, [CUSTOMER_ADDRESS1]
, [LAUNCH_NUM]
, [WEIGHT_UM]
, [VOLUME_UM]
, [ROUTING_CODE]
, [SINGLE_ITEM_CARTONS]
, [USER_DEF1]
, [USER_DEF2]
, [PRIORITY]
, [USER_DEF3]
, [USER_DEF4]
, [USER_DEF5]
, [USER_DEF6]
, [USER_DEF7]
, [MANUALLY_ENTERED]
, [USER_DEF8]
, [USER_STAMP]
, [PROCESS_STAMP]
, [DATE_TIME_STAMP]
, [BOL_NUM_ALPHA]
, [PRO_NUM_ALPHA]
, [CUSTOMER_ADDRESS3]
, [CUSTOMER_ADDRESS2]
, [CUSTOMER_ATTENTION_TO]
, [CUSTOMER_CITY]
, [CUSTOMER_STATE]
, [CUSTOMER_COUNTRY]
, [CUSTOMER_POSTAL_CODE]
, [CUSTOMER_PHONE_NUM]
, [CUSTOMER_FAX_NUM]
, [CUSTOMER_EMAIL_ADDRESS]
, [SHIP_TO_NAME]
, [SHIP_TO_ATTENTION_TO]
, [SHIP_TO_EMAIL_ADDRESS]
, [REQUESTED_DELIVERY_DATE]
, [REQUESTED_DELIVERY_TYPE]
, [SCHEDULED_SHIP_DATE]
, [PLANNED_SHIP_DATE]
, [ACTUAL_SHIP_DATE_TIME]
, [PLANNED_DELIVERY_DATE_TIME]
, [ACTUAL_DELIVERY_DATE_TIME]
, [QUANTITY_UM]
, [TOTAL_FREIGHT_CHARGE]
, [BASE_FREIGHT_CHARGE]
, [FREIGHT_DISCOUNT]
, [ACCESSORIAL_CHARGE]
, [CONSOLIDATION_ALLOWED]
, [INTERMEDIATE_CONSIGNEE]
, [INTERMEDIATE_NAME]
, [INTERMEDIATE_ADDRESS1]
, [INTERMEDIATE_ADDRESS2]
, [INTERMEDIATE_ADDRESS3]
, [INTERMEDIATE_ATTENTION_TO]
, [INTERMEDIATE_CITY]
, [INTERMEDIATE_STATE]
, [INTERMEDIATE_COUNTRY]
, [INTERMEDIATE_POSTAL_CODE]
, [INTERMEDIATE_PHONE_NUM]
, [INTERMEDIATE_FAX_NUM]
, [INTERMEDIATE_EMAIL_ADDRESS]
, [FREIGHT_BILL_TO]
, [FREIGHT_BILL_TO_NAME]
, [FREIGHT_BILL_TO_ADDRESS1]
, [FREIGHT_BILL_TO_ADDRESS2]
, [FREIGHT_BILL_TO_ADDRESS3]
, [FREIGHT_BILL_TO_ATTENTION_TO]
, [FREIGHT_BILL_TO_CITY]
, [FREIGHT_BILL_TO_STATE]
, [FREIGHT_BILL_TO_COUNTRY]
, [FREIGHT_BILL_TO_POSTAL_CODE]
, [FREIGHT_BILL_TO_PHONE_NUM]
, [FREIGHT_BILL_TO_FAX_NUM]
, [FREIGHT_BILL_TO_EMAIL_ADDRESS]
, [ERP_ORDER]
, [INTERNAL_ORDER_NUM]
, [EXPORT_TAX_ID]
, [PARTIES]
, [LOADING_PIER]
, [TRANSPORTATION_MODE]
, [EXPORT_PORT]
, [UNLOADING_PORT]
, [CONTAINERIZED]
, [FTZ]
, [VALIDATED_LICENSE]
, [LICENSE_EXP_DATE]
, [ECCN]
, [AUTHORIZED_EMPL_NAME]
, [AUTHORIZED_EMPL_TITLE]
, [UPLOAD_INTERFACE_BATCH]
, [CUSTOMER_RESIDENTIAL_FLAG]
, [SHIPTO_RESIDENTIAL_FLAG]
, [REJECTION_NOTE]
, [INTERFACE_RECORD_ID]
, [CUSTOMER_CATEGORY1]
, [CUSTOMER_CATEGORY2]
, [CUSTOMER_CATEGORY3]
, [CUSTOMER_CATEGORY4]
, [CUSTOMER_CATEGORY5]
, [CUSTOMER_CATEGORY6]
, [CUSTOMER_CATEGORY7]
, [CUSTOMER_CATEGORY8]
, [CUSTOMER_CATEGORY9]
, [CUSTOMER_CATEGORY10]
, [CONSOLIDATION_DOCK_LOC_AREA]
, [CONSOLIDATION_DOCK_LOC_POS]
, [PROCESS_TYPE]
, [CREATION_PROCESS_STAMP]
, [CREATION_DATE_TIME_STAMP]
, [IMMEDIATE_NEEDS_NOTE]
, [ALLOCATE_COMPLETE]
, [ALTERNATE_EMAIL_ADDRESS]
, [STOP_SEQUENCE]
, [INTERNAL_CARRIER_NUM]
, [STORE_DISTRIBUTION]
, [TOTAL_LBR_ESTIMATE]
, [WEIGHT_ENTERED]
, [VOLUME_ENTERED]
, [VALUE_ENTERED]
, [LOCKED]
, [SHIPPER_CODE]
, [IN_DELETION]
, [INVENTORY_LOAD_CONFIRMED]
, [LAST_STATUS_UPLOADED]
, [USER_DEF9]
, [USER_DEF10]
, [USER_DEF11]
, [USER_DEF12]
, [USER_DEF13]
, [USER_DEF14]
, [USER_DEF15]
, [USER_DEF16]
, [USER_DEF17_DATE_TIME]
, [USER_DEF18_DATE_TIME]
, [USER_DEF19_DATE_TIME]
, [USER_DEF20_DATE_TIME]
FROM AR_SHIPMENT_HEADER WITH(NOLOCK)  
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]