-- DOCUMENTATION ONLY: literals/comments removed; do not execute.


CREATE VIEW [dbo].[SCI_SHIPPING_CONTAINER_VIEW]  
AS  
SELECT 
  [INTERNAL_CONTAINER_NUM]
, [CONTAINER_ID]
, [WAREHOUSE]
, [CONTAINER_TYPE]
, [CONTAINER_CLASS]
, [STATUS]
, [STATUS_FAILED]
, [PARENT]
, [WEIGHT]
, [WEIGHT_UM]
, [VOLUME]
, [LENGTH]
, [WIDTH]
, [HEIGHT]
, [DIMENSION_UM]
, [VOLUME_UM]
, [VALUE]
, [INTERNAL_SHIPMENT_NUM]
, [INTERNAL_SHIPMENT_LINE_NUM]
, [COMPANY]
, [ITEM]
, [QUANTITY]
, [QUANTITY_UM]
, [NMFC_CODE]
, [STATUS_FLOW_NAME]
, [HAZARDOUS_CODE]
, [MANIFEST_STATE]
, [MANIFEST_CARR_SERVICE_SYMBOL]
, [MANIFEST_DATE_TIME]
, [TRACKING_NUMBER]
, [TOTAL_FREIGHT_CHARGE]
, [BASE_FREIGHT_CHARGE]
, [FREIGHT_DISCOUNT]
, [ACCESSORIAL_CHARGE]
, [USER_DEF1]
, [USER_DEF2]
, [USER_DEF3]
, [USER_DEF4]
, [USER_DEF5]
, [USER_DEF6]
, [USER_DEF7]
, [USER_DEF8]
, [USER_STAMP]
, [PROCESS_STAMP]
, [DATE_TIME_STAMP]
, [INTERNAL_ORDER_NUM]
, [MANIFEST_FOR_DATE]
, [TREE_UNIT]
, [PLANNED_DELIVERY_DATE_TIME]
, [BUNDLE_ID]
, [MSN]
, [LOCATION]
, [GROUP_POSITION]
, [LAUNCH_NUM]
, [CONTAINER_COUNT_NUMBER]
, [CONTAINER_COUNT_TOTAL]
, [GROUP_NUM]
, [WORK_ZONE]
, [INTERFACE_RECORD_ID]
, [PARENT_CONTAINER_ID]
, [INTERNAL_SHIP_ALLOC_NUM]
, [WORK_CREATED]
, [HUNDREDWEIGHT]
, [MANIFEST_ID]
, [MANIFEST_CLOSE_DATE_TIME]
, [EPC]
, [LOT]
, [URI]
, [RETURNS_TOTAL_FREIGHT_CHARGE]
, [RETURNS_BASE_FREIGHT_CHARGE]
, [RETURNS_FREIGHT_DISCOUNT]
, [RETURNS_ACCESSORIAL_CHARGE]
, [RETURNS_CALLTAG_FEE]
, [RETURNS_TRACKING_NUMBER]
, [RETURNS_MSN]
, [RETURNS_PRINT_LABEL]
, [WORLD_EASE_ID]
, [WORLD_EASE_GROUP_STATUS]
, [LOGISTICS_UNIT]
, [PARENT_LOGISTICS_UNIT]
, [PALLET_SEQUENCE]
, [ORIGINAL_PICK_LOC]
, [INTERNAL_MOP_NUMBER]
, [QC_STATUS]
, [QC_ASSIGNMENT_ID]
, [PALLET_UM_CONVERSION_IDENTIFIER]
, [PALLET_UM_CONVERSION_PARENT_UM]
, [MMS_PIECE_ID]
FROM SHIPPING_CONTAINER WITH(NOLOCK)  
UNION   
SELECT 
  [INTERNAL_CONTAINER_NUM]
, [CONTAINER_ID]
, [WAREHOUSE]
, [CONTAINER_TYPE]
, [CONTAINER_CLASS]
, [STATUS]
, [STATUS_FAILED]
, [PARENT]
, [WEIGHT]
, [WEIGHT_UM]
, [VOLUME]
, [LENGTH]
, [WIDTH]
, [HEIGHT]
, [DIMENSION_UM]
, [VOLUME_UM]
, [VALUE]
, [INTERNAL_SHIPMENT_NUM]
, [INTERNAL_SHIPMENT_LINE_NUM]
, [COMPANY]
, [ITEM]
, [QUANTITY]
, [QUANTITY_UM]
, [NMFC_CODE]
, [STATUS_FLOW_NAME]
, [HAZARDOUS_CODE]
, [MANIFEST_STATE]
, [MANIFEST_CARR_SERVICE_SYMBOL]
, [MANIFEST_DATE_TIME]
, [TRACKING_NUMBER]
, [TOTAL_FREIGHT_CHARGE]
, [BASE_FREIGHT_CHARGE]
, [FREIGHT_DISCOUNT]
, [ACCESSORIAL_CHARGE]
, [USER_DEF1]
, [USER_DEF2]
, [USER_DEF3]
, [USER_DEF4]
, [USER_DEF5]
, [USER_DEF6]
, [USER_DEF7]
, [USER_DEF8]
, [USER_STAMP]
, [PROCESS_STAMP]
, [DATE_TIME_STAMP]
, [INTERNAL_ORDER_NUM]
, [MANIFEST_FOR_DATE]
, [TREE_UNIT]
, [PLANNED_DELIVERY_DATE_TIME]
, [BUNDLE_ID]
, [MSN]
, [LOCATION]
, [GROUP_POSITION]
, [LAUNCH_NUM]
, [CONTAINER_COUNT_NUMBER]
, [CONTAINER_COUNT_TOTAL]
, [GROUP_NUM]
, [WORK_ZONE]
, [INTERFACE_RECORD_ID]
, [PARENT_CONTAINER_ID]
, [INTERNAL_SHIP_ALLOC_NUM]
, [WORK_CREATED]
, [HUNDREDWEIGHT]
, [MANIFEST_ID]
, [MANIFEST_CLOSE_DATE_TIME]
, [EPC]
, [LOT]
, [URI]
, [RETURNS_TOTAL_FREIGHT_CHARGE]
, [RETURNS_BASE_FREIGHT_CHARGE]
, [RETURNS_FREIGHT_DISCOUNT]
, [RETURNS_ACCESSORIAL_CHARGE]
, [RETURNS_CALLTAG_FEE]
, [RETURNS_TRACKING_NUMBER]
, [RETURNS_MSN]
, [RETURNS_PRINT_LABEL]
, [LOGISTICS_UNIT]
, [PARENT_LOGISTICS_UNIT]
, [WORLD_EASE_ID]
, [WORLD_EASE_GROUP_STATUS]
, [PALLET_SEQUENCE]
, [ORIGINAL_PICK_LOC]
, [INTERNAL_MOP_NUMBER]
, [QC_STATUS]
, [QC_ASSIGNMENT_ID]
, [PALLET_UM_CONVERSION_IDENTIFIER]
, [PALLET_UM_CONVERSION_PARENT_UM]
, [MMS_PIECE_ID]
FROM AR_SHIPPING_CONTAINER WITH(NOLOCK)  
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]
-- [comment omitted]