-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */














	


CREATE PROCEDURE SHP_SplitShippingContainer(
	@qty numeric(19,5),
	@internalContNum numeric(9),
	@userName nvarchar(30),
	@newInternalContNum numeric(9) output,
	@newParentContNum numeric(9) output)
AS
	
	declare @rowCount int;

	-- [comment omitted]
	if (@internalContNum is null OR @internalContNum <= 0 OR @qty is null OR @qty <= 0)
		return -1;

	-- [comment omitted]
	-- [comment omitted]
	SET @rowCount = (SELECT COUNT(*) FROM SHIPPING_CONTAINER WHERE INTERNAL_CONTAINER_NUM = @internalContNum 
	AND CONTAINER_ID IS NOT NULL AND ITEM IS NOT NULL AND CONTAINER_TYPE <> N'<literal:1>');

	if(@rowCount > 0)
	begin
		/* [comment omitted] */
		INSERT INTO SHIPPING_CONTAINER (
			CONTAINER_ID,
			WAREHOUSE,
			CONTAINER_TYPE,
			CONTAINER_CLASS,
			STATUS,
			STATUS_FAILED,
			PARENT,
			WEIGHT,
			WEIGHT_UM,
			VOLUME,
			LENGTH,
			WIDTH,
			HEIGHT,
			DIMENSION_UM,
			VOLUME_UM,
			VALUE,
			INTERNAL_SHIPMENT_NUM,
			INTERNAL_SHIPMENT_LINE_NUM,
			COMPANY,
			ITEM,
			QUANTITY,
			QUANTITY_UM,
			NMFC_CODE,
			STATUS_FLOW_NAME,
			HAZARDOUS_CODE,
			MANIFEST_STATE,
			MANIFEST_CARR_SERVICE_SYMBOL,
			MANIFEST_DATE_TIME,
			TRACKING_NUMBER,
			TOTAL_FREIGHT_CHARGE,
			BASE_FREIGHT_CHARGE,
			FREIGHT_DISCOUNT,
			ACCESSORIAL_CHARGE,
			USER_DEF1,
			USER_DEF2,
			USER_DEF3,
			USER_DEF4,
			USER_DEF5,
			USER_DEF6,
			USER_DEF7,
			USER_DEF8,
			USER_STAMP,
			PROCESS_STAMP,
			DATE_TIME_STAMP,
			INTERNAL_ORDER_NUM,
			MANIFEST_FOR_DATE,
			TREE_UNIT,
			PLANNED_DELIVERY_DATE_TIME,
			BUNDLE_ID,
			MSN,
			LOCATION,
			GROUP_POSITION,
			LAUNCH_NUM,
			CONTAINER_COUNT_NUMBER,
			CONTAINER_COUNT_TOTAL,
			GROUP_NUM,
			WORK_ZONE,
			INTERFACE_RECORD_ID,
			PARENT_CONTAINER_ID,
			INTERNAL_SHIP_ALLOC_NUM,
			WORK_CREATED,
			HUNDREDWEIGHT,
			MANIFEST_ID,
			MANIFEST_CLOSE_DATE_TIME,
			EPC,	
			LOT,
			URI,
			RETURNS_TOTAL_FREIGHT_CHARGE,
			RETURNS_BASE_FREIGHT_CHARGE,
			RETURNS_FREIGHT_DISCOUNT,
			RETURNS_ACCESSORIAL_CHARGE,
			RETURNS_CALLTAG_FEE,
			RETURNS_TRACKING_NUMBER,
			RETURNS_MSN,
			RETURNS_PRINT_LABEL,
			WORLD_EASE_ID,
			WORLD_EASE_GROUP_STATUS,
			LOGISTICS_UNIT,
			PARENT_LOGISTICS_UNIT,
			PALLET_SEQUENCE)
		SELECT 
			CONTAINER_ID,
			WAREHOUSE,
			CONTAINER_TYPE,
			CONTAINER_CLASS,
			STATUS,
			STATUS_FAILED,
			PARENT,
			WEIGHT,
			WEIGHT_UM,
			VOLUME,
			LENGTH,
			WIDTH,
			HEIGHT,
			DIMENSION_UM,
			VOLUME_UM,
			VALUE,
			INTERNAL_SHIPMENT_NUM,
			INTERNAL_SHIPMENT_LINE_NUM,
			COMPANY,
			ITEM,
			QUANTITY,
			QUANTITY_UM,
			NMFC_CODE,
			STATUS_FLOW_NAME,
			HAZARDOUS_CODE,
			MANIFEST_STATE,
			MANIFEST_CARR_SERVICE_SYMBOL,
			MANIFEST_DATE_TIME,
			TRACKING_NUMBER,
			TOTAL_FREIGHT_CHARGE,
			BASE_FREIGHT_CHARGE,
			FREIGHT_DISCOUNT,
			ACCESSORIAL_CHARGE,
			USER_DEF1,
			USER_DEF2,
			USER_DEF3,
			USER_DEF4,
			USER_DEF5,
			USER_DEF6,
			USER_DEF7,
			USER_DEF8,
			USER_STAMP,
			PROCESS_STAMP,
			DATE_TIME_STAMP,
			INTERNAL_ORDER_NUM,
			MANIFEST_FOR_DATE,
			TREE_UNIT,
			PLANNED_DELIVERY_DATE_TIME,
			BUNDLE_ID,
			MSN,
			LOCATION,
			GROUP_POSITION,
			LAUNCH_NUM,
			CONTAINER_COUNT_NUMBER,
			CONTAINER_COUNT_TOTAL,
			GROUP_NUM,
			WORK_ZONE,
			INTERFACE_RECORD_ID,
			PARENT_CONTAINER_ID,
			INTERNAL_SHIP_ALLOC_NUM,
			WORK_CREATED,
			HUNDREDWEIGHT,
			MANIFEST_ID,
			MANIFEST_CLOSE_DATE_TIME,
			EPC,
			LOT,
			URI,
			RETURNS_TOTAL_FREIGHT_CHARGE,
			RETURNS_BASE_FREIGHT_CHARGE,
			RETURNS_FREIGHT_DISCOUNT,
			RETURNS_ACCESSORIAL_CHARGE,
			RETURNS_CALLTAG_FEE,
			RETURNS_TRACKING_NUMBER,
			RETURNS_MSN,
			RETURNS_PRINT_LABEL,
			WORLD_EASE_ID,
			WORLD_EASE_GROUP_STATUS,
			LOGISTICS_UNIT,
			PARENT_LOGISTICS_UNIT,
			PALLET_SEQUENCE
		FROM SHIPPING_CONTAINER
		WHERE INTERNAL_CONTAINER_NUM = @internalContNum;
			
		if (@@ERROR <> 0) return -1;
	
		set @newParentContNum = SCOPE_IDENTITY();

		-- [comment omitted]
		UPDATE SHIPPING_CONTAINER
		SET PARENT = NULL,
		INTERNAL_SHIPMENT_LINE_NUM = NULL, 
		ITEM = NULL,
		QUANTITY = NULL,
		LOCATION = NULL,
		WORK_ZONE = NULL,
		PARENT_CONTAINER_ID = NULL,
		PROCESS_STAMP = N'<literal:2>',
		INTERNAL_SHIP_ALLOC_NUM = NULL,
		WORK_CREATED = N'<literal:3>',
		USER_STAMP = @userName,
		LOT = NULL
		WHERE INTERNAL_CONTAINER_NUM = @newParentContNum;

		-- [comment omitted]
		UPDATE SHIPPING_CONTAINER
		SET PARENT_CONTAINER_ID = CONTAINER_ID,  
		CONTAINER_ID = NULL,
		CONTAINER_TYPE = N'<literal:4>',
		CONTAINER_CLASS = NULL,
		PARENT = @newParentContNum,
		MANIFEST_STATE = NULL,
		MANIFEST_CARR_SERVICE_SYMBOL = NULL,
		MANIFEST_DATE_TIME = NULL,
		TRACKING_NUMBER = NULL,
		TOTAL_FREIGHT_CHARGE = 0,
		BASE_FREIGHT_CHARGE = 0,
		FREIGHT_DISCOUNT = 0,
		ACCESSORIAL_CHARGE = 0,
		MANIFEST_FOR_DATE = NULL,
		BUNDLE_ID = 0,
		MSN = 0,
		CONTAINER_COUNT_NUMBER = 0,
		CONTAINER_COUNT_TOTAL = 0,
		MANIFEST_ID = NULL,
		MANIFEST_CLOSE_DATE_TIME = NULL,
		PROCESS_STAMP = N'<literal:5>',
		RETURNS_TOTAL_FREIGHT_CHARGE = 0,
		RETURNS_BASE_FREIGHT_CHARGE = 0,
		RETURNS_FREIGHT_DISCOUNT = 0,
		RETURNS_ACCESSORIAL_CHARGE = 0,
		RETURNS_CALLTAG_FEE = 0,
		RETURNS_TRACKING_NUMBER = NULL,
		RETURNS_MSN = 0,
		RETURNS_PRINT_LABEL = NULL,
		USER_STAMP = @userName,
		WORLD_EASE_ID = 0,
		WORLD_EASE_GROUP_STATUS = 0
		WHERE  INTERNAL_CONTAINER_NUM = @internalContNum;
	end;
 

	-- [comment omitted]
	-- [comment omitted]
	/* [comment omitted] */
	INSERT INTO SHIPPING_CONTAINER (
		CONTAINER_ID,
		WAREHOUSE,
		CONTAINER_TYPE,
		CONTAINER_CLASS,
		STATUS,
		STATUS_FAILED,
		PARENT,
		WEIGHT,
		WEIGHT_UM,
		VOLUME,
		LENGTH,
		WIDTH,
		HEIGHT,
		DIMENSION_UM,
		VOLUME_UM,
		VALUE,
		INTERNAL_SHIPMENT_NUM,
		INTERNAL_SHIPMENT_LINE_NUM,
		COMPANY,
		ITEM,
		QUANTITY,
		QUANTITY_UM,
		NMFC_CODE,
		STATUS_FLOW_NAME,
		HAZARDOUS_CODE,
		MANIFEST_STATE,
		MANIFEST_CARR_SERVICE_SYMBOL,
		MANIFEST_DATE_TIME,
		TRACKING_NUMBER,
		TOTAL_FREIGHT_CHARGE,
		BASE_FREIGHT_CHARGE,
		FREIGHT_DISCOUNT,
		ACCESSORIAL_CHARGE,
		USER_DEF1,
		USER_DEF2,
		USER_DEF3,
		USER_DEF4,
		USER_DEF5,
		USER_DEF6,
		USER_DEF7,
		USER_DEF8,
		USER_STAMP,
		PROCESS_STAMP,
		DATE_TIME_STAMP,
		INTERNAL_ORDER_NUM,
		MANIFEST_FOR_DATE,
		TREE_UNIT,
		PLANNED_DELIVERY_DATE_TIME,
		BUNDLE_ID,
		MSN,
		LOCATION,
		GROUP_POSITION,
		LAUNCH_NUM,
		CONTAINER_COUNT_NUMBER,
		CONTAINER_COUNT_TOTAL,
		GROUP_NUM,
		WORK_ZONE,
		INTERFACE_RECORD_ID,
		PARENT_CONTAINER_ID,
		INTERNAL_SHIP_ALLOC_NUM,
		WORK_CREATED,
		HUNDREDWEIGHT,
		MANIFEST_ID,
		MANIFEST_CLOSE_DATE_TIME,
		EPC,
		LOT,
		URI,
		RETURNS_TOTAL_FREIGHT_CHARGE,
		RETURNS_BASE_FREIGHT_CHARGE,
		RETURNS_FREIGHT_DISCOUNT,
		RETURNS_ACCESSORIAL_CHARGE,
		RETURNS_CALLTAG_FEE,
		RETURNS_TRACKING_NUMBER,
		RETURNS_MSN,
		RETURNS_PRINT_LABEL,
		WORLD_EASE_ID,
		WORLD_EASE_GROUP_STATUS,
		LOGISTICS_UNIT,
		PARENT_LOGISTICS_UNIT,
		PALLET_SEQUENCE)
	SELECT 
		CONTAINER_ID,
		WAREHOUSE,
		CONTAINER_TYPE,
		CONTAINER_CLASS,
		STATUS,
		STATUS_FAILED,
		PARENT,
		WEIGHT,
		WEIGHT_UM,
		VOLUME,
		LENGTH,
		WIDTH,
		HEIGHT,
		DIMENSION_UM,
		VOLUME_UM,
		VALUE,
		INTERNAL_SHIPMENT_NUM,
		INTERNAL_SHIPMENT_LINE_NUM,
		COMPANY,
		ITEM,
		QUANTITY,
		QUANTITY_UM,
		NMFC_CODE,
		STATUS_FLOW_NAME,
		HAZARDOUS_CODE,
		MANIFEST_STATE,
		MANIFEST_CARR_SERVICE_SYMBOL,
		MANIFEST_DATE_TIME,
		TRACKING_NUMBER,
		TOTAL_FREIGHT_CHARGE,
		BASE_FREIGHT_CHARGE,
		FREIGHT_DISCOUNT,
		ACCESSORIAL_CHARGE,
		USER_DEF1,
		USER_DEF2,
		USER_DEF3,
		USER_DEF4,
		USER_DEF5,
		USER_DEF6,
		USER_DEF7,
		USER_DEF8,
		USER_STAMP,
		PROCESS_STAMP,
		DATE_TIME_STAMP,
		INTERNAL_ORDER_NUM,
		MANIFEST_FOR_DATE,
		TREE_UNIT,
		PLANNED_DELIVERY_DATE_TIME,
		BUNDLE_ID,
		MSN,
		LOCATION,
		GROUP_POSITION,
		LAUNCH_NUM,
		CONTAINER_COUNT_NUMBER,
		CONTAINER_COUNT_TOTAL,
		GROUP_NUM,
		WORK_ZONE,
		INTERFACE_RECORD_ID,
		PARENT_CONTAINER_ID,
		INTERNAL_SHIP_ALLOC_NUM,
		WORK_CREATED,
		HUNDREDWEIGHT,
		MANIFEST_ID,
		MANIFEST_CLOSE_DATE_TIME,
		EPC,
		LOT,
		URI,
		RETURNS_TOTAL_FREIGHT_CHARGE,
		RETURNS_BASE_FREIGHT_CHARGE,
		RETURNS_FREIGHT_DISCOUNT,
		RETURNS_ACCESSORIAL_CHARGE,
		RETURNS_CALLTAG_FEE,
		RETURNS_TRACKING_NUMBER,
		RETURNS_MSN,
		RETURNS_PRINT_LABEL,
		WORLD_EASE_ID,
		WORLD_EASE_GROUP_STATUS,
		LOGISTICS_UNIT,
		PARENT_LOGISTICS_UNIT,
		PALLET_SEQUENCE
		FROM SHIPPING_CONTAINER
		WHERE INTERNAL_CONTAINER_NUM = @internalContNum;
	if (@@ERROR <> 0) return -1;	

	set @newInternalContNum = SCOPE_IDENTITY();

	/* [comment omitted] */
	UPDATE SHIPPING_CONTAINER
	SET	QUANTITY = QUANTITY - @qty,
		WEIGHT = (WEIGHT / QUANTITY) * (QUANTITY - @qty),
		VOLUME = (VOLUME / QUANTITY) * (QUANTITY - @qty),
		VALUE = (VALUE /QUANTITY) * (QUANTITY - @qty),
		PROCESS_STAMP = N'<literal:6>',
		DATE_TIME_STAMP = GETUTCDATE(),
		USER_STAMP = @userName
	WHERE INTERNAL_CONTAINER_NUM = @internalContNum
	AND QUANTITY >= @qty;
	if (@@ERROR <> 0) return -1;
	

	/* [comment omitted] */	

	UPDATE SHIPPING_CONTAINER
	SET	QUANTITY  = (QUANTITY  - (QUANTITY  - @qty)),
		WEIGHT = (WEIGHT / QUANTITY) * (QUANTITY  - (QUANTITY  - @qty)),
		VOLUME = (VOLUME / QUANTITY) * (QUANTITY  - (QUANTITY  - @qty)),
		VALUE = (VALUE /QUANTITY) * (QUANTITY  - (QUANTITY  - @qty)),
		PROCESS_STAMP = N'<literal:7>',
		DATE_TIME_STAMP = GETUTCDATE(),
		USER_STAMP = @userName
	WHERE INTERNAL_CONTAINER_NUM = @newInternalContNum;
	if (@@ERROR <> 0) return -1;

-- [comment omitted]





