-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */







CREATE VIEW WORK_ORDER_DETAIL_VIEW
AS   
SELECT 
WH.WORK_ORDER_ID,
WH.QTY_TO_BE_BUILT, 
WH.QTY_BUILT,
WD.INTERNAL_WRK_ORD_LINE_NUM,
WD.INTERNAL_WORK_ORDER_NUM,
WD.WAREHOUSE,
WD.ITEM,
WD.COMPANY,
WD.BUILD_SEQUENCE,
WD.BUILD_LEVEL,
WD.QTY_NEEDED_PER_ITEM,
WD.TOTAL_QTY_NEEDED,
WD.TOTAL_QTY_USED,
WD.QUANTITY_UM,
WD.FROM_LOCATION,
WD.ALLOCATION_RULE,
WD.LAUNCH_NUM,
WD.WORK_CREATED,
WD.ALLOCATED,
WD.USER_DEF1,
WD.USER_DEF2,
WD.USER_DEF3,
WD.USER_DEF4,
WD.USER_DEF5,
WD.USER_DEF6,
WD.USER_DEF7,
WD.USER_DEF8,
WD.USER_STAMP,
WD.PROCESS_STAMP,
WD.DATE_TIME_STAMP,
WD.TOTAL_CONVERTED_QTY_NEEDED,
WD.CONVERTED_UM,
WD.ITEM_DESC,
WD.ITEM_HEIGHT,
WD.ITEM_LENGTH,
WD.ITEM_WIDTH,
WD.DIMENSION_UM,
WD.ITEM_WEIGHT,
WD.WEIGHT_UM,
WD.VOLUME_UM,
WD.ITEM_VALUE,
WD.ON_HAND_QTY,
WD.ITEM_CLASS,
WD.IMMEDIATE_NEEDS_NOTE,
WD.IN_ALLOCATION,
WD.LOT,
WD.INC_QTY_ELIGIBLE,
CAST(WD.INC_QTY_TYPE AS NVARCHAR(1)) AS INC_QTY_TYPE ,
WD.INC_QTY_AMOUNT,
WD.INC_QTY_MIN_AMOUNT,
WD.ORIG_TOTAL_QTY_NEEDED,
WD.SIBLING_WRK_ORD_LIN_NUM,
WD.LOGISTICS_UNIT,
WD.PARENT_LOGISTICS_UNIT, I.INVENTORY_TRACKING  FROM WORK_ORDER_DETAIL  WD
INNER JOIN WORK_ORDER_HEADER WH on WH.INTERNAL_WORK_ORDER_NUM = WD.INTERNAL_WORK_ORDER_NUM
INNER JOIN ITEM I ON I.ITEM =WD.ITEM AND (I.COMPANY =WD.COMPANY OR ( WD.COMPANY IS NULL AND I.COMPANY IS NULL) OR ( WD.COMPANY IS NOT NULL AND I.COMPANY IS NULL))