-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */








CREATE PROCEDURE wm_RSerialNumber11
	@TransHistId numeric(9)
AS
	SET NOCOUNT ON;
	
	SELECT SN.*
	  FROM SERIAL_NUMBER SN,
	       TRANS_HIST_ATTRIBUTES THA
	 WHERE THA.ATTRIBUTE_TYPE = N'<literal:1>'
	   AND THA.LINK_ID = @TransHistId
	   AND SN.OBJECT_ID = THA.ATTRIBUTE_VALUE
	   AND SN.TEMPLATE_ID IS NULL
	UNION ALL
	SELECT ASN.*
	  FROM AR_SERIAL_NUMBER ASN,
	       TRANS_HIST_ATTRIBUTES THA
	 WHERE THA.ATTRIBUTE_TYPE = N'<literal:2>'
	   AND THA.LINK_ID = @TransHistId
	   AND ASN.OBJECT_ID = THA.ATTRIBUTE_VALUE
	   AND ASN.TEMPLATE_ID IS NULL
	
	UNION ALL
	
	SELECT SN.*
	  FROM SERIAL_NUMBER SN,
	       SERIAL_NUM_TEMPLATE SNT,
	       TRANS_HIST_ATTRIBUTES THA
	 WHERE THA.ATTRIBUTE_TYPE = N'<literal:3>'
	   AND THA.LINK_ID = @TransHistId
	   AND SN.OBJECT_ID = THA.ATTRIBUTE_VALUE
	   AND SNT.OBJECT_ID = SN.TEMPLATE_ID
	   AND SNT.SEQUENCE = 0
	UNION ALL
	SELECT ASN.*
	  FROM AR_SERIAL_NUMBER ASN,
	       SERIAL_NUM_TEMPLATE SNT,
	       TRANS_HIST_ATTRIBUTES THA
	 WHERE THA.ATTRIBUTE_TYPE = N'<literal:4>'
	   AND THA.LINK_ID = @TransHistId
	   AND ASN.OBJECT_ID = THA.ATTRIBUTE_VALUE
	   AND SNT.OBJECT_ID = ASN.TEMPLATE_ID
	   AND SNT.SEQUENCE = 0