-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
CREATE VIEW dbo.SHIPMENT_DETAIL_VIEW
AS
SELECT     ITEM, ITEM_DESC, QUANTITY_UM, TOTAL_QTY, MARK_FOR_ADDRESS1, MARK_FOR_ADDRESS2, MARK_FOR_ADDRESS3, MARK_FOR_CITY, MARK_FOR_STATE, 
                      MARK_FOR_POSTAL_CODE, MARK_FOR_COUNTRY, ERP_ORDER, CUSTOMER, INTERNAL_SHIPMENT_NUM, INTERNAL_SHIPMENT_LINE_NUM, ITEM_CLASS, 
                      REQUESTED_QTY, PRIORITY, ITEM_LIST_PRICE
FROM         dbo.SHIPMENT_DETAIL AS SD
UNION
SELECT     ITEM, ITEM_DESC, QUANTITY_UM, TOTAL_QTY, MARK_FOR_ADDRESS1, MARK_FOR_ADDRESS2, MARK_FOR_ADDRESS3, MARK_FOR_CITY, MARK_FOR_STATE, 
                      MARK_FOR_POSTAL_CODE, MARK_FOR_COUNTRY, ERP_ORDER, CUSTOMER, INTERNAL_SHIPMENT_NUM, INTERNAL_SHIPMENT_LINE_NUM, ITEM_CLASS, 
                      REQUESTED_QTY, PRIORITY, ITEM_LIST_PRICE
FROM         dbo.AR_SHIPMENT_DETAIL AS SD