-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
CREATE VIEW SHIPMENT_HEADER_ORDER_VIEW
AS
SELECT 
	MAX(Detail.SHIPMENT_ID) AS SHIPMENT_ID, 
	MAX(Detail.ERP_ORDER) AS ERP_ORDER, 
	Detail.CUSTOMER_PO AS CUSTOMER_PO, 
	MAX(Header.CONSOLIDATED) AS CONSOLIDATED, 
	MAX(Detail.COMPANY) AS COMPANY, 
	MAX(Detail.WAREHOUSE) AS WAREHOUSE,
	Detail.INTERNAL_SHIPMENT_NUM AS INTERNAL_SHIPMENT_NUM, 
	Detail.INTERNAL_ORDER_NUM AS INTERNAL_ORDER_NUM,	
	MAX(Header.LEADING_STS) AS LEADING_STS,
	CASE WHEN MAX(Header.LAUNCH_NUM) > 0 AND MAX(LAUNCH.RELEASED) = N'<literal:1>' THEN N'<literal:2>' ELSE N'<literal:3>' END AS RELEASED
FROM
	SHIPMENT_HEADER Header INNER JOIN SHIPMENT_DETAIL Detail
	ON Header.INTERNAL_SHIPMENT_NUM = Detail.INTERNAL_SHIPMENT_NUM
	LEFT OUTER JOIN LAUNCH_STATISTICS LAUNCH
	ON Header.LAUNCH_NUM = LAUNCH.INTERNAL_LAUNCH_NUM
GROUP BY 
	Detail.CUSTOMER_PO, Detail.INTERNAL_ORDER_NUM, Detail.INTERNAL_SHIPMENT_NUM;