-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */






CREATE PROCEDURE dbc_IGenericConfigHeader(
	@recordType nvarchar(50),
	@description nvarchar(50),
	@systemCreated nchar(1) = N'<literal:1>',
	@sys1FieldName nvarchar(30) = null,
	@sys1FieldType nvarchar(6) = null,
	@sys1FieldLookup nvarchar(50) = null,
	@sys1Required nchar(1) = N'<literal:2>', 
	@sys2FieldName nvarchar(30) = null,
	@sys2FieldType nvarchar(6) = null,
	@sys2FieldLookup nvarchar(50) = null,
	@sys2Required nchar(1) = N'<literal:3>', 
	@sys3FieldName nvarchar(30) = null,
	@sys3FieldType nvarchar(6) = null,
	@sys3FieldLookup nvarchar(50) = null,
	@sys3Required nchar(1) = N'<literal:4>', 
	@sys4FieldName nvarchar(30) = null,
	@sys4FieldType nvarchar(6) = null,
	@sys4FieldLookup nvarchar(50) = null,
	@sys4Required nchar(1) = N'<literal:5>', 
	@sys5FieldName nvarchar(30) = null,
	@sys5FieldType nvarchar(6) = null,
	@sys5FieldLookup nvarchar(50) = null,
	@sys5Required nchar(1) = N'<literal:6>', 
	@user1FieldName nvarchar(30) = null,
	@user1FieldType nvarchar(6) = null,
	@user1FieldLookup nvarchar(50) = null,
	@user1Required nchar(1) = N'<literal:7>', 
	@user2FieldName nvarchar(30) = null,
	@user2FieldType nvarchar(6) = null,
	@user2FieldLookup nvarchar(50) = null,
	@user2Required nchar(1) = N'<literal:8>', 
	@user3FieldName nvarchar(30) = null,
	@user3FieldType nvarchar(6) = null,
	@user3FieldLookup nvarchar(50) = null,
	@user3Required nchar(1) = N'<literal:9>', 
	@user4FieldName nvarchar(30) = null,
	@user4FieldType nvarchar(6) = null,
	@user4FieldLookup nvarchar(50) = null,
	@user4Required nchar(1) = N'<literal:10>', 
	@user5FieldName nvarchar(30) = null,
	@user5FieldType nvarchar(6) = null,
	@user5FieldLookup nvarchar(50) = null,
	@user5Required nchar(1) = N'<literal:11>', 
	@user6FieldName nvarchar(30) = null,
	@user6FieldType nvarchar(6) = null,
	@user6FieldLookup nvarchar(50) = null,
	@user6Required nchar(1) = N'<literal:12>', 
	@user7FieldName nvarchar(30) = null,
	@user7FieldType nvarchar(6) = null,
	@user7FieldLookup nvarchar(50) = null,
	@user7Required nchar(1) = N'<literal:13>', 
	@user8FieldName nvarchar(30) = null,
	@user8FieldType nvarchar(6) = null,
	@user8FieldLookup nvarchar(50) = null,
	@user8Required nchar(1) = N'<literal:14>', 
	@processStamp nvarchar(100))

AS
	SET NOCOUNT ON;
IF EXISTS (SELECT 1  
               FROM GENERIC_CONFIG_HEADER  
               WHERE RECORD_TYPE = @recordType)
BEGIN
UPDATE  GENERIC_CONFIG_HEADER SET
		
		 DESCRIPTION = @description,
		 SYSTEM_CREATED = @systemCreated,
		 SYS1_FIELD_NAME = @sys1FieldName,
		 SYS1_FIELD_TYPE         = @sys1FieldType,
     SYS1_FIELD_LOOKUP       = @sys1FieldLookup,
     SYS1_REQUIRED           = @sys1Required,
     SYS2_FIELD_NAME         = @sys2FieldName,
     SYS2_FIELD_TYPE         = @sys2FieldType,
     SYS2_FIELD_LOOKUP       = @sys2FieldLookup,
     SYS2_REQUIRED           = @sys2Required,
     SYS3_FIELD_NAME         = @sys3FieldName,
     SYS3_FIELD_TYPE         = @sys3FieldType,
     SYS3_FIELD_LOOKUP       = @sys3FieldLookup,
     SYS3_REQUIRED           = @sys3Required,
     SYS4_FIELD_NAME         = @sys4FieldName,
     SYS4_FIELD_TYPE         = @sys4FieldType,
     SYS4_FIELD_LOOKUP       = @sys4FieldLookup,
     SYS4_REQUIRED           = @sys4Required,
     SYS5_FIELD_NAME         = @sys5FieldName,
     SYS5_FIELD_TYPE         = @sys5FieldType,
     SYS5_FIELD_LOOKUP       = @sys5FieldLookup,
     SYS5_REQUIRED           = @sys5Required,
     USER1_FIELD_NAME        = @user1FieldName,
     USER1_FIELD_TYPE        = @user1FieldType,
     USER1_FIELD_LOOKUP      = @user1FieldLookup,
     USER1_REQUIRED          = @user1Required,
     USER2_FIELD_NAME        = @user2FieldName,
     USER2_FIELD_TYPE        = @user2FieldType,
     USER2_FIELD_LOOKUP      = @user2FieldLookup,
     USER2_REQUIRED          = @user2Required,
     USER3_FIELD_NAME        = @user3FieldName,
     USER3_FIELD_TYPE        = @user3FieldType,
     USER3_FIELD_LOOKUP      = @user3FieldLookup,
     USER3_REQUIRED          = @user3Required,
     USER4_FIELD_NAME        = @user4FieldName,
     USER4_FIELD_TYPE        = @user4FieldType,
     USER4_FIELD_LOOKUP      = @user4FieldLookup,
     USER4_REQUIRED          = @user4Required,
     USER5_FIELD_NAME        = @user5FieldName,
     USER5_FIELD_TYPE        = @user5FieldType,
     USER5_FIELD_LOOKUP      = @user5FieldLookup,
     USER5_REQUIRED          = @user5Required,
     USER6_FIELD_NAME        = @user6FieldName,
     USER6_FIELD_TYPE        = @user6FieldType,
     USER6_FIELD_LOOKUP      = @user6FieldLookup,
     USER6_REQUIRED          = @user6Required,
     USER7_FIELD_NAME        = @user7FieldName,
     USER7_FIELD_TYPE        = @user7FieldType,
     USER7_FIELD_LOOKUP      = @user7FieldLookup,
     USER7_REQUIRED          = @user7Required,
     USER8_FIELD_NAME        = @user8FieldName,
     USER8_FIELD_TYPE        = @user8FieldType,
     USER8_FIELD_LOOKUP      = @user8FieldLookup,
     USER8_REQUIRED          = @user8Required,
     USER_STAMP              = N'<literal:15>',
     PROCESS_STAMP           = @processStamp,
     DATE_TIME_STAMP         = GETUTCDATE()
		   WHERE RECORD_TYPE = @recordType;
END
ELSE
BEGIN
INSERT INTO GENERIC_CONFIG_HEADER
		(RECORD_TYPE,
		 DESCRIPTION,
		 SYSTEM_CREATED,
		 SYS1_FIELD_NAME,
		 SYS1_FIELD_TYPE,
		 SYS1_FIELD_LOOKUP,
		 SYS1_REQUIRED,
		 SYS2_FIELD_NAME,
		 SYS2_FIELD_TYPE,
		 SYS2_FIELD_LOOKUP,
		 SYS2_REQUIRED,
		 SYS3_FIELD_NAME,
		 SYS3_FIELD_TYPE,
		 SYS3_FIELD_LOOKUP,
		 SYS3_REQUIRED,
		 SYS4_FIELD_NAME,
		 SYS4_FIELD_TYPE,
		 SYS4_FIELD_LOOKUP,
		 SYS4_REQUIRED,
		 SYS5_FIELD_NAME,
		 SYS5_FIELD_TYPE,
		 SYS5_FIELD_LOOKUP,
		 SYS5_REQUIRED,
		 USER1_FIELD_NAME,
		 USER1_FIELD_TYPE,
		 USER1_FIELD_LOOKUP,
		 USER1_REQUIRED,
		 USER2_FIELD_NAME,
		 USER2_FIELD_TYPE,
		 USER2_FIELD_LOOKUP,
		 USER2_REQUIRED,
		 USER3_FIELD_NAME,
		 USER3_FIELD_TYPE,
		 USER3_FIELD_LOOKUP,
		 USER3_REQUIRED,
		 USER4_FIELD_NAME,
		 USER4_FIELD_TYPE,
		 USER4_FIELD_LOOKUP,
		 USER4_REQUIRED,
		 USER5_FIELD_NAME,
		 USER5_FIELD_TYPE,
		 USER5_FIELD_LOOKUP,
		 USER5_REQUIRED,
		 USER6_FIELD_NAME,
		 USER6_FIELD_TYPE,
		 USER6_FIELD_LOOKUP,
		 USER6_REQUIRED,
		 USER7_FIELD_NAME,
		 USER7_FIELD_TYPE,
		 USER7_FIELD_LOOKUP,
		 USER7_REQUIRED,
		 USER8_FIELD_NAME,
		 USER8_FIELD_TYPE,
		 USER8_FIELD_LOOKUP,
		 USER8_REQUIRED,
		 USER_STAMP,
		 PROCESS_STAMP,
		 DATE_TIME_STAMP)		 
	SELECT @recordType,
		   @description,
		   @systemCreated,
		   @sys1FieldName,
		   @sys1FieldType,
		   @sys1FieldLookup,
		   @sys1Required,
		   @sys2FieldName,
		   @sys2FieldType,
		   @sys2FieldLookup,
		   @sys2Required,
		   @sys3FieldName,
		   @sys3FieldType,
		   @sys3FieldLookup,
		   @sys3Required,
		   @sys4FieldName,
		   @sys4FieldType,
		   @sys4FieldLookup,
		   @sys4Required,
		   @sys5FieldName,
		   @sys5FieldType,
		   @sys5FieldLookup,
		   @sys5Required,
		   @user1FieldName,
		   @user1FieldType,
		   @user1FieldLookup,
		   @user1Required,
		   @user2FieldName,
		   @user2FieldType,
		   @user2FieldLookup,
		   @user2Required,
		   @user3FieldName,
		   @user3FieldType,
		   @user3FieldLookup,
		   @user3Required,
		   @user4FieldName,
		   @user4FieldType,
		   @user4FieldLookup,
		   @user4Required,
		   @user5FieldName,
		   @user5FieldType,
		   @user5FieldLookup,
		   @user5Required,
		   @user6FieldName,
		   @user6FieldType,
		   @user6FieldLookup,
		   @user6Required,
		   @user7FieldName,
		   @user7FieldType,
		   @user7FieldLookup,
		   @user7Required,
		   @user8FieldName,
		   @user8FieldType,
		   @user8FieldLookup,
		   @user8Required,
		   N'<literal:16>',
		   @processStamp,
		   GETUTCDATE();
END
	
-- [comment omitted]
