-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
CREATE VIEW dbo.SHIPMENT_HEADER_VIEW_SIMPLE
AS
SELECT     INTERNAL_SHIPMENT_NUM, SHIPMENT_ID, CARRIER, CARRIER_SERVICE, PRIORITY, CUSTOMER_CATEGORY1, ACTUAL_SHIP_DATE_TIME, LEADING_STS, 
                      TRAILING_STS, CONSOLIDATED, SHIP_TO_CITY, SHIP_TO_STATE, SHIP_TO_COUNTRY, CREATION_DATE_TIME_STAMP, CUSTOMER, USER_DEF1, 
                      SHIPPING_LOAD_NUM, LAUNCH_NUM
FROM         dbo.SHIPMENT_HEADER
UNION
SELECT     INTERNAL_SHIPMENT_NUM, SHIPMENT_ID, CARRIER, CARRIER_SERVICE, PRIORITY, CUSTOMER_CATEGORY1, ACTUAL_SHIP_DATE_TIME, LEADING_STS, 
                      TRAILING_STS, CONSOLIDATED, SHIP_TO_CITY, SHIP_TO_STATE, SHIP_TO_COUNTRY, CREATION_DATE_TIME_STAMP, CUSTOMER, USER_DEF1, 
                      SHIPPING_LOAD_NUM, LAUNCH_NUM
FROM         dbo.AR_SHIPMENT_HEADER