-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
CREATE VIEW INVENTORY_BALANCE_VIEW
AS	
	SELECT 		
		LOCATION_INVENTORY.WAREHOUSE,
		LOCATION_INVENTORY.ITEM,
		ISNULL(LOCATION_INVENTORY.COMPANY,N'<literal:1>') COMPANY,	  	
		ISNULL(LOCATION_INVENTORY.QUANTITY_UM,N'<literal:2>') QUANTITY_UM,               
		LOCATION_INVENTORY.INVENTORY_STS, 
		sum(LOCATION_INVENTORY.ON_HAND_QTY) AS Total_ON_HAND_QTY,	
		sum(LOCATION_INVENTORY.ALLOCATED_QTY) AS Total_Allocated_Quantity,
		sum(LOCATION_INVENTORY.IN_TRANSIT_QTY) AS Total_Intransit_Quantity,	
		sum(LOCATION_INVENTORY.SUSPENSE_QTY) AS Total_Suspense_Quantity		                 	
	FROM LOCATION_INVENTORY LEFT JOIN LOCATION ON LOCATION_INVENTORY.LOCATION = LOCATION.LOCATION 
	AND LOCATION_INVENTORY.WAREHOUSE = LOCATION.WAREHOUSE  	
	WHERE EXISTS (
		SELECT N'<literal:3>'
		FROM GENERIC_CONFIG_DETAIL CFG Inner join LOCATION LOC
		ON LOCATION_INVENTORY.LOCATION = LOC.LOCATION
		AND LOCATION_INVENTORY.WAREHOUSE = LOC.WAREHOUSE
		AND CFG.RECORD_TYPE = N'<literal:4>'
		AND CFG.IDENTIFIER = LOC.LOCATION_CLASS
		AND SYS1VALUE = N'<literal:5>')
	AND (
		(ALLOCATED_QTY IS NOT NULL AND ALLOCATED_QTY != 0)
		OR (ON_HAND_QTY IS NOT NULL AND ON_HAND_QTY != 0)
		OR (IN_TRANSIT_QTY IS NOT NULL AND IN_TRANSIT_QTY != 0)
		OR (SUSPENSE_QTY IS NOT NULL AND SUSPENSE_QTY != 0))  		
	Group by LOCATION_INVENTORY.WAREHOUSE,
	LOCATION_INVENTORY.ITEM,
	LOCATION_INVENTORY.COMPANY,	
	LOCATION_INVENTORY.QUANTITY_UM,             
	LOCATION_INVENTORY.INVENTORY_STS;
	


