-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
CREATE VIEW SHIPPING_CONTAINER_ORDER_VIEW
AS
SELECT 
       CONTAINER_ID, 
       CONTAINER_TYPE, 
       PARENT_CONTAINER_ID, 
       ITEM, 
       COMPANY, 
       LOT, 
       LOCATION, 
       ORIGINAL_PICK_LOC, 
       SUM(QUANTITY) as QUANTITY,
       QUANTITY_UM, 
       LAUNCH_NUM, 
	   INTERNAL_ORDER_NUM,
       WAREHOUSE, 
       INTERNAL_SHIPMENT_NUM
from 
(
       select 
             case when SC.CONTAINER_TYPE = N'<literal:1>' THEN PARENT.CONTAINER_ID ELSE SC.CONTAINER_ID END AS CONTAINER_ID, 
             CASE WHEN SC.CONTAINER_TYPE = N'<literal:2>' THEN PARENT.CONTAINER_TYPE ELSE SC.CONTAINER_TYPE END AS CONTAINER_TYPE,  
             CASE WHEN (SC.PARENT = TREEUNIT.INTERNAL_CONTAINER_NUM OR SC.INTERNAL_CONTAINER_NUM =  TREEUNIT.INTERNAL_CONTAINER_NUM) 
                    THEN NUll ELSE TREEUNIT.CONTAINER_ID END as PARENT_CONTAINER_ID,
             SC.ITEM,
             SC.COMPANY,
             SC.LOT,
             SC.QUANTITY,
             SC.QUANTITY_UM,
             SC.LOCATION,
             SC.ORIGINAL_PICK_LOC,
             SC.LAUNCH_NUM,
             SC.WAREHOUSE,
             SC.INTERNAL_SHIPMENT_NUM,
			 SC.INTERNAL_ORDER_NUM
       FROM SHIPPING_CONTAINER SC 
       LEFT OUTER JOIN SHIPPING_CONTAINER PARENT ON SC.PARENT = PARENT.INTERNAL_CONTAINER_NUM
       LEFT OUTER JOIN SHIPPING_CONTAINER TREEUNIT ON SC.TREE_UNIT = TREEUNIT.INTERNAL_CONTAINER_NUM
       WHERE SC.INTERNAL_SHIPMENT_LINE_NUM > 0
) result
GROUP BY CONTAINER_ID, CONTAINER_TYPE, PARENT_CONTAINER_ID, ITEM, COMPANY, LOT, LOCATION, ORIGINAL_PICK_LOC, QUANTITY_UM, LAUNCH_NUM, WAREHOUSE, INTERNAL_SHIPMENT_NUM, INTERNAL_ORDER_NUM