-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
CREATE VIEW ITEM_ORDER_QUANTITY_VIEW
AS
	SELECT
	   SD.ITEM,
	   ISNULL(SD.COMPANY,N'<literal:1>') COMPANY,
	   SD.QUANTITY_UM,
	   SD.WAREHOUSE,	   
	   SUM(SD.TOTAL_QTY) TOTAL_ORDERED_QUANTITY 
	FROM
		SHIPMENT_DETAIL SD INNER JOIN SHIPMENT_HEADER SH 
		ON SD.INTERNAL_SHIPMENT_NUM=SH.INTERNAL_SHIPMENT_NUM
	WHERE SH.TRAILING_STS < 900
	GROUP BY
	   SD.ITEM,
	   SD.COMPANY,
	   SD.QUANTITY_UM,
	   SD.WAREHOUSE;
	   



