-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
CREATE VIEW METADATA_INSIGHT_DOCUMENT_MANAGEMENT_VIEW
AS
SELECT 
 OBJECT_ID
,REFERENCE_TYPE
,REFERENCE_CATEGORY
,REFERENCE_ID
,INTERNAL_REFERENCE_NUM
,NOTES
,DOCUMENT_SOURCE
,COMPANY
,WAREHOUSE
,USER_DEF1
,USER_DEF2
,USER_DEF3
,USER_DEF4
,USER_DEF5
,USER_DEF6
,USER_DEF7
,USER_DEF8
,USER_STAMP
,PROCESS_STAMP
,DATE_TIME_STAMP
,N'<literal:1>' AS ICON,
REVERSE(SUBSTRING(REVERSE(DOCUMENT_SOURCE), 1, CHARINDEX((CASE WHEN CHARINDEX(N'<literal:2>', DOCUMENT_SOURCE) > 0 THEN N'<literal:3>' ELSE N'<literal:4>' END), REVERSE(DOCUMENT_SOURCE)) - 1)) AS FILE_NAME
FROM DOCUMENT_MANAGEMENT LMD
