-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
CREATE VIEW dbo.SHIPPING_CONTAINER_VIEW
AS
SELECT     INTERNAL_SHIPMENT_NUM, INTERNAL_SHIPMENT_LINE_NUM, CONTAINER_ID, ITEM, TRACKING_NUMBER, status, WEIGHT, QUANTITY, 
                      INTERNAL_MOP_NUMBER, INTERNAL_CONTAINER_NUM, TREE_UNIT, PARENT, CONTAINER_TYPE
FROM         dbo.SHIPPING_CONTAINER
UNION
SELECT     INTERNAL_SHIPMENT_NUM, INTERNAL_SHIPMENT_LINE_NUM, CONTAINER_ID, ITEM, TRACKING_NUMBER, status, WEIGHT, QUANTITY, 
                      INTERNAL_MOP_NUMBER, INTERNAL_CONTAINER_NUM, TREE_UNIT, PARENT, CONTAINER_TYPE
FROM         dbo.AR_SHIPPING_CONTAINER