-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */







CREATE VIEW SHIPPING_LOAD_SHIPPING_ADDRESS_VIEW
AS   
SELECT   
sl.INTERNAL_LOAD_NUM,
sl.[warehouse],
sl.[LEADING_STS],
sl.[LEADING_STS_DATE],
sl.LEADING_STS_FAILED,
sl.TRAILING_STS,
sl.TRAILING_STS_DATE,
sl.TRAILING_STS_FAILED,
sl.CARRIER,
sl.SCHEDULED_SHIP_DATE,
sl.ACTUAL_SHIP_DATE_TIME,
sl.PLANNED_DEPARTURE_DATE_TIME,
sl.ACTUAL_DEPARTURE_DATE_TIME,
sl.LOAD_SIZE_DEF,
sl.LOAD_CLOSED,
sl.SEAL_ID,
sl.TRAILER_ID,
ISNULL(sh.TOTAL_SHIPMENTS,0) AS TOTAL_SHIPMENTS,
ISNULL(sh.TOTAL_CONTAINERS,0) AS TOTAL_CONTAINERS,
ISNULL(sh.TOTAL_WEIGHT,0) AS TOTAL_WEIGHT,
ISNULL(sh.TOTAL_VOLUME,0) AS TOTAL_VOLUME,
sl.WEIGHT_UM,
sl.VOLUME_UM,
sl.MANUALLY_ENTERED,
sl.USER_DEF1,
sl.USER_DEF2,
sl.USER_DEF3,
sl.USER_DEF4,
sl.USER_DEF5,
sl.USER_DEF6,
ISNULL(sl.USER_DEF7,0) AS USER_DEF7,
ISNULL(sl.USER_DEF8,0) AS USER_DEF8,
sl.USER_STAMP,
sl.PROCESS_STAMP,
sl.DATE_TIME_STAMP,
sl.in_confirmation,
sl.MASTER_BOL_TYPE,
sl.MASTER_BOL_NUM_ALPHA,
sl.PRO_NUM_ALPHA,
sl.CONSOLIDATOR,
sl.[ROUTE],
sl.VESSEL,
sl.VOYAGE,
sl.DOCK_DOOR,
sl.IN_TRANSFER,
sa.INTERNAL_SHIP_ADDRESS_NUM,
sa.RECORD_TYPE,
sa.Name,
sa.ATTENTION_TO,
sa.ADDRESS1,
sa.ADDRESS2,
sa.ADDRESS3,
sa.CITY,
sa.[STATE],
sa.POSTAL_CODE,
sa.COUNTRY,
sa.PHONE_NUM,
sa.FAX_NUM,
sa.EMAIL_ADDRESS
FROM SHIPPING_LOAD sl WITH (NOLOCK)
LEFT OUTER JOIN SHIPPING_ADDRESS sa 
ON sl.INTERNAL_LOAD_NUM = sa.INTERNAL_LOAD_NUM
LEFT OUTER JOIN
 (SELECT SHIPPING_LOAD_NUM,
					SUM(ISNULL(TOTAL_CONTAINERS,0)) AS TOTAL_CONTAINERS,
					COUNT(INTERNAL_SHIPMENT_NUM) AS TOTAL_SHIPMENTS,
					SUM(ISNULL(TOTAL_WEIGHT,0)) AS TOTAL_WEIGHT,
					SUM(ISNULL(TOTAL_VOLUME,0)) AS TOTAL_VOLUME
			FROM SHIPMENT_HEADER_VIEW WITH (NOLOCK)
			GROUP BY SHIPPING_LOAD_NUM) sh 
		ON sl.INTERNAL_LOAD_NUM = sh.SHIPPING_LOAD_NUM;