-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */












CREATE PROCEDURE wm_RUDownloadOrderHeader01
	@ProcessStamp nvarchar(100)
AS
	UPDATE DOWNLOAD_ORDER_HEADER
	SET INTERFACE_CONDITION = N'<literal:1>', PROCESS_STAMP = @ProcessStamp
	WHERE (INTERFACE_CONDITION = N'<literal:2>' OR INTERFACE_CONDITION IS NULL);

	UPDATE DOWNLOAD_ORDER_DETAIL
	SET INTERFACE_CONDITION = N'<literal:3>', PROCESS_STAMP = @ProcessStamp
	WHERE 
		INTERFACE_LINK_ID IN (
			SELECT INTERFACE_RECORD_ID
			FROM DOWNLOAD_ORDER_HEADER WITH (NOLOCK)
			WHERE PROCESS_STAMP = @ProcessStamp
			AND INTERFACE_CONDITION <> N'<literal:4>'
			AND INTERFACE_CONDITION <> N'<literal:5>' );
			
	UPDATE DOWNLOAD_ORDER_DETAIL
	SET INTERFACE_CONDITION = N'<literal:6>', PROCESS_STAMP = @ProcessStamp
	WHERE 
		(INTERFACE_CONDITION = N'<literal:7>' OR INTERFACE_CONDITION IS NULL)
		AND (INTERFACE_LINK_ID IS NULL OR INTERFACE_LINK_ID NOT IN (
			SELECT INTERFACE_RECORD_ID
			FROM DOWNLOAD_ORDER_HEADER WITH (NOLOCK)));

	UPDATE DOWNLOAD_ORDER_CONTAINER
	SET INTERFACE_CONDITION = N'<literal:8>',PROCESS_STAMP = @ProcessStamp
	WHERE 
		INTERFACE_LINK_ID IN (
		SELECT INTERFACE_RECORD_ID
		FROM DOWNLOAD_ORDER_HEADER WITH (NOLOCK)
			WHERE PROCESS_STAMP = @ProcessStamp
			AND INTERFACE_CONDITION <> N'<literal:9>'
			AND INTERFACE_CONDITION <> N'<literal:10>');   
   
	UPDATE DOWNLOAD_ORDER_CONTAINER
	SET INTERFACE_CONDITION = N'<literal:11>', PROCESS_STAMP = @ProcessStamp
	WHERE   
		(INTERFACE_CONDITION = N'<literal:12>' OR INTERFACE_CONDITION IS NULL)
		AND 
		(INTERFACE_LINK_ID IS NULL OR INTERFACE_LINK_ID NOT IN (
			SELECT INTERFACE_RECORD_ID
			FROM DOWNLOAD_ORDER_HEADER WITH (NOLOCK)));

	UPDATE DOWNLOAD_ORDER_COMMENT
	SET INTERFACE_CONDITION = N'<literal:13>', PROCESS_STAMP = @ProcessStamp
	WHERE  (INTERFACE_CONDITION = N'<literal:14>' OR INTERFACE_CONDITION IS NULL) AND
		INTERFACE_LINK_ID IN (
			SELECT INTERFACE_RECORD_ID
			FROM DOWNLOAD_ORDER_HEADER WITH (NOLOCK)
			WHERE PROCESS_STAMP = @ProcessStamp
			AND INTERFACE_CONDITION <> N'<literal:15>'
			AND INTERFACE_CONDITION <> N'<literal:16>');

	UPDATE DOWNLOAD_ORDER_COMMENT
	SET INTERFACE_CONDITION = N'<literal:17>', PROCESS_STAMP = @ProcessStamp
	WHERE  (INTERFACE_CONDITION = N'<literal:18>' OR INTERFACE_CONDITION IS NULL) AND
		INTERFACE_LINK_ID IN (
			SELECT INTERFACE_RECORD_ID
			FROM DOWNLOAD_ORDER_DETAIL WITH (NOLOCK)
			WHERE PROCESS_STAMP = @ProcessStamp
			AND INTERFACE_CONDITION <> N'<literal:19>'
			AND INTERFACE_CONDITION <> N'<literal:20>');

	UPDATE DOWNLOAD_ORDER_COMMENT
	SET INTERFACE_CONDITION = N'<literal:21>', PROCESS_STAMP = @ProcessStamp
	WHERE  (INTERFACE_CONDITION = N'<literal:22>' OR INTERFACE_CONDITION IS NULL)
		AND (
			INTERFACE_LINK_ID IS NULL
			OR INTERFACE_LINK_ID NOT IN (
				SELECT INTERFACE_RECORD_ID
				FROM DOWNLOAD_ORDER_HEADER WITH (NOLOCK))
			OR INTERFACE_LINK_ID NOT IN (
				SELECT INTERFACE_RECORD_ID
				FROM DOWNLOAD_ORDER_DETAIL WITH (NOLOCK)));


	UPDATE DOWNLOAD_ORDER_VAS_ACTIVITY
	SET INTERFACE_CONDITION = N'<literal:23>', PROCESS_STAMP = @ProcessStamp
	WHERE  (INTERFACE_CONDITION = N'<literal:24>' OR INTERFACE_CONDITION IS NULL) AND
		INTERFACE_LINK_ID IN (
			SELECT INTERFACE_RECORD_ID
			FROM DOWNLOAD_ORDER_HEADER WITH (NOLOCK)
			WHERE PROCESS_STAMP = @ProcessStamp
			AND INTERFACE_CONDITION <> N'<literal:25>'
			AND INTERFACE_CONDITION <> N'<literal:26>');

	UPDATE DOWNLOAD_ORDER_VAS_ACTIVITY
	SET INTERFACE_CONDITION = N'<literal:27>', PROCESS_STAMP = @ProcessStamp
	WHERE  (INTERFACE_CONDITION = N'<literal:28>' OR INTERFACE_CONDITION IS NULL) AND
		INTERFACE_LINK_ID IN (
			SELECT INTERFACE_RECORD_ID
			FROM DOWNLOAD_ORDER_DETAIL WITH (NOLOCK)
			WHERE PROCESS_STAMP = @ProcessStamp
			AND INTERFACE_CONDITION <> N'<literal:29>'
			AND INTERFACE_CONDITION <> N'<literal:30>');

	UPDATE DOWNLOAD_ORDER_VAS_ACTIVITY
	SET INTERFACE_CONDITION = N'<literal:31>', PROCESS_STAMP = @ProcessStamp
	WHERE  (INTERFACE_CONDITION = N'<literal:32>' OR INTERFACE_CONDITION IS NULL)
		AND (
			INTERFACE_LINK_ID IS NULL
			OR INTERFACE_LINK_ID NOT IN (
				SELECT INTERFACE_RECORD_ID
				FROM DOWNLOAD_ORDER_HEADER WITH (NOLOCK))
			OR INTERFACE_LINK_ID NOT IN (
				SELECT INTERFACE_RECORD_ID
				FROM DOWNLOAD_ORDER_DETAIL WITH (NOLOCK)));

	SELECT N'<literal:33>', *
	FROM DOWNLOAD_ORDER_HEADER
	WHERE PROCESS_STAMP = @ProcessStamp
	AND INTERFACE_CONDITION <> N'<literal:34>'
	AND INTERFACE_CONDITION <> N'<literal:35>';

	SELECT N'<literal:36>', *
	FROM DOWNLOAD_ORDER_DETAIL
	WHERE PROCESS_STAMP = @ProcessStamp
	AND INTERFACE_CONDITION <> N'<literal:37>'
	AND INTERFACE_CONDITION <> N'<literal:38>';

	SELECT N'<literal:39>', *
	FROM DOWNLOAD_ORDER_CONTAINER
	WHERE PROCESS_STAMP = @ProcessStamp
	AND INTERFACE_CONDITION <> N'<literal:40>'
	AND INTERFACE_CONDITION <> N'<literal:41>';

	SELECT N'<literal:42>', *
	FROM DOWNLOAD_ORDER_COMMENT
	WHERE PROCESS_STAMP = @ProcessStamp
	AND INTERFACE_CONDITION <> N'<literal:43>'
	AND INTERFACE_CONDITION <> N'<literal:44>';

	SELECT N'<literal:45>', *
	FROM DOWNLOAD_ORDER_VAS_ACTIVITY
	WHERE PROCESS_STAMP = @ProcessStamp
	AND INTERFACE_CONDITION <> N'<literal:46>'
	AND INTERFACE_CONDITION <> N'<literal:47>'
    AND (ERP_ORDER_LINE_NUM <= 0 OR ERP_ORDER_LINE_NUM IS NULL);

    SELECT N'<literal:48>', *
	FROM DOWNLOAD_ORDER_VAS_ACTIVITY
	WHERE PROCESS_STAMP = @ProcessStamp
	AND INTERFACE_CONDITION <> N'<literal:49>'
	AND INTERFACE_CONDITION <> N'<literal:50>'
    AND ERP_ORDER_LINE_NUM > 0;


