-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */









CREATE PROCEDURE wm_RUDownloadReceiptHeader01
	@ProcessStamp nvarchar(100)
AS
	
	UPDATE DOWNLOAD_PURCHASE_ORDER_HEADER
	SET INTERFACE_CONDITION = N'<literal:1>', PROCESS_STAMP = @ProcessStamp
	WHERE (INTERFACE_CONDITION = N'<literal:2>' OR INTERFACE_CONDITION IS NULL);
	
	UPDATE DOWNLOAD_PURCHASE_ORDER_DETAIL
	SET INTERFACE_CONDITION = N'<literal:3>', PROCESS_STAMP = @ProcessStamp
	WHERE INTERFACE_LINK_ID IN (
			SELECT INTERFACE_RECORD_ID
			FROM DOWNLOAD_PURCHASE_ORDER_HEADER
			WHERE PROCESS_STAMP = @ProcessStamp
			AND INTERFACE_CONDITION <> N'<literal:4>');

	UPDATE DOWNLOAD_PURCHASE_ORDER_DETAIL
	SET INTERFACE_CONDITION = N'<literal:5>', PROCESS_STAMP = @ProcessStamp
	WHERE (INTERFACE_CONDITION = N'<literal:6>' OR INTERFACE_CONDITION IS NULL)
		AND (INTERFACE_LINK_ID IS NULL OR INTERFACE_LINK_ID NOT IN (
			SELECT INTERFACE_RECORD_ID
			FROM DOWNLOAD_PURCHASE_ORDER_HEADER));
	
	UPDATE DOWNLOAD_RECEIPT_HEADER
	SET INTERFACE_CONDITION = N'<literal:7>', PROCESS_STAMP = @ProcessStamp
	WHERE (INTERFACE_CONDITION = N'<literal:8>' OR INTERFACE_CONDITION IS NULL);

	UPDATE DOWNLOAD_RECEIPT_DETAIL
	SET INTERFACE_CONDITION = N'<literal:9>', PROCESS_STAMP = @ProcessStamp
	WHERE (
		INTERFACE_LINK_ID IN (
			SELECT INTERFACE_RECORD_ID
			FROM DOWNLOAD_RECEIPT_HEADER
			WHERE PROCESS_STAMP = @ProcessStamp
			AND INTERFACE_CONDITION <> N'<literal:10>'))
	OR (
		(INTERFACE_CONDITION = N'<literal:11>' OR INTERFACE_CONDITION IS NULL)
		AND (INTERFACE_LINK_ID IS NULL OR INTERFACE_LINK_ID NOT IN (
			SELECT INTERFACE_RECORD_ID
			FROM DOWNLOAD_RECEIPT_HEADER)));

	UPDATE DOWNLOAD_RECEIPT_CONTAINER
	SET INTERFACE_CONDITION = N'<literal:12>', PROCESS_STAMP = @ProcessStamp
	WHERE (
		INTERFACE_LINK_ID IN (
			SELECT INTERFACE_RECORD_ID
			FROM DOWNLOAD_RECEIPT_HEADER
			WHERE PROCESS_STAMP = @ProcessStamp
			AND INTERFACE_CONDITION <> N'<literal:13>'))
	OR (
		(INTERFACE_CONDITION = N'<literal:14>' OR INTERFACE_CONDITION IS NULL)
		AND (INTERFACE_LINK_ID IS NULL OR INTERFACE_LINK_ID NOT IN (
			SELECT INTERFACE_RECORD_ID
			FROM DOWNLOAD_RECEIPT_HEADER)));

	-- [comment omitted]
	UPDATE DOWNLOAD_APPT_SCHEDULE
	SET INTERFACE_CONDITION = N'<literal:15>', PROCESS_STAMP = @ProcessStamp
	WHERE (
		INTERFACE_LINK_ID IN (
			SELECT INTERFACE_RECORD_ID
			FROM DOWNLOAD_APPT_SCHEDULE
			WHERE PROCESS_STAMP = @ProcessStamp 
			AND INTERFACE_LINK_TYPE = N'<literal:16>'
			AND INTERFACE_CONDITION <> N'<literal:17>'))
	OR (
		(INTERFACE_CONDITION = N'<literal:18>' OR INTERFACE_CONDITION IS NULL)
		AND (INTERFACE_LINK_ID IS NULL OR INTERFACE_LINK_ID NOT IN (
			SELECT INTERFACE_RECORD_ID
			FROM DOWNLOAD_APPT_SCHEDULE WHERE INTERFACE_LINK_TYPE = N'<literal:19>')));

	-- [comment omitted]
	UPDATE DOWNLOAD_SERIAL_NUMBER
	   SET INTERFACE_CONDITION = N'<literal:20>', PROCESS_STAMP = @ProcessStamp
	 WHERE (INTERFACE_LINK_ID IN (
			SELECT INTERFACE_RECORD_ID
			  FROM DOWNLOAD_RECEIPT_CONTAINER
			 WHERE PROCESS_STAMP = @ProcessStamp)
	    AND (INTERFACE_CONDITION = N'<literal:21>' 
	      	OR INTERFACE_CONDITION IS NULL))
	    OR ((INTERFACE_CONDITION = N'<literal:22>' 
	         OR INTERFACE_CONDITION IS NULL)
		    AND (INTERFACE_LINK_ID IS NULL 
		         OR (INTERFACE_LINK_ID NOT IN (
						SELECT INTERFACE_RECORD_ID
						  FROM DOWNLOAD_RECEIPT_HEADER)
					 AND INTERFACE_LINK_ID NOT IN (
						SELECT INTERFACE_RECORD_ID
						  FROM DOWNLOAD_SERIAL_NUMBER))));

	-- [comment omitted]
	-- [comment omitted]
	UPDATE DOWNLOAD_SERIAL_NUMBER
	   SET INTERFACE_CONDITION = N'<literal:23>', PROCESS_STAMP = @ProcessStamp
	 WHERE INTERFACE_LINK_ID IN (
			SELECT INTERFACE_RECORD_ID
			  FROM DOWNLOAD_SERIAL_NUMBER
			 WHERE PROCESS_STAMP = @ProcessStamp)
	 AND INTERFACE_CONDITION <> N'<literal:24>';

	SELECT N'<literal:25>', *
	FROM DOWNLOAD_PURCHASE_ORDER_HEADER
	WHERE PROCESS_STAMP = @ProcessStamp
	AND INTERFACE_CONDITION <> N'<literal:26>';

	SELECT N'<literal:27>', *
	FROM DOWNLOAD_PURCHASE_ORDER_DETAIL
	WHERE PROCESS_STAMP = @ProcessStamp
	AND INTERFACE_CONDITION <> N'<literal:28>';

	SELECT N'<literal:29>', *
	FROM DOWNLOAD_RECEIPT_HEADER
	WHERE PROCESS_STAMP = @ProcessStamp
	AND INTERFACE_CONDITION <> N'<literal:30>';

	SELECT N'<literal:31>', *
	FROM DOWNLOAD_RECEIPT_DETAIL
	WHERE PROCESS_STAMP = @ProcessStamp
	AND INTERFACE_CONDITION <> N'<literal:32>';

	SELECT N'<literal:33>', *
	FROM DOWNLOAD_RECEIPT_CONTAINER
	WHERE PROCESS_STAMP = @ProcessStamp
	AND INTERFACE_CONDITION <> N'<literal:34>';
	
	SELECT N'<literal:35>', *
	FROM DOWNLOAD_SERIAL_NUMBER
	WHERE PROCESS_STAMP = @ProcessStamp
	AND INTERFACE_CONDITION <> N'<literal:36>';

	SELECT N'<literal:37>', *
	FROM DOWNLOAD_APPT_SCHEDULE
	WHERE PROCESS_STAMP = @ProcessStamp
	AND INTERFACE_CONDITION <> N'<literal:38>';
	



