-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */





CREATE VIEW SPLIT_SHIPMENT_VIEW 
AS
SELECT 
ERP_ORDER_LINE_NUM ,  
ITEM,  
ITEM_DESC, 
CUSTOMER_PO, 
QUANTITY_AT_STS1 ,  
QUANTITY_UM , 
INTERNAL_SHIPMENT_LINE_NUM,ERP_ORDER , 
RELATED_INTERNAL_LINE_NUM, 
INTERNAL_SHIPMENT_NUM,
cast( 0  as numeric(19,5)) AS SPLIT_QUANTITY FROM SHIPMENT_DETAIL