-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
CREATE VIEW METADATA_INSIGHT_DIF_OUTGOING_MESSAGE
AS 
SELECT DOM.MSG_ID
      ,DOM.DATE_TIME_STAMP
      ,DOM.DATA
      ,DOM.STATUS
      ,DOM.PROCESS_STAMP
      ,DOM.USER_DEF1
      ,DOM.USER_DEF2
      ,DOM.USER_DEF3
      ,DOM.USER_DEF4
      ,DOM.USER_DEF5
      ,DOM.USER_DEF6
      ,DOM.USER_DEF7
      ,DOM.USER_DEF8
      ,DOM.EVENT_ID
      ,DOM.USER_STAMP
      ,DOM.MSG_PART1
      ,DOM.MSG_PART2
      ,DOM.MSG_PART3
      ,DOM.MSG_PART4
      ,DOM.MSG_PART5
      ,DOM.MSG_PART6
      ,DOM.MSG_PART7
      ,DOM.MSG_PART8
      ,DOM.MSG_PART9
      ,DOM.MSG_PART10
      ,DOM.MSG_PART11
      ,DOM.MSG_PART12
      ,DOM.MSG_PART13
      ,DOM.MSG_PART14
      ,DOM.MSG_PART15
      ,DOM.MSG_PART16
      ,DOM.MSG_PART17
      ,DOM.MSG_PART18
      ,DOM.MSG_PART19
      ,DOM.MSG_PART20
      ,DOM.MSG_PART21
      ,DOM.MSG_PART22
      ,DOM.MSG_PART23
      ,DOM.MSG_PART24
      ,DOM.MSG_PART25
      ,DOM.MSG_PART26
      ,DOM.MSG_PART27
      ,DOM.MSG_PART28
      ,DOM.MSG_PART29
      ,DOM.MSG_PART30
      ,dbo.RSCMfn_RtrvMsg(DOM.ERROR_MESSAGE) AS ERROR_MESSAGE

	  ,DEPT.ENDPOINT_ID AS ENDPOINT_ID
      ,DEPT.NAME AS ENDPOINT_NAME
      ,DEPT.DESCRIPTION AS ENDPOINT_DESC
      ,DEPT.ENDPOINT_HANDLER
      ,DEPT.DIRECTION AS ENDPOINT_DIRECTION

      ,DE.EVENT_DESCRIPTION AS EVENT_DESC
      ,DE.ENABLED
      ,DE.EXECUTION_IDENTIFIER
      ,DE.MULTI_THREADED

  FROM DIF_OUTGOING_MESSAGE DOM
  JOIN DIF_EVENT DE 
  on DOM.EVENT_ID = DE.EVENT_ID
  JOIN DIF_ENDPOINT DEPT
  on DE.EVENT_ID = DEPT.EVENT_ID

