-- DOCUMENTATION ONLY: literals/comments removed; do not execute.

CREATE PROCEDURE dbc_IScreenControlGridColumns(
    @active char(1),
	@columnTemplate nvarchar(2000) = NULL, 
    @decimalPositions nvarchar(50) = NULL,
    @field nvarchar(2000),
    @fieldName nvarchar(128) = NULL,
    @fieldType numeric(3) = NULL,
    @fieldWidth numeric(9) = NULL,
    @hidden char(1) = N'<literal:1>',
	@isPrimaryKey char(1) = N'<literal:2>',
	@isEditable char(1) = N'<literal:3>',
	@requiredForEdit char(1) = N'<literal:4>',
	@dataSourceType numeric(4) = NULL,
	@dataSource nvarchar(2000) = NULL,
	@bindToForInsert nvarchar(2000) = NULL,
    @validationMessage nvarchar(2000) = NULL,
	@allowSort char(1) = N'<literal:5>',
    @processStamp nvarchar(100),
    @resourceKey nvarchar(50) = NULL,
    @screenControlId numeric(9),
    @sequence numeric(9) = NULL,
    @sqlClauseType numeric(3),
    @userDef1 nvarchar(25) = NULL,
    @userDef2 nvarchar(25) = NULL,
    @userDef3 nvarchar(25) = NULL,
    @userDef4 nvarchar(25) = NULL,
    @userDef5 nvarchar(25) = NULL,
    @userDef6 nvarchar(25) = NULL,
    @userDef7 numeric(19,5) = NULL,
    @userDef8 numeric(19,5) = NULL)
AS
    SET NOCOUNT ON;

    INSERT INTO SCREEN_CONTROL_GRID_COLUMNS
        (ACTIVE,
         DATE_TIME_STAMP,
		 COLUMN_TEMPLATE, 
         DECIMAL_POSITIONS,
         FIELD,
         FIELD_NAME,
         FIELD_TYPE,
         FIELD_WIDTH,
         HIDDEN,
		 IS_PRIMARY_KEY,
		 IS_EDITABLE, 
		 REQUIRED_FOR_EDIT, 
		 DATA_SOURCE_TYPE, 
		 DATA_SOURCE, 
		 BIND_TO_FOR_INSERT, 
		VALIDATION_MESSAGE,
		ALLOW_SORT,
         PROCESS_STAMP,
         RESOURCE_KEY,
         SCREEN_CONTROL_ID,
         SEQUENCE,
         SQL_CLAUSE_TYPE,
         SYSTEM_CREATED,
         USER_DEF1,
         USER_DEF2,
         USER_DEF3,
         USER_DEF4,
         USER_DEF5,
         USER_DEF6,
         USER_DEF7,
         USER_DEF8,
         USER_STAMP)
    SELECT @active,
           getDate(),
		   @columnTemplate, 
           @decimalPositions,
           @field,
           @fieldName,
           @fieldType,
           @fieldWidth,
           @hidden,
		   @isPrimaryKey, 
		   @isEditable, 
		   @requiredForEdit, 
		   @dataSourceType, 
		   @dataSource, 
		   @bindToForInsert, 
		@validationMessage,
		@allowSort,
           @processStamp,
           @resourceKey,
           @screenControlId,
           @sequence,
           @sqlClauseType,
           N'<literal:6>',
           @userDef1,
           @userDef2,
           @userDef3,
           @userDef4,
           @userDef5,
           @userDef6,
           @userDef7,
           @userDef8,
           N'<literal:7>'
     WHERE NOT EXISTS(SELECT *
                        FROM SCREEN_CONTROL_GRID_COLUMNS WHERE SCREEN_CONTROL_ID = @screenControlId and (ISNULL(FIELD, 0) =  ISNULL(@field, 0)) 
                        and (ISNULL(FIELD_NAME, 0) =  ISNULL(@fieldName, 0))
                        and SQL_CLAUSE_TYPE = @sqlClauseType);
-- [comment omitted]