-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */





CREATE VIEW LABOR_MANAGEMENT_DETAIL_VIEW
AS
SELECT 
LMD.ACTIVITY_SCREEN,
LMD.ACTIVITY_TYPE,
LMD.ACTUAL_RATE,
LMD.CLOSED,
LMD.COMPANY,
LMD.CONTAINER_ID,
LMD.DATE_TIME_STAMP,
LMD.DEVICE_TYPE,
LMD.END_DATE_TIME,
LMD.EQUIPMENT_TYPE,
LMD.FROM_LOCATION,
LMD.GOAL_QUANTITY,
LMD.GOAL_RATE,
LMD.INTERNAL_CONTAINER_NUM,
LMD.INTERNAL_DETAIL_NUM,
LMD.INTERNAL_NUM,
LMD.ITEM,
LMD.LABOR_GROUP,
LMD.LABOR_TYPE,
LMD.LICENSE_PLATE,
LMD.MANUAL,
LMD.PERCENT_OF_GOAL,
LMD.PROCESS_STAMP,
LMD.PROCESS_TYPE,
LMD.QUANTITY_UM,
LMD.REFERENCE_ID,
LMD.SESSION_ID,
LMD.SHIFT,
LMD.START_DATE_TIME,
LMD.TO_LOCATION,
LMD.TOTAL_ACTUAL_TIME,
LMD.TOTAL_LABOR_COST,
LMD.TOTAL_QUANTITY,
LMD.TOTAL_TRANSACTIONS,
LMD.TOTAL_VALUE,
LMD.TOTAL_VOLUME,
LMD.TOTAL_WEIGHT,
LMD.USER_DEF1,
LMD.USER_DEF2,
LMD.USER_DEF3,
LMD.USER_DEF4,
LMD.USER_DEF5,
LMD.USER_DEF6,
LMD.USER_DEF7,
LMD.USER_DEF8,
LMD.USER_NAME,
LMD.USER_STAMP,
LMD.VOLUME_UM,
LMD.WAREHOUSE,
LMD.WAVE_NUM,
LMD.WEIGHT_UM,
LMD.WORK_GROUP,
LMD.WORK_TEAM,
LMD.WORK_UNIT,
I.WEB_THUMBNAIL_IMG,
I.DESCRIPTION,
LMD.WAREHOUSE_DAY,
LMD.CONSOLIDATED

FROM LABOR_MANAGEMENT_DETAIL LMD
LEFT OUTER JOIN ITEM I ON LMD.ITEM = I.ITEM AND COALESCE(LMD.COMPANY, N'<literal:1>') = COALESCE(I.COMPANY, N'<literal:2>');