-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */








CREATE VIEW METADATA_INSIGHT_PUTWALL_LOCATION_VIEW
AS  
SELECT

	td.TOTE_HEADER_ID,
	th.TOTE_ID,
	td.PUT_WALL_LOCATION,
	th.CONDITION,
	th.MARK_FOR_SORTING,
	th.USER_ASSIGNED,
	sh.SHIPMENT_ID,
	sc.CONTAINER_ID,
	td.INTERNAL_CONTAINER_NUM,
	td.INTERNAL_SHIPMENT_NUM,
	td.INTERNAL_SHIPMENT_LINE_NUM,
	td.LAUNCH_NUM,
	td.PROCESS_STAMP,
	td.USER_STAMP,
	td.DATE_TIME_STAMP,
	td.PARENT_CONTAINER_NUM,
	td.SORT_COMPLETED,
	td.LOCATION_CLEARED,
	l.ACTIVE, 
	l.ALLOCATE_IN_TRANSIT, 
	l.ALLOCATION_ZONE, 
	l.ALLOW_WORK_SELECT_ON_SYS_DIR, 
	l.CHECK_DIG, 
	l.DATE_TIME_STAMP as LOCATION_DATE_TIME_STAMP, 
	l.DOCK_AREA_ANCHOR_CRITERIA, 
	l.DOCK_AREA_SELECTION_PRIORITY, 
	l.DOCK_LOCATION_TYPE, 
	l.INCOMING_PD_LOC, 
	l.LAST_CYCLE_COUNT_DATE, 
	l.LOCATING_ZONE, 
	l.LOCATION,
	l.LOCATION_TEMPLATE, 
	l.LOCATION_CLASS, 
	l.LOCATION_STS, 
	l.LOCATION_SUBCLASS, 
	l.TEMPLATE_FIELD1, 
	l.TEMPLATE_FIELD2, 
	l.TEMPLATE_FIELD3, 
	l.TEMPLATE_FIELD4, 
	l.TEMPLATE_FIELD5, 
	l.LOCATION_TYPE, 
	l.LOCKED_FOR_LOCATE, 
	l.MAX_LOTS, 
	l.MOVEMENT_CLS, 
	l.MULTI_ITEM, 
	l.NEXT_DOCK_AREA, 
	l.OBJECT_ID, 
	l.OUTGOING_PD_LOC, 
	l.PARENT_DOCK_AREA, 
	l.PICKING_SEQ, 
	l.PROCESS_STAMP as LOCATION_PROCESS_STAMP, 
	l.PUTAWAY_SEQ, 
	l.QTY_UM_LIST, 
	l.REAL_TIME_RPLN, 
	l.ROW_VERSION, 
	l.RPLN_EVALUATION, 
	l.STAGING_ROW_COUNT, 
	l.TRACK_CONTAINERS, 
	l.USER_DEF1 as LOCATION_USER_DEF1, 
	l.USER_DEF2 as LOCATION_USER_DEF2, 
	l.USER_DEF3 as LOCATION_USER_DEF3, 
	l.USER_DEF4 as LOCATION_USER_DEF4, 
	l.USER_DEF5 as LOCATION_USER_DEF5, 
	l.USER_DEF6 as LOCATION_USER_DEF6, 
	l.USER_DEF7 as LOCATION_USER_DEF7, 
	l.USER_DEF8 as LOCATION_USER_DEF8, 
	l.USER_STAMP as LOCATION_USER_STAMP, 
	l.VECTOR_COORDINATE, 
	l.VERIFICATION_METH, 
	l.warehouse as WAREHOUSE, 
	l.WORK_ZONE,
	case when l.LOCATION_STS=N'<literal:1>' then N'<literal:2>' else N'<literal:3>' END AS EMPTY
	
FROM
	LOCATION l
	left outer join TOTE_DETAIL td on l.LOCATION = td.PUT_WALL_LOCATION AND l.warehouse=td.WAREHOUSE AND COALESCE(td.LOCATION_CLEARED,N'<literal:4>')<>N'<literal:5>'
	left outer join TOTE_HEADER th on th.OBJECT_ID=td.TOTE_HEADER_ID
	left outer join SHIPMENT_HEADER sh on sh.INTERNAL_SHIPMENT_NUM=td.INTERNAL_SHIPMENT_NUM
	left outer join SHIPPING_CONTAINER sc on sc.INTERNAL_CONTAINER_NUM=td.PARENT_CONTAINER_NUM
	
Where 
	l.LOCATION_CLASS = N'<literal:6>' ;

