-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
CREATE PROCEDURE wm_DUploadOrderHeader01
	@ProcessStamp nvarchar(100)
AS
	DELETE FROM UPLOAD_ORDER_DETAIL
	WHERE INTERFACE_LINK_ID IN 
		(SELECT INTERFACE_RECORD_ID
		 FROM UPLOAD_ORDER_HEADER
		 WHERE PROCESS_STAMP = @ProcessStamp);

	DELETE FROM UPLOAD_ORDER_HEADER
	WHERE PROCESS_STAMP = @ProcessStamp;