-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */







CREATE PROCEDURE wm_RUUploadOrderHeader01
	@BatchId nvarchar(100),
	@InterfaceDtlKey numeric(9),
	@InterfaceConst nvarchar(25)
AS
	
	IF @InterfaceConst = N'<literal:1>'
		BEGIN

			UPDATE UPLOAD_ORDER_HEADER
			SET PROCESS_STAMP = @BatchId,
			INTERFACE_CONDITION = @InterfaceConst
			Where INTERFACE_CONDITION !=N'<literal:2>'
			AND INTERFACE_DETAIL_KEY_NUM = @InterfaceDtlKey

			UPDATE UPLOAD_ORDER_DETAIL
			SET PROCESS_STAMP = @BatchId,
			INTERFACE_CONDITION = @InterfaceConst
			Where INTERFACE_CONDITION !=N'<literal:3>'
			AND INTERFACE_LINK_ID IN ( Select INTERFACE_RECORD_ID from UPLOAD_ORDER_HEADER where PROCESS_STAMP = @BatchId)

			UPDATE UPLOAD_ORDER_COMMENT
			SET PROCESS_STAMP = @BatchId,
			INTERFACE_CONDITION = @InterfaceConst
			Where INTERFACE_CONDITION !=N'<literal:4>'
			AND (INTERFACE_LINK_ID IN ( Select INTERFACE_RECORD_ID from UPLOAD_ORDER_HEADER where PROCESS_STAMP = @BatchId) 
			OR INTERFACE_LINK_ID IN ( Select INTERFACE_RECORD_ID from UPLOAD_ORDER_DETAIL where PROCESS_STAMP = @BatchId))

			UPDATE UPLOAD_ORDER_CONTAINER
			SET PROCESS_STAMP = @BatchId,
			INTERFACE_CONDITION = @InterfaceConst
			Where INTERFACE_CONDITION !=N'<literal:5>'
			AND INTERFACE_LINK_ID IN ( Select INTERFACE_RECORD_ID from UPLOAD_ORDER_HEADER where PROCESS_STAMP = @BatchId)
	
			UPDATE UPLOAD_SERIAL_NUMBER
			SET PROCESS_STAMP = @BatchId,
			INTERFACE_CONDITION = @InterfaceConst
			Where INTERFACE_CONDITION !=N'<literal:6>'
			AND INTERFACE_LINK_ID IN ( Select INTERFACE_RECORD_ID from UPLOAD_ORDER_CONTAINER where PROCESS_STAMP = @BatchId)

			UPDATE UPLOAD_LOCATION_INVENTORY_ATTRIBUTES
			SET PROCESS_STAMP = @BatchId,
			INTERFACE_CONDITION = @InterfaceConst
			Where INTERFACE_CONDITION !=N'<literal:7>'
			AND INTERFACE_LINK_ID IN ( Select INTERFACE_RECORD_ID from UPLOAD_ORDER_CONTAINER where PROCESS_STAMP = @BatchId)

			SELECT TOP 1 *
			FROM UPLOAD_ORDER_HEADER
			WHERE PROCESS_STAMP = @BatchId
		END
	ELSE 
	BEGIN
			UPDATE UPLOAD_ORDER_HEADER
			SET INTERFACE_CONDITION =@InterfaceConst
			Where INTERFACE_CONDITION = N'<literal:8>'
			AND PROCESS_STAMP = @BatchId
			AND INTERFACE_DETAIL_KEY_NUM = @InterfaceDtlKey

			UPDATE UPLOAD_ORDER_DETAIL
			SET PROCESS_STAMP = @BatchId,
			INTERFACE_CONDITION =@InterfaceConst
			Where INTERFACE_CONDITION =N'<literal:9>'
			AND INTERFACE_LINK_ID IN ( Select INTERFACE_RECORD_ID from UPLOAD_ORDER_HEADER where PROCESS_STAMP = @BatchId)

			UPDATE UPLOAD_ORDER_COMMENT
			SET PROCESS_STAMP = @BatchId,
			INTERFACE_CONDITION =@InterfaceConst
			Where INTERFACE_CONDITION =N'<literal:10>'
			AND (INTERFACE_LINK_ID IN ( Select INTERFACE_RECORD_ID from UPLOAD_ORDER_HEADER where PROCESS_STAMP = @BatchId) 
			OR INTERFACE_LINK_ID IN ( Select INTERFACE_RECORD_ID from UPLOAD_ORDER_DETAIL where PROCESS_STAMP = @BatchId))

			UPDATE UPLOAD_ORDER_CONTAINER
			SET PROCESS_STAMP = @BatchId,
			INTERFACE_CONDITION =@InterfaceConst
			Where INTERFACE_CONDITION =N'<literal:11>'
			AND INTERFACE_LINK_ID IN ( Select INTERFACE_RECORD_ID from UPLOAD_ORDER_HEADER where PROCESS_STAMP = @BatchId)
	
			UPDATE UPLOAD_SERIAL_NUMBER
			SET PROCESS_STAMP = @BatchId,
			INTERFACE_CONDITION =@InterfaceConst
			Where INTERFACE_CONDITION =N'<literal:12>'
			AND INTERFACE_LINK_ID IN ( Select INTERFACE_RECORD_ID from UPLOAD_ORDER_CONTAINER where PROCESS_STAMP = @BatchId)

			UPDATE UPLOAD_LOCATION_INVENTORY_ATTRIBUTES
			SET PROCESS_STAMP = @BatchId,
			INTERFACE_CONDITION =@InterfaceConst
			Where INTERFACE_CONDITION =N'<literal:13>'
			AND INTERFACE_LINK_ID IN ( Select INTERFACE_RECORD_ID from UPLOAD_ORDER_CONTAINER where PROCESS_STAMP = @BatchId)

			SELECT *
			FROM UPLOAD_ORDER_HEADER
			WHERE PROCESS_STAMP = @BatchId
	END
