-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */





  

CREATE PROCEDURE MetaTrans_DockLocationTransfer
(
@internalContainerNum numeric(9), @culture nvarchar(10)
)
AS
	SET NOCOUNT ON;

	SELECT TOP 1
	N'<literal:1>' AS N'<literal:2>',	
	N'<literal:3>' AS N'<literal:4>', 	
	SHIPPING_CONTAINER.INTERNAL_CONTAINER_NUM AS N'<literal:5>', 		
	SHIPPING_CONTAINER.CONTAINER_ID AS N'<literal:6>' ,
	SHIPPING_CONTAINER.COMPANY AS N'<literal:7>',
	SHIPPING_CONTAINER.WAREHOUSE AS N'<literal:8>' ,
	(SELECT top 1 Location FROM SHIPPING_CONTAINER 
	WHERE SHIPPING_CONTAINER.INTERNAL_SHIPMENT_LINE_NUM > 0 AND
	(SHIPPING_CONTAINER.INTERNAL_CONTAINER_NUM = @internalContainerNum
	OR SHIPPING_CONTAINER.PARENT = @internalContainerNum
	OR SHIPPING_CONTAINER.TREE_UNIT = @internalContainerNum)) AS N'<literal:9>',	
	(select top 1 WI.TO_LOC
	FROM WORK_INSTRUCTION WI
	WHERE WI.TREE_UNIT = @internalContainerNum
	AND WI.INSTRUCTION_TYPE = N'<literal:10>'
	AND WI.INTERNAL_NUM_TYPE IN (N'<literal:11>', N'<literal:12>')
	and WI.CONDITION != N'<literal:13>') AS N'<literal:14>'
	FROM SHIPPING_CONTAINER where INTERNAL_CONTAINER_NUM=@internalContainerNum

	-- [comment omitted]
	SELECT 
	N'<literal:15>' AS N'<literal:16>',	
	N'<literal:17>' AS N'<literal:18>', 
	SHIPMENT_HEADER.INTERNAL_SHIPMENT_NUM AS N'<literal:19>', 
	SHIPMENT_HEADER.SHIPMENT_ID AS N'<literal:20>',
	SHIPMENT_HEADER.CARRIER AS N'<literal:21>',
	SHIPMENT_HEADER.CARRIER_SERVICE AS N'<literal:22>',
	SHIPMENT_HEADER.COMPANY AS N'<literal:23>',
	SHIPMENT_HEADER.Warehouse AS N'<literal:24>' ,
	SHIPMENT_HEADER.SHIP_TO AS N'<literal:25>',
	SHIPMENT_HEADER.SHIP_TO_NAME AS N'<literal:26>',
	SHIPMENT_HEADER.SHIP_TO_ADDRESS1 AS N'<literal:27>',
	SHIPMENT_HEADER.SHIP_TO_ADDRESS2 AS N'<literal:28>',
	SHIPMENT_HEADER.SHIP_TO_ADDRESS3 AS N'<literal:29>',
	SHIPMENT_HEADER.SHIP_TO_CITY AS N'<literal:30>',
	SHIPMENT_HEADER.SHIP_TO_STATE AS N'<literal:31>',
	SHIPMENT_HEADER.SHIP_TO_COUNTRY AS N'<literal:32>',
	SHIPMENT_HEADER.SHIP_TO_POSTAL_CODE AS N'<literal:33>',
	SHIPMENT_HEADER.SHIP_TO_PHONE_NUM AS N'<literal:34>',
	SHIPMENT_HEADER.SHIP_TO_FAX_NUM AS N'<literal:35>' ,
	SHIPMENT_HEADER.SHIP_TO_ATTENTION_TO AS N'<literal:36>',
	SHIPMENT_HEADER.SHIP_TO_EMAIL_ADDRESS AS N'<literal:37>' ,
	SHIPMENT_HEADER.SCHEDULED_SHIP_DATE AS N'<literal:38>'
	FROM SHIPMENT_HEADER WHERE SHIPMENT_HEADER.INTERNAL_SHIPMENT_NUM = (select INTERNAL_SHIPMENT_NUM from SHIPPING_CONTAINER where INTERNAL_CONTAINER_NUM=@internalContainerNum) ;