-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */







CREATE PROCEDURE wm_UOrderDetail01
	@RowsAffected int OUTPUT,
	@InternalOrderDtlNum numeric(9),
	@StatusFlowName nvarchar(25),
	@Warehouse nvarchar(25),
	@AllocationName nvarchar(25),
	@InternalOrderNum numeric(9),
	@ErpOrderLineNum numeric(19,5),
	@Condition nvarchar(25),
	@Customer nvarchar(25),
	@CustomerName nvarchar(50),
	@CustomerAddress1 nvarchar(50),
	@CustomerAddress2 nvarchar(50),
	@CustomerAddress3 nvarchar(50),
	@CustomerAttentionTo nvarchar(50),
	@CustomerCity nvarchar(30),
	@CustomerState nvarchar(25),
	@CustomerCountry nvarchar(25),
	@CustomerPostalCode nvarchar(25),
	@CustomerPhoneNum nvarchar(50),
	@CustomerFaxNum nvarchar(25),
	@CustomerEmailAddress nvarchar(50),
	@ShipTo nvarchar(25),
	@ShipToName nvarchar(50),
	@ShipToAddress1 nvarchar(50),
	@ShipToAddress2 nvarchar(50),
	@ShipToAddress3 nvarchar(50),
	@ShipToAttentionTo nvarchar(50),
	@ShipToCity nvarchar(30),
	@ShipToState nvarchar(25),
	@ShipToCountry nvarchar(25),
	@ShipToPostalCode nvarchar(25),
	@ShipToPhoneNum nvarchar(50),
	@ShipToFaxNum nvarchar(25),
	@ShipToEmailAddress nvarchar(50),
	@CustomerPo nvarchar(25),
	@OrderDate datetime,
	@RequestedDeliveryDate datetime,
	@RequestedDeliveryType nvarchar(10),
	@Item nvarchar(50),
	@Company nvarchar(25),
	@ItemDesc nvarchar(100),
	@ItemSize nvarchar(25),
	@ItemColor nvarchar(25),
	@ItemStyle nvarchar(25),
	@InitialWeight numeric(19,5),
	@WeightUm nvarchar(25),
	@InitialVolume numeric(19,5),
	@VolumeUm nvarchar(25),
	@InitialValue numeric(19,5),
	@InitialQty numeric(19,5),
	@OpenQty numeric(19,5),
	@ShippedQty numeric(19,5),
	@QuantityUm nvarchar(25),
	@CustomerItem nvarchar(50),
	@PlannedShipDate datetime,
	@InterfacedDate datetime,
	@PickLoc nvarchar(25),
	@PickZone nvarchar(25),
	@SecondaryPickLoc nvarchar(25),
	@SecondaryPickZone nvarchar(25),
	@ItemLength numeric(19,5),
	@ItemWidth numeric(19,5),
	@ItemHeight numeric(19,5),
	@ItemDimensionUm nvarchar(25),
	@ItemVolume numeric(19,5),
	@TotalVolume numeric(28,5),
	@TotalWeight numeric(28,5),
	@ItemDivision nvarchar(25),
	@ItemDepartment nvarchar(25),
	@ItemListPrice numeric(19,5),
	@ItemNetPrice numeric(19,5),
	@OriginalItemOrdered nvarchar(50),
	@Invoice nvarchar(25),
	@PackingCategory nvarchar(25),
	@HazardousCode nvarchar(25),
	@NmfcCode nvarchar(25),
	@CatalogId nvarchar(25),
	@ManufacturerId nvarchar(25),
	@MerchandiseCode nvarchar(25),
	@LotControlled nchar(1),
	@SerialNumReqd nchar(1),
	@CatchWeightReqd nchar(1),
	@UserDef1 nvarchar(25),
	@UserDef2 nvarchar(25),
	@UserDef3 nvarchar(25),
	@UserDef4 nvarchar(25),
	@UserDef5 nvarchar(25),
	@UserDef6 nvarchar(25),
	@UserDef7 numeric(19,5),
	@UserDef8 numeric(19,5),
	@UserStamp nvarchar(30),
	@ProcessStamp nvarchar(100),
	@DateTimeStamp datetime,
	@OrderPriority nvarchar(25),
	@MarkForName nvarchar(50),
	@MarkForAddress1 nvarchar(50),
	@MarkForAddress2 nvarchar(50),
	@MarkForAddress3 nvarchar(50),
	@MarkForAttentionTo nvarchar(50),
	@MarkForCity nvarchar(30),
	@MarkForState nvarchar(25),
	@MarkForCountry nvarchar(25),
	@MarkForPostalCode nvarchar(25),
	@MarkForPhoneNum nvarchar(50),
	@MarkForFaxNum nvarchar(25),
	@MarkForEmailAddress nvarchar(50),
	@PickListId nvarchar(25),
	@ItemWeight numeric(19,5),
	@Lot nvarchar(25),
	@ItemClass nvarchar(50),
	@InterfaceRecordId nvarchar(25),
	@ItemCategory1 nvarchar(50),
	@ItemCategory2 nvarchar(50),
	@ItemCategory3 nvarchar(50),
	@ItemCategory4 nvarchar(50),
	@ItemCategory5 nvarchar(50),
	@ItemCategory6 nvarchar(50),
	@ItemCategory7 nvarchar(50),
	@ItemCategory8 nvarchar(50),
	@ItemCategory9 nvarchar(50),
	@ItemCategory10 nvarchar(50),
	@PackingClass nvarchar(25),
	@AllocateFullLocQty nchar(1),
	@AllowPctAlloc nchar(1),
	@MinimumAllocPct numeric(4),
	@MaximumAllocPct numeric(4),
	@TreatAsLoose nchar(1)
AS
	UPDATE ORDER_DETAIL
	   SET
		STATUS_FLOW_NAME=@StatusFlowName,
		warehouse=@Warehouse,
		ALLOCATION_NAME=@AllocationName,
		INTERNAL_ORDER_NUM=@InternalOrderNum,
		ERP_ORDER_LINE_NUM=@ErpOrderLineNum,
		CONDITION=@Condition,
		CUSTOMER=@Customer,
		CUSTOMER_NAME=@CustomerName,
		CUSTOMER_ADDRESS1=@CustomerAddress1,
		CUSTOMER_ADDRESS2=@CustomerAddress2,
		CUSTOMER_ADDRESS3=@CustomerAddress3,
		CUSTOMER_ATTENTION_TO=@CustomerAttentionTo,
		CUSTOMER_CITY=@CustomerCity,
		CUSTOMER_STATE=@CustomerState,
		CUSTOMER_COUNTRY=@CustomerCountry,
		CUSTOMER_POSTAL_CODE=@CustomerPostalCode,
		CUSTOMER_PHONE_NUM=@CustomerPhoneNum,
		CUSTOMER_FAX_NUM=@CustomerFaxNum,
		CUSTOMER_EMAIL_ADDRESS=@CustomerEmailAddress,
		SHIP_TO=@ShipTo,
		SHIP_TO_NAME=@ShipToName,
		SHIP_TO_ADDRESS1=@ShipToAddress1,
		SHIP_TO_ADDRESS2=@ShipToAddress2,
		SHIP_TO_ADDRESS3=@ShipToAddress3,
		SHIP_TO_ATTENTION_TO=@ShipToAttentionTo,
		SHIP_TO_CITY=@ShipToCity,
		SHIP_TO_STATE=@ShipToState,
		SHIP_TO_COUNTRY=@ShipToCountry,
		SHIP_TO_POSTAL_CODE=@ShipToPostalCode,
		SHIP_TO_PHONE_NUM=@ShipToPhoneNum,
		SHIP_TO_FAX_NUM=@ShipToFaxNum,
		SHIP_TO_EMAIL_ADDRESS=@ShipToEmailAddress,
		CUSTOMER_PO=@CustomerPo,
		ORDER_DATE=@OrderDate,
		REQUESTED_DELIVERY_DATE=@RequestedDeliveryDate,
		REQUESTED_DELIVERY_TYPE=@RequestedDeliveryType,
		ITEM=@Item,
		COMPANY=@Company,
		ITEM_DESC=@ItemDesc,
		ITEM_SIZE=@ItemSize,
		ITEM_COLOR=@ItemColor,
		ITEM_STYLE=@ItemStyle,
		INITIAL_WEIGHT=@InitialWeight,
		WEIGHT_UM=@WeightUm,
		INITIAL_VOLUME=@InitialVolume,
		VOLUME_UM=@VolumeUm,
		INITIAL_VALUE=@InitialValue,
		INITIAL_QTY=@InitialQty,
		OPEN_QTY=@OpenQty,
		SHIPPED_QTY=@ShippedQty,
		QUANTITY_UM=@QuantityUm,
		CUSTOMER_ITEM=@CustomerItem,
		PLANNED_SHIP_DATE=@PlannedShipDate,
		INTERFACED_DATE=@InterfacedDate,
		PICK_LOC=@PickLoc,
		PICK_ZONE=@PickZone,
		SECONDARY_PICK_LOC=@SecondaryPickLoc,
		SECONDARY_PICK_ZONE=@SecondaryPickZone,
		ITEM_LENGTH=@ItemLength,
		ITEM_WIDTH=@ItemWidth,
		ITEM_HEIGHT=@ItemHeight,
		ITEM_DIMENSION_UM=@ItemDimensionUm,
		ITEM_VOLUME=@ItemVolume,
		TOTAL_VOLUME=@TotalVolume,
		TOTAL_WEIGHT=@TotalWeight,
		ITEM_DIVISION=@ItemDivision,
		ITEM_DEPARTMENT=@ItemDepartment,
		ITEM_LIST_PRICE=@ItemListPrice,
		ITEM_NET_PRICE=@ItemNetPrice,
		ORIGINAL_ITEM_ORDERED=@OriginalItemOrdered,
		INVOICE=@Invoice,
		PACKING_CATEGORY=@PackingCategory,
		HAZARDOUS_CODE=@HazardousCode,
		NMFC_CODE=@NmfcCode,
		CATALOG_ID=@CatalogId,
		MANUFACTURER_ID=@ManufacturerId,
		MERCHANDISE_CODE=@MerchandiseCode,
		LOT_CONTROLLED=@LotControlled,
		SERIAL_NUM_REQD=@SerialNumReqd,
		CATCH_WEIGHT_REQD=@CatchWeightReqd,
		USER_DEF1=@UserDef1,
		USER_DEF2=@UserDef2,
		USER_DEF3=@UserDef3,
		USER_DEF4=@UserDef4,
		USER_DEF5=@UserDef5,
		USER_DEF6=@UserDef6,
		USER_DEF7=@UserDef7,
		USER_DEF8=@UserDef8,
		USER_STAMP=@UserStamp,
		PROCESS_STAMP=@ProcessStamp,
		DATE_TIME_STAMP=@DateTimeStamp,
		ORDER_PRIORITY=@OrderPriority,
		MARK_FOR_NAME=@MarkForName,
		MARK_FOR_ADDRESS1=@MarkForAddress1,
		MARK_FOR_ADDRESS2=@MarkForAddress2,
		MARK_FOR_ADDRESS3=@MarkForAddress3,
		MARK_FOR_ATTENTION_TO=@MarkForAttentionTo,
		MARK_FOR_CITY=@MarkForCity,
		MARK_FOR_STATE=@MarkForState,
		MARK_FOR_COUNTRY=@MarkForCountry,
		MARK_FOR_POSTAL_CODE=@MarkForPostalCode,
		MARK_FOR_PHONE_NUM=@MarkForPhoneNum,
		MARK_FOR_FAX_NUM=@MarkForFaxNum,
		MARK_FOR_EMAIL_ADDRESS=@MarkForEmailAddress,
		PICK_LIST_ID=@PickListId,
		ITEM_WEIGHT=@ItemWeight,
		LOT=@Lot,
		ITEM_CLASS=@ItemClass,
		INTERFACE_RECORD_ID=@InterfaceRecordId,
		ITEM_CATEGORY1=@ItemCategory1,
		ITEM_CATEGORY2=@ItemCategory2,
		ITEM_CATEGORY3=@ItemCategory3,
		ITEM_CATEGORY4=@ItemCategory4,
		ITEM_CATEGORY5=@ItemCategory5,
		ITEM_CATEGORY6=@ItemCategory6,
		ITEM_CATEGORY7=@ItemCategory7,
		ITEM_CATEGORY8=@ItemCategory8,
		ITEM_CATEGORY9=@ItemCategory9,
		ITEM_CATEGORY10=@ItemCategory10,
		PACKING_CLASS=@PackingClass,
		ALLOCATE_FULL_LOC_QTY=@AllocateFullLocQty,
		ALLOW_PCT_ALLOC=@AllowPctAlloc,
		MINIMUM_ALLOC_PCT=@MinimumAllocPct,
		MAXIMUM_ALLOC_PCT=@MaximumAllocPct,
		TREAT_AS_LOOSE=@TreatAsLoose
	 WHERE INTERNAL_ORDER_DTL_NUM = @InternalOrderDtlNum

	SET @RowsAffected = @@ROWCOUNT


