-- DOCUMENTATION ONLY: literals/comments removed; do not execute.




CREATE VIEW PRODUCT_RECALL_VIEW
AS
SELECT 
	SC.INTERNAL_CONTAINER_NUM,
	CONTAINER_ID,
	ITEM, 
	SC.COMPANY,
	SC.LOT, 
	SC.STATUS, 
	SC.WAREHOUSE, 
	SC.QUANTITY, 
	SC.QUANTITY_UM, 
	ACTUAL_SHIP_DATE_TIME, 
	SHIPMENT_ID,  
	SHIP_TO, 
	SHIP_TO_ADDRESS1, 
	SHIP_TO_ADDRESS2, 
	SHIP_TO_ADDRESS3, 
	SHIP_TO_CITY, 
	SHIP_TO_STATE, 
	SHIP_TO_POSTAL_CODE, 
	SHIP_TO_COUNTRY
FROM
		(SELECT * FROM SHIPPING_CONTAINER
		 UNION ALL
		 SELECT * FROM AR_SHIPPING_CONTAINER) AS SC 
	 INNER JOIN
		(SELECT * FROM SHIPMENT_HEADER
		 UNION ALL
		 SELECT * FROM AR_SHIPMENT_HEADER) AS SH 
     ON SC.INTERNAL_SHIPMENT_NUM = SH.INTERNAL_SHIPMENT_NUM
WHERE SC.STATUS > dbo.STSfn_RtrvSts(N'<literal:1>', N'<literal:2>')