-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
-- [comment omitted]

-- [comment omitted]


/* [comment omitted] */





-- [comment omitted]


CREATE PROCEDURE MetaTrans_GetConsolidateShipment(
@internalShipmentNum numeric(9), @culture nvarchar(10))

AS
	SET NOCOUNT ON;

SELECT N'<literal:1>' AS N'<literal:2>',
	N'<literal:3>' AS N'<literal:4>',
	SHIPMENT_HEADER_VIEW.INTERNAL_SHIPMENT_NUM AS N'<literal:5>', 
	SHIPMENT_HEADER_VIEW.SHIPMENT_ID AS N'<literal:6>',
	SHIPMENT_HEADER_VIEW.CARRIER AS N'<literal:7>',
	SHIPMENT_HEADER_VIEW.CARRIER_SERVICE AS N'<literal:8>',
	SHIPMENT_HEADER_VIEW.FREIGHT_TERMS AS N'<literal:9>',	
	SHIPMENT_HEADER_VIEW.COMPANY AS N'<literal:10>' ,
	SHIPMENT_HEADER_VIEW.Warehouse AS N'<literal:11>' ,
	SHIPMENT_HEADER_VIEW.SCHEDULED_SHIP_DATE AS N'<literal:12>' ,
	SHIPMENT_HEADER_VIEW.CUSTOMER AS N'<literal:13>',
	SHIPMENT_HEADER_VIEW.CUSTOMER_NAME AS N'<literal:14>',
	SHIPMENT_HEADER_VIEW.SHIP_TO AS N'<literal:15>',
	SHIPMENT_HEADER_VIEW.SHIP_TO_NAME AS N'<literal:16>',
	SHIPMENT_HEADER_VIEW.SHIP_TO_ADDRESS1 AS N'<literal:17>',
	SHIPMENT_HEADER_VIEW.SHIP_TO_ADDRESS2 AS N'<literal:18>',
	SHIPMENT_HEADER_VIEW.SHIP_TO_ADDRESS3 AS N'<literal:19>',
	SHIPMENT_HEADER_VIEW.SHIP_TO_CITY AS N'<literal:20>',
	SHIPMENT_HEADER_VIEW.SHIP_TO_STATE AS N'<literal:21>',
	SHIPMENT_HEADER_VIEW.SHIP_TO_POSTAL_CODE AS N'<literal:22>',
	SHIPMENT_HEADER_VIEW.SHIP_TO_COUNTRY AS N'<literal:23>',
	SHIPMENT_HEADER_VIEW.TOTAL_LINES AS N'<literal:24>',
	SHIPMENT_HEADER_VIEW.TOTAL_VOLUME AS N'<literal:25>',
	SHIPMENT_HEADER_VIEW.TOTAL_WEIGHT AS N'<literal:26>',
	SHIPMENT_HEADER_VIEW.WEIGHT_UM AS N'<literal:27>',
	SHIPMENT_HEADER_VIEW.VOLUME_UM AS N'<literal:28>',
	SHIPMENT_HEADER_VIEW.TRAILING_STS AS N'<literal:29>'
FROM SHIPMENT_HEADER_VIEW 
WHERE SHIPMENT_HEADER_VIEW.INTERNAL_SHIPMENT_NUM =@internalShipmentNum