-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */






CREATE PROCEDURE wm_UPurchaseOrderHeader01
	@ClosedDateTime datetime,
	@CreatedDateTime datetime,
	@Company nvarchar(25),
	@DateTimeStamp datetime,	
	@ObjectId numeric(9),
	@ProcessStamp nvarchar(100),
	@PurchaseOrderId nvarchar(25),
	@ReceiptType nvarchar(25),	
	@ShipFrom nvarchar(25),
	@ShipFromAddress1 nvarchar(50),
	@ShipFromAddress2 nvarchar(50),
	@ShipFromAddress3 nvarchar(50),
	@ShipFromCity nvarchar(30),
	@ShipFromState nvarchar(25),
	@ShipFromCountry nvarchar(25),
	@ShipFromPostalCode nvarchar(25),
	@ShipFromName nvarchar(50),
	@ShipFromAttentionTo nvarchar(50),
	@ShipFromEmailAddress nvarchar(50),
	@ShipFromPhoneNum nvarchar(50),
	@ShipFromFaxNum nvarchar(50),
	@SourceId nvarchar(25),
	@SourceName nvarchar(50),
	@SourceAddress1 nvarchar(50),
	@SourceAddress2 nvarchar(50),
	@SourceAddress3 nvarchar(50),
	@SourceCity nvarchar(50),
	@SourceState nvarchar(25),
	@SourcePostalCode nvarchar(25),
	@SourceCountry nvarchar(25),
	@SourceAttentionTo nvarchar(50),
	@SourcePhoneNum nvarchar(50),
	@SourceFaxNum nvarchar(50),
	@SourceEmailAddress nvarchar(50),
	@Status nvarchar(25),
	@UserDef1 nvarchar(25),
	@UserDef2 nvarchar(25),
	@UserDef3 nvarchar(25),
	@UserDef4 nvarchar(25),
	@UserDef5 nvarchar(25),
	@UserDef6 nvarchar(25),
	@UserDef7 numeric(19,5),
	@UserDef8 numeric(19,5),
	@UserStamp nvarchar(30),
	@Warehouse nvarchar(25)
AS
			update
				purchase_order_header
			set
				CLOSED_DATE_TIME = @ClosedDateTime,
				CREATED_DATE_TIME = @CreatedDateTime,
				company = @Company,
				DATE_TIME_STAMP = @DateTimeStamp,	
				PROCESS_STAMP = @ProcessStamp,
				PURCHASE_ORDER_ID = @PurchaseOrderId,
				receipt_type = @ReceiptType,	
				ship_from = @ShipFrom,
				ship_from_address1 = @ShipFromAddress1 ,
				ship_from_address2 = @ShipFromAddress2,
				ship_from_address3 = @ShipFromAddress3,
				ship_from_city = @ShipFromCity,
				ship_from_state = @ShipFromState ,
				ship_from_country = @ShipFromCountry,
				ship_from_postal_code = @ShipFromPostalCode,
				ship_from_name = @ShipFromName,
				ship_from_attention_to = @ShipFromAttentionTo,
				ship_from_email_address = @ShipFromEmailAddress,
				ship_from_phone_num = @ShipFromPhoneNum,
				ship_from_fax_num = @ShipFromFaxNum,
				source_id = @SourceId ,
				source_name = @SourceName,
				source_address1 = @SourceAddress1,
				source_address2 = @SourceAddress2,
				source_address3 = @SourceAddress3,
				source_city =@SourceCity,
				source_state = @SourceState,
				source_postal_code = @SourcePostalCode,
				source_country = @SourceCountry,
				source_attention_to = @SourceAttentionTo,
				source_phone_num = @SourcePhoneNum,
				source_fax_num = @SourceFaxNum,
				source_email_address = @SourceEmailAddress,
				STATUS = @Status,
				user_def1 = @UserDef1,
				user_def2 = @UserDef2,
				user_def3 = @UserDef3,
				user_def4 = @UserDef4,
				user_def5 = @UserDef5,
				user_def6 = @UserDef6,
				user_def7 = @UserDef7,
				user_def8 = @UserDef8,
				USER_STAMP = @UserStamp,
				warehouse =@Warehouse 
			where
				object_id = @ObjectId;


