-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */

















CREATE PROCEDURE wm_IItem01
	@Active nchar(1),
	@AppIdentifier nvarchar(10),
	@InternalItemNum numeric(9) OUTPUT,
	@LocatingRule nvarchar(25),
	@AllocationRule nvarchar(25),
	@Item nvarchar(50),
	@Company nvarchar(25),
	@DaysToExpire numeric(9),
	@Description nvarchar(100),
	@LongDescription nvarchar(2000),
	@ItemTemplate nvarchar(25),
	@TemplateField1 nvarchar(50),
	@TemplateField2 nvarchar(50),
	@TemplateField3 nvarchar(50),
	@TemplateField4 nvarchar(50),
	@TemplateField5 nvarchar(50),
	@Division nvarchar(25),
	@Department nvarchar(25),
	@Cost numeric(19,5),
	@GtinEnabled nchar(1),
	@ItemSize nvarchar(25),
	@ItemColor nvarchar(25),
	@ItemStyle nvarchar(25),
	@NmfcCode nvarchar(25),
	@LotControlled nchar(1),
	@LotTemplate nvarchar(25),
	@CatchWeightReqd nchar(1),
	@UserDef1 nvarchar(25),
	@UserDef2 nvarchar(25),
	@UserDef3 nvarchar(25),
	@UserDef4 nvarchar(25),
	@UserDef5 nvarchar(25),
	@UserDef6 nvarchar(25),
	@UserDef7 numeric(19,5),
	@UserDef8 numeric(19,5),
	@UserStamp nvarchar(30),
	@ProcessStamp nvarchar(100),
	@DateTimeStamp datetime,
	@ListPrice numeric(19,5),
	@NetPrice numeric(19,5),
	@StorageTemplate nvarchar(25),
	@InventoryTracking nchar(1),
	@ItemClass nvarchar(50),
	@HarmonizedCode nvarchar(25),
	@PreferenceCrit nchar(1),
	@Producer nchar(1),
	@NetCost nchar(1),
	@CountryOfOrigin nvarchar(25),
	@PackingClass nvarchar(25),
	@ItemCategory1 nvarchar(50),
	@ItemCategory2 nvarchar(50),
	@ItemCategory3 nvarchar(50),
	@ItemCategory4 nvarchar(50),
	@ItemCategory5 nvarchar(50),
	@ItemCategory6 nvarchar(50),
	@ItemCategory7 nvarchar(50),
	@ItemCategory8 nvarchar(50),
	@ItemCategory9 nvarchar(50),
	@ItemCategory10 nvarchar(50),
	@WebThumbnailImg nvarchar(200),
	@WebImg nvarchar(200),
	@AlternateItem nvarchar(50),
	@AvailableOnWeb nchar(1),
	@ImmediateNeedsLocRule nvarchar(25),
	@ImmediateNeedsEligible nchar(1),
	@InboundQcEligible nchar(1),
	@InboundQcLocRule nvarchar(25),
	@InboundQcAmount numeric(19,5),
	@InboundQcAmountType nchar(1),
	@InboundQcUm nvarchar(25),
	@BomAction nchar(1),
	@EPCCageCode nvarchar(5),
	@EPCCompanyPrefix nvarchar(12),
	@EPCItemReference nvarchar(50),
	@SerialNumTemplate nvarchar(25),
	@SerialNumTracking numeric(3),
	@FedExITN nvarchar(17),
	@FedExXTN nvarchar(17)
	
AS
	INSERT INTO ITEM(
		ACTIVE,
		APP_IDENTIFIER,
		ALLOCATION_RULE,
		ALTERNATE_ITEM,
		AVAILABLE_ON_WEB,
		BOM_ACTION,
		CATCH_WEIGHT_REQD,
		COMPANY,
		COST,
		COUNTRY_OF_ORIGIN,
		DAYS_TO_EXPIRE,
		DATE_TIME_STAMP,
		DEPARTMENT,
		DESCRIPTION,
		LONG_DESCRIPTION,
		DIVISION,
		EPC_CAGE_CODE,
		EPC_COMPANY_PREFIX,
		EPC_ITEM_REFERENCE,
		GTIN_ENABLED,
		HARMONIZED_CODE,
		IMMEDIATE_NEEDS_ELIGIBLE,
		IMMEDIATE_NEEDS_LOC_RULE,
		INBOUND_QC_AMOUNT,
		INBOUND_QC_AMOUNT_TYPE,
		INBOUND_QC_ELIGIBLE,
		INBOUND_QC_LOC_RULE,
		INBOUND_QC_UM,
		INVENTORY_TRACKING,
		ITEM,
		ITEM_CATEGORY1,
		ITEM_CATEGORY10,
		ITEM_CATEGORY2,
		ITEM_CATEGORY3,
		ITEM_CATEGORY4,
		ITEM_CATEGORY5,
		ITEM_CATEGORY6,
		ITEM_CATEGORY7,
		ITEM_CATEGORY8,
		ITEM_CATEGORY9,
		ITEM_CLASS,
		ITEM_COLOR,
		ITEM_SIZE,
		ITEM_STYLE,
		ITEM_TEMPLATE,
		LIST_PRICE,
		LOCATING_RULE,
		LOT_CONTROLLED,
		LOT_TEMPLATE,
		NET_COST,
		NET_PRICE,
		NMFC_CODE,
		PACKING_CLASS,
		PREFERENCE_CRIT,
		PROCESS_STAMP,
		PRODUCER,
		SERIAL_NUM_TEMPLATE,
		SERIAL_NUM_TRACKING,
		STORAGE_TEMPLATE,
		TEMPLATE_FIELD1,
		TEMPLATE_FIELD2,
		TEMPLATE_FIELD3,
		TEMPLATE_FIELD4,
		TEMPLATE_FIELD5,
		USER_DEF1,
		USER_DEF2,
		USER_DEF3,
		USER_DEF4,
		USER_DEF5,
		USER_DEF6,
		USER_DEF7,
		USER_DEF8,
		USER_STAMP,
		WEB_IMG,
		WEB_THUMBNAIL_IMG,
		FedEx_ITN,
		FedEx_XTN
	) VALUES (
		@Active,
		@AppIdentifier,
		@AllocationRule,
		@AlternateItem,
		@AvailableOnWeb,
		@BomAction,
		@CatchWeightReqd,
		@Company,
		@Cost,
		@CountryOfOrigin,
		@DaysToExpire,
		@DateTimeStamp,
		@Department,
		@Description,
		@LongDescription,
		@Division,
		@EpcCageCode,
		@EpcCompanyPrefix,
		@EpcItemReference,
		@GtinEnabled,
		@HarmonizedCode,
		@ImmediateNeedsEligible,
		@ImmediateNeedsLocRule,
		@InboundQcAmount,
		@InboundQcAmountType,
		@InboundQcEligible,
		@InboundQcLocRule,
		@InboundQcUm,
		@InventoryTracking,
		@Item,
		@ItemCategory1,
		@ItemCategory10,
		@ItemCategory2,
		@ItemCategory3,
		@ItemCategory4,
		@ItemCategory5,
		@ItemCategory6,
		@ItemCategory7,
		@ItemCategory8,
		@ItemCategory9,
		@ItemClass,
		@ItemColor,
		@ItemSize,
		@ItemStyle,
		@ItemTemplate,
		@ListPrice,
		@LocatingRule,
		@LotControlled,
		@LotTemplate,
		@NetCost,
		@NetPrice,
		@NmfcCode,
		@PackingClass,
		@PreferenceCrit,
		@ProcessStamp,
		@Producer,
		@SerialNumTemplate,
		@SerialNumTracking,
		@StorageTemplate,
		@TemplateField1,
		@TemplateField2,
		@TemplateField3,
		@TemplateField4,
		@TemplateField5,
		@UserDef1,
		@UserDef2,
		@UserDef3,
		@UserDef4,
		@UserDef5,
		@UserDef6,
		@UserDef7,
		@UserDef8,
		@UserStamp,
		@WebImg,
		@WebThumbnailImg,
		@FedExITN,
		@FedExXTN
	)
SELECT @InternalItemNum = SCOPE_IDENTITY()


