-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */








CREATE PROCEDURE wm_RReceiptHeader04
	@Sts numeric(9)
AS
	DECLARE @uploadReceiptsWithoutCntrs nvarchar(1)
	
	SELECT @uploadReceiptsWithoutCntrs = SYSTEM_VALUE FROM SYSTEM_CONFIG_DETAIL 
	WHERE SYS_KEY = N'<literal:1>'
	AND RECORD_TYPE = N'<literal:2>';

	-- [comment omitted]
	IF (@uploadReceiptsWithoutCntrs = N'<literal:3>')
		BEGIN
			SELECT *
			FROM RECEIPT_HEADER
			WHERE INTERNAL_RECEIPT_NUM IN (
				-- [comment omitted]
				SELECT INTERNAL_RECEIPT_NUM
				FROM RECEIPT_CONTAINER
				WHERE    UPLOAD_INTERFACE_BATCH is null
				   AND STATUS >= @Sts
				   AND ISNULL(INTERNAL_RECEIPT_LINE_NUM, 0) > 0 
				UNION ALL
				-- [comment omitted]
				SELECT INTERNAL_RECEIPT_NUM
				FROM RECEIPT_CONTAINER
				WHERE    UPLOAD_INTERFACE_BATCH is null
				   AND ISNULL(INTERNAL_RECEIPT_LINE_NUM, 0) > 0
				   AND INTERNAL_RECEIPT_NUM IN (SELECT INTERNAL_RECEIPT_NUM FROM RECEIPT_HEADER WHERE CLOSE_DATE IS						NOT NULL)
				UNION ALL
				-- [comment omitted]
				SELECT INTERNAL_RECEIPT_NUM
				FROM RECEIPT_CONTAINER
				WHERE    ISNULL(INTERNAL_RECEIPT_LINE_NUM, 0) = 0 
				   AND INTERNAL_REC_CONT_NUM IN (SELECT PARENT FROM RECEIPT_CONTAINER WHERE 
					UPLOAD_INTERFACE_BATCH is null
					   AND STATUS >= @Sts
					   AND ISNULL(INTERNAL_RECEIPT_LINE_NUM, 0) > 0)
				UNION ALL
				SELECT INTERNAL_RECEIPT_NUM
				FROM RECEIPT_CONTAINER
				WHERE    ISNULL(INTERNAL_RECEIPT_LINE_NUM, 0) = 0 
				   AND INTERNAL_REC_CONT_NUM IN (SELECT PARENT FROM RECEIPT_CONTAINER WHERE 
					UPLOAD_INTERFACE_BATCH is null
				   AND ISNULL(INTERNAL_RECEIPT_LINE_NUM, 0) > 0
				   AND INTERNAL_RECEIPT_NUM IN (SELECT INTERNAL_RECEIPT_NUM FROM RECEIPT_HEADER WHERE CLOSE_DATE IS					   NOT NULL))
				UNION
				SELECT INTERNAL_RECEIPT_NUM 
				FROM RECEIPT_HEADER
				WHERE UPLOAD_INTERFACE_BATCH IS NULL
				AND CLOSE_DATE IS NOT NULL
			);
		END
	ELSE
		BEGIN
			SELECT *
			FROM RECEIPT_HEADER
			WHERE INTERNAL_RECEIPT_NUM IN (
				-- [comment omitted]
				SELECT INTERNAL_RECEIPT_NUM
				FROM RECEIPT_CONTAINER
				WHERE    UPLOAD_INTERFACE_BATCH is null
				   AND STATUS >= @Sts
				   AND ISNULL(INTERNAL_RECEIPT_LINE_NUM, 0) > 0 
				UNION ALL
				-- [comment omitted]
				SELECT INTERNAL_RECEIPT_NUM
				FROM RECEIPT_CONTAINER
				WHERE    UPLOAD_INTERFACE_BATCH is null
				   AND ISNULL(INTERNAL_RECEIPT_LINE_NUM, 0) > 0
				   AND INTERNAL_RECEIPT_NUM IN (SELECT INTERNAL_RECEIPT_NUM FROM RECEIPT_HEADER WHERE CLOSE_DATE IS NOT NULL)
				UNION ALL
				-- [comment omitted]
				SELECT INTERNAL_RECEIPT_NUM
				FROM RECEIPT_CONTAINER
				WHERE    ISNULL(INTERNAL_RECEIPT_LINE_NUM, 0) = 0 
				   AND INTERNAL_REC_CONT_NUM IN (SELECT PARENT FROM RECEIPT_CONTAINER WHERE 
					UPLOAD_INTERFACE_BATCH is null
					   AND STATUS >= @Sts
					   AND ISNULL(INTERNAL_RECEIPT_LINE_NUM, 0) > 0)
				UNION ALL
				SELECT INTERNAL_RECEIPT_NUM
				FROM RECEIPT_CONTAINER
				WHERE    ISNULL(INTERNAL_RECEIPT_LINE_NUM, 0) = 0 
				   AND INTERNAL_REC_CONT_NUM IN (SELECT PARENT FROM RECEIPT_CONTAINER WHERE 
					UPLOAD_INTERFACE_BATCH is null
				   AND ISNULL(INTERNAL_RECEIPT_LINE_NUM, 0) > 0
				   AND INTERNAL_RECEIPT_NUM IN (SELECT INTERNAL_RECEIPT_NUM FROM RECEIPT_HEADER WHERE CLOSE_DATE IS NOT NULL))
			);
		END