-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
CREATE PROCEDURE DeleteUserProfileReferences(
@userNameToDelete nvarchar(30),
@processStamp nvarchar(100),
@userName nvarchar(30)
)        
AS        
BEGIN  
	DELETE FROM WORK_PROFILE_USER_AUTH WHERE USER_NAME = @userNameToDelete
	DELETE FROM COMPANY_ACCESS WHERE USER_NAME = @userNameToDelete
	DELETE FROM WAREHOUSE_ACCESS WHERE USER_NAME = @userNameToDelete
	DELETE FROM USER_ADJSTMNT_AUTHORIZATION WHERE USER_NAME = @userNameToDelete
	DELETE FROM SECURITY WHERE USER_NAME = @userNameToDelete AND SECURITY_LEVEL = N'<literal:1>'
	DELETE FROM WORK_SPECIAL_HANDLING WHERE USER_NAME = @userNameToDelete
	DELETE FROM RECEIVING_PREFERENCE_USER_AUTHORIZATION WHERE USER_NAME = @userNameToDelete
	DELETE FROM USER_SETTINGS WHERE USER_NAME = @userNameToDelete
	DELETE FROM USER_PROFILE WHERE USER_NAME = @userNameToDelete

	INSERT INTO USER_PROFILE_ACTIVITY 
	(ACTIVITY, DATE_TIME_STAMP, PROCESS_STAMP, USER_NAME, USER_STAMP) VALUES 
	(N'<literal:2>', SYSUTCDATETIME(), @processStamp,@userNameToDelete, @userName );
	
END