-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */









CREATE VIEW MOVEMENT_CLASS_ANALYSIS_VIEW AS
SELECT
   ISNULL((CASE WHEN ((
      SELECT
         COUNT(GC.OBJECT_ID) 
      FROM
         GENERIC_CONFIG_DETAIL AS GC WITH (NOLOCK)  INNER JOIN ITEM_UNIT_OF_MEASURE AS IU WITH(NOLOCK)  ON GC.IDENTIFIER=IU.ITEM_CLASS
   )  <> 0)  THEN ITEM_INFO.ITEMCLASSOBJECTID END),
   ITEM_INFO.INTERNALITEMNUM)  AS OBJECT_ID,
    MCA.ITEM,
    ITEM_INFO.ITEMDESC AS DESCRIPTION,
    ITEM_INFO.ITEMCLASS AS ITEM_CLASS,
    MCA.COMPANY,
    MCA.LOCATION,
    L.LOCATION_TYPE,
    L.LOCATING_ZONE,
    MCA.WAREHOUSE,
    NUMBER_OF_HITS,
    MCA.TOTAL_QUANTITY,
    MCA.QUANTITY_UM,
    MCA.NUMBER_OF_DAYS,
    MCA.DATE_TIME_STAMP,
    ITEM_INFO.VALUEPERITEM * MCA.TOTAL_QUANTITY AS TOTAL_VALUE_PICKED,
    ITEM_INFO.COSTPERITEM * MCA.TOTAL_QUANTITY AS TOTAL_COST_PICKED,
    CONVERSION_INFO.WEIGHTPERITEM * (MCA.TOTAL_QUANTITY/CONVERSION_INFO.CONVERSIONQTY) AS TOTAL_WEIGHT_PICKED,
    ITEM_INFO.MOVEMENTCLASS AS QUANTITY_UM_MOVEMENT_CLASS,
    L.MOVEMENT_CLS AS LOCATION_MOVEMENT_CLASS,
    CASE WHEN LEN(ILA.ALLOCATION_LOC)  > 0 THEN N'<literal:1>' ELSE N'<literal:2>' END AS PERMANENT,
	CASE WHEN CONVERSION_INFO.CONVERSIONQUANTITYUM != MCA.QUANTITY_UM THEN MCA.TOTAL_QUANTITY/CONVERSION_INFO.CONVERSIONQTY ELSE MCA.TOTAL_QUANTITY END AS CONVERTED_QTY,
	CONVERSION_INFO.CONVERSIONQUANTITYUM AS CONVERTED_QTY_UM,
	CONVERSION_INFO.CONVERSIONQUANTITYMOVEMENTCLASS AS CONVERTED_UM_MOVEMENT_CLASS
FROM
   MOVEMENT_CLASS_ANALYSIS MCA WITH (NOLOCK)  LEFT OUTER JOIN ITEM_LOCATION_ASSIGNMENT ILA WITH (NOLOCK)  ON ILA.WAREHOUSE = MCA.WAREHOUSE
   AND ILA.ALLOCATION_LOC= MCA.LOCATION
   AND ILA.ITEM = MCA.ITEM
   AND (ILA.COMPANY = MCA.COMPANY OR (ILA.COMPANY IS NULL
   AND MCA.COMPANY IS NULL) )  LEFT OUTER JOIN LOCATION L WITH (NOLOCK)  ON L.LOCATION = MCA.LOCATION
   AND L.WAREHOUSE = MCA.WAREHOUSE
   OUTER APPLY INVFN_RTRVITEMINFOFORBASEUM(MCA.ITEM,MCA.COMPANY,MCA.WAREHOUSE)  AS ITEM_INFO 
   OUTER APPLY INVfn_RtrvConversionInfoForItemAndLocation(MCA.ITEM,MCA.COMPANY,MCA.WAREHOUSE,MCA.LOCATION,MCA.TOTAL_QUANTITY,MCA.QUANTITY_UM,ITEM_INFO.MOVEMENTCLASS, ITEM_INFO.weightPerItem) AS CONVERSION_INFO;