-- DOCUMENTATION ONLY: literals/comments removed; do not execute.

CREATE PROCEDURE wm_UReceiptDetail01
	@RowsAffected int OUTPUT,
	@InternalReceiptLineNum numeric(9),
	@LocatingRule nvarchar(25),
	@Warehouse nvarchar(25),
	@InternalReceiptNum numeric(9),
	@ReceiptId nvarchar(25),
	@Item nvarchar(50),
	@ItemDesc nvarchar(100),
	@ItemClass nvarchar(50),
	@Lot nvarchar(25),
	@Company nvarchar(25),
	@TotalQty numeric(28,5),
	@QuantityUm nvarchar(25),
	@OpenQty numeric(28,5),
	@ErpOrderNum nvarchar(25),
	@ErpOrderType nvarchar(25),
	@ErpOrderLineNum numeric(19,5),
	@ExpirationDateTime datetime,
	@ManufacturedDateTime datetime,
	@ItemWeight numeric(19,5),
	@WeightUm nvarchar(25),
	@ItemLength numeric(19,5),
	@ItemWidth numeric(19,5),
	@ItemHeight numeric(19,5),
	@ItemDimensionUm nvarchar(25),
	@VolumeUm nvarchar(25),
	@ItemDivision nvarchar(25),
	@ItemDepartment nvarchar(25),
	@Value numeric(28,5),
	@ItemSize nvarchar(25),
	@ItemColor nvarchar(25),
	@ItemStyle nvarchar(25),
	@LaunchNum numeric(9),
	@PutLoc nvarchar(25),
	@UserDef1 nvarchar(25),
	@UserDef2 nvarchar(25),
	@UserDef3 nvarchar(25),
	@UserDef4 nvarchar(25),
	@UserDef5 nvarchar(25),
	@UserDef6 nvarchar(25),
	@UserDef7 numeric(19,5),
	@UserDef8 numeric(19,5),
	@UserStamp nvarchar(30),
	@ProcessStamp nvarchar(100),
	@DateTimeStamp datetime,
	@PutZone nvarchar(25),
	@ItemListPrice numeric(19,5),
	@ItemNetPrice numeric(19,5),
	@PutListNum numeric(9),
	@ManuallyEntered nchar(1),
	@LotControlled nchar(1),
	@SerialNumReqd nchar(1),
	@CatchWeightReqd nchar(1),
	@SourceId nvarchar(25),
	@HazardousCode nvarchar(25),
	@TotalWeight numeric(28,5),
	@StatusFlowName nvarchar(25),
	@ExpectedInvSts nvarchar(50),
	@ShipFrom nvarchar(25),
	@ConversionQty numeric(19,5),
	@ConversionUm nvarchar(25),
	@Priority numeric(3),
	@CustomerOrderNum nvarchar(25),
	@ReceiptDate datetime,
	@ConversionHeight numeric(19,5),
	@ConversionWidth numeric(19,5),
	@ConversionLength numeric(19,5),
	@ConversionWeight numeric(19,5),
	@OriginalTotalQuantity numeric(28,5),
	@InterfaceRecordId nvarchar(25),
	@ItemCategory1 nvarchar(50),
	@ItemCategory2 nvarchar(50),
	@ItemCategory3 nvarchar(50),
	@ItemCategory4 nvarchar(50),
	@ItemCategory5 nvarchar(50),
	@ItemCategory6 nvarchar(50),
	@ItemCategory7 nvarchar(50),
	@ItemCategory8 nvarchar(50),
	@ItemCategory9 nvarchar(50),
	@ItemCategory10 nvarchar(50),
	@InventorySts nvarchar(50),
	@PurchaseOrderDetailId numeric(9),
	@PurchaseOrderId nvarchar(25),
	@PurchaseOrderLineNumber numeric(19,5)
AS
	UPDATE RECEIPT_DETAIL
	   SET
		LOCATING_RULE=@LocatingRule,
		warehouse=@Warehouse,
		INTERNAL_RECEIPT_NUM=@InternalReceiptNum,
		RECEIPT_ID=@ReceiptId,
		ITEM=@Item,
		ITEM_DESC=@ItemDesc,
		ITEM_CLASS=@ItemClass,
		LOT=@Lot,
		COMPANY=@Company,
		TOTAL_QTY=@TotalQty,
		QUANTITY_UM=@QuantityUm,
		OPEN_QTY=@OpenQty,
		ERP_ORDER_NUM=@ErpOrderNum,
		ERP_ORDER_TYPE=@ErpOrderType,
		ERP_ORDER_LINE_NUM=@ErpOrderLineNum,
		EXPIRATION_DATE_TIME=@ExpirationDateTime,
		MANUFACTURED_DATE_TIME=@ManufacturedDateTime,
		ITEM_WEIGHT=@ItemWeight,
		WEIGHT_UM=@WeightUm,
		ITEM_LENGTH=@ItemLength,
		ITEM_WIDTH=@ItemWidth,
		ITEM_HEIGHT=@ItemHeight,
		ITEM_DIMENSION_UM=@ItemDimensionUm,
		VOLUME_UM=@VolumeUm,
		ITEM_DIVISION=@ItemDivision,
		ITEM_DEPARTMENT=@ItemDepartment,
		VALUE=@Value,
		ITEM_SIZE=@ItemSize,
		ITEM_COLOR=@ItemColor,
		ITEM_STYLE=@ItemStyle,
		LAUNCH_NUM=@LaunchNum,
		PUT_LOC=@PutLoc,
		USER_DEF1=@UserDef1,
		USER_DEF2=@UserDef2,
		USER_DEF3=@UserDef3,
		USER_DEF4=@UserDef4,
		USER_DEF5=@UserDef5,
		USER_DEF6=@UserDef6,
		USER_DEF7=@UserDef7,
		USER_DEF8=@UserDef8,
		USER_STAMP=@UserStamp,
		PROCESS_STAMP=@ProcessStamp,
		DATE_TIME_STAMP=@DateTimeStamp,
		PUT_ZONE=@PutZone,
		ITEM_LIST_PRICE=@ItemListPrice,
		ITEM_NET_PRICE=@ItemNetPrice,
		PUT_LIST_NUM=@PutListNum,
		MANUALLY_ENTERED=@ManuallyEntered,
		LOT_CONTROLLED=@LotControlled,
		SERIAL_NUM_REQD=@SerialNumReqd,
		CATCH_WEIGHT_REQD=@CatchWeightReqd,
		SOURCE_ID=@SourceId,
		HAZARDOUS_CODE=@HazardousCode,
		TOTAL_WEIGHT=@TotalWeight,
		STATUS_FLOW_NAME=@StatusFlowName,
		EXPECTED_INV_STS=@ExpectedInvSts,
		SHIP_FROM=@ShipFrom,
		CONVERSION_QTY=@ConversionQty,
		CONVERSION_UM=@ConversionUm,
		PRIORITY=@Priority,
		CUSTOMER_ORDER_NUM=@CustomerOrderNum,
		RECEIPT_DATE=@ReceiptDate,
		CONVERSION_HEIGHT=@ConversionHeight,
		CONVERSION_WIDTH=@ConversionWidth,
		CONVERSION_LENGTH=@ConversionLength,
		CONVERSION_WEIGHT=@ConversionWeight,
		ORIGINAL_TOTAL_QUANTITY=@OriginalTotalQuantity,
		INTERFACE_RECORD_ID=@InterfaceRecordId,
		ITEM_CATEGORY1=@ItemCategory1,
		ITEM_CATEGORY2=@ItemCategory2,
		ITEM_CATEGORY3=@ItemCategory3,
		ITEM_CATEGORY4=@ItemCategory4,
		ITEM_CATEGORY5=@ItemCategory5,
		ITEM_CATEGORY6=@ItemCategory6,
		ITEM_CATEGORY7=@ItemCategory7,
		ITEM_CATEGORY8=@ItemCategory8,
		ITEM_CATEGORY9=@ItemCategory9,
		ITEM_CATEGORY10=@ItemCategory10,
		INVENTORY_STS=@InventorySts,
		PURCHASE_ORDER_DETAIL_ID = @PurchaseOrderDetailId, 
		PURCHASE_ORDER_ID = @PurchaseOrderId, 
		PURCHASE_ORDER_LINE_NUMBER = @PurchaseOrderLineNumber
	 WHERE INTERNAL_RECEIPT_LINE_NUM = @InternalReceiptLineNum

	SET @RowsAffected = @@ROWCOUNT




