-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */






CREATE VIEW REPLENISHMENT_REQUEST_VIEW  
AS  
SELECT RR.* ,   
  
(SELECT costPerItem FROM  dbo.INVfn_RtrvItemInfo(RR.ITEM, case when RR.COMPANY IS NULL Then N'<literal:1>' ELSE RR.COMPANY END, RR.QUANTITY_UM,null, RR.FROM_WHS,null)) * RR.ALLOCATED_QTY as TotalCost,  
(SELECT volumePerItem FROM  dbo.INVfn_RtrvItemInfo(RR.ITEM, case when RR.COMPANY IS NULL Then N'<literal:2>' ELSE RR.COMPANY END, RR.QUANTITY_UM,null, RR.FROM_WHS,null)) * RR.ALLOCATED_QTY as TotalVolume,  
(SELECT weightPerItem FROM  dbo.INVfn_RtrvItemInfo(RR.ITEM, case when RR.COMPANY IS NULL Then N'<literal:3>' ELSE RR.COMPANY END, RR.QUANTITY_UM,null, RR.FROM_WHS,null)) * RR.ALLOCATED_QTY as TotalWeight,  
  
LI1.ON_HAND_QTY AS FromOnHandQty,   
LI1.IN_TRANSIT_QTY AS FromIntransitQty,   
LI1.SUSPENSE_QTY AS FromSuspenseQty,  
LI1.ALLOCATED_QTY AS FromAllocatedQty,   
LI1.QUANTITY_UM AS FromQuantityUm,   
dbo.INVfn_GetAvailableQuantity(FROM_LOC,FROM_WHS, RR.ITEM, RR.COMPANY , RR.LOT, RR.FROM_LOGISTICS_UNIT, null, N'<literal:4>', N'<literal:5>',null, null ) As FromAvailableQty,  
  
LI2.ON_HAND_QTY AS ToOnHandQty,   
LI2.IN_TRANSIT_QTY AS ToIntransitQty,   
LI2.SUSPENSE_QTY AS ToSuspenseQty,  
LI2.ALLOCATED_QTY AS ToAllocatedQty,   
LI2.QUANTITY_UM AS ToQuantityUm,   
dbo.INVfn_GetAvailableQuantity(TO_LOC,TO_WHS, RR.ITEM, RR.COMPANY , RR.LOT , RR.TO_LOGISTICS_UNIT, null, N'<literal:6>', N'<literal:7>',null, null ) As ToAvailableQty  
  
from REPLENISHMENT_REQUEST RR   
left outer JOIN LOCATION_INVENTORY LI1  
ON RR.ITEM = LI1.ITEM AND RR.FROM_LOC = LI1.LOCATION AND (RR.COMPANY = LI1.COMPANY OR( RR.COMPANY IS NULL AND  LI1.COMPANY IS NULL)) AND RR.FROM_WHS = LI1.WAREHOUSE AND   
(RR.LOT = LI1.LOT OR RR.LOT IS NULL AND LI1.LOT is null) AND (RR.FROM_LOGISTICS_UNIT = LI1.LOGISTICS_UNIT OR (RR.FROM_LOGISTICS_UNIT IS NULL AND LI1.LOGISTICS_UNIT IS NULL))  
left outer JOIN LOCATION_INVENTORY LI2  
ON RR.ITEM = LI2.ITEM AND RR.TO_LOC = LI2.LOCATION AND (RR.COMPANY = LI2.COMPANY OR( RR.COMPANY IS NULL AND  LI2.COMPANY IS NULL)) AND RR.TO_WHS = LI2.WAREHOUSE AND  
(RR.LOT = LI2.LOT OR RR.LOT IS NULL AND LI2.LOT is null) AND (RR.TO_LOGISTICS_UNIT = LI2.LOGISTICS_UNIT OR (RR.TO_LOGISTICS_UNIT IS NULL AND LI2.LOGISTICS_UNIT IS NULL));