-- DOCUMENTATION ONLY: literals/comments removed; do not execute.

CREATE PROCEDURE wm_UReceiptHeader01
	@RowsAffected int OUTPUT,
	@InternalReceiptNum numeric(9),
	@Warehouse nvarchar(25),
	@Company nvarchar(25),
	@ReceiptId nvarchar(25),
	@ReceiptIdType nvarchar(25),
	@ReceiptType nvarchar(25),
	@ReceiptDate datetime,
	@CloseDate datetime,
	@SourceId nvarchar(25),
	@SourceName nvarchar(50),
	@SourceAddress1 nvarchar(50),
	@SourceAddress2 nvarchar(50),
	@SourceAddress3 nvarchar(50),
	@SourceCity nvarchar(30),
	@SourceState nvarchar(25),
	@SourcePostalCode nvarchar(25),
	@SourceCountry nvarchar(25),
	@SourceAttentionTo nvarchar(50),
	@SourcePhoneNum nvarchar(50),
	@SourceFaxNum nvarchar(50),
	@SourceEmailAddress nvarchar(50),
	@Priority numeric(3),
	@Carrier nvarchar(25),
	@CarrierService nvarchar(50),
	@ErpOrderNum nvarchar(25),
	@ErpOrderType nvarchar(25),
	@BolNumAlpha nvarchar(25),
	@LicensePlateId nvarchar(25),
	@PackingListId nvarchar(25),
	@ProNumAlpha nvarchar(25),
	@TrailerId nvarchar(25),
	@SealId nvarchar(25),
	@TotalContainers numeric(9),
	@TotalLines numeric(9),
	@TotalQty numeric(28,5),
	@QuantityUm nvarchar(25),
	@TotalWeight numeric(28,5),
	@WeightUm nvarchar(25),
	@TotalVolume numeric(28,5),
	@VolumeUm nvarchar(25),
	@TotalValue numeric(28,5),
	@LeadingSts numeric(3),
	@LeadingStsDate datetime,
	@LeadingStsFailed nchar(1),
	@TrailingSts numeric(3),
	@TrailingStsDate datetime,
	@TrailingStsFailed nchar(1),
	@UserDef1 nvarchar(25),
	@UserDef2 nvarchar(25),
	@UserDef3 nvarchar(25),
	@UserDef4 nvarchar(25),
	@UserDef5 nvarchar(25),
	@UserDef6 nvarchar(25),
	@UserDef7 numeric(19,5),
	@UserDef8 numeric(19,5),
	@UserStamp nvarchar(30),
	@ProcessStamp nvarchar(100),
	@DateTimeStamp datetime,
	@ManuallyEntered nchar(1),
	@ShipFrom nvarchar(25),
	@ShipFromAddress1 nvarchar(50),
	@ShipFromAddress2 nvarchar(50),
	@ShipFromAddress3 nvarchar(50),
	@ShipFromCity nvarchar(30),
	@ShipFromState nvarchar(25),
	@ShipFromCountry nvarchar(25),
	@ShipFromPostalCode nvarchar(25),
	@ShipFromName nvarchar(50),
	@ShipFromAttentionTo nvarchar(50),
	@ShipFromEmailAddress nvarchar(50),
	@ShipFromPhoneNum nvarchar(50),
	@ShipFromFaxNum nvarchar(50),
	@ScheduledDateTime datetime,
	@ArrivedDateTime datetime,
	@StartUnitizeDateTime datetime,
	@EndUnitizeDateTime datetime,
	@InterfaceRecordId nvarchar(25),
	@CreationProcessStamp nvarchar(100),
	@CreationDateTimeStamp datetime
AS
	UPDATE RECEIPT_HEADER
	   SET
		warehouse=@Warehouse,
		COMPANY=@Company,
		RECEIPT_ID=@ReceiptId,
		RECEIPT_ID_TYPE=@ReceiptIdType,
		RECEIPT_TYPE=@ReceiptType,
		RECEIPT_DATE=@ReceiptDate,
		CLOSE_DATE=@CloseDate,
		SOURCE_ID=@SourceId,
		SOURCE_NAME=@SourceName,
		SOURCE_ADDRESS1=@SourceAddress1,
		SOURCE_ADDRESS2=@SourceAddress2,
		SOURCE_ADDRESS3=@SourceAddress3,
		SOURCE_CITY=@SourceCity,
		SOURCE_STATE=@SourceState,
		SOURCE_POSTAL_CODE=@SourcePostalCode,
		SOURCE_COUNTRY=@SourceCountry,
		SOURCE_ATTENTION_TO=@SourceAttentionTo,
		SOURCE_PHONE_NUM=@SourcePhoneNum,
		SOURCE_FAX_NUM=@SourceFaxNum,
		SOURCE_EMAIL_ADDRESS=@SourceEmailAddress,
		PRIORITY=@Priority,
		CARRIER=@Carrier,
		CARRIER_SERVICE=@CarrierService,
		ERP_ORDER_NUM=@ErpOrderNum,
		ERP_ORDER_TYPE=@ErpOrderType,
		BOL_NUM_ALPHA=@BolNumAlpha,
		LICENSE_PLATE_ID=@LicensePlateId,
		PACKING_LIST_ID=@PackingListId,
		PRO_NUM_ALPHA=@ProNumAlpha,
		TRAILER_ID=@TrailerId,
		SEAL_ID=@SealId,
		TOTAL_CONTAINERS=@TotalContainers,
		TOTAL_LINES=@TotalLines,
		TOTAL_QTY=@TotalQty,
		QUANTITY_UM=@QuantityUm,
		TOTAL_WEIGHT=@TotalWeight,
		WEIGHT_UM=@WeightUm,
		TOTAL_VOLUME=@TotalVolume,
		VOLUME_UM=@VolumeUm,
		TOTAL_VALUE=@TotalValue,
		LEADING_STS=@LeadingSts,
		LEADING_STS_DATE=@LeadingStsDate,
		LEADING_STS_FAILED=@LeadingStsFailed,
		TRAILING_STS=@TrailingSts,
		TRAILING_STS_DATE=@TrailingStsDate,
		TRAILING_STS_FAILED=@TrailingStsFailed,
		USER_DEF1=@UserDef1,
		USER_DEF2=@UserDef2,
		USER_DEF3=@UserDef3,
		USER_DEF4=@UserDef4,
		USER_DEF5=@UserDef5,
		USER_DEF6=@UserDef6,
		USER_DEF7=@UserDef7,
		USER_DEF8=@UserDef8,
		USER_STAMP=@UserStamp,
		PROCESS_STAMP=@ProcessStamp,
		DATE_TIME_STAMP=@DateTimeStamp,
		MANUALLY_ENTERED=@ManuallyEntered,
		SHIP_FROM=@ShipFrom,
		SHIP_FROM_ADDRESS1=@ShipFromAddress1,
		SHIP_FROM_ADDRESS2=@ShipFromAddress2,
		SHIP_FROM_ADDRESS3=@ShipFromAddress3,
		SHIP_FROM_CITY=@ShipFromCity,
		SHIP_FROM_STATE=@ShipFromState,
		SHIP_FROM_COUNTRY=@ShipFromCountry,
		SHIP_FROM_POSTAL_CODE=@ShipFromPostalCode,
		SHIP_FROM_NAME=@ShipFromName,
		SHIP_FROM_ATTENTION_TO=@ShipFromAttentionTo,
		SHIP_FROM_EMAIL_ADDRESS=@ShipFromEmailAddress,
		SHIP_FROM_PHONE_NUM=@ShipFromPhoneNum,
		SHIP_FROM_FAX_NUM=@ShipFromFaxNum,
		SCHEDULED_DATE_TIME=@ScheduledDateTime,
		ARRIVED_DATE_TIME=@ArrivedDateTime,
		START_UNITIZE_DATE_TIME=@StartUnitizeDateTime,
		END_UNITIZE_DATE_TIME=@EndUnitizeDateTime,
		INTERFACE_RECORD_ID=@InterfaceRecordId,
		CREATION_PROCESS_STAMP=@CreationProcessStamp,
		CREATION_DATE_TIME_STAMP=@CreationDateTimeStamp
	 WHERE INTERNAL_RECEIPT_NUM = @InternalReceiptNum

	SET @RowsAffected = @@ROWCOUNT



