-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */





CREATE PROCEDURE wm_UShipmentDetail01
	@RowsAffected int OUTPUT,
	@InternalShipmentLineNum numeric(9),
	@InternalShipmentNum numeric(9),
	@AllocationRule nvarchar(25),
	@StatusFlowName nvarchar(25),
	@ErpOrder nvarchar(25),
	@Status1 numeric(3),
	@ErpOrderLineNum numeric(19,5),
	@Warehouse nvarchar(25),
	@InternalOrderNum numeric(9),
	@Status2 numeric(3),
	@ShipTo nvarchar(25),
	@Status3 numeric(3),
	@LaunchNum numeric(9),
	@Status4 numeric(3),
	@StatusFailed nchar(1),
	@Status5 numeric(3),
	@Status6 numeric(3),
	@Status7 numeric(3),
	@OrderType nvarchar(25),
	@Status8 numeric(3),
	@Customer nvarchar(25),
	@Item nvarchar(50),
	@Status9 numeric(3),
	@Status10 numeric(3),
	@MarkFor nvarchar(25),
	@ItemDesc nvarchar(100),
	@CustomerItem nvarchar(50),
	@Carrier nvarchar(25),
	@CarrierService nvarchar(50),
	@FreightTerms nvarchar(50),
	@LiabilityTerms nvarchar(25),
	@OrderDate datetime,
	@ShipmentId nvarchar(25),
	@Company nvarchar(25),
	@InterfacedDate datetime,
	@RequestedQty numeric(28,5),
	@QuantityUm nvarchar(25),
	@PickLoc nvarchar(25),
	@CarrierType nvarchar(25),
	@PickZone nvarchar(25),
	@SecondaryPickLoc nvarchar(25),
	@WeightUm nvarchar(25),
	@SecondaryPickZone nvarchar(25),
	@PlannedShipDate datetime,
	@ItemLength numeric(19,5),
	@ItemWidth numeric(19,5),
	@RequestedDeliveryDate datetime,
	@RequestedDeliveryType nvarchar(10),
	@ItemHeight numeric(19,5),
	@ItemDimensionUm nvarchar(25),
	@ItemDepartment nvarchar(25),
	@ItemListPrice numeric(19,5),
	@ItemNetPrice numeric(19,5),
	@ItemColor nvarchar(25),
	@ItemStyle nvarchar(25),
	@ItemSize nvarchar(25),
	@OriginalItemOrdered nvarchar(50),
	@PickListId nvarchar(25),
	@CustomerPo nvarchar(25),
	@Invoice nvarchar(25),
	@ItemVolume numeric(19,5),
	@PackingCategory nvarchar(25),
	@TotalVolume numeric(28,5),
	@HazardousCode nvarchar(25),
	@ItemDivision nvarchar(25),
	@NmfcCode nvarchar(25),
	@TotalWeight numeric(28,5),
	@CatalogId nvarchar(25),
	@ManufactureId nvarchar(25),
	@TotalQty numeric(28,5),
	@Value numeric(28,5),
	@MerchandiseCode nvarchar(25),
	@ValueAddLabelCode nvarchar(25),
	@VolumeUm nvarchar(25),
	@UserDef1 nvarchar(25),
	@UserDef2 nvarchar(25),
	@UserDef3 nvarchar(25),
	@ManuallyEntered nchar(1),
	@UserDef4 nvarchar(25),
	@UserDef5 nvarchar(25),
	@UserDef6 nvarchar(25),
	@UserDef7 numeric(19,5),
	@UserDef8 numeric(19,5),
	@UserStamp nvarchar(30),
	@ProcessStamp nvarchar(100),
	@QuantityAtSts1 numeric(19,5),
	@LotControlled nchar(1),
	@DateTimeStamp datetime,
	@SerialNumReqd nchar(1),
	@QuantityAtSts2 numeric(19,5),
	@CatchWeightReqd nchar(1),
	@QuantityAtSts3 numeric(19,5),
	@QuantityAtSts4 numeric(19,5),
	@QuantityAtSts5 numeric(19,5),
	@QuantityAtSts6 numeric(19,5),
	@QuantityAtSts7 numeric(19,5),
	@QuantityAtSts8 numeric(19,5),
	@QuantityAtSts9 numeric(19,5),
	@Priority numeric(3),
	@ItemWeight numeric(19,5),
	@QuantityAtSts10 numeric(19,5),
	@Lot nvarchar(25),
	@ItemClass nvarchar(50),
	@MarkForName nvarchar(50),
	@MarkForAddress1 nvarchar(50),
	@MarkForAddress2 nvarchar(50),
	@MarkForAddress3 nvarchar(50),
	@MarkForAttentionTo nvarchar(50),
	@MarkForCity nvarchar(30),
	@MarkForState nvarchar(25),
	@MarkForCountry nvarchar(25),
	@MarkForPostalCode nvarchar(25),
	@MarkForPhoneNum nvarchar(50),
	@MarkForFaxNum nvarchar(25),
	@MarkForEmailAddress nvarchar(50),
	@HarmonizedCode nvarchar(25),
	@HarmonizedDesc nvarchar(500),
	@ExportDesc nvarchar(500),
	@PreferenceCrit nchar(1),
	@Producer nchar(1),
	@NetCost nchar(1),
	@CountryOfOrigin nvarchar(25),
	@PackingClass nvarchar(25),
	@InterfaceRecordId nvarchar(25),
	@ItemCategory1 nvarchar(50),
	@ItemCategory2 nvarchar(50),
	@ItemCategory3 nvarchar(50),
	@ItemCategory4 nvarchar(50),
	@ItemCategory5 nvarchar(50),
	@ItemCategory6 nvarchar(50),
	@ItemCategory7 nvarchar(50),
	@ItemCategory8 nvarchar(50),
	@ItemCategory9 nvarchar(50),
	@ItemCategory10 nvarchar(50),
	@ContCreationFullQty numeric(19,5),
	@ContCreationFullQtyUm nvarchar(25),
	@ContCreationInnerpackQty numeric(19,5),
	@AllocateFullLocQty nchar(1),
	@AllowPctAlloc nchar(1),
	@MinimumAllocPct numeric(4),
	@MaximumAllocPct numeric(4),
	@ImmediateNeedsNote nvarchar(50),
	@TreatAsLoose nchar(1),
	@BomAction nchar(1),
	@RelatedInternalLineNum numeric(9),
	@QuantityNeededPerItem numeric(19,5),
	@ImmediateNeedsEligible nchar(1),
	@ImmediateNeedsLocRule nvarchar(25),
	@StoreDistribution nvarchar(25),
	@Eccn nvarchar(50),
	@ValidatedLicense nvarchar(50),
	@LicenseExpDate datetime
AS

		DECLARE @stEccn nvarchar(50),@stVLicense nvarchar(50),@stLExpDate datetime

		Select @stEccn = ECCN, @stVLicense = VALIDATED_LICENSE,@stLExpDate = LICENSE_EXP_DATE From SHIPMENT_HEADER WHERE SHIPMENT_ID = @ShipmentId

		if(@Eccn is null)
		Set @Eccn = @stEccn
		if(@ValidatedLicense is null )
		set @ValidatedLicense = @stVLicense
			if (@LicenseExpDate is null)
			set @LicenseExpDate = @stLExpDate

	UPDATE SHIPMENT_DETAIL
	   SET
		INTERNAL_SHIPMENT_NUM=@InternalShipmentNum,
		ALLOCATION_RULE=@AllocationRule,
		STATUS_FLOW_NAME=@StatusFlowName,
		ERP_ORDER=@ErpOrder,
		STATUS1=@Status1,
		ERP_ORDER_LINE_NUM=@ErpOrderLineNum,
		warehouse=@Warehouse,
		INTERNAL_ORDER_NUM=@InternalOrderNum,
		STATUS2=@Status2,
		SHIP_TO=@ShipTo,
		STATUS3=@Status3,
		LAUNCH_NUM=@LaunchNum,
		STATUS4=@Status4,
		STATUS_FAILED=@StatusFailed,
		STATUS5=@Status5,
		STATUS6=@Status6,
		STATUS7=@Status7,
		ORDER_TYPE=@OrderType,
		STATUS8=@Status8,
		CUSTOMER=@Customer,
		ITEM=@Item,
		STATUS9=@Status9,
		STATUS10=@Status10,
		MARK_FOR=@MarkFor,
		ITEM_DESC=@ItemDesc,
		CUSTOMER_ITEM=@CustomerItem,
		CARRIER=@Carrier,
		CARRIER_SERVICE=@CarrierService,
		FREIGHT_TERMS=@FreightTerms,
		LIABILITY_TERMS=@LiabilityTerms,
		ORDER_DATE=@OrderDate,
		SHIPMENT_ID=@ShipmentId,
		COMPANY=@Company,
		INTERFACED_DATE=@InterfacedDate,
		REQUESTED_QTY=@RequestedQty,
		QUANTITY_UM=@QuantityUm,
		PICK_LOC=@PickLoc,
		CARRIER_TYPE=@CarrierType,
		PICK_ZONE=@PickZone,
		SECONDARY_PICK_LOC=@SecondaryPickLoc,
		WEIGHT_UM=@WeightUm,
		SECONDARY_PICK_ZONE=@SecondaryPickZone,
		PLANNED_SHIP_DATE=@PlannedShipDate,
		ITEM_LENGTH=@ItemLength,
		ITEM_WIDTH=@ItemWidth,
		REQUESTED_DELIVERY_DATE=@RequestedDeliveryDate,
		REQUESTED_DELIVERY_TYPE=@RequestedDeliveryType,
		ITEM_HEIGHT=@ItemHeight,
		ITEM_DIMENSION_UM=@ItemDimensionUm,
		ITEM_DEPARTMENT=@ItemDepartment,
		ITEM_LIST_PRICE=@ItemListPrice,
		ITEM_NET_PRICE=@ItemNetPrice,
		ITEM_COLOR=@ItemColor,
		ITEM_STYLE=@ItemStyle,
		ITEM_SIZE=@ItemSize,
		ORIGINAL_ITEM_ORDERED=@OriginalItemOrdered,
		PICK_LIST_ID=@PickListId,
		CUSTOMER_PO=@CustomerPo,
		INVOICE=@Invoice,
		ITEM_VOLUME=@ItemVolume,
		PACKING_CATEGORY=@PackingCategory,
		TOTAL_VOLUME=@TotalVolume,
		HAZARDOUS_CODE=@HazardousCode,
		ITEM_DIVISION=@ItemDivision,
		NMFC_CODE=@NmfcCode,
		TOTAL_WEIGHT=@TotalWeight,
		CATALOG_ID=@CatalogId,
		MANUFACTURE_ID=@ManufactureId,
		TOTAL_QTY=@TotalQty,
		VALUE=@Value,
		MERCHANDISE_CODE=@MerchandiseCode,
		VALUE_ADD_LABEL_CODE=@ValueAddLabelCode,
		VOLUME_UM=@VolumeUm,
		USER_DEF1=@UserDef1,
		USER_DEF2=@UserDef2,
		USER_DEF3=@UserDef3,
		MANUALLY_ENTERED=@ManuallyEntered,
		USER_DEF4=@UserDef4,
		USER_DEF5=@UserDef5,
		USER_DEF6=@UserDef6,
		USER_DEF7=@UserDef7,
		USER_DEF8=@UserDef8,
		USER_STAMP=@UserStamp,
		PROCESS_STAMP=@ProcessStamp,
		QUANTITY_AT_STS1=@QuantityAtSts1,
		LOT_CONTROLLED=@LotControlled,
		DATE_TIME_STAMP=@DateTimeStamp,
		SERIAL_NUM_REQD=@SerialNumReqd,
		QUANTITY_AT_STS2=@QuantityAtSts2,
		CATCH_WEIGHT_REQD=@CatchWeightReqd,
		QUANTITY_AT_STS3=@QuantityAtSts3,
		QUANTITY_AT_STS4=@QuantityAtSts4,
		QUANTITY_AT_STS5=@QuantityAtSts5,
		QUANTITY_AT_STS6=@QuantityAtSts6,
		QUANTITY_AT_STS7=@QuantityAtSts7,
		QUANTITY_AT_STS8=@QuantityAtSts8,
		QUANTITY_AT_STS9=@QuantityAtSts9,
		PRIORITY=@Priority,
		ITEM_WEIGHT=@ItemWeight,
		QUANTITY_AT_STS10=@QuantityAtSts10,
		LOT=@Lot,
		ITEM_CLASS=@ItemClass,
		MARK_FOR_NAME=@MarkForName,
		MARK_FOR_ADDRESS1=@MarkForAddress1,
		MARK_FOR_ADDRESS2=@MarkForAddress2,
		MARK_FOR_ADDRESS3=@MarkForAddress3,
		MARK_FOR_ATTENTION_TO=@MarkForAttentionTo,
		MARK_FOR_CITY=@MarkForCity,
		MARK_FOR_STATE=@MarkForState,
		MARK_FOR_COUNTRY=@MarkForCountry,
		MARK_FOR_POSTAL_CODE=@MarkForPostalCode,
		MARK_FOR_PHONE_NUM=@MarkForPhoneNum,
		MARK_FOR_FAX_NUM=@MarkForFaxNum,
		MARK_FOR_EMAIL_ADDRESS=@MarkForEmailAddress,
		HARMONIZED_CODE=@HarmonizedCode,
		HARMONIZED_DESC=@HarmonizedDesc,
		EXPORT_DESC=@ExportDesc,
		PREFERENCE_CRIT=@PreferenceCrit,
		PRODUCER=@Producer,
		NET_COST=@NetCost,
		COUNTRY_OF_ORIGIN=@CountryOfOrigin,
		PACKING_CLASS=@PackingClass,
		INTERFACE_RECORD_ID=@InterfaceRecordId,
		ITEM_CATEGORY1=@ItemCategory1,
		ITEM_CATEGORY2=@ItemCategory2,
		ITEM_CATEGORY3=@ItemCategory3,
		ITEM_CATEGORY4=@ItemCategory4,
		ITEM_CATEGORY5=@ItemCategory5,
		ITEM_CATEGORY6=@ItemCategory6,
		ITEM_CATEGORY7=@ItemCategory7,
		ITEM_CATEGORY8=@ItemCategory8,
		ITEM_CATEGORY9=@ItemCategory9,
		ITEM_CATEGORY10=@ItemCategory10,
		CONT_CREATION_FULL_QTY=@ContCreationFullQty,
		CONT_CREATION_FULL_QTY_UM=@ContCreationFullQtyUm,
		CONT_CREATION_INNERPACK_QTY=@ContCreationInnerpackQty,
		ALLOCATE_FULL_LOC_QTY=@AllocateFullLocQty,
		ALLOW_PCT_ALLOC=@AllowPctAlloc,
		MINIMUM_ALLOC_PCT=@MinimumAllocPct,
		MAXIMUM_ALLOC_PCT=@MaximumAllocPct,
		IMMEDIATE_NEEDS_NOTE=@ImmediateNeedsNote,
		TREAT_AS_LOOSE=@TreatAsLoose,
		BOM_ACTION=@BomAction,
		RELATED_INTERNAL_LINE_NUM=@RelatedInternalLineNum,
		QUANTITY_NEEDED_PER_ITEM=@QuantityNeededPerItem,
		IMMEDIATE_NEEDS_ELIGIBLE=@ImmediateNeedsEligible,
		IMMEDIATE_NEEDS_LOC_RULE=@ImmediateNeedsLocRule,
		STORE_DISTRIBUTION=@StoreDistribution,
		ECCN=@Eccn,
		LICENSE_EXP_DATE=@LicenseExpDate,
		VALIDATED_LICENSE=@ValidatedLicense
	 WHERE INTERNAL_SHIPMENT_LINE_NUM = @InternalShipmentLineNum

	SET @RowsAffected = @@ROWCOUNT


