-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */









CREATE PROCEDURE LBL_WorkInstructionDetail (
	@INTERNAL_INSTRUCTION_NUM numeric(9))
AS
BEGIN

SET NOCOUNT ON;

DECLARE @PARENT_INSTR numeric(9)

SELECT @PARENT_INSTR = PARENT_INSTR
FROM WORK_INSTRUCTION_VIEW WITH (NOLOCK) 
WHERE INTERNAL_INSTRUCTION_NUM = @INTERNAL_INSTRUCTION_NUM

 
SELECT  WORK_UNIT, 
		FROM_LOC,
		ITEM, 
		ITEM_DESC,
		SUM(QUANTITY) QUANTITY, 
		MIN(QUANTITY_UM) QUANTITY_UM from WORK_INSTRUCTION_VIEW
WHERE PARENT_INSTR = ISNULL(@PARENT_INSTR,@INTERNAL_INSTRUCTION_NUM) AND
(@PARENT_INSTR IS NULL  OR INTERNAL_INSTRUCTION_NUM = @INTERNAL_INSTRUCTION_NUM) AND INSTRUCTION_TYPE=N'<literal:1>'
group by WORK_UNIT, FROM_LOC,ITEM,ITEM_DESC

END  