-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */





CREATE PROCEDURE wm_IPurchaseOrderDetail01
	@ObjectId numeric(9) OUTPUT,
	@Company nvarchar(25),
	@DateTimeStamp datetime,
	@Item nvarchar(50),
	@ItemCategory1 nvarchar(50),
	@ItemCategory2 nvarchar(50),
	@ItemCategory3 nvarchar(50),
	@ItemCategory4 nvarchar(50),
	@ItemCategory5 nvarchar(50),
	@ItemCategory6 nvarchar(50),
	@ItemCategory7 nvarchar(50),
	@ItemCategory8 nvarchar(50),
	@ItemCategory9 nvarchar(50),
	@ItemCategory10 nvarchar(50),
	@ItemClass nvarchar(50),
	@ItemColor nvarchar(25),	
	@ItemDesc nvarchar(100),
	@ItemDepartment nvarchar(25),
	@ItemDimensionUm nvarchar(25),
	@ItemDivision nvarchar(25),
	@ItemHeight numeric(19,5),
	@ItemLength numeric(19,5),
	@ItemListPrice numeric(19,5),
	@ItemNetPrice numeric(19,5),
	@ItemSize nvarchar(25),
	@ItemStyle nvarchar(25),
	@ItemWidth numeric(19,5),
	@ItemWeight numeric(19,5),
	@LineNumber numeric(19,5),
	@OpenQuantity numeric(19,5),
	@ProcessStamp nvarchar(100),
	@PurchaseOrderObjectId numeric(9),
	@PurchaseOrderId nvarchar(25),
	@QuantityUm nvarchar(25),
	@TotalQty numeric(19,5),
	@UserDef1 nvarchar(25),
	@UserDef2 nvarchar(25),
	@UserDef3 nvarchar(25),
	@UserDef4 nvarchar(25),
	@UserDef5 nvarchar(25),
	@UserDef6 nvarchar(25),
	@UserDef7 numeric(19,5),
	@UserDef8 numeric(19,5),
	@UserStamp nvarchar(30),
	@WeightUm nvarchar(25)
AS
			
	INSERT INTO PURCHASE_ORDER_DETAIL(
				company,                                                     
				DATE_TIME_STAMP,
				item,         
				item_category1,                                              
				item_category2,                                              
				item_category3,                                              
				item_category4,                                              
				item_category5,                                              
				item_category6,                                              
				item_category7,                                              
				item_category8,                                              
				item_category9,                                              
				item_category10,                                             
				item_class,                                                  
				item_color,                                                  
				item_desc,                                                   
				item_department,                                             
				item_dimension_um,                                           
				item_division,  
				item_height,                                                 
				item_length,                                                 
				item_list_price,                                             
				item_net_price,                                              
				item_size,                                                   
				item_style,                                                  
				item_width,                                                  
				item_weight,                                                 
				LINE_NUMBER,                                                 
				OPEN_QUANTITY,   
				PROCESS_STAMP,   
				PURCHASE_ORDER_OBJECT_ID,                                    
				PURCHASE_ORDER_ID ,    
				quantity_um,                                                 
				total_quantity,                                              
				user_def1,                                                   
				user_def2,                                                   
				user_def3,                                                   
				user_def4,                                                   
				user_def5,                                                   
				user_def6,                                                   
				user_def7,                                                   
				user_def8,                                                   
				USER_STAMP,                                                  
				weight_um                                                      
				)
		VALUES
				(
				@Company,
				@DateTimeStamp,
				@Item,         
				@ItemCategory1,
				@ItemCategory2,
				@ItemCategory3,
				@ItemCategory4,
				@ItemCategory5,
				@ItemCategory6,
				@ItemCategory7,
				@ItemCategory8,
				@ItemCategory9,
				@ItemCategory10,
				@ItemClass, 
				@ItemColor,
				@ItemDesc,
				@ItemDepartment,
				@ItemDimensionUm,
				@ItemDivision,  
				@ItemHeight,     
				@ItemLength,     
				@ItemListPrice,  
				@ItemNetPrice,   
				@ItemSize,       
				@ItemStyle,      
				@ItemWidth,      
				@ItemWeight,     
				@LineNumber,     
				@OpenQuantity,   
				@ProcessStamp,   
				@PurchaseOrderObjectId,
				@PurchaseOrderId,    
				@QuantityUm,
				@TotalQty,
				@UserDef1,
				@UserDef2,
				@UserDef3,
				@UserDef4,
				@UserDef5,
				@UserDef6,
				@UserDef7,
				@UserDef8,
				@UserStamp,
				@WeightUm
				);

	SELECT @objectId = SCOPE_IDENTITY();


