-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */







CREATE PROCEDURE wm_UShippingContainer01
	@RowsAffected int OUTPUT,
	@InternalContainerNum numeric(9),
	@ContainerId nvarchar(25),
	@Warehouse nvarchar(25),
	@ContainerType nvarchar(25),
	@ContainerClass nvarchar(25),
	@Status numeric(3),
	@StatusFailed nchar(1),
	@Parent numeric(9),
	@Weight numeric(19,5),
	@WeightUm nvarchar(25),
	@Volume numeric(19,5),
	@Length numeric(19,5),
	@Width numeric(19,5),
	@Height numeric(19,5),
	@DimensionUm nvarchar(25),
	@VolumeUm nvarchar(25),
	@Value numeric(19,5),
	@InternalShipmentNum numeric(9),
	@InternalShipmentLineNum numeric(9),
	@Company nvarchar(25),
	@Item nvarchar(50),
	@Quantity numeric(19,5),
	@QuantityUm nvarchar(25),
	@NmfcCode nvarchar(25),
	@StatusFlowName nvarchar(25),
	@HazardousCode nvarchar(25),
	@ManifestState nvarchar(25),
	@ManifestCarrServiceSymbol nvarchar(50),
	@ManifestDateTime datetime,
	@TrackingNumber nvarchar(50),
	@TotalFreightCharge numeric(28,5),
	@BaseFreightCharge numeric(19,5),
	@FreightDiscount numeric(19,5),
	@AccessorialCharge numeric(19,5),
	@UserDef1 nvarchar(25),
	@UserDef2 nvarchar(25),
	@UserDef3 nvarchar(25),
	@UserDef4 nvarchar(25),
	@UserDef5 nvarchar(25),
	@UserDef6 nvarchar(25),
	@UserDef7 numeric(19,5),
	@UserDef8 numeric(19,5),
	@UserStamp nvarchar(30),
	@ProcessStamp nvarchar(100),
	@DateTimeStamp datetime,
	@InternalOrderNum numeric(9),
	@ManifestForDate datetime,
	@TreeUnit numeric(9),
	@PlannedDeliveryDateTime datetime,
	@BundleId numeric(25),
	@Msn numeric(25),
	@Location nvarchar(25),
	@GroupPosition numeric(9),
	@LaunchNum numeric(9),
	@ContainerCountNumber numeric(9),
	@ContainerCountTotal numeric(9),
	@GroupNum numeric(9),
	@WorkZone nvarchar(25),
	@InterfaceRecordId nvarchar(25),
	@ParentContainerId nvarchar(25),
	@InternalShipAllocNum numeric(9),
	@WorkCreated nchar(1),
	@Hundredweight nchar(1),
	@ManifestId nvarchar(100),
	@ManifestCloseDateTime datetime,
	@Lot nvarchar(25)
AS
	UPDATE SHIPPING_CONTAINER
	   SET
		CONTAINER_ID=@ContainerId,
		warehouse=@Warehouse,
		CONTAINER_TYPE=@ContainerType,
		CONTAINER_CLASS=@ContainerClass,
		status=@Status,
		STATUS_FAILED=@StatusFailed,
		PARENT=@Parent,
		WEIGHT=@Weight,
		WEIGHT_UM=@WeightUm,
		VOLUME=@Volume,
		LENGTH=@Length,
		WIDTH=@Width,
		HEIGHT=@Height,
		DIMENSION_UM=@DimensionUm,
		VOLUME_UM=@VolumeUm,
		VALUE=@Value,
		INTERNAL_SHIPMENT_NUM=@InternalShipmentNum,
		INTERNAL_SHIPMENT_LINE_NUM=@InternalShipmentLineNum,
		COMPANY=@Company,
		ITEM=@Item,
		QUANTITY=@Quantity,
		QUANTITY_UM=@QuantityUm,
		NMFC_CODE=@NmfcCode,
		STATUS_FLOW_NAME=@StatusFlowName,
		HAZARDOUS_CODE=@HazardousCode,
		MANIFEST_STATE=@ManifestState,
		MANIFEST_CARR_SERVICE_SYMBOL=@ManifestCarrServiceSymbol,
		MANIFEST_DATE_TIME=@ManifestDateTime,
		TRACKING_NUMBER=@TrackingNumber,
		TOTAL_FREIGHT_CHARGE=@TotalFreightCharge,
		BASE_FREIGHT_CHARGE=@BaseFreightCharge,
		FREIGHT_DISCOUNT=@FreightDiscount,
		ACCESSORIAL_CHARGE=@AccessorialCharge,
		USER_DEF1=@UserDef1,
		USER_DEF2=@UserDef2,
		USER_DEF3=@UserDef3,
		USER_DEF4=@UserDef4,
		USER_DEF5=@UserDef5,
		USER_DEF6=@UserDef6,
		USER_DEF7=@UserDef7,
		USER_DEF8=@UserDef8,
		USER_STAMP=@UserStamp,
		PROCESS_STAMP=@ProcessStamp,
		DATE_TIME_STAMP=@DateTimeStamp,
		INTERNAL_ORDER_NUM=@InternalOrderNum,
		MANIFEST_FOR_DATE=@ManifestForDate,
		TREE_UNIT=@TreeUnit,
		PLANNED_DELIVERY_DATE_TIME=@PlannedDeliveryDateTime,
		BUNDLE_ID=@BundleId,
		MSN=@Msn,
		LOCATION=@Location,
		GROUP_POSITION=@GroupPosition,
		LAUNCH_NUM=@LaunchNum,
		CONTAINER_COUNT_NUMBER=@ContainerCountNumber,
		CONTAINER_COUNT_TOTAL=@ContainerCountTotal,
		GROUP_NUM=@GroupNum,
		WORK_ZONE=@WorkZone,
		INTERFACE_RECORD_ID=@InterfaceRecordId,
		PARENT_CONTAINER_ID=@ParentContainerId,
		INTERNAL_SHIP_ALLOC_NUM=@InternalShipAllocNum,
		WORK_CREATED=@WorkCreated,
		HUNDREDWEIGHT=@Hundredweight,
		MANIFEST_ID=@ManifestId,
		MANIFEST_CLOSE_DATE_TIME=@ManifestCloseDateTime,
		LOT=@Lot
	 WHERE INTERNAL_CONTAINER_NUM = @InternalContainerNum

	SET @RowsAffected = @@ROWCOUNT



