-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */





CREATE PROCEDURE wm_IPurchaseOrderHeader01
	@objectId numeric(9) OUTPUT,
	@ClosedDateTime datetime,
	@CreatedDateTime datetime,
	@Company nvarchar(25),
	@DateTimeStamp datetime,	
	@ProcessStamp nvarchar(100),
	@PurchaseOrderId nvarchar(25),
	@ReceiptType nvarchar(25),	
	@ShipFrom nvarchar(25),
	@ShipFromAddress1 nvarchar(50),
	@ShipFromAddress2 nvarchar(50),
	@ShipFromAddress3 nvarchar(50),
	@ShipFromCity nvarchar(30),
	@ShipFromState nvarchar(25),
	@ShipFromCountry nvarchar(25),
	@ShipFromPostalCode nvarchar(25),
	@ShipFromName nvarchar(50),
	@ShipFromAttentionTo nvarchar(50),
	@ShipFromEmailAddress nvarchar(50),
	@ShipFromPhoneNum nvarchar(50),
	@ShipFromFaxNum nvarchar(50),
	@SourceId nvarchar(25),
	@SourceName nvarchar(50),
	@SourceAddress1 nvarchar(50),
	@SourceAddress2 nvarchar(50),
	@SourceAddress3 nvarchar(50),
	@SourceCity nvarchar(50),
	@SourceState nvarchar(25),
	@SourcePostalCode nvarchar(25),
	@SourceCountry nvarchar(25),
	@SourceAttentionTo nvarchar(50),
	@SourcePhoneNum nvarchar(50),
	@SourceFaxNum nvarchar(50),
	@SourceEmailAddress nvarchar(50),
	@Status nvarchar(25),
	@UserDef1 nvarchar(25),
	@UserDef2 nvarchar(25),
	@UserDef3 nvarchar(25),
	@UserDef4 nvarchar(25),
	@UserDef5 nvarchar(25),
	@UserDef6 nvarchar(25),
	@UserDef7 numeric(19,5),
	@UserDef8 numeric(19,5),
	@UserStamp nvarchar(30),
	@Warehouse nvarchar(25)
AS
	
	INSERT INTO PURCHASE_ORDER_HEADER(
				CLOSED_DATE_TIME,                
				CREATED_DATE_TIME,                
				company,                       
				DATE_TIME_STAMP,               
				PROCESS_STAMP,                 
				PURCHASE_ORDER_ID,                
				receipt_type,                  
				ship_from,                     
				ship_from_address1,               
				ship_from_address2,               
				ship_from_address3,               
				ship_from_city,                
				ship_from_state,               
				ship_from_country,                
				ship_from_postal_code,            
				ship_from_name,                
				ship_from_attention_to,           
				ship_from_email_address,          
				ship_from_phone_num,              
				ship_from_fax_num,                
				source_id,                     
				source_name,                   
				source_address1,               
				source_address2,               
				source_address3,               
				source_city,                   
				source_state,                  
				source_postal_code,               
				source_country,                
				source_attention_to,              
				source_phone_num,                
				source_fax_num,                
				source_email_address,             
				STATUS,                        
				user_def1,                     
				user_def2,                     
				user_def3,                     
				user_def4,                     
				user_def5,                     
				user_def6,                     
				user_def7,                     
				user_def8,                     
				USER_STAMP,                    
				warehouse					     
				)
			VALUES(
				@ClosedDateTime,
				@CreatedDateTime,
				@Company,
				@DateTimeStamp,	
				@ProcessStamp,
				@PurchaseOrderId,
				@ReceiptType,	
				@ShipFrom,
				@ShipFromAddress1 ,
				@ShipFromAddress2,
				@ShipFromAddress3,
				@ShipFromCity,
				@ShipFromState ,
				@ShipFromCountry,
				@ShipFromPostalCode,
				@ShipFromName,
				@ShipFromAttentionTo,
				@ShipFromEmailAddress,
				@ShipFromPhoneNum,
				@ShipFromFaxNum,
				@SourceId ,
				@SourceName,
				@SourceAddress1,
				@SourceAddress2,
				@SourceAddress3,
				@SourceCity,
				@SourceState,
				@SourcePostalCode,
				@SourceCountry,
				@SourceAttentionTo,
				@SourcePhoneNum,
				@SourceFaxNum,
				@SourceEmailAddress,
				@Status,
				@UserDef1,
				@UserDef2,
				@UserDef3,
				@UserDef4,
				@UserDef5,
				@UserDef6,
				@UserDef7,
				@UserDef8,
				@UserStamp,
				@Warehouse
			);
	
	SELECT @objectId = SCOPE_IDENTITY();	



