-- DOCUMENTATION ONLY: literals/comments removed; do not execute.


CREATE PROCEDURE wm_IReceiptContainer01
	@InternalRecContNum numeric(9) OUTPUT,
	@LocatingRule nvarchar(25),
	@Company nvarchar(25),
	@InternalReceiptNum numeric(9),
	@InternalReceiptLineNum numeric(9),
	@ReceiptId nvarchar(25),
	@ReceiptIdType nvarchar(25),
	@ContainerId nvarchar(25),
	@ContainerType nvarchar(25),
	@ContainerClass nvarchar(25),
	@Parent numeric(9),
	@Item nvarchar(50),
	@Quantity numeric(28,5),
	@QuantityUm nvarchar(25),
	@Status numeric(3),
	@StatusFailed nchar(1),
	@FromWarehouse nvarchar(25),
	@ToWarehouse nvarchar(25),
	@FromLocation nvarchar(25),
	@ToLocation nvarchar(25),
	@LaunchNum numeric(9),
	@UserDef1 nvarchar(25),
	@UserDef2 nvarchar(25),
	@UserDef3 nvarchar(25),
	@UserDef4 nvarchar(25),
	@UserDef5 nvarchar(25),
	@UserDef6 nvarchar(25),
	@UserDef7 numeric(19,5),
	@UserDef8 numeric(19,5),
	@UserStamp nvarchar(30),
	@ProcessStamp nvarchar(100),
	@DateTimeStamp datetime,
	@StatusFlowName nvarchar(25),
	@Weight numeric(19,5),
	@WeightUm nvarchar(25),
	@Length numeric(19,5),
	@Width numeric(19,5),
	@Height numeric(19,5),
	@DimensionUm nvarchar(25),
	@Lot nvarchar(25),
	@ItemDesc nvarchar(100),
	@ConvertedLocQty numeric(19,5),
	@ConvertedQtyUm nvarchar(25),
	@ItemClass nvarchar(50),
	@ReceiptDate datetime,
	@ExpirationDateTime datetime,
	@ManufacturedDateTime datetime,
	@InternalLocContNum numeric(9),
	@UploadInterfaceBatch nvarchar(50),
	@InterfaceRecordId nvarchar(25),
	@IncomingPdLoc nvarchar(25),
	@OutgoingPdLoc nvarchar(25),
	@UsedByImmedNeed nchar(1),
	@InventorySts nvarchar(50),
	@QcInspection nchar(1),
	@DispositionCode nvarchar(50),
	@ReasonCode nvarchar(50),
	@EPC nvarchar(32),
	@URI nvarchar(100)
AS
	INSERT INTO RECEIPT_CONTAINER(
		COMPANY,
		CONTAINER_CLASS,
		CONTAINER_ID,
		CONTAINER_TYPE,
		CONVERTED_LOC_QTY,
		CONVERTED_QTY_UM,
		DATE_TIME_STAMP,
		DIMENSION_UM,
		DISPOSITION_CODE,
		EPC,
		EXPIRATION_DATE_TIME,
		FROM_LOCATION,
		FROM_WAREHOUSE,
		HEIGHT,
		INCOMING_PD_LOC,
		INTERFACE_RECORD_ID,
		INTERNAL_LOC_CONT_NUM,
		INTERNAL_RECEIPT_LINE_NUM,
		INTERNAL_RECEIPT_NUM,
		INVENTORY_STS,
		ITEM,
		ITEM_CLASS,
		ITEM_DESC,
		LAUNCH_NUM,
		LENGTH,
		LOCATING_RULE,
		LOT,
		MANUFACTURED_DATE_TIME,
		OUTGOING_PD_LOC,
		PARENT,
		PROCESS_STAMP,
		QC_INSPECTION,
		QUANTITY,
		QUANTITY_UM,
		REASON_CODE,
		RECEIPT_DATE,
		RECEIPT_ID,
		RECEIPT_ID_TYPE,
		STATUS,
		STATUS_FAILED,
		STATUS_FLOW_NAME,
		TO_LOCATION,
		TO_WAREHOUSE,
		UPLOAD_INTERFACE_BATCH,
		URI,
		USED_BY_IMMED_NEED,
		USER_DEF1,
		USER_DEF2,
		USER_DEF3,
		USER_DEF4,
		USER_DEF5,
		USER_DEF6,
		USER_DEF7,
		USER_DEF8,
		USER_STAMP,
		WEIGHT,
		WEIGHT_UM,
		WIDTH,
  CREATED_BY  
	) VALUES (
		@Company,
		@ContainerClass,
		@ContainerId,
		@ContainerType,
		@ConvertedLocQty,
		@ConvertedQtyUm,
		@DateTimeStamp,
		@DimensionUm,
		@DispositionCode,
		@EPC,
		@ExpirationDateTime,
		@FromLocation,
		@FromWarehouse,
		@Height,
		@IncomingPdLoc,
		@InterfaceRecordId,
		@InternalLocContNum,
		@InternalReceiptLineNum,
		@InternalReceiptNum,
		@InventorySts,
		@Item,
		@ItemClass,
		@ItemDesc,
		@LaunchNum,
		@Length,
		@LocatingRule,
		@Lot,
		@ManufacturedDateTime,
		@OutgoingPdLoc,
		@Parent,
		@ProcessStamp,
		@QcInspection,
		@Quantity,
		@QuantityUm,
		@ReasonCode,
		@ReceiptDate,
		@ReceiptId,
		@ReceiptIdType,
		@Status,
		@StatusFailed,
		@StatusFlowName,
		@ToLocation,
		@ToWarehouse,
		@UploadInterfaceBatch,
		@URI,
		@UsedByImmedNeed,
		@UserDef1,
		@UserDef2,
		@UserDef3,
		@UserDef4,
		@UserDef5,
		@UserDef6,
		@UserDef7,
		@UserDef8,
		@UserStamp,
		@Weight,
		@WeightUm,
		@Width,
  1  
	)
SELECT @InternalRecContNum = SCOPE_IDENTITY()


