-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
CREATE VIEW dbo.UPLOAD_ORDER_CONTAINER_VIEW
AS
SELECT     CONTAINER_CLASS, CONTAINER_ID, CONTAINER_TYPE, HEIGHT, LENGTH, WIDTH, INTERNAL_SHIPMENT_NUM, ITEM, MANIFEST_FOR_DATE, 
                      QUANTITY, QUANTITY_UM, TRACKING_NUMBER, VALUE, VOLUME, WEIGHT, MULTI_ORDER_PALLET_ID, INTERNAL_SHIPMENT_LINE_NUM, 
                      CONTAINER_COUNT_NUMBER, CONTAINER_COUNT_TOTAL, EPC, MANIFEST_CARR_SERVICE_SYMBOL, INTERNAL_CONTAINER_NUM, 
                      TREE_UNIT
FROM         dbo.UPLOAD_ORDER_CONTAINER
UNION
SELECT     CONTAINER_CLASS, CONTAINER_ID, CONTAINER_TYPE, HEIGHT, LENGTH, WIDTH, INTERNAL_SHIPMENT_NUM, ITEM, MANIFEST_FOR_DATE, 
                      QUANTITY, QUANTITY_UM, TRACKING_NUMBER, VALUE, VOLUME, WEIGHT, MULTI_ORDER_PALLET_ID, INTERNAL_SHIPMENT_LINE_NUM, 
                      CONTAINER_COUNT_NUMBER, CONTAINER_COUNT_TOTAL, EPC, MANIFEST_CARR_SERVICE_SYMBOL, INTERNAL_CONTAINER_NUM, 
                      TREE_UNIT
FROM         dbo.AR_UPLOAD_ORDER_CONTAINER