-- DOCUMENTATION ONLY: literals/comments removed; do not execute.

CREATE PROCEDURE wm_IReceiptHeader01
	@InternalReceiptNum numeric(9) OUTPUT,
	@Warehouse nvarchar(25),
	@Company nvarchar(25),
	@ReceiptId nvarchar(25),
	@ReceiptIdType nvarchar(25),
	@ReceiptType nvarchar(25),
	@ReceiptDate datetime,
	@CloseDate datetime,
	@SourceId nvarchar(25),
	@SourceName nvarchar(50),
	@SourceAddress1 nvarchar(50),
	@SourceAddress2 nvarchar(50),
	@SourceAddress3 nvarchar(50),
	@SourceCity nvarchar(30),
	@SourceState nvarchar(25),
	@SourcePostalCode nvarchar(25),
	@SourceCountry nvarchar(25),
	@SourceAttentionTo nvarchar(50),
	@SourcePhoneNum nvarchar(50),
	@SourceFaxNum nvarchar(50),
	@SourceEmailAddress nvarchar(50),
	@Priority numeric(3),
	@Carrier nvarchar(25),
	@CarrierService nvarchar(50),
	@ErpOrderNum nvarchar(25),
	@ErpOrderType nvarchar(25),
	@BolNumAlpha nvarchar(25),
	@LicensePlateId nvarchar(25),
	@PackingListId nvarchar(25),
	@ProNumAlpha nvarchar(25),
	@TrailerId nvarchar(25),
	@SealId nvarchar(25),
	@TotalContainers numeric(9),
	@TotalLines numeric(9),
	@TotalQty numeric(28,5),
	@QuantityUm nvarchar(25),
	@TotalWeight numeric(28,5),
	@WeightUm nvarchar(25),
	@TotalVolume numeric(28,5),
	@VolumeUm nvarchar(25),
	@TotalValue numeric(28,5),
	@LeadingSts numeric(3),
	@LeadingStsDate datetime,
	@LeadingStsFailed nchar(1),
	@TrailingSts numeric(3),
	@TrailingStsDate datetime,
	@TrailingStsFailed nchar(1),
	@UserDef1 nvarchar(25),
	@UserDef2 nvarchar(25),
	@UserDef3 nvarchar(25),
	@UserDef4 nvarchar(25),
	@UserDef5 nvarchar(25),
	@UserDef6 nvarchar(25),
	@UserDef7 numeric(19,5),
	@UserDef8 numeric(19,5),
	@UserStamp nvarchar(30),
	@ProcessStamp nvarchar(100),
	@DateTimeStamp datetime,
	@ManuallyEntered nchar(1),
	@ShipFrom nvarchar(25),
	@ShipFromAddress1 nvarchar(50),
	@ShipFromAddress2 nvarchar(50),
	@ShipFromAddress3 nvarchar(50),
	@ShipFromCity nvarchar(30),
	@ShipFromState nvarchar(25),
	@ShipFromCountry nvarchar(25),
	@ShipFromPostalCode nvarchar(25),
	@ShipFromName nvarchar(50),
	@ShipFromAttentionTo nvarchar(50),
	@ShipFromEmailAddress nvarchar(50),
	@ShipFromPhoneNum nvarchar(50),
	@ShipFromFaxNum nvarchar(50),
	@ScheduledDateTime datetime,
	@ArrivedDateTime datetime,
	@StartUnitizeDateTime datetime,
	@EndUnitizeDateTime datetime,
	@InterfaceRecordId nvarchar(25),
	@CreationProcessStamp nvarchar(100),
	@CreationDateTimeStamp datetime
AS
	INSERT INTO RECEIPT_HEADER(
		ARRIVED_DATE_TIME,
		BOL_NUM_ALPHA,
		CARRIER,
		CARRIER_SERVICE,
		CLOSE_DATE,
		COMPANY,
		CREATION_DATE_TIME_STAMP,
		CREATION_PROCESS_STAMP,
		DATE_TIME_STAMP,
		END_UNITIZE_DATE_TIME,
		ERP_ORDER_NUM,
		ERP_ORDER_TYPE,
		INTERFACE_RECORD_ID,
		LEADING_STS,
		LEADING_STS_DATE,
		LEADING_STS_FAILED,
		LICENSE_PLATE_ID,
		MANUALLY_ENTERED,
		PACKING_LIST_ID,
		PRIORITY,
		PRO_NUM_ALPHA,
		PROCESS_STAMP,
		QUANTITY_UM,
		RECEIPT_DATE,
		RECEIPT_ID,
		RECEIPT_ID_TYPE,
		RECEIPT_TYPE,
		SCHEDULED_DATE_TIME,
		SEAL_ID,
		SHIP_FROM,
		SHIP_FROM_ADDRESS1,
		SHIP_FROM_ADDRESS2,
		SHIP_FROM_ADDRESS3,
		SHIP_FROM_ATTENTION_TO,
		SHIP_FROM_CITY,
		SHIP_FROM_COUNTRY,
		SHIP_FROM_EMAIL_ADDRESS,
		SHIP_FROM_FAX_NUM,
		SHIP_FROM_NAME,
		SHIP_FROM_PHONE_NUM,
		SHIP_FROM_POSTAL_CODE,
		SHIP_FROM_STATE,
		SOURCE_ADDRESS1,
		SOURCE_ADDRESS2,
		SOURCE_ADDRESS3,
		SOURCE_ATTENTION_TO,
		SOURCE_CITY,
		SOURCE_COUNTRY,
		SOURCE_EMAIL_ADDRESS,
		SOURCE_FAX_NUM,
		SOURCE_ID,
		SOURCE_NAME,
		SOURCE_PHONE_NUM,
		SOURCE_POSTAL_CODE,
		SOURCE_STATE,
		START_UNITIZE_DATE_TIME,
		TOTAL_CONTAINERS,
		TOTAL_LINES,
		TOTAL_QTY,
		TOTAL_VALUE,
		TOTAL_VOLUME,
		TOTAL_WEIGHT,
		TRAILER_ID,
		TRAILING_STS,
		TRAILING_STS_DATE,
		TRAILING_STS_FAILED,
		USER_DEF1,
		USER_DEF2,
		USER_DEF3,
		USER_DEF4,
		USER_DEF5,
		USER_DEF6,
		USER_DEF7,
		USER_DEF8,
		USER_STAMP,
		VOLUME_UM,
		warehouse,
		WEIGHT_UM
	) VALUES (
		@ArrivedDateTime,
		@BolNumAlpha,
		@Carrier,
		@CarrierService,
		@CloseDate,
		@Company,
		@CreationDateTimeStamp,
		@CreationProcessStamp,
		@DateTimeStamp,
		@EndUnitizeDateTime,
		@ErpOrderNum,
		@ErpOrderType,
		@InterfaceRecordId,
		@LeadingSts,
		@LeadingStsDate,
		@LeadingStsFailed,
		@LicensePlateId,
		@ManuallyEntered,
		@PackingListId,
		@Priority,
		@ProNumAlpha,
		@ProcessStamp,
		@QuantityUm,
		@ReceiptDate,
		@ReceiptId,
		@ReceiptIdType,
		@ReceiptType,
		@ScheduledDateTime,
		@SealId,
		@ShipFrom,
		@ShipFromAddress1,
		@ShipFromAddress2,
		@ShipFromAddress3,
		@ShipFromAttentionTo,
		@ShipFromCity,
		@ShipFromCountry,
		@ShipFromEmailAddress,
		@ShipFromFaxNum,
		@ShipFromName,
		@ShipFromPhoneNum,
		@ShipFromPostalCode,
		@ShipFromState,
		@SourceAddress1,
		@SourceAddress2,
		@SourceAddress3,
		@SourceAttentionTo,
		@SourceCity,
		@SourceCountry,
		@SourceEmailAddress,
		@SourceFaxNum,
		@SourceId,
		@SourceName,
		@SourcePhoneNum,
		@SourcePostalCode,
		@SourceState,
		@StartUnitizeDateTime,
		@TotalContainers,
		@TotalLines,
		@TotalQty,
		@TotalValue,
		@TotalVolume,
		@TotalWeight,
		@TrailerId,
		@TrailingSts,
		@TrailingStsDate,
		@TrailingStsFailed,
		@UserDef1,
		@UserDef2,
		@UserDef3,
		@UserDef4,
		@UserDef5,
		@UserDef6,
		@UserDef7,
		@UserDef8,
		@UserStamp,
		@VolumeUm,
		@Warehouse,
		@WeightUm
	)
SELECT @InternalReceiptNum = SCOPE_IDENTITY()



