-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
-- [comment omitted]
-- [comment omitted]
/* [comment omitted] */






-- [comment omitted]
CREATE PROCEDURE GetAccessorialDetails(
@internalNum int,
@internalNumType nvarchar(100),
@headerId int)
AS

-- [comment omitted]
IF(@headerId > 0)
BEGIN
if(UPPER(@internalNumType) = N'<literal:1>')
BEGIN
	SELECT 
		ISNULL((SELECT OBJECT_ID FROM SHIPMENT_ACCESSORIALS WHERE INTERNAL_NUM=@internalNum AND ACCESSORIAL_DETAIL_ID = AD.OBJECT_ID AND SHIPMENT_LEVEL=N'<literal:2>'), 0) as N'<literal:3>',
		AD.OBJECT_ID as N'<literal:4>',
		AD.ACCESSORIAL_CODE,
		AD.ACCESSORIAL_SUB_CODE,
		AD.DESCRIPTION as DetailDesc, 
		AH.DESCRIPTION as HeaderDesc, 
		ISNULL((SELECT VALUE FROM SHIPMENT_ACCESSORIALS WHERE INTERNAL_NUM=@internalNum AND ACCESSORIAL_DETAIL_ID = AD.OBJECT_ID AND SHIPMENT_LEVEL=N'<literal:5>'), AD.VALUE) as N'<literal:6>',
		UPPER(AD.VALUE_TYPE) AS VALUE_TYPE,
		AD.ALLOW_OVERRIDE,
		ISNULL(AD.REQUIRED_FOR_RATING, N'<literal:7>') AS REQUIRED
	FROM 
		SHIPMENT_HEADER SHP
		INNER JOIN
		CARRIER CR ON SHP.CARRIER=CR.CARRIER AND ISNULL(SHP.CARRIER_SERVICE, N'<literal:8>') = ISNULL(CR.SERVICE, N'<literal:9>')
		INNER JOIN
		ACCESSORIAL_HEADER AH ON AH.RATING_ID = CR.RATING_ID AND ISNULL(AH.RATING_SERVICE, N'<literal:10>') = ISNULL(CR.RATING_SERVICE, N'<literal:11>')
		INNER JOIN
		ACCESSORIAL_DETAIL AD ON AH.OBJECT_ID = AD.HEADER_ID
	WHERE AD.VALUE_TYPE NOT IN (N'<literal:12>', N'<literal:13>') AND SHP.INTERNAL_SHIPMENT_NUM=@internalNum AND AH.OBJECT_ID=@headerId;
END
ELSE
BEGIN 
	declare @isContainerContent bit=0;
	select @isContainerContent = 1 FROM SHIPPING_CONTAINER WHERE INTERNAL_CONTAINER_NUM=@internalNum AND CONTAINER_TYPE=N'<literal:14>';
	IF(@isContainerContent = 1)
	BEGIN
		SELECT 
			ISNULL((SELECT OBJECT_ID FROM SHIPMENT_ACCESSORIALS WHERE INTERNAL_NUM=@internalNum AND ACCESSORIAL_DETAIL_ID = AD.OBJECT_ID AND SHIPMENT_LEVEL=N'<literal:15>'), 0) as N'<literal:16>',
			AD.OBJECT_ID as N'<literal:17>',
			AD.ACCESSORIAL_CODE,
			AD.ACCESSORIAL_SUB_CODE,
			AD.DESCRIPTION as DetailDesc, 
			AH.DESCRIPTION as HeaderDesc, 
			ISNULL((SELECT VALUE FROM SHIPMENT_ACCESSORIALS WHERE INTERNAL_NUM=@internalNum AND ACCESSORIAL_DETAIL_ID = AD.OBJECT_ID AND SHIPMENT_LEVEL=N'<literal:18>'), AD.VALUE) as N'<literal:19>',
			UPPER(AD.VALUE_TYPE) AS VALUE_TYPE,
			AD.ALLOW_OVERRIDE,
			ISNULL(AD.REQUIRED_FOR_RATING, N'<literal:20>') AS REQUIRED
		FROM 
			SHIPPING_CONTAINER SC
			INNER JOIN
			SHIPMENT_HEADER SHP ON SC.INTERNAL_SHIPMENT_NUM = SHP.INTERNAL_SHIPMENT_NUM
			INNER JOIN
			CARRIER CR ON SHP.CARRIER=CR.CARRIER AND ISNULL(SHP.CARRIER_SERVICE, N'<literal:21>') = ISNULL(CR.SERVICE, N'<literal:22>')
			INNER JOIN
			ACCESSORIAL_HEADER AH ON AH.RATING_ID = CR.RATING_ID AND ISNULL(AH.RATING_SERVICE, N'<literal:23>') = ISNULL(CR.RATING_SERVICE, N'<literal:24>')
			INNER JOIN
			ACCESSORIAL_DETAIL AD ON AH.OBJECT_ID = AD.HEADER_ID
		WHERE AD.VALUE_TYPE NOT IN (N'<literal:25>', N'<literal:26>') AND SC.INTERNAL_CONTAINER_NUM=@internalNum AND AH.OBJECT_ID=@headerId;
	END
	ELSE
	BEGIN
		SELECT 
			ISNULL((SELECT OBJECT_ID FROM SHIPMENT_ACCESSORIALS WHERE INTERNAL_NUM=@internalNum AND ACCESSORIAL_DETAIL_ID = AD.OBJECT_ID AND SHIPMENT_LEVEL=N'<literal:27>'), 0) as N'<literal:28>',
			AD.OBJECT_ID as N'<literal:29>',
			AD.ACCESSORIAL_CODE,
			AD.ACCESSORIAL_SUB_CODE,
			AD.DESCRIPTION as DetailDesc, 
			AH.DESCRIPTION as HeaderDesc, 
			ISNULL((SELECT VALUE FROM SHIPMENT_ACCESSORIALS WHERE INTERNAL_NUM=@internalNum AND ACCESSORIAL_DETAIL_ID = AD.OBJECT_ID AND SHIPMENT_LEVEL=N'<literal:30>'), AD.VALUE) as N'<literal:31>',
			UPPER(AD.VALUE_TYPE) AS VALUE_TYPE,
			AD.ALLOW_OVERRIDE,
			ISNULL(AD.REQUIRED_FOR_RATING, N'<literal:32>') AS REQUIRED
		FROM 
			SHIPPING_CONTAINER SC
			INNER JOIN
			SHIPMENT_HEADER SHP ON SC.INTERNAL_SHIPMENT_NUM = SHP.INTERNAL_SHIPMENT_NUM
			INNER JOIN
			CARRIER CR ON SHP.CARRIER=CR.CARRIER AND ISNULL(SHP.CARRIER_SERVICE, N'<literal:33>') = ISNULL(CR.SERVICE, N'<literal:34>')
			INNER JOIN
			ACCESSORIAL_HEADER AH ON AH.RATING_ID = CR.RATING_ID AND ISNULL(AH.RATING_SERVICE, N'<literal:35>') = ISNULL(CR.RATING_SERVICE, N'<literal:36>')
			INNER JOIN
			ACCESSORIAL_DETAIL AD ON AH.OBJECT_ID = AD.HEADER_ID
		WHERE AD.VALUE_TYPE NOT IN (N'<literal:37>', N'<literal:38>') AND AD.APPLY_TO_CONTAINER_CONTENTS=N'<literal:39>' AND SC.INTERNAL_CONTAINER_NUM=@internalNum AND AH.OBJECT_ID=@headerId;
	END
END
END
