-- DOCUMENTATION ONLY: literals/comments removed; do not execute.

CREATE PROCEDURE wm_IShipmentAccessorials01
	@InternalNum numeric(9),
	@ShipmentLevel nchar(1),
	@AccessorialCode nvarchar(25),
	@AccessorialSubCode nvarchar(25),	
	@AccessorialDetailId numeric(9),
	@Value nvarchar(50),
	@UserDef1 nvarchar(25),
	@UserDef2 nvarchar(25),
	@UserDef3 nvarchar(25),
	@UserDef4 nvarchar(25),
	@UserDef5 nvarchar(25),
	@UserDef6 nvarchar(25),
	@UserDef7 numeric(19,5),
	@UserDef8 numeric(19,5),
	@UserStamp nvarchar(30),
	@ProcessStamp nvarchar(100),
	@DateTimeStamp datetime,
	@CarrierFreightCharge numeric(19,5),
	@PaidFreightCharge numeric(19,5),
	@BilledFreightCharge numeric(19,5)
AS
	INSERT INTO SHIPMENT_ACCESSORIALS(
		INTERNAL_NUM,
		ACCESSORIAL_CODE,
		ACCESSORIAL_SUB_CODE,
		ACCESSORIAL_DETAIL_ID,
		BILLED_FREIGHT_CHARGE,
		CARRIER_FREIGHT_CHARGE,
		DATE_TIME_STAMP,
		PAID_FREIGHT_CHARGE,
		PROCESS_STAMP,
		SHIPMENT_LEVEL,
		USER_DEF1,
		USER_DEF2,
		USER_DEF3,
		USER_DEF4,
		USER_DEF5,
		USER_DEF6,
		USER_DEF7,
		USER_DEF8,
		USER_STAMP,
		VALUE
	) VALUES (
		@InternalNum,
		@AccessorialCode,
		@AccessorialSubCode,
		@AccessorialDetailId,
		@BilledFreightCharge,
		@CarrierFreightCharge,
		@DateTimeStamp,
		@PaidFreightCharge,
		@ProcessStamp,
		@ShipmentLevel,
		@UserDef1,
		@UserDef2,
		@UserDef3,
		@UserDef4,
		@UserDef5,
		@UserDef6,
		@UserDef7,
		@UserDef8,
		@UserStamp,
		@Value
	)


