-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */





CREATE PROCEDURE wm_IShipmentDetail01
	@InternalShipmentLineNum numeric(9) OUTPUT,
	@InternalShipmentNum numeric(9),
	@AllocationRule nvarchar(25),
	@StatusFlowName nvarchar(25),
	@ErpOrder nvarchar(25),
	@Status1 numeric(3),
	@ErpOrderLineNum numeric(19,5),
	@Warehouse nvarchar(25),
	@InternalOrderNum numeric(9),
	@Status2 numeric(3),
	@ShipTo nvarchar(25),
	@Status3 numeric(3),
	@LaunchNum numeric(9),
	@Status4 numeric(3),
	@StatusFailed nchar(1),
	@Status5 numeric(3),
	@Status6 numeric(3),
	@Status7 numeric(3),
	@OrderType nvarchar(25),
	@Status8 numeric(3),
	@Customer nvarchar(25),
	@Item nvarchar(50),
	@Status9 numeric(3),
	@Status10 numeric(3),
	@MarkFor nvarchar(25),
	@ItemDesc nvarchar(100),
	@CustomerItem nvarchar(50),
	@Carrier nvarchar(25),
	@CarrierService nvarchar(50),
	@FreightTerms nvarchar(50),
	@LiabilityTerms nvarchar(25),
	@OrderDate datetime,
	@ShipmentId nvarchar(25),
	@Company nvarchar(25),
	@InterfacedDate datetime,
	@RequestedQty numeric(28,5),
	@QuantityUm nvarchar(25),
	@PickLoc nvarchar(25),
	@CarrierType nvarchar(25),
	@PickZone nvarchar(25),
	@SecondaryPickLoc nvarchar(25),
	@WeightUm nvarchar(25),
	@SecondaryPickZone nvarchar(25),
	@PlannedShipDate datetime,
	@ItemLength numeric(19,5),
	@ItemWidth numeric(19,5),
	@RequestedDeliveryDate datetime,
	@RequestedDeliveryType nvarchar(10),
	@ItemHeight numeric(19,5),
	@ItemDimensionUm nvarchar(25),
	@ItemDepartment nvarchar(25),
	@ItemListPrice numeric(19,5),
	@ItemNetPrice numeric(19,5),
	@ItemColor nvarchar(25),
	@ItemStyle nvarchar(25),
	@ItemSize nvarchar(25),
	@OriginalItemOrdered nvarchar(50),
	@PickListId nvarchar(25),
	@CustomerPo nvarchar(25),
	@Invoice nvarchar(25),
	@ItemVolume numeric(19,5),
	@PackingCategory nvarchar(25),
	@TotalVolume numeric(28,5),
	@HazardousCode nvarchar(25),
	@ItemDivision nvarchar(25),
	@NmfcCode nvarchar(25),
	@TotalWeight numeric(28,5),
	@CatalogId nvarchar(25),
	@ManufactureId nvarchar(25),
	@TotalQty numeric(28,5),
	@Value numeric(28,5),
	@MerchandiseCode nvarchar(25),
	@ValueAddLabelCode nvarchar(25),
	@VolumeUm nvarchar(25),
	@UserDef1 nvarchar(25),
	@UserDef2 nvarchar(25),
	@UserDef3 nvarchar(25),
	@ManuallyEntered nchar(1),
	@UserDef4 nvarchar(25),
	@UserDef5 nvarchar(25),
	@UserDef6 nvarchar(25),
	@UserDef7 numeric(19,5),
	@UserDef8 numeric(19,5),
	@UserStamp nvarchar(30),
	@ProcessStamp nvarchar(100),
	@QuantityAtSts1 numeric(19,5),
	@LotControlled nchar(1),
	@DateTimeStamp datetime,
	@SerialNumReqd nchar(1),
	@QuantityAtSts2 numeric(19,5),
	@CatchWeightReqd nchar(1),
	@QuantityAtSts3 numeric(19,5),
	@QuantityAtSts4 numeric(19,5),
	@QuantityAtSts5 numeric(19,5),
	@QuantityAtSts6 numeric(19,5),
	@QuantityAtSts7 numeric(19,5),
	@QuantityAtSts8 numeric(19,5),
	@QuantityAtSts9 numeric(19,5),
	@Priority numeric(3),
	@ItemWeight numeric(19,5),
	@QuantityAtSts10 numeric(19,5),
	@Lot nvarchar(25),
	@ItemClass nvarchar(50),
	@MarkForName nvarchar(50),
	@MarkForAddress1 nvarchar(50),
	@MarkForAddress2 nvarchar(50),
	@MarkForAddress3 nvarchar(50),
	@MarkForAttentionTo nvarchar(50),
	@MarkForCity nvarchar(30),
	@MarkForState nvarchar(25),
	@MarkForCountry nvarchar(25),
	@MarkForPostalCode nvarchar(25),
	@MarkForPhoneNum nvarchar(50),
	@MarkForFaxNum nvarchar(25),
	@MarkForEmailAddress nvarchar(50),
	@HarmonizedCode nvarchar(25),
	@HarmonizedDesc nvarchar(500),
	@ExportDesc nvarchar(500),
	@PreferenceCrit nchar(1),
	@Producer nchar(1),
	@NetCost nchar(1),
	@CountryOfOrigin nvarchar(25),
	@PackingClass nvarchar(25),
	@InterfaceRecordId nvarchar(25),
	@ItemCategory1 nvarchar(50),
	@ItemCategory2 nvarchar(50),
	@ItemCategory3 nvarchar(50),
	@ItemCategory4 nvarchar(50),
	@ItemCategory5 nvarchar(50),
	@ItemCategory6 nvarchar(50),
	@ItemCategory7 nvarchar(50),
	@ItemCategory8 nvarchar(50),
	@ItemCategory9 nvarchar(50),
	@ItemCategory10 nvarchar(50),
	@ContCreationFullQty numeric(19,5),
	@ContCreationFullQtyUm nvarchar(25),
	@ContCreationInnerpackQty numeric(19,5),
	@AllocateFullLocQty nchar(1),
	@AllowPctAlloc nchar(1),
	@MinimumAllocPct numeric(4),
	@MaximumAllocPct numeric(4),
	@ImmediateNeedsNote nvarchar(50),
	@TreatAsLoose nchar(1),
	@BomAction nchar(1),
	@RelatedInternalLineNum numeric(9),
	@QuantityNeededPerItem numeric(19,5),
	@LogisticsUnit nvarchar(50),
	@ImmediateNeedsEligible nchar(1),
	@ImmediateNeedsLocRule nvarchar(25),
	@StoreDistribution nvarchar(25),
	@Eccn nvarchar(50),
	@ValidatedLicense nvarchar(50),
	@LicenseExpDate datetime
AS
		DECLARE @stEccn nvarchar(50),@stVLicense nvarchar(50),@stLExpDate datetime

		Select @stEccn = ECCN, @stVLicense = VALIDATED_LICENSE,@stLExpDate = LICENSE_EXP_DATE From SHIPMENT_HEADER WHERE SHIPMENT_ID = @ShipmentId

		if(@Eccn is null)
		Set @Eccn = @stEccn
		if(@ValidatedLicense is null )
		set @ValidatedLicense = @stVLicense
			if (@LicenseExpDate is null)
			set @LicenseExpDate = @stLExpDate

	INSERT INTO SHIPMENT_DETAIL(
		ALLOCATE_FULL_LOC_QTY,
		ALLOCATION_RULE,
		ALLOW_PCT_ALLOC,
		BOM_ACTION,
		CARRIER,
		CARRIER_SERVICE,
		CARRIER_TYPE,
		CATALOG_ID,
		CATCH_WEIGHT_REQD,
		COMPANY,
		CONT_CREATION_FULL_QTY,
		CONT_CREATION_FULL_QTY_UM,
		CONT_CREATION_INNERPACK_QTY,
		COUNTRY_OF_ORIGIN,
		CUSTOMER,
		CUSTOMER_ITEM,
		CUSTOMER_PO,
		DATE_TIME_STAMP,
		ECCN,
		ERP_ORDER,
		ERP_ORDER_LINE_NUM,
		EXPORT_DESC,
		FREIGHT_TERMS,
		HARMONIZED_CODE,
		HARMONIZED_DESC,
		HAZARDOUS_CODE,
		IMMEDIATE_NEEDS_ELIGIBLE,
		IMMEDIATE_NEEDS_LOC_RULE,
		IMMEDIATE_NEEDS_NOTE,
		INTERFACE_RECORD_ID,
		INTERFACED_DATE,
		INTERNAL_ORDER_NUM,
		INTERNAL_SHIPMENT_NUM,
		INVOICE,
		ITEM,
		ITEM_CATEGORY1,
		ITEM_CATEGORY10,
		ITEM_CATEGORY2,
		ITEM_CATEGORY3,
		ITEM_CATEGORY4,
		ITEM_CATEGORY5,
		ITEM_CATEGORY6,
		ITEM_CATEGORY7,
		ITEM_CATEGORY8,
		ITEM_CATEGORY9,
		ITEM_CLASS,
		ITEM_COLOR,
		ITEM_DEPARTMENT,
		ITEM_DESC,
		ITEM_DIMENSION_UM,
		ITEM_DIVISION,
		ITEM_HEIGHT,
		ITEM_LENGTH,
		ITEM_LIST_PRICE,
		ITEM_NET_PRICE,
		ITEM_SIZE,
		ITEM_STYLE,
		ITEM_VOLUME,
		ITEM_WEIGHT,
		ITEM_WIDTH,
		LAUNCH_NUM,
		LIABILITY_TERMS,
		LICENSE_EXP_DATE,
		LOGISTICS_UNIT,
		LOT,
		LOT_CONTROLLED,
		MANUALLY_ENTERED,
		MANUFACTURE_ID,
		MARK_FOR,
		MARK_FOR_ADDRESS1,
		MARK_FOR_ADDRESS2,
		MARK_FOR_ADDRESS3,
		MARK_FOR_ATTENTION_TO,
		MARK_FOR_CITY,
		MARK_FOR_COUNTRY,
		MARK_FOR_EMAIL_ADDRESS,
		MARK_FOR_FAX_NUM,
		MARK_FOR_NAME,
		MARK_FOR_PHONE_NUM,
		MARK_FOR_POSTAL_CODE,
		MARK_FOR_STATE,
		MAXIMUM_ALLOC_PCT,
		MERCHANDISE_CODE,
		MINIMUM_ALLOC_PCT,
		NET_COST,
		NMFC_CODE,
		ORDER_DATE,
		ORDER_TYPE,
		ORIGINAL_ITEM_ORDERED,
		PACKING_CATEGORY,
		PACKING_CLASS,
		PICK_LIST_ID,
		PICK_LOC,
		PICK_ZONE,
		PLANNED_SHIP_DATE,
		PREFERENCE_CRIT,
		PRIORITY,
		PROCESS_STAMP,
		PRODUCER,
		QUANTITY_AT_STS1,
		QUANTITY_AT_STS10,
		QUANTITY_AT_STS2,
		QUANTITY_AT_STS3,
		QUANTITY_AT_STS4,
		QUANTITY_AT_STS5,
		QUANTITY_AT_STS6,
		QUANTITY_AT_STS7,
		QUANTITY_AT_STS8,
		QUANTITY_AT_STS9,
		QUANTITY_NEEDED_PER_ITEM,
		QUANTITY_UM,
		RELATED_INTERNAL_LINE_NUM,
		REQUESTED_DELIVERY_DATE,
		REQUESTED_DELIVERY_TYPE,
		REQUESTED_QTY,
		SECONDARY_PICK_LOC,
		SECONDARY_PICK_ZONE,
		SERIAL_NUM_REQD,
		SHIP_TO,
		SHIPMENT_ID,
		STATUS_FAILED,
		STATUS_FLOW_NAME,
		STATUS1,
		STATUS10,
		STATUS2,
		STATUS3,
		STATUS4,
		STATUS5,
		STATUS6,
		STATUS7,
		STATUS8,
		STATUS9,
		STORE_DISTRIBUTION,
		TOTAL_QTY,
		TOTAL_VOLUME,
		TOTAL_WEIGHT,
		TREAT_AS_LOOSE,
		USER_DEF1,
		USER_DEF2,
		USER_DEF3,
		USER_DEF4,
		USER_DEF5,
		USER_DEF6,
		USER_DEF7,
		USER_DEF8,
		USER_STAMP,
		VALIDATED_LICENSE,
		VALUE,
		VALUE_ADD_LABEL_CODE,
		VOLUME_UM,
		warehouse,
		WEIGHT_UM
	) VALUES (
		@AllocateFullLocQty,
		@AllocationRule,
		@AllowPctAlloc,
		@BomAction,
		@Carrier,
		@CarrierService,
		@CarrierType,
		@CatalogId,
		@CatchWeightReqd,
		@Company,
		@ContCreationFullQty,
		@ContCreationFullQtyUm,
		@ContCreationInnerpackQty,
		@CountryOfOrigin,
		@Customer,
		@CustomerItem,
		@CustomerPo,
		@DateTimeStamp,
		@Eccn,
		@ErpOrder,
		@ErpOrderLineNum,
		@ExportDesc,
		@FreightTerms,
		@HarmonizedCode,
		@HarmonizedDesc,
		@HazardousCode,
		@ImmediateNeedsEligible,
		@ImmediateNeedsLocRule,
		@ImmediateNeedsNote,
		@InterfaceRecordId,
		@InterfacedDate,
		@InternalOrderNum,
		@InternalShipmentNum,
		@Invoice,
		@Item,
		@ItemCategory1,
		@ItemCategory10,
		@ItemCategory2,
		@ItemCategory3,
		@ItemCategory4,
		@ItemCategory5,
		@ItemCategory6,
		@ItemCategory7,
		@ItemCategory8,
		@ItemCategory9,
		@ItemClass,
		@ItemColor,
		@ItemDepartment,
		@ItemDesc,
		@ItemDimensionUm,
		@ItemDivision,
		@ItemHeight,
		@ItemLength,
		@ItemListPrice,
		@ItemNetPrice,
		@ItemSize,
		@ItemStyle,
		@ItemVolume,
		@ItemWeight,
		@ItemWidth,
		@LaunchNum,
		@LiabilityTerms,
		@LicenseExpDate,
		@LogisticsUnit,
		@Lot,
		@LotControlled,
		@ManuallyEntered,
		@ManufactureId,
		@MarkFor,
		@MarkForAddress1,
		@MarkForAddress2,
		@MarkForAddress3,
		@MarkForAttentionTo,
		@MarkForCity,
		@MarkForCountry,
		@MarkForEmailAddress,
		@MarkForFaxNum,
		@MarkForName,
		@MarkForPhoneNum,
		@MarkForPostalCode,
		@MarkForState,
		@MaximumAllocPct,
		@MerchandiseCode,
		@MinimumAllocPct,
		@NetCost,
		@NmfcCode,
		@OrderDate,
		@OrderType,
		@OriginalItemOrdered,
		@PackingCategory,
		@PackingClass,
		@PickListId,
		@PickLoc,
		@PickZone,
		@PlannedShipDate,
		@PreferenceCrit,
		@Priority,
		@ProcessStamp,
		@Producer,
		@QuantityAtSts1,
		@QuantityAtSts10,
		@QuantityAtSts2,
		@QuantityAtSts3,
		@QuantityAtSts4,
		@QuantityAtSts5,
		@QuantityAtSts6,
		@QuantityAtSts7,
		@QuantityAtSts8,
		@QuantityAtSts9,
		@QuantityNeededPerItem,
		@QuantityUm,
		@RelatedInternalLineNum,
		@RequestedDeliveryDate,
		@RequestedDeliveryType,
		@RequestedQty,
		@SecondaryPickLoc,
		@SecondaryPickZone,
		@SerialNumReqd,
		@ShipTo,
		@ShipmentId,
		@StatusFailed,
		@StatusFlowName,
		@Status1,
		@Status10,
		@Status2,
		@Status3,
		@Status4,
		@Status5,
		@Status6,
		@Status7,
		@Status8,
		@Status9,
		@StoreDistribution,
		@TotalQty,
		@TotalVolume,
		@TotalWeight,
		@TreatAsLoose,
		@UserDef1,
		@UserDef2,
		@UserDef3,
		@UserDef4,
		@UserDef5,
		@UserDef6,
		@UserDef7,
		@UserDef8,
		@UserStamp,
		@ValidatedLicense,
		@Value,
		@ValueAddLabelCode,
		@VolumeUm,
		@Warehouse,
		@WeightUm
	)
SELECT @InternalShipmentLineNum = SCOPE_IDENTITY()


