-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
-- [comment omitted]
-- [comment omitted]
/* [comment omitted] */




-- [comment omitted]
CREATE PROCEDURE GetAvailableAccessorials(
@internalNum int,
@internalNumType nvarchar(100))
AS
-- [comment omitted]
if(UPPER(@internalNumType) = N'<literal:1>')
BEGIN
	SELECT 
		AH.ACCESSORIAL_CODE,
		AH.DESCRIPTION,
		AH.OBJECT_ID
	FROM 
		SHIPMENT_HEADER SHP
		INNER JOIN
		CARRIER CR ON SHP.CARRIER=CR.CARRIER AND ISNULL(SHP.CARRIER_SERVICE, N'<literal:2>') = ISNULL(CR.SERVICE, N'<literal:3>')
		INNER JOIN
		ACCESSORIAL_HEADER AH ON AH.RATING_ID = CR.RATING_ID AND ISNULL(AH.RATING_SERVICE, N'<literal:4>') = ISNULL(CR.RATING_SERVICE, N'<literal:5>')
	WHERE SHP.INTERNAL_SHIPMENT_NUM=@internalNum;
END
ELSE
BEGIN 
	declare @isContainerContent bit=0;
	select @isContainerContent = 1 FROM SHIPPING_CONTAINER WHERE INTERNAL_CONTAINER_NUM=@internalNum AND CONTAINER_TYPE=N'<literal:6>';
	IF(@isContainerContent = 1)	
	BEGIN
		SELECT 
			AH.ACCESSORIAL_CODE,
			AH.DESCRIPTION,
			AH.OBJECT_ID
		FROM 
			SHIPPING_CONTAINER SC
			INNER JOIN
			SHIPMENT_HEADER SHP ON SC.INTERNAL_SHIPMENT_NUM=SHP.INTERNAL_SHIPMENT_NUM
			INNER JOIN
			CARRIER CR ON SHP.CARRIER=CR.CARRIER AND ISNULL(SHP.CARRIER_SERVICE, N'<literal:7>') = ISNULL(CR.SERVICE, N'<literal:8>')
			INNER JOIN
			ACCESSORIAL_HEADER AH ON AH.RATING_ID = CR.RATING_ID AND ISNULL(AH.RATING_SERVICE, N'<literal:9>') = ISNULL(CR.RATING_SERVICE, N'<literal:10>')
		WHERE SC.INTERNAL_CONTAINER_NUM=@internalNum AND AH.APPLY_PER_CONTAINER=N'<literal:11>';
	END
	ELSE
	BEGIN
		SELECT 
			AH.ACCESSORIAL_CODE,
			AH.DESCRIPTION,
			AH.OBJECT_ID
		FROM 
			SHIPPING_CONTAINER SC
			INNER JOIN
			SHIPMENT_HEADER SHP ON SC.INTERNAL_SHIPMENT_NUM=SHP.INTERNAL_SHIPMENT_NUM
			INNER JOIN
			CARRIER CR ON SHP.CARRIER=CR.CARRIER AND ISNULL(SHP.CARRIER_SERVICE, N'<literal:12>') = ISNULL(CR.SERVICE, N'<literal:13>')
			INNER JOIN
			ACCESSORIAL_HEADER AH ON AH.RATING_ID = CR.RATING_ID AND ISNULL(AH.RATING_SERVICE, N'<literal:14>') = ISNULL(CR.RATING_SERVICE, N'<literal:15>')
		WHERE SC.INTERNAL_CONTAINER_NUM=@internalNum AND AH.APPLY_PER_CONTAINER=N'<literal:16>' AND EXISTS(SELECT TOP 1 1 FROM ACCESSORIAL_DETAIL WHERE HEADER_ID=AH.OBJECT_ID AND APPLY_TO_CONTAINER_CONTENTS=N'<literal:17>');
	END
END

