-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */









CREATE PROCEDURE wm_IShipmentHeader01
	@InternalShipmentNum numeric(9) OUTPUT,
	@Warehouse nvarchar(25),
	@ShippingLoadNum numeric(9),
	@ShipmentId nvarchar(25),
	@ShipperCode nvarchar(25),
	@LaunchStep nvarchar(25),
	@TrailingSts numeric(3),
	@TrailingStsDate datetime,
	@TrailingStsFailed nchar(1),
	@OrderType nvarchar(25),
	@Consolidated nchar(1),
	@LeadingSts numeric(3),
	@LeadingStsDate datetime,
	@Carrier nvarchar(25),
	@LeadingStsFailed nchar(1),
	@Company nvarchar(25),
	@CarrierService nvarchar(50),
	@CarrierGroup nvarchar(25),
	@CarrierType nvarchar(25),
	@FreightTerms nvarchar(50),
	@LiabilityTerms nvarchar(25),
	@Customer nvarchar(25),
	@ShipTo nvarchar(25),
	@Route nvarchar(25),
	@Stop nvarchar(25),
	@ShipToAddress1 nvarchar(50),
	@CustomerName nvarchar(50),
	@ShipToAddress2 nvarchar(50),
	@ShipToAddress3 nvarchar(50),
	@ShipToCity nvarchar(30),
	@ShipToState nvarchar(25),
	@ShipToCountry nvarchar(25),
	@ShipToPostalCode nvarchar(25),
	@ShipToPhoneNum nvarchar(50),
	@ShipToFaxNum nvarchar(50),
	@CustomerAddress1 nvarchar(50),
	@LaunchNum numeric(9),
	@WeightUm nvarchar(25),
	@VolumeUm nvarchar(25),
	@RoutingCode nvarchar(25),
	@SingleItemCartons nchar(1),
	@UserDef1 nvarchar(25),
	@UserDef2 nvarchar(25),
	@Priority numeric(3),
	@UserDef3 nvarchar(25),
	@UserDef4 nvarchar(25),
	@UserDef5 nvarchar(25),
	@UserDef6 nvarchar(25),
	@UserDef7 numeric(19,5),
	@ManuallyEntered nchar(1),
	@UserDef8 numeric(19,5),
	@UserStamp nvarchar(30),
	@ProcessStamp nvarchar(100),
	@DateTimeStamp datetime,
	@BolNumAlpha nvarchar(25),
	@ProNumAlpha nvarchar(25),
	@CustomerAddress3 nvarchar(50),
	@CustomerAddress2 nvarchar(50),
	@CustomerAttentionTo nvarchar(50),
	@CustomerCity nvarchar(30),
	@CustomerState nvarchar(25),
	@CustomerCountry nvarchar(25),
	@CustomerPostalCode nvarchar(25),
	@CustomerPhoneNum nvarchar(50),
	@CustomerFaxNum nvarchar(50),
	@CustomerEmailAddress nvarchar(50),
	@ShipToName nvarchar(50),
	@ShipToAttentionTo nvarchar(50),
	@ShipToEmailAddress nvarchar(50),
	@RequestedDeliveryDate datetime,
	@RequestedDeliveryType nvarchar(10),
	@ScheduledShipDate datetime,
	@PlannedShipDate datetime,
	@ActualShipDateTime datetime,
	@PlannedDeliveryDateTime datetime,
	@ActualDeliveryDateTime datetime,
	@QuantityUm nvarchar(25),
	@TotalFreightCharge numeric(28,5),
	@BaseFreightCharge numeric(19,5),
	@FreightDiscount numeric(19,5),
	@AccessorialCharge numeric(19,5),
	@ConsolidationAllowed nchar(1),
	@IntermediateConsignee nvarchar(25),
	@IntermediateName nvarchar(50),
	@IntermediateAddress1 nvarchar(50),
	@IntermediateAddress2 nvarchar(50),
	@IntermediateAddress3 nvarchar(50),
	@IntermediateAttentionTo nvarchar(50),
	@IntermediateCity nvarchar(30),
	@IntermediateState nvarchar(25),
	@IntermediateCountry nvarchar(25),
	@IntermediatePostalCode nvarchar(25),
	@IntermediatePhoneNum nvarchar(50),
	@IntermediateFaxNum nvarchar(50),
	@IntermediateEmailAddress nvarchar(50),
	@FreightBillTo nvarchar(25),
	@FreightBillToName nvarchar(50),
	@FreightBillToAddress1 nvarchar(50),
	@FreightBillToAddress2 nvarchar(50),
	@FreightBillToAddress3 nvarchar(50),
	@FreightBillToAttentionTo nvarchar(50),
	@FreightBillToCity nvarchar(30),
	@FreightBillToState nvarchar(25),
	@FreightBillToCountry nvarchar(25),
	@FreightBillToPostalCode nvarchar(25),
	@FreightBillToPhoneNum nvarchar(50),
	@FreightBillToFaxNum nvarchar(50),
	@FreightBillToEmailAddress nvarchar(50),
	@ErpOrder nvarchar(25),
	@InternalOrderNum numeric(9),
	@ExportTaxId nvarchar(25),
	@Parties nvarchar(100),
	@LoadingPier nvarchar(50),
	@TransportationMode nvarchar(25),
	@ExportPort nvarchar(50),
	@UnloadingPort nvarchar(50),
	@Containerized nchar(1),
	@Ftz nvarchar(25),
	@ValidatedLicense nvarchar(50),
	@LicenseExpDate datetime,
	@Eccn nvarchar(50),
	@AuthorizedEmplName nvarchar(50),
	@AuthorizedEmplTitle nvarchar(50),
	@UploadInterfaceBatch nvarchar(50),
	@CustomerResidentialFlag nchar(1),
	@ShiptoResidentialFlag nchar(1),
	@RejectionNote nvarchar(1000),
	@InterfaceRecordId nvarchar(25),
	@CustomerCategory1 nvarchar(50),
	@CustomerCategory2 nvarchar(50),
	@CustomerCategory3 nvarchar(50),
	@CustomerCategory4 nvarchar(50),
	@CustomerCategory5 nvarchar(50),
	@CustomerCategory6 nvarchar(50),
	@CustomerCategory7 nvarchar(50),
	@CustomerCategory8 nvarchar(50),
	@CustomerCategory9 nvarchar(50),
	@CustomerCategory10 nvarchar(50),
	@ConsolidationDockLocArea nvarchar(25),
	@ConsolidationDockLocPos nvarchar(25),	
	@ProcessType nvarchar(25),
	@CreationProcessStamp nvarchar(100),
	@CreationDateTimeStamp datetime,
	@ImmediateNeedsNote nvarchar(50),
	@AllocateComplete nchar(1),
	@AlternateEmailAddress nvarchar(50),
	@StopSequence numeric(9),
	@InternalCarrierNum numeric(9),
	@StoreDistribution nvarchar(25),
	@WeightEntered numeric(28,5),
	@ValueEntered numeric(28,5),
	@VolumeEntered numeric(28,5),	
	@UserDef10 numeric(19,5),
	@UserDef11 nvarchar(250),
	@UserDef12 nvarchar(250),
	@UserDef13 nvarchar(100),
	@UserDef14 nvarchar(100),
	@UserDef15 nvarchar(100),
	@UserDef16 nvarchar(100),
	@UserDef17DateTime datetime,
	@UserDef18DateTime datetime,
	@UserDef19DateTime datetime,
	@UserDef20DateTime datetime,
	@UserDef9 numeric(19,5)
AS
	INSERT INTO SHIPMENT_HEADER(
		ACCESSORIAL_CHARGE,
		ACTUAL_DELIVERY_DATE_TIME,
		ACTUAL_SHIP_DATE_TIME,
		ALLOCATE_COMPLETE,
		ALTERNATE_EMAIL_ADDRESS,
		AUTHORIZED_EMPL_NAME,
		AUTHORIZED_EMPL_TITLE,
		BASE_FREIGHT_CHARGE,
		BOL_NUM_ALPHA,
		CARRIER,
		CARRIER_GROUP,
		CARRIER_SERVICE,
		CARRIER_TYPE,
		COMPANY,
		CONSOLIDATED,
		CONSOLIDATION_ALLOWED,
		CONSOLIDATION_DOCK_LOC_AREA,
		CONSOLIDATION_DOCK_LOC_POS,
		CONTAINERIZED,
		CREATION_DATE_TIME_STAMP,
		CREATION_PROCESS_STAMP,
		CUSTOMER,
		CUSTOMER_ADDRESS1,
		CUSTOMER_ADDRESS2,
		CUSTOMER_ADDRESS3,
		CUSTOMER_ATTENTION_TO,
		CUSTOMER_CATEGORY1,
		CUSTOMER_CATEGORY10,
		CUSTOMER_CATEGORY2,
		CUSTOMER_CATEGORY3,
		CUSTOMER_CATEGORY4,
		CUSTOMER_CATEGORY5,
		CUSTOMER_CATEGORY6,
		CUSTOMER_CATEGORY7,
		CUSTOMER_CATEGORY8,
		CUSTOMER_CATEGORY9,
		CUSTOMER_CITY,
		CUSTOMER_COUNTRY,
		CUSTOMER_EMAIL_ADDRESS,
		CUSTOMER_FAX_NUM,
		CUSTOMER_NAME,
		CUSTOMER_PHONE_NUM,
		CUSTOMER_POSTAL_CODE,
		CUSTOMER_RESIDENTIAL_FLAG,
		CUSTOMER_STATE,
		DATE_TIME_STAMP,
		ECCN,
		ERP_ORDER,
		EXPORT_PORT,
		EXPORT_TAX_ID,
		FREIGHT_BILL_TO,
		FREIGHT_BILL_TO_ADDRESS1,
		FREIGHT_BILL_TO_ADDRESS2,
		FREIGHT_BILL_TO_ADDRESS3,
		FREIGHT_BILL_TO_ATTENTION_TO,
		FREIGHT_BILL_TO_CITY,
		FREIGHT_BILL_TO_COUNTRY,
		FREIGHT_BILL_TO_EMAIL_ADDRESS,
		FREIGHT_BILL_TO_FAX_NUM,
		FREIGHT_BILL_TO_NAME,
		FREIGHT_BILL_TO_PHONE_NUM,
		FREIGHT_BILL_TO_POSTAL_CODE,
		FREIGHT_BILL_TO_STATE,
		FREIGHT_DISCOUNT,
		FREIGHT_TERMS,
		FTZ,
		IMMEDIATE_NEEDS_NOTE,
		INTERFACE_RECORD_ID,
		INTERMEDIATE_ADDRESS1,
		INTERMEDIATE_ADDRESS2,
		INTERMEDIATE_ADDRESS3,
		INTERMEDIATE_ATTENTION_TO,
		INTERMEDIATE_CITY,
		INTERMEDIATE_CONSIGNEE,
		INTERMEDIATE_COUNTRY,
		INTERMEDIATE_EMAIL_ADDRESS,
		INTERMEDIATE_FAX_NUM,
		INTERMEDIATE_NAME,
		INTERMEDIATE_PHONE_NUM,
		INTERMEDIATE_POSTAL_CODE,
		INTERMEDIATE_STATE,
		INTERNAL_CARRIER_NUM,
		INTERNAL_ORDER_NUM,
		LAUNCH_NUM,
		LAUNCH_STEP,
		LEADING_STS,
		LEADING_STS_DATE,
		LEADING_STS_FAILED,
		LIABILITY_TERMS,
		LICENSE_EXP_DATE,
		LOADING_PIER,
		MANUALLY_ENTERED,
		ORDER_TYPE,
		PARTIES,
		PLANNED_DELIVERY_DATE_TIME,
		PLANNED_SHIP_DATE,
		PRIORITY,
		PRO_NUM_ALPHA,
		PROCESS_STAMP,
		PROCESS_TYPE,
		QUANTITY_UM,
		REJECTION_NOTE,
		REQUESTED_DELIVERY_DATE,
		REQUESTED_DELIVERY_TYPE,
		ROUTE,
		ROUTING_CODE,
		SCHEDULED_SHIP_DATE,
		SHIP_TO,
		SHIP_TO_ADDRESS1,
		SHIP_TO_ADDRESS2,
		SHIP_TO_ADDRESS3,
		SHIP_TO_ATTENTION_TO,
		SHIP_TO_CITY,
		SHIP_TO_COUNTRY,
		SHIP_TO_EMAIL_ADDRESS,
		SHIP_TO_FAX_NUM,
		SHIP_TO_NAME,
		SHIP_TO_PHONE_NUM,
		SHIP_TO_POSTAL_CODE,
		SHIP_TO_STATE,
		SHIPMENT_ID,
		SHIPPER_CODE,
		SHIPPING_LOAD_NUM,
		SHIPTO_RESIDENTIAL_FLAG,
		SINGLE_ITEM_CARTONS,		
		STOP,
		STOP_SEQUENCE,
		STORE_DISTRIBUTION,
		TOTAL_FREIGHT_CHARGE,
		TRAILING_STS,
		TRAILING_STS_DATE,
		TRAILING_STS_FAILED,
		TRANSPORTATION_MODE,
		UNLOADING_PORT,
		UPLOAD_INTERFACE_BATCH,
		USER_DEF1,
		USER_DEF2,
		USER_DEF3,
		USER_DEF4,
		USER_DEF5,
		USER_DEF6,
		USER_DEF7,
		USER_DEF8,
		USER_DEF9,
		USER_DEF10,
		USER_DEF11,
		USER_DEF12,
		USER_DEF13,
		USER_DEF14,
		USER_DEF15,
		USER_DEF16,
		USER_DEF17_Date_Time,
		USER_DEF18_Date_Time,
		USER_DEF19_Date_Time,
		USER_DEF20_Date_Time,
		USER_STAMP,
		VALIDATED_LICENSE,
		VOLUME_UM,
		warehouse,
		WEIGHT_UM,
		WEIGHT_ENTERED,
		VOLUME_ENTERED,
		VALUE_ENTERED
	) VALUES (
		@AccessorialCharge,
		@ActualDeliveryDateTime,
		@ActualShipDateTime,
		@AllocateComplete,
		@AlternateEmailAddress,
		@AuthorizedEmplName,
		@AuthorizedEmplTitle,
		@BaseFreightCharge,
		@BolNumAlpha,
		@Carrier,
		@CarrierGroup,
		@CarrierService,
		@CarrierType,
		@Company,
		@Consolidated,
		@ConsolidationAllowed,
		@ConsolidationDockLocArea,
		@ConsolidationDockLocPos,
		@Containerized,
		@CreationDateTimeStamp,
		@CreationProcessStamp,
		@Customer,
		@CustomerAddress1,
		@CustomerAddress2,
		@CustomerAddress3,
		@CustomerAttentionTo,
		@CustomerCategory1,
		@CustomerCategory10,
		@CustomerCategory2,
		@CustomerCategory3,
		@CustomerCategory4,
		@CustomerCategory5,
		@CustomerCategory6,
		@CustomerCategory7,
		@CustomerCategory8,
		@CustomerCategory9,
		@CustomerCity,
		@CustomerCountry,
		@CustomerEmailAddress,
		@CustomerFaxNum,
		@CustomerName,
		@CustomerPhoneNum,
		@CustomerPostalCode,
		@CustomerResidentialFlag,
		@CustomerState,
		@DateTimeStamp,
		@Eccn,
		@ErpOrder,
		@ExportPort,
		@ExportTaxId,
		@FreightBillTo,
		@FreightBillToAddress1,
		@FreightBillToAddress2,
		@FreightBillToAddress3,
		@FreightBillToAttentionTo,
		@FreightBillToCity,
		@FreightBillToCountry,
		@FreightBillToEmailAddress,
		@FreightBillToFaxNum,
		@FreightBillToName,
		@FreightBillToPhoneNum,
		@FreightBillToPostalCode,
		@FreightBillToState,
		@FreightDiscount,
		@FreightTerms,
		@Ftz,
		@ImmediateNeedsNote,
		@InterfaceRecordId,
		@IntermediateAddress1,
		@IntermediateAddress2,
		@IntermediateAddress3,
		@IntermediateAttentionTo,
		@IntermediateCity,
		@IntermediateConsignee,
		@IntermediateCountry,
		@IntermediateEmailAddress,
		@IntermediateFaxNum,
		@IntermediateName,
		@IntermediatePhoneNum,
		@IntermediatePostalCode,
		@IntermediateState,
		@InternalCarrierNum,
		@InternalOrderNum,
		@LaunchNum,
		@LaunchStep,
		@LeadingSts,
		@LeadingStsDate,
		@LeadingStsFailed,
		@LiabilityTerms,
		@LicenseExpDate,
		@LoadingPier,
		@ManuallyEntered,
		@OrderType,
		@Parties,
		@PlannedDeliveryDateTime,
		@PlannedShipDate,
		@Priority,
		@ProNumAlpha,
		@ProcessStamp,
		@ProcessType,
		@QuantityUm,
		@RejectionNote,
		@RequestedDeliveryDate,
		@RequestedDeliveryType,
		@Route,
		@RoutingCode,
		@ScheduledShipDate,
		@ShipTo,
		@ShipToAddress1,
		@ShipToAddress2,
		@ShipToAddress3,
		@ShipToAttentionTo,
		@ShipToCity,
		@ShipToCountry,
		@ShipToEmailAddress,
		@ShipToFaxNum,
		@ShipToName,
		@ShipToPhoneNum,
		@ShipToPostalCode,
		@ShipToState,
		@ShipmentId,
		@ShipperCode,
		@ShippingLoadNum,
		@ShiptoResidentialFlag,
		@SingleItemCartons,		
		@Stop,
		@StopSequence,
		@StoreDistribution,
		@TotalFreightCharge,
		@TrailingSts,
		@TrailingStsDate,
		@TrailingStsFailed,
		@TransportationMode,
		@UnloadingPort,
		@UploadInterfaceBatch,
		@UserDef1,
		@UserDef2,
		@UserDef3,
		@UserDef4,
		@UserDef5,
		@UserDef6,
		@UserDef7,
		@UserDef8,
		@UserDef9,
		@UserDef10,
		@UserDef11,
		@UserDef12,
		@UserDef13,
		@UserDef14,
		@UserDef15,
		@UserDef16,
		@UserDef17DateTime,
		@UserDef18DateTime,
		@UserDef19DateTime,
		@UserDef20DateTime,
		@UserStamp,
		@ValidatedLicense,
		@VolumeUm,
		@Warehouse,
		@WeightUm,
		@WeightEntered,
		@VolumeEntered,
		@ValueEntered
	)
SELECT @InternalShipmentNum = SCOPE_IDENTITY()
