-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */

















CREATE PROCEDURE RPT_YardVisibilityDetails
(	
	@paramwarehouse nvarchar(25)
)
AS
BEGIN
	
	SELECT
			D.DOCK_LOCATION AS N'<literal:1>', 
			T.TRAILER_LOCATION AS N'<literal:2>', 
			CASE 
				WHEN T.TRAILER_ID IS NULL THEN N'<literal:3>'
				WHEN T.SCHEDULED_YARD_LOCATION = D.DOCK_LOCATION THEN N'<literal:4>'
				ELSE T.TRAILER_ID
			END N'<literal:5>',
			CASE 
				WHEN T.SCHEDULED_YARD_LOCATION = D.DOCK_LOCATION THEN T.TRAILER_ID
			END N'<literal:6>',
			R.RECEIPT_ID N'<literal:7>',
			R.INTERNAL_RECEIPT_NUM N'<literal:8>', 
			A.APPT_DATE_TIME N'<literal:9>', 
			T.CHECKED_IN_DATE_TIME N'<literal:10>'			
	FROM 	(
				SELECT		DOCK_LOCATION 
				FROM		DOCK_LOCATION WITH (NOLOCK)
				WHERE		WAREHOUSE = @paramwarehouse
				AND			DOCK_LOCATION_AREA IN
				(	
					SELECT	IDENTIFIER 
					FROM	GENERIC_CONFIG_DETAIL WITH (NOLOCK)
					WHERE	RECORD_TYPE = N'<literal:11>'
				)
			)D 
	LEFT OUTER JOIN TRAILER_YARD_STATUS T WITH (NOLOCK)
	ON			(D.DOCK_LOCATION = T.TRAILER_LOCATION OR 
				D.DOCK_LOCATION = T.SCHEDULED_YARD_LOCATION)
	LEFT OUTER JOIN RECEIPT_HEADER R WITH (NOLOCK)
	ON			T.TRAILER_ID = R.TRAILER_ID 
	LEFT OUTER JOIN APPOINTMENT_SCHEDULE A WITH (NOLOCK)
	ON			R.INTERNAL_RECEIPT_NUM = A.INTERNAL_RECEIPT_NUM
	ORDER BY	DOCK_LOCATION
END




