-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */







CREATE PROCEDURE wm_IShippingContainer01
	@InternalContainerNum numeric(9) OUTPUT,
	@ContainerId nvarchar(25),
	@Warehouse nvarchar(25),
	@ContainerType nvarchar(25),
	@ContainerClass nvarchar(25),
	@Status numeric(3),
	@StatusFailed nchar(1),
	@Parent numeric(9),
	@Weight numeric(19,5),
	@WeightUm nvarchar(25),
	@Volume numeric(19,5),
	@Length numeric(19,5),
	@Width numeric(19,5),
	@Height numeric(19,5),
	@DimensionUm nvarchar(25),
	@VolumeUm nvarchar(25),
	@Value numeric(19,5),
	@InternalShipmentNum numeric(9),
	@InternalShipmentLineNum numeric(9),
	@Company nvarchar(25),
	@Item nvarchar(50),
	@Quantity numeric(19,5),
	@QuantityUm nvarchar(25),
	@NmfcCode nvarchar(25),
	@StatusFlowName nvarchar(25),
	@HazardousCode nvarchar(25),
	@ManifestState nvarchar(25),
	@ManifestCarrServiceSymbol nvarchar(50),
	@ManifestDateTime datetime,
	@TrackingNumber nvarchar(50),
	@TotalFreightCharge numeric(28,5),
	@BaseFreightCharge numeric(19,5),
	@FreightDiscount numeric(19,5),
	@AccessorialCharge numeric(19,5),
	@UserDef1 nvarchar(25),
	@UserDef2 nvarchar(25),
	@UserDef3 nvarchar(25),
	@UserDef4 nvarchar(25),
	@UserDef5 nvarchar(25),
	@UserDef6 nvarchar(25),
	@UserDef7 numeric(19,5),
	@UserDef8 numeric(19,5),
	@UserStamp nvarchar(30),
	@ProcessStamp nvarchar(100),
	@DateTimeStamp datetime,
	@InternalOrderNum numeric(9),
	@ManifestForDate datetime,
	@TreeUnit numeric(9),
	@PlannedDeliveryDateTime datetime,
	@BundleId numeric(25),
	@Msn numeric(25),
	@Location nvarchar(25),
	@GroupPosition numeric(9),
	@LaunchNum numeric(9),
	@ContainerCountNumber numeric(9),
	@ContainerCountTotal numeric(9),
	@GroupNum numeric(9),
	@WorkZone nvarchar(25),
	@InterfaceRecordId nvarchar(25),
	@ParentContainerId nvarchar(25),
	@InternalShipAllocNum numeric(9),
	@WorkCreated nchar(1),
	@Hundredweight nchar(1),
	@ManifestId nvarchar(100),
	@ManifestCloseDateTime datetime,
	@EPC nvarchar(32),
	@URI nvarchar(100),
	@Lot nvarchar(25),
	@OriginalPickLoc nvarchar(25)=null,
	@PalletUmConversionIdentifier numeric(9),
	@PalletUmConversionParentUm nvarchar(25)
AS
	INSERT INTO SHIPPING_CONTAINER(
		ACCESSORIAL_CHARGE,
		BASE_FREIGHT_CHARGE,
		BUNDLE_ID,
		COMPANY,
		CONTAINER_CLASS,
		CONTAINER_COUNT_NUMBER,
		CONTAINER_COUNT_TOTAL,
		CONTAINER_ID,
		CONTAINER_TYPE,
		DATE_TIME_STAMP,
		DIMENSION_UM,
		EPC,
		URI,
		FREIGHT_DISCOUNT,
		GROUP_NUM,
		GROUP_POSITION,
		HAZARDOUS_CODE,
		HEIGHT,
		HUNDREDWEIGHT,
		INTERFACE_RECORD_ID,
		INTERNAL_ORDER_NUM,
		INTERNAL_SHIP_ALLOC_NUM,
		INTERNAL_SHIPMENT_LINE_NUM,
		INTERNAL_SHIPMENT_NUM,
		ITEM,
		LAUNCH_NUM,
		LENGTH,
		LOCATION,
		MANIFEST_CARR_SERVICE_SYMBOL,
		MANIFEST_CLOSE_DATE_TIME,
		MANIFEST_DATE_TIME,
		MANIFEST_FOR_DATE,
		MANIFEST_ID,
		MANIFEST_STATE,
		MSN,
		NMFC_CODE,
		ORIGINAL_PICK_LOC,
		PALLET_UM_CONVERSION_IDENTIFIER,
		PALLET_UM_CONVERSION_PARENT_UM,
		PARENT,
		PARENT_CONTAINER_ID,
		PLANNED_DELIVERY_DATE_TIME,
		PROCESS_STAMP,
		QUANTITY,
		QUANTITY_UM,
		status,
		STATUS_FAILED,
		STATUS_FLOW_NAME,
		TOTAL_FREIGHT_CHARGE,
		TRACKING_NUMBER,
		TREE_UNIT,
		USER_DEF1,
		USER_DEF2,
		USER_DEF3,
		USER_DEF4,
		USER_DEF5,
		USER_DEF6,
		USER_DEF7,
		USER_DEF8,
		USER_STAMP,
		VALUE,
		VOLUME,
		VOLUME_UM,
		warehouse,
		WEIGHT,
		WEIGHT_UM,
		WIDTH,
		WORK_CREATED,
		WORK_ZONE,
		LOT,
		QC_STATUS
	) VALUES (
		@AccessorialCharge,
		@BaseFreightCharge,
		@BundleId,
		@Company,
		@ContainerClass,
		@ContainerCountNumber,
		@ContainerCountTotal,
		@ContainerId,
		@ContainerType,
		@DateTimeStamp,
		@DimensionUm,
		@EPC,
		@URI,
		@FreightDiscount,
		@GroupNum,
		@GroupPosition,
		@HazardousCode,
		@Height,
		@Hundredweight,
		@InterfaceRecordId,
		@InternalOrderNum,
		@InternalShipAllocNum,
		@InternalShipmentLineNum,
		@InternalShipmentNum,
		@Item,
		@LaunchNum,
		@Length,
		@Location,
		@ManifestCarrServiceSymbol,
		@ManifestCloseDateTime,
		@ManifestDateTime,
		@ManifestForDate,
		@ManifestId,
		@ManifestState,
		@Msn,
		@NmfcCode,
		isnull(@OriginalPickLoc,@Location),
		@PalletUmConversionIdentifier,
		@PalletUmConversionParentUm,
		@Parent,
		@ParentContainerId,
		@PlannedDeliveryDateTime,
		@ProcessStamp,
		@Quantity,
		@QuantityUm,
		@Status,
		@StatusFailed,
		@StatusFlowName,
		@TotalFreightCharge,
		@TrackingNumber,
		@TreeUnit,
		@UserDef1,
		@UserDef2,
		@UserDef3,
		@UserDef4,
		@UserDef5,
		@UserDef6,
		@UserDef7,
		@UserDef8,
		@UserStamp,
		@Value,
		@Volume,
		@VolumeUm,
		@Warehouse,
		@Weight,
		@WeightUm,
		@Width,
		@WorkCreated,
		@WorkZone,
		@Lot,
		0
	)

   IF (@TreeUnit IS NULL) 
      UPDATE shipping_container
         SET @InternalContainerNum = tree_unit = SCOPE_IDENTITY()
       WHERE internal_container_num = SCOPE_IDENTITY()
   ELSE   
      SELECT @InternalContainerNum = SCOPE_IDENTITY()

