-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */


















CREATE PROCEDURE RPT_YardVisibilityHdrDetails
(
	@paramwarehouse nvarchar(25)
)
AS
	BEGIN
			SELECT		
			COUNT(DISTINCT(D.DOCK_LOCATION)) N'<literal:1>', 
			COUNT(CASE WHEN T.TRAILER_ID IS NOT NULL THEN NULL ELSE N'<literal:2>' END) N'<literal:3>',			
			COUNT(DISTINCT(T.TRAILER_ID)) N'<literal:4>',			
			COUNT(DISTINCT(R.RECEIPT_ID)) N'<literal:5>',
			COUNT(L.ITEM) N'<literal:6>',
			SUM(L.TOTAL_QTY) N'<literal:7>'
	FROM (
			SELECT	DOCK_LOCATION 
			FROM	DOCK_LOCATION WITH (NOLOCK)
			WHERE	WAREHOUSE = @paramwarehouse 
			AND DOCK_LOCATION_AREA IN
			(	SELECT	IDENTIFIER 
				FROM	GENERIC_CONFIG_DETAIL WITH (NOLOCK)
				WHERE	RECORD_TYPE = N'<literal:8>' )
			)D
	LEFT OUTER JOIN TRAILER_YARD_STATUS T WITH (NOLOCK)
	ON	(D.DOCK_LOCATION = T.TRAILER_LOCATION)
	LEFT OUTER JOIN RECEIPT_HEADER R WITH (NOLOCK)
	ON T.TRAILER_ID = R.TRAILER_ID 
	LEFT OUTER JOIN APPOINTMENT_SCHEDULE A WITH (NOLOCK)
	ON R.INTERNAL_RECEIPT_NUM = A.INTERNAL_RECEIPT_NUM
	LEFT OUTER JOIN RECEIPT_DETAIL L WITH (NOLOCK)
	ON R.INTERNAL_RECEIPT_NUM = L.INTERNAL_RECEIPT_NUM
END


