-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
CREATE VIEW dbo.UPLOAD_ORDER_DETAIL_VIEW
AS
SELECT     ERP_ORDER, SHIPPED_QTY, INTERFACE_LINK_ID, INTERNAL_SHIPMENT_NUM, ITEM, ITEM_LIST_PRICE, ITEM_DESC, ITEM_SIZE, TOTAL_QTY, 
                      MARK_FOR_NAME, MARK_FOR_ADDRESS1, MARK_FOR_ADDRESS2, MARK_FOR_ADDRESS3, MARK_FOR_CITY, MARK_FOR_STATE, 
                      MARK_FOR_POSTAL_CODE, MARK_FOR_COUNTRY, INTERNAL_SHIPMENT_LINE_NUM, ITEM_CLASS
FROM         dbo.UPLOAD_ORDER_DETAIL
UNION
SELECT     ERP_ORDER, SHIPPED_QTY, INTERFACE_LINK_ID, INTERNAL_SHIPMENT_NUM, ITEM, ITEM_LIST_PRICE, ITEM_DESC, ITEM_SIZE, TOTAL_QTY, 
                      MARK_FOR_NAME, MARK_FOR_ADDRESS1, MARK_FOR_ADDRESS2, MARK_FOR_ADDRESS3, MARK_FOR_CITY, MARK_FOR_STATE, 
                      MARK_FOR_POSTAL_CODE, MARK_FOR_COUNTRY, INTERNAL_SHIPMENT_LINE_NUM, ITEM_CLASS
FROM         dbo.AR_UPLOAD_ORDER_DETAIL