-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */





CREATE PROCEDURE MetaTrans_GetReceiptFromPO(
@internalNum numeric(9),
@culture nvarchar(10))
AS
	SET NOCOUNT ON;

SELECT N'<literal:1>' AS N'<literal:2>',
	N'<literal:3>' AS N'<literal:4>',
	PURCHASE_ORDER_HEADER.OBJECT_ID AS N'<literal:5>', 
	PURCHASE_ORDER_HEADER.PURCHASE_ORDER_ID AS N'<literal:6>',
	N'<literal:7>' AS N'<literal:8>', 
	PURCHASE_ORDER_HEADER.SOURCE_ID AS N'<literal:9>', 
	PURCHASE_ORDER_HEADER.SOURCE_ATTENTION_TO AS N'<literal:10>', 
	PURCHASE_ORDER_HEADER.SOURCE_NAME AS N'<literal:11>', 
	PURCHASE_ORDER_HEADER.SOURCE_PHONE_NUM AS N'<literal:12>', 
	PURCHASE_ORDER_HEADER.SOURCE_ADDRESS1 AS N'<literal:13>', 
	PURCHASE_ORDER_HEADER.SOURCE_ADDRESS2 AS N'<literal:14>', 
	PURCHASE_ORDER_HEADER.SOURCE_ADDRESS3 AS N'<literal:15>', 
	PURCHASE_ORDER_HEADER.SOURCE_FAX_NUM AS N'<literal:16>', 
	PURCHASE_ORDER_HEADER.SOURCE_EMAIL_ADDRESS AS N'<literal:17>', 
	PURCHASE_ORDER_HEADER.SOURCE_CITY AS N'<literal:18>', 
	PURCHASE_ORDER_HEADER.SOURCE_STATE AS N'<literal:19>', 
	PURCHASE_ORDER_HEADER.SOURCE_COUNTRY AS N'<literal:20>', 
	PURCHASE_ORDER_HEADER.SOURCE_POSTAL_CODE AS N'<literal:21>', 
	PURCHASE_ORDER_HEADER.COMPANY AS N'<literal:22>',
	PURCHASE_ORDER_HEADER.Warehouse AS N'<literal:23>'

FROM PURCHASE_ORDER_HEADER
WHERE PURCHASE_ORDER_HEADER.OBJECT_ID = @internalNum;