-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */











CREATE procedure WRK_InsertWorkInstruction(
	@CycleCount nchar(1),
	@InventoryAtPd nchar(1),
	@InventoryTracking nchar(1),

	@AgingDateTime nvarchar(25),
	@DateTimeStamp nvarchar(25),
	@EndDateTime nvarchar(25),
	@StartDateTime nvarchar(25),

	@ConvertedQty numeric(19,5),
	@CycleCountGroupNum numeric(9),
	@ErpOrderLineNum numeric(19,5),
	@EstimatedTime numeric(9),
	@FromQty numeric(19,5),
	@InternalContainerNum numeric(9),
	@InternalCountNum numeric(9),
	@InternalLineNum numeric(9),
	@InternalNum numeric(9),
	@InternalReqNum numeric(9),
	@LaunchNum numeric(9),
	@NumberOfChildren numeric(9),
	@ParentContainerNum numeric(9),
	@Priority numeric(3),
	@Quantity numeric(19,5),
	@Sequence numeric(5),
	@ToQty numeric(19,5),
	@TotalValue numeric(28,5),
	@TotalVolume numeric(28,5),
	@TotalWeight numeric(28,5),
	@UserDef7 numeric(19,5),
	@UserDef8 numeric(19,5),

	@Account nvarchar(25),
	@AllocationZone nvarchar(25),
	@Company nvarchar(25),
	@CompletedByUser nvarchar(30),
	@Condition nvarchar(25),
	@ContainerId nvarchar(25),
	@ConvertedQtyUm nvarchar(25),
	@EquipmentLoc nvarchar(25),
	@ErpOrder nvarchar(25),
	@FromCheckDig nvarchar(25),
	@FromLoc nvarchar(25),
	@FromTemplField1 nvarchar(25),
	@FromTemplField2 nvarchar(25),
	@FromTemplField3 nvarchar(25),
	@FromTemplField4 nvarchar(25),
	@FromTemplField5 nvarchar(25),
	@FromWhs nvarchar(25),
	@FromWorkZone nvarchar(25),
	@GroupNum nvarchar(50),
	@HoldCode nvarchar(50),
	@IncomingPdLoc nvarchar(25),
	@InstructionType nvarchar(25),
	@InternalNumType nvarchar(25),
	@Item nvarchar(50),
	@ItemDesc nvarchar(100),
	@LocatingZone nvarchar(25),
	@Lot nvarchar(25),
	@MessageId nvarchar(25),
	@OutgoingPdLoc nvarchar(25),
	@ParentContainerId nvarchar(25),
	@PickListId nvarchar(25),
	@ProcessStamp nvarchar(100),
	@QuantityUm nvarchar(25),
	@ReferenceId nvarchar(25),
	@ReferenceType nvarchar(25),
	@RelatedWorkUnit nvarchar(50),
	@TeamAssigned nvarchar(50),
	@ToCheckDig nvarchar(25),
	@ToLoc nvarchar(25),
	@ToTemplField1 nvarchar(25),
	@ToTemplField2 nvarchar(25),
	@ToTemplField3 nvarchar(25),
	@ToTemplField4 nvarchar(25),
	@ToTemplField5 nvarchar(25),
	@ToWhs nvarchar(25),
	@ToWorkZone nvarchar(25),
	@TransportContId nvarchar(25),
	@UserAssigned nvarchar(30),
	@UserDef1 nvarchar(25),
	@UserDef2 nvarchar(25),
	@UserDef3 nvarchar(25),
	@UserDef4 nvarchar(25),
	@UserDef5 nvarchar(25),
	@UserDef6 nvarchar(25),
	@UserStamp nvarchar(30),
	@VolumeUm nvarchar(25),
	@WeightUm nvarchar(25),
	@WorkGroup nvarchar(25),
	@WorkType nvarchar(25),
	@workUnit nvarchar(50),
	@logisticsUnit nvarchar(50),
	@parentLogisticsUnit nvarchar(50),
	@treeUnit numeric(9),
	@treeUnitId nvarchar(25),
	@fromLocInvAttributesId numeric(9),
	@toLocInvAttributesId numeric(9),
	@SrcIdentifier nvarchar(50),
	@MinWorkZoneSeq numeric(4),
	@MaxWorkZoneSeq numeric(4))
as
	insert into work_instruction (

		cycle_count,
		inventory_at_pd,
		inventory_tracking,

		aging_date_time,
		date_time_stamp,
		end_date_time,
		start_date_time,

		converted_qty,
		cycle_count_group_num,
		erp_order_line_num,
		estimated_time,
		from_qty,
		internal_container_num,
		internal_count_num,
		internal_line_num,
		internal_num,
		internal_req_num,
		launch_num,
		number_of_children,
		parent_container_num,
		priority,
		quantity,
		sequence,
		to_qty,
		total_value,
		total_volume,
		total_weight,
		user_def7,
		user_def8,

		account,
		allocation_zone,
		company,
		completed_by_user,
		condition,
		container_id,
		converted_qty_um,
		equipment_loc,
		erp_order,
		from_check_dig,
		from_loc,
		from_templ_field1,
		from_templ_field2,
		from_templ_field3,
		from_templ_field4,
		from_templ_field5,
		from_whs,
		from_work_zone,
		group_num,
		hold_code,
		incoming_pd_loc,
		instruction_type,
		internal_num_type,
		item,
		item_desc,
		locating_zone,
		lot,
		message_id,
		outgoing_pd_loc,
		parent_container_id,
		pick_list_id,
		process_stamp,
		quantity_um,
		reference_id,
		reference_type,
		related_work_unit,
		team_assigned,
		to_check_dig,
		to_loc,
		to_templ_field1,
		to_templ_field2,
		to_templ_field3,
		to_templ_field4,
		to_templ_field5,
		to_whs,
		to_work_zone,
		transport_cont_id,
		user_assigned,
		user_def1,
		user_def2,
		user_def3,
		user_def4,
		user_def5,
		user_def6,
		user_stamp,
		volume_um,
		weight_um,
		work_group,
		work_type,
		work_unit,
		logistics_unit,
		parent_logistics_unit,
		tree_unit,
		tree_unit_id,
		from_loc_inv_attributes_id,
		to_loc_inv_attributes_id,
		src_identifier,
		min_work_zone_seq,
		max_work_zone_seq

		) values (

		@CycleCount,
		@InventoryAtPd,
		@InventoryTracking,

		case when @AgingDateTime is null then null else convert(datetime, @AgingDateTime, 20) end,
		case when @DateTimeStamp is null then null else convert(datetime, @DateTimeStamp, 20) end,
		case when @EndDateTime is null then null else convert(datetime, @EndDateTime, 20) end,
		case when @StartDateTime is null then null else convert(datetime, @StartDateTime, 20) end,

		@ConvertedQty,
		@CycleCountGroupNum,
		@ErpOrderLineNum,
		@EstimatedTime,
		@FromQty,
		@InternalContainerNum,
		case when @InternalCountnum > 0 then @InternalCountNum else null end,
		@InternalLineNum,
		@InternalNum,
		@InternalReqNum,
		@LaunchNum,
		@NumberOfChildren,
		@ParentContainerNum,
		@Priority,
		@Quantity,
		@Sequence,
		@ToQty,
		@TotalValue,
		@TotalVolume,
		@TotalWeight,
		@UserDef7,
		@UserDef8,

		@Account,
		@AllocationZone,
		@Company,
		@CompletedByUser,
		@Condition,
		@ContainerId,
		@ConvertedQtyUm,
		@EquipmentLoc,
		@ErpOrder,
		@FromCheckDig,
		@FromLoc,
		@FromTemplField1,
		@FromTemplField2,
		@FromTemplField3,
		@FromTemplField4,
		@FromTemplField5,
		@FromWhs,
		@FromWorkZone,
		@GroupNum,
		@HoldCode,
		@IncomingPdLoc,
		@InstructionType,
		@InternalNumType,
		@Item,
		@ItemDesc,
		@LocatingZone,
		@Lot,
		@MessageId,
		@OutgoingPdLoc,
		@ParentContainerId,
		@PickListId,
		@ProcessStamp,
		@QuantityUm,
		@ReferenceId,
		@ReferenceType,
		@RelatedWorkUnit,
		@TeamAssigned,
		@ToCheckDig,
		@ToLoc,
		@ToTemplField1,
		@ToTemplField2,
		@ToTemplField3,
		@ToTemplField4,
		@ToTemplField5,
		@ToWhs,
		@ToWorkZone,
		@TransportContId,
		@UserAssigned,
		@UserDef1,
		@UserDef2,
		@UserDef3,
		@UserDef4,
		@UserDef5,
		@UserDef6,
		@UserStamp,
		@VolumeUm,
		@WeightUm,
		@WorkGroup,
		@WorkType,
		@WorkUnit,
		@logisticsUnit,
		@parentLogisticsUnit,
		@treeUnit,
		@treeUnitId,
		case when @fromLocInvAttributesId > 0 then @fromLocInvAttributesId else null end,
		case when @toLocInvAttributesId > 0 then @toLocInvAttributesId else null end,
		@SrcIdentifier,
		@MinWorkZoneSeq,
		@MaxWorkZoneSeq)
