-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */






CREATE PROCEDURE MetaTrans_GetShipmentForCreateReceipt(
@internalShipmentNum numeric(9),
 @culture nvarchar(10))
AS
	SET NOCOUNT ON;

SELECT N'<literal:1>' AS N'<literal:2>',
	N'<literal:3>' AS N'<literal:4>',
	SHIPMENT_HEADER.INTERNAL_SHIPMENT_NUM AS N'<literal:5>', 
	SHIPMENT_HEADER.SHIPMENT_ID AS N'<literal:6>',
	SHIPMENT_HEADER.CARRIER AS N'<literal:7>',
	SHIPMENT_HEADER.CARRIER_SERVICE AS N'<literal:8>',	
	SHIPMENT_HEADER.COMPANY AS N'<literal:9>' ,
	SHIPMENT_HEADER.Warehouse AS N'<literal:10>' ,
	SHIPMENT_HEADER.SCHEDULED_SHIP_DATE AS N'<literal:11>' ,
	SHIPMENT_HEADER.CUSTOMER_NAME AS N'<literal:12>',
	SHIPMENT_HEADER.SHIP_TO AS N'<literal:13>',
	SHIPMENT_HEADER.SHIP_TO_NAME AS N'<literal:14>',
	SHIPMENT_HEADER.SHIP_TO_ADDRESS1 AS N'<literal:15>',
	SHIPMENT_HEADER.SHIP_TO_ADDRESS2 AS N'<literal:16>',
	SHIPMENT_HEADER.SHIP_TO_ADDRESS3 AS N'<literal:17>',
	SHIPMENT_HEADER.SHIP_TO_CITY AS N'<literal:18>',
	SHIPMENT_HEADER.SHIP_TO_STATE AS N'<literal:19>',
	SHIPMENT_HEADER.SHIP_TO_POSTAL_CODE AS N'<literal:20>',
	SHIPMENT_HEADER.SHIP_TO_COUNTRY AS N'<literal:21>',
	SHIPMENT_HEADER.ACTUAL_SHIP_DATE_TIME AS N'<literal:22>',
	SHIPMENT_HEADER.SHIP_TO_ATTENTION_TO AS N'<literal:23>', 
	SHIPMENT_HEADER.SHIP_TO_PHONE_NUM AS N'<literal:24>', 
	SHIPMENT_HEADER.SHIP_TO_FAX_NUM AS N'<literal:25>', 
	SHIPMENT_HEADER.SHIP_TO_EMAIL_ADDRESS AS N'<literal:26>'

FROM SHIPMENT_HEADER
WHERE SHIPMENT_HEADER.INTERNAL_SHIPMENT_NUM =@internalShipmentNum
