-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */





CREATE VIEW DOCUMENT_ROUTING_VIEW
AS
select 
INTERNAL_DOCUMENT_NUM,
DOCUMENT_TYPE,
WORK_TYPE,
SHIP_TO,
COMPANY,
CARRIER,
CARRIER_SERVICE,
CONTAINER_CLASS,
DOCUMENT,
NUMBER_OF_COPIES,
DEVICE_NAME,
USER_DEF1 AS UD_DOCUMENT_ROUTING1,
USER_DEF2 AS UD_DOCUMENT_ROUTING2,
USER_DEF3 AS UD_DOCUMENT_ROUTING3,
USER_DEF4 AS UD_DOCUMENT_ROUTING4,
USER_DEF5 AS UD_DOCUMENT_ROUTING5,
USER_DEF6 AS UD_DOCUMENT_ROUTING6,
USER_DEF7 AS UD_DOCUMENT_ROUTING7,
USER_DEF8 AS UD_DOCUMENT_ROUTING8,
USER_STAMP,
PROCESS_STAMP,
DATE_TIME_STAMP,
USER_NAME,
WAREHOUSE,
CUSTOMER,
RATING_ID,
COUNTRY,
MACHINE_NAME
FROM
DOCUMENT_ROUTING