-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */









CREATE PROCEDURE WRK_MonitorCustomerCategoryChartData
@filterCriteria NVARCHAR(MAX),
@culture NVARCHAR(10)
        
AS
    SET NOCOUNT ON
	DECLARE @warehouse as NVARCHAR(50);
	DECLARE @criteriaTempTable TABLE (
   filterName NVARCHAR(300),
   filterValue NVARCHAR(300))

 /* [comment omitted] */
  INSERT INTO @criteriaTempTable SELECT * FROM fn_GetMonitorFilterParameters(@filterCriteria)

  SELECT @warehouse = filterValue FROM @criteriaTempTable WHERE filterName = N'<literal:1>'


/* [comment omitted] */

SELECT N'<literal:2>' AS CHARTDATA_MonitorCustomerCategory, 
CATEGORY = CASE WHEN  WI_SH.CUST_CAT IS NULL THEN dbo.RSCMfn_RtrvResource(N'<literal:3>',N'<literal:4>',@culture) ELSE  WI_SH.CUST_CAT END,
COUNT(WI_SH.WORK_UNIT) AS N'<literal:5>' ,
DESCRIPTION = CASE WHEN  WI_SH.CUST_CAT IS NULL THEN NULL ELSE WI_SH.CUST_CAT END,
N'<literal:6>' AS XAXISTITLE, 
N'<literal:7>' AS YAXISTITLE, 
1 AS NextDrillDownLevel, 
N'<literal:8>' AS CHARTTITLE
FROM 
(
SELECT DISTINCT SH.CUSTOMER_CATEGORY1 AS N'<literal:9>',WI.WORK_UNIT AS N'<literal:10>' FROM WORK_INSTRUCTION WI
INNER JOIN SHIPMENT_HEADER SH ON WI.INTERNAL_NUM=SH.INTERNAL_SHIPMENT_NUM
 WHERE WI.INTERNAL_NUM_TYPE  IN (N'<literal:11>',N'<literal:12>') AND WI.condition <> N'<literal:13>'  AND (WI.FROM_WHS =@warehouse or WI.TO_WHS = @warehouse)
 ) WI_SH
GROUP BY WI_SH.CUST_CAT  
ORDER BY DATA DESC

/* [comment omitted] */

/* [comment omitted] */


DECLARE @TOTAL_WORKUNIT INT=0,@TOTAL_INTERNAL_INSTRUCTION_NUM INT=0,@TOTAL_ESTIMATED_TIME NUMERIC(9,0)=0, @OPEN_INTERNAL_INSTRUCTION_NUM INT, @INPROCESS_INTERNAL_INSTRUCTION_NUM INT, @CLOSED_INTERNAL_INSTRUCTION_NUM INT;

SELECT     @TOTAL_WORKUNIT = SUM(WORK.WORK_UNIT_COUNT),
		   @TOTAL_INTERNAL_INSTRUCTION_NUM =SUM(WORK.INSTRUCTION_NUMS_COUNT) ,
		   @TOTAL_ESTIMATED_TIME =ISNULL(SUM(WORK.ESTIMATED_TIMES), 0) , 
		   @OPEN_INTERNAL_INSTRUCTION_NUM = SUM(CASE WHEN WORK.CONDITION = N'<literal:14>' THEN WORK.INSTRUCTION_NUMS_COUNT ELSE 0 END), 
		   @INPROCESS_INTERNAL_INSTRUCTION_NUM = SUM(CASE WHEN WORK.CONDITION = N'<literal:15>' THEN WORK.INSTRUCTION_NUMS_COUNT ELSE 0 END)		   
FROM(
SELECT COUNT(DISTINCT WI.WORK_UNIT) AS N'<literal:16>',COUNT(INTERNAL_INSTRUCTION_NUM) AS INSTRUCTION_NUMS_COUNT,
ISNULL(SUM(WI.ESTIMATED_TIME), 0) AS ESTIMATED_TIMES, WI.CONDITION  FROM WORK_INSTRUCTION WI
INNER JOIN SHIPMENT_HEADER SH ON WI.INTERNAL_NUM=SH.INTERNAL_SHIPMENT_NUM
WHERE WI.INTERNAL_NUM_TYPE  IN (N'<literal:17>',N'<literal:18>') AND WI.CONDITION <> N'<literal:19>'
AND (WI.FROM_WHS =@warehouse or WI.TO_WHS = @warehouse)
GROUP BY CONDITION
)WORK

SELECT @CLOSED_INTERNAL_INSTRUCTION_NUM = COUNT(INTERNAL_INSTRUCTION_NUM)
	FROM WORK_INSTRUCTION_VIEW WI INNER JOIN SHIPMENT_HEADER SH ON WI.INTERNAL_NUM=SH.INTERNAL_SHIPMENT_NUM
    WHERE WI.INTERNAL_NUM_TYPE  IN (N'<literal:20>',N'<literal:21>') AND (WI.FROM_WHS =@warehouse or WI.TO_WHS = @warehouse)
    AND WI.CONDITION =N'<literal:22>'
	AND  WI.DATE_TIME_STAMP >=DATEADD(HOUR, -1, GETUTCDATE()) GROUP BY CONDITION

 
 SELECT TOP 1 N'<literal:23>' AS N'<literal:24>', @TOTAL_WORKUNIT AS N'<literal:25>';
 SELECT TOP 1 N'<literal:26>' AS N'<literal:27>', @TOTAL_INTERNAL_INSTRUCTION_NUM AS N'<literal:28>';
 SELECT TOP 1 N'<literal:29>' AS N'<literal:30>', @TOTAL_ESTIMATED_TIME AS N'<literal:31>';
 SELECT TOP 1 N'<literal:32>' AS N'<literal:33>', @OPEN_INTERNAL_INSTRUCTION_NUM AS N'<literal:34>' ;	
 SELECT TOP 1 N'<literal:35>' AS N'<literal:36>', @INPROCESS_INTERNAL_INSTRUCTION_NUM AS N'<literal:37>' ;
 SELECT TOP 1 N'<literal:38>' AS N'<literal:39>',  @CLOSED_INTERNAL_INSTRUCTION_NUM AS N'<literal:40>' ;

/* [comment omitted] */
   
                 
 IF @@ERROR <> 0 GOTO ERRORHANDLER
 SET NOCOUNT OFF
 RETURN(0)
  
ERRORHANDLER:
    RETURN(@@ERROR)
