-- DOCUMENTATION ONLY: literals/comments removed; do not execute.
/* [comment omitted] */




CREATE VIEW GENERIC_ADDRESS_DETAIL_VIEW
AS
SELECT
	IDENTIFIER AS ACCOUNTNUMBER,
	NAME,
	ADDRESS1,
	CITY,
	RECORD_TYPE,
	ACTIVE
	FROM GENERIC_ADDRESS_DETAIL;