
/*
	Task	| By	| Date		| Modification Description
	--------------------------------------------------------------------
	174114	| MHM	| 02/29/16	| Created
	176146	| MHM	| 03/09/16	| the columns is sorted with the largest columns on the left side.
	174914	| MHM	| 03/16/16	| Updated the correct filter name Ship_to.
    177398  | KSS   | 04/19/16  | Chnages made for customer , shipto to Customer_name and ship_to_name
	177492  | MHM   | 04/20/16  | Updated customer and ShipTo variable length.
	176298	| RJR	| 10/26/16	| Consider to_whs as well.
	219206	| MHM	| 02/16/18	| Modified Date to UTCDate.
*/

CREATE PROCEDURE WRK_MonitorCustomerWorkTypeChartData
@filterCriteria NVARCHAR(MAX),
@culture NVARCHAR(10)
        
AS
    SET NOCOUNT ON
	DECLARE @warehouse as NVARCHAR(50);
	DECLARE @customerCat1 as NVARCHAR(50);
	DECLARE @customer as NVARCHAR(50);
	DECLARE @shipTo as NVARCHAR(50);	
	DECLARE @workGroup as NVARCHAR(25);
  
	DECLARE @criteriaTempTable TABLE (
   filterName NVARCHAR(300),
   filterValue NVARCHAR(300))

 /*get the where clause value*/
  INSERT INTO @criteriaTempTable SELECT * FROM fn_GetMonitorFilterParameters(@filterCriteria)

  SELECT @warehouse = filterValue FROM @criteriaTempTable WHERE filterName = N'FROM_WHS'
  SELECT @customerCat1 = filterValue from @criteriaTempTable WHERE filterName = N'customer_Category1'
  SELECT @customer = filterValue from @criteriaTempTable WHERE filterName = N'customer_name'
  SELECT @shipTo = filterValue from @criteriaTempTable WHERE filterName = N'ship_to_name'
  SELECT @workGroup = filterValue from @criteriaTempTable WHERE filterName = N'work_group'
  DECLARE @Unassign NVARCHAR(2000);
  SET @Unassign=  dbo.RSCMfn_RtrvResource(N'UNASSIGNED',N'text',@culture)

   IF(@customerCat1 = @Unassign)
	SET @customerCat1 = NULL;

  IF(@customer = @Unassign)
	SET @customer = NULL;

  IF(@shipTo = @Unassign)
	SET @shipTo = NULL;

  IF(@workGroup = @Unassign)
	SET @workGroup = NULL; 


/* CHART START */

SELECT N'CHARTDATA_MonitorCustomerCategory' AS CHARTDATA_MonitorCustomerCategory, 
CATEGORY = CASE WHEN  WI_SH.WORK_TYPE IS NULL THEN @Unassign ELSE  WI_SH.WORK_TYPE END,
COUNT(WI_SH.WORK_UNIT) AS N'DATA',
DESCRIPTION = CASE WHEN  WI_SH.WORK_TYPE IS NULL THEN @Unassign ELSE WI_SH.WORK_TYPE END,
N'WORKTYPE' AS XAXISTITLE, 
N'WORKUNITS' AS YAXISTITLE, 
-1 AS NextDrillDownLevel,    ---1 set for the last drilldown
N'OPENWORKBYWORKTYPE' AS CHARTTITLE
FROM 
(
SELECT DISTINCT WI.WORK_TYPE as N'WORK_TYPE',WI.WORK_UNIT AS N'WORK_UNIT',WI.INTERNAL_NUM AS N'INTERNAL_NUM'
FROM WORK_INSTRUCTION WI
INNER JOIN SHIPMENT_HEADER SH ON WI.INTERNAL_NUM=SH.INTERNAL_SHIPMENT_NUM
 WHERE WI.INTERNAL_NUM_TYPE  IN (N'SHIPMENT',N'DOCK MANAGEMENT')  AND WI.condition <> N'Closed' AND (WI.FROM_WHS = @warehouse or WI.TO_WHS = @warehouse)
 AND ((@customerCat1 IS NULL AND SH.CUSTOMER_CATEGORY1 IS NULL) OR SH.CUSTOMER_CATEGORY1 =@customerCat1)   -- DRILL DOWN-1 CRITERIA
 AND ((@customer IS NULL AND SH.CUSTOMER_NAME IS NULL) OR SH.CUSTOMER_NAME =@customer)   --drill down 2
 AND ((@shipTo IS NULL AND SH.SHIP_TO_NAME IS NULL) OR SH.SHIP_TO_NAME =@shipTo)   --drill down 3 
 AND ((@workGroup IS NULL AND WI.WORK_GROUP IS NULL) OR WI.WORK_GROUP =@workGroup)
 ) WI_SH
GROUP BY WI_SH.WORK_TYPE  
ORDER BY DATA DESC

/* CHART END */

/* SUMMARY TILES START */


DECLARE @TOTAL_WORKUNIT INT=0,@TOTAL_INTERNAL_INSTRUCTION_NUM INT=0,@TOTAL_ESTIMATED_TIME NUMERIC(9,0)=0, @OPEN_INTERNAL_INSTRUCTION_NUM INT, @INPROCESS_INTERNAL_INSTRUCTION_NUM INT, @CLOSED_INTERNAL_INSTRUCTION_NUM INT;

SELECT  @TOTAL_WORKUNIT = SUM(WORK.WORK_UNIT_COUNT),
		   @TOTAL_INTERNAL_INSTRUCTION_NUM =SUM(WORK.INSTRUCTION_NUMS_COUNT) ,
		   @TOTAL_ESTIMATED_TIME =ISNULL(SUM(WORK.ESTIMATED_TIMES), 0) , 
		   @OPEN_INTERNAL_INSTRUCTION_NUM = SUM(CASE WHEN WORK.CONDITION = N'OPEN' THEN WORK.INSTRUCTION_NUMS_COUNT ELSE 0 END), 
		   @INPROCESS_INTERNAL_INSTRUCTION_NUM = SUM(CASE WHEN WORK.CONDITION = N'IN PROCESS' THEN WORK.INSTRUCTION_NUMS_COUNT ELSE 0 END)		   
FROM(
SELECT COUNT(DISTINCT WI.WORK_UNIT) AS WORK_UNIT_COUNT,COUNT(INTERNAL_INSTRUCTION_NUM) AS INSTRUCTION_NUMS_COUNT,ISNULL(SUM(WI.ESTIMATED_TIME), 0) AS ESTIMATED_TIMES,WI.CONDITION 
FROM WORK_INSTRUCTION WI INNER JOIN SHIPMENT_HEADER SH ON WI.INTERNAL_NUM=SH.INTERNAL_SHIPMENT_NUM
WHERE WI.INTERNAL_NUM_TYPE  IN (N'SHIPMENT',N'DOCK MANAGEMENT') AND WI.condition <> N'Closed' AND (WI.FROM_WHS =@warehouse or WI.TO_WHS = @warehouse)
AND ((@customerCat1 IS NULL AND SH.CUSTOMER_CATEGORY1 IS NULL) OR SH.CUSTOMER_CATEGORY1 =@customerCat1)   -- DRILL DOWN-1 CRITERIA
AND ((@customer IS NULL AND SH.CUSTOMER_NAME IS NULL) OR SH.CUSTOMER_NAME =@customer)    --drill down 2
AND ((@shipTo IS NULL AND SH.SHIP_TO_NAME IS NULL) OR SH.SHIP_TO_NAME =@shipTo)    --drill down 3
AND ((@workGroup IS NULL AND WI.WORK_GROUP IS NULL) OR WI.WORK_GROUP =@workGroup)
GROUP BY CONDITION
)WORK

SELECT @CLOSED_INTERNAL_INSTRUCTION_NUM = COUNT(INTERNAL_INSTRUCTION_NUM)
	FROM WORK_INSTRUCTION_VIEW WI INNER JOIN SHIPMENT_HEADER SH ON WI.INTERNAL_NUM=SH.INTERNAL_SHIPMENT_NUM
    WHERE WI.INTERNAL_NUM_TYPE  IN (N'SHIPMENT',N'DOCK MANAGEMENT') AND  (WI.FROM_WHS =@warehouse or WI.TO_WHS = @warehouse)  --DEFAULT CRITERIA
	AND ((@customerCat1 IS NULL AND SH.CUSTOMER_CATEGORY1 IS NULL) OR SH.CUSTOMER_CATEGORY1 =@customerCat1)   -- DRILL DOWN-1 CRITERIA
	AND ((@customer IS NULL AND SH.CUSTOMER_NAME IS NULL) OR SH.CUSTOMER_NAME =@customer)    --drill down 2
	AND ((@shipTo IS NULL AND SH.SHIP_TO_NAME IS NULL) OR SH.SHIP_TO_NAME =@shipTo)          --drill down 3
    AND ((@workGroup IS NULL AND WI.WORK_GROUP IS NULL) OR WI.WORK_GROUP =@workGroup)
    AND WI.CONDITION =N'CLOSED'
	AND  WI.DATE_TIME_STAMP >=DATEADD(HOUR, -1, GETUTCDATE()) GROUP BY CONDITION
 
 SELECT TOP 1 N'SUMMARYTILE_TOTALWORKUNITS' AS N'SUMMARYTILE_TOTALWORKUNITS', @TOTAL_WORKUNIT AS N'TOTAL_WORK_UNITS';
 SELECT TOP 1 N'SUMMARYTILE_TOTALWORKINST' AS N'SUMMARYTILE_TOTALWORKINST', @TOTAL_INTERNAL_INSTRUCTION_NUM AS N'TOTAL_WORK_INST';
 SELECT TOP 1 N'SUMMARYTILE_TOTALESTIMATEDTIME' AS N'SUMMARYTILE_TOTALESTIMATEDTIME', @TOTAL_ESTIMATED_TIME AS N'TOTAL_ESTIMATED_TIME';
 SELECT TOP 1 N'SUMMARYTILE_OPEN' AS N'SUMMARYTILE_OPEN', @OPEN_INTERNAL_INSTRUCTION_NUM AS N'OPEN_WORK' ;	
 SELECT TOP 1 N'SUMMARYTILE_INPROCESS_WORK' AS N'SUMMARYTILE_INPROCESS_WORK', @INPROCESS_INTERNAL_INSTRUCTION_NUM AS N'INPROCESS_WORK' ;
 SELECT TOP 1 N'SUMMARYTILE_CLOSED_WORK' AS N'SUMMARYTILE_CLOSED_WORK',  @CLOSED_INTERNAL_INSTRUCTION_NUM AS N'CLOSED_WORK' ;

/*  SUMMARY TILES END  */
   
                 
 IF @@ERROR <> 0 GOTO ERRORHANDLER
 SET NOCOUNT OFF
 RETURN(0)
  
ERRORHANDLER:
    RETURN(@@ERROR)
