/*
	Task	| By	| Date		| Modification Description
	--------------------------------------------------------------------
	169654	| KSS	| 12/14/15	| Created
	170980  | KSS   |01/09/16   | Added code to get Description
	170631  | KSS   |02/09/16   | Added code to get Chart Title
	172358  | KSS   |03/02/16   | Changes made as per customer comment
	144977  | KSS   |03/06/16   | Made the count consistent in monitoring scrren and Insight screen
	176146	| MHM	|03/09/16	| the columns is sorted with the largest columns on the left side.
	219206	| MHM	| 02/16/18	| Modified Date to UTCDate.  
	    
*/
CREATE Procedure WRK_MonitorWorkTypeChartData
@filterCriteria nVarchar(MAX),
@culture nvarchar(10)
        
AS
    Set NoCount ON
	DECLARE @warehouse as nVarchar(50);
	DECLARE @workGroup as nVarchar(50);
	DECLARE @criteriaTempTable TABLE (
   filterName nVarchar(300),
   filterValue nVarchar(300))


 /*get the where clause value*/
  INSERT INTO @criteriaTempTable SELECT * FROM fn_GetMonitorFilterParameters(@filterCriteria)


  SELECT @warehouse = filterValue from @criteriaTempTable WHERE filterName = N'FROM_WHS'
  SELECT @workGroup = filterValue from @criteriaTempTable WHERE filterName = N'WORK_GROUP'

  IF(@workGroup =N'Unassigned')
	SET @workGroup = NULL;
 	
  SELECT N'CHARTDATA_MonitorWorkType' AS CHARTDATA_MonitorWorkType, CATEGORY = CASE WHEN  WORK_INSTRUCTION.WORK_TYPE IS NULL THEN dbo.RSCMfn_RtrvResource(N'UNASSIGNED',N'text',@culture) ELSE  WORK_INSTRUCTION.WORK_TYPE END,
												COUNT(DISTINCT WORK_INSTRUCTION.WORK_UNIT) AS DATA, 
												DESCRIPTION = CASE WHEN  WORK_INSTRUCTION.WORK_TYPE IS NULL THEN NULL ELSE  WORK_TYPE.DESCRIPTION END,
												N'WORKTYPE' AS XAXISTITLE, N'WORKUNITS' AS YAXISTITLE, 2 AS NextDrillDownLevel, N'OPENWORKBYWORKTYPE' AS CHARTTITLE FROM WORK_INSTRUCTION LEFT OUTER JOIN WORK_TYPE ON WORK_TYPE.WORK_TYPE = WORK_INSTRUCTION.WORK_TYPE
  WHERE (WORK_INSTRUCTION.FROM_WHS =@warehouse OR WORK_INSTRUCTION.TO_WHS=@warehouse )
   AND ((@workGroup IS NULL AND WORK_INSTRUCTION.WORK_GROUP IS NULL) OR WORK_INSTRUCTION.WORK_GROUP =@workGroup) 
   AND WORK_INSTRUCTION.CONDITION != N'CLOSED' AND WORK_INSTRUCTION.INSTRUCTION_TYPE =N'DETAIL' GROUP BY WORK_INSTRUCTION.WORK_TYPE, WORk_TYPE.DESCRIPTION
   ORDER BY DATA DESC

   



   /* Summary Tiles Start */

 DECLARE @TOTAL_WORKUNIT INT=0,@TOTAL_INTERNAL_INSTRUCTION_NUM INT=0,@TOTAL_ESTIMATED_TIME NUMERIC(9,0)=0, @OPEN_INTERNAL_INSTRUCTION_NUM INT, @INPROCESS_INTERNAL_INSTRUCTION_NUM INT, @CLOSED_INTERNAL_INSTRUCTION_NUM INT;

   SELECT  @TOTAL_WORKUNIT = SUM(WORK.WORK_UNIT_COUNT),
		   @TOTAL_INTERNAL_INSTRUCTION_NUM =SUM(WORK.INSTRUCTION_NUMS_COUNT) ,
		   @TOTAL_ESTIMATED_TIME =ISNULL(SUM(WORK.ESTIMATED_TIMES), 0) , 
		   @OPEN_INTERNAL_INSTRUCTION_NUM = SUM(CASE WHEN WORK.CONDITION = N'OPEN' THEN WORK.INSTRUCTION_NUMS_COUNT ELSE 0 END), 
		   @INPROCESS_INTERNAL_INSTRUCTION_NUM = SUM(CASE WHEN WORK.CONDITION = N'IN PROCESS' THEN WORK.INSTRUCTION_NUMS_COUNT ELSE 0 END)
	FROM(
		SELECT COUNT(DISTINCT WORK_UNIT) AS WORK_UNIT_COUNT, COUNT(INTERNAL_INSTRUCTION_NUM) AS INSTRUCTION_NUMS_COUNT, ISNULL(SUM(ESTIMATED_TIME), 0) AS ESTIMATED_TIMES, CONDITION FROM WORK_INSTRUCTION WHERE
			INSTRUCTION_TYPE =  N'DETAIL'  AND WORK_INSTRUCTION.CONDITION != N'CLOSED' AND (FROM_WHS =@WAREHOUSE OR TO_WHS=@warehouse  ) AND  ((@workGroup IS NULL AND WORK_GROUP IS NULL) OR WORK_GROUP =@workGroup)  GROUP BY CONDITION
			)WORK

	SELECT @CLOSED_INTERNAL_INSTRUCTION_NUM = COUNT(INTERNAL_INSTRUCTION_NUM)
	FROM WORK_INSTRUCTION_VIEW
		 WHERE  INSTRUCTION_TYPE =  N'DETAIL'  AND (FROM_WHS =@warehouse OR TO_WHS=@warehouse ) AND
		 ((@workGroup IS NULL AND WORK_GROUP IS NULL) OR WORK_GROUP =@workGroup)	  
		  AND CONDITION =N'CLOSED'
		  AND  DATE_TIME_STAMP >=DATEADD(HOUR, -1, GETUTCDATE())

   
   SELECT top 1 N'SUMMARYTILE_TOTALWORKUNITS' AS N'SUMMARYTILE_TOTALWORKUNITS', @TOTAL_WORKUNIT AS N'TOTAL_WORK_UNITS';
   SELECT top 1 N'SUMMARYTILE_TOTALWORKINST' AS N'SUMMARYTILE_TOTALWORKINST', @TOTAL_INTERNAL_INSTRUCTION_NUM AS N'TOTAL_WORK_INST';
   SELECT top 1 N'SUMMARYTILE_TOTALESTIMATEDTIME' AS N'SUMMARYTILE_TOTALESTIMATEDTIME', @TOTAL_ESTIMATED_TIME AS N'TOTAL_ESTIMATED_TIME';
   SELECT top 1 N'SUMMARYTILE_OPEN' AS N'SUMMARYTILE_OPEN', @OPEN_INTERNAL_INSTRUCTION_NUM AS N'OPEN_WORK' ;	
   SELECT top 1 N'SUMMARYTILE_INPROCESS_WORK' AS N'SUMMARYTILE_INPROCESS_WORK', @INPROCESS_INTERNAL_INSTRUCTION_NUM AS N'INPROCESS_WORK' ;
   SELECT top 1 N'SUMMARYTILE_CLOSED_WORK' AS N'SUMMARYTILE_CLOSED_WORK',  @CLOSED_INTERNAL_INSTRUCTION_NUM AS N'CLOSED_WORK' ;
   
   /* Summary Tiles End */       

    If @@ERROR <> 0 GoTo ErrorHandler
    Set NoCount OFF
    Return(0)
  
ErrorHandler:
    Return(@@ERROR)