/*
	Task	| By	| Date		| Modification Description
	--------------------------------------------------------------------
	16277	| KMD	| 04/25/05	| Merged oracle and Sql server versions.
	16277	| KMD	| 04/25/05	| Made internal_location_inv available as object_id for SN retrieval
	16241	| VK	| 07/29/05	| Modified to make all uploads consistent
	139895  | JY    |03/25/14   | Selected LOC_INV_ATTRIBUTES_ID too in final results.
	217198	| SHS	| 01/17/18	| Modified to add filter criteria.
	220776	| SO	| 04/18/18	| Modified to pass warehouse as parameter.
	221909	| SO	| 05/08/18	| Modified to improve performance of filter statement.
	259819	| MGK	| 11/09/20	| Modified to Add Order by statement
*/

CREATE PROCEDURE wm_RInventory01(@filterCriteriaName nvarchar(25),@filterWarehouse nvarchar(25))
AS
	DECLARE @filterCriteria nvarchar(max);
	DECLARE @filterStatement nvarchar(max);
	DECLARE @SQLString nvarchar(max);
	DECLARE @warehouseDate datetime;

	SELECT @warehouseDate = dbo.GetWarehouseTimezoneValue( @filterWarehouse,null);

	IF (@filterCriteriaName IS NOT NULL AND @filterCriteriaName <> N'')
	BEGIN
		SET @filterStatement = (SELECT FILTER_STATEMENT FROM FILTER_CONFIG_DETAIL WHERE FILTER_NAME = @filterCriteriaName and record_type = N'ITEMBALINTUPLOADCRIT')
		--fetch only where condition
		SET @filterCriteria = (SELECT SUBSTRING(@filterStatement, CHARINDEX(N'WHERE', @filterStatement)+5, LEN(@filterStatement)))
	END

	SET @SQLString = N'
	SELECT 
	LOCATION_INVENTORY.INTERNAL_LOCATION_INV,
	LOCATION_INVENTORY.ALLOCATED_QTY,
	LOCATION_INVENTORY.IN_TRANSIT_QTY,
	LOCATION_INVENTORY.ON_HAND_QTY,
	LOCATION_INVENTORY.SUSPENSE_QTY,
	LOCATION_INVENTORY.TOTAL_COST,
	LOCATION_INVENTORY.TOTAL_VALUE,
	LOCATION_INVENTORY.TOTAL_VOLUME,
	LOCATION_INVENTORY.TOTAL_WEIGHT,
	LOCATION_INVENTORY.ITEM,
	LOCATION_INVENTORY.COMPANY,
	LOCATION_INVENTORY.ITEM_COLOR,
	LOCATION_INVENTORY.ITEM_DESC,
	LOCATION_INVENTORY.ITEM_SIZE,
	LOCATION_INVENTORY.ITEM_STYLE,
	LOCATION_INVENTORY.USER_DEF1,
	LOCATION_INVENTORY.USER_DEF2,
	LOCATION_INVENTORY.USER_DEF3,
	LOCATION_INVENTORY.USER_DEF4,
	LOCATION_INVENTORY.USER_DEF5,
	LOCATION_INVENTORY.USER_DEF6,
	LOCATION_INVENTORY.USER_DEF7,
	LOCATION_INVENTORY.USER_DEF8,
	LOCATION_INVENTORY.USER_STAMP,
	LOCATION_INVENTORY.WAREHOUSE,
	LOCATION_INVENTORY.LOCATION_TEMPLATE,       
	LOCATION_INVENTORY.TEMPLATE_FIELD1,         
	LOCATION_INVENTORY.TEMPLATE_FIELD2,         
	LOCATION_INVENTORY.TEMPLATE_FIELD3,         
	LOCATION_INVENTORY.TEMPLATE_FIELD4,         
	LOCATION_INVENTORY.TEMPLATE_FIELD5,         
	LOCATION_INVENTORY.PERMANENT,               
	LOCATION_INVENTORY.LOT,                     
	LOCATION_INVENTORY.QUANTITY_UM,             
	LOCATION_INVENTORY.INVENTORY_STS,           
	LOCATION_INVENTORY.AGING_DATE,              
	LOCATION_INVENTORY.EXPIRATION_DATE,         
	LOCATION_INVENTORY.MANUFACTURED_DATE,       
	LOCATION_INVENTORY.RECEIVED_DATE,           
	LOCATION_INVENTORY.VOLUME_UM,               
	LOCATION_INVENTORY.PROCESS_STAMP,           
	GETUTCDATE() AS DATE_TIME_STAMP,         
	LOCATION_INVENTORY.WEIGHT_UM,               
	LOCATION_INVENTORY.LOCATION, 
	LOCATION_INVENTORY.INTERNAL_LOCATION_INV AS OBJECT_ID,
	LOCATION_INVENTORY.LOC_INV_ATTRIBUTES_ID,    
    CWI.CATCH_WEIGHT,    
    CWI.WEIGHT_UM AS CATCH_WEIGHT_UM    
    FROM LOCATION_INVENTORY    
   LEFT JOIN CATCH_WEIGHT_INFORMATION CWI    
        ON CWI.INTERNAL_LOCATION_INV = LOCATION_INVENTORY.INTERNAL_LOCATION_INV'

	IF (@filterCriteria IS NOT NULL AND @filterCriteria <> N'')
		BEGIN
			SET @SQLString = @SQLString + N' LEFT JOIN LOCATION_INVENTORY_ATTRIBUTES ON LOCATION_INVENTORY.LOC_INV_ATTRIBUTES_ID = LOCATION_INVENTORY_ATTRIBUTES.OBJECT_ID
											LEFT JOIN LOCATION ON LOCATION_INVENTORY.LOCATION = LOCATION.LOCATION AND LOCATION_INVENTORY.WAREHOUSE = LOCATION.WAREHOUSE ';
		END	 

	SET @SQLString = @SQLString + N' 
	WHERE NOT EXISTS (
		SELECT ''X''
		FROM GENERIC_CONFIG_DETAIL CFG, LOCATION LOC
		WHERE LOCATION_INVENTORY.LOCATION = LOC.LOCATION
		AND LOCATION_INVENTORY.WAREHOUSE = LOC.WAREHOUSE
		AND CFG.RECORD_TYPE = ''LOCCLASS''
		AND CFG.IDENTIFIER = LOC.LOCATION_CLASS
		AND SYS1VALUE = ''N'')
	AND (
		(ALLOCATED_QTY IS NOT NULL AND ALLOCATED_QTY != 0)
		OR (ON_HAND_QTY IS NOT NULL AND ON_HAND_QTY != 0)
		OR (IN_TRANSIT_QTY IS NOT NULL AND IN_TRANSIT_QTY != 0)
		OR (SUSPENSE_QTY IS NOT NULL AND SUSPENSE_QTY != 0)) ';


		IF (@filterCriteria IS NOT NULL AND @filterCriteria <> N'')
		BEGIN
			SET @SQLString = @SQLString + N' AND ( ' + @filterCriteria + N' )  ';
		END
		SET @SQLString = @SQLString + N'
		ORDER BY INTERNAL_LOCATION_INV ;';
		EXECUTE sp_executesql @SQLString, N'@WarehouseDate DATETIME',@WarehouseDate = @warehouseDate