/*
	Task	| By	| Date		| Modification Description
	--------------------------------------------------------------------
	16175	| MD	| 02/03/05	| Modified and merged oracle and Sql server versions.
	16277	| KMD	| 04/25/05	| Made internal_location_inv available as object_id for SN retrieval
	16241	| VK	| 07/26/05	| Modified to retrieve all columns from location inventory
	188720	| SHS	| 10/13/16	| Modified to include location inventory attributes id
	217198	| SHS	| 01/17/18	| Modified to add filter criteria
	220776	| SO	| 04/18/18	| Modified to pass warehouse as parameter.
	221909	| SO	| 05/08/18	| Modified to improve performance of filter statement.
*/

CREATE PROCEDURE wm_RInventory02(@filterCriteriaName nvarchar(25),@filterWarehouse nvarchar(25))
AS 
 DECLARE @filterCriteria nvarchar(max);  
 DECLARE @filterStatement nvarchar(max);  
 DECLARE @SQLString nvarchar(max);   
 DECLARE @WarehouseDate datetime;  
  
	SELECT @WarehouseDate = dbo.GetWarehouseTimezoneValue( @filterWarehouse,null);
	IF (@filterCriteriaName IS NOT NULL AND @filterCriteriaName <> N'')
	BEGIN
		SET @filterStatement = (SELECT FILTER_STATEMENT FROM FILTER_CONFIG_DETAIL WHERE FILTER_NAME = @filterCriteriaName and record_type = N'ITEMBALINTUPLOADCRIT')
		--fetch only where condition
		SET @filterCriteria = (SELECT SUBSTRING(@filterStatement, CHARINDEX(N'WHERE', @filterStatement)+5, LEN(@filterStatement)))
	END 
  
 SET @SQLString = N'  
  SELECT  LOCATION_INVENTORY.INTERNAL_LOCATION_INV AS OBJECT_ID,     
  ALLOCATED_QTY,      
  IN_TRANSIT_QTY,      
  ON_HAND_QTY,      
  SUSPENSE_QTY,      
  TOTAL_COST,      
  TOTAL_VALUE,      
  TOTAL_VOLUME,      
  TOTAL_WEIGHT,      
  ITEM,      
  COMPANY,      
  ITEM_COLOR,      
  ITEM_DESC,      
  ITEM_SIZE,      
  ITEM_STYLE,      
  LOCATION_INVENTORY.USER_DEF1,      
  LOCATION_INVENTORY.USER_DEF2,      
  LOCATION_INVENTORY.USER_DEF3,      
  LOCATION_INVENTORY.USER_DEF4,      
  LOCATION_INVENTORY.USER_DEF5,      
  LOCATION_INVENTORY.USER_DEF6,      
  LOCATION_INVENTORY.USER_DEF7,      
  LOCATION_INVENTORY.USER_DEF8,      
  LOCATION_INVENTORY.USER_STAMP,    
   LOCATION_INVENTORY.WAREHOUSE,      
   LOCATION_INVENTORY.LOCATION_TEMPLATE,     
   LOCATION_INVENTORY.TEMPLATE_FIELD1,       
   LOCATION_INVENTORY.TEMPLATE_FIELD2,       
   LOCATION_INVENTORY.TEMPLATE_FIELD3,       
   LOCATION_INVENTORY.TEMPLATE_FIELD4,       
   LOCATION_INVENTORY.TEMPLATE_FIELD5,       
   PERMANENT,      
   LOT,           
   QUANTITY_UM,           
   INVENTORY_STS,         
   AGING_DATE,   
    EXPIRATION_DATE,       
    MANUFACTURED_DATE,     
    RECEIVED_DATE,    
    VOLUME_UM,    
    LOCATION_INVENTORY.PROCESS_STAMP,    
    GETUTCDATE() AS DATE_TIME_STAMP,       
    LOCATION_INVENTORY.WEIGHT_UM,     
    LOCATION_INVENTORY.LOCATION ,      
    LOC_INV_ATTRIBUTES_ID,
	CWI.CATCH_WEIGHT,    
    CWI.WEIGHT_UM AS CATCH_WEIGHT_UM    
    FROM LOCATION_INVENTORY    
    LEFT JOIN CATCH_WEIGHT_INFORMATION CWI    
    ON CWI.INTERNAL_LOCATION_INV = LOCATION_INVENTORY.INTERNAL_LOCATION_INV '  
  
    IF (@filterCriteria IS NOT NULL AND @filterCriteria <> N'')
	BEGIN
		SET @SQLString = @SQLString + N' LEFT JOIN LOCATION ON LOCATION_INVENTORY.LOCATION = LOCATION.LOCATION AND LOCATION_INVENTORY.WAREHOUSE = LOCATION.WAREHOUSE
										LEFT JOIN LOCATION_INVENTORY_ATTRIBUTES ON LOCATION_INVENTORY.LOC_INV_ATTRIBUTES_ID = LOCATION_INVENTORY_ATTRIBUTES.OBJECT_ID  ';
	END

   SET @SQLString = @SQLString + N'   
 WHERE NOT EXISTS (    
  SELECT N''X''    
  FROM GENERIC_CONFIG_DETAIL CFG, LOCATION LOC    
  WHERE LOCATION_INVENTORY.LOCATION = LOC.LOCATION    
  AND LOCATION_INVENTORY.WAREHOUSE = LOC.WAREHOUSE    
  AND CFG.RECORD_TYPE = N''LOCCLASS''    
  AND CFG.IDENTIFIER = LOC.LOCATION_CLASS    
  AND SYS1VALUE = N''N'')    
 AND (    
  (LOCATION_INVENTORY.ALLOCATED_QTY IS NOT NULL AND ALLOCATED_QTY != 0)    
  OR (ON_HAND_QTY IS NOT NULL AND ON_HAND_QTY != 0)    
  OR (IN_TRANSIT_QTY IS NOT NULL AND IN_TRANSIT_QTY != 0)    
  OR (SUSPENSE_QTY IS NOT NULL AND SUSPENSE_QTY != 0)) '  
  
   IF (@filterCriteria IS NOT NULL AND @filterCriteria <> N'')
	BEGIN
		SET @SQLString = @SQLString + N' AND ( ' + @filterCriteria + N' )  ';
	END


 SET @SQLString = @SQLString + N'  
 UNION ALL

 SELECT    0 AS OBJECT_ID,      
 0 AS ALLOCATED_QTY,      
 0 AS IN_TRANSIT_QTY,      
 0 AS ON_HAND_QTY,      
 0 AS SUSPENSE_QTY,     
 0 AS TOTAL_COST,      
 0 AS TOTAL_VALUE,      
 0 AS TOTAL_VOLUME,      
 0 AS TOTAL_WEIGHT,     
 I.ITEM AS ITEM,      
 I.COMPANY AS COMPANY,      
 I.ITEM_COLOR AS ITEM_COLOR,      
 I.DESCRIPTION AS ITEM_DESC,      
 I.ITEM_SIZE AS ITEM_SIZE,      
 I.ITEM_STYLE AS ITEM_STYLE,      
 I.USER_DEF1 AS USER_DEF1,      
 I.USER_DEF2 AS USER_DEF2,      
 I.USER_DEF3 AS USER_DEF3,      
 I.USER_DEF4 AS USER_DEF4,      
 I.USER_DEF5 AS USER_DEF5,      
 I.USER_DEF6 AS USER_DEF6,      
 I.USER_DEF7 AS USER_DEF7,      
 I.USER_DEF8 AS USER_DEF8,      
 I.USER_STAMP AS USER_STAMP,      
 W.WAREHOUSE AS WAREHOUSE,  
 NULL AS  LOCATION_TEMPLATE,   
 NULL AS  TEMPLATE_FIELD1,  
 NULL AS     TEMPLATE_FIELD2,  
 NULL AS     TEMPLATE_FIELD3,  
 NULL AS     TEMPLATE_FIELD4,  
 NULL AS     TEMPLATE_FIELD5,  
 NULL AS     PERMANENT,  
 NULL AS           LOT,  
 NULL AS         QUANTITY_UM,  
 NULL AS         INVENTORY_STS,  
 NULL AS       AGING_DATE,      
  NULL AS EXPIRATION_DATE,  
  NULL AS     MANUFACTURED_DATE,  
  NULL AS   RECEIVED_DATE,  
  NULL AS       VOLUME_UM,  
  NULL AS           PROCESS_STAMP,         
  GETUTCDATE() AS DATE_TIME_STAMP,  
  NULL AS     WEIGHT_UM,  
  NULL AS           LOCATION ,  
  NULL AS    LOC_INV_ATTRIBUTES_ID,
  NULL AS CATCH_WEIGHT,  
  NULL AS CATCH_WEIGHT_UM 
FROM ITEM I, WAREHOUSE W    
 WHERE NOT EXISTS (    
  SELECT N''X''    
  FROM LOCATION_INVENTORY   
  WHERE NOT EXISTS (    
   SELECT N''X''    
   FROM GENERIC_CONFIG_DETAIL CFG, LOCATION LOC    
   WHERE LOCATION_INVENTORY.LOCATION = LOC.LOCATION    
   AND LOCATION_INVENTORY.WAREHOUSE = LOC.WAREHOUSE    
   AND CFG.RECORD_TYPE = N''LOCCLASS''    
   AND CFG.IDENTIFIER = LOC.LOCATION_CLASS    
   AND SYS1VALUE = N''N'')    
  AND (    
   (LOCATION_INVENTORY.ALLOCATED_QTY IS NOT NULL AND ALLOCATED_QTY != 0)    
   OR (ON_HAND_QTY IS NOT NULL AND ON_HAND_QTY != 0)    
   OR (IN_TRANSIT_QTY IS NOT NULL AND IN_TRANSIT_QTY != 0)    
   OR (SUSPENSE_QTY IS NOT NULL AND SUSPENSE_QTY != 0))    
  AND LOCATION_INVENTORY.WAREHOUSE = W.WAREHOUSE    
  AND I.ITEM = LOCATION_INVENTORY.ITEM    
  AND ISNULL(I.COMPANY, N''*'') = ISNULL(LOCATION_INVENTORY.COMPANY, N''*'')) ';  
    
   
  
 EXECUTE sp_executesql @SQLString, N'@WarehouseDate DATETIME',@WarehouseDate = @WarehouseDate