
/*
	Task	| By	| Date		| Modification Description
	--------------------------------------------------------------------
	182441	| SSD	| 07/22/16	| Created	
	
*/

CREATE PROCEDURE INV_MonitorLocationChartData
@filterCriteria NVARCHAR(MAX),
@culture NVARCHAR(10) 
AS
Set NoCount ON
	DECLARE @warehouse as nVarchar(80);
	DECLARE @criteriaTempTable TABLE (
	filterName nVarchar(300),
	filterValue nVarchar(300))

   
 /*get the where clause value*/
	INSERT INTO @criteriaTempTable SELECT * FROM fn_GetMonitorFilterParameters(@filterCriteria)

	SELECT @warehouse = filterValue from @criteriaTempTable WHERE filterName = N'WAREHOUSE'
	

  SELECT N'CHARTDATA_MonitorInventory' AS CHARTDATA_MonitorInventory,											
  CATEGORY= CASE WHEN LOCATING_ZONE IS NULL THEN dbo.RSCMfn_RtrvResource(N'UNASSIGNED',N'text',@culture) ELSE LOCATING_ZONE END, 
  COUNT(distinct LOCATION) AS DATA,
  DESCRIPTION = CASE WHEN LOCATING_ZONE IS NULL THEN NULL ELSE N'' END,	
  N'LOCATINGZONE' AS XAXISTITLE, 
  N'LOCATIONS' AS YAXISTITLE, 
  1 AS NextDrillDownLevel, 
  N'EMPTYLOCBYLOCATINGZONE' AS CHARTTITLE  from METADATA_INSIGHT_INVENTORY_VIEW 
  where warehouse=@warehouse and location_sts=N'Empty' AND ACTIVE=N'Y'
  group by (LOCATING_ZONE)
  ORDER BY DATA desc;
 
  
/* SUMMARY TILES START */
   DECLARE @TOTAL_LOCATIONS INT=0,@EMPTY_LOCATIONS INT=0,@PERCENT_EMPTY FLOAT=0.00,@FROZEN_EMPTY INT=0;

   SELECT  @TOTAL_LOCATIONS = (sum (loc.cnt)), @EMPTY_LOCATIONS = SUM(CASE WHEN loc.locationSTS =N'Empty' THEN cnt ELSE 0 END)
from ( SELECT count (distinct (LOCATION)) as cnt, LOCATION_STS as locationSTS, Count(DISTINCT LOCATION) as locCount FROM METADATA_INSIGHT_INVENTORY_VIEW WHERE WAREHOUSE=@warehouse  AND ACTIVE=N'Y'
GROUp by Location, LOCATION_STS) loc;
SELECT  @PERCENT_EMPTY = case when @TOTAL_LOCATIONS<>0 then (CAST(@EMPTY_LOCATIONS AS FLOAT)/CAST(@TOTAL_LOCATIONS AS FLOAT)*100.00) else 0.00 end;
SELECT  @FROZEN_EMPTY = (COUNT(DISTINCT(L.location))) from METADATA_INSIGHT_INVENTORY_VIEW L WHERE L.WAREHOUSE=@warehouse AND L.ACTIVE=N'Y' and L.LOCATION_STS=N'FROZEN'	AND L.LOCATION NOT in (select distinct LI.LOCATION from LOCATION_INVENTORY LI);


 SELECT TOP 1 N'SUMMARYTILE_TOTAL_LOCATIONS' AS SUMMARYTILE_TOTAL_LOCATIONS,  @TOTAL_LOCATIONS AS TOTAL_LOCATIONS;
 SELECT TOP 1 N'SUMMARYTILE_EMPTY_LOCATIONS' AS SUMMARYTILE_EMPTY_LOCATIONS,  @EMPTY_LOCATIONS AS EMPTY_LOCATIONS;
 SELECT TOP 1 N'SUMMARYTILE_PERCENT_EMPTY' AS SUMMARYTILE_PERCENT_EMPTY, @PERCENT_EMPTY AS PERCENT_EMPTY;
 SELECT TOP 1 N'SUMMARYTILE_FROZEN_EMPTY' AS SUMMARYTILE_FROZEN_EMPTY,  @FROZEN_EMPTY AS FROZEN_EMPTY;

/* SUMMARY TILES ENDS */

If @@ERROR <> 0 GoTo ErrorHandler
    Set NoCount OFF
    Return(0)
  
ErrorHandler:
    Return(@@ERROR)
	