/*
    Task       | By         | Date                  | Modification Description
    --------------------------------------------------------------------
    255761	   | PMB        | 08/05/20				| Created to update group number and sequence on work instruction for system  directed work.
*/

CREATE PROCEDURE WRK_UpdateWorkInstructionForSystemDirectedWorkUnitSelection(
@workunit nvarchar(50),
@groupNumber nvarchar(50)
)  
AS

IF(ISNULL(@WORKUNIT, N'') != N'')
	BEGIN
	
	-- UPDATE GROUP NUMBER ON WORK INSTRUCTION
	UPDATE WORK_INSTRUCTION
	SET  GROUP_NUM = @GROUPNUMBER
		,SEQUENCE = 0 
		WHERE WORK_UNIT = @WORKUNIT;
	
	-- UPDATE SEQUECE ON WORK INSTRUCTION
	UPDATE WORK_INSTRUCTION SET 
	SEQUENCE =( SELECT MAX(SEQUENCE) 
	FROM WORK_INSTRUCTION
	WHERE GROUP_NUM = @GROUPNUMBER AND INTERNAL_NUM_TYPE =N'RECEIPT'
	)
	+ SORTEDWORKINSTRUCTIONS.SEQUENCENUM 
	FROM WORK_INSTRUCTION WI
	INNER JOIN 
	( 	SELECT  
		INTERNAL_INSTRUCTION_NUM
		, ROW_NUMBER()
			OVER ( ORDER BY  INTERNAL_INSTRUCTION_NUM ASC )  AS SEQUENCENUM 
		FROM  WORK_INSTRUCTION  
		WHERE  GROUP_NUM = @GROUPNUMBER  AND SEQUENCE = 0 AND INSTRUCTION_TYPE =N'DETAIL' 
	)SORTEDWORKINSTRUCTIONS ON SORTEDWORKINSTRUCTIONS.INTERNAL_INSTRUCTION_NUM = WI.INTERNAL_INSTRUCTION_NUM AND WI.INTERNAL_NUM_TYPE =N'RECEIPT'

	END