CREATE PROCEDURE TRAV_delete_empty_loads
AS
--Jimmy 
DELETE 
FROM SHIPPING_LOAD 
WHERE INTERNAL_LOAD_NUM IN 
	(
	SELECT INTERNAL_LOAD_NUM 
	FROM SHIPPING_LOAD 
	WHERE INTERNAL_LOAD_NUM NOT IN 
		(
		SELECT SHIPPING_LOAD_NUM 
		FROM SHIPMENT_HEADER 
		WHERE SHIPPING_LOAD_NUM IS NOT NULL 
		GROUP BY SHIPPING_LOAD_NUM 
		) 
	)