/*
	Task	| By	| Date			| Modification Description
	-------------------------------------------------
	107559	| MJ	| 02/20/2013	| Created.
	108670	| MJ	| 03/07/2013	| Modified for reteriving from AR_TRANSACTION_HISTORY Table.
	109688	| TDA	| 03/15/2013	| Include todays date and fixed transaction types for archive history
	145662  | KSS   | 09/05/2014    | Insert records to MOVEMENT_CLASS_ANALYSIS for zero hit transaction.
	191074	| DN	| 01/23/17		| Updated parameter types
	196637  | MHM   | 01/31/2017    | Modified the script so that the number of hits and qty are correctly calculated when multiple lot records exist in a location.
*/
CREATE PROCEDURE MOVECLS_MineMovementClassAnalysisData
(	@Warehouse nvarchar(25),
	@Days int = 90,
	@Permanent nchar(1),
	@IncludeArchivedData nchar(1)
)
AS

SET NOCOUNT ON;

DECLARE	@DateFrom	DATETIME
DECLARE @DateTo		DATETIME
DECLARE	@stErrorMsg NVARCHAR(2000)
DECLARE @rowEffected Numeric(9,0)

SELECT @DateTo = DATEADD(dd, 1, DATEDIFF(dd, 0, GETUTCDATE()))
SELECT @DateFrom = @DateTo - @Days

--Wareshouse should not be null
if (@Warehouse is null)
begin
	set @stErrorMsg = N'MSG_INVVAL28';
	return -1;
end

--Clear MOVEMENT_CLASS_ANALYSIS table on each run
DELETE FROM MOVEMENT_CLASS_ANALYSIS where WAREHOUSE = @Warehouse


IF UPPER(@PERMANENT) = N'Y' 
BEGIN
	INSERT INTO MOVEMENT_CLASS_ANALYSIS (ITEM, COMPANY, WAREHOUSE, LOCATION, TOTAL_QUANTITY, QUANTITY_UM, ITEM_CLASS, NUMBER_OF_HITS, NUMBER_OF_DAYS, DATE_TIME_STAMP, USER_STAMP,			PROCESS_STAMP)
	SELECT ITEM, COMPANY, WAREHOUSE, LOCATION,  sum(TOTAL_QUATITY) AS TOTAL_QUATITY, QUANTITY_UM, ITEM_CLASS,SUM(NUMBER_OF_HITS), @Days , GETUTCDATE(),N'System',N'MineMovementClassAnalysis'
	FROM 
	(		 
		SELECT TH.ITEM, TH.COMPANY, TH.WAREHOUSE, TH.LOCATION,  sum(TH.QUANTITY) AS TOTAL_QUATITY, th.QUANTITY_UM, I.ITEM_CLASS,NUMBER_OF_HITS
		FROM ITEM I WITH (NOLOCK) 
		JOIN 
			( 
				SELECT TRANSACTION_HISTORY.ITEM, TRANSACTION_HISTORY.COMPANY, TRANSACTION_HISTORY.WAREHOUSE, TRANSACTION_HISTORY.LOCATION, TRANSACTION_HISTORY.QUANTITY_UM,
					sum(TRANSACTION_HISTORY.QUANTITY) as QUANTITY, COUNT(*) as NUMBER_OF_HITS
				FROM TRANSACTION_HISTORY  WITH (NOLOCK) 
				INNER JOIN LOCATION WITH (NOLOCK) 
					ON	LOCATION.LOCATION = TRANSACTION_HISTORY.LOCATION   
					AND LOCATION.WAREHOUSE = TRANSACTION_HISTORY.WAREHOUSE   
					AND LOCATION.LOCATION_CLASS = N'Inventory' 
				INNER JOIN LOCATION_INVENTORY LI on TRANSACTION_HISTORY.LOCATION  = LI.LOCATION AND TRANSACTION_HISTORY.WAREHOUSE = LI.WAREHOUSE
					AND ISNULL(LI.LOT,N'!') = ISNULL(TRANSACTION_HISTORY.LOT,N'!')
				    AND ISNULL(LI.COMPANY,N'!') = ISNULL(TRANSACTION_HISTORY.COMPANY,N'!')
				WHERE 
					ACTIVITY_DATE_TIME >=  @DateFrom and ACTIVITY_DATE_TIME < @DateTo
					AND DIRECTION = N'FROM'   
					AND TRANSACTION_TYPE IN (40,60,100,130,120,240,250,360)
					and TRANSACTION_HISTORY.WAREHOUSE = @Warehouse
					and ( LI.PERMANENT <> N'N')
				 GROUP BY TRANSACTION_HISTORY.ITEM, TRANSACTION_HISTORY.COMPANY, TRANSACTION_HISTORY.WAREHOUSE, TRANSACTION_HISTORY.LOCATION,TRANSACTION_HISTORY.QUANTITY_UM
			) TH  
		ON I.ITEM = TH.ITEM   AND (TH.COMPANY = I.COMPANY OR (TH.COMPANY IS NULL OR I.COMPANY IS NULL))	
		WHERE TH.WAREHOUSE = @WAREHOUSE 
		GROUP BY TH.ITEM,TH.COMPANY, TH.LOCATION,TH.WAREHOUSE, TH.QUANTITY_UM,I.ITEM_CLASS,NUMBER_OF_HITS		
		
	
		UNION
		
		SELECT TH.ITEM, TH.COMPANY, TH.WAREHOUSE, TH.LOCATION,  sum(TH.QUANTITY) AS TOTAL_QUATITY, th.QUANTITY_UM, I.ITEM_CLASS,NUMBER_OF_HITS
		FROM ITEM I WITH (NOLOCK) 
		JOIN 
			( 
				SELECT AR_TRANSACTION_HISTORY.ITEM, AR_TRANSACTION_HISTORY.COMPANY, AR_TRANSACTION_HISTORY.WAREHOUSE, AR_TRANSACTION_HISTORY.LOCATION, AR_TRANSACTION_HISTORY.QUANTITY_UM,
					sum(AR_TRANSACTION_HISTORY.QUANTITY) as QUANTITY, COUNT(*) as NUMBER_OF_HITS
				FROM AR_TRANSACTION_HISTORY  WITH (NOLOCK) 
				INNER JOIN LOCATION WITH (NOLOCK) 
					ON	LOCATION.LOCATION = AR_TRANSACTION_HISTORY.LOCATION   
					AND LOCATION.WAREHOUSE = AR_TRANSACTION_HISTORY.WAREHOUSE   
					AND LOCATION.LOCATION_CLASS = N'Inventory' 
				INNER JOIN LOCATION_INVENTORY LI on AR_TRANSACTION_HISTORY.LOCATION  = LI.LOCATION AND AR_TRANSACTION_HISTORY.WAREHOUSE = LI.WAREHOUSE
				    AND ISNULL(LI.LOT,N'!') = ISNULL(AR_TRANSACTION_HISTORY.LOT,N'!')
				    AND ISNULL(LI.COMPANY,N'!') = ISNULL(AR_TRANSACTION_HISTORY.COMPANY,N'!')
				WHERE 
					ACTIVITY_DATE_TIME >=  @DateFrom and ACTIVITY_DATE_TIME < @DateTo
					AND DIRECTION = N'FROM'   
					AND TRANSACTION_TYPE IN (40,60,100,130,120,240,250,360)
					and AR_TRANSACTION_HISTORY.WAREHOUSE = @Warehouse
					and ( LI.PERMANENT <> N'N')
				 GROUP BY AR_TRANSACTION_HISTORY.ITEM, AR_TRANSACTION_HISTORY.COMPANY, AR_TRANSACTION_HISTORY.WAREHOUSE, AR_TRANSACTION_HISTORY.LOCATION,AR_TRANSACTION_HISTORY.QUANTITY_UM
			) TH  
		ON I.ITEM = TH.ITEM   AND (TH.COMPANY = I.COMPANY OR (TH.COMPANY IS NULL OR I.COMPANY IS NULL))	
		WHERE TH.WAREHOUSE = @WAREHOUSE and @IncludeArchivedData = N'Y'
		GROUP BY TH.ITEM,TH.COMPANY, TH.LOCATION,TH.WAREHOUSE, TH.QUANTITY_UM,I.ITEM_CLASS,NUMBER_OF_HITS	
				
	) TransactionHistoryData
	GROUP BY ITEM,COMPANY, LOCATION,WAREHOUSE, QUANTITY_UM,ITEM_CLASS		
	
	
	
END
ELSE 
BEGIN


	INSERT INTO MOVEMENT_CLASS_ANALYSIS (ITEM, COMPANY, WAREHOUSE, LOCATION, TOTAL_QUANTITY, QUANTITY_UM, ITEM_CLASS, NUMBER_OF_HITS, NUMBER_OF_DAYS, DATE_TIME_STAMP, USER_STAMP,PROCESS_STAMP)		
	SELECT 	ITEM, COMPANY, WAREHOUSE, LOCATION,  sum(TOTAL_QUATITY) AS TOTAL_QUATITY, QUANTITY_UM, ITEM_CLASS,SUM(NUMBER_OF_HITS), @DAYS , GETUTCDATE(),N'System',N'MineMovementClassAnalysis' 
	FROM
	(
		SELECT TH.ITEM, TH.COMPANY, TH.WAREHOUSE, TH.LOCATION,  sum(TH.QUANTITY) AS TOTAL_QUATITY, th.QUANTITY_UM, I.ITEM_CLASS, NUMBER_OF_HITS
		FROM ITEM I WITH (NOLOCK) 
		JOIN 
			( 
				SELECT TRANSACTION_HISTORY.ITEM, TRANSACTION_HISTORY.COMPANY, TRANSACTION_HISTORY.WAREHOUSE, TRANSACTION_HISTORY.LOCATION, QUANTITY_UM,
					sum(TRANSACTION_HISTORY.QUANTITY) as QUANTITY, COUNT(*) as NUMBER_OF_HITS
				FROM TRANSACTION_HISTORY  WITH (NOLOCK) 
				INNER JOIN LOCATION WITH (NOLOCK) 
					ON	LOCATION.LOCATION = TRANSACTION_HISTORY.LOCATION   
					AND LOCATION.WAREHOUSE = TRANSACTION_HISTORY.WAREHOUSE   
					AND LOCATION.LOCATION_CLASS = N'Inventory' 
				WHERE 
					ACTIVITY_DATE_TIME >=  @DateFrom and ACTIVITY_DATE_TIME < @DateTo
					AND DIRECTION = N'FROM'   
					AND TRANSACTION_TYPE IN (40,60,100,130,120,240,250,360)
					and TRANSACTION_HISTORY.WAREHOUSE = @Warehouse
				 GROUP BY TRANSACTION_HISTORY.ITEM, TRANSACTION_HISTORY.COMPANY, TRANSACTION_HISTORY.WAREHOUSE, TRANSACTION_HISTORY.LOCATION,QUANTITY_UM
			) TH  
		ON I.ITEM = TH.ITEM   AND (TH.COMPANY = I.COMPANY OR (TH.COMPANY IS NULL OR I.COMPANY IS NULL))		
		WHERE TH.WAREHOUSE = @WAREHOUSE 
		GROUP BY TH.ITEM,TH.COMPANY, TH.LOCATION,TH.WAREHOUSE, TH.QUANTITY_UM,I.ITEM_CLASS,NUMBER_OF_HITS		
		
		UNION
		
		SELECT TH.ITEM, TH.COMPANY, TH.WAREHOUSE, TH.LOCATION,  sum(TH.QUANTITY) AS TOTAL_QUATITY, th.QUANTITY_UM, I.ITEM_CLASS,NUMBER_OF_HITS
		FROM ITEM I WITH (NOLOCK) 
		JOIN 
			( 
				SELECT AR_TRANSACTION_HISTORY.ITEM, AR_TRANSACTION_HISTORY.COMPANY, AR_TRANSACTION_HISTORY.WAREHOUSE, AR_TRANSACTION_HISTORY.LOCATION, QUANTITY_UM,
					sum(AR_TRANSACTION_HISTORY.QUANTITY) as QUANTITY, COUNT(*) as NUMBER_OF_HITS
				FROM AR_TRANSACTION_HISTORY  WITH (NOLOCK) 
				INNER JOIN LOCATION WITH (NOLOCK) 
					ON	LOCATION.LOCATION = AR_TRANSACTION_HISTORY.LOCATION   
					AND LOCATION.WAREHOUSE = AR_TRANSACTION_HISTORY.WAREHOUSE   
					AND LOCATION.LOCATION_CLASS = N'Inventory' 
				WHERE 
					ACTIVITY_DATE_TIME >=  @DateFrom and ACTIVITY_DATE_TIME < @DateTo
					AND DIRECTION = N'FROM'   
					AND TRANSACTION_TYPE IN (40,60,100,130,120,240,250,360)
					and AR_TRANSACTION_HISTORY.WAREHOUSE = @Warehouse
				 GROUP BY AR_TRANSACTION_HISTORY.ITEM, AR_TRANSACTION_HISTORY.COMPANY, AR_TRANSACTION_HISTORY.WAREHOUSE, AR_TRANSACTION_HISTORY.LOCATION,QUANTITY_UM
			) TH  
		ON I.ITEM = TH.ITEM   AND (TH.COMPANY = I.COMPANY OR (TH.COMPANY IS NULL OR I.COMPANY IS NULL))		
		WHERE TH.WAREHOUSE = @WAREHOUSE and @IncludeArchivedData = N'Y'
		GROUP BY TH.ITEM,TH.COMPANY, TH.LOCATION,TH.WAREHOUSE, TH.QUANTITY_UM,I.ITEM_CLASS,NUMBER_OF_HITS		
	) TransactionHistoryData
	GROUP BY ITEM,COMPANY, LOCATION,WAREHOUSE, QUANTITY_UM,ITEM_CLASS		
END

Select  @rowEffected = @@ROWCOUNT 

IF UPPER(@PERMANENT) = N'Y' 
BEGIN
INSERT INTO MOVEMENT_CLASS_ANALYSIS (ITEM, COMPANY, WAREHOUSE, LOCATION, TOTAL_QUANTITY, QUANTITY_UM, ITEM_CLASS, NUMBER_OF_HITS, NUMBER_OF_DAYS, DATE_TIME_STAMP, USER_STAMP,PROCESS_STAMP)		
SELECT 	li.ITEM, li.COMPANY, li.WAREHOUSE, li.LOCATION,  sum(ON_HAND_QTY) AS TOTAL_QUATITY, QUANTITY_UM, ITEM_CLASS, 0 , @Days , GETUTCDATE(),N'System',N'SDT_MineMovementClassAnalysis' 
from 
	location_inventory li
	inner join location loc on (loc.location =li.LOCATION and loc.warehouse =li.warehouse)
	left join item on (item.item = li.item and (item.COMPANY = li.COMPANY OR (item.COMPANY IS NULL and li.COMPANY IS NULL))) 
where 
loc.LOCATION_CLASS = N'Inventory'
and loc.warehouse = @Warehouse
and (li.PERMANENT <> N'N')
and not exists (select N'X' from MOVEMENT_CLASS_ANALYSIS mca where mca.warehouse = li.warehouse and mca.LOCATION = li.LOCATION AND mca.ITEM = li.ITEM and (mca.COMPANY = li.COMPANY OR (mca.COMPANY IS NULL AND li.COMPANY IS NULL)) )
group  by  
li.ITEM, li.COMPANY, li.WAREHOUSE, li.LOCATION, QUANTITY_UM, ITEM_CLASS
having sum(ON_HAND_QTY) >0

Select  @rowEffected = @rowEffected + @@ROWCOUNT

END
ELSE
BEGIN
INSERT INTO MOVEMENT_CLASS_ANALYSIS (ITEM, COMPANY, WAREHOUSE, LOCATION, TOTAL_QUANTITY, QUANTITY_UM, ITEM_CLASS, NUMBER_OF_HITS, NUMBER_OF_DAYS, DATE_TIME_STAMP, USER_STAMP,PROCESS_STAMP)		
SELECT 	li.ITEM, li.COMPANY, li.WAREHOUSE, li.LOCATION,  sum(ON_HAND_QTY) AS TOTAL_QUATITY, QUANTITY_UM, ITEM_CLASS, 0 , @Days , GETUTCDATE(),N'System',N'SDT_MineMovementClassAnalysis' 
from 
	location_inventory li
	inner join location loc on (loc.location =li.LOCATION and loc.warehouse =li.warehouse)
	left join item on (item.item = li.item and (item.COMPANY = li.COMPANY OR (item.COMPANY IS NULL and li.COMPANY IS NULL))) 
where 
loc.LOCATION_CLASS = N'Inventory'
and loc.warehouse = @Warehouse

and not exists (select N'X' from MOVEMENT_CLASS_ANALYSIS mca where mca.warehouse = li.warehouse and mca.LOCATION = li.LOCATION AND mca.ITEM = li.ITEM and (mca.COMPANY = li.COMPANY OR (mca.COMPANY IS NULL AND li.COMPANY IS NULL)) )
group  by  
li.ITEM, li.COMPANY, li.WAREHOUSE, li.LOCATION, QUANTITY_UM, ITEM_CLASS
having sum(ON_HAND_QTY) >0

Select  @rowEffected = @rowEffected + @@ROWCOUNT

END

SET NOCOUNT OFF
if (@@ERROR <> 0) select -1 else select @rowEffected
