/*
	Task	| By	| Date		| Modification Description
	--------------------------------------------------------------------
	18273	| VK	| 12/06/05	| Created
	19778	| MAG	| 09/26/06	| Updated the Stored Proc to retrieve the associated ERP ORDER NUM AND LINE NUM
    60479	| PP	| 10/28/09	| Updated the stored Proc to retrieve the associated MultiOrder PalletID info.
	135689	| JY	| 02/17/14	| Modified the table of upload and added new filter.
	143891	| DN	| 06/14/14	| Fixed queries
*/
	

CREATE PROCEDURE wm_RShippingContainer06
	@InternalContainerNum numeric(9),
	@InterfaceLinkID numeric(9)
AS
	IF(@InterfaceLinkID =0)	
	SELECT	SC.*, SD.ERP_ORDER, SD.ERP_ORDER_LINE_NUM, MOP.MULTI_ORDER_PALLET_ID
	FROM SHIPPING_CONTAINER SC
	INNER JOIN  SHIPMENT_DETAIL SD ON SC.INTERNAL_SHIPMENT_LINE_NUM = SD.INTERNAL_SHIPMENT_LINE_NUM
	LEFT OUTER JOIN MULTI_ORDER_PALLET MOP on SC.INTERNAL_MOP_NUMBER = MOP.INTERNAL_MOP_NUMBER
	WHERE 
		PARENT = @InternalContainerNum
		AND CONTAINER_TYPE = N'-'      
	UNION
	SELECT	SC.*, SD.ERP_ORDER, SD.ERP_ORDER_LINE_NUM, MOP.MULTI_ORDER_PALLET_ID
	FROM SHIPPING_CONTAINER SC
	INNER JOIN  SHIPMENT_DETAIL SD ON SC.INTERNAL_SHIPMENT_LINE_NUM = SD.INTERNAL_SHIPMENT_LINE_NUM
	LEFT OUTER JOIN MULTI_ORDER_PALLET MOP on SC.INTERNAL_MOP_NUMBER = MOP.INTERNAL_MOP_NUMBER
	WHERE 
		INTERNAL_CONTAINER_NUM = @InternalContainerNum
		AND SC.ITEM IS NOT NULL
		AND CONTAINER_TYPE <> N'-';
	ELSE
	SELECT	UC.*, SD.ERP_ORDER, SD.ERP_ORDER_LINE_NUM, MOP.MULTI_ORDER_PALLET_ID
	FROM UPLOAD_ORDER_CONTAINER UC
	INNER JOIN  SHIPMENT_DETAIL SD ON UC.INTERNAL_SHIPMENT_LINE_NUM = SD.INTERNAL_SHIPMENT_LINE_NUM
	LEFT OUTER JOIN MULTI_ORDER_PALLET MOP on UC.INTERNAL_MOP_NUMBER = MOP.INTERNAL_MOP_NUMBER
	WHERE 
		INTERFACE_PARENT_LINK_ID = @InternalContainerNum
		AND CONTAINER_TYPE = N'-'  
		AND INTERFACE_LINK_ID = @InterfaceLinkID    
	UNION
	SELECT	UC.*, SD.ERP_ORDER, SD.ERP_ORDER_LINE_NUM, MOP.MULTI_ORDER_PALLET_ID
	FROM UPLOAD_ORDER_CONTAINER UC
	INNER JOIN  SHIPMENT_DETAIL SD ON UC.INTERNAL_SHIPMENT_LINE_NUM = SD.INTERNAL_SHIPMENT_LINE_NUM
	LEFT OUTER JOIN MULTI_ORDER_PALLET MOP on UC.INTERNAL_MOP_NUMBER = MOP.INTERNAL_MOP_NUMBER
	WHERE 
		INTERNAL_CONTAINER_NUM = @InternalContainerNum
		AND UC.ITEM IS NOT NULL
		AND CONTAINER_TYPE <> N'-'
		AND INTERFACE_LINK_ID = @InterfaceLinkID;

