/*
	Mod Number	| Programmer	| Date   	| Modification Description
	--------------------------------------------------------------------
	185190		| MDL			| 08/22/16	| Modified to use correct type.
	190589		| DP			| 11/11/16	| Modified to get resource keys from RESOURCE_FILE_CUSTOM table
*/

CREATE PROCEDURE wm_RResource01
	@Group nvarchar(4),
	@Lang nvarchar(25)
AS

SELECT RESOURCE_KEY, TEXT, RESOURCE_GROUP, FIELD_LENGTH, DECIMAL_POS, RESOURCE_LANGUAGE FROM RESOURCE_FILE_CUSTOM CUSTOM WHERE RESOURCE_LANGUAGE = @Lang AND RESOURCE_GROUP = @Group

UNION

SELECT RESOURCE_KEY, TEXT, RESOURCE_GROUP, FIELD_LENGTH, DECIMAL_POS, RESOURCE_LANGUAGE FROM RESOURCE_FILE_BASE BASE WHERE RESOURCE_LANGUAGE = @Lang AND RESOURCE_GROUP = @Group 
AND RESOURCE_KEY NOT IN (SELECT RESOURCE_KEY FROM RESOURCE_FILE_CUSTOM CUSTOM WHERE RESOURCE_LANGUAGE = @Lang AND RESOURCE_GROUP = @Group) 

