/*
	Mod Number	| Programmer	| Date   	| Modification Description
	--------------------------------------------------------------------
	20780		| MDL			| 05/09/08	| Created.

	Splits the internal work instruction passed in
	
	Parameters
		double		@qty							qty to remain on existing instruction number
		int			@internalInstructionNum			The WorkInstruction details internalInstructionNum.	
		string  	@userName						The user doing the split
		int			@newInternalInstrNum			The new internal instruction number resulting from the split	
*/


CREATE PROCEDURE WTH_SplitWorkInPutawayRetInstr(
	@qty	numeric(19,5),
	@internalInstructionNum numeric(9),
	@userStamp nvarchar(30),
	@newInternalInstrNum numeric(9) output)
AS
	SET NOCOUNT ON;

	-- #DEFINE WMW.Jsharp.General com.pronto.general.Constants Constants;
	-- #DEFINE WMW.JSharp.DataAccess.DO com.pronto.dbutility.process.WorkInstructionDO workDO;
	
	-- local variables
	declare @iError int;
	declare @iRowCount int;
	declare @stMsg nvarchar(2000);

	-- validate parameters.
	if (@internalInstructionNum is null OR @internalInstructionNum <= 0 OR @qty is null OR @qty <= 0)
		return -1;
	
	/*Copy Work Instruction */
	INSERT INTO WORK_INSTRUCTION ( ACCOUNT, AGING_DATE_TIME, ALLOCATION_ZONE, ASSIGNMENT_ID, COMPANY, COMPLETED_BY_USER, CONDITION, CONTAINER_ID, CONVERTED_QTY, CONVERTED_QTY_UM, CYCLE_COUNT, CYCLE_COUNT_GROUP_NUM, END_DATE_TIME, EQUIPMENT_LOC, ERP_ORDER, ERP_ORDER_LINE_NUM, ESTIMATED_TIME, FROM_CHECK_DIG, FROM_LOC, FROM_LOC_INV_ATTRIBUTES_ID, FROM_QTY, FROM_TEMPL_FIELD1, FROM_TEMPL_FIELD2, FROM_TEMPL_FIELD3, FROM_TEMPL_FIELD4, FROM_TEMPL_FIELD5, FROM_WHS, FROM_WORK_ZONE, GROUP_NUM, HOLD_CODE, INCOMING_PD_LOC, INSTRUCTION_TYPE, INTERNAL_CONTAINER_NUM, INTERNAL_COUNT_NUM, INTERNAL_LINE_NUM, INTERNAL_NUM, INTERNAL_NUM_TYPE, INTERNAL_REQ_NUM, INVENTORY_AT_PD, INVENTORY_TRACKING, ITEM, ITEM_DESC, LAUNCH_NUM, LOCATING_ZONE, LOCKED, LOGISTICS_UNIT, LOT, MESSAGE_ID, NUMBER_OF_CHILDREN, OUTGOING_PD_LOC, PARENT_CONTAINER_ID, PARENT_CONTAINER_NUM, PARENT_INSTR, PARENT_LOGISTICS_UNIT, PICK_LIST_ID, PRIORITY, QUANTITY, QUANTITY_UM, REFERENCE_ID, REFERENCE_TYPE, RELATED_WORK_UNIT, SEQUENCE, SRC_IDENTIFIER, START_DATE_TIME, TEAM_ASSIGNED, TO_CHECK_DIG, TO_LOC, TO_LOC_INV_ATTRIBUTES_ID, TO_QTY, TO_TEMPL_FIELD1, TO_TEMPL_FIELD2, TO_TEMPL_FIELD3, TO_TEMPL_FIELD4, TO_TEMPL_FIELD5, TO_WHS, TO_WORK_ZONE, TOTAL_VALUE, TOTAL_VOLUME, TOTAL_WEIGHT, TRANSPORT_CONT_ID, TREE_UNIT, TREE_UNIT_ID, USER_ASSIGNED, VOLUME_UM, WEIGHT_UM, WORK_GROUP, WORK_TYPE, WORK_UNIT, USER_DEF1, USER_DEF2, USER_DEF3, USER_DEF4, USER_DEF5, USER_DEF6, USER_DEF7, USER_DEF8, USER_STAMP, PROCESS_STAMP, DATE_TIME_STAMP ) 
		SELECT ACCOUNT, AGING_DATE_TIME, ALLOCATION_ZONE, ASSIGNMENT_ID, COMPANY, COMPLETED_BY_USER, CONDITION, CONTAINER_ID, CONVERTED_QTY, CONVERTED_QTY_UM, CYCLE_COUNT, CYCLE_COUNT_GROUP_NUM, END_DATE_TIME, EQUIPMENT_LOC, ERP_ORDER, ERP_ORDER_LINE_NUM, ESTIMATED_TIME, FROM_CHECK_DIG, FROM_LOC, FROM_LOC_INV_ATTRIBUTES_ID, FROM_QTY, FROM_TEMPL_FIELD1, FROM_TEMPL_FIELD2, FROM_TEMPL_FIELD3, FROM_TEMPL_FIELD4, FROM_TEMPL_FIELD5, FROM_WHS, FROM_WORK_ZONE, GROUP_NUM, HOLD_CODE, INCOMING_PD_LOC, INSTRUCTION_TYPE, INTERNAL_CONTAINER_NUM, INTERNAL_COUNT_NUM, INTERNAL_LINE_NUM, INTERNAL_NUM, INTERNAL_NUM_TYPE, INTERNAL_REQ_NUM, INVENTORY_AT_PD, INVENTORY_TRACKING, ITEM, ITEM_DESC, LAUNCH_NUM, LOCATING_ZONE, LOCKED, LOGISTICS_UNIT, LOT, MESSAGE_ID, NUMBER_OF_CHILDREN, OUTGOING_PD_LOC, PARENT_CONTAINER_ID, PARENT_CONTAINER_NUM, PARENT_INSTR, PARENT_LOGISTICS_UNIT, PICK_LIST_ID, PRIORITY, QUANTITY, QUANTITY_UM, REFERENCE_ID, REFERENCE_TYPE, RELATED_WORK_UNIT, SEQUENCE, SRC_IDENTIFIER, START_DATE_TIME, TEAM_ASSIGNED, TO_CHECK_DIG, TO_LOC, TO_LOC_INV_ATTRIBUTES_ID, TO_QTY, TO_TEMPL_FIELD1, TO_TEMPL_FIELD2, TO_TEMPL_FIELD3, TO_TEMPL_FIELD4, TO_TEMPL_FIELD5, TO_WHS, TO_WORK_ZONE, TOTAL_VALUE, TOTAL_VOLUME, TOTAL_WEIGHT, TRANSPORT_CONT_ID, TREE_UNIT, TREE_UNIT_ID, USER_ASSIGNED, VOLUME_UM, WEIGHT_UM, WORK_GROUP, WORK_TYPE, WORK_UNIT, USER_DEF1, USER_DEF2, USER_DEF3, USER_DEF4, USER_DEF5, USER_DEF6, USER_DEF7, USER_DEF8, USER_STAMP, PROCESS_STAMP, DATE_TIME_STAMP 
		FROM WORK_INSTRUCTION
		WHERE INTERNAL_INSTRUCTION_NUM = @internalInstructionNum;
	if (@@ERROR <> 0) return -1;	

	set @newInternalInstrNum = SCOPE_IDENTITY();

	/* Update new Instruction */
	UPDATE WORK_INSTRUCTION
	SET	CONVERTED_QTY = (CONVERTED_QTY / QUANTITY) * (QUANTITY - @qty),
		FROM_QTY = FROM_QTY ,
		QUANTITY = QUANTITY - @qty,
		TO_QTY = 0,
		TOTAL_WEIGHT = (TOTAL_WEIGHT / QUANTITY) * (QUANTITY - @qty),
		TOTAL_VOLUME = (TOTAL_VOLUME / QUANTITY) * (QUANTITY - @qty),
		TOTAL_VALUE = (TOTAL_VALUE / QUANTITY) * (QUANTITY - @qty),
		USER_STAMP = @userStamp,
		PROCESS_STAMP = N'WTH_SplitWorkInPutawayRetInstr'
	WHERE INTERNAL_INSTRUCTION_NUM = @newInternalInstrNum
	AND TO_QTY >= @qty;
	select @iError = @@ERROR, @iRowCount = @@ROWCOUNT;
	
	if (@iError <> 0) return -1;	
		
	if (@iRowCount <= 0) 
      begin 
		set @stMsg = N'MSG_WORK10: ' + dbo.RSCMfn_RtrvMsg(N'MSG_WORK10'); 
            RAISERROR(@stMsg, 18, 1); 
            return -1; 
     	end;	

	/* Update Old Instruction */
	UPDATE WORK_INSTRUCTION
	SET	CONVERTED_QTY = (CONVERTED_QTY / QUANTITY) * (QUANTITY - (QUANTITY - @qty)),
		FROM_QTY = 0,
		TO_QTY =  @qty,
		QUANTITY = (QUANTITY - (QUANTITY - @qty)),
		TOTAL_WEIGHT = (TOTAL_WEIGHT / QUANTITY) * (QUANTITY - (QUANTITY - @qty)),
		TOTAL_VOLUME = (TOTAL_VOLUME / QUANTITY) * (QUANTITY - (QUANTITY - @qty)),
		TOTAL_VALUE = (TOTAL_VALUE / QUANTITY) * (QUANTITY - (QUANTITY - @qty)),
		USER_STAMP = @userStamp,
		PROCESS_STAMP = N'WTH_SplitWorkInPutawayRetInstr',
		EQUIPMENT_LOC = NULL
	WHERE INTERNAL_INSTRUCTION_NUM = @internalInstructionNum;
	if (@@ERROR <> 0) return -1;	
	
	/* Update Header */
	UPDATE WORK_INSTRUCTION
	SET	NUMBER_OF_CHILDREN = NUMBER_OF_CHILDREN + 1
	WHERE INTERNAL_INSTRUCTION_NUM IN
		(SELECT PARENT_INSTR FROM WORK_INSTRUCTION 
		WHERE INTERNAL_INSTRUCTION_NUM = @internalInstructionNum);
	if (@@ERROR <> 0) return -1;	


-- end WTH_SplitWorkInPutawayRetInstr





