/*
 Mod     | Programmer    | Date       | Modification Description
 --------------------------------------------------------------------
  EX01   | rphilip	     | 03/10/2023 | EX01 - Insert Data for PS
*/

CREATE PROCEDURE TRAV_EX01_InsertDataForPS (
 @InternalWaveNum nvarchar(max)
)
AS
BEGIN

    SET NOCOUNT ON; 


    DECLARE @EVENT_ID int;
	DECLARE @ENDPOINT_ID int;
    DECLARE @DIF_EVE_EXE_IDENTIFIER VARCHAR(25);
    DECLARE @Warehouse VARCHAR(max);
    DECLARE @UDF1 NCHAR(1);
   
    SELECT @Warehouse = Warehouse,@UDF1 = USER_DEF1 from LAUNCH_STATISTICS WITH(NOLOCK) Where INTERNAL_LAUNCH_NUM = @InternalWaveNum;

    IF(@UDF1 = N'Y')
    BEGIN
    
     
     SET @DIF_EVE_EXE_IDENTIFIER = N'EX01_SCALETOPS';

     SELECT @EVENT_ID = EVENT_ID FROM DIF_EVENT WITH(NOLOCK) WHERE EVENT_DESCRIPTION = N'EX01_SCALETOPS' AND DIF_EVE_EXE_IDENTIFIER = @DIF_EVE_EXE_IDENTIFIER ;

     SELECT @ENDPOINT_ID = ENDPOINT_ID FROM DIF_ENDPOINT WITH(NOLOCK) WHERE EVENT_ID = @EVENT_ID;

      INSERT INTO DIF_INCOMING_MESSAGE(ENCODING, DATA, STATUS, DIF_EVE_EXE_IDENTIFIER, ENDPOINT_ID, EVENT_ID,Msg_Part1, USER_STAMP, PROCESS_STAMP, DATE_TIME_STAMP, INSERTED_DATE_TIME) 
	  VALUES(0,@InternalWaveNum, N'Ready',@DIF_EVE_EXE_IDENTIFIER, @ENDPOINT_ID, @EVENT_ID,@Warehouse,N'ILSSRV', N'TRAV_EXP_ReleaseWaveAfter', GETUTCDATE(),GETUTCDATE());
     
     END

END