CREATE PROCEDURE TRAV_EX02LANEDataProcess(
		@LANE_NUMBER			NVARCHAR(25),
		@PALLET_ACTIVE			NCHAR(1),
		@WORK_UNIT			NVARCHAR(50),
		@PRIORITY_ESCALATED	NCHAR(1)		
)
AS
IF NOT EXISTS (SELECT 1 FROM TRAV_LANE WITH(NOLOCK) WHERE WORK_UNIT = @WORK_UNIT and LANE_NUMBER=@LANE_NUMBER)
BEGIN
INSERT INTO TRAV_LANE(LANE_NUMBER,PALLET_ACTIVE,WORK_UNIT,PRIORITY_ESCALATED)
VALUES(@LANE_NUMBER,@PALLET_ACTIVE,@WORK_UNIT,@PRIORITY_ESCALATED);
END