CREATE PROCEDURE TRAV_EX06UpdateMOPValues(  
@MOP_NUMBER NVARCHAR(50),  
@PALLET_NUMBER NVARCHAR(25),  
@MOP_WEIGHT NVARCHAR(20)  
)  
AS  
  
IF EXISTS(SELECT 1 FROM multi_order_pallet WITH(NOLOCK) WHERE MULTI_ORDER_PALLET_ID = @MOP_NUMBER)  
BEGIN  
UPDATE multi_order_pallet SET USER_DEF1=@PALLET_NUMBER, USER_DEF7=@MOP_WEIGHT where MULTI_ORDER_PALLET_ID = @MOP_NUMBER;  
END
