/*
 Mod Number  | Programmer | Date       | Modification Description
 --------------------------------------------------------------------
 00000       | copilot    | 05/19/2026 | Create procedure to transfer rejected shipment detail and copy comments.
*/

CREATE PROCEDURE TransferRejectedDetail
    @internalLineNum numeric(9),
    @newStatus numeric(3),
    @rejStatus numeric(3),
    @qtyAtSts1 numeric(19,5),
    @toShipNum numeric(9),
    @toShipId nvarchar(25)
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    DECLARE @newInternalLineNum numeric(9);
    DECLARE @errorMessage NVARCHAR(4000);

    
    BEGIN TRANSACTION;

    BEGIN TRY
        -- NOTE: Explicit column list intentionally mirrors SHIPMENT_DETAIL schema.
        -- Keep this INSERT/SELECT list in sync when SHIPMENT_DETAIL columns are added/changed.
        INSERT INTO SHIPMENT_DETAIL
            (INTERNAL_SHIPMENT_NUM,
             ALLOCATION_RULE,
             STATUS_FLOW_NAME,
             ERP_ORDER,
             STATUS1,
             ERP_ORDER_LINE_NUM,
             WAREHOUSE,
             INTERNAL_ORDER_NUM,
             STATUS2,
             SHIP_TO,
             STATUS3,
             LAUNCH_NUM,
             STATUS4,
             STATUS_FAILED,
             STATUS5,
             STATUS6,
             STATUS7,
             ORDER_TYPE,
             STATUS8,
             CUSTOMER,
             ITEM,
             STATUS9,
             STATUS10,
             MARK_FOR,
             ITEM_DESC,
             CUSTOMER_ITEM,
             CARRIER,
             CARRIER_SERVICE,
             FREIGHT_TERMS,
             LIABILITY_TERMS,
             ORDER_DATE,
             SHIPMENT_ID,
             COMPANY,
             INTERFACED_DATE,
             REQUESTED_QTY,
             QUANTITY_UM,
             PICK_LOC,
             CARRIER_TYPE,
             PICK_ZONE,
             SECONDARY_PICK_LOC,
             WEIGHT_UM,
             SECONDARY_PICK_ZONE,
             PLANNED_SHIP_DATE,
             ITEM_LENGTH,
             ITEM_WIDTH,
             REQUESTED_DELIVERY_DATE,
             REQUESTED_DELIVERY_TYPE,
             ITEM_HEIGHT,
             ITEM_DIMENSION_UM,
             ITEM_DEPARTMENT,
             ITEM_LIST_PRICE,
             ITEM_NET_PRICE,
             ITEM_COLOR,
             ITEM_STYLE,
             ITEM_SIZE,
             ORIGINAL_ITEM_ORDERED,
             PICK_LIST_ID,
             CUSTOMER_PO,
             INVOICE,
             ITEM_VOLUME,
             PACKING_CATEGORY,
             TOTAL_VOLUME,
             HAZARDOUS_CODE,
             ITEM_DIVISION,
             NMFC_CODE,
             TOTAL_WEIGHT,
             CATALOG_ID,
             MANUFACTURE_ID,
             TOTAL_QTY,
             VALUE,
             MERCHANDISE_CODE,
             VALUE_ADD_LABEL_CODE,
             VOLUME_UM,
             USER_DEF1,
             USER_DEF2,
             USER_DEF3,
             MANUALLY_ENTERED,
             USER_DEF4,
             USER_DEF5,
             USER_DEF6,
             USER_DEF7,
             USER_DEF8,
             USER_STAMP,
             PROCESS_STAMP,
             QUANTITY_AT_STS1,
             LOT_CONTROLLED,
             DATE_TIME_STAMP,
             SERIAL_NUM_REQD,
             QUANTITY_AT_STS2,
             CATCH_WEIGHT_REQD,
             QUANTITY_AT_STS3,
             QUANTITY_AT_STS4,
             QUANTITY_AT_STS5,
             QUANTITY_AT_STS6,
             QUANTITY_AT_STS7,
             QUANTITY_AT_STS8,
             QUANTITY_AT_STS9,
             PRIORITY,
             ITEM_WEIGHT,
             QUANTITY_AT_STS10,
             LOT,
             ITEM_CLASS,
             MARK_FOR_NAME,
             MARK_FOR_ADDRESS1,
             MARK_FOR_ADDRESS2,
             MARK_FOR_ADDRESS3,
             MARK_FOR_ATTENTION_TO,
             MARK_FOR_CITY,
             MARK_FOR_STATE,
             MARK_FOR_COUNTRY,
             MARK_FOR_POSTAL_CODE,
             MARK_FOR_PHONE_NUM,
             MARK_FOR_FAX_NUM,
             MARK_FOR_EMAIL_ADDRESS,
             HARMONIZED_CODE,
             HARMONIZED_DESC,
             EXPORT_DESC,
             PREFERENCE_CRIT,
             PRODUCER,
             NET_COST,
             COUNTRY_OF_ORIGIN,
             PACKING_CLASS,
             INTERFACE_RECORD_ID,
             ITEM_CATEGORY1,
             ITEM_CATEGORY2,
             ITEM_CATEGORY3,
             ITEM_CATEGORY4,
             ITEM_CATEGORY5,
             ITEM_CATEGORY6,
             ITEM_CATEGORY7,
             ITEM_CATEGORY8,
             ITEM_CATEGORY9,
             ITEM_CATEGORY10,
             CONT_CREATION_FULL_QTY,
             CONT_CREATION_FULL_QTY_UM,
             CONT_CREATION_INNERPACK_QTY,
             ALLOCATE_FULL_LOC_QTY,
             ALLOW_PCT_ALLOC,
             MINIMUM_ALLOC_PCT,
             MAXIMUM_ALLOC_PCT,
             IMMEDIATE_NEEDS_NOTE,
             TREAT_AS_LOOSE,
             PREVIOUS_WAVE_NUM,
             BOM_ACTION,
             INTERNAL_WORK_ORDER_NUM,
             RELATED_INTERNAL_LINE_NUM,
             QUANTITY_NEEDED_PER_ITEM,
             STORE_DISTRIBUTION,
             IMMEDIATE_NEEDS_ELIGIBLE,
             IMMEDIATE_NEEDS_LOC_RULE,
             LOGISTICS_UNIT,
             PARENT_LOGISTICS_UNIT,
             LOC_INV_ATTRIBUTES_ID,
             ALLOCATION_REJECTED_QTY,
             ECCN,
             VALIDATED_LICENSE,
             LICENSE_EXP_DATE)
        SELECT @toShipNum,
               ALLOCATION_RULE,
               STATUS_FLOW_NAME,
               ERP_ORDER,
               @newStatus,
               ERP_ORDER_LINE_NUM,
               WAREHOUSE,
               INTERNAL_ORDER_NUM,
               0,
               SHIP_TO,
               0,
               0,
               0,
               STATUS_FAILED,
               0,
               0,
               0,
               ORDER_TYPE,
               0,
               CUSTOMER,
               ITEM,
               0,
               0,
               MARK_FOR,
               ITEM_DESC,
               CUSTOMER_ITEM,
               CARRIER,
               CARRIER_SERVICE,
               FREIGHT_TERMS,
               LIABILITY_TERMS,
               ORDER_DATE,
               @toShipId,
               COMPANY,
               INTERFACED_DATE,
               REQUESTED_QTY,
               QUANTITY_UM,
               PICK_LOC,
               CARRIER_TYPE,
               PICK_ZONE,
               SECONDARY_PICK_LOC,
               WEIGHT_UM,
               SECONDARY_PICK_ZONE,
               PLANNED_SHIP_DATE,
               ITEM_LENGTH,
               ITEM_WIDTH,
               REQUESTED_DELIVERY_DATE,
               REQUESTED_DELIVERY_TYPE,
               ITEM_HEIGHT,
               ITEM_DIMENSION_UM,
               ITEM_DEPARTMENT,
               ITEM_LIST_PRICE,
               ITEM_NET_PRICE,
               ITEM_COLOR,
               ITEM_STYLE,
               ITEM_SIZE,
               ORIGINAL_ITEM_ORDERED,
               PICK_LIST_ID,
               CUSTOMER_PO,
               INVOICE,
               ITEM_VOLUME,
               PACKING_CATEGORY,
               TOTAL_VOLUME,
               HAZARDOUS_CODE,
               ITEM_DIVISION,
               NMFC_CODE,
               TOTAL_WEIGHT,
               CATALOG_ID,
               MANUFACTURE_ID,
               TOTAL_QTY,
               VALUE,
               MERCHANDISE_CODE,
               VALUE_ADD_LABEL_CODE,
               VOLUME_UM,
               USER_DEF1,
               USER_DEF2,
               USER_DEF3,
               MANUALLY_ENTERED,
               USER_DEF4,
               USER_DEF5,
               USER_DEF6,
               USER_DEF7,
               USER_DEF8,
               USER_STAMP,
               PROCESS_STAMP,
               @qtyAtSts1,
               LOT_CONTROLLED,
               GETUTCDATE(),
               SERIAL_NUM_REQD,
               0,
               CATCH_WEIGHT_REQD,
               0,
               0,
               0,
               0,
               0,
               0,
               0,
               PRIORITY,
               ITEM_WEIGHT,
               0,
               LOT,
               ITEM_CLASS,
               MARK_FOR_NAME,
               MARK_FOR_ADDRESS1,
               MARK_FOR_ADDRESS2,
               MARK_FOR_ADDRESS3,
               MARK_FOR_ATTENTION_TO,
               MARK_FOR_CITY,
               MARK_FOR_STATE,
               MARK_FOR_COUNTRY,
               MARK_FOR_POSTAL_CODE,
               MARK_FOR_PHONE_NUM,
               MARK_FOR_FAX_NUM,
               MARK_FOR_EMAIL_ADDRESS,
               HARMONIZED_CODE,
               HARMONIZED_DESC,
               EXPORT_DESC,
               PREFERENCE_CRIT,
               PRODUCER,
               NET_COST,
               COUNTRY_OF_ORIGIN,
               PACKING_CLASS,
               INTERFACE_RECORD_ID,
               ITEM_CATEGORY1,
               ITEM_CATEGORY2,
               ITEM_CATEGORY3,
               ITEM_CATEGORY4,
               ITEM_CATEGORY5,
               ITEM_CATEGORY6,
               ITEM_CATEGORY7,
               ITEM_CATEGORY8,
               ITEM_CATEGORY9,
               ITEM_CATEGORY10,
               CONT_CREATION_FULL_QTY,
               CONT_CREATION_FULL_QTY_UM,
               CONT_CREATION_INNERPACK_QTY,
               ALLOCATE_FULL_LOC_QTY,
               ALLOW_PCT_ALLOC,
               MINIMUM_ALLOC_PCT,
               MAXIMUM_ALLOC_PCT,
               NULL,
               TREAT_AS_LOOSE,
               PREVIOUS_WAVE_NUM,
               BOM_ACTION,
               INTERNAL_WORK_ORDER_NUM,
               RELATED_INTERNAL_LINE_NUM,
               QUANTITY_NEEDED_PER_ITEM,
               STORE_DISTRIBUTION,
               IMMEDIATE_NEEDS_ELIGIBLE,
               IMMEDIATE_NEEDS_LOC_RULE,
               LOGISTICS_UNIT,
               PARENT_LOGISTICS_UNIT,
               LOC_INV_ATTRIBUTES_ID,
               ALLOCATION_REJECTED_QTY,
               ECCN,
               VALIDATED_LICENSE,
               LICENSE_EXP_DATE
        FROM SHIPMENT_DETAIL
        WHERE INTERNAL_SHIPMENT_LINE_NUM = @internalLineNum;

        SELECT @newInternalLineNum = SCOPE_IDENTITY();

        IF @newInternalLineNum IS NULL
        BEGIN
            SET @errorMessage = CONCAT(N'TransferRejectedDetail failed to create new shipment detail line for source line ',
                                       @internalLineNum);
            THROW 50000, @errorMessage, 1;
        END
         exec STH_UpdateHeader @iIntShipNum=@toShipNum;
     
        UPDATE SHIPMENT_DETAIL
        SET STATUS1 = @rejStatus,
         TOTAL_QTY = 0, TOTAL_VOLUME = 0, TOTAL_WEIGHT = 0, VALUE = 0, DATE_TIME_STAMP = GETUTCDATE()
        WHERE INTERNAL_SHIPMENT_LINE_NUM = @internalLineNum;


        DECLARE @iIntShipNum INT;

SELECT @iIntShipNum = INTERNAL_SHIPMENT_NUM
FROM SHIPMENT_DETAIL
WHERE INTERNAL_SHIPMENT_LINE_NUM = @internalLineNum;

EXEC STH_UpdateHeader
    @iIntShipNum = @iIntShipNum;

INSERT INTO COMMENT_TEXT
            (COMMENT_TYPE,
             DATE_TIME_STAMP,
             INTERNAL_LINE_NUM,
             INTERNAL_NUM,
             PROCESS_STAMP,
             RECORD_TYPE,
             TEXT,
             USER_DEF1,
             USER_DEF2,
             USER_DEF3,
             USER_DEF4,
             USER_DEF5,
             USER_DEF6,
             USER_DEF7,
             USER_DEF8,
             USER_STAMP)
        SELECT COMMENT_TYPE,
               GETUTCDATE(),
               @newInternalLineNum,
               @toShipNum,
               PROCESS_STAMP,
               RECORD_TYPE,
               TEXT,
               USER_DEF1,
               USER_DEF2,
               USER_DEF3,
               USER_DEF4,
               USER_DEF5,
               USER_DEF6,
               USER_DEF7,
               USER_DEF8,
               USER_STAMP
        FROM COMMENT_TEXT
        WHERE INTERNAL_LINE_NUM = @internalLineNum
          AND RECORD_TYPE = N'SHIPMENT';

        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0
            ROLLBACK TRANSACTION;

        THROW;
    END CATCH
END
