CREATE PROCEDURE EX06ValidateMOPNum_Weights(
@MOPNumber NVARCHAR(50)
)
AS
DECLARE @PalletNumber NVARCHAR(25);
DECLARE @PalletWeight DECIMAL(9,3);
DECLARE @stErrorText NVARCHAR(MAX);
DECLARE @stResult NVARCHAR(MAX);

IF EXISTS(SELECT 1 FROM multi_order_pallet WITH(NOLOCK) WHERE MULTI_ORDER_PALLET_ID = @MOPNumber)
BEGIN

IF EXISTS(select 1 from SHIPPING_CONTAINER where INTERNAL_MOP_NUMBER=(select INTERNAL_MOP_NUMBER FROM MULTI_ORDER_PALLET WHERE MULTI_ORDER_PALLET_ID=@MOPNumber) and status<900)
BEGIN
SELECT @PalletNumber=USER_DEF1,@PalletWeight=USER_DEF7 FROM multi_order_pallet where MULTI_ORDER_PALLET_ID = @MOPNumber;

select @MOPNumber AS MOPNumber,@PalletNumber As PalletNumber,@PalletWeight As PalletWeight;
END

ELSE
BEGIN
			SET @stResult = N'MSG_EX06_INVALIDMOP_NUM';
			SELECT @stErrorText = ISNULL(TEXT, N'') FROM RESOURCE_FILE_CUSTOM WITH(NOLOCK) WHERE RESOURCE_KEY = N'MSG_EX06_INVALIDMOP_NUM' 
			AND RESOURCE_GROUP = N'Msg' AND RESOURCE_LANGUAGE = N'en-US';

			SELECT @stResult AS RESULT, @stErrorText AS ERRORTEXT;
END

END




