/*
	Task	| By	| Date		| Modification Description
	--------------------------------------------------------------------
	251336	| MGK	| 05/15/20	| Created
	254391	| MGK	| 07/02/20	| Modified as ALTER script & removed dbo

*/

CREATE PROCEDURE wm_RPurchaseOrderDetail04
	@PurchaseOrderId nvarchar(25),
	@LineNumber numeric(19,5),
	@Warehouse nvarchar(25)
AS
	SELECT 
		POD.*,
		POH.CLOSED_DATE_TIME,
		POH.CREATED_DATE_TIME,
		POH.RECEIPT_TYPE,
		POH.SHIP_FROM,
		POH.SHIP_FROM_ADDRESS1,
		POH.SHIP_FROM_ADDRESS2,
		POH.SHIP_FROM_ADDRESS3,
		POH.SHIP_FROM_CITY,
		POH.SHIP_FROM_STATE,
		POH.SHIP_FROM_COUNTRY,
		POH.SHIP_FROM_POSTAL_CODE,
		POH.SHIP_FROM_NAME,
		POH.SHIP_FROM_ATTENTION_TO,
		POH.SHIP_FROM_EMAIL_ADDRESS,
		POH.SHIP_FROM_PHONE_NUM,
		POH.SHIP_FROM_FAX_NUM,
		POH.SOURCE_ID,
		POH.SOURCE_NAME,
		POH.SOURCE_ADDRESS1,
		POH.SOURCE_ADDRESS2,
		POH.SOURCE_ADDRESS3,
		POH.SOURCE_CITY,
		POH.SOURCE_STATE,
		POH.SOURCE_POSTAL_CODE,
		POH.SOURCE_COUNTRY,
		POH.SOURCE_ATTENTION_TO,
		POH.SOURCE_PHONE_NUM,
		POH.SOURCE_FAX_NUM,
		POH.SOURCE_EMAIL_ADDRESS,
		POH.STATUS,
		POH.WAREHOUSE
	  FROM PURCHASE_ORDER_DETAIL POD, PURCHASE_ORDER_HEADER POH
	 WHERE 
			POD.PURCHASE_ORDER_OBJECT_ID = POH.OBJECT_ID
			AND POD.PURCHASE_ORDER_ID =@PurchaseOrderId
	        AND LINE_NUMBER = @LineNumber
			AND POH.WAREHOUSE=@Warehouse
			AND CLOSED_DATE_TIME IS NULL;