/*
	Task	| By	| Date			| Modification Description
	-------------------------------------------------
	100866	| MMM	| 07/30/2012	| Created.
	110834	| SHS	| 05/07/2013	| Modified Wave Activity section to get the correct Total_Shipments and Total_Lines count
*/	

CREATE PROCEDURE PMN_ActivitySummary (
	@startDateTime datetime,
	@endDateTime datetime
	)
AS
 
-- WAVE ACTIVITY
SELECT ISNULL(SUM(S),0) AS TOTAL_SHIPMENTS_WAVED, ISNULL(SUM(L),0) AS TOTAL_LINES_WAVED, ISNULL(SUM(C),0) AS TOTAL_CONTAINERS_WAVED FROM
(
SELECT ISNULL(TOTAL_SHIPMENTS,0) AS S, ISNULL(TOTAL_LINES,0) AS L,
	(
	SELECT COUNT(*) FROM SHIPPING_CONTAINER SC WHERE SC.LAUNCH_NUM = LS.INTERNAL_LAUNCH_NUM AND SC.CONTAINER_TYPE != N'-'
	) AS C
FROM LAUNCH_STATISTICS LS 
WHERE LS.LAUNCH_DATE_TIME_STARTED >= @startDateTime  
	AND LS.LAUNCH_DATE_TIME_ENDED <= @endDateTime 
) T;
 
-- RECEIPT ACTIVITY
SELECT ISNULL(COUNT(DISTINCT TH.REFERENCE_ID+CAST(TH.REFERENCE_LINE_NUM AS NVARCHAR)), 0) AS TOTAL_LINES_RECEIVED, 
	ISNULL(COUNT(DISTINCT TH.CONTAINER_ID), 0) AS TOTAL_CONTAINERS_RECEIVED 
FROM TRANSACTION_HISTORY TH 
WHERE TH.TRANSACTION_TYPE = N'20' 
	AND TH.ACTIVITY_DATE_TIME BETWEEN @startDateTime AND @endDateTime;
 
-- PICKING ACTIVITY
SELECT WIV.INTERNAL_NUM_TYPE, 
	ISNULL(COUNT(DISTINCT INTERNAL_INSTRUCTION_NUM), 0) AS TOTAL_INSTRUCTIONS_COMPLETED 
FROM WORK_INSTRUCTION_VIEW WIV 
WHERE WIV.INSTRUCTION_TYPE = N'DETAIL' 
	AND WIV.END_DATE_TIME BETWEEN @startDateTime AND @endDateTime 
GROUP BY WIV.INTERNAL_NUM_TYPE
 
-- SHIPPING ACTIVITY
SELECT ISNULL(COUNT(DISTINCT SHV.SHIPPING_LOAD_NUM), 0) AS TOTAL_LOADS_WITH_SHIPMENTS_CONFIRMED, 
	ISNULL(COUNT(DISTINCT SHV.INTERNAL_SHIPMENT_NUM), 0) AS TOTAL_SHIPMENTS_CONFIRMED, 
	ISNULL(SUM(ISNULL(SHV.TOTAL_LINES, 0)), 0) AS TOTAL_LINES_CONFIRMED, 
	ISNULL(SUM(ISNULL(SHV.TOTAL_CONTAINERS, 0)), 0) AS TOTAL_CONTAINERS_CONFIRMED 
FROM SHIPMENT_HEADER_VIEW SHV 
WHERE SHV.ACTUAL_SHIP_DATE_TIME BETWEEN @startDateTime AND @endDateTime;
 
-- CREATION ACTIVITY
SELECT ISNULL(COUNT(DISTINCT SHV.INTERNAL_SHIPMENT_NUM), 0) AS TOTAL_SHIPMENTS_CREATED, 
	ISNULL(SUM(ISNULL(SHV.TOTAL_LINES, 0)), 0) AS TOTAL_SHIPMENT_LINES_CREATED 
FROM SHIPMENT_HEADER_VIEW SHV 
WHERE SHV.CREATION_DATE_TIME_STAMP BETWEEN @startDateTime AND @endDateTime;

SELECT ISNULL(COUNT(DISTINCT RH.INTERNAL_RECEIPT_NUM), 0) AS TOTAL_RECEIPTS_CREATED, 
	ISNULL(SUM(ISNULL(RH.TOTAL_LINES, 0)),0) AS TOTAL_RECEIPT_LINES_CREATED 
FROM RECEIPT_HEADER RH 
WHERE RH.CREATION_DATE_TIME_STAMP BETWEEN @startDateTime AND @endDateTime;
