/*
	Task	| By	| Date		| Modification Description
	--------------------------------------------------------------------
	182443	| SSD	| 07/26/16	| Created
	188561	| AU	| 10/12/16	| Added a summary tile
	202320  | AH    | 04/13/17  | Ordering customer names by INTERNAL_SHIPMENT_NUM
	216453	| MJ	| 12/11/17	| Modified to make db compatible with Azure SQL.
	
*/

CREATE PROCEDURE SHP_MonitorCustomerCategoryChartData
@filterCriteria NVARCHAR(MAX),
@culture NVARCHAR(10) 
AS
    SET NOCOUNT ON
	DECLARE @warehouse as NVARCHAR(50);
	DECLARE @customerCat1 as NVARCHAR(50);
  
	DECLARE @criteriaTempTable TABLE (
   filterName NVARCHAR(300),
   filterValue NVARCHAR(300))

 /*get the where clause value*/
  INSERT INTO @criteriaTempTable SELECT * FROM fn_GetMonitorFilterParameters(@filterCriteria)

  SELECT @warehouse = filterValue FROM @criteriaTempTable WHERE filterName = N'WAREHOUSE'
  SELECT @customerCat1 = filterValue from @criteriaTempTable WHERE filterName = N'customer_Category1'

   DECLARE @Unassign NVARCHAR(2000);
  SET @Unassign=  dbo.RSCMfn_RtrvResource(N'UNASSIGNED',N'text',@culture)

   IF(@customerCat1 = @Unassign)
	SET @customerCat1 = NULL;

SELECT N'CHARTDATA_MonitorCustomerCategory' AS CHARTDATA_MonitorCustomerCategory, 
CATEGORY = CASE WHEN  CUSTOMER_NAME IS NULL THEN dbo.RSCMfn_RtrvResource(N'UNASSIGNED',N'text',@culture) ELSE  CUSTOMER_NAME END,
COUNT(DISTINCT(INTERNAL_SHIPMENT_NUM)) AS N'DATA' ,
DESCRIPTION = CASE WHEN  CUSTOMER_NAME IS NULL THEN NULL ELSE CUSTOMER_NAME END,
N'CUSTOMERNAME' AS XAXISTITLE, 
N'SHIPMENTS' AS YAXISTITLE, 
2 AS NextDrillDownLevel, 
N'SHIPBYCUSTNAME' AS CHARTTITLE
FROM Metadata_Insight_Shipment_View WHERE WAREHOUSE=@warehouse AND 
((@customerCat1 is null AND CUSTOMER_CATEGORY1 is null ) OR CUSTOMER_CATEGORY1=@customerCat1) AND SHIPMENT_HEADER_TRAILING_STS <900 
GROUP BY CUSTOMER_NAME 
order  by COUNT(DISTINCT(INTERNAL_SHIPMENT_NUM)) DESC,CUSTOMER_NAME 

/* SUMMARY TILES START */
DECLARE @TOTAL_SHIPMENTS INT=0,@TOTAL_SHIPPING_LOAD INT=0,@WIP_SHIPMENTS INT=0,@SHIPMENT_NOT_PICKING INT=0;

SELECT @TOTAL_SHIPMENTS = COUNT(DISTINCT(INTERNAL_SHIPMENT_NUM)) ,
	   @TOTAL_SHIPPING_LOAD =COUNT(DISTINCT(SHIPPING_LOAD_NUM)) FROM Metadata_Insight_Shipment_View WHERE WAREHOUSE=@warehouse and ((@customerCat1 is null AND CUSTOMER_CATEGORY1 is null ) OR CUSTOMER_CATEGORY1=@customerCat1) AND SHIPMENT_HEADER_TRAILING_STS <900 ;
SELECT @WIP_SHIPMENTS =COUNT(DISTINCT(INTERNAL_SHIPMENT_NUM)) FROM Metadata_Insight_Shipment_View WHERE WAREHOUSE=@warehouse  AND ((@customerCat1 is null AND CUSTOMER_CATEGORY1 is null ) OR CUSTOMER_CATEGORY1=@customerCat1) 
AND SHIPMENT_HEADER_LEADING_STS>300 AND SHIPMENT_HEADER_TRAILING_STS <700 ;
SELECT @SHIPMENT_NOT_PICKING=COUNT(DISTINCT(INTERNAL_SHIPMENT_NUM)) FROM Metadata_Insight_Shipment_View WHERE WAREHOUSE=@warehouse 
AND ((@customerCat1 is null AND CUSTOMER_CATEGORY1 is null ) OR CUSTOMER_CATEGORY1=@customerCat1)
AND SHIPMENT_HEADER_TRAILING_STS =300 AND SHIPMENT_HEADER_LEADING_STS =300;

SELECT TOP 1 N'SUMMARYTILE_TOTAL_SHIPMENTS' AS SUMMARYTILE_TOTAL_SHIPMENTS,  @TOTAL_SHIPMENTS AS TOTAL_SHIPMENTS;
SELECT TOP 1 N'SUMMARYTILE_TOTAL_SHIPPING_LOADS' AS SUMMARYTILE_TOTAL_SHIPPING_LOADS,  @TOTAL_SHIPPING_LOAD AS TOTAL_SHIPPING_LOADS;
SELECT TOP 1 N'SUMMARYTILE_WIP_SHIPMENTS' AS SUMMARYTILE_WIP_SHIPMENTS,  @WIP_SHIPMENTS AS WIP_SHIPMENTS;
SELECT TOP 1 N'SUMMARYTILE_SHIPMENTS_NOT_STARTED_PICKING' AS SUMMARYTILE_SHIPMENTS_NOT_STARTED_PICKING, @SHIPMENT_NOT_PICKING AS SHIPMENTS_NOT_STARTED_PICKING;