/*
	Task	| By	| Date		| Modification Description
	--------------------------------------------------------------------
	182443	| SSD	| 07/26/16	| Created
	185988	| SSD	| 08/26/16	| Modified Chart title
	188561	| AU	| 10/12/16	| Added a summary tile
	
*/

CREATE PROCEDURE SHP_MonitorShipmentChartData
@filterCriteria NVARCHAR(MAX),
@culture NVARCHAR(10) 
AS
    SET NOCOUNT ON
	DECLARE @warehouse as NVARCHAR(50);
	DECLARE @criteriaTempTable TABLE (
   filterName NVARCHAR(300),
   filterValue NVARCHAR(300))

 /*get the where clause value*/
  INSERT INTO @criteriaTempTable SELECT * FROM fn_GetMonitorFilterParameters(@filterCriteria)

  SELECT @warehouse = filterValue FROM @criteriaTempTable WHERE filterName = N'WAREHOUSE'

SELECT N'CHARTDATA_MonitorShipment' AS CHARTDATA_MonitorShipment,  
CATEGORY = CASE WHEN  CUSTOMER_CATEGORY1 IS NULL THEN dbo.RSCMfn_RtrvResource(N'UNASSIGNED',N'text',@culture) ELSE  CUSTOMER_CATEGORY1 END,
COUNT(DISTINCT(INTERNAL_SHIPMENT_NUM)) AS N'DATA' ,
DESCRIPTION = CASE WHEN  CUSTOMER_CATEGORY1 IS NULL THEN N'' ELSE CUSTOMER_CATEGORY1 END,
N'CUSTOMERCATEGORY1' AS XAXISTITLE, 
N'SHIPMENTS' AS YAXISTITLE, 
1 AS NextDrillDownLevel, 
N'SHIPMENTSBY+CUSTOMERCATEGORY1' AS CHARTTITLE
FROM Metadata_Insight_Shipment_View WHERE WAREHOUSE=@warehouse and SHIPMENT_HEADER_TRAILING_STS < 900  GROUP BY  CUSTOMER_CATEGORY1

/* SUMMARY TILES START */
DECLARE @TOTAL_SHIPMENTS INT=0,@TOTAL_SHIPPING_LOAD INT=0,@WIP_SHIPMENTS INT=0,@SHIPMENT_NOT_PICKING INT=0;

SELECT @TOTAL_SHIPMENTS = COUNT(DISTINCT(INTERNAL_SHIPMENT_NUM)) ,
	   @TOTAL_SHIPPING_LOAD =COUNT(DISTINCT(SHIPPING_LOAD_NUM)) FROM Metadata_Insight_Shipment_View WHERE WAREHOUSE=@warehouse and SHIPMENT_HEADER_TRAILING_STS <900 ;
SELECT @WIP_SHIPMENTS =COUNT(DISTINCT(INTERNAL_SHIPMENT_NUM)) FROM Metadata_Insight_Shipment_View WHERE WAREHOUSE=@warehouse AND SHIPMENT_HEADER_LEADING_STS>300 AND SHIPMENT_HEADER_TRAILING_STS <700; 
SELECT @SHIPMENT_NOT_PICKING=COUNT(DISTINCT(INTERNAL_SHIPMENT_NUM)) FROM Metadata_Insight_Shipment_View WHERE WAREHOUSE=@warehouse AND SHIPMENT_HEADER_TRAILING_STS =300 AND SHIPMENT_HEADER_LEADING_STS =300;

SELECT TOP 1 N'SUMMARYTILE_TOTAL_SHIPMENTS' AS SUMMARYTILE_TOTAL_SHIPMENTS,  @TOTAL_SHIPMENTS AS TOTAL_SHIPMENTS;
SELECT TOP 1 N'SUMMARYTILE_TOTAL_SHIPPING_LOADS' AS SUMMARYTILE_TOTAL_SHIPPING_LOADS,  @TOTAL_SHIPPING_LOAD AS TOTAL_SHIPPING_LOADS;
SELECT TOP 1 N'SUMMARYTILE_WIP_SHIPMENTS' AS SUMMARYTILE_WIP_SHIPMENTS,  @WIP_SHIPMENTS AS WIP_SHIPMENTS;
SELECT TOP 1 N'SUMMARYTILE_SHIPMENTS_NOT_STARTED_PICKING' AS SUMMARYTILE_SHIPMENTS_NOT_STARTED_PICKING, @SHIPMENT_NOT_PICKING AS SHIPMENTS_NOT_STARTED_PICKING;
