/*
	Task	| By	| Date			| Modification Description
	-------------------------------------------------
	100866	| MMM	| 07/30/2012	| Created.
*/	

CREATE PROCEDURE PMN_ReceiptsCreatedActivity (
	@startDateTime datetime,
	@endDateTime datetime
	)
AS
 
WITH INTERVALTABLE
AS
(
	SELECT @startDateTime AS INTERVAL_DATE_TIME
	
	UNION ALL
	
	SELECT DATEADD(SS, 30, INTERVAL_DATE_TIME)
	FROM INTERVALTABLE
	WHERE DATEADD(SS, 30, INTERVAL_DATE_TIME) < @endDateTime
) 
 
SELECT INTERVALTABLE.INTERVAL_DATE_TIME, 
	ISNULL(COUNT(DISTINCT RH.INTERNAL_RECEIPT_NUM), 0) AS RECEIPTS_CREATED, 
	SUM(ISNULL(RH.TOTAL_LINES, 0)) AS RECEIPT_LINES_CREATED 
FROM INTERVALTABLE LEFT OUTER JOIN RECEIPT_HEADER RH 
	ON RH.CREATION_DATE_TIME_STAMP >= DATEADD(SS, -30, INTERVALTABLE.INTERVAL_DATE_TIME) 
	AND RH.CREATION_DATE_TIME_STAMP < INTERVALTABLE.INTERVAL_DATE_TIME 
GROUP BY INTERVALTABLE.INTERVAL_DATE_TIME
ORDER BY INTERVALTABLE.INTERVAL_DATE_TIME
OPTION (MAXRECURSION 0)


