/*
	Task	| By	| Date			| Modification Description
	-------------------------------------------------
	100866	| MMM	| 07/30/2012	| Created.
*/	

CREATE PROCEDURE PMN_ShipmentsCreatedActivity (
	@startDateTime datetime,
	@endDateTime datetime
	)
AS
 
WITH INTERVALTABLE
AS
(
	SELECT @startDateTime AS INTERVAL_DATE_TIME
	
	UNION ALL
	
	SELECT DATEADD(SS, 30, INTERVAL_DATE_TIME)
	FROM INTERVALTABLE
	WHERE DATEADD(SS, 30, INTERVAL_DATE_TIME) < @endDateTime
) 
 
SELECT INTERVALTABLE.INTERVAL_DATE_TIME, 
	ISNULL(COUNT(DISTINCT SHV.INTERNAL_SHIPMENT_NUM), 0) AS SHIPMENTS_CREATED, 
	SUM(ISNULL(SHV.TOTAL_LINES, 0)) AS SHIPMENT_LINES_CREATED 
FROM INTERVALTABLE 
LEFT OUTER JOIN SHIPMENT_HEADER_VIEW SHV 
	ON SHV.CREATION_DATE_TIME_STAMP >= DATEADD(SS, -30, INTERVALTABLE.INTERVAL_DATE_TIME) 
	AND SHV.CREATION_DATE_TIME_STAMP < INTERVALTABLE.INTERVAL_DATE_TIME 
GROUP BY INTERVALTABLE.INTERVAL_DATE_TIME 
ORDER BY INTERVALTABLE.INTERVAL_DATE_TIME
OPTION (MAXRECURSION 0)


