/*
	Task	| By	| Date			| Modification Description
	-------------------------------------------------
	100866	| MMM	| 07/30/2012	| Created.
*/	

CREATE PROCEDURE PMN_UserActivity (
	@startDateTime datetime,
	@endDateTime datetime
	)
AS
 
WITH INTERVALTABLE
AS
(
	SELECT @startDateTime AS INTERVAL_DATE_TIME
	
	UNION ALL
	
	SELECT DATEADD(SS, 30, INTERVAL_DATE_TIME)
	FROM INTERVALTABLE
	WHERE DATEADD(SS, 30, INTERVAL_DATE_TIME) < @endDateTime
) 
 
SELECT INTERVALTABLE.INTERVAL_DATE_TIME, 
	SUM(CASE WHEN UA.USER_TYPE = N'FULLSCREEN' THEN 1 ELSE 0 END) AS TOTAL_FS_USERS, 
	SUM(CASE WHEN UA.USER_TYPE = N'RF' THEN 1 ELSE 0 END) AS TOTAL_RF_USERS, 
	SUM(CASE WHEN UA.USER_TYPE = N'VOCOLLECT' THEN 1 ELSE 0 END) AS TOTAL_VOCOLLECT_USERS 
FROM INTERVALTABLE 
LEFT OUTER JOIN USER_ACTIVITY UA 
	ON UA.LOGON_DATE_TIME <= INTERVALTABLE.INTERVAL_DATE_TIME 
	AND (UA.LOGOFF_DATE_TIME IS NULL OR  UA.LOGOFF_DATE_TIME >= INTERVALTABLE.INTERVAL_DATE_TIME)
GROUP BY INTERVALTABLE.INTERVAL_DATE_TIME 
ORDER BY INTERVALTABLE.INTERVAL_DATE_TIME
OPTION (MAXRECURSION 0)
