

CREATE PROCEDURE [dbo].[TRAV_EXEC_PROC]
	 @InvlocNumbers NVARCHAR(MAX),  
	 @Warehouse NVARCHAR(50),
	@success NVARCHAR(50) OUTPUT,  
	@error NVARCHAR(50) OUTPUT,
	@Username NVARCHAR (max)
AS
BEGIN


	    DECLARE @SQL NVARCHAR(MAX) = N'


CREATE view TRAV_METADATA_INSIGHT_SHIPPING_CONTAINER_VIEW AS 
SELECT   sc.INTERNAL_SHIPMENT_NUM, sc.warehouse, sh.SHIPPING_LOAD_NUM, sh.SHIPMENT_ID, sh.LAUNCH_STEP, sh.TRAILING_STS AS SHIPMENT_HEADER_TRAILING_STS, sh.TRAILING_STS_DATE AS SHIPMENT_HEADER_TRAILING_STS_DATE, sh.TRAILING_STS_FAILED AS SHIPMENT_HEADER_TRAILING_STS_FAILED, 
             sh.ORDER_TYPE AS SHIPMENT_HEADER_ORDER_TYPE, sh.CONSOLIDATED, sh.LEADING_STS AS SHIPMENT_HEADER_LEADING_STS, sh.LEADING_STS_DATE AS SHIPMENT_HEADER_LEADING_STS_DATE, sh.CARRIER AS SHIPMENT_HEADER_CARRIER, sh.LEADING_STS_FAILED AS SHIPMENT_HEADER_LEADING_STS_FAILED, 
             sc.COMPANY, sh.CARRIER_SERVICE, sh.CARRIER_GROUP, sh.CARRIER_TYPE, sh.FREIGHT_TERMS, sh.LIABILITY_TERMS, sh.CUSTOMER, sh.SHIP_TO, sh.ROUTE AS SHIPMENT_HEADER_ROUTE, sh.STOP, sh.SHIP_TO_ADDRESS1, sh.CUSTOMER_NAME, sh.SHIP_TO_ADDRESS2, sh.SHIP_TO_ADDRESS3, sh.SHIP_TO_CITY, 
             sh.SHIP_TO_STATE, sh.SHIP_TO_COUNTRY, sh.SHIP_TO_POSTAL_CODE, sh.SHIP_TO_PHONE_NUM, sh.SHIP_TO_FAX_NUM, sh.CUSTOMER_ADDRESS1, sc.LAUNCH_NUM, sh.WEIGHT_UM AS SHIPMENT_HEADER_WEIGHT_UM, sh.VOLUME_UM AS SHIPMENT_HEADER_VOLUME_UM, sh.ROUTING_CODE, sh.SINGLE_ITEM_CARTONS, 
             sh.USER_DEF1 AS SHIPMENT_HEADER_USER_DEF1, sh.USER_DEF2 AS SHIPMENT_HEADER_USER_DEF2, sh.PRIORITY AS SHIPMENT_HEADER_PRIORITY, sh.USER_DEF3 AS SHIPMENT_HEADER_USER_DEF3, sh.USER_DEF4 AS SHIPMENT_HEADER_USER_DEF4, sh.USER_DEF5 AS SHIPMENT_HEADER_USER_DEF5, 
             sh.USER_DEF6 AS SHIPMENT_HEADER_USER_DEF6, sh.USER_DEF7 AS SHIPMENT_HEADER_USER_DEF7, sh.MANUALLY_ENTERED AS SHIPMENT_HEADER_MANUALLY_ENTERED, sh.USER_DEF8 AS SHIPMENT_HEADER_USER_DEF8, sh.USER_STAMP AS SHIPMENT_HEADER_USER_STAMP, 
             sh.PROCESS_STAMP AS SHIPMENT_HEADER_PROCESS_STAMP, sh.DATE_TIME_STAMP AS SHIPMENT_HEADER_DATE_TIME_STAMP, sh.BOL_NUM_ALPHA, sh.PRO_NUM_ALPHA AS SHIPMENT_HEADER_PRO_NUM_ALPHA, sh.CUSTOMER_ADDRESS3, sh.CUSTOMER_ADDRESS2, sh.CUSTOMER_ATTENTION_TO, sh.CUSTOMER_CITY, 
             sh.CUSTOMER_STATE, sh.CUSTOMER_COUNTRY, sh.CUSTOMER_POSTAL_CODE, sh.CUSTOMER_PHONE_NUM, sh.CUSTOMER_FAX_NUM, sh.CUSTOMER_EMAIL_ADDRESS, sh.SHIP_TO_NAME, sh.SHIP_TO_ATTENTION_TO, sh.SHIP_TO_EMAIL_ADDRESS, sh.REQUESTED_DELIVERY_DATE, sh.REQUESTED_DELIVERY_TYPE, 
             sh.SCHEDULED_SHIP_DATE, sh.PLANNED_SHIP_DATE, sh.ACTUAL_SHIP_DATE_TIME AS SHIPMENT_HEADER_ACTUAL_SHIP_DATE_TIME, sh.PLANNED_DELIVERY_DATE_TIME, sh.ACTUAL_DELIVERY_DATE_TIME, sh.QUANTITY_UM, sh.TOTAL_FREIGHT_CHARGE AS SHIPMENT_HEADER_TOTAL_FREIGHT_CHARGE, 
             sh.BASE_FREIGHT_CHARGE AS SHIPMENT_HEADER_BASE_FREIGHT_CHARGE, sh.FREIGHT_DISCOUNT AS SHIPMENT_HEADER_FREIGHT_DISCOUNT, sh.ACCESSORIAL_CHARGE AS SHIPMENT_HEADER_ACCESSORIAL_CHARGE, sh.CONSOLIDATION_ALLOWED, sh.INTERMEDIATE_CONSIGNEE, sh.INTERMEDIATE_NAME, 
             sh.INTERMEDIATE_ADDRESS1, sh.INTERMEDIATE_ADDRESS2, sh.INTERMEDIATE_ADDRESS3, sh.INTERMEDIATE_ATTENTION_TO, sh.INTERMEDIATE_CITY, sh.INTERMEDIATE_STATE, sh.INTERMEDIATE_COUNTRY, sh.INTERMEDIATE_POSTAL_CODE, sh.INTERMEDIATE_PHONE_NUM, sh.INTERMEDIATE_FAX_NUM, 
             sh.INTERMEDIATE_EMAIL_ADDRESS, sh.FREIGHT_BILL_TO, sh.FREIGHT_BILL_TO_NAME, sh.FREIGHT_BILL_TO_ADDRESS1, sh.FREIGHT_BILL_TO_ADDRESS2, sh.FREIGHT_BILL_TO_ADDRESS3, sh.FREIGHT_BILL_TO_ATTENTION_TO, sh.FREIGHT_BILL_TO_CITY, sh.FREIGHT_BILL_TO_STATE, sh.FREIGHT_BILL_TO_COUNTRY, 
             sh.FREIGHT_BILL_TO_POSTAL_CODE, sh.FREIGHT_BILL_TO_PHONE_NUM, sh.FREIGHT_BILL_TO_FAX_NUM, sh.FREIGHT_BILL_TO_EMAIL_ADDRESS, sh.ERP_ORDER AS SHIPMENT_HEADER_ERP_ORDER, sh.INTERNAL_ORDER_NUM, sh.EXPORT_TAX_ID, sh.PARTIES, sh.LOADING_PIER, sh.TRANSPORTATION_MODE, 
             sh.EXPORT_PORT, sh.UNLOADING_PORT, sh.CONTAINERIZED, sh.FTZ, sh.VALIDATED_LICENSE AS SHIPMENT_HEADER_VALIDATED_LICENSE, sh.LICENSE_EXP_DATE, sh.ECCN AS SHIPMENT_HEADER_ECCN, sh.AUTHORIZED_EMPL_NAME, sh.AUTHORIZED_EMPL_TITLE, sh.UPLOAD_INTERFACE_BATCH, 
             sh.CUSTOMER_RESIDENTIAL_FLAG, sh.SHIPTO_RESIDENTIAL_FLAG, sh.REJECTION_NOTE, sh.INTERFACE_RECORD_ID AS SHIPMENT_HEADER_INTERFACE_RECORD_ID, sh.CUSTOMER_CATEGORY1, sh.CUSTOMER_CATEGORY2, sh.CUSTOMER_CATEGORY3, sh.CUSTOMER_CATEGORY4, sh.CUSTOMER_CATEGORY5, 
             sh.CUSTOMER_CATEGORY6, sh.CUSTOMER_CATEGORY7, sh.CUSTOMER_CATEGORY8, sh.CUSTOMER_CATEGORY9, sh.CUSTOMER_CATEGORY10, sh.CONSOLIDATION_DOCK_LOC_AREA, sh.CONSOLIDATION_DOCK_LOC_POS, sh.PROCESS_TYPE, sh.CREATION_PROCESS_STAMP, sh.CREATION_DATE_TIME_STAMP, 
             sh.IMMEDIATE_NEEDS_NOTE AS SHIPMENT_HEADER_IMMEDIATE_NEEDS_NOTE, sh.ALLOCATE_COMPLETE, sh.ALTERNATE_EMAIL_ADDRESS, sh.STOP_SEQUENCE, sh.INTERNAL_CARRIER_NUM, sh.STORE_DISTRIBUTION AS SHIPMENT_HEADER_STORE_DISTRIBUTION, sh.TOTAL_LBR_ESTIMATE, 
             CASE WHEN sh.LOCKED = N''Y'' THEN 1 ELSE 0 END AS LOCKED, sh.SHIPPER_CODE, sh.IN_DELETION, sh.INVENTORY_LOAD_CONFIRMED, sh.LAST_STATUS_UPLOADED AS SHIPMENT_HEADER_LAST_STATUS_UPLOADED, sh.USER_DEF9 AS SHIPMENT_HEADER_USER_DEF9, sh.USER_DEF10 AS SHIPMENT_HEADER_USER_DEF10, 
             sh.USER_DEF11 AS SHIPMENT_HEADER_USER_DEF11, sh.USER_DEF12 AS SHIPMENT_HEADER_USER_DEF12, sh.USER_DEF13 AS SHIPMENT_HEADER_USER_DEF13, sh.USER_DEF14 AS SHIPMENT_HEADER_USER_DEF14, sh.USER_DEF15 AS SHIPMENT_HEADER_USER_DEF15, 
             sh.USER_DEF16 AS SHIPMENT_HEADER_USER_DEF16, sh.USER_DEF17_DATE_TIME AS SHIPMENT_HEADER_USER_DEF17_DATE_TIME, sh.USER_DEF18_DATE_TIME AS SHIPMENT_HEADER_USER_DEF18_DATE_TIME, sh.USER_DEF19_DATE_TIME AS SHIPMENT_HEADER_USER_DEF19_DATE_TIME, 
             sh.USER_DEF20_DATE_TIME AS SHIPMENT_HEADER_USER_DEF20_DATE_TIME, sc.ITEM, sc.INTERNAL_CONTAINER_NUM, sc.CONTAINER_ID, sc.CONTAINER_TYPE, sc.CONTAINER_CLASS, sc.status AS SHIPPING_CONTAINER_STATUS, sc.STATUS_FAILED AS SHIPPING_CONTAINER_STATUS_FAILED, 
             sc.status AS SHIPPING_CONTAINER_STATUS_CLOSED, CASE WHEN sc.PARENT IS NULL THEN 0 ELSE sc.PARENT END AS PARENT, sc.WEIGHT, CEILING(sc.Weight) AS Rounded_Weight, sc.VOLUME, sc.LENGTH, sc.WIDTH, sc.HEIGHT, sc.VALUE AS SHIPPING_CONTAINER_VALUE, sc.QUANTITY, sc.STATUS_FLOW_NAME AS SHIPPING_CONTAINER_STATUS_FLOW_NAME, 
             sc.HAZARDOUS_CODE AS SHIPPING_CONTAINER_HAZARDOUS_CODE, sc.MANIFEST_STATE, sc.MANIFEST_CARR_SERVICE_SYMBOL, sc.MANIFEST_DATE_TIME, sc.TRACKING_NUMBER, sc.TOTAL_FREIGHT_CHARGE AS SHIPPING_CONTAINER_TOTAL_FREIGHT_CHARGE, 
             sc.BASE_FREIGHT_CHARGE AS SHIPPING_CONTAINER_BASE_FREIGHT_CHARGE, sc.FREIGHT_DISCOUNT AS SHIPPING_CONTAINER_FREIGHT_DISCOUNT, sc.ACCESSORIAL_CHARGE AS SHIPPING_CONTAINER_ACCESSORIAL_CHARGE, sc.USER_DEF1 AS SHIPPING_CONTAINER_USER_DEF1, 
             sc.USER_DEF2 AS SHIPPING_CONTAINER_USER_DEF2, sc.USER_DEF3 AS SHIPPING_CONTAINER_USER_DEF3, sc.USER_DEF4 AS SHIPPING_CONTAINER_USER_DEF4, sc.USER_DEF5 AS SHIPPING_CONTAINER_USER_DEF5, sc.USER_DEF6 AS SHIPPING_CONTAINER_USER_DEF6, 
             sc.USER_DEF7 AS SHIPPING_CONTAINER_USER_DEF7, sc.USER_DEF8 AS SHIPPING_CONTAINER_USER_DEF8, sc.USER_STAMP AS SHIPPING_CONTAINER_USER_STAMP, sc.PROCESS_STAMP AS SHIPPING_CONTAINER_PROCESS_STAMP, sc.DATE_TIME_STAMP AS SHIPPING_CONTAINER_DATE_TIME_STAMP, 
             sc.MANIFEST_FOR_DATE, sc.TREE_UNIT, sc.BUNDLE_ID, sc.MSN, sc.LOCATION, sc.GROUP_POSITION, sc.CONTAINER_COUNT_NUMBER, sc.CONTAINER_COUNT_TOTAL, sc.GROUP_NUM, sc.WORK_ZONE, sc.INTERFACE_RECORD_ID AS SHIPPING_CONTAINER_INTERFACE_RECORD_ID, 
             parentContainer.CONTAINER_ID AS PARENT_CONTAINER_ID, sc.INTERNAL_SHIP_ALLOC_NUM, sc.WORK_CREATED, sc.HUNDREDWEIGHT, sc.MANIFEST_ID, sc.MANIFEST_CLOSE_DATE_TIME, sc.EPC, sc.LOT AS SHIPPING_CONTAINER_LOT, sc.URI, sc.RETURNS_TOTAL_FREIGHT_CHARGE, sc.RETURNS_BASE_FREIGHT_CHARGE, 
             sc.RETURNS_FREIGHT_DISCOUNT, sc.RETURNS_ACCESSORIAL_CHARGE, sc.RETURNS_CALLTAG_FEE, sc.RETURNS_TRACKING_NUMBER, sc.RETURNS_MSN, sc.RETURNS_PRINT_LABEL, sc.WORLD_EASE_ID, sc.WORLD_EASE_GROUP_STATUS, sc.LOGISTICS_UNIT AS SHIPPING_CONTAINER_LOGISTICS_UNIT, 
             sc.PARENT_LOGISTICS_UNIT AS SHIPPING_CONTAINER_PARENT_LOGISTICS_UNIT, sc.PALLET_SEQUENCE, sc.ORIGINAL_PICK_LOC, sc.INTERNAL_MOP_NUMBER, sc.QC_STATUS AS QCSTATUS, sc.QC_ASSIGNMENT_ID, sc.PALLET_UM_CONVERSION_IDENTIFIER, sc.PALLET_UM_CONVERSION_PARENT_UM, sc.MMS_PIECE_ID, 
             CASE WHEN sc.item IS NULL THEN NULL ELSE
                 (SELECT   it.DESCRIPTION
                 FROM     item it
                 WHERE   sc.ITEM = it.ITEM AND ISNULL(sc.COMPANY, N''!'') = ISNULL(it.COMPANY, N''!'') OR
                              (sc.ITEM = it.ITEM AND it.COMPANY IS NULL)) END AS ITEM_DESC,
                 (SELECT   CASE MIN(scvas.COMPLETED) WHEN N''Y'' THEN N''Complete'' WHEN N''N'' THEN N''Pending'' ELSE N'' '' END AS Expr1
                 FROM     dbo.SHIPPING_CONT_VAS_ACTIVITY AS scvas LEFT OUTER JOIN
                              dbo.SHIPPING_CONTAINER AS scont ON scvas.INTERNAL_CONTAINER_NUM = sc.INTERNAL_CONTAINER_NUM AND sc.CONTAINER_TYPE <> N''-''
                 WHERE   (scont.INTERNAL_CONTAINER_NUM = sc.INTERNAL_CONTAINER_NUM)) AS VAS, CASE WHEN sh.LAUNCH_NUM > 0 THEN ls.RELEASED ELSE N''Y'' END AS RELEASED
FROM     dbo.SHIPPING_CONTAINER AS sc WITH (nolock) LEFT OUTER JOIN
             dbo.SHIPPING_CONTAINER AS parentContainer WITH (nolock) ON sc.PARENT = parentContainer.INTERNAL_CONTAINER_NUM INNER JOIN
             dbo.SHIPMENT_HEADER AS sh WITH (nolock) LEFT OUTER JOIN
             dbo.SHIPPING_LOAD AS SHIPLOAD WITH (nolock) ON sh.SHIPPING_LOAD_NUM = SHIPLOAD.INTERNAL_LOAD_NUM LEFT OUTER JOIN
             dbo.LAUNCH_STATISTICS AS ls ON ls.INTERNAL_LAUNCH_NUM = sh.LAUNCH_NUM ON sc.INTERNAL_SHIPMENT_NUM = sh.INTERNAL_SHIPMENT_NUM'

    EXEC sp_executesql @SQL;

	
    
	

END
