
CREATE PROCEDURE [dbo].[TRAV_RESEED_DB]
(
@MsgID nvarchar(max),
@username NVARCHAR(200),   
@error NVARCHAR(2000) OUTPUT,  
@success NVARCHAR(2000) OUTPUT
)
AS
SET NOCOUNT ON

DBCC CHECKIDENT ('SHIPPING_LOAD', RESEED, 86000);
