/*
	Task	| By	| Date		| Modification Description
	--------------------------------------------------------------------
	14876	| LJM	| 08/30/04	| created
	135689	| JY	| 02/17/14	| Modified the table of upload and added new filter.
	138673	| JY	| 03/14/14	| Selected distinct results.
    134894  | SHS   | 05/22/14  | Removed Serial_Number_View
	143196	| DN	| 06/04/14	| Fixed query	
*/

CREATE PROCEDURE wm_RSerialNumber10
	@ShipContNum numeric(9),
	@InterfaceLinkID numeric(9)
AS
SET NOCOUNT ON;

	if(@InterfaceLinkID =0)
		SELECT *
		FROM SERIAL_NUMBER SN
		WHERE SN.SHIP_CONT_NUM = @ShipContNum
		AND SN.TEMPLATE_ID IS NULL

		UNION ALL
		
		SELECT *
		FROM AR_SERIAL_NUMBER SN
		WHERE SN.SHIP_CONT_NUM = @ShipContNum
		AND SN.TEMPLATE_ID IS NULL
	
		UNION ALL
	
		SELECT SN.*
		FROM SERIAL_NUMBER SN, SERIAL_NUM_TEMPLATE SNT
		WHERE SN.SHIP_CONT_NUM = @ShipContNum
		AND SN.TEMPLATE_ID = SNT.OBJECT_ID
		AND SNT.SEQUENCE = 0
	
		UNION ALL
	
		SELECT SN.*
		FROM AR_SERIAL_NUMBER SN, SERIAL_NUM_TEMPLATE SNT
		WHERE SN.SHIP_CONT_NUM = @ShipContNum
		AND SN.TEMPLATE_ID = SNT.OBJECT_ID
		AND SNT.SEQUENCE = 0
	else
		SELECT *
		FROM SERIAL_NUMBER 
		WHERE OBJECT_ID IN (SELECT INTERFACE_RECORD_ID 
		FROM UPLOAD_SERIAL_NUMBER 
		WHERE SHIP_CONT_NUM = @ShipContNum		
		AND INTERFACE_LINK_ID = @InterfaceLinkID)
		AND TEMPLATE_ID IS NULL

		UNION ALL

		SELECT *
		FROM AR_SERIAL_NUMBER ASN
		WHERE OBJECT_ID IN (SELECT INTERFACE_RECORD_ID 
		FROM UPLOAD_SERIAL_NUMBER 
		WHERE SHIP_CONT_NUM = @ShipContNum
		AND INTERFACE_LINK_ID = @InterfaceLinkID)
		AND TEMPLATE_ID IS NULL
	   
		UNION ALL
	
		SELECT SN.*
		FROM SERIAL_NUMBER SN, SERIAL_NUM_TEMPLATE SNT
		WHERE 
		SN.SHIP_CONT_NUM = @ShipContNum
		AND SN.TEMPLATE_ID = SNT.OBJECT_ID
		AND SNT.SEQUENCE = 0
		AND SN.OBJECT_ID IN (SELECT INTERFACE_RECORD_ID 
		FROM UPLOAD_SERIAL_NUMBER 
		WHERE SHIP_CONT_NUM = @ShipContNum
		AND INTERFACE_LINK_ID = @InterfaceLinkID)

		UNION ALL
		
		SELECT SN.*
		FROM AR_SERIAL_NUMBER SN, SERIAL_NUM_TEMPLATE SNT  
		WHERE 
		SN.SHIP_CONT_NUM = @ShipContNum
		AND SN.TEMPLATE_ID = SNT.OBJECT_ID
		AND SNT.SEQUENCE = 0
		AND SN.OBJECT_ID IN (SELECT INTERFACE_RECORD_ID 
		FROM UPLOAD_SERIAL_NUMBER 
		WHERE SHIP_CONT_NUM = @ShipContNum
		AND INTERFACE_LINK_ID = @InterfaceLinkID)
