/*
	Task	| By	| Date		| Modification Description
	--------------------------------------------------------------------
	14842	| RAB	| 09/09/04	| created
    134894  | SHS   | 05/22/14  | Removed Serial_Number_View
*/



CREATE PROCEDURE wm_RSerialNumber11
	@TransHistId numeric(9)
AS
	SET NOCOUNT ON;
	
	SELECT SN.*
	  FROM SERIAL_NUMBER SN,
	       TRANS_HIST_ATTRIBUTES THA
	 WHERE THA.ATTRIBUTE_TYPE = N'SERIALNUMBER'
	   AND THA.LINK_ID = @TransHistId
	   AND SN.OBJECT_ID = THA.ATTRIBUTE_VALUE
	   AND SN.TEMPLATE_ID IS NULL
	UNION ALL
	SELECT ASN.*
	  FROM AR_SERIAL_NUMBER ASN,
	       TRANS_HIST_ATTRIBUTES THA
	 WHERE THA.ATTRIBUTE_TYPE = N'SERIALNUMBER'
	   AND THA.LINK_ID = @TransHistId
	   AND ASN.OBJECT_ID = THA.ATTRIBUTE_VALUE
	   AND ASN.TEMPLATE_ID IS NULL
	
	UNION ALL
	
	SELECT SN.*
	  FROM SERIAL_NUMBER SN,
	       SERIAL_NUM_TEMPLATE SNT,
	       TRANS_HIST_ATTRIBUTES THA
	 WHERE THA.ATTRIBUTE_TYPE = N'SERIALNUMBER'
	   AND THA.LINK_ID = @TransHistId
	   AND SN.OBJECT_ID = THA.ATTRIBUTE_VALUE
	   AND SNT.OBJECT_ID = SN.TEMPLATE_ID
	   AND SNT.SEQUENCE = 0
	UNION ALL
	SELECT ASN.*
	  FROM AR_SERIAL_NUMBER ASN,
	       SERIAL_NUM_TEMPLATE SNT,
	       TRANS_HIST_ATTRIBUTES THA
	 WHERE THA.ATTRIBUTE_TYPE = N'SERIALNUMBER'
	   AND THA.LINK_ID = @TransHistId
	   AND ASN.OBJECT_ID = THA.ATTRIBUTE_VALUE
	   AND SNT.OBJECT_ID = ASN.TEMPLATE_ID
	   AND SNT.SEQUENCE = 0