/*
	Task	| By	| Date		| Modification Description
	--------------------------------------------------------------------
	17029	| NNP	| 06/13/05	| Modified the SQL Version to prevent deadlock situation ,
								  Modified the Oracle Version to split OR conditions,
								  Merged SQL And ORACLE version
	16763	| SMF	| 07/06/05	| Only select records if they are not stamped as "Processed"
   	59031   | DRK   | 09/25/09  | Added VAS Download functionality  
	51519	| MDL   | 01/20/10  | Added error condition in where clause 
	87728	| MAG   | 08/02/11  | Added Criteria to Comments and VAS to ensure only unprocessed records are added to orders 
	191074	| DN	| 01/23/17	| Updated parameter types
*/

CREATE PROCEDURE wm_RUDownloadOrderHeader01
	@ProcessStamp nvarchar(100)
AS
	UPDATE DOWNLOAD_ORDER_HEADER
	SET INTERFACE_CONDITION = N'In Process', PROCESS_STAMP = @ProcessStamp
	WHERE (INTERFACE_CONDITION = N'Ready' OR INTERFACE_CONDITION IS NULL);

	UPDATE DOWNLOAD_ORDER_DETAIL
	SET INTERFACE_CONDITION = N'In Process', PROCESS_STAMP = @ProcessStamp
	WHERE 
		INTERFACE_LINK_ID IN (
			SELECT INTERFACE_RECORD_ID
			FROM DOWNLOAD_ORDER_HEADER WITH (NOLOCK)
			WHERE PROCESS_STAMP = @ProcessStamp
			AND INTERFACE_CONDITION <> N'Processed'
			AND INTERFACE_CONDITION <> N'Error' );
			
	UPDATE DOWNLOAD_ORDER_DETAIL
	SET INTERFACE_CONDITION = N'In Process', PROCESS_STAMP = @ProcessStamp
	WHERE 
		(INTERFACE_CONDITION = N'Ready' OR INTERFACE_CONDITION IS NULL)
		AND (INTERFACE_LINK_ID IS NULL OR INTERFACE_LINK_ID NOT IN (
			SELECT INTERFACE_RECORD_ID
			FROM DOWNLOAD_ORDER_HEADER WITH (NOLOCK)));

	UPDATE DOWNLOAD_ORDER_CONTAINER
	SET INTERFACE_CONDITION = N'In Process',PROCESS_STAMP = @ProcessStamp
	WHERE 
		INTERFACE_LINK_ID IN (
		SELECT INTERFACE_RECORD_ID
		FROM DOWNLOAD_ORDER_HEADER WITH (NOLOCK)
			WHERE PROCESS_STAMP = @ProcessStamp
			AND INTERFACE_CONDITION <> N'Processed'
			AND INTERFACE_CONDITION <> N'Error');   
   
	UPDATE DOWNLOAD_ORDER_CONTAINER
	SET INTERFACE_CONDITION = N'In Process', PROCESS_STAMP = @ProcessStamp
	WHERE   
		(INTERFACE_CONDITION = N'Ready' OR INTERFACE_CONDITION IS NULL)
		AND 
		(INTERFACE_LINK_ID IS NULL OR INTERFACE_LINK_ID NOT IN (
			SELECT INTERFACE_RECORD_ID
			FROM DOWNLOAD_ORDER_HEADER WITH (NOLOCK)));

	UPDATE DOWNLOAD_ORDER_COMMENT
	SET INTERFACE_CONDITION = N'In Process', PROCESS_STAMP = @ProcessStamp
	WHERE  (INTERFACE_CONDITION = N'Ready' OR INTERFACE_CONDITION IS NULL) AND
		INTERFACE_LINK_ID IN (
			SELECT INTERFACE_RECORD_ID
			FROM DOWNLOAD_ORDER_HEADER WITH (NOLOCK)
			WHERE PROCESS_STAMP = @ProcessStamp
			AND INTERFACE_CONDITION <> N'Processed'
			AND INTERFACE_CONDITION <> N'Error');

	UPDATE DOWNLOAD_ORDER_COMMENT
	SET INTERFACE_CONDITION = N'In Process', PROCESS_STAMP = @ProcessStamp
	WHERE  (INTERFACE_CONDITION = N'Ready' OR INTERFACE_CONDITION IS NULL) AND
		INTERFACE_LINK_ID IN (
			SELECT INTERFACE_RECORD_ID
			FROM DOWNLOAD_ORDER_DETAIL WITH (NOLOCK)
			WHERE PROCESS_STAMP = @ProcessStamp
			AND INTERFACE_CONDITION <> N'Processed'
			AND INTERFACE_CONDITION <> N'Error');

	UPDATE DOWNLOAD_ORDER_COMMENT
	SET INTERFACE_CONDITION = N'In Process', PROCESS_STAMP = @ProcessStamp
	WHERE  (INTERFACE_CONDITION = N'Ready' OR INTERFACE_CONDITION IS NULL)
		AND (
			INTERFACE_LINK_ID IS NULL
			OR INTERFACE_LINK_ID NOT IN (
				SELECT INTERFACE_RECORD_ID
				FROM DOWNLOAD_ORDER_HEADER WITH (NOLOCK))
			OR INTERFACE_LINK_ID NOT IN (
				SELECT INTERFACE_RECORD_ID
				FROM DOWNLOAD_ORDER_DETAIL WITH (NOLOCK)));


	UPDATE DOWNLOAD_ORDER_VAS_ACTIVITY
	SET INTERFACE_CONDITION = N'In Process', PROCESS_STAMP = @ProcessStamp
	WHERE  (INTERFACE_CONDITION = N'Ready' OR INTERFACE_CONDITION IS NULL) AND
		INTERFACE_LINK_ID IN (
			SELECT INTERFACE_RECORD_ID
			FROM DOWNLOAD_ORDER_HEADER WITH (NOLOCK)
			WHERE PROCESS_STAMP = @ProcessStamp
			AND INTERFACE_CONDITION <> N'Processed'
			AND INTERFACE_CONDITION <> N'Error');

	UPDATE DOWNLOAD_ORDER_VAS_ACTIVITY
	SET INTERFACE_CONDITION = N'In Process', PROCESS_STAMP = @ProcessStamp
	WHERE  (INTERFACE_CONDITION = N'Ready' OR INTERFACE_CONDITION IS NULL) AND
		INTERFACE_LINK_ID IN (
			SELECT INTERFACE_RECORD_ID
			FROM DOWNLOAD_ORDER_DETAIL WITH (NOLOCK)
			WHERE PROCESS_STAMP = @ProcessStamp
			AND INTERFACE_CONDITION <> N'Processed'
			AND INTERFACE_CONDITION <> N'Error');

	UPDATE DOWNLOAD_ORDER_VAS_ACTIVITY
	SET INTERFACE_CONDITION = N'In Process', PROCESS_STAMP = @ProcessStamp
	WHERE  (INTERFACE_CONDITION = N'Ready' OR INTERFACE_CONDITION IS NULL)
		AND (
			INTERFACE_LINK_ID IS NULL
			OR INTERFACE_LINK_ID NOT IN (
				SELECT INTERFACE_RECORD_ID
				FROM DOWNLOAD_ORDER_HEADER WITH (NOLOCK))
			OR INTERFACE_LINK_ID NOT IN (
				SELECT INTERFACE_RECORD_ID
				FROM DOWNLOAD_ORDER_DETAIL WITH (NOLOCK)));

	SELECT N'DM SHH DW', *
	FROM DOWNLOAD_ORDER_HEADER
	WHERE PROCESS_STAMP = @ProcessStamp
	AND INTERFACE_CONDITION <> N'Processed'
	AND INTERFACE_CONDITION <> N'Error';

	SELECT N'DM SHD DW', *
	FROM DOWNLOAD_ORDER_DETAIL
	WHERE PROCESS_STAMP = @ProcessStamp
	AND INTERFACE_CONDITION <> N'Processed'
	AND INTERFACE_CONDITION <> N'Error';

	SELECT N'DM SHC DW', *
	FROM DOWNLOAD_ORDER_CONTAINER
	WHERE PROCESS_STAMP = @ProcessStamp
	AND INTERFACE_CONDITION <> N'Processed'
	AND INTERFACE_CONDITION <> N'Error';

	SELECT N'DM SHM DW', *
	FROM DOWNLOAD_ORDER_COMMENT
	WHERE PROCESS_STAMP = @ProcessStamp
	AND INTERFACE_CONDITION <> N'Processed'
	AND INTERFACE_CONDITION <> N'Error';

	SELECT N'DM SHV DW', *
	FROM DOWNLOAD_ORDER_VAS_ACTIVITY
	WHERE PROCESS_STAMP = @ProcessStamp
	AND INTERFACE_CONDITION <> N'Processed'
	AND INTERFACE_CONDITION <> N'Error'
    AND (ERP_ORDER_LINE_NUM <= 0 OR ERP_ORDER_LINE_NUM IS NULL);

    SELECT N'DM SDV DW', *
	FROM DOWNLOAD_ORDER_VAS_ACTIVITY
	WHERE PROCESS_STAMP = @ProcessStamp
	AND INTERFACE_CONDITION <> N'Processed'
	AND INTERFACE_CONDITION <> N'Error'
    AND ERP_ORDER_LINE_NUM > 0;


