/*
	Task	| By	| Date		| Modification Description
	--------------------------------------------------------------------
	17111	| VK	| 11/21/05	| Created
	19199	| MAG	| 04/24/06	| Order the Selection of records by Interface_Record_Id
    59031   | DRK   | 09/25/09  | Added VAS Download functionality   
	51519	| MDL   | 01/20/10  | Added error condition in where clause
	87728	| MAG   | 08/02/11  | Added Criteria to Comments and VAS to ensure only unprocessed records are added to orders 
*/

CREATE PROCEDURE wm_RUDownloadOrderHeader02
	@ProcessStamp nvarchar(100),
	@MaxRecords numeric(9)
AS
	declare @ready nvarchar(25);
	declare @inProcess nvarchar(25);
	declare @sql nvarchar(1000);
	
	set @ready = N'Ready';
	set @inProcess = N'In Process';
	
	set @sql = N'UPDATE DOWNLOAD_ORDER_HEADER
		    SET INTERFACE_CONDITION = @inProcessParam, PROCESS_STAMP = @processStampParam
	            WHERE INTERFACE_RECORD_ID IN(
				SELECT TOP '+convert(varchar, @maxRecords)+N' INTERFACE_RECORD_ID
				FROM DOWNLOAD_ORDER_HEADER
				WHERE (INTERFACE_CONDITION = @readyParam OR INTERFACE_CONDITION IS NULL)
				ORDER BY INTERFACE_RECORD_ID)';

	exec sp_executesql @sql,N'@readyParam nvarchar(25),
		@inProcessParam nvarchar(25),
		@processStampParam nvarchar(100)',
		@readyParam = @ready,
		@inProcessParam = @inProcess,
		@processStampParam = @ProcessStamp; 

	set @maxRecords = @maxRecords - @@ROWCOUNT;	

	IF (@maxRecords > 0)
	BEGIN		
		set @sql = N'UPDATE DOWNLOAD_ORDER_DETAIL
		        SET INTERFACE_CONDITION = @inProcessParam, PROCESS_STAMP = @processStampParam
		        WHERE INTERFACE_RECORD_ID IN(
				SELECT TOP '+convert(varchar, @maxRecords)+N' INTERFACE_RECORD_ID
				FROM DOWNLOAD_ORDER_DETAIL
				WHERE (INTERFACE_CONDITION = @readyParam OR INTERFACE_CONDITION IS NULL)
			         AND (INTERFACE_LINK_ID IS NULL OR INTERFACE_LINK_ID NOT IN (
									SELECT INTERFACE_RECORD_ID
									FROM DOWNLOAD_ORDER_HEADER WITH (NOLOCK)))
				ORDER BY INTERFACE_RECORD_ID)';

		exec sp_executesql @sql,N'@readyParam nvarchar(25),
			@inProcessParam nvarchar(25),
			@processStampParam nvarchar(100)',
			@readyParam = @ready,
			@inProcessParam = @inProcess,
			@processStampParam = @ProcessStamp; 

		set @maxRecords = @maxRecords - @@ROWCOUNT;
	END;

	IF (@maxRecords > 0)
	BEGIN
		set @sql = N'UPDATE DOWNLOAD_ORDER_CONTAINER
			SET INTERFACE_CONDITION = @inProcessParam, PROCESS_STAMP = @processStampParam
			WHERE INTERFACE_RECORD_ID IN(
				SELECT TOP '+convert(varchar, @maxRecords)+N' INTERFACE_RECORD_ID
				FROM DOWNLOAD_ORDER_CONTAINER
				WHERE (INTERFACE_CONDITION = @readyParam OR INTERFACE_CONDITION IS NULL)
				 AND (INTERFACE_LINK_ID IS NULL 
	  			   OR INTERFACE_LINK_ID NOT IN (
					SELECT INTERFACE_RECORD_ID
					FROM DOWNLOAD_ORDER_HEADER WITH (NOLOCK))
				   OR INTERFACE_LINK_ID NOT IN (
					SELECT INTERFACE_RECORD_ID
					FROM DOWNLOAD_ORDER_CONTAINER WITH (NOLOCK))
				   OR INTERFACE_PARENT_LINK_ID NOT IN (
					SELECT INTERFACE_RECORD_ID
					FROM DOWNLOAD_ORDER_CONTAINER WITH (NOLOCK)))
				ORDER BY INTERFACE_RECORD_ID)';

		exec sp_executesql @sql,N'@readyParam nvarchar(25),
			@inProcessParam nvarchar(25),
			@processStampParam nvarchar(100)',
			@readyParam = @ready,
			@inProcessParam = @inProcess,
			@processStampParam = @ProcessStamp; 

		set @maxRecords = @maxRecords - @@ROWCOUNT;
	END;

	IF (@maxRecords > 0)
	BEGIN
		set @sql = N'UPDATE DOWNLOAD_ORDER_COMMENT
			SET INTERFACE_CONDITION = @inProcessParam, PROCESS_STAMP = @processStampParam
			WHERE INTERFACE_RECORD_ID IN(
				SELECT TOP '+convert(varchar, @maxRecords)+N' INTERFACE_RECORD_ID
				FROM DOWNLOAD_ORDER_COMMENT
				WHERE (INTERFACE_CONDITION = @readyParam  OR INTERFACE_CONDITION IS NULL)
				 AND (INTERFACE_LINK_ID IS NULL
			              OR INTERFACE_LINK_ID NOT IN (
						SELECT INTERFACE_RECORD_ID
						FROM DOWNLOAD_ORDER_HEADER WITH (NOLOCK))
			              OR INTERFACE_LINK_ID NOT IN (
						SELECT INTERFACE_RECORD_ID
						FROM DOWNLOAD_ORDER_DETAIL WITH (NOLOCK)))
				ORDER BY INTERFACE_RECORD_ID)';

		exec sp_executesql @sql,N'@readyParam nvarchar(25),
			@inProcessParam nvarchar(25),
			@processStampParam nvarchar(100)',
			@readyParam = @ready,
			@inProcessParam = @inProcess,
			@processStampParam = @ProcessStamp; 

        set @maxRecords = @maxRecords - @@ROWCOUNT;
	END;

	IF (@maxRecords > 0)
	BEGIN
		set @sql = N'UPDATE DOWNLOAD_ORDER_VAS_ACTIVITY
			SET INTERFACE_CONDITION = @inProcessParam, PROCESS_STAMP = @processStampParam
			WHERE INTERFACE_RECORD_ID IN(
				SELECT TOP '+convert(varchar, @maxRecords)+N' INTERFACE_RECORD_ID
				FROM DOWNLOAD_ORDER_VAS_ACTIVITY
				WHERE (INTERFACE_CONDITION = @readyParam  OR INTERFACE_CONDITION IS NULL)
				 AND (INTERFACE_LINK_ID IS NULL
			              OR INTERFACE_LINK_ID NOT IN (
						SELECT INTERFACE_RECORD_ID
						FROM DOWNLOAD_ORDER_HEADER WITH (NOLOCK))
			              OR INTERFACE_LINK_ID NOT IN (
						SELECT INTERFACE_RECORD_ID
						FROM DOWNLOAD_ORDER_DETAIL WITH (NOLOCK)))
				ORDER BY INTERFACE_RECORD_ID)';

		exec sp_executesql @sql,N'@readyParam nvarchar(25),
			@inProcessParam nvarchar(25),
			@processStampParam nvarchar(100)',
			@readyParam = @ready,
			@inProcessParam = @inProcess,
			@processStampParam = @ProcessStamp; 

	END;

	UPDATE DOWNLOAD_ORDER_DETAIL
	SET INTERFACE_CONDITION = N'In Process', PROCESS_STAMP = @ProcessStamp
	WHERE 
		INTERFACE_LINK_ID IN (
			SELECT INTERFACE_RECORD_ID
			FROM DOWNLOAD_ORDER_HEADER WITH (NOLOCK)
			WHERE PROCESS_STAMP = @ProcessStamp
			AND INTERFACE_CONDITION <> N'Processed'
			AND INTERFACE_CONDITION <> N'Error');
			
	
	UPDATE DOWNLOAD_ORDER_CONTAINER
	SET INTERFACE_CONDITION = N'In Process',PROCESS_STAMP = @ProcessStamp
	WHERE 
		INTERFACE_LINK_ID IN (
		SELECT INTERFACE_RECORD_ID
		FROM DOWNLOAD_ORDER_HEADER WITH (NOLOCK)
			WHERE PROCESS_STAMP = @ProcessStamp
			AND INTERFACE_CONDITION <> N'Processed'
			AND INTERFACE_CONDITION <> N'Error');

	-- Level1 nested containers   
   	UPDATE DOWNLOAD_ORDER_CONTAINER
	SET INTERFACE_CONDITION = N'In Process',PROCESS_STAMP = @ProcessStamp
	WHERE 
		INTERFACE_LINK_ID IN (
		SELECT INTERFACE_RECORD_ID
		FROM DOWNLOAD_ORDER_CONTAINER WITH (NOLOCK)
			WHERE PROCESS_STAMP = @ProcessStamp
			AND INTERFACE_CONDITION <> N'Processed'
			AND INTERFACE_CONDITION <> N'Error');

	-- Level2 nested containers   
   	UPDATE DOWNLOAD_ORDER_CONTAINER
	SET INTERFACE_CONDITION = N'In Process',PROCESS_STAMP = @ProcessStamp
	WHERE 
		INTERFACE_LINK_ID IN (
		SELECT INTERFACE_RECORD_ID
		FROM DOWNLOAD_ORDER_CONTAINER WITH (NOLOCK)
			WHERE PROCESS_STAMP = @ProcessStamp
			AND INTERFACE_CONDITION <> N'Processed'
			AND INTERFACE_CONDITION <> N'Error');

	-- Level3 nested containers   
   	UPDATE DOWNLOAD_ORDER_CONTAINER
	SET INTERFACE_CONDITION = N'In Process',PROCESS_STAMP = @ProcessStamp
	WHERE 
		INTERFACE_LINK_ID IN (
		SELECT INTERFACE_RECORD_ID
		FROM DOWNLOAD_ORDER_CONTAINER WITH (NOLOCK)
			WHERE PROCESS_STAMP = @ProcessStamp
			AND INTERFACE_CONDITION <> N'Processed'
			AND INTERFACE_CONDITION <> N'Error');

	--select all the details of containers that are stamped in previous updates
	UPDATE DOWNLOAD_ORDER_CONTAINER
	SET INTERFACE_CONDITION = N'In Process',PROCESS_STAMP = @ProcessStamp
	WHERE 
		INTERFACE_PARENT_LINK_ID IN (
		SELECT INTERFACE_RECORD_ID
		FROM DOWNLOAD_ORDER_CONTAINER WITH (NOLOCK)
			WHERE PROCESS_STAMP = @ProcessStamp
			AND INTERFACE_CONDITION <> N'Processed'
			AND INTERFACE_CONDITION <> N'Error');

	UPDATE DOWNLOAD_ORDER_COMMENT
	SET INTERFACE_CONDITION = N'In Process', PROCESS_STAMP = @ProcessStamp
	WHERE  (INTERFACE_CONDITION = N'Ready' OR INTERFACE_CONDITION IS NULL) AND
		INTERFACE_LINK_ID IN (
			SELECT INTERFACE_RECORD_ID
			FROM DOWNLOAD_ORDER_HEADER WITH (NOLOCK)
			WHERE PROCESS_STAMP = @ProcessStamp
			AND INTERFACE_CONDITION <> N'Processed'
			AND INTERFACE_CONDITION <> N'Error');

	UPDATE DOWNLOAD_ORDER_COMMENT
	SET INTERFACE_CONDITION = N'In Process', PROCESS_STAMP = @ProcessStamp
	WHERE  (INTERFACE_CONDITION = N'Ready' OR INTERFACE_CONDITION IS NULL) AND
		INTERFACE_LINK_ID IN (
			SELECT INTERFACE_RECORD_ID
			FROM DOWNLOAD_ORDER_DETAIL WITH (NOLOCK)
			WHERE PROCESS_STAMP = @ProcessStamp
			AND INTERFACE_CONDITION <> N'Processed'
			AND INTERFACE_CONDITION <> N'Error');

	UPDATE DOWNLOAD_ORDER_VAS_ACTIVITY
	SET INTERFACE_CONDITION = N'In Process', PROCESS_STAMP = @ProcessStamp
	WHERE  (INTERFACE_CONDITION = N'Ready' OR INTERFACE_CONDITION IS NULL) AND
		INTERFACE_LINK_ID IN (
			SELECT INTERFACE_RECORD_ID
			FROM DOWNLOAD_ORDER_HEADER WITH (NOLOCK)
			WHERE PROCESS_STAMP = @ProcessStamp
			AND INTERFACE_CONDITION <> N'Processed'
			AND INTERFACE_CONDITION <> N'Error');

	UPDATE DOWNLOAD_ORDER_VAS_ACTIVITY
	SET INTERFACE_CONDITION = N'In Process', PROCESS_STAMP = @ProcessStamp
	WHERE  (INTERFACE_CONDITION = N'Ready' OR INTERFACE_CONDITION IS NULL) AND
		INTERFACE_LINK_ID IN (
			SELECT INTERFACE_RECORD_ID
			FROM DOWNLOAD_ORDER_DETAIL WITH (NOLOCK)
			WHERE PROCESS_STAMP = @ProcessStamp
			AND INTERFACE_CONDITION <> N'Processed'
			AND INTERFACE_CONDITION <> N'Error');

	SELECT N'DM SHH DW', *
	FROM DOWNLOAD_ORDER_HEADER
	WHERE PROCESS_STAMP = @ProcessStamp
	AND INTERFACE_CONDITION <> N'Processed'
	AND INTERFACE_CONDITION <> N'Error'
	ORDER BY INTERFACE_RECORD_ID;

	SELECT N'DM SHD DW', *
	FROM DOWNLOAD_ORDER_DETAIL
	WHERE PROCESS_STAMP = @ProcessStamp
	AND INTERFACE_CONDITION <> N'Processed'
	AND INTERFACE_CONDITION <> N'Error'
	ORDER BY INTERFACE_RECORD_ID;

	SELECT N'DM SHC DW', *
	FROM DOWNLOAD_ORDER_CONTAINER
	WHERE PROCESS_STAMP = @ProcessStamp
	AND INTERFACE_CONDITION <> N'Processed'
	AND INTERFACE_CONDITION <> N'Error'
	ORDER BY INTERFACE_RECORD_ID;

	SELECT N'DM SHM DW', *
	FROM DOWNLOAD_ORDER_COMMENT
	WHERE PROCESS_STAMP = @ProcessStamp
	AND INTERFACE_CONDITION <> N'Processed'
	AND INTERFACE_CONDITION <> N'Error'
	ORDER BY INTERFACE_RECORD_ID;

	SELECT N'DM SHV DW', *
	FROM DOWNLOAD_ORDER_VAS_ACTIVITY
	WHERE PROCESS_STAMP = @ProcessStamp
	AND INTERFACE_CONDITION <> N'Processed'
	AND INTERFACE_CONDITION <> N'Error'
    AND (ERP_ORDER_LINE_NUM <= 0 OR ERP_ORDER_LINE_NUM IS NULL)
	ORDER BY INTERFACE_RECORD_ID;

    SELECT N'DM SDV DW', *
	FROM DOWNLOAD_ORDER_VAS_ACTIVITY
	WHERE PROCESS_STAMP = @ProcessStamp
	AND INTERFACE_CONDITION <> N'Processed'
	AND INTERFACE_CONDITION <> N'Error'
    AND ERP_ORDER_LINE_NUM > 0
	ORDER BY INTERFACE_RECORD_ID;

SELECT CASE WHEN (SUM(ALIAS.TOTAL)>0) 
	THEN N'1' ELSE N'0' END AreRecordsRemaining
	FROM (
		SELECT COUNT(*) TOTAL FROM DOWNLOAD_ORDER_HEADER
		WHERE INTERFACE_CONDITION = N'Ready' OR INTERFACE_CONDITION IS NULL
		UNION
		SELECT COUNT(*) TOTAL FROM DOWNLOAD_ORDER_DETAIL
		WHERE INTERFACE_CONDITION = N'Ready' OR INTERFACE_CONDITION IS NULL
		UNION
		SELECT COUNT(*) TOTAL FROM DOWNLOAD_ORDER_CONTAINER
		WHERE INTERFACE_CONDITION = N'Ready' OR INTERFACE_CONDITION IS NULL
		UNION
		SELECT COUNT(*) TOTAL FROM DOWNLOAD_ORDER_COMMENT
		WHERE INTERFACE_CONDITION = N'Ready' OR INTERFACE_CONDITION IS NULL
		UNION
		SELECT COUNT(*) TOTAL FROM DOWNLOAD_ORDER_VAS_ACTIVITY
		WHERE INTERFACE_CONDITION = N'Ready' OR INTERFACE_CONDITION IS NULL
	      ) ALIAS;

