/*
	Task	| By	| Date		| Modification Description
	--------------------------------------------------------------------
	15053	| MD	| 10/01/04	| Added support for appointment schedule download.
	16193	| SMF	| 02/03/05	| Added check to not precess serial numbres if they
		|	|		| 	are "in process" or "error"
	16763	| SMF	| 07/06/05	| Only select records if they are not stamped as "Processed"
	18633	| VK	| 02/10/06	| Added support for purchase orders download
*/

CREATE PROCEDURE wm_RUDownloadReceiptHeader01
	@ProcessStamp nvarchar(100)
AS
	
	UPDATE DOWNLOAD_PURCHASE_ORDER_HEADER
	SET INTERFACE_CONDITION = N'In Process', PROCESS_STAMP = @ProcessStamp
	WHERE (INTERFACE_CONDITION = N'Ready' OR INTERFACE_CONDITION IS NULL);
	
	UPDATE DOWNLOAD_PURCHASE_ORDER_DETAIL
	SET INTERFACE_CONDITION = N'In Process', PROCESS_STAMP = @ProcessStamp
	WHERE INTERFACE_LINK_ID IN (
			SELECT INTERFACE_RECORD_ID
			FROM DOWNLOAD_PURCHASE_ORDER_HEADER
			WHERE PROCESS_STAMP = @ProcessStamp
			AND INTERFACE_CONDITION <> N'Processed');

	UPDATE DOWNLOAD_PURCHASE_ORDER_DETAIL
	SET INTERFACE_CONDITION = N'In Process', PROCESS_STAMP = @ProcessStamp
	WHERE (INTERFACE_CONDITION = N'Ready' OR INTERFACE_CONDITION IS NULL)
		AND (INTERFACE_LINK_ID IS NULL OR INTERFACE_LINK_ID NOT IN (
			SELECT INTERFACE_RECORD_ID
			FROM DOWNLOAD_PURCHASE_ORDER_HEADER));
	
	UPDATE DOWNLOAD_RECEIPT_HEADER
	SET INTERFACE_CONDITION = N'In Process', PROCESS_STAMP = @ProcessStamp
	WHERE (INTERFACE_CONDITION = N'Ready' OR INTERFACE_CONDITION IS NULL);

	UPDATE DOWNLOAD_RECEIPT_DETAIL
	SET INTERFACE_CONDITION = N'In Process', PROCESS_STAMP = @ProcessStamp
	WHERE (
		INTERFACE_LINK_ID IN (
			SELECT INTERFACE_RECORD_ID
			FROM DOWNLOAD_RECEIPT_HEADER
			WHERE PROCESS_STAMP = @ProcessStamp
			AND INTERFACE_CONDITION <> N'Processed'))
	OR (
		(INTERFACE_CONDITION = N'Ready' OR INTERFACE_CONDITION IS NULL)
		AND (INTERFACE_LINK_ID IS NULL OR INTERFACE_LINK_ID NOT IN (
			SELECT INTERFACE_RECORD_ID
			FROM DOWNLOAD_RECEIPT_HEADER)));

	UPDATE DOWNLOAD_RECEIPT_CONTAINER
	SET INTERFACE_CONDITION = N'In Process', PROCESS_STAMP = @ProcessStamp
	WHERE (
		INTERFACE_LINK_ID IN (
			SELECT INTERFACE_RECORD_ID
			FROM DOWNLOAD_RECEIPT_HEADER
			WHERE PROCESS_STAMP = @ProcessStamp
			AND INTERFACE_CONDITION <> N'Processed'))
	OR (
		(INTERFACE_CONDITION = N'Ready' OR INTERFACE_CONDITION IS NULL)
		AND (INTERFACE_LINK_ID IS NULL OR INTERFACE_LINK_ID NOT IN (
			SELECT INTERFACE_RECORD_ID
			FROM DOWNLOAD_RECEIPT_HEADER)));

	-- update appointments on receipt
	UPDATE DOWNLOAD_APPT_SCHEDULE
	SET INTERFACE_CONDITION = N'In Process', PROCESS_STAMP = @ProcessStamp
	WHERE (
		INTERFACE_LINK_ID IN (
			SELECT INTERFACE_RECORD_ID
			FROM DOWNLOAD_APPT_SCHEDULE
			WHERE PROCESS_STAMP = @ProcessStamp 
			AND INTERFACE_LINK_TYPE = N'Receiving'
			AND INTERFACE_CONDITION <> N'Processed'))
	OR (
		(INTERFACE_CONDITION = N'Ready' OR INTERFACE_CONDITION IS NULL)
		AND (INTERFACE_LINK_ID IS NULL OR INTERFACE_LINK_ID NOT IN (
			SELECT INTERFACE_RECORD_ID
			FROM DOWNLOAD_APPT_SCHEDULE WHERE INTERFACE_LINK_TYPE = N'Receiving')));

	-- stamp master serial numbers and lone serial numbers.
	UPDATE DOWNLOAD_SERIAL_NUMBER
	   SET INTERFACE_CONDITION = N'In Process', PROCESS_STAMP = @ProcessStamp
	 WHERE (INTERFACE_LINK_ID IN (
			SELECT INTERFACE_RECORD_ID
			  FROM DOWNLOAD_RECEIPT_CONTAINER
			 WHERE PROCESS_STAMP = @ProcessStamp)
	    AND (INTERFACE_CONDITION = N'Ready' 
	      	OR INTERFACE_CONDITION IS NULL))
	    OR ((INTERFACE_CONDITION = N'Ready' 
	         OR INTERFACE_CONDITION IS NULL)
		    AND (INTERFACE_LINK_ID IS NULL 
		         OR (INTERFACE_LINK_ID NOT IN (
						SELECT INTERFACE_RECORD_ID
						  FROM DOWNLOAD_RECEIPT_HEADER)
					 AND INTERFACE_LINK_ID NOT IN (
						SELECT INTERFACE_RECORD_ID
						  FROM DOWNLOAD_SERIAL_NUMBER))));

	-- stamp minor serial numbers.  note that we do this in a different
	-- update as the masters got stamped in the previous.
	UPDATE DOWNLOAD_SERIAL_NUMBER
	   SET INTERFACE_CONDITION = N'In Process', PROCESS_STAMP = @ProcessStamp
	 WHERE INTERFACE_LINK_ID IN (
			SELECT INTERFACE_RECORD_ID
			  FROM DOWNLOAD_SERIAL_NUMBER
			 WHERE PROCESS_STAMP = @ProcessStamp)
	 AND INTERFACE_CONDITION <> N'Processed';

	SELECT N'DM POH DW', *
	FROM DOWNLOAD_PURCHASE_ORDER_HEADER
	WHERE PROCESS_STAMP = @ProcessStamp
	AND INTERFACE_CONDITION <> N'Processed';

	SELECT N'DM POD DW', *
	FROM DOWNLOAD_PURCHASE_ORDER_DETAIL
	WHERE PROCESS_STAMP = @ProcessStamp
	AND INTERFACE_CONDITION <> N'Processed';

	SELECT N'DM RCH DW', *
	FROM DOWNLOAD_RECEIPT_HEADER
	WHERE PROCESS_STAMP = @ProcessStamp
	AND INTERFACE_CONDITION <> N'Processed';

	SELECT N'DM RCD DW', *
	FROM DOWNLOAD_RECEIPT_DETAIL
	WHERE PROCESS_STAMP = @ProcessStamp
	AND INTERFACE_CONDITION <> N'Processed';

	SELECT N'DM RCC DW', *
	FROM DOWNLOAD_RECEIPT_CONTAINER
	WHERE PROCESS_STAMP = @ProcessStamp
	AND INTERFACE_CONDITION <> N'Processed';
	
	SELECT N'DM SN DW', *
	FROM DOWNLOAD_SERIAL_NUMBER
	WHERE PROCESS_STAMP = @ProcessStamp
	AND INTERFACE_CONDITION <> N'Processed';

	SELECT N'DM AS DW', *
	FROM DOWNLOAD_APPT_SCHEDULE
	WHERE PROCESS_STAMP = @ProcessStamp
	AND INTERFACE_CONDITION <> N'Processed';
	



