/*
	Task	| By	| Date		    | Modification Description
	---------------------------------------------------------------
	148831	| MDL	| 10/16/2014	| Created.

	
	Parameters:
		BatchId	batch Id marked for upload.


	Returns:
		return container for upload for delimited mode

*/

CREATE PROCEDURE wm_RUReceiptContainer05(
	@BatchId nvarchar(50)
	)

AS
begin
	set nocount on;
with cte  (INTERFACE_RECORD_ID, 
       INTERFACE_LINK_ID, 
       container_class, 
       container_id, 
       container_type, 
       converted_loc_qty, 
       converted_qty_um, 
       dimension_um, 
       expiration_date_time, 
       from_location, 
       from_warehouse, 
       height, 
       item, 
       item_class, 
       item_desc, 
       length, 
       locating_rule, 
       lot, 
       manufactured_date_time, 
       parent, 
       quantity, 
       quantity_um, 
       receipt_date, 
       receipt_id, 
       receipt_id_type, 
       to_location, 
       to_warehouse, 
       weight, 
       weight_um, 
       width, 
       user_def1, 
       user_def2, 
       user_def3, 
       user_def4, 
       user_def5, 
       user_def6, 
       user_def7, 
       user_def8, 
       USER_STAMP, 
       PROCESS_STAMP, 
       INTERFACE_ACTION_CODE, 
       INTERFACE_CONDITION, 
       internal_receipt_num, 
       internal_receipt_line_num, 
       internal_rec_cont_num, 
       internal_loc_cont_num, 
       DATE_TIME_STAMP, 
       company, 
       status_flow_name, 
       launch_num, 
       incoming_pd_loc, 
       outgoing_pd_loc, 
       used_by_immed_need, 
       inventory_sts, 
       disposition_code, 
       reason_code, 
       epc, 
       uri,
	   tree)
as
(SELECT rc.internal_rec_cont_num                                          AS        INTERFACE_RECORD_ID, 
       rc.internal_receipt_num                                           AS        INTERFACE_LINK_ID, 
       rc.container_class, 
       rc.container_id, 
       rc.container_type, 
       rc.converted_loc_qty, 
       rc.converted_qty_um, 
       rc.dimension_um, 
       rc.expiration_date_time, 
       rc.from_location, 
       rc.from_warehouse, 
       rc.height, 
       rc.item, 
       rc.item_class, 
       rc.item_desc, 
       rc.length, 
       rc.locating_rule, 
       rc.lot, 
       rc.manufactured_date_time, 
       rc.parent, 
       rc.quantity, 
       rc.quantity_um, 
       rc.receipt_date, 
       rc.receipt_id, 
       rc.receipt_id_type, 
       rc.to_location, 
       rc.to_warehouse, 
       rc.weight, 
       rc.weight_um, 
       rc.width, 
       rc.user_def1, 
       rc.user_def2, 
       rc.user_def3, 
       rc.user_def4, 
       rc.user_def5, 
       rc.user_def6, 
       rc.user_def7, 
       rc.user_def8, 
       rc.user_stamp                                                     AS       USER_STAMP, 
       N'Receiving Interface Batch:'+@BatchId 							 AS       PROCESS_STAMP, 
       N'New'                                                            AS       INTERFACE_ACTION_CODE, 
       N'Processed'                                                      AS 	  INTERFACE_CONDITION, 
       rc.internal_receipt_num, 
       rc.internal_receipt_line_num, 
       rc.internal_rec_cont_num, 
       rc.internal_loc_cont_num, 
       CONVERT(DATETIME, CONVERT(NVARCHAR, GETUTCDATE(), 20))               AS 
       DATE_TIME_STAMP, 
       rc.company, 
       rc.status_flow_name, 
       rc.launch_num, 
       rc.incoming_pd_loc, 
       rc.outgoing_pd_loc, 
       rc.used_by_immed_need, 
       rc.inventory_sts, 
       rc.disposition_code, 
       rc.reason_code, 
       rc.epc, 
       rc.uri,
	   CAST(internal_rec_cont_num AS VARCHAR(128)) AS tree
FROM   receipt_container rc 
WHERE rc.PARENT is null or rc.parent =0 
 and (rc.INTERNAL_REC_CONT_NUM in ( select parent from   receipt_container rc 
WHERE  rc.upload_interface_batch = @BatchId )  or rc.upload_interface_batch = @BatchId )

UNION ALL 

SELECT rc.internal_rec_cont_num                                          AS        INTERFACE_RECORD_ID, 
       rc.Parent			                                             AS        INTERFACE_LINK_ID, 
       rc.container_class, 
       rc.container_id, 
       rc.container_type, 
       rc.converted_loc_qty, 
       rc.converted_qty_um, 
       rc.dimension_um, 
       rc.expiration_date_time, 
       rc.from_location, 
       rc.from_warehouse, 
       rc.height, 
       rc.item, 
       rc.item_class, 
       rc.item_desc, 
       rc.length, 
       rc.locating_rule, 
       rc.lot, 
       rc.manufactured_date_time, 
       rc.parent, 
       rc.quantity, 
       rc.quantity_um, 
       rc.receipt_date, 
       rc.receipt_id, 
       rc.receipt_id_type, 
       rc.to_location, 
       rc.to_warehouse, 
       rc.weight, 
       rc.weight_um, 
       rc.width, 
       rc.user_def1, 
       rc.user_def2, 
       rc.user_def3, 
       rc.user_def4, 
       rc.user_def5, 
       rc.user_def6, 
       rc.user_def7, 
       rc.user_def8, 
       rc.user_stamp                                                     AS       USER_STAMP, 
       N'Receiving Interface Batch:'+@BatchId 							 AS       PROCESS_STAMP, 
       N'New'                                                            AS       INTERFACE_ACTION_CODE, 
       N'Processed'                                                      AS 	  INTERFACE_CONDITION, 
       rc.internal_receipt_num, 
       rc.internal_receipt_line_num, 
       rc.internal_rec_cont_num, 
       rc.internal_loc_cont_num, 
       CONVERT(DATETIME, CONVERT(NVARCHAR, GETUTCDATE(), 20))               AS 
       DATE_TIME_STAMP, 
       rc.company, 
       rc.status_flow_name, 
       rc.launch_num, 
       rc.incoming_pd_loc, 
       rc.outgoing_pd_loc, 
       rc.used_by_immed_need, 
       rc.inventory_sts, 
       rc.disposition_code, 
       rc.reason_code, 
       rc.epc, 
       rc.uri,
	   CAST(cte.tree + N'/' + CAST(rc.internal_rec_cont_num AS VARCHAR) AS VARCHAR(128)) 
FROM cte 
  join RECEIPT_CONTAINER rc
  on cte.internal_rec_cont_num = rc.PARENT WHERE  rc.upload_interface_batch = @BatchId )


SELECT 
INTERFACE_RECORD_ID, 
       INTERFACE_LINK_ID, 
       container_class, 
       container_id, 
       container_type, 
       converted_loc_qty, 
       converted_qty_um, 
       dimension_um, 
       expiration_date_time, 
       from_location, 
       from_warehouse, 
       height, 
       item, 
       item_class, 
       item_desc, 
       length, 
       locating_rule, 
       lot, 
       manufactured_date_time, 
       parent, 
       quantity, 
       quantity_um, 
       receipt_date, 
       receipt_id, 
       receipt_id_type, 
       to_location, 
       to_warehouse, 
       weight, 
       weight_um, 
       width, 
       user_def1, 
       user_def2, 
       user_def3, 
       user_def4, 
       user_def5, 
       user_def6, 
       user_def7, 
       user_def8, 
       USER_STAMP, 
       PROCESS_STAMP, 
       INTERFACE_ACTION_CODE, 
       INTERFACE_CONDITION, 
       internal_receipt_num, 
       internal_receipt_line_num, 
       internal_rec_cont_num, 
       internal_loc_cont_num, 
       DATE_TIME_STAMP, 
       company, 
       status_flow_name, 
       launch_num, 
       incoming_pd_loc, 
       outgoing_pd_loc, 
       used_by_immed_need, 
       inventory_sts, 
       disposition_code, 
       reason_code, 
       epc, 
       uri
from cte order by tree

end 



