/*
 Mod          | Programmer           | Date       | Modification Description
 --------------------------------------------------------------------
 APRunbook    | jelliott / aapatel   | 11/24/2025 | Revised version from original
 APRunbook    | jelliott / aapatel   | 02/18/2026 | Corrected Transaction History ARCHIVE_PROCESS
 APRunbook	  | jelliott / aapatel   | 02/26/2026 | Corrected and optimized Truncate and Delete logic
 APRunbook	  | jelliott / aapatel   | 02/27/2026 | Bypass truncate and delete logic if loop limit = 0
 APRunbook	  | jelliott / aapatel   | 03/02/2026 | Updated USER_DEF logic, Data Save (Tier 2) logic, Custom Preference logic
 APRunbook	  | jelliott / aapatel   | 03/13/2026 | Updated logic for custom Process and Transaction History Types
 APRunbook	  | jelliott / aapatel   | 04/02/2026 | Updated logic to account for existing UDF data
 APRunbook	  | jelliott / aapatel   | 04/14/2026 | Only purge / truncate if Active and Run by Default = Y
 APRunbook	  | jelliott / aapatel   | 05/27/2026 | Adjusted TRANSACTION_HISTORY and WORK_INSTRUCTION for better optimization
 APRunbook	  | jelliott / aapatel   | 06/11/2026 | Updated SYS_KEY for new MAS_DATASAVE_TIER2 value
 APRunbook    | jelliott / team      | 09/02/2026 | Corrected logic for Data Save Tier 2 to use description instead of new SYS_KEY
 */

/*
NOTE:   GENERIC_CONFIG_DETAIL.RECORD_TYPE = N'HIST PROC' REFERS TO PROCESS_HISTORY TYPES
        GENERIC_CONFIG_DETAIL.RECORD_TYPE = N'HIST TR TY' REFERS TO TRANSACTION_HISTORY TYPES

STORED PROCEDURE TO SET STANDARD ARCHIVE PREFERENCE VALUES AS DEFINED BY THE CLOUD SERVICES TEAM.
VALUES CAN BE OVERRIDDEN WITH THE FOLLOWING CONFIGURABLE FIELDS:
1. ARCHIVE_PREFERENCES.USER_DEF1 IS USED TO STORE THE 'PARENT' ARCHIVE PREFERENCE FOR THE NEWLY CREATED AR_XX ARCHIVE PREFERENCES FOR EASIER TRACKING OF WHAT CAN BE TRUNCATED
2. ARCHIVE_PREFERENCES.USER_DEF2 (Y) DEFINES THAT THIS SCRIPT CAN MODIFY THE CORRESPONDING ARCHIVE_PREFERENCE WHICH IS MARKED AS SYSTEM_CREATED = N
3. ARCHIVE_PREFERENCES.USER_DEF3 (Y) DEFINES TO ALLOW CUSTOM SETTINGS FOR NON-PROD, THIS SCRIPT WILL NOT OVERRIDE THE ARCHIVE_PREFERENCE IF SET TO 'Y'
4. ARCHIVE_PREFERENCES.USER_DEF4 (Y) DEFINES TO ALLOW CUSTOM SETTINGS FOR PROD, THIS SCRIPT WILL NOT OVERRIDE THE ARCHIVE_PREFERENCE IF SET TO 'Y'
5. ARCHIVE_PREFERENCES.USER_DEF5 (Y OR N) DEFINES IF THE ARCHIVE PREFERENCE SHOULD BE ACTIVE OR NOT
6. ARCHIVE_PREFERENCES.USER_DEF6 (Y OR N) DEFINES THE VALUE FOR SAVE_DATA
7. ARCHIVE_PREFERENCES.USER_DEF7 (NUMBER) DEFINES THE VALUE FOR DAYS_HIST
8. SYSTEM_CONFIG_DETAIL.SYSTEM_VALUE WHERE RECORD_TYPE = N'MAS_DATASAVE_TIER2', TO ENABLE DATA SAVE TIER 2, BOTH THIS VALUE AND THE USER_DEF4 OF THIS SAME RECORD
    MUST BE SET TO 'Y'
9. SCHEDULED_JOBS.USER_DEF6 (HOLD) DEFINES IF A JOB IS INTENDED TO RUN LESS THAN EVERY 5 MINUTES. IF NOT MARKED, THIS SCRIPT WILL ENSURE THE MINIMUM MINUTES_FREQUENCY ALLOWED IS 5 

******************************************************************************************************************************************************************************
ARCHIVE PREFERENCES WITH AN ARCHIVE_NAME STARTING WTIH THE CLIENT_CODE OR MARKED AS SYSTEM_CREATED = N WILL BE IGNORED BY THIS SCRIPT, UNLESS ARCHIVE_PREFERENCE.USER_DEF2 = Y
******************************************************************************************************************************************************************************

IF ANY CUSTOMIZATIONS TO THE STANDARD ARCHIVE PREFERENCE VALUES AS DEFINED BY THE USER_DEF FIELDS IS REQUIRED, USER_DEF3 (NON-PROD) OR USER_DEF4 (PROD) NEEDS TO BE MARKED AS Y
THEN THE CORRESPONDING CONFIG COLUMN (SUCH AS SAVE_DATA) CAN BE CUSTOMIZED
FOR EXAMPLE, USER_DEF6 FOR "SAVE_DATA", IF USER_DEF6 IS Y AND SAVE_DATA IS N, AND USER_DEF3 (NON-PROD) OR USER_DEF4 (PROD) ARE NULL 
THIS SCRIPT WILL UPDATE SAVE_DATA BACK TO Y TO MATCH OUR STANDARD SETTINGS.
*/
CREATE   PROCEDURE [dbo].[ArchivePurgeRunbook] AS  
BEGIN
SET NOCOUNT ON;
/* DECLARE VARIABLES USED FOR CURSORS / INSERTS / UPDATES */
DECLARE @ARtableName nvarchar(250); /* LIST OF TABLES TO CREATE NEW ARCHIVE PREFERENCES INCLUDING PROCESS_HISTORY AND TRANSACTION_HISTORY BY TYPE, i.e. PROCESS_HISTORY_170 */
DECLARE @ARHistTableName NVARCHAR(250); /* ONLY USED TO TRIM OFF TYPES FROM PROCESS_HISTORY AND TRANSACTION_HISTORY FOR EASIER LOGIC i.e. PROCESS_HISTORY INSTEAD OF PROCESS_HISTORY_170 */
DECLARE @stArchiveID NVARCHAR(25);
DECLARE @FilterArchiveID NVARCHAR(25);
DECLARE @DaysHist NUMERIC(9,0) = 90;
DECLARE @NewArchivePrefTables TABLE (TABLE_NAME NVARCHAR(250))
INSERT INTO @NewArchivePrefTables
VALUES (N'LABEL_PRINT_REQUEST'),
        (N'SSRS_PRINTING_REQUEST'),
        (N'UPLOAD_LOCATION_INVENTORY_ATTRIBUTES'),
        (N'UPLOAD_SERIAL_NUMBER'); /* NEW ARCHIVE PREFERENCES TO CREATE WITH THIS SCRIPT */
DECLARE @ArchiveFilterTables TABLE (ARCHIVE_NAME NVARCHAR(50))
INSERT INTO @ArchiveFilterTables
VALUES (N'Wave'),
        (N'Work Instruction'),
        (N'Work Order Header'); /* ARCHIVE PREFERENCES GETTING AN EXTRA FILTER ADDED */
DECLARE @TABLEDONAME NVARCHAR(50);
DECLARE @DOPATH NVARCHAR(500); /* ONLY BEING USED FOR PROCESS_HISTORY AND TRANSACTION_HISTORY. AR_XX TABLES DO NOT REQUIRE THIS VALUE */
DECLARE @DataStorageType NVARCHAR(25) = N'DEFAULT'; /* DEFAULT MEANS TO ARCHIVE TO THE SAME DATABASE, MS SQL MEANS TO ARCHIVE TO THE HISTORIAL DATABASE USED IN DATA SAVE (TIER 2) ONLY */
DECLARE @Active NVARCHAR(25) = N'Y';
DECLARE @AR_Active NVARCHAR(25) = N'Y'; /* CONTROLS WHETHER THE AR_XX ARCHIVE PREFERENCES ARE SET TO ACTIVE OR NOT BY DEFAULT */
DECLARE @SaveData NVARCHAR(25) = N'Y';
DECLARE @stArchiveProcess NVARCHAR(25);
DECLARE @FilterStatement NVARCHAR(MAX);
DECLARE @IDENTIFIER NVARCHAR(50);
DECLARE @SYSTEMCREATED NVARCHAR(25);
DECLARE @USER6VALUE NVARCHAR(250);
DECLARE @sequence NUMERIC(5,0); 
DECLARE @attribute NVARCHAR(100);
DECLARE @literalvalue NVARCHAR(200);
DECLARE @operand NVARCHAR(15);
DECLARE @NonProdServerList TABLE (DB_SERVER NVARCHAR(250)) 
INSERT INTO @NonProdServerList
VALUES (N'sqlservereastustlsft'),
        (N'sqlserveraustraliasoutheastfxivr'),
        (N'sqlserverwesteuropebsfns'),
        (N'sqlserverwestindiaudrde');
SET @stArchiveProcess = (SELECT TOP 1 IDENTIFIER FROM DYNAMIC_CALLING_DETAIL WHERE RECORD_TYPE='ARCHIVE' AND DESCRIPTION='ArchiveData');
SET @sequence = 100;
/* FLAG ALL NON-BASE ARCHIVE_PREFERENCES AS SYSTEM_CREATED = N FOR PROPER CONTROL */
UPDATE ARCHIVE_PREFERENCES
SET SYSTEM_CREATED = N'N'
WHERE SYSTEM_CREATED = N'Y'
	AND (CASE WHEN PROCESS_STAMP LIKE N'DBCHANGE%' THEN SUBSTRING(PROCESS_STAMP, 9, 1) ELSE NULL END NOT LIKE '[0-9]'
		OR PROCESS_STAMP IS NULL
		OR PROCESS_STAMP NOT LIKE N'DBCHANGE%')
	AND ARCHIVE_ID NOT IN (
	'100','110','120','130','140','150','160','170','180','190',
	'200','210','220','230','240','250','260','270','290',
	'300','310','320','330','340','350','360','370','380','390',
	'40','400','410','420','430','450','460','470','480','490',
	'50','500','510','520','530','540','550','560','570','580','590',
	'60',
	'70',
	'90');
/* FLAG ALL NON-BASE GENERIC_CONFIG_DETAIL 'HIST PROC' AS SYSTEM_CREATED = N FOR PROPER CONTROL */
UPDATE GENERIC_CONFIG_DETAIL
SET SYSTEM_CREATED = N'N'
WHERE RECORD_TYPE='HIST PROC'
AND SYSTEM_CREATED = N'Y'
    AND (CASE WHEN PROCESS_STAMP LIKE N'DBCHANGE%' THEN SUBSTRING(PROCESS_STAMP, 9, 1) ELSE NULL END NOT LIKE '[0-9]'
        OR PROCESS_STAMP IS NULL
        OR PROCESS_STAMP NOT LIKE N'DBCHANGE%')
    AND IDENTIFIER NOT IN (
    '100','110','120','130','150','160','170','180',
    '20','200','210','220','230','240','250','260','270','280','290',
    '30','300','310','330','340','350','360','370','380','390',
    '40','400','410','420','430','440','450','460','470','480','490',
    '50','500','510','520','530','540','550','560','570','580','590',
    '60','600','610','620','630','640','650','660','670','680','690',
    '70','700','710','720','730',
    '80',
    '90');
/* FLAG ALL NON-BASE GENERIC_CONFIG_DETAIL 'HIST TR TY' AS SYSTEM_CREATED = N FOR PROPER CONTROL */
UPDATE GENERIC_CONFIG_DETAIL
SET SYSTEM_CREATED = N'N'
WHERE RECORD_TYPE='HIST TR TY'
AND SYSTEM_CREATED = N'Y'
    AND (CASE WHEN PROCESS_STAMP LIKE N'DBCHANGE%' THEN SUBSTRING(PROCESS_STAMP, 9, 1) ELSE NULL END NOT LIKE '[0-9]'
        OR PROCESS_STAMP IS NULL
        OR PROCESS_STAMP NOT LIKE N'DBCHANGE%')
    AND IDENTIFIER NOT IN (
    '10','100','110','120','130','140','150','160','165','170','180','190',
    '20','200','21','210','220','230','240','250','260','270','280','290',
    '30','300','310','320','330','340','350','360','370','380','390',
    '40','400','410','420','430','440','450','460','470','480','490',
    '50','500','510',
    '60',
    '70',
    '80',
    '90');
DECLARE @CustomArchivePreferences TABLE (ARCHIVE_NAME NVARCHAR(50)) /* ARCHIVE PREFERENCES THAT ARE NOT BASE AND NOT CREATED BY THIS SCRIPT, USUALLY CREATED BY MANHATTAN SERVICES */
INSERT INTO @CustomArchivePreferences (ARCHIVE_NAME)
(SELECT ARCHIVE_NAME
FROM ARCHIVE_PREFERENCES
WHERE (SYSTEM_CREATED = N'N' AND (USER_DEF2 IS NULL OR USER_DEF2 != N'Y'))
OR LEFT(ARCHIVE_NAME, 4) LIKE UPPER(LEFT(DB_NAME(), 4))); /* CUSTOM ARCHIVE PREFERENCES OR ARCHIVE PREFERENCES TO NOT MANAGE WITH THIS SCRIPT */
DECLARE @ProcessHistoryTypesToSave TABLE (IDENTIFIER NVARCHAR(50))
INSERT INTO @ProcessHistoryTypesToSave
VALUES (N'280'), /* Run wave */
    (N'300'), /* Shipment Processing */
    (N'700'); /* Deconsolidation */
DECLARE @TransactionHistoryTypesToPurge TABLE (IDENTIFIER NVARCHAR(50))
INSERT INTO @TransactionHistoryTypesToPurge
VALUES (N'30'), /* Immediate needs allocation */
    (N'80'), /* Locating */
    (N'170'), /* Replenishment allocation */
    (N'180'), /* Replenishment deallocation */
    (N'190'), /* Shipment allocation */
    (N'200'), /* Shipment deallocation */
    (N'280'), /* Work instruction change */
    (N'300'), /* Work order allocation */
    (N'310'), /* Work order deallocation */
    (N'420'), /* Dock Locating */
    (N'490'); /* Pre-Check In Container Creation */
DECLARE @TransactionHistoryTypesNonDefault TABLE (IDENTIFIER NVARCHAR(50))
INSERT INTO @TransactionHistoryTypesNonDefault
VALUES (N'70'), /* Load confirmation */
    (N'110'), /* Pack confirmation */
    (N'120'), /* Pick & Put confirmation */
    (N'130'), /* Pick confirmation */
    (N'140'), /* Putaway confirmation */
    (N'410'), /* Dock Transfer */
    (N'460'); /* Dock Location Pick and Putaway */
DECLARE @ProdArchiveUD5NTables TABLE (ARCHIVE_NAME NVARCHAR(50)) 
INSERT INTO @ProdArchiveUD5NTables
VALUES (N'Process History'),
        (N'Progistics Manifest and Transmit Data'),
        (N'Transaction History'); /* ARCHIVE PREFERENCES GETTING DEFAULTED TO ACTIVE=N AS THE STANDARD, ALL OTHERS WILL BE Y */
DECLARE @NonProdArchiveUD5NTables TABLE (ARCHIVE_NAME NVARCHAR(50)) 
INSERT INTO @NonProdArchiveUD5NTables
VALUES (N'Process History'),
        (N'Progistics Manifest and Transmit Data'),
        (N'Transaction History'); /* ARCHIVE PREFERENCES GETTING DEFAULTED TO ACTIVE=N AS THE STANDARD, ALL OTHERS WILL BE Y */
DECLARE @ProdArchiveUD6YTables TABLE (ARCHIVE_NAME NVARCHAR(50)) 
INSERT INTO @ProdArchiveUD6YTables
VALUES (N'Comment Text'),
        (N'Cycle Count Plan'),
        (N'Interface - Upload Item Balance'),
        (N'Inventory Attributes'),
        (N'Labor Management Detail'),
        (N'Labor Management Summary'),
        (N'Process History'),
        (N'Purchase Order Header'),
        (N'Quality History'),
        (N'Receipt Header'),
        (N'Receipt Quality History'),
        (N'Shipping Load'),
        (N'Tote Data'),
        (N'Transaction History'),
        (N'User Activity'),
        (N'Wave'),
        (N'Work Instruction'),
        (N'Work Order Header'); /* ARCHIVE PREFERENCES GETTING DEFAULTED TO SAVE_DATA = Y AS THE STANDARD, ALL OTHERS WILL BE N EXCEPT FOR PROCESS_HISTORY AND
                                TRANSACTION HISTORY WHO HAVE THEIR ARCHIVE_PREFERENCE.USER_DEF6 CONTROLLED BY GENERIC_CONFIG_DETAIL.USER6VALUE FOR EACH TYPE OF HISTORY */
DECLARE @DaysHistARTablesDefault NUMERIC(5, 0) = 372;
DECLARE @DaysHistMinimumValue NUMERIC(5, 0) = 7;
DECLARE @DaysHistPurgeValue NUMERIC(5, 0) = 30;
DECLARE @DaysHistDefaultValue NUMERIC(5, 0) = 90;
DECLARE @DaysHistMaximumValue NUMERIC(5, 0) = 180;
DECLARE @DaysHistArchivePreferencesMinimum TABLE (ARCHIVE_NAME NVARCHAR(50)) 
INSERT INTO @DaysHistArchivePreferencesMinimum
VALUES (N'DIF Incoming Message'),
        (N'DIF Outgoing Message'),
        (N'Dock Management Work Data'),
        (N'Interface - Download Item'),
        (N'Interface - Download Order Comment'),
        (N'Interface - Download Order Container'),
        (N'Interface - Download Order Detail'),
        (N'Interface - Download Order Header'),
        (N'Interface - Download Purchase Order Detail'),
        (N'Interface - Download Purchase Order Header'),
        (N'Interface - Download Receipt Container'),
        (N'Interface - Download Receipt Detail'),
        (N'Interface - Download Receipt Header'),
        (N'Interface - Upload Inventory Trans'),
        (N'Interface - Upload Receipt Container'),
        (N'Interface - Upload Receipt Detail'),
        (N'Interface - Upload Receipt Header'),
        (N'Inventory Management Work Data'),
        (N'Notification Message'),
        (N'Summary Requests'),
        (N'TRANSACTION_HISTORY_190'),
        (N'TRANSACTION_HISTORY_200'),
        (N'Warehouse Alert Requests'),
        (N'Work Instruction'); /* ARCHIVE PREFERENCES GETTING DEFAULTED TO DAYS_HIST = @DaysHistMinimumValue AS THE STANDARD, MOST WILL BE SET TO @DaysHistDefaultValue */
DECLARE @DaysHistArchivePreferencesMaximum TABLE (ARCHIVE_NAME NVARCHAR(50)) 
INSERT INTO @DaysHistArchivePreferencesMaximum
VALUES (N'Comment Text'),
        (N'Receipt Header'),
        (N'Shipping Load'); /* ARCHIVE PREFERENCES GETTING DEFAULTED TO DAYS_HIST = @DaysHistMaximumValue AS THE STANDARD, MOST WILL BE SET TO @DaysHistDefaultValue */
DECLARE @tableName NVARCHAR(250);
DECLARE @truncateSQL NVARCHAR(MAX);
DECLARE @HistType NVARCHAR(50);
DECLARE @DeleteLoopLimit NUMERIC(5, 0) = 10;
DECLARE @DeleteBatchSize NUMERIC(9, 0) = 500000;


/*******************************************************************************************************************************************************************************
STOP STOP STOP

ALL LOGIC BELOW THIS LINE SHOULD REMAIN STATIC, THERE SHOULD BE NO NEED TO CUSTOMIZE. IF YOU THINK SOMETHING NEEDS TO BE CHANGED, PLEASE LET THE TEAM KNOW SO THE SOURCE 
SCRIPT CAN BE UPDATED ACCORDINGLY

********************************************************************************************************************************************************************************/


/* ENSURE USER_DEF1 IS SET TO NULL FOR ALL ARCHIVE PREFERENCES IF IT IS NOT SET TO BE CUSTOMIZED */
UPDATE ARCHIVE_PREFERENCES
SET USER_DEF1 = CASE WHEN (CASE WHEN (SELECT @@SERVERNAME) IN (SELECT DB_SERVER FROM @NonProdServerList) THEN USER_DEF3 ELSE USER_DEF4 END IS NULL
                OR CASE WHEN (SELECT @@SERVERNAME) IN (SELECT DB_SERVER FROM @NonProdServerList) THEN USER_DEF3 ELSE USER_DEF4 END <> N'Y') AND USER_DEF1 IS NOT NULL THEN NULL ELSE USER_DEF1 END,
USER_DEF2 = CASE WHEN (CASE WHEN (SELECT @@SERVERNAME) IN (SELECT DB_SERVER FROM @NonProdServerList) THEN USER_DEF3 ELSE USER_DEF4 END IS NULL
                OR CASE WHEN (SELECT @@SERVERNAME) IN (SELECT DB_SERVER FROM @NonProdServerList) THEN USER_DEF3 ELSE USER_DEF4 END <> N'Y') AND USER_DEF2 IS NOT NULL AND USER_DEF2 != N'Y' THEN NULL ELSE USER_DEF2 END,
USER_DEF3 = CASE WHEN USER_DEF3 IS NOT NULL AND USER_DEF3 != N'Y' THEN NULL ELSE USER_DEF3 END,
USER_DEF4 = CASE WHEN USER_DEF4 IS NOT NULL AND USER_DEF4 != N'Y' THEN NULL ELSE USER_DEF4 END,
USER_DEF5 = CASE WHEN (CASE WHEN (SELECT @@SERVERNAME) IN (SELECT DB_SERVER FROM @NonProdServerList) THEN USER_DEF3 ELSE USER_DEF4 END IS NULL
                OR CASE WHEN (SELECT @@SERVERNAME) IN (SELECT DB_SERVER FROM @NonProdServerList) THEN USER_DEF3 ELSE USER_DEF4 END <> N'Y') AND USER_DEF5 IS NOT NULL AND USER_DEF5 NOT IN (N'Y', N'N') THEN NULL ELSE USER_DEF5 END,
USER_DEF6 = CASE WHEN (CASE WHEN (SELECT @@SERVERNAME) IN (SELECT DB_SERVER FROM @NonProdServerList) THEN USER_DEF3 ELSE USER_DEF4 END IS NULL
                OR CASE WHEN (SELECT @@SERVERNAME) IN (SELECT DB_SERVER FROM @NonProdServerList) THEN USER_DEF3 ELSE USER_DEF4 END <> N'Y') AND USER_DEF6 IS NOT NULL AND USER_DEF6 NOT IN (N'Y', N'N') THEN NULL ELSE USER_DEF6 END,
USER_DEF7 = CASE WHEN (CASE WHEN (SELECT @@SERVERNAME) IN (SELECT DB_SERVER FROM @NonProdServerList) THEN USER_DEF3 ELSE USER_DEF4 END IS NULL
                OR CASE WHEN (SELECT @@SERVERNAME) IN (SELECT DB_SERVER FROM @NonProdServerList) THEN USER_DEF3 ELSE USER_DEF4 END <> N'Y') AND USER_DEF7 IS NOT NULL 
                    AND USER_DEF7 NOT IN (
                    0, 
                    @DaysHistMinimumValue, 
                    @DaysHistPurgeValue, 
                    @DaysHistDefaultValue, 
                    @DaysHistMaximumValue) THEN NULL ELSE USER_DEF7 END;

/* CORRECT ARCHIVE_PROCESS FOR TRANSACTION_HISTORY */
UPDATE ARCHIVE_PREFERENCES
SET ARCHIVE_PROCESS = (SELECT TOP 1 IDENTIFIER FROM DYNAMIC_CALLING_DETAIL WHERE RECORD_TYPE='ARCHIVE' AND DESCRIPTION='Archive Transaction History and Attributes')
WHERE TABLE_DO_NAME = N'TRANSACTION_HISTORY'
AND ISNULL(ARCHIVE_PROCESS, N'!') <> ISNULL((SELECT TOP 1 IDENTIFIER FROM DYNAMIC_CALLING_DETAIL WHERE RECORD_TYPE='ARCHIVE' AND DESCRIPTION='Archive Transaction History and Attributes'), N'!');

/* REMOVE LEGACY PROCESS HISTORY PURGE AND TRANSACTION HISTORY PURGE AS THESE ARE NOW BEING CONTROLLED BY EACH TYPE OF HISTORY INDIVIDUALLY */
SET @stArchiveID = (SELECT ARCHIVE_ID FROM ARCHIVE_PREFERENCES WHERE ARCHIVE_NAME = N'Process History Purge');
  
/* IF LEGACY PROCESS HISTORY PURGE STILL EXISTS, REMOVE IT */  
IF EXISTS (SELECT 1 FROM FILTER_CONFIG_HEADER WHERE RECORD_TYPE = N'AR_' + @stArchiveID)  
BEGIN  
    UPDATE ARCHIVE_PREFERENCES  
    SET DATA_FILTER = NULL  
    WHERE ARCHIVE_ID = @stArchiveID;  
  
    DELETE FROM FILTER_STATEMENT  
    WHERE RECORD_TYPE = N'AR_' + @stArchiveID;  
  
    DELETE FROM FILTER_CONFIG_DETAIL  
    WHERE RECORD_TYPE = N'AR_' + @stArchiveID;  
  
    DELETE FROM FILTER_CONFIG_HEADER  
    WHERE RECORD_TYPE = N'AR_' + @stArchiveID; 
END

IF @stArchiveID IS NOT NULL
BEGIN
    DELETE FROM ARCHIVE_PREFERENCES
    WHERE ARCHIVE_ID = @stArchiveID;
END
 

SET @stArchiveID = (SELECT ARCHIVE_ID FROM ARCHIVE_PREFERENCES WHERE ARCHIVE_NAME = N'Transaction History Purge'); 
  
/* IF LEGACY TRANSACTION HISTORY PURGE STILL EXISTS, REMOVE IT */  
IF EXISTS (SELECT 1 FROM FILTER_CONFIG_HEADER WHERE RECORD_TYPE = N'AR_' + @stArchiveID)  
BEGIN  
    UPDATE ARCHIVE_PREFERENCES  
    SET DATA_FILTER = NULL  
    WHERE ARCHIVE_ID = @stArchiveID;  
  
    DELETE FROM FILTER_STATEMENT  
    WHERE RECORD_TYPE = N'AR_' + @stArchiveID;  
  
    DELETE FROM FILTER_CONFIG_DETAIL  
    WHERE RECORD_TYPE = N'AR_' + @stArchiveID;  
  
    DELETE FROM FILTER_CONFIG_HEADER  
    WHERE RECORD_TYPE = N'AR_' + @stArchiveID; 
END

IF @stArchiveID IS NOT NULL
BEGIN
    DELETE FROM ARCHIVE_PREFERENCES
    WHERE ARCHIVE_ID = @stArchiveID;
END 

/* INSERT A NEW SYSTEM_CONFIG_DETAIL RECORD TO ALLOW A CONFIGURATION TO CONTROL DATASAVE TIER 2 OR NOT. TO USE DATASAVE TIER 2, BOTH THE SYSTEM_VALUE AND USER_DEF4
    OF THE SYSTEM_CONFIG_DETAIL RECORD HAVE TO BE SET TO Y */
IF (SELECT SYS_KEY FROM SYSTEM_CONFIG_DETAIL WITH(NOLOCK) 
        WHERE ISNUMERIC(CAST(SYS_KEY AS VARCHAR)) = 1 
        AND CAST(CASE WHEN SYS_KEY NOT LIKE N'%-%' THEN SYS_KEY ELSE 0 END AS INT) = 5000) IS NULL
    SET @stArchiveID = 5000;
ELSE
BEGIN
    SET @stArchiveID = (SELECT TOP 1 CAST(T.SYS_KEY AS INT) + 1 AS NEXT_AVAILABLE_NUMBER
                        FROM (
                            SELECT 
                                SYS_KEY,
                                LEAD(CAST(SYS_KEY AS INT)) OVER (ORDER BY SYS_KEY) AS NEXT_NUMBER
                            FROM SYSTEM_CONFIG_DETAIL
                            WHERE ISNUMERIC(CAST(SYS_KEY AS VARCHAR)) = 1
                                AND SYS_KEY NOT LIKE N'%-%'
                                AND CAST(CASE WHEN SYS_KEY NOT LIKE N'%-%' THEN SYS_KEY ELSE 0 END AS INT) BETWEEN 5000 AND 9999
                        ) AS T
                        WHERE T.NEXT_NUMBER > CAST(T.SYS_KEY AS INT) + 1
                        ORDER BY T.SYS_KEY);

    IF @stArchiveID IS NULL
    BEGIN
        SET @stArchiveID = (SELECT CONVERT(NVARCHAR, MAX(
        CASE
            WHEN ISNUMERIC(CAST(SYS_KEY AS VARCHAR)) = 1
                    AND CAST(SYS_KEY AS INT) BETWEEN 5000 AND 9999
            THEN CAST(SYS_KEY AS INT)  /* INCREMENT IF BETWEEN 5000 AND 9999 */
            ELSE 4999 /* DEFAULT TO 4999 IF OUTSIDE THE RANGE */
        END + 1
        ))
        FROM SYSTEM_CONFIG_DETAIL)
    END
END

IF NOT EXISTS (SELECT 1 FROM SYSTEM_CONFIG_DETAIL WHERE DESCRIPTION = N'MAS DataSave Tier 2?')
BEGIN
    INSERT INTO [dbo].[SYSTEM_CONFIG_DETAIL]
               ([SYS_KEY]
               ,[DESCRIPTION]
               ,[SYSTEM_VALUE]
               ,[RECORD_TYPE]
               ,[LOOKUP_KEY]
               ,[SYSTEM_CREATED]
               ,[USER_DEF1]
               ,[USER_DEF2]
               ,[USER_DEF3]
               ,[USER_DEF4]
               ,[USER_DEF5]
               ,[USER_DEF6]
               ,[USER_DEF7]
               ,[USER_DEF8]
               ,[USER_STAMP]
               ,[PROCESS_STAMP]
               ,[DATE_TIME_STAMP]
               ,[VALUE_REQUIRED]
               ,[WAREHOUSE]
               ,[COMPANY])
         VALUES
               (@stArchiveID,  /* [SYS_KEY] */
               N'MAS DataSave Tier 2?', /* [DESCRIPTION] */
               N'N',                    /* [SYSTEM_VALUE] */
               N'Technical',            /* [RECORD_TYPE] */
               N'YN',                   /* [LOOKUP_KEY] */
               N'N',                    /* [SYSTEM_CREATED] */
               NULL,                    /* [USER_DEF1] */
               NULL,                    /* [USER_DEF2] */
               NULL,                    /* [USER_DEF3] */
               N'N',                    /* [USER_DEF4] */
               NULL,                    /* [USER_DEF5] */
               NULL,                    /* [USER_DEF6] */
               0,                       /* [USER_DEF7] */
               0,                       /* [USER_DEF8] */
               N'MANHATTAN_CLOUD',      /* [USER_STAMP] */
               N'ArchivePurgeRunbook',  /* [PROCESS_STAMP] */
               GETUTCDATE(),            /* [DATE_TIME_STAMP] */
               N'N',                    /* [VALUE_REQUIRED] */
               NULL,                    /* [WAREHOUSE] */
               NULL                     /* [COMPANY] */
               );
END
ELSE IF EXISTS (SELECT 1 FROM SYSTEM_CONFIG_DETAIL WHERE DESCRIPTION = N'MAS DataSave Tier 2?')
BEGIN
    UPDATE SYSTEM_CONFIG_DETAIL
    SET SYS_KEY = @stArchiveID
    WHERE DESCRIPTION = N'MAS DataSave Tier 2?';
END

/* DELETE ARCHIVE PREFERENCES CREATED BY THIS SCRIPT (THAT ARE NOT CUSTOMIZED) TO ENSURE THEY ARE RECREATED CORRECTLY AS OF THE MOST CURRENT UPDATES */
DECLARE cFilterDelete CURSOR FAST_FORWARD READ_ONLY FOR
SELECT ARCHIVE_ID
FROM ARCHIVE_PREFERENCES
WHERE ARCHIVE_NAME IN (
SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE'
 AND TABLE_NAME NOT LIKE '%[0-9]%'
 AND TABLE_NAME NOT LIKE N'%DSCSA%'
 AND TABLE_NAME NOT LIKE N'%' + UPPER(LEFT(DB_NAME(), 4)) + N'%'
    AND (TABLE_NAME LIKE 'AR[_]%'
  OR TABLE_NAME IN (SELECT TABLE_NAME COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS FROM @NewArchivePrefTables))
UNION ALL
SELECT CASE 
 WHEN RECORD_TYPE = N'HIST PROC' THEN N'PROCESS_HISTORY_' + LEFT(GCD.IDENTIFIER, 34) 
 WHEN RECORD_TYPE = N'HIST TR TY' THEN N'TRANSACTION_HISTORY_' + LEFT(GCD.IDENTIFIER, 30) END COLLATE SQL_Latin1_General_CP1_CI_AS AS TABLE_NAME
FROM GENERIC_CONFIG_DETAIL GCD WITH(NOLOCK)
WHERE RECORD_TYPE IN (N'HIST PROC', N'HIST TR TY'))
AND (CASE WHEN (SELECT @@SERVERNAME) IN (SELECT DB_SERVER FROM @NonProdServerList) THEN USER_DEF3 ELSE USER_DEF4 END IS NULL
    OR CASE WHEN (SELECT @@SERVERNAME) IN (SELECT DB_SERVER FROM @NonProdServerList) THEN USER_DEF3 ELSE USER_DEF4 END <> N'Y')
ORDER BY 1
OPEN cFilterDelete
FETCH NEXT FROM cFilterDelete INTO @stArchiveID
 
WHILE @@FETCH_STATUS = 0 
BEGIN


    /* IF LEGACY PROCESS HISTORY PURGE STILL EXISTS, REMOVE IT */  
    IF EXISTS (SELECT 1 FROM FILTER_CONFIG_HEADER WHERE RECORD_TYPE = N'AR_' + @stArchiveID)  
    BEGIN  
        UPDATE ARCHIVE_PREFERENCES  
        SET DATA_FILTER = NULL  
        WHERE ARCHIVE_ID = @stArchiveID;  
  
        DELETE FROM FILTER_STATEMENT  
        WHERE RECORD_TYPE = N'AR_' + @stArchiveID;  
  
        DELETE FROM FILTER_CONFIG_DETAIL  
        WHERE RECORD_TYPE = N'AR_' + @stArchiveID;  
  
        DELETE FROM FILTER_CONFIG_HEADER  
        WHERE RECORD_TYPE = N'AR_' + @stArchiveID; 
 
    END   

    DELETE FROM ARCHIVE_PREFERENCES
    WHERE ARCHIVE_ID = @stArchiveID;


    FETCH NEXT FROM cFilterDelete INTO @stArchiveID
 
END
 
CLOSE cFilterDelete
DEALLOCATE cFilterDelete

/* UPDATE ARCHIVE_PREFERENCES.USER_DEF5 FOR ACTIVE AND RUN_BY_DEFAULT TO STORE OUR STANDARD VALUES IF NOT PREVIOUSLY SET */
UPDATE ARCHIVE_PREFERENCES
SET USER_DEF5 = CASE 
        WHEN (SELECT @@SERVERNAME) IN (SELECT DB_SERVER FROM @NonProdServerList)
            AND ARCHIVE_NAME IN (SELECT ARCHIVE_NAME FROM @NonProdArchiveUD5NTables) THEN N'N' 
        WHEN (SELECT @@SERVERNAME) NOT IN (SELECT DB_SERVER FROM @NonProdServerList)
            AND ARCHIVE_NAME IN (SELECT ARCHIVE_NAME FROM @ProdArchiveUD5NTables) THEN N'N'
        WHEN ARCHIVE_NAME LIKE 'AR[_]%' THEN @AR_Active
        ELSE N'Y' END,
    USER_STAMP = N'MANHATTAN_CLOUD',
    PROCESS_STAMP = N'ArchivePurgeRunbook',
    DATE_TIME_STAMP = GETUTCDATE()
WHERE (USER_DEF5 IS NULL
    OR (CASE WHEN (SELECT @@SERVERNAME) IN (SELECT DB_SERVER FROM @NonProdServerList) THEN USER_DEF3 ELSE USER_DEF4 END IS NULL
        OR CASE WHEN (SELECT @@SERVERNAME) IN (SELECT DB_SERVER FROM @NonProdServerList) THEN USER_DEF3 ELSE USER_DEF4 END <> N'Y'))
AND ARCHIVE_NAME NOT IN (SELECT ARCHIVE_NAME FROM @CustomArchivePreferences);

/* UPDATE ACTIVE AND RUN_BY_DEFAULT BASED ON ARCHIVE_PREFERENCES.USER_DEF5 VALUE IF THE RECORD IS NOT CUSTOMIZED AS DEFINED BY ARCHIVE_PREFERENCE.USER_DEF3 FOR NON-PROD
    OR ARCHIVE_PREFERENCE.USER_DEF4 FOR PROD */
UPDATE ARCHIVE_PREFERENCES
SET ACTIVE = USER_DEF5,
    RUN_BY_DEFAULT = USER_DEF5,
    USER_STAMP = N'MANHATTAN_CLOUD',
    PROCESS_STAMP = N'ArchivePurgeRunbook',
    DATE_TIME_STAMP = GETUTCDATE()
WHERE (ACTIVE != USER_DEF5
    OR RUN_BY_DEFAULT != USER_DEF5)
AND (CASE WHEN (SELECT @@SERVERNAME) IN (SELECT DB_SERVER FROM @NonProdServerList) THEN USER_DEF3 ELSE USER_DEF4 END IS NULL
    OR CASE WHEN (SELECT @@SERVERNAME) IN (SELECT DB_SERVER FROM @NonProdServerList) THEN USER_DEF3 ELSE USER_DEF4 END <> N'Y')
AND UPPER(USER_DEF5) IN (N'N', N'Y')
AND ARCHIVE_NAME NOT IN (SELECT ARCHIVE_NAME FROM @CustomArchivePreferences);

/* UPDATE ARCHIVE_PREFERENCES.USER_DEF6 FOR SAVE_DATA FOR ALL OTHER ARCHIVE MASTERS THAT ARE NOT PROCESS_HISTORY OR TRANSACTION_HISTORY AS DETERMINED BY @ProdArchiveUD6YTables
    LIST FOR PROD. ALL NON-PROD ARCHIVE_PREFERNCES ARE SET TO 'N' AS THE DEFAULT STANDARD IF NOT PREVIOUSLY SET */
UPDATE ARCHIVE_PREFERENCES
SET USER_DEF6 = CASE WHEN (SELECT @@SERVERNAME) NOT IN (SELECT DB_SERVER FROM @NonProdServerList)
            AND ARCHIVE_NAME IN (SELECT ARCHIVE_NAME FROM @ProdArchiveUD6YTables) THEN N'Y' 
        ELSE N'N' END,
    USER_STAMP = N'MANHATTAN_CLOUD',
    PROCESS_STAMP = N'ArchivePurgeRunbook',
    DATE_TIME_STAMP = GETUTCDATE()
WHERE (USER_DEF6 IS NULL
    OR (CASE WHEN (SELECT @@SERVERNAME) IN (SELECT DB_SERVER FROM @NonProdServerList) THEN USER_DEF3 ELSE USER_DEF4 END IS NULL
        OR CASE WHEN (SELECT @@SERVERNAME) IN (SELECT DB_SERVER FROM @NonProdServerList) THEN USER_DEF3 ELSE USER_DEF4 END <> N'Y'))
AND ARCHIVE_NAME NOT LIKE N'PROCESS[_]HISTORY[_]%'
AND ARCHIVE_NAME NOT LIKE N'TRANSACTION[_]HISTORY[_]%'
AND ARCHIVE_NAME NOT IN (SELECT ARCHIVE_NAME FROM @CustomArchivePreferences);

/* UPDATE SAVE_DATA BASED ON ARCHIVE_PREFERENCES.USER_DEF6 VALUE IF THE RECORD IS NOT CUSTOMIZED AS DEFINED BY ARCHIVE_PREFERENCE.USER_DEF3 FOR NON-PROD
    OR ARCHIVE_PREFERENCE.USER_DEF4 FOR PROD */
UPDATE ARCHIVE_PREFERENCES
SET SAVE_DATA = USER_DEF6,
    USER_STAMP = N'MANHATTAN_CLOUD',
    PROCESS_STAMP = N'ArchivePurgeRunbook',
    DATE_TIME_STAMP = GETUTCDATE()
WHERE SAVE_DATA != USER_DEF6 
AND (CASE WHEN (SELECT @@SERVERNAME) IN (SELECT DB_SERVER FROM @NonProdServerList) THEN USER_DEF3 ELSE USER_DEF4 END IS NULL
    OR CASE WHEN (SELECT @@SERVERNAME) IN (SELECT DB_SERVER FROM @NonProdServerList) THEN USER_DEF3 ELSE USER_DEF4 END <> N'Y')
AND UPPER(USER_DEF6) IN (N'N', N'Y')
AND ARCHIVE_NAME NOT IN (SELECT ARCHIVE_NAME FROM @CustomArchivePreferences);

/* UPDATE ARCHIVE_PREFERENCE.USER_DEF7 FOR THE MINIMUM VALUE, WHICH ARE THE SAME BETWEEN NON-PROD AND PROD */
UPDATE ARCHIVE_PREFERENCES
SET USER_DEF7 = @DaysHistMinimumValue
WHERE ARCHIVE_NAME IN (SELECT ARCHIVE_NAME FROM @DaysHistArchivePreferencesMinimum)
AND (ISNULL(USER_DEF7, 0) = 0
    OR (CASE WHEN (SELECT @@SERVERNAME) IN (SELECT DB_SERVER FROM @NonProdServerList) THEN USER_DEF3 ELSE USER_DEF4 END IS NULL
        OR CASE WHEN (SELECT @@SERVERNAME) IN (SELECT DB_SERVER FROM @NonProdServerList) THEN USER_DEF3 ELSE USER_DEF4 END <> N'Y'))
AND ARCHIVE_NAME NOT IN (SELECT ARCHIVE_NAME FROM @CustomArchivePreferences);

/* UPDATE ARCHIVE_PREFERENCE.USER_DEF7 FOR THE MAXIMUM VALUE, WHICH ARE DIFFERENT BETWEEN NON-PROD AND PROD */
UPDATE ARCHIVE_PREFERENCES
SET USER_DEF7 = CASE WHEN (SELECT @@SERVERNAME) IN (SELECT DB_SERVER FROM @NonProdServerList)
    THEN @DaysHistDefaultValue
    ELSE @DaysHistMaximumValue
    END
WHERE ARCHIVE_NAME IN (SELECT ARCHIVE_NAME FROM @DaysHistArchivePreferencesMaximum)
AND (ISNULL(USER_DEF7, 0) = 0
    OR (CASE WHEN (SELECT @@SERVERNAME) IN (SELECT DB_SERVER FROM @NonProdServerList) THEN USER_DEF3 ELSE USER_DEF4 END IS NULL
        OR CASE WHEN (SELECT @@SERVERNAME) IN (SELECT DB_SERVER FROM @NonProdServerList) THEN USER_DEF3 ELSE USER_DEF4 END <> N'Y'))
AND ARCHIVE_NAME NOT IN (SELECT ARCHIVE_NAME FROM @CustomArchivePreferences);

/* UPDATE ARCHIVE_PREFERENCE.USER_DEF7 FOR PROCESS_HISTORY ARCHIVE PREFERENCES, WHICH ARE THE SAME BETWEEN NON-PROD AND PROD */
UPDATE ARCHIVE_PREFERENCES
SET USER_DEF7 = CASE WHEN ARCHIVE_NAME IN (SELECT ARCHIVE_NAME FROM @DaysHistArchivePreferencesMinimum)
    THEN @DaysHistMinimumValue
    WHEN RIGHT(ARCHIVE_NAME, LEN(ARCHIVE_NAME) - CHARINDEX(N'_', ARCHIVE_NAME, 14)) IN (SELECT IDENTIFIER FROM @ProcessHistoryTypesToSave)
    THEN @DaysHistDefaultValue
    ELSE @DaysHistPurgeValue
    END
WHERE ARCHIVE_NAME LIKE N'PROCESS[_]HISTORY[_]%'
AND (ISNULL(USER_DEF7, 0) = 0
    OR (CASE WHEN (SELECT @@SERVERNAME) IN (SELECT DB_SERVER FROM @NonProdServerList) THEN USER_DEF3 ELSE USER_DEF4 END IS NULL
        OR CASE WHEN (SELECT @@SERVERNAME) IN (SELECT DB_SERVER FROM @NonProdServerList) THEN USER_DEF3 ELSE USER_DEF4 END <> N'Y'));

/* UPDATE ARCHIVE_PREFERENCE.USER_DEF7 FOR TRANSACTION_HISTORY ARCHIVE PREFERENCES, WHICH ARE THE SAME BETWEEN NON-PROD AND PROD */
UPDATE ARCHIVE_PREFERENCES
SET USER_DEF7 = CASE WHEN ARCHIVE_NAME IN (SELECT ARCHIVE_NAME FROM @DaysHistArchivePreferencesMinimum)
    THEN @DaysHistMinimumValue
    WHEN RIGHT(ARCHIVE_NAME, LEN(ARCHIVE_NAME) - CHARINDEX(N'_', ARCHIVE_NAME, 14)) IN (SELECT IDENTIFIER FROM @TransactionHistoryTypesToPurge)
        OR RIGHT(ARCHIVE_NAME, LEN(ARCHIVE_NAME) - CHARINDEX(N'_', ARCHIVE_NAME, 14)) IN (SELECT IDENTIFIER FROM @TransactionHistoryTypesNonDefault)
    THEN @DaysHistPurgeValue
    ELSE @DaysHistDefaultValue
    END
WHERE ARCHIVE_NAME LIKE N'TRANSACTION[_]HISTORY[_]%'
AND (ISNULL(USER_DEF7, 0) = 0
    OR (CASE WHEN (SELECT @@SERVERNAME) IN (SELECT DB_SERVER FROM @NonProdServerList) THEN USER_DEF3 ELSE USER_DEF4 END IS NULL
        OR CASE WHEN (SELECT @@SERVERNAME) IN (SELECT DB_SERVER FROM @NonProdServerList) THEN USER_DEF3 ELSE USER_DEF4 END <> N'Y'));

/* UPDATE ARCHIVE_PREFERENCE.USER_DEF7 FOR AR_XX ARCHIVE PREFERENCES TO THE ONE-YEAR DATA RETENTION DEFAULT */
UPDATE ARCHIVE_PREFERENCES
SET USER_DEF7 = CASE WHEN ARCHIVE_NAME IN (N'AR_WORK_INSTRUCTION', N'AR_IA_WORK_INSTRUCTION')
        AND (SELECT ISNULL(USER_DEF4, N'!') FROM ARCHIVE_PREFERENCES WITH(NOLOCK) WHERE ARCHIVE_NAME = N'Work Instruction') <> N'Y'
        AND USER_DEF4 IS NULL OR USER_DEF4 <> N'Y'
    THEN @DaysHistDefaultValue
    ELSE @DaysHistARTablesDefault
    END
WHERE ARCHIVE_NAME LIKE 'AR[_]%'
AND (ISNULL(USER_DEF7, 0) = 0
    OR (CASE WHEN (SELECT @@SERVERNAME) IN (SELECT DB_SERVER FROM @NonProdServerList) THEN USER_DEF3 ELSE USER_DEF4 END IS NULL
        OR CASE WHEN (SELECT @@SERVERNAME) IN (SELECT DB_SERVER FROM @NonProdServerList) THEN USER_DEF3 ELSE USER_DEF4 END <> N'Y'));

/* UPDATE ARCHIVE_PREFERENCE.USER_DEF7 FOR THE DEFAULT VALUE IF NOT ALREADY SET */
UPDATE ARCHIVE_PREFERENCES
SET USER_DEF7 = @DaysHistDefaultValue
WHERE ISNULL(USER_DEF7, 0) = 0
AND ARCHIVE_NAME NOT IN (SELECT ARCHIVE_NAME FROM @CustomArchivePreferences);

/* UPDATE DAYS_HIST BASED ON ARCHIVE_PREFERENCES.USER_DEF7 VALUE IF THE RECORD IS NOT CUSTOMIZED AS DEFINED BY ARCHIVE_PREFERENCE.USER_DEF3 FOR NON-PROD
    OR ARCHIVE_PREFERENCE.USER_DEF4 FOR PROD */
UPDATE ARCHIVE_PREFERENCES
SET DAYS_HIST = USER_DEF7,
    USER_STAMP = N'MANHATTAN_CLOUD',
    PROCESS_STAMP = N'ArchivePurgeRunbook',
    DATE_TIME_STAMP = GETUTCDATE()
WHERE ISNULL(DAYS_HIST, 0) != USER_DEF7
AND (CASE WHEN (SELECT @@SERVERNAME) IN (SELECT DB_SERVER FROM @NonProdServerList) THEN USER_DEF3 ELSE USER_DEF4 END IS NULL
    OR CASE WHEN (SELECT @@SERVERNAME) IN (SELECT DB_SERVER FROM @NonProdServerList) THEN USER_DEF3 ELSE USER_DEF4 END <> N'Y')
AND ISNULL(USER_DEF7, 0) > 0
AND ARCHIVE_NAME NOT IN (SELECT ARCHIVE_NAME FROM @CustomArchivePreferences);

/* CREATE NEW ARCHIVE PREFERENCES FOR 
    AR_XX TABLES 
    ALL PROCESS_HISTORY AND TRANSACTION_HISTORY TYPES
    LABEL_PRINT_REQUEST
    SSRS_PRINTING_REQUEST
    UPLOAD_LOCATION_INVENTORY_ATTRIBUTES 
*/
DECLARE cArchiveCreate CURSOR FAST_FORWARD READ_ONLY FOR
SELECT TABLE_NAME, NULL AS IDENTIFIER, NULL AS SYSTEM_CREATED
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE'
	AND TABLE_NAME NOT LIKE '%[0-9]%'
	AND TABLE_NAME NOT LIKE N'%DSCSA%'
	AND TABLE_NAME NOT LIKE N'%' + UPPER(LEFT(DB_NAME(), 4)) + N'%'
    AND (TABLE_NAME LIKE 'AR[_]%'
		OR TABLE_NAME IN (SELECT TABLE_NAME COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS FROM @NewArchivePrefTables))
UNION ALL
SELECT CASE 
	WHEN RECORD_TYPE = N'HIST PROC' THEN N'PROCESS_HISTORY_' + LEFT(GCD.IDENTIFIER, 34) 
	WHEN RECORD_TYPE = N'HIST TR TY' THEN N'TRANSACTION_HISTORY_' + LEFT(GCD.IDENTIFIER, 30) END COLLATE SQL_Latin1_General_CP1_CI_AS AS TABLE_NAME, 
	GCD.IDENTIFIER, GCD.SYSTEM_CREATED
FROM GENERIC_CONFIG_DETAIL GCD WITH(NOLOCK)
WHERE RECORD_TYPE IN (N'HIST PROC', N'HIST TR TY')
ORDER BY TABLE_NAME
OPEN cArchiveCreate
FETCH NEXT FROM cArchiveCreate INTO @ARtableName, @IDENTIFIER, @SYSTEMCREATED
 
WHILE @@FETCH_STATUS = 0 
BEGIN
    /* SET ARHISTTABLENAME TO TRIM OFF _170 FOR EXAMPLE FROM PROCESS_HISTORY_170 */
    SET @ARHistTableName = (SELECT LEFT(@ARtableName, CHARINDEX(N'_', @ARtableName, 14)-1) 
        WHERE @ARtableName LIKE N'PROCESS[_]HISTORY[_]%'
            OR @ARtableName LIKE N'TRANSACTION[_]HISTORY[_]%');
    SET @DOPATH = (SELECT TOP 1 DO_PATH FROM ARCHIVE_PREFERENCES WHERE TABLE_DO_NAME = @ARHistTableName AND @ARHistTableName IN (N'PROCESS_HISTORY', N'TRANSACTION_HISTORY'));
    /* SET @stArchiveID TO THE MATCHING ARCHIVE_ID IF THE RECORD ALREADY EXISTS */
    SET @stArchiveID = (SELECT ARCHIVE_ID FROM ARCHIVE_PREFERENCES WHERE ARCHIVE_NAME = @ARtableName);

    /* IF THE ARCHIVE PREFERENCE TO BE CREATED DOES NOT ALREADY EXIST, CREATE IT */
    IF @stArchiveID IS NULL  
    BEGIN
        IF (SELECT ARCHIVE_ID FROM ARCHIVE_PREFERENCES WITH(NOLOCK) 
                WHERE ISNUMERIC(CAST(ARCHIVE_ID AS VARCHAR)) = 1 
                AND CAST(CASE WHEN ARCHIVE_ID NOT LIKE N'%-%' THEN ARCHIVE_ID ELSE 0 END AS INT) = 5000) IS NULL
            SET @stArchiveID = 5000;
        ELSE
        BEGIN
            SET @stArchiveID = (SELECT TOP 1 CAST(T.ARCHIVE_ID AS INT) + 1 AS NEXT_AVAILABLE_NUMBER
                                FROM (
                                    SELECT 
                                        ARCHIVE_ID,
                                        LEAD(CAST(ARCHIVE_ID AS INT)) OVER (ORDER BY ARCHIVE_ID) AS NEXT_NUMBER
                                    FROM ARCHIVE_PREFERENCES
                                    WHERE ISNUMERIC(CAST(ARCHIVE_ID AS VARCHAR)) = 1
                                        AND ARCHIVE_ID NOT LIKE N'%-%'
                                        AND CAST(CASE WHEN ARCHIVE_ID NOT LIKE N'%-%' THEN ARCHIVE_ID ELSE 0 END AS INT) BETWEEN 5000 AND 9999
                                ) AS T
                                WHERE T.NEXT_NUMBER > CAST(T.ARCHIVE_ID AS INT) + 1
                                ORDER BY T.ARCHIVE_ID);

            IF @stArchiveID IS NULL
            BEGIN
                SET @stArchiveID = (SELECT CONVERT(NVARCHAR, MAX(
                CASE
                    WHEN ISNUMERIC(CAST(ARCHIVE_ID AS VARCHAR)) = 1
                            AND CAST(ARCHIVE_ID AS INT) BETWEEN 5000 AND 9999
                    THEN CAST(ARCHIVE_ID AS INT)  /* INCREMENT IF BETWEEN 5000 AND 9999 */
                    ELSE 4999 /* DEFAULT TO 4999 IF OUTSIDE THE RANGE */
                END + 1
                ))
                FROM ARCHIVE_PREFERENCES)
            END
        END

        IF (@ARtableName LIKE 'AR[_]%' 
			AND (EXISTS (SELECT N'%' FROM SYSTEM_CONFIG_DETAIL 
					WHERE DESCRIPTION = N'MAS DataSave Tier 2?' 
					AND (SYSTEM_VALUE = N'N' 
					OR USER_DEF4 = N'N')) /* AND NEW CONFIG VALUE FOR MAS_DATASAVE_TIER2 = N */
				OR NOT EXISTS (SELECT N'%' FROM SYSTEM_CONFIG_DETAIL 
					WHERE DESCRIPTION = N'MAS DataSave Tier 2?')
				OR (SELECT @@SERVERNAME) IN (SELECT DB_SERVER FROM @NonProdServerList)))	
        BEGIN
            SET @DaysHist = CASE WHEN @ARtableName IN (N'AR_WORK_INSTRUCTION', N'AR_IA_WORK_INSTRUCTION')
                    AND (SELECT ISNULL(USER_DEF4, N'!') FROM ARCHIVE_PREFERENCES WITH(NOLOCK) WHERE ARCHIVE_NAME = N'Work Instruction') <> N'Y'
                THEN @DaysHistDefaultValue
                ELSE @DaysHistARTablesDefault
                END
            SET @SaveData = N'N';
            SET @Active = @AR_Active;
            SET @DataStorageType = N'DEFAULT';
        END
        ELSE IF (@ARtableName LIKE 'AR[_]%' AND 
            EXISTS (SELECT N'%' FROM SYSTEM_CONFIG_DETAIL 
                WHERE DESCRIPTION = N'MAS DataSave Tier 2?' 
                AND SYSTEM_VALUE = N'Y' 
                AND USER_DEF4 = N'Y')) /* AND NEW CONFIG VALUE FOR MAS_DATASAVE_TIER2 = Y */
        BEGIN
            SET @DaysHist = CASE WHEN @ARtableName IN (N'AR_WORK_INSTRUCTION', N'AR_IA_WORK_INSTRUCTION')
                    AND (SELECT ISNULL(USER_DEF4, N'!') FROM ARCHIVE_PREFERENCES WITH(NOLOCK) WHERE ARCHIVE_NAME = N'Work Instruction') <> N'Y'
                THEN @DaysHistDefaultValue
                ELSE @DaysHistARTablesDefault
                END;
            SET @SaveData = N'Y';
            SET @Active = @AR_Active;
            SET @DataStorageType = N'MS SQL';
        END
        ELSE IF @ARtableName IN (SELECT TABLE_NAME FROM @NewArchivePrefTables)
        BEGIN
            SET @DaysHist = @DaysHistMinimumValue;
            SET @SaveData = N'N';
            SET @Active = N'Y';
            SET @DataStorageType = N'DEFAULT';
        END
        ELSE IF @ARHistTableName IN (N'PROCESS_HISTORY')
        BEGIN
            SET @DaysHist = CASE WHEN @ARtableName IN (SELECT ARCHIVE_NAME FROM @DaysHistArchivePreferencesMinimum)
                            THEN @DaysHistMinimumValue
                            WHEN @IDENTIFIER IN (SELECT IDENTIFIER FROM @ProcessHistoryTypesToSave) OR @SYSTEMCREATED = N'N'
                            THEN @DaysHistDefaultValue
                            ELSE @DaysHistPurgeValue
                            END
            SET @SaveData = CASE WHEN (@IDENTIFIER IN (SELECT IDENTIFIER FROM @ProcessHistoryTypesToSave) OR @SYSTEMCREATED = N'N')
                                    AND (SELECT @@SERVERNAME) NOT IN (SELECT DB_SERVER FROM @NonProdServerList)
                            THEN N'Y'
                            ELSE N'N'
                            END
            SET @Active = N'Y';
            SET @DataStorageType = N'DEFAULT';
        END
        ELSE IF @ARHistTableName IN (N'TRANSACTION_HISTORY')
        BEGIN
            SET @DaysHist = CASE WHEN @ARtableName IN (SELECT ARCHIVE_NAME FROM @DaysHistArchivePreferencesMinimum)
                            THEN @DaysHistMinimumValue
                            WHEN @IDENTIFIER IN (SELECT IDENTIFIER FROM @TransactionHistoryTypesToPurge)
                                OR @IDENTIFIER IN (SELECT IDENTIFIER FROM @TransactionHistoryTypesNonDefault)
                            THEN @DaysHistPurgeValue
                            ELSE @DaysHistDefaultValue
                            END
            SET @SaveData = CASE WHEN @IDENTIFIER IN (SELECT IDENTIFIER FROM @TransactionHistoryTypesToPurge)
                                    OR (SELECT @@SERVERNAME) IN (SELECT DB_SERVER FROM @NonProdServerList)
                            THEN N'N'
                            ELSE N'Y'
                            END
            SET @Active = N'Y';
            SET @DataStorageType = N'DEFAULT';
        END

        INSERT INTO [ARCHIVE_PREFERENCES]
            ([ARCHIVE_ID]
            ,[ARCHIVE_NAME]
            ,[ARCHIVE_PROCESS]
            ,[TABLE_DO_NAME]
            ,[DO_PATH]
            ,[DAYS_HIST]
            ,[DATA_FILTER]
            ,[SAVE_DATA]
            ,[RUN_BY_DEFAULT]
            ,[LAST_ARCH_DATE_TIME]
            ,[SYSTEM_CREATED]
            ,[ACTIVE]
            ,[USER_DEF1]
            ,[USER_DEF2]
            ,[USER_DEF3]
            ,[USER_DEF4]
            ,[USER_DEF5]
            ,[USER_DEF6]
            ,[USER_DEF7]
            ,[USER_DEF8]
            ,[USER_STAMP]
            ,[PROCESS_STAMP]
            ,[DATE_TIME_STAMP]
            ,[DATA_STORAGE_TYPE])
        VALUES 
            (@stArchiveID, /*[ARCHIVE_ID]*/
            @ARtableName, /*[ARCHIVE_NAME]*/
            CASE WHEN @ARHistTableName IS NOT NULL AND @ARHistTableName = N'TRANSACTION_HISTORY' THEN 
                (SELECT TOP 1 IDENTIFIER FROM DYNAMIC_CALLING_DETAIL WHERE RECORD_TYPE='ARCHIVE' AND DESCRIPTION='Archive Transaction History and Attributes')
                ELSE @stArchiveProcess END, /*[ARCHIVE_PROCESS]*/
            CASE WHEN @ARHistTableName IS NOT NULL THEN @ARHistTableName ELSE @ARtableName END, /*[TABLE_DO_NAME]*/
            @DOPATH, /*[DO_PATH]*/
            @DaysHist, /*[DAYS_HIST]*/
            NULL, /*[DATA_FILTER]*/
            @SaveData, /*[SAVE_DATA]*/
            @Active, /*[RUN_BY_DEFAULT]*/
            NULL, /*[LAST_ARCH_DATE_TIME]*/
            N'N', /*[SYSTEM_CREATED]*/
            @Active, /*[ACTIVE]*/
            CASE 
	            WHEN @ARtableName = N'AR_APPOINTMENT_SCHEDULE' THEN (SELECT TOP 1 ARCHIVE_ID FROM ARCHIVE_PREFERENCES WHERE TABLE_DO_NAME = N'RECEIPT_HEADER')
	            WHEN @ARtableName = N'AR_AUDIT_LOG_VALUE' THEN (SELECT TOP 1 ARCHIVE_ID FROM ARCHIVE_PREFERENCES WHERE TABLE_DO_NAME = N'AUDIT_LOG')
	            WHEN @ARtableName = N'AR_CYCLE_COUNT_REQUEST' THEN (SELECT TOP 1 ARCHIVE_ID FROM ARCHIVE_PREFERENCES WHERE TABLE_DO_NAME = N'CYCLE_COUNT_PLAN')
	            WHEN @ARtableName = N'AR_DELETED_RECEIPT_CONTAINER' THEN (SELECT TOP 1 ARCHIVE_ID FROM ARCHIVE_PREFERENCES WHERE TABLE_DO_NAME = N'RECEIPT_HEADER')
	            WHEN @ARtableName = N'AR_IA_WORK_INSTRUCTION' THEN (SELECT TOP 1 ARCHIVE_ID FROM ARCHIVE_PREFERENCES WHERE TABLE_DO_NAME = N'WORK_INSTRUCTION')
	            WHEN @ARtableName = N'AR_MULTI_ORDER_PALLET' THEN (SELECT TOP 1 ARCHIVE_ID FROM ARCHIVE_PREFERENCES WHERE TABLE_DO_NAME = N'SHIPPING_LOAD')
	            WHEN @ARtableName = N'AR_ORDER_DETAIL' THEN (SELECT TOP 1 ARCHIVE_ID FROM ARCHIVE_PREFERENCES WHERE TABLE_DO_NAME = N'ORDER_HEADER')
	            WHEN @ARtableName = N'AR_RECEIPT_CATCH_WEIGHT_INFO' THEN (SELECT TOP 1 ARCHIVE_ID FROM ARCHIVE_PREFERENCES WHERE TABLE_DO_NAME = N'RECEIPT_HEADER')
	            WHEN @ARtableName = N'AR_RECEIPT_CONTAINER' THEN (SELECT TOP 1 ARCHIVE_ID FROM ARCHIVE_PREFERENCES WHERE TABLE_DO_NAME = N'RECEIPT_HEADER')
	            WHEN @ARtableName = N'AR_RECEIPT_DETAIL' THEN (SELECT TOP 1 ARCHIVE_ID FROM ARCHIVE_PREFERENCES WHERE TABLE_DO_NAME = N'RECEIPT_HEADER')
	            WHEN @ARtableName = N'AR_SHIPMENT_ACCESSORIALS' THEN (SELECT TOP 1 ARCHIVE_ID FROM ARCHIVE_PREFERENCES WHERE TABLE_DO_NAME = N'SHIPPING_LOAD')
	            WHEN @ARtableName = N'AR_SHIPMENT_ALLOC_REQUEST' THEN (SELECT TOP 1 ARCHIVE_ID FROM ARCHIVE_PREFERENCES WHERE TABLE_DO_NAME = N'SHIPPING_LOAD')
	            WHEN @ARtableName = N'AR_SHIPMENT_DETAIL' THEN (SELECT TOP 1 ARCHIVE_ID FROM ARCHIVE_PREFERENCES WHERE TABLE_DO_NAME = N'SHIPPING_LOAD')
	            WHEN @ARtableName = N'AR_SHIPMENT_HEADER' THEN (SELECT TOP 1 ARCHIVE_ID FROM ARCHIVE_PREFERENCES WHERE TABLE_DO_NAME = N'SHIPPING_LOAD')
                WHEN @ARtableName = N'AR_SHIPMENT_HEADER_LOCATION' THEN (SELECT TOP 1 ARCHIVE_ID FROM ARCHIVE_PREFERENCES WHERE TABLE_DO_NAME = N'SHIPPING_LOAD')
                WHEN @ARtableName = N'AR_SHIPMENT_HEADER_VAS_ACTIVITY' THEN (SELECT TOP 1 ARCHIVE_ID FROM ARCHIVE_PREFERENCES WHERE TABLE_DO_NAME = N'SHIPPING_LOAD')
	            WHEN @ARtableName = N'AR_SHIPPING_CONT_QC_COUNT' THEN (SELECT TOP 1 ARCHIVE_ID FROM ARCHIVE_PREFERENCES WHERE TABLE_DO_NAME = N'SHIPPING_LOAD')
                WHEN @ARtableName = N'AR_SHIPPING_CONT_QC_EVALUATION' THEN (SELECT TOP 1 ARCHIVE_ID FROM ARCHIVE_PREFERENCES WHERE TABLE_DO_NAME = N'SHIPPING_LOAD')
	            WHEN @ARtableName = N'AR_SHIPPING_CONT_QC_REASON_CODE' THEN (SELECT TOP 1 ARCHIVE_ID FROM ARCHIVE_PREFERENCES WHERE TABLE_DO_NAME = N'SHIPPING_LOAD')
                WHEN @ARtableName = N'AR_SHIPPING_CONT_VAS_ACTIVITY' THEN (SELECT TOP 1 ARCHIVE_ID FROM ARCHIVE_PREFERENCES WHERE TABLE_DO_NAME = N'SHIPPING_LOAD')
	            WHEN @ARtableName = N'AR_SHIPPING_CONTAINER' THEN (SELECT TOP 1 ARCHIVE_ID FROM ARCHIVE_PREFERENCES WHERE TABLE_DO_NAME = N'SHIPPING_LOAD')
                WHEN @ARtableName = N'AR_SHIPPING_CONTAINER_LOCATION' THEN (SELECT TOP 1 ARCHIVE_ID FROM ARCHIVE_PREFERENCES WHERE TABLE_DO_NAME = N'SHIPPING_LOAD')
	            WHEN @ARtableName = N'AR_TOTE_DETAIL' THEN (SELECT TOP 1 ARCHIVE_ID FROM ARCHIVE_PREFERENCES WHERE TABLE_DO_NAME = N'SHIPPING_LOAD')
	            WHEN @ARtableName = N'AR_WORK_ORDER_DETAIL' THEN (SELECT TOP 1 ARCHIVE_ID FROM ARCHIVE_PREFERENCES WHERE TABLE_DO_NAME = N'WORK_ORDER_HEADER')
	            WHEN @ARtableName = N'AR_WORK_ORDER_PUTAWAY_UNIT' THEN (SELECT TOP 1 ARCHIVE_ID FROM ARCHIVE_PREFERENCES WHERE TABLE_DO_NAME = N'WORK_ORDER_HEADER')
                ELSE (SELECT TOP 1 ARCHIVE_ID FROM ARCHIVE_PREFERENCES WHERE TABLE_DO_NAME = REPLACE(@ARtableName, N'AR_', N'') 
                        AND REPLACE(@ARtableName, N'AR_', N'') NOT IN (N'PROCESS_HISTORY', N'TRANSACTION_HISTORY'))
            END, /*[USER_DEF1], SETTING THE PARENT ARCHIVE PREFERENCE FOR NESTED AR_XX TABLES */
            N'Y', /*[USER_DEF2]*/
            NULL, /*[USER_DEF3]*/
            NULL, /*[USER_DEF4]*/
            CASE WHEN @ARtableName LIKE 'AR[_]%' THEN @AR_Active ELSE NULL END, /*[USER_DEF5]*/
            @SaveData, /*[USER_DEF6]*/
            @DaysHist, /*[USER_DEF7]*/
            0, /*[USER_DEF8]*/
            N'MANHATTAN_CLOUD', /*[USER_STAMP]*/
            N'ArchivePurgeRunbook', /*[PROCESS_STAMP]*/
            GETUTCDATE(), /*[DATE_TIME_STAMP]*/
            @DataStorageType /*[DATA_STORAGE_TYPE]*/
            )
    END
    FETCH NEXT FROM cArchiveCreate INTO @ARtableName, @IDENTIFIER, @SYSTEMCREATED
 
END
 
CLOSE cArchiveCreate
DEALLOCATE cArchiveCreate

/* CREATE FILTERS FOR ARCHIVE PREFERENCES THAT REQUIRE THEM */
DECLARE cFilterCreate CURSOR FAST_FORWARD READ_ONLY FOR
SELECT ARCHIVE_ID, LEFT(ARCHIVE_NAME, 25), TABLE_DO_NAME, DO_PATH, CASE WHEN GCDP.IDENTIFIER IS NULL THEN GCDT.IDENTIFIER ELSE GCDP.IDENTIFIER END AS IDENTIFIER
FROM ARCHIVE_PREFERENCES AP WITH(NOLOCK)
LEFT OUTER JOIN GENERIC_CONFIG_DETAIL GCDP WITH(NOLOCK)
ON GCDP.RECORD_TYPE = N'HIST PROC'
AND LEFT(GCDP.IDENTIFIER, 34) = LEFT(REPLACE(AP.ARCHIVE_NAME, N'PROCESS_HISTORY_', N''), 34)
LEFT OUTER JOIN GENERIC_CONFIG_DETAIL GCDT WITH(NOLOCK)
ON GCDT.RECORD_TYPE = N'HIST TR TY'
AND LEFT(GCDT.IDENTIFIER, 30) = LEFT(REPLACE(AP.ARCHIVE_NAME, N'TRANSACTION_HISTORY_', N''), 30)
WHERE ARCHIVE_NAME IN (SELECT ARCHIVE_NAME FROM @ArchiveFilterTables)
	OR (ARCHIVE_NAME LIKE N'PROCESS[_]HISTORY[_]%'
		OR ARCHIVE_NAME LIKE N'TRANSACTION[_]HISTORY[_]%')
ORDER BY ARCHIVE_NAME
OPEN cFilterCreate
FETCH NEXT FROM cFilterCreate INTO @stArchiveID, @ARtableName, @TABLEDONAME, @DOPATH, @IDENTIFIER
 
WHILE @@FETCH_STATUS = 0 
BEGIN

    SET @FilterArchiveID = N'AR_' + @stArchiveID;
    SET @FilterStatement = NULL;
    SET @attribute = NULL;
    SET @operand = NULL;
    SET @literalvalue = NULL;
  
    /* IF THE FILTER ALREADY EXISTS, REMOVE IT SO IT CAN BE RECREATED AS DEFINED BY THE SCRIPT. NO CUSTOMIZATIONS ALLOWED ON THESE FILTERS */
    IF EXISTS (SELECT N'%' FROM FILTER_CONFIG_HEADER WHERE RECORD_TYPE = @FilterArchiveID)  
    BEGIN  
        UPDATE ARCHIVE_PREFERENCES  
        SET DATA_FILTER = NULL  
        WHERE ARCHIVE_ID = @stArchiveID;  
  
        DELETE FROM FILTER_STATEMENT  
        WHERE RECORD_TYPE = @FilterArchiveID;  
  
        DELETE FROM FILTER_CONFIG_DETAIL  
        WHERE RECORD_TYPE = @FilterArchiveID;  
  
        DELETE FROM FILTER_CONFIG_HEADER  
        WHERE RECORD_TYPE = @FilterArchiveID;  
    END  
  
    /* CREATE THE STANDARD FILTERS AS DEFINED BY THIS STORED PROCEDURE */ 
    IF NOT EXISTS (SELECT N'%' FROM FILTER_CONFIG_HEADER WHERE RECORD_TYPE = @FilterArchiveID)   
    BEGIN 
        /* SET NECESSARY VARIABLES BASED ON MATCHING ARCHIVE PREFERENCE FOR THE FILTER INSERTS */
        IF @TABLEDONAME IN (N'WORK_ORDER_HEADER', N'WORK_INSTRUCTION')
        BEGIN
            SET @FilterStatement = N'SELECT * FROM ' + @TABLEDONAME + N' WHERE (CONDITION = N''Closed'')';
            SET @attribute = N'CONDITION';
            SET @operand = N'=';
            SET @literalvalue = N'N''Closed''';
        END
        ELSE IF @TABLEDONAME IN (N'LAUNCH_STATISTICS')
        BEGIN
            SET @FilterStatement = N'SELECT * FROM ' + @TABLEDONAME + N' WHERE (Closed = N''Y'')';
            SET @attribute = N'CLOSED';
            SET @operand = N'=';
            SET @literalvalue = N'N''Y''';
        END
        ELSE IF @TABLEDONAME IN (N'PROCESS_HISTORY')
        BEGIN
            SET @FilterStatement = N'SELECT * FROM ' + @TABLEDONAME + N' WHERE (PROCESS = N''' + @IDENTIFIER + N''' )';
            SET @attribute = N'PROCESS';
            SET @operand = N'=';
            SET @literalvalue = N'N''' + @IDENTIFIER + N'''';
        END
        ELSE IF @TABLEDONAME IN (N'TRANSACTION_HISTORY')
        BEGIN
            SET @FilterStatement = N'SELECT * FROM ' + @TABLEDONAME + N' WHERE (TRANSACTION_TYPE = N''' + @IDENTIFIER + N''')';
            SET @attribute = N'TRANSACTION_TYPE';
            SET @operand = N'=';
            SET @literalvalue = N'N''' + @IDENTIFIER + N'''';
        END

        /* INSERT NEW FILTERS AS DEFINED ABOVE */
        INSERT INTO FILTER_CONFIG_HEADER(RECORD_TYPE,DESCRIPTION,TABLE_DO_NAME,SYSTEM_CREATED,ALLOW_ORDER_BY,USER_DEF7,USER_DEF8,USER_STAMP,PROCESS_STAMP,DATE_TIME_STAMP,DO_PATH,JOIN_CLAUSE,ALLOW_MATCHES)  
        VALUES(@FilterArchiveID,@ARtableName,@TABLEDONAME,N'N',N'N',0,0,N'MANHATTAN_CLOUD',N'ArchivePurgeRunbook',GETUTCDATE(),@DOPATH,NULL,N'N'); 
		  
        INSERT INTO FILTER_CONFIG_DETAIL(RECORD_TYPE,FILTER_NAME,DESCRIPTION,FILTER_STATEMENT,SYSTEM_CREATED,ACTIVE,USER_DEF7,USER_DEF8,USER_STAMP,PROCESS_STAMP,DATE_TIME_STAMP)  
        VALUES(@FilterArchiveID,@FilterArchiveID,@ARtableName,@FilterStatement,N'N',N'Y',0,0,N'MANHATTAN_CLOUD',N'ArchivePurgeRunbook',GETUTCDATE());  
   
        INSERT INTO FILTER_STATEMENT(RECORD_TYPE,FILTER_NAME,SEQUENCE,ATTRIBUTE,OPERAND,LITERAL_VALUE,AND_OR,USER_DEF7,USER_DEF8,USER_STAMP,PROCESS_STAMP,DATE_TIME_STAMP,LEFT_PAREN,RIGHT_PAREN)  
        VALUES (@FilterArchiveID,@FilterArchiveID,@sequence,@attribute,@operand,@literalvalue,NULL,0,0,N'MANHATTAN_CLOUD',N'ArchivePurgeRunbook',GETUTCDATE(),0,0);

        /* UPDATE ARCHIVE PREFERENCE TO THE NEWLY CREATED FILTER */
        UPDATE ARCHIVE_PREFERENCES  
        SET DATA_FILTER = @FilterArchiveID 
        WHERE ARCHIVE_ID = @stArchiveID;    
    END 

    FETCH NEXT FROM cFilterCreate INTO @stArchiveID, @ARtableName, @TABLEDONAME, @DOPATH, @IDENTIFIER
 
END
 
CLOSE cFilterCreate
DEALLOCATE cFilterCreate

SET NOCOUNT OFF;
IF @DeleteLoopLimit > 0 /* DON'T DO ANY TRUNCATING OR PURGING LOGIC IF THE LOOP LIMIT IS SET TO 0 */
BEGIN
/* TRUNCATE DATA FROM AR_XX TABLES THAT SHOULD BE EMPTY BASED ON THE ARCHIVE_PREFERENCE.SAVE_DATA FLAG 
    THE LOGIC ABOVE ENSURES THAT ARCHIVE_PREFERENCE.SAVE DATA IS CORRECTLY SET BASED ON PROD VS NON-PROD AND BASED ON IF A CUSTOMIZED
    ARCHIVE PREFERENCE HAS BEEN SET AS WELL */
DECLARE cArchiveTruncate CURSOR FAST_FORWARD READ_ONLY FOR
SELECT APCHILD.TABLE_DO_NAME
FROM ARCHIVE_PREFERENCES APCHILD WITH(NOLOCK)
INNER JOIN ARCHIVE_PREFERENCES APPARENT WITH(NOLOCK)
ON APCHILD.USER_DEF1 = APPARENT.ARCHIVE_ID
WHERE APCHILD.USER_DEF1 IS NOT NULL 
    AND APPARENT.SAVE_DATA = N'N' 
    AND APPARENT.ACTIVE = N'Y'
    AND APPARENT.RUN_BY_DEFAULT = N'Y'
    AND APCHILD.TABLE_DO_NAME LIKE N'AR[_]%'
    AND EXISTS (SELECT N'%'
                FROM 
                    SYS.TABLES T
                INNER JOIN      
                    SYS.INDEXES I ON T.OBJECT_ID = I.OBJECT_ID
                INNER JOIN 
                    SYS.PARTITIONS P ON I.OBJECT_ID = P.OBJECT_ID AND I.INDEX_ID = P.INDEX_ID
                WHERE 
                    T.NAME NOT LIKE 'DT%' 
                    AND T.IS_MS_SHIPPED = 0
                    AND I.OBJECT_ID > 255
                    AND T.NAME = APCHILD.TABLE_DO_NAME COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS
                    AND P.ROWS > 0
                GROUP BY T.NAME, P.ROWS)
UNION ALL
SELECT TOP 1 CASE 
	WHEN NOT EXISTS (SELECT N'%' FROM ARCHIVE_PREFERENCES WITH(NOLOCK) WHERE ARCHIVE_NAME LIKE N'PROCESS[_]HISTORY[_]%' AND SAVE_DATA = N'Y') 
	THEN N'AR_PROCESS_HISTORY' 
	ELSE NULL END
FROM ARCHIVE_PREFERENCES AP WITH(NOLOCK)
WHERE ARCHIVE_NAME LIKE N'PROCESS[_]HISTORY[_]%'
    AND EXISTS (SELECT N'%'
                FROM 
                    SYS.TABLES T
                INNER JOIN      
                    SYS.INDEXES I ON T.OBJECT_ID = I.OBJECT_ID
                INNER JOIN 
                    SYS.PARTITIONS P ON I.OBJECT_ID = P.OBJECT_ID AND I.INDEX_ID = P.INDEX_ID
                WHERE 
                    T.NAME NOT LIKE 'DT%' 
                    AND T.IS_MS_SHIPPED = 0
                    AND I.OBJECT_ID > 255
                    AND T.NAME = N'AR_PROCESS_HISTORY' 
                    AND P.ROWS > 0
                GROUP BY T.NAME, P.ROWS)
UNION ALL
SELECT TOP 1 CASE 
	WHEN NOT EXISTS (SELECT N'%' FROM ARCHIVE_PREFERENCES WITH(NOLOCK) WHERE ARCHIVE_NAME LIKE N'TRANSACTION[_]HISTORY[_]%' AND SAVE_DATA = N'Y') 
	THEN N'AR_TRANSACTION_HISTORY' 
	ELSE NULL END
FROM ARCHIVE_PREFERENCES AP WITH(NOLOCK)
WHERE ARCHIVE_NAME LIKE N'TRANSACTION[_]HISTORY[_]%'
    AND EXISTS (SELECT N'%'
                FROM 
                    SYS.TABLES T
                INNER JOIN      
                    SYS.INDEXES I ON T.OBJECT_ID = I.OBJECT_ID
                INNER JOIN 
                    SYS.PARTITIONS P ON I.OBJECT_ID = P.OBJECT_ID AND I.INDEX_ID = P.INDEX_ID
                WHERE 
                    T.NAME NOT LIKE 'DT%' 
                    AND T.IS_MS_SHIPPED = 0
                    AND I.OBJECT_ID > 255
                    AND T.NAME = N'AR_TRANSACTION_HISTORY' 
                    AND P.ROWS > 0
                GROUP BY T.NAME, P.ROWS)
ORDER BY 1
 
OPEN cArchiveTruncate
FETCH NEXT FROM cArchiveTruncate INTO @tableName
 
WHILE @@FETCH_STATUS = 0 
BEGIN
    /* LOOP THROUGH ARCHIVE_TABLES MARKED AS SAFE TO TRUNCATE BECAUSE SAVE_DATA IS MARKED AS N AND THEN TRUNCATE THEM TO KEEP THE DATA CLEAN */
    IF (@tableName IS NOT NULL)
    BEGIN 
        SET @truncateSQL = 'TRUNCATE TABLE ' + QUOTENAME(@tableName);
        EXEC sp_executesql @truncateSQL;
    END

	FETCH NEXT FROM cArchiveTruncate INTO @tableName
END
 
CLOSE cArchiveTruncate
DEALLOCATE cArchiveTruncate

/* THIS CURSOR AND DELETE IS ESSENTIALLY DOING THE SAME AS WHAT BASE SHOULD BE DOING FOR THE AR_XX TABLES THAT WERE NOT TRUNCATED, 
    BUT THIS WILL HELP ON THE INITIAL CLEANOUT AND ALSO HELP TO MAINTAIN THE DBS IN CASE THE BASE ARCHIVING FAILS. 
    LOOPING THROUGH ALL ARCHIVE PREFERENCES FOR AR_XX TABLES MARKED AS SAVE_DATA = N THAT STILL HAVE DATA */
DECLARE cArchiveDelete CURSOR FAST_FORWARD READ_ONLY FOR
SELECT TABLE_DO_NAME, DAYS_HIST
FROM ARCHIVE_PREFERENCES AP WITH(NOLOCK)
WHERE ARCHIVE_NAME LIKE 'AR[_]%'
AND SAVE_DATA = N'N'
AND ACTIVE = N'Y'
AND RUN_BY_DEFAULT = N'Y'
AND EXISTS (SELECT N'%'
        FROM 
            SYS.TABLES T
        INNER JOIN      
            SYS.INDEXES I ON T.OBJECT_ID = I.OBJECT_ID
        INNER JOIN 
            SYS.PARTITIONS P ON I.OBJECT_ID = P.OBJECT_ID AND I.INDEX_ID = P.INDEX_ID
        WHERE 
            T.NAME NOT LIKE 'DT%' 
            AND T.IS_MS_SHIPPED = 0
            AND I.OBJECT_ID > 255
            AND T.NAME = AP.TABLE_DO_NAME COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS
            AND P.ROWS > 0
        GROUP BY T.NAME, P.ROWS)
ORDER BY TABLE_DO_NAME
 
OPEN cArchiveDelete
FETCH NEXT FROM cArchiveDelete INTO @tableName, @DaysHist
 
WHILE @@FETCH_STATUS = 0 
BEGIN
    /* LOOP THROUGH AR_XX TABLES DELETING ROWS THAT SHOULD NOT EXIST AND DELETE IN BATCHES TO OPTIMIZE PERFORMANCE */
    IF (@tableName IS NOT NULL AND @DaysHist > 0)
    BEGIN 
        SET @truncateSQL = N'IF EXISTS (SELECT TOP 1 N''%''
                                FROM ' + @tableName + ' 
                                WHERE DATE_TIME_STAMP <= CONVERT(DATE, GETUTCDATE()-' + CONVERT(NVARCHAR, @DaysHist) + N')) 
                            BEGIN

                                DECLARE @Counter NUMERIC(5, 0) = 1;

                                WHILE (@Counter <= ' + CONVERT(NVARCHAR, @DeleteLoopLimit) + N') 
                                BEGIN
	                                ;WITH CTE AS
                                    (
                                    SELECT TOP ' + CONVERT(NVARCHAR, @DeleteBatchSize) + N' *
                                    FROM ' + @tableName + ' 
                                    WHERE DATE_TIME_STAMP <= CONVERT(DATE, GETUTCDATE()-' + CONVERT(NVARCHAR, @DaysHist) + N') 
                                    ORDER BY DATE_TIME_STAMP
                                    )
                                    DELETE FROM CTE   
    
                                    SET @Counter = @Counter + 1;
                                END
                            END'
        EXEC sp_executesql @truncateSQL;
    END

	FETCH NEXT FROM cArchiveDelete INTO @tableName, @DaysHist
END

CLOSE cArchiveDelete
DEALLOCATE cArchiveDelete

/* DELETE FROM AR_PROCESS_HISTORY ROWS THAT EXIST FOR HISTORY TYPES MARKED AS SAVE_DATA = N */
DECLARE cHistDelete CURSOR FAST_FORWARD READ_ONLY FOR
SELECT TABLE_DO_NAME, RIGHT(ARCHIVE_NAME, LEN(ARCHIVE_NAME) - CHARINDEX(N'_', ARCHIVE_NAME, 14)) AS TYPE
FROM ARCHIVE_PREFERENCES WITH(NOLOCK)
WHERE ARCHIVE_NAME LIKE N'PROCESS[_]HISTORY[_]%'
    AND SAVE_DATA = N'N'
    AND ACTIVE = N'Y'
    AND RUN_BY_DEFAULT = N'Y'
    AND EXISTS (SELECT TOP 1 '%' FROM AR_PROCESS_HISTORY WHERE PROCESS = RIGHT(ARCHIVE_NAME, LEN(ARCHIVE_NAME) - CHARINDEX(N'_', ARCHIVE_NAME, 14)))
ORDER BY 1, 2
 
OPEN cHistDelete
FETCH NEXT FROM cHistDelete INTO @tableName, @HistType
 
WHILE @@FETCH_STATUS = 0 
BEGIN
    /* LOOP THROUGH AR_PROCESS_HISTORY DELETING ROWS FOR TYPES THAT SHOULD NOT EXIST AND DELETE IN BATCHES TO OPTIMIZE PERFORMANCE */
    IF (@tableName IS NOT NULL AND @HistType IS NOT NULL)
    BEGIN 
        SET @truncateSQL = N'DECLARE @Counter NUMERIC(5, 0) = 1;

                                WHILE (@Counter <= ' + CONVERT(NVARCHAR, @DeleteLoopLimit) + N') 
                                BEGIN
	                                ;WITH CTE AS
                                    (
                                    SELECT TOP ' + CONVERT(NVARCHAR, @DeleteBatchSize) + N' *
                                    FROM AR_' + @tableName + ' 
                                    WHERE PROCESS = N''' + @HistType + N'''
                                    )
                                    DELETE FROM CTE   
    
                                    SET @Counter = @Counter + 1;
                                END'
        EXEC sp_executesql @truncateSQL;
    END

	FETCH NEXT FROM cHistDelete INTO @tableName, @HistType
END
 
CLOSE cHistDelete
DEALLOCATE cHistDelete

/* DELETE FROM AR_TRANSACTION_HISTORY ROWS THAT EXIST FOR HISTORY TYPES MARKED AS SAVE_DATA = N */
DECLARE cHistDelete CURSOR FAST_FORWARD READ_ONLY FOR
SELECT TABLE_DO_NAME, RIGHT(ARCHIVE_NAME, LEN(ARCHIVE_NAME) - CHARINDEX(N'_', ARCHIVE_NAME, 14)) AS TYPE
FROM ARCHIVE_PREFERENCES WITH(NOLOCK)
WHERE ARCHIVE_NAME LIKE N'TRANSACTION[_]HISTORY[_]%'
    AND SAVE_DATA = N'N'
    AND ACTIVE = N'Y'
    AND RUN_BY_DEFAULT = N'Y'
    AND EXISTS (SELECT TOP 1 '%' FROM AR_TRANSACTION_HISTORY WHERE TRANSACTION_TYPE = RIGHT(ARCHIVE_NAME, LEN(ARCHIVE_NAME) - CHARINDEX(N'_', ARCHIVE_NAME, 14)))
ORDER BY 1, 2
 
OPEN cHistDelete
FETCH NEXT FROM cHistDelete INTO @tableName, @HistType
 
WHILE @@FETCH_STATUS = 0 
BEGIN
    /* LOOP THROUGH AR_TRANSACTION_HISTORY DELETING ROWS FOR TYPES THAT SHOULD NOT EXIST AND DELETE IN BATCHES TO OPTIMIZE PERFORMANCE */
    IF (@tableName IS NOT NULL AND @HistType IS NOT NULL)
    BEGIN 
        SET @truncateSQL = N'DECLARE @Counter NUMERIC(5, 0) = 1;

                                WHILE (@Counter <= ' + CONVERT(NVARCHAR, @DeleteLoopLimit) + N') 
                                BEGIN
	                                ;WITH CTE AS
                                    (
                                    SELECT TOP ' + CONVERT(NVARCHAR, @DeleteBatchSize) + N' *
                                    FROM AR_' + @tableName + ' 
                                    WHERE TRANSACTION_TYPE = N''' + @HistType + N'''
                                    )
                                    DELETE FROM CTE   
    
                                    SET @Counter = @Counter + 1;
                                END'
        EXEC sp_executesql @truncateSQL;
    END

	FETCH NEXT FROM cHistDelete INTO @tableName, @HistType
END
 
CLOSE cHistDelete
DEALLOCATE cHistDelete
END /* END IF @DeleteLoopLimit > 0 */

/* TURN BASE DATA ARCHIVING SCHEDULED_JOBS RECORD ON IF NO JOB OF TYPE ARCHIVE DATA IS ACTIVE */  
IF (SELECT @@SERVERNAME) IN (SELECT DB_SERVER FROM @NonProdServerList)
/* STAGE */  
BEGIN  
UPDATE SCHEDULED_JOBS  
SET ACTIVE = N'Y',  
    NEXT_RUN_DATE_TIME = CASE   
    WHEN NEXT_RUN_DATE_TIME IS NULL THEN CONVERT(DATE, GETUTCDATE()+1)  
    WHEN NEXT_RUN_DATE_TIME > CONVERT(DATE, GETUTCDATE()+1) THEN CONVERT(DATE, GETUTCDATE()+1)   
    ELSE NEXT_RUN_DATE_TIME END,
    PARAMETER_DATA = NULL,
    DAYS_TO_RUN = N'1111111',  
    USER_STAMP = N'MANHATTAN_CLOUD',
    PROCESS_STAMP = N'ArchivePurgeRunbook',
    DATE_TIME_STAMP = GETUTCDATE()  
WHERE JOB_NAME = N'Data Archiving';  
END  
/* PROD */  
ELSE  
BEGIN  
UPDATE SCHEDULED_JOBS  
SET ACTIVE = N'Y',  
    NEXT_RUN_DATE_TIME = CONVERT(DATE, DATEADD(DAY, 1, GETUTCDATE() - DATEPART(DW, GETUTCDATE())  
        + CASE WHEN DATEPART(DW, GETUTCDATE()) < 1 THEN 0 ELSE 7 END )),
    PARAMETER_DATA = NULL,
    USER_STAMP = N'MANHATTAN_CLOUD',
    PROCESS_STAMP = N'ArchivePurgeRunbook',
    DATE_TIME_STAMP = GETUTCDATE()  
WHERE JOB_NAME = N'Data Archiving'   
    AND NOT EXISTS (SELECT N'%'  
    FROM SCHEDULED_JOBS WITH(NOLOCK)  
        WHERE RECORD_TYPE = N'Archive Data'  
        AND ACTIVE = N'Y'  
        AND PARAMETER_DATA IS NULL);  
END  
  
/* PREVENT SCHEDULED JOBS FROM RUNNING LESS THAN EVERY 5 MINUTES */  
UPDATE SCHEDULED_JOBS  
SET NEXT_RUN_DATE_TIME = DATEADD(MINUTE, 5, NEXT_RUN_DATE_TIME),  
    MINUTES_FREQUENCY = CASE WHEN MINUTES_FREQUENCY < 5 THEN 5 ELSE MINUTES_FREQUENCY END,  
    USER_STAMP = N'MANHATTAN_CLOUD',
    PROCESS_STAMP = N'ArchivePurgeRunbook',
    DATE_TIME_STAMP = GETUTCDATE() 
WHERE ACTIVE = N'Y'  
    AND SPECIFIC_TIME IS NULL  
    AND NEXT_RUN_DATE_TIME IS NOT NULL  
    AND MINUTES_FREQUENCY < 5 
    AND ISNULL(USER_DEF6, N'!') <> N'HOLD';  
  
END
/* END PROCEDURE */