
/*
	Mod Number	| Programmer	| Date   	| Modification Description
	--------------------------------------------------------------------
	191074		| DN		| 01/23/17	| Updated parameter types

*/
CREATE PROCEDURE wm_RUShipmentHeader01
	@TrailingSts numeric(3),
	@BatchId nvarchar(50)
AS

	DECLARE @TEMPTABLE TABLE(INTERNAL_SHIPMENT_NUM NUMERIC(9,0));

	INSERT INTO @TEMPTABLE 
		SELECT SH.INTERNAL_SHIPMENT_NUM 
		FROM SHIPMENT_HEADER SH WITH (NOLOCK) INNER JOIN SHIPPING_LOAD SL ON
		SH.SHIPPING_LOAD_NUM = SL.INTERNAL_LOAD_NUM
		WHERE SH.TRAILING_STS >= @TrailingSts
		AND SH.TRAILING_STS < 997
		AND SH.UPLOAD_INTERFACE_BATCH IS NULL
		AND SL.IN_CONFIRMATION != N'Y';

	UPDATE SHIPMENT_HEADER
	SET UPLOAD_INTERFACE_BATCH = @BatchId
	WHERE INTERNAL_SHIPMENT_NUM  IN 
		(SELECT INTERNAL_SHIPMENT_NUM  FROM @TEMPTABLE);

	SELECT *
	FROM SHIPMENT_HEADER
	WHERE UPLOAD_INTERFACE_BATCH = @BatchId;
