/*
	Task	| By	| Date		| Modification Description
	--------------------------------------------------------------------
	134942	| DN   | 01/04/13	| Removed check for interface condition
	133750  |KSS   |01/10/13    | As per DINT requirement
	137225	|JY	   |02/28/14	| Added update for all other upload tables while doing the interfacing.
*/

CREATE PROCEDURE wm_RUUploadOrderHeader01
	@BatchId nvarchar(100),
	@InterfaceDtlKey numeric(9),
	@InterfaceConst nvarchar(25)
AS
	
	IF @InterfaceConst = N'In Process'
		BEGIN

			UPDATE UPLOAD_ORDER_HEADER
			SET PROCESS_STAMP = @BatchId,
			INTERFACE_CONDITION = @InterfaceConst
			Where INTERFACE_CONDITION !=N'Processed'
			AND INTERFACE_DETAIL_KEY_NUM = @InterfaceDtlKey

			UPDATE UPLOAD_ORDER_DETAIL
			SET PROCESS_STAMP = @BatchId,
			INTERFACE_CONDITION = @InterfaceConst
			Where INTERFACE_CONDITION !=N'Processed'
			AND INTERFACE_LINK_ID IN ( Select INTERFACE_RECORD_ID from UPLOAD_ORDER_HEADER where PROCESS_STAMP = @BatchId)

			UPDATE UPLOAD_ORDER_COMMENT
			SET PROCESS_STAMP = @BatchId,
			INTERFACE_CONDITION = @InterfaceConst
			Where INTERFACE_CONDITION !=N'Processed'
			AND (INTERFACE_LINK_ID IN ( Select INTERFACE_RECORD_ID from UPLOAD_ORDER_HEADER where PROCESS_STAMP = @BatchId) 
			OR INTERFACE_LINK_ID IN ( Select INTERFACE_RECORD_ID from UPLOAD_ORDER_DETAIL where PROCESS_STAMP = @BatchId))

			UPDATE UPLOAD_ORDER_CONTAINER
			SET PROCESS_STAMP = @BatchId,
			INTERFACE_CONDITION = @InterfaceConst
			Where INTERFACE_CONDITION !=N'Processed'
			AND INTERFACE_LINK_ID IN ( Select INTERFACE_RECORD_ID from UPLOAD_ORDER_HEADER where PROCESS_STAMP = @BatchId)
	
			UPDATE UPLOAD_SERIAL_NUMBER
			SET PROCESS_STAMP = @BatchId,
			INTERFACE_CONDITION = @InterfaceConst
			Where INTERFACE_CONDITION !=N'Processed'
			AND INTERFACE_LINK_ID IN ( Select INTERFACE_RECORD_ID from UPLOAD_ORDER_CONTAINER where PROCESS_STAMP = @BatchId)

			UPDATE UPLOAD_LOCATION_INVENTORY_ATTRIBUTES
			SET PROCESS_STAMP = @BatchId,
			INTERFACE_CONDITION = @InterfaceConst
			Where INTERFACE_CONDITION !=N'Processed'
			AND INTERFACE_LINK_ID IN ( Select INTERFACE_RECORD_ID from UPLOAD_ORDER_CONTAINER where PROCESS_STAMP = @BatchId)

			SELECT TOP 1 *
			FROM UPLOAD_ORDER_HEADER
			WHERE PROCESS_STAMP = @BatchId
		END
	ELSE 
	BEGIN
			UPDATE UPLOAD_ORDER_HEADER
			SET INTERFACE_CONDITION =@InterfaceConst
			Where INTERFACE_CONDITION = N'In Process'
			AND PROCESS_STAMP = @BatchId
			AND INTERFACE_DETAIL_KEY_NUM = @InterfaceDtlKey

			UPDATE UPLOAD_ORDER_DETAIL
			SET PROCESS_STAMP = @BatchId,
			INTERFACE_CONDITION =@InterfaceConst
			Where INTERFACE_CONDITION =N'In Process'
			AND INTERFACE_LINK_ID IN ( Select INTERFACE_RECORD_ID from UPLOAD_ORDER_HEADER where PROCESS_STAMP = @BatchId)

			UPDATE UPLOAD_ORDER_COMMENT
			SET PROCESS_STAMP = @BatchId,
			INTERFACE_CONDITION =@InterfaceConst
			Where INTERFACE_CONDITION =N'In Process'
			AND (INTERFACE_LINK_ID IN ( Select INTERFACE_RECORD_ID from UPLOAD_ORDER_HEADER where PROCESS_STAMP = @BatchId) 
			OR INTERFACE_LINK_ID IN ( Select INTERFACE_RECORD_ID from UPLOAD_ORDER_DETAIL where PROCESS_STAMP = @BatchId))

			UPDATE UPLOAD_ORDER_CONTAINER
			SET PROCESS_STAMP = @BatchId,
			INTERFACE_CONDITION =@InterfaceConst
			Where INTERFACE_CONDITION =N'In Process'
			AND INTERFACE_LINK_ID IN ( Select INTERFACE_RECORD_ID from UPLOAD_ORDER_HEADER where PROCESS_STAMP = @BatchId)
	
			UPDATE UPLOAD_SERIAL_NUMBER
			SET PROCESS_STAMP = @BatchId,
			INTERFACE_CONDITION =@InterfaceConst
			Where INTERFACE_CONDITION =N'In Process'
			AND INTERFACE_LINK_ID IN ( Select INTERFACE_RECORD_ID from UPLOAD_ORDER_CONTAINER where PROCESS_STAMP = @BatchId)

			UPDATE UPLOAD_LOCATION_INVENTORY_ATTRIBUTES
			SET PROCESS_STAMP = @BatchId,
			INTERFACE_CONDITION =@InterfaceConst
			Where INTERFACE_CONDITION =N'In Process'
			AND INTERFACE_LINK_ID IN ( Select INTERFACE_RECORD_ID from UPLOAD_ORDER_CONTAINER where PROCESS_STAMP = @BatchId)

			SELECT *
			FROM UPLOAD_ORDER_HEADER
			WHERE PROCESS_STAMP = @BatchId
	END
