-- =============================================
-- Author:		Jimmy
-- Create date: 09/24/2008
-- Description:	Chart for current work/pool by building
-- =============================================
CREATE PROCEDURE PM_UNSHIPPED_BY_BUILDING_PRIORITY 

AS

BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    -- Insert statements for procedure here

	DECLARE @sql nvarchar(max);


SET @sql = '
SELECT 
''225-Pri. Grp. 1'' AS DESTINATION,
SUM(CASE WHEN 
SD.ITEM_CATEGORY1 IN (''Marine Corps'', ''Navy'') 
AND SH.PRIORITY < 4 
AND SH.TRAILING_STS < 202 THEN 1 ELSE 0 END) AS InPool,
SUM(CASE WHEN 
SD.ITEM_CATEGORY1 IN (''Marine Corps'', ''Navy'') 
AND SH.PRIORITY < 4 
AND TRAILING_STS > 202 AND TRAILING_STS < 700 THEN 1 ELSE 0 END) AS Working
FROM SHIPMENT_HEADER as SH LEFT OUTER JOIN SHIPMENT_DETAIL AS SD ON SD.INTERNAL_SHIPMENT_NUM = SH.INTERNAL_SHIPMENT_NUM 

UNION 

SELECT 
''225-Pri. Grp. 2'' AS DESTINATION,
SUM(CASE WHEN 
SD.ITEM_CATEGORY1 IN (''Marine Corps'', ''Navy'') 
AND SH.PRIORITY >= 4 AND SH.PRIORITY <= 8 
AND SH.TRAILING_STS < 202 THEN 1 ELSE 0 END) AS InPool,
SUM(CASE WHEN 
SD.ITEM_CATEGORY1 IN (''Marine Corps'', ''Navy'') 
AND SH.PRIORITY >= 4 AND SH.PRIORITY <= 8 
AND TRAILING_STS > 202 AND TRAILING_STS < 700 THEN 1 ELSE 0 END) AS Working
FROM SHIPMENT_HEADER as SH LEFT OUTER JOIN SHIPMENT_DETAIL AS SD ON SD.INTERNAL_SHIPMENT_NUM = SH.INTERNAL_SHIPMENT_NUM 

UNION 

SELECT 
''225-Pri. Grp. 3'' AS DESTINATION,
SUM(CASE WHEN 
SD.ITEM_CATEGORY1 IN (''Marine Corps'', ''Navy'') 
AND SH.PRIORITY > 8 
AND SH.TRAILING_STS < 202 THEN 1 ELSE 0 END) AS InPool,
SUM(CASE WHEN 
SD.ITEM_CATEGORY1 IN (''Marine Corps'', ''Navy'') 
AND SH.PRIORITY > 8 
AND TRAILING_STS > 202 AND TRAILING_STS < 700 THEN 1 ELSE 0 END) AS Working
FROM SHIPMENT_HEADER as SH LEFT OUTER JOIN SHIPMENT_DETAIL AS SD ON SD.INTERNAL_SHIPMENT_NUM = SH.INTERNAL_SHIPMENT_NUM 

UNION 

SELECT 
''402-Pri. Grp. 1'' AS DESTINATION,
SUM(CASE WHEN 
SD.ITEM_CATEGORY1 IN (''Air Force'', ''Coast Guard'', ''Army'') 
AND SH.PRIORITY < 4 
AND SH.TRAILING_STS < 202 THEN 1 ELSE 0 END) AS InPool,
SUM(CASE WHEN 
SD.ITEM_CATEGORY1 IN (''Air Force'', ''Coast Guard'', ''Army'') 
AND SH.PRIORITY < 4 
AND TRAILING_STS > 202 AND TRAILING_STS < 700 THEN 1 ELSE 0 END) AS Working
FROM SHIPMENT_HEADER as SH LEFT OUTER JOIN SHIPMENT_DETAIL AS SD ON SD.INTERNAL_SHIPMENT_NUM = SH.INTERNAL_SHIPMENT_NUM 

UNION 

SELECT 
''402-Pri. Grp. 2'' AS DESTINATION,
SUM(CASE WHEN 
SD.ITEM_CATEGORY1 IN (''Air Force'', ''Coast Guard'', ''Army'') 
AND SH.PRIORITY >= 4 AND SH.PRIORITY <= 8 
AND SH.TRAILING_STS < 202 THEN 1 ELSE 0 END) AS InPool,
SUM(CASE WHEN 
SD.ITEM_CATEGORY1 IN (''Air Force'', ''Coast Guard'', ''Army'') 
AND SH.PRIORITY >= 4 AND SH.PRIORITY <= 8 
AND TRAILING_STS > 202 AND TRAILING_STS < 700 THEN 1 ELSE 0 END) AS Working
FROM SHIPMENT_HEADER as SH LEFT OUTER JOIN SHIPMENT_DETAIL AS SD ON SD.INTERNAL_SHIPMENT_NUM = SH.INTERNAL_SHIPMENT_NUM 

UNION 

SELECT 
''402-Pri. Grp. 3'' AS DESTINATION,
SUM(CASE WHEN 
SD.ITEM_CATEGORY1 IN (''Air Force'', ''Coast Guard'', ''Army'') 
AND SH.PRIORITY > 8 
AND SH.TRAILING_STS < 202 THEN 1 ELSE 0 END) AS InPool,
SUM(CASE WHEN 
SD.ITEM_CATEGORY1 IN (''Air Force'', ''Coast Guard'', ''Army'') 
AND SH.PRIORITY > 8 
AND TRAILING_STS > 202 AND TRAILING_STS < 700 THEN 1 ELSE 0 END) AS Working
FROM SHIPMENT_HEADER as SH LEFT OUTER JOIN SHIPMENT_DETAIL AS SD ON SD.INTERNAL_SHIPMENT_NUM = SH.INTERNAL_SHIPMENT_NUM 


'

exec dbo.sp_executesql @sql

END