/*
	  51519	   | MDL | 01/20/10  | Reset erroneous records to NULL.  
	 191074	   | DN	 | 01/23/17	 | Updated parameter types
*/

CREATE PROCEDURE wm_UDownloadOrderHeader03
	@RowsAffected int OUTPUT,
	@ProcessStamp nvarchar(100)
AS
	UPDATE DOWNLOAD_ORDER_CONTAINER
	SET INTERFACE_CONDITION = NULL
	WHERE PROCESS_STAMP = @ProcessStamp
	AND INTERFACE_CONDITION = N'Error';

	SET @RowsAffected = @@ROWCOUNT

	UPDATE DOWNLOAD_ORDER_COMMENT
	SET INTERFACE_CONDITION = NULL
	WHERE PROCESS_STAMP = @ProcessStamp
	AND INTERFACE_CONDITION = N'Error';

	SET @RowsAffected = @RowsAffected + @@ROWCOUNT

    UPDATE DOWNLOAD_ORDER_VAS_ACTIVITY
	SET INTERFACE_CONDITION = NULL
	WHERE PROCESS_STAMP = @ProcessStamp
	AND INTERFACE_CONDITION = N'Error';

	SET @RowsAffected = @RowsAffected + @@ROWCOUNT
    
	UPDATE DOWNLOAD_ORDER_DETAIL
	SET INTERFACE_CONDITION = NULL
	WHERE PROCESS_STAMP = @ProcessStamp
	AND INTERFACE_CONDITION = N'Error';

	SET @RowsAffected = @RowsAffected + @@ROWCOUNT

	UPDATE DOWNLOAD_ORDER_HEADER
	SET INTERFACE_CONDITION = NULL
	WHERE PROCESS_STAMP = @ProcessStamp
	AND INTERFACE_CONDITION = N'Error';

	SET @RowsAffected = @RowsAffected + @@ROWCOUNT
