/*
	Mod Number	| Programmer		| Date   	| Modification Description
	--------------------------------------------------------------------
	15114		| BTD			    | 1/16/06	| Modified numeric field sizes
	219934		| NRJ				| 04/13/18	| MOdified such that Order_Date will be updated to its original value when passes as null.
*/



CREATE PROCEDURE wm_UOrderHeader01
	@RowsAffected int OUTPUT,
	@InternalOrderNum numeric(9),
	@Warehouse nvarchar(25),
	@ErpOrder nvarchar(25),
	@Condition nvarchar(25),
	@OrderType nvarchar(25),
	@TotalShipments numeric(9),
	@ContainersShipped numeric(9),
	@WeightShipped numeric(19,5),
	@WeightUm nvarchar(25),
	@VolumeShipped numeric(19,5),
	@VolumeUm nvarchar(25),
	@ValueShipped numeric(19,5),
	@PartOfConsolidation nchar(1),
	@Company nvarchar(25),
	@UserDef1 nvarchar(25),
	@UserDef2 nvarchar(25),
	@UserDef3 nvarchar(25),
	@UserDef4 nvarchar(25),
	@UserDef5 nvarchar(25),
	@UserDef6 nvarchar(25),
	@UserDef7 numeric(19,5),
	@UserDef8 numeric(19,5),
	@UserStamp nvarchar(30),
	@ProcessStamp nvarchar(100),
	@DateTimeStamp datetime,
	@ConditionDateTime datetime,
	@Customer nvarchar(25),
	@CustomerName nvarchar(50),
	@CustomerAddress1 nvarchar(50),
	@CustomerAddress2 nvarchar(50),
	@CustomerAddress3 nvarchar(50),
	@CustomerAttentionTo nvarchar(50),
	@CustomerCity nvarchar(30),
	@CustomerState nvarchar(25),
	@CustomerCountry nvarchar(25),
	@CustomerPostalCode nvarchar(25),
	@CustomerPhoneNum nvarchar(50),
	@CustomerFaxNum nvarchar(50),
	@CustomerEmailAddress nvarchar(50),
	@ShipTo nvarchar(25),
	@ShipToName nvarchar(50),
	@ShipToAddress1 nvarchar(50),
	@ShipToAddress2 nvarchar(50),
	@ShipToAddress3 nvarchar(50),
	@ShipToAttentionTo nvarchar(50),
	@ShipToCity nvarchar(30),
	@ShipToState nvarchar(25),
	@ShipToCountry nvarchar(25),
	@ShipToPostalCode nvarchar(25),
	@ShipToPhoneNum nvarchar(50),
	@ShipToFaxNum nvarchar(50),
	@ShipToEmailAddress nvarchar(50),
	@CustomerPo nvarchar(25),
	@OrderDate datetime,
	@RequestedDeliveryDate datetime,
	@RequestedDeliveryType nvarchar(10),
	@IntermediateConsignee nvarchar(25),
	@IntermediateName nvarchar(50),
	@IntermediateAddress1 nvarchar(50),
	@IntermediateAddress2 nvarchar(50),
	@IntermediateAddress3 nvarchar(50),
	@IntermediateAttentionTo nvarchar(50),
	@IntermediateCity nvarchar(30),
	@IntermediateState nvarchar(25),
	@IntermediateCountry nvarchar(25),
	@IntermediatePostalCode nvarchar(25),
	@IntermediatePhoneNum nvarchar(50),
	@IntermediateFaxNum nvarchar(50),
	@IntermediateEmailAddress nvarchar(50),
	@FreightBillTo nvarchar(25),
	@FreightBillToName nvarchar(50),
	@FreightBillToAddress1 nvarchar(50),
	@FreightBillToAddress2 nvarchar(50),
	@FreightBillToAddress3 nvarchar(50),
	@FreightBillToAttentionTo nvarchar(50),
	@FreightBillToCity nvarchar(30),
	@FreightBillToState nvarchar(25),
	@FreightBillToCountry nvarchar(25),
	@FreightBillToPostalCode nvarchar(25),
	@FreightBillToPhoneNum nvarchar(50),
	@FreightBillToFaxNum nvarchar(50),
	@FreightBillToEmailAddress nvarchar(50),
	@Priority numeric(3),
	@ConsolidationAllowed nchar(1),
	@Carrier nvarchar(25),
	@CarrierService nvarchar(50),
	@CarrierGroup nvarchar(25),
	@CarrierType nvarchar(25),
	@PlannedShipDate datetime,
	@PlannedDeliveryDate datetime,
	@FreightTerms nvarchar(50),
	@LiabilityTerms nvarchar(25),
	@Route nvarchar(25),
	@Stop nvarchar(25),
	@RoutingCode nvarchar(25),
	@SingleItemCartons nvarchar(25),
	@CustomerResidentialFlag nchar(1),
	@ShiptoResidentialFlag nchar(1),
	@InterfaceRecordId nvarchar(25),
	@CustomerCategory1 nvarchar(50),
	@CustomerCategory2 nvarchar(50),
	@CustomerCategory3 nvarchar(50),
	@CustomerCategory4 nvarchar(50),
	@CustomerCategory5 nvarchar(50),
	@CustomerCategory6 nvarchar(50),
	@CustomerCategory7 nvarchar(50),
	@CustomerCategory8 nvarchar(50),
	@CustomerCategory9 nvarchar(50),
	@CustomerCategory10 nvarchar(50),
	@ProcessType nvarchar(25),
	@CreationProcessStamp nvarchar(100),
	@CreationDateTimeStamp datetime,
	@AlternateEmailAddress nvarchar(50)
AS
	
	if @OrderDate IS NULL
	BEGIN
		 SELECT @OrderDate = ORDER_DATE FROM ORDER_HEADER WHERE INTERNAL_ORDER_NUM=@InternalOrderNum;
	END

	UPDATE ORDER_HEADER
	   SET
		warehouse=@Warehouse,
		ERP_ORDER=@ErpOrder,
		CONDITION=@Condition,
		ORDER_TYPE=@OrderType,
		TOTAL_SHIPMENTS=@TotalShipments,
		CONTAINERS_SHIPPED=@ContainersShipped,
		WEIGHT_SHIPPED=@WeightShipped,
		WEIGHT_UM=@WeightUm,
		VOLUME_SHIPPED=@VolumeShipped,
		VOLUME_UM=@VolumeUm,
		VALUE_SHIPPED=@ValueShipped,
		PART_OF_CONSOLIDATION=@PartOfConsolidation,
		COMPANY=@Company,
		USER_DEF1=@UserDef1,
		USER_DEF2=@UserDef2,
		USER_DEF3=@UserDef3,
		USER_DEF4=@UserDef4,
		USER_DEF5=@UserDef5,
		USER_DEF6=@UserDef6,
		USER_DEF7=@UserDef7,
		USER_DEF8=@UserDef8,
		USER_STAMP=@UserStamp,
		PROCESS_STAMP=@ProcessStamp,
		DATE_TIME_STAMP=@DateTimeStamp,
		CONDITION_DATE_TIME=@ConditionDateTime,
		CUSTOMER=@Customer,
		CUSTOMER_NAME=@CustomerName,
		CUSTOMER_ADDRESS1=@CustomerAddress1,
		CUSTOMER_ADDRESS2=@CustomerAddress2,
		CUSTOMER_ADDRESS3=@CustomerAddress3,
		CUSTOMER_ATTENTION_TO=@CustomerAttentionTo,
		CUSTOMER_CITY=@CustomerCity,
		CUSTOMER_STATE=@CustomerState,
		CUSTOMER_COUNTRY=@CustomerCountry,
		CUSTOMER_POSTAL_CODE=@CustomerPostalCode,
		CUSTOMER_PHONE_NUM=@CustomerPhoneNum,
		CUSTOMER_FAX_NUM=@CustomerFaxNum,
		CUSTOMER_EMAIL_ADDRESS=@CustomerEmailAddress,
		SHIP_TO=@ShipTo,
		SHIP_TO_NAME=@ShipToName,
		SHIP_TO_ADDRESS1=@ShipToAddress1,
		SHIP_TO_ADDRESS2=@ShipToAddress2,
		SHIP_TO_ADDRESS3=@ShipToAddress3,
		SHIP_TO_ATTENTION_TO=@ShipToAttentionTo,
		SHIP_TO_CITY=@ShipToCity,
		SHIP_TO_STATE=@ShipToState,
		SHIP_TO_COUNTRY=@ShipToCountry,
		SHIP_TO_POSTAL_CODE=@ShipToPostalCode,
		SHIP_TO_PHONE_NUM=@ShipToPhoneNum,
		SHIP_TO_FAX_NUM=@ShipToFaxNum,
		SHIP_TO_EMAIL_ADDRESS=@ShipToEmailAddress,
		CUSTOMER_PO=@CustomerPo,
		ORDER_DATE=@OrderDate,
		REQUESTED_DELIVERY_DATE=@RequestedDeliveryDate,
		REQUESTED_DELIVERY_TYPE=@RequestedDeliveryType,
		INTERMEDIATE_CONSIGNEE=@IntermediateConsignee,
		INTERMEDIATE_NAME=@IntermediateName,
		INTERMEDIATE_ADDRESS1=@IntermediateAddress1,
		INTERMEDIATE_ADDRESS2=@IntermediateAddress2,
		INTERMEDIATE_ADDRESS3=@IntermediateAddress3,
		INTERMEDIATE_ATTENTION_TO=@IntermediateAttentionTo,
		INTERMEDIATE_CITY=@IntermediateCity,
		INTERMEDIATE_STATE=@IntermediateState,
		INTERMEDIATE_COUNTRY=@IntermediateCountry,
		INTERMEDIATE_POSTAL_CODE=@IntermediatePostalCode,
		INTERMEDIATE_PHONE_NUM=@IntermediatePhoneNum,
		INTERMEDIATE_FAX_NUM=@IntermediateFaxNum,
		INTERMEDIATE_EMAIL_ADDRESS=@IntermediateEmailAddress,
		FREIGHT_BILL_TO=@FreightBillTo,
		FREIGHT_BILL_TO_NAME=@FreightBillToName,
		FREIGHT_BILL_TO_ADDRESS1=@FreightBillToAddress1,
		FREIGHT_BILL_TO_ADDRESS2=@FreightBillToAddress2,
		FREIGHT_BILL_TO_ADDRESS3=@FreightBillToAddress3,
		FREIGHT_BILL_TO_ATTENTION_TO=@FreightBillToAttentionTo,
		FREIGHT_BILL_TO_CITY=@FreightBillToCity,
		FREIGHT_BILL_TO_STATE=@FreightBillToState,
		FREIGHT_BILL_TO_COUNTRY=@FreightBillToCountry,
		FREIGHT_BILL_TO_POSTAL_CODE=@FreightBillToPostalCode,
		FREIGHT_BILL_TO_PHONE_NUM=@FreightBillToPhoneNum,
		FREIGHT_BILL_TO_FAX_NUM=@FreightBillToFaxNum,
		FREIGHT_BILL_TO_EMAIL_ADDRESS=@FreightBillToEmailAddress,
		PRIORITY=@Priority,
		CONSOLIDATION_ALLOWED=@ConsolidationAllowed,
		CARRIER=@Carrier,
		CARRIER_SERVICE=@CarrierService,
		CARRIER_GROUP=@CarrierGroup,
		CARRIER_TYPE=@CarrierType,
		PLANNED_SHIP_DATE=@PlannedShipDate,
		PLANNED_DELIVERY_DATE=@PlannedDeliveryDate,
		FREIGHT_TERMS=@FreightTerms,
		LIABILITY_TERMS=@LiabilityTerms,
		ROUTE=@Route,
		STOP=@Stop,
		ROUTING_CODE=@RoutingCode,
		SINGLE_ITEM_CARTONS=@SingleItemCartons,
		CUSTOMER_RESIDENTIAL_FLAG=@CustomerResidentialFlag,
		SHIPTO_RESIDENTIAL_FLAG=@ShiptoResidentialFlag,
		INTERFACE_RECORD_ID=@InterfaceRecordId,
		CUSTOMER_CATEGORY1=@CustomerCategory1,
		CUSTOMER_CATEGORY2=@CustomerCategory2,
		CUSTOMER_CATEGORY3=@CustomerCategory3,
		CUSTOMER_CATEGORY4=@CustomerCategory4,
		CUSTOMER_CATEGORY5=@CustomerCategory5,
		CUSTOMER_CATEGORY6=@CustomerCategory6,
		CUSTOMER_CATEGORY7=@CustomerCategory7,
		CUSTOMER_CATEGORY8=@CustomerCategory8,
		CUSTOMER_CATEGORY9=@CustomerCategory9,
		CUSTOMER_CATEGORY10=@CustomerCategory10,
		PROCESS_TYPE=@ProcessType,
		CREATION_PROCESS_STAMP=@CreationProcessStamp,
		CREATION_DATE_TIME_STAMP=@CreationDateTimeStamp,
		ALTERNATE_EMAIL_ADDRESS=@AlternateEmailAddress
	 WHERE INTERNAL_ORDER_NUM = @InternalOrderNum

	SET @RowsAffected = @@ROWCOUNT


