/*
	Task	| By	| Date		| Modification Description
	--------------------------------------------------------------------
	17142	| SA	| 12/19/05	| Created
	18633	| VK	| 02/13/06	| Added new fields for update
*/

CREATE PROCEDURE wm_UPurchaseOrderDetail01
	@Company nvarchar(25),
	@DateTimeStamp datetime,
	@Item nvarchar(50),
	@ItemCategory1 nvarchar(50),
	@ItemCategory2 nvarchar(50),
	@ItemCategory3 nvarchar(50),
	@ItemCategory4 nvarchar(50),
	@ItemCategory5 nvarchar(50),
	@ItemCategory6 nvarchar(50),
	@ItemCategory7 nvarchar(50),
	@ItemCategory8 nvarchar(50),
	@ItemCategory9 nvarchar(50),
	@ItemCategory10 nvarchar(50),
	@ItemClass nvarchar(50),
	@ItemColor nvarchar(25),	
	@ItemDesc nvarchar(100),
	@ItemDepartment nvarchar(25),
	@ItemDimensionUm nvarchar(25),
	@ItemDivision nvarchar(25),
	@ItemHeight numeric(19,5),
	@ItemLength numeric(19,5),
	@ItemListPrice numeric(19,5),
	@ItemNetPrice numeric(19,5),
	@ItemSize nvarchar(25),
	@ItemStyle nvarchar(25),
	@ItemWidth numeric(19,5),
	@ItemWeight numeric(19,5),
	@LineNumber numeric(19,5),
	@ObjectId numeric(9),
	@OpenQuantity numeric(19,5),
	@ProcessStamp nvarchar(100),
	@PurchaseOrderObjectId numeric(9),
	@PurchaseOrderId nvarchar(25),
	@QuantityUm nvarchar(25),
	@TotalQty numeric(19,5),
	@UserDef1 nvarchar(25),
	@UserDef2 nvarchar(25),
	@UserDef3 nvarchar(25),
	@UserDef4 nvarchar(25),
	@UserDef5 nvarchar(25),
	@UserDef6 nvarchar(25),
	@UserDef7 numeric(19,5),
	@UserDef8 numeric(19,5),
	@UserStamp nvarchar(30),
	@WeightUm nvarchar(25)
AS
			update
				PURCHASE_ORDER_DETAIL
			set
				company = @Company,
				DATE_TIME_STAMP =@DateTimeStamp,
				item =  @Item,         
				item_category1 = @ItemCategory1,
				item_category2 = @ItemCategory2,
				item_category3 = @ItemCategory3,
				item_category4 = @ItemCategory4,
				item_category5 = @ItemCategory5,
				item_category6 = @ItemCategory6,
				item_category7 = @ItemCategory7,
				item_category8 = @ItemCategory8,
				item_category9 = @ItemCategory9,
				item_category10 = @ItemCategory10,
				item_class = @ItemClass, 
				item_color = @ItemColor,
				item_desc = @ItemDesc,
				item_department = @ItemDepartment,
				item_dimension_um = @ItemDimensionUm,
				item_division =	@ItemDivision,  
				item_height = @ItemHeight,     
				item_length = @ItemLength,     
				item_list_price = @ItemListPrice,  
				item_net_price = @ItemNetPrice,   
				item_size = @ItemSize,       
				item_style = @ItemStyle,      
				item_width = @ItemWidth,      
				item_weight = @ItemWeight,     
				LINE_NUMBER = @LineNumber,     
				OPEN_QUANTITY =	@OpenQuantity,   
				PROCESS_STAMP =	@ProcessStamp,   
				PURCHASE_ORDER_OBJECT_ID = @PurchaseOrderObjectId,
				PURCHASE_ORDER_ID =@PurchaseOrderId,    
				quantity_um = @QuantityUm,
				total_quantity = @TotalQty,
				user_def1 = @UserDef1,
				user_def2 = @UserDef2,
				user_def3 = @UserDef3,
				user_def4 = @UserDef4,
				user_def5 = @UserDef5,
				user_def6 = @UserDef6,
				user_def7 = @UserDef7,
				user_def8 = @UserDef8,
				USER_STAMP = @UserStamp,
				weight_um = @WeightUm

			where
				object_id = @ObjectId;


