
CREATE PROCEDURE wm_UReceiptContainer01
	@RowsAffected int OUTPUT,
	@InternalRecContNum numeric(9),
	@LocatingRule nvarchar(25),
	@Company nvarchar(25),
	@InternalReceiptNum numeric(9),
	@InternalReceiptLineNum numeric(9),
	@ReceiptId nvarchar(25),
	@ReceiptIdType nvarchar(25),
	@ContainerId nvarchar(25),
	@ContainerType nvarchar(25),
	@ContainerClass nvarchar(25),
	@Parent numeric(9),
	@Item nvarchar(50),
	@Quantity numeric(28,5),
	@QuantityUm nvarchar(25),
	@Status numeric(3),
	@StatusFailed nchar(1),
	@FromWarehouse nvarchar(25),
	@ToWarehouse nvarchar(25),
	@FromLocation nvarchar(25),
	@ToLocation nvarchar(25),
	@LaunchNum numeric(9),
	@UserDef1 nvarchar(25),
	@UserDef2 nvarchar(25),
	@UserDef3 nvarchar(25),
	@UserDef4 nvarchar(25),
	@UserDef5 nvarchar(25),
	@UserDef6 nvarchar(25),
	@UserDef7 numeric(19,5),
	@UserDef8 numeric(19,5),
	@UserStamp nvarchar(30),
	@ProcessStamp nvarchar(100),
	@DateTimeStamp datetime,
	@StatusFlowName nvarchar(25),
	@Weight numeric(19,5),
	@WeightUm nvarchar(25),
	@Length numeric(19,5),
	@Width numeric(19,5),
	@Height numeric(19,5),
	@DimensionUm nvarchar(25),
	@Lot nvarchar(25),
	@ItemDesc nvarchar(100),
	@ConvertedLocQty numeric(19,5),
	@ConvertedQtyUm nvarchar(25),
	@ItemClass nvarchar(50),
	@ReceiptDate datetime,
	@ExpirationDateTime datetime,
	@ManufacturedDateTime datetime,
	@InternalLocContNum numeric(9),
	@UploadInterfaceBatch nvarchar(50),
	@InterfaceRecordId nvarchar(25),
	@IncomingPdLoc nvarchar(25),
	@OutgoingPdLoc nvarchar(25),
	@UsedByImmedNeed nchar(1),
	@InventorySts nvarchar(50),
	@QcInspection nchar(1),
	@DispositionCode nvarchar(50),
	@ReasonCode nvarchar(50)
AS
	UPDATE RECEIPT_CONTAINER
	   SET
		LOCATING_RULE=@LocatingRule,
		COMPANY=@Company,
		INTERNAL_RECEIPT_NUM=@InternalReceiptNum,
		INTERNAL_RECEIPT_LINE_NUM=@InternalReceiptLineNum,
		RECEIPT_ID=@ReceiptId,
		RECEIPT_ID_TYPE=@ReceiptIdType,
		CONTAINER_ID=@ContainerId,
		CONTAINER_TYPE=@ContainerType,
		CONTAINER_CLASS=@ContainerClass,
		PARENT=@Parent,
		ITEM=@Item,
		QUANTITY=@Quantity,
		QUANTITY_UM=@QuantityUm,
		STATUS=@Status,
		STATUS_FAILED=@StatusFailed,
		FROM_WAREHOUSE=@FromWarehouse,
		TO_WAREHOUSE=@ToWarehouse,
		FROM_LOCATION=@FromLocation,
		TO_LOCATION=@ToLocation,
		LAUNCH_NUM=@LaunchNum,
		USER_DEF1=@UserDef1,
		USER_DEF2=@UserDef2,
		USER_DEF3=@UserDef3,
		USER_DEF4=@UserDef4,
		USER_DEF5=@UserDef5,
		USER_DEF6=@UserDef6,
		USER_DEF7=@UserDef7,
		USER_DEF8=@UserDef8,
		USER_STAMP=@UserStamp,
		PROCESS_STAMP=@ProcessStamp,
		DATE_TIME_STAMP=@DateTimeStamp,
		STATUS_FLOW_NAME=@StatusFlowName,
		WEIGHT=@Weight,
		WEIGHT_UM=@WeightUm,
		LENGTH=@Length,
		WIDTH=@Width,
		HEIGHT=@Height,
		DIMENSION_UM=@DimensionUm,
		LOT=@Lot,
		ITEM_DESC=@ItemDesc,
		CONVERTED_LOC_QTY=@ConvertedLocQty,
		CONVERTED_QTY_UM=@ConvertedQtyUm,
		ITEM_CLASS=@ItemClass,
		RECEIPT_DATE=@ReceiptDate,
		EXPIRATION_DATE_TIME=@ExpirationDateTime,
		MANUFACTURED_DATE_TIME=@ManufacturedDateTime,
		INTERNAL_LOC_CONT_NUM=@InternalLocContNum,
		UPLOAD_INTERFACE_BATCH=@UploadInterfaceBatch,
		INTERFACE_RECORD_ID=@InterfaceRecordId,
		INCOMING_PD_LOC=@IncomingPdLoc,
		OUTGOING_PD_LOC=@OutgoingPdLoc,
		USED_BY_IMMED_NEED=@UsedByImmedNeed,
		INVENTORY_STS=@InventorySts,
		QC_INSPECTION=@QcInspection,
		DISPOSITION_CODE=@DispositionCode,
		REASON_CODE=@ReasonCode
	 WHERE INTERNAL_REC_CONT_NUM = @InternalRecContNum

	SET @RowsAffected = @@ROWCOUNT


