/*
This SP will take the one unique inserted into the upload_location_inventory_Attributes table during the upload bases on the min(loc_inv_attributes_id) and will check for all other records with same attributes.

Task	| By	| Date		| Modification Description
	--------------------------------------------------------------------
139920	| JY	| 04/01/14	| Created
188720  | SHS	| 10/13/16	| Modified to avoid updating the loc_inv_attrs as delimited upload uses these records for writing to file
191074	| DN	| 01/23/17	| Updated parameter types
247714	| MK	| 03/04/20	| Modified to prevent timeout in case of large data. Moved the loop to C# code.

*/
CREATE PROCEDURE wm_InsertLocationInventoryAttributes
@PROCESSSTAMP nvarchar(100),
@INTERFACEACTIONCODE nvarchar(25),
@INTERFACECONDITION nvarchar(25),
@ITEM nvarchar(50),
@COMPANY nvarchar(25),
@WAREHOUSE nvarchar(25),
@LOT nvarchar(25),
@INVENTORY_STS nvarchar(50),
@INTERFACE_RECORD_ID numeric(9),
@LOC_OBJECT_ID numeric(9)

AS

BEGIN
INSERT INTO UPLOAD_LOCATION_INVENTORY_ATTRIBUTES 
(INTERFACE_RECORD_ID, 
INTERFACE_LINK_ID, 
INTERFACE_ACTION_CODE, 
INTERFACE_CONDITION, 
INTERNAL_SHIPPING_CONTAINER_NUM, 
LOC_INV_ATTRIBUTE1,
LOC_INV_ATTRIBUTE2, 
LOC_INV_ATTRIBUTE3, 
LOC_INV_ATTRIBUTE4, 
LOC_INV_ATTRIBUTE5, 
LOC_INV_ATTRIBUTE6, 
LOC_INV_ATTRIBUTE7, 
LOC_INV_ATTRIBUTE8, 
LOC_INV_ATTRIBUTE9, 
LOC_INV_ATTRIBUTE10, 
LOC_INV_ATTRIBUTE11,
LOC_INV_ATTRIBUTE12, 
LOC_INV_ATTRIBUTE13, 
LOC_INV_ATTRIBUTE14, 
LOC_INV_ATTRIBUTE15, 
LOC_INV_ATTRIBUTE16, 
LOC_INV_ATTRIBUTE17, 
LOC_INV_ATTRIBUTE18, 
LOC_INV_ATTRIBUTE19, 
LOC_INV_ATTRIBUTE20,
USER_DEF1, 
USER_DEF2, 
USER_DEF3, 
USER_DEF4, 
USER_DEF5, 
USER_DEF6, 
USER_DEF7, 
USER_DEF8, 
USER_STAMP, 
PROCESS_STAMP, 
DATE_TIME_STAMP )  
SELECT LIAT.OBJECT_ID AS INTERFACE_RECORD_ID, 
ULIAT.INTERFACE_LINK_ID AS INTERFACE_LINK_ID, 
@INTERFACEACTIONCODE AS INTERFACE_ACTION_CODE,  
@INTERFACECONDITION AS INTERFACE_CONDITION, 
ULIAT.INTERNAL_SHIPPING_CONTAINER_NUM AS INTERNAL_SHIPPING_CONTAINER_NUM, 
ULIAT.LOC_INV_ATTRIBUTE1 AS LOC_INV_ATTRIBUTE1, 
ULIAT.LOC_INV_ATTRIBUTE2 AS LOC_INV_ATTRIBUTE2, 
ULIAT.LOC_INV_ATTRIBUTE3 AS LOC_INV_ATTRIBUTE3, 
ULIAT.LOC_INV_ATTRIBUTE4 AS LOC_INV_ATTRIBUTE4, 
ULIAT.LOC_INV_ATTRIBUTE5 AS LOC_INV_ATTRIBUTE5, 
ULIAT.LOC_INV_ATTRIBUTE6 AS LOC_INV_ATTRIBUTE6, 
ULIAT.LOC_INV_ATTRIBUTE7 AS LOC_INV_ATTRIBUTE7, 
ULIAT.LOC_INV_ATTRIBUTE8 AS LOC_INV_ATTRIBUTE8, 
ULIAT.LOC_INV_ATTRIBUTE9 AS LOC_INV_ATTRIBUTE9, 
ULIAT.LOC_INV_ATTRIBUTE10 AS LOC_INV_ATTRIBUTE10, 
ULIAT.LOC_INV_ATTRIBUTE11 AS LOC_INV_ATTRIBUTE11, 
ULIAT.LOC_INV_ATTRIBUTE12 AS LOC_INV_ATTRIBUTE12, 
ULIAT.LOC_INV_ATTRIBUTE13 AS LOC_INV_ATTRIBUTE13, 
ULIAT.LOC_INV_ATTRIBUTE14 AS LOC_INV_ATTRIBUTE14, 
ULIAT.LOC_INV_ATTRIBUTE15 AS LOC_INV_ATTRIBUTE15, 
ULIAT.LOC_INV_ATTRIBUTE16 AS LOC_INV_ATTRIBUTE16, 
ULIAT.LOC_INV_ATTRIBUTE17 AS LOC_INV_ATTRIBUTE17, 
ULIAT.LOC_INV_ATTRIBUTE18 AS LOChe_INV_ATTRIBUTE18, 
ULIAT.LOC_INV_ATTRIBUTE19 AS LOC_INV_ATTRIBUTE19, 
ULIAT.LOC_INV_ATTRIBUTE20 AS LOC_INV_ATTRIBUTE20,
LIAT.USER_DEF1 AS USER_DEF1, 
LIAT.USER_DEF2 AS USER_DEF2, 
LIAT.USER_DEF3 AS USER_DEF3, 
LIAT.USER_DEF4 AS USER_DEF4,
LIAT.USER_DEF5 AS USER_DEF5, 
LIAT.USER_DEF6 AS USER_DEF6, 
LIAT.USER_DEF7 AS USER_DEF7, 
LIAT.USER_DEF8 AS USER_DEF8,
LIAT.USER_STAMP AS USER_STAMP,  
@PROCESSSTAMP AS PROCESS_STAMP,  
CONVERT(DATETIME,CONVERT(NVARCHAR,GETUTCDATE(),20))  AS DATE_TIME_STAMP  
FROM (SELECT LIT.*,LI.ITEM, LI.COMPANY, LI.WAREHOUSE, LI.LOT, LI.INVENTORY_STS FROM LOCATION_INVENTORY_ATTRIBUTES LIT LEFT OUTER JOIN  LOCATION_INVENTORY LI ON LI.LOC_INV_ATTRIBUTES_ID = LIT.OBJECT_ID) AS LIAT 
INNER JOIN  UPLOAD_LOCATION_INVENTORY_ATTRIBUTES ULIAT ON
 ( ISNULL(LIAT.LOC_INV_ATTRIBUTE1, N'!')  =  ISNULL(ULIAT.LOC_INV_ATTRIBUTE1, N'!') )   
AND ( ISNULL(LIAT.LOC_INV_ATTRIBUTE2, N'!')  =  ISNULL(ULIAT.LOC_INV_ATTRIBUTE2, N'!') )
AND ( ISNULL(LIAT.LOC_INV_ATTRIBUTE3, N'!')  =  ISNULL(ULIAT.LOC_INV_ATTRIBUTE3, N'!') )   
AND ( ISNULL(LIAT.LOC_INV_ATTRIBUTE4, N'!')  =  ISNULL(ULIAT.LOC_INV_ATTRIBUTE4, N'!') )
AND ( ISNULL(LIAT.LOC_INV_ATTRIBUTE5, N'!')  =  ISNULL(ULIAT.LOC_INV_ATTRIBUTE5, N'!') )   
AND ( ISNULL(LIAT.LOC_INV_ATTRIBUTE6, N'!')  =  ISNULL(ULIAT.LOC_INV_ATTRIBUTE6, N'!') )
AND ( ISNULL(LIAT.LOC_INV_ATTRIBUTE7, N'!')  =  ISNULL(ULIAT.LOC_INV_ATTRIBUTE7, N'!') )   
AND ( ISNULL(LIAT.LOC_INV_ATTRIBUTE8, N'!')  =  ISNULL(ULIAT.LOC_INV_ATTRIBUTE8, N'!') )
AND ( ISNULL(LIAT.LOC_INV_ATTRIBUTE9, N'!')  =  ISNULL(ULIAT.LOC_INV_ATTRIBUTE9, N'!') )   
AND ( ISNULL(LIAT.LOC_INV_ATTRIBUTE10, N'!')  =  ISNULL(ULIAT.LOC_INV_ATTRIBUTE10, N'!') )
AND ( ISNULL(LIAT.LOC_INV_ATTRIBUTE11, N'!')  =  ISNULL(ULIAT.LOC_INV_ATTRIBUTE11, N'!') )   
AND ( ISNULL(LIAT.LOC_INV_ATTRIBUTE12, N'!')  =  ISNULL(ULIAT.LOC_INV_ATTRIBUTE12, N'!') )
AND ( ISNULL(LIAT.LOC_INV_ATTRIBUTE13, N'!')  =  ISNULL(ULIAT.LOC_INV_ATTRIBUTE13, N'!') )   
AND ( ISNULL(LIAT.LOC_INV_ATTRIBUTE14, N'!')  =  ISNULL(ULIAT.LOC_INV_ATTRIBUTE14, N'!') )
AND ( ISNULL(LIAT.LOC_INV_ATTRIBUTE15, N'!')  =  ISNULL(ULIAT.LOC_INV_ATTRIBUTE15, N'!') )   
AND ( ISNULL(LIAT.LOC_INV_ATTRIBUTE16, N'!')  =  ISNULL(ULIAT.LOC_INV_ATTRIBUTE16, N'!') )
AND ( ISNULL(LIAT.LOC_INV_ATTRIBUTE17, N'!')  =  ISNULL(ULIAT.LOC_INV_ATTRIBUTE17, N'!') )   
AND ( ISNULL(LIAT.LOC_INV_ATTRIBUTE18, N'!')  =  ISNULL(ULIAT.LOC_INV_ATTRIBUTE18, N'!') )
AND ( ISNULL(LIAT.LOC_INV_ATTRIBUTE19, N'!')  =  ISNULL(ULIAT.LOC_INV_ATTRIBUTE19, N'!') )   
AND ( ISNULL(LIAT.LOC_INV_ATTRIBUTE20, N'!')  =  ISNULL(ULIAT.LOC_INV_ATTRIBUTE20, N'!') )
WHERE
LIAT.ITEM = @ITEM
AND ( ISNULL(LIAT.COMPANY, N'!')  = ISNULL(@COMPANY, N'!') )
AND LIAT.warehouse = @WAREHOUSE
AND LIAT.INVENTORY_STS = @INVENTORY_STS 
AND  ( ISNULL(LIAT.LOT, N'!')  =  ISNULL(@LOT , N'!') )
AND ULIAT.INTERFACE_RECORD_ID = @INTERFACE_RECORD_ID 
AND ULIAT.PROCESS_STAMP = @PROCESSSTAMP;

DELETE FROM UPLOAD_LOCATION_INVENTORY_ATTRIBUTES WHERE OBJECT_ID = @LOC_OBJECT_ID;

END

