/*
This SP will insert the serial number for the records which contains location inventory attributes.

Task	| By	| Date		| Modification Description
	--------------------------------------------------------------------
139920	| JY	| 04/01/14	| Created
143963	| DN	| 06/17/14	| multiple location inventory records can have the same location inventory attribute id
191074	| DN	| 01/23/17	| Updated parameter types
*/

CREATE PROCEDURE wm_InsertUploadSerialNumber

@PROCESSSTAMP nvarchar(100),
@INTERFACEACTIONCODE nvarchar(25),
@INTERFACECONDITION nvarchar(25)
AS
DECLARE @count INT
SET @count = 1
DECLARE @table TABLE (OBJECT_ID INT IDENTITY, INTERFACE_RECORD_ID INT , INTERFACE_LINK_ID INT)
DECLARE @loop INT 
INSERT INTO @table SELECT INTERFACE_RECORD_ID,INTERFACE_LINK_ID FROM UPLOAD_LOCATION_INVENTORY_ATTRIBUTES WHERE PROCESS_STAMP = @PROCESSSTAMP;
SELECT @loop = COUNT(OBJECT_ID) FROM @table;

WHILE(@count <= @loop)
BEGIN
DECLARE @loopId int
SELECT @loopId = INTERFACE_RECORD_ID FROM @TABLE WHERE OBJECT_ID = @count;
INSERT INTO UPLOAD_SERIAL_NUMBER (INTERFACE_RECORD_ID,INTERFACE_LINK_ID,INTERFACE_ACTION_CODE,INTERFACE_CONDITION,SERIAL_NUMBER,SERIAL_NUM_TEMPLATE_DESC,
USER_DEF1,USER_DEF2,USER_DEF3,USER_DEF4,USER_DEF5,USER_DEF6,USER_DEF7,USER_DEF8,USER_STAMP,PROCESS_STAMP,DATE_TIME_STAMP, UPLOAD_TYPE) 
SELECT DISTINCT SN.OBJECT_ID AS INTERFACE_RECORD_ID, (SELECT INTERFACE_LINK_ID FROM @table where OBJECT_ID = @count) AS INTERFACE_LINK_ID,
@INTERFACEACTIONCODE AS INTERFACE_ACTION_CODE,
 @INTERFACECONDITION AS INTERFACE_CONDITION,
SN.SERIAL_NUMBER,SNT.DESCRIPTION AS SERIAL_NUM_TEMPLATE_DESC,SN.USER_DEF1,SN.USER_DEF2,SN.USER_DEF3,SN.USER_DEF4,SN.USER_DEF5,SN.USER_DEF6,SN.USER_DEF7,SN.USER_DEF8, N'ILSSRV' AS USER_STAMP, 
@PROCESSSTAMP AS PROCESS_STAMP, convert(datetime,convert(nvarchar,GETUTCDATE(),20))  AS DATE_TIME_STAMP,  N'Item Balance' AS UPLOAD_TYPE 
FROM SERIAL_NUMBER SN, SERIAL_NUM_TEMPLATE SNT
WHERE SN.TEMPLATE_ID = SNT.OBJECT_ID AND SNT.SEQUENCE = 0
AND SN.LOC_INV_NUM IN (SELECT INTERNAL_LOCATION_INV FROM LOCATION_INVENTORY WHERE LOC_INV_ATTRIBUTES_ID = @loopId)
 
UNION ALL 
SELECT DISTINCT SN.OBJECT_ID AS INTERFACE_RECORD_ID,(SELECT INTERFACE_LINK_ID FROM @table WHERE OBJECT_ID = @count) AS INTERFACE_LINK_ID,
 @INTERFACEACTIONCODE AS INTERFACE_ACTION_CODE, 
 @INTERFACECONDITION AS INTERFACE_CONDITION,
SN.SERIAL_NUMBER,NULL AS SERIAL_NUM_TEMPLATE_DESC,SN.USER_DEF1,SN.USER_DEF2,SN.USER_DEF3,SN.USER_DEF4,SN.USER_DEF5,SN.USER_DEF6,SN.USER_DEF7,SN.USER_DEF8, N'ILSSRV' AS USER_STAMP, 
@PROCESSSTAMP AS PROCESS_STAMP, convert(datetime,convert(nvarchar,GETUTCDATE(),20))  AS DATE_TIME_STAMP,  N'Item Balance' AS UPLOAD_TYPE 
FROM SERIAL_NUMBER SN
WHERE SN.TEMPLATE_ID IS NULL AND  SN.LOC_INV_NUM  IN (select INTERNAL_LOCATION_INV from LOCATION_INVENTORY where LOC_INV_ATTRIBUTES_ID = @loopId);

SET @count = @count + 1;
END
