
CREATE PROCEDURE wm_IOrderDetail01
	@InternalOrderDtlNum numeric(9) OUTPUT,
	@StatusFlowName nvarchar(25),
	@Warehouse nvarchar(25),
	@AllocationName nvarchar(25),
	@InternalOrderNum numeric(9),
	@ErpOrderLineNum numeric(19,5),
	@Condition nvarchar(25),
	@Customer nvarchar(25),
	@CustomerName nvarchar(50),
	@CustomerAddress1 nvarchar(50),
	@CustomerAddress2 nvarchar(50),
	@CustomerAddress3 nvarchar(50),
	@CustomerAttentionTo nvarchar(50),
	@CustomerCity nvarchar(30),
	@CustomerState nvarchar(25),
	@CustomerCountry nvarchar(25),
	@CustomerPostalCode nvarchar(25),
	@CustomerPhoneNum nvarchar(50),
	@CustomerFaxNum nvarchar(25),
	@CustomerEmailAddress nvarchar(50),
	@ShipTo nvarchar(25),
	@ShipToName nvarchar(50),
	@ShipToAddress1 nvarchar(50),
	@ShipToAddress2 nvarchar(50),
	@ShipToAddress3 nvarchar(50),
	@ShipToAttentionTo nvarchar(50),
	@ShipToCity nvarchar(30),
	@ShipToState nvarchar(25),
	@ShipToCountry nvarchar(25),
	@ShipToPostalCode nvarchar(25),
	@ShipToPhoneNum nvarchar(50),
	@ShipToFaxNum nvarchar(25),
	@ShipToEmailAddress nvarchar(50),
	@CustomerPo nvarchar(25),
	@OrderDate datetime,
	@RequestedDeliveryDate datetime,
	@RequestedDeliveryType nvarchar(10),
	@Item nvarchar(50),
	@Company nvarchar(25),
	@ItemDesc nvarchar(100),
	@ItemSize nvarchar(25),
	@ItemColor nvarchar(25),
	@ItemStyle nvarchar(25),
	@InitialWeight numeric(19,5),
	@WeightUm nvarchar(25),
	@InitialVolume numeric(19,5),
	@VolumeUm nvarchar(25),
	@InitialValue numeric(19,5),
	@InitialQty numeric(19,5),
	@OpenQty numeric(19,5),
	@ShippedQty numeric(19,5),
	@QuantityUm nvarchar(25),
	@CustomerItem nvarchar(50),
	@PlannedShipDate datetime,
	@InterfacedDate datetime,
	@PickLoc nvarchar(25),
	@PickZone nvarchar(25),
	@SecondaryPickLoc nvarchar(25),
	@SecondaryPickZone nvarchar(25),
	@ItemLength numeric(19,5),
	@ItemWidth numeric(19,5),
	@ItemHeight numeric(19,5),
	@ItemDimensionUm nvarchar(25),
	@ItemVolume numeric(19,5),
	@TotalVolume numeric(28,5),
	@TotalWeight numeric(28,5),
	@ItemDivision nvarchar(25),
	@ItemDepartment nvarchar(25),
	@ItemListPrice numeric(19,5),
	@ItemNetPrice numeric(19,5),
	@OriginalItemOrdered nvarchar(50),
	@Invoice nvarchar(25),
	@PackingCategory nvarchar(25),
	@HazardousCode nvarchar(25),
	@NmfcCode nvarchar(25),
	@CatalogId nvarchar(25),
	@ManufacturerId nvarchar(25),
	@MerchandiseCode nvarchar(25),
	@LotControlled nchar(1),
	@SerialNumReqd nchar(1),
	@CatchWeightReqd nchar(1),
	@UserDef1 nvarchar(25),
	@UserDef2 nvarchar(25),
	@UserDef3 nvarchar(25),
	@UserDef4 nvarchar(25),
	@UserDef5 nvarchar(25),
	@UserDef6 nvarchar(25),
	@UserDef7 numeric(19,5),
	@UserDef8 numeric(19,5),
	@UserStamp nvarchar(30),
	@ProcessStamp nvarchar(100),
	@DateTimeStamp datetime,
	@OrderPriority nvarchar(25),
	@MarkForName nvarchar(50),
	@MarkForAddress1 nvarchar(50),
	@MarkForAddress2 nvarchar(50),
	@MarkForAddress3 nvarchar(50),
	@MarkForAttentionTo nvarchar(50),
	@MarkForCity nvarchar(30),
	@MarkForState nvarchar(25),
	@MarkForCountry nvarchar(25),
	@MarkForPostalCode nvarchar(25),
	@MarkForPhoneNum nvarchar(50),
	@MarkForFaxNum nvarchar(25),
	@MarkForEmailAddress nvarchar(50),
	@PickListId nvarchar(25),
	@ItemWeight numeric(19,5),
	@Lot nvarchar(25),
	@ItemClass nvarchar(50),
	@InterfaceRecordId nvarchar(25),
	@ItemCategory1 nvarchar(50),
	@ItemCategory2 nvarchar(50),
	@ItemCategory3 nvarchar(50),
	@ItemCategory4 nvarchar(50),
	@ItemCategory5 nvarchar(50),
	@ItemCategory6 nvarchar(50),
	@ItemCategory7 nvarchar(50),
	@ItemCategory8 nvarchar(50),
	@ItemCategory9 nvarchar(50),
	@ItemCategory10 nvarchar(50),
	@PackingClass nvarchar(25),
	@AllocateFullLocQty nchar(1),
	@AllowPctAlloc nchar(1),
	@MinimumAllocPct numeric(4),
	@MaximumAllocPct numeric(4),
	@TreatAsLoose nchar(1)
AS
	INSERT INTO ORDER_DETAIL(
		ALLOCATE_FULL_LOC_QTY,
		ALLOCATION_NAME,
		ALLOW_PCT_ALLOC,
		CATALOG_ID,
		CATCH_WEIGHT_REQD,
		COMPANY,
		CONDITION,
		CUSTOMER,
		CUSTOMER_ADDRESS1,
		CUSTOMER_ADDRESS2,
		CUSTOMER_ADDRESS3,
		CUSTOMER_ATTENTION_TO,
		CUSTOMER_CITY,
		CUSTOMER_COUNTRY,
		CUSTOMER_EMAIL_ADDRESS,
		CUSTOMER_FAX_NUM,
		CUSTOMER_ITEM,
		CUSTOMER_NAME,
		CUSTOMER_PHONE_NUM,
		CUSTOMER_PO,
		CUSTOMER_POSTAL_CODE,
		CUSTOMER_STATE,
		DATE_TIME_STAMP,
		ERP_ORDER_LINE_NUM,
		HAZARDOUS_CODE,
		INITIAL_QTY,
		INITIAL_VALUE,
		INITIAL_VOLUME,
		INITIAL_WEIGHT,
		INTERFACE_RECORD_ID,
		INTERFACED_DATE,
		INTERNAL_ORDER_NUM,
		INVOICE,
		ITEM,
		ITEM_CATEGORY1,
		ITEM_CATEGORY10,
		ITEM_CATEGORY2,
		ITEM_CATEGORY3,
		ITEM_CATEGORY4,
		ITEM_CATEGORY5,
		ITEM_CATEGORY6,
		ITEM_CATEGORY7,
		ITEM_CATEGORY8,
		ITEM_CATEGORY9,
		ITEM_CLASS,
		ITEM_COLOR,
		ITEM_DEPARTMENT,
		ITEM_DESC,
		ITEM_DIMENSION_UM,
		ITEM_DIVISION,
		ITEM_HEIGHT,
		ITEM_LENGTH,
		ITEM_LIST_PRICE,
		ITEM_NET_PRICE,
		ITEM_SIZE,
		ITEM_STYLE,
		ITEM_VOLUME,
		ITEM_WEIGHT,
		ITEM_WIDTH,
		LOT,
		LOT_CONTROLLED,
		MANUFACTURER_ID,
		MARK_FOR_ADDRESS1,
		MARK_FOR_ADDRESS2,
		MARK_FOR_ADDRESS3,
		MARK_FOR_ATTENTION_TO,
		MARK_FOR_CITY,
		MARK_FOR_COUNTRY,
		MARK_FOR_EMAIL_ADDRESS,
		MARK_FOR_FAX_NUM,
		MARK_FOR_NAME,
		MARK_FOR_PHONE_NUM,
		MARK_FOR_POSTAL_CODE,
		MARK_FOR_STATE,
		MAXIMUM_ALLOC_PCT,
		MERCHANDISE_CODE,
		MINIMUM_ALLOC_PCT,
		NMFC_CODE,
		OPEN_QTY,
		ORDER_DATE,
		ORDER_PRIORITY,
		ORIGINAL_ITEM_ORDERED,
		PACKING_CATEGORY,
		PACKING_CLASS,
		PICK_LIST_ID,
		PICK_LOC,
		PICK_ZONE,
		PLANNED_SHIP_DATE,
		PROCESS_STAMP,
		QUANTITY_UM,
		REQUESTED_DELIVERY_DATE,
		REQUESTED_DELIVERY_TYPE,
		SECONDARY_PICK_LOC,
		SECONDARY_PICK_ZONE,
		SERIAL_NUM_REQD,
		SHIP_TO,
		SHIP_TO_ADDRESS1,
		SHIP_TO_ADDRESS2,
		SHIP_TO_ADDRESS3,
		SHIP_TO_ATTENTION_TO,
		SHIP_TO_CITY,
		SHIP_TO_COUNTRY,
		SHIP_TO_EMAIL_ADDRESS,
		SHIP_TO_FAX_NUM,
		SHIP_TO_NAME,
		SHIP_TO_PHONE_NUM,
		SHIP_TO_POSTAL_CODE,
		SHIP_TO_STATE,
		SHIPPED_QTY,
		STATUS_FLOW_NAME,
		TOTAL_VOLUME,
		TOTAL_WEIGHT,
		TREAT_AS_LOOSE,
		USER_DEF1,
		USER_DEF2,
		USER_DEF3,
		USER_DEF4,
		USER_DEF5,
		USER_DEF6,
		USER_DEF7,
		USER_DEF8,
		USER_STAMP,
		VOLUME_UM,
		warehouse,
		WEIGHT_UM
	) VALUES (
		@AllocateFullLocQty,
		@AllocationName,
		@AllowPctAlloc,
		@CatalogId,
		@CatchWeightReqd,
		@Company,
		@Condition,
		@Customer,
		@CustomerAddress1,
		@CustomerAddress2,
		@CustomerAddress3,
		@CustomerAttentionTo,
		@CustomerCity,
		@CustomerCountry,
		@CustomerEmailAddress,
		@CustomerFaxNum,
		@CustomerItem,
		@CustomerName,
		@CustomerPhoneNum,
		@CustomerPo,
		@CustomerPostalCode,
		@CustomerState,
		@DateTimeStamp,
		@ErpOrderLineNum,
		@HazardousCode,
		@InitialQty,
		@InitialValue,
		@InitialVolume,
		@InitialWeight,
		@InterfaceRecordId,
		@InterfacedDate,
		@InternalOrderNum,
		@Invoice,
		@Item,
		@ItemCategory1,
		@ItemCategory10,
		@ItemCategory2,
		@ItemCategory3,
		@ItemCategory4,
		@ItemCategory5,
		@ItemCategory6,
		@ItemCategory7,
		@ItemCategory8,
		@ItemCategory9,
		@ItemClass,
		@ItemColor,
		@ItemDepartment,
		@ItemDesc,
		@ItemDimensionUm,
		@ItemDivision,
		@ItemHeight,
		@ItemLength,
		@ItemListPrice,
		@ItemNetPrice,
		@ItemSize,
		@ItemStyle,
		@ItemVolume,
		@ItemWeight,
		@ItemWidth,
		@Lot,
		@LotControlled,
		@ManufacturerId,
		@MarkForAddress1,
		@MarkForAddress2,
		@MarkForAddress3,
		@MarkForAttentionTo,
		@MarkForCity,
		@MarkForCountry,
		@MarkForEmailAddress,
		@MarkForFaxNum,
		@MarkForName,
		@MarkForPhoneNum,
		@MarkForPostalCode,
		@MarkForState,
		@MaximumAllocPct,
		@MerchandiseCode,
		@MinimumAllocPct,
		@NmfcCode,
		@OpenQty,
		@OrderDate,
		@OrderPriority,
		@OriginalItemOrdered,
		@PackingCategory,
		@PackingClass,
		@PickListId,
		@PickLoc,
		@PickZone,
		@PlannedShipDate,
		@ProcessStamp,
		@QuantityUm,
		@RequestedDeliveryDate,
		@RequestedDeliveryType,
		@SecondaryPickLoc,
		@SecondaryPickZone,
		@SerialNumReqd,
		@ShipTo,
		@ShipToAddress1,
		@ShipToAddress2,
		@ShipToAddress3,
		@ShipToAttentionTo,
		@ShipToCity,
		@ShipToCountry,
		@ShipToEmailAddress,
		@ShipToFaxNum,
		@ShipToName,
		@ShipToPhoneNum,
		@ShipToPostalCode,
		@ShipToState,
		@ShippedQty,
		@StatusFlowName,
		@TotalVolume,
		@TotalWeight,
		@TreatAsLoose,
		@UserDef1,
		@UserDef2,
		@UserDef3,
		@UserDef4,
		@UserDef5,
		@UserDef6,
		@UserDef7,
		@UserDef8,
		@UserStamp,
		@VolumeUm,
		@Warehouse,
		@WeightUm
	)
SELECT @InternalOrderDtlNum = SCOPE_IDENTITY()



