/*
	Task	| By	| Date		| Modification Description
	--------------------------------------------------------------------
	16446	| MD	| 02/05/05	| Fixed load update.
	5114	| SPS	| 06/06/07	| Modified query to remove the six TOTAL columns that are dropped 
									and added columns that are added to SHIPMENT_HEADER
    11821	| DSK	| 10/12/07	| Removed STAGING_DOCK_LOC_AREA, STAGING_DOCK_LOC_POS
    31643	| MM	| 07/24/08	| Added SHIPPER_CODE
*/


CREATE PROCEDURE wm_UShipmentHeader01
	@RowsAffected int OUTPUT,
	@InternalShipmentNum numeric(9),
	@Warehouse nvarchar(25),
	@ShippingLoadNum numeric(9),
	@ShipmentId nvarchar(25),
	@ShipperCode nvarchar(25),
	@LaunchStep nvarchar(25),
	@TrailingSts numeric(3),
	@TrailingStsDate datetime,
	@TrailingStsFailed nchar(1),
	@OrderType nvarchar(25),
	@Consolidated nchar(1),
	@LeadingSts numeric(3),
	@LeadingStsDate datetime,
	@Carrier nvarchar(25),
	@LeadingStsFailed nchar(1),
	@Company nvarchar(25),
	@CarrierService nvarchar(50),
	@CarrierGroup nvarchar(25),
	@CarrierType nvarchar(25),
	@FreightTerms nvarchar(50),
	@LiabilityTerms nvarchar(25),
	@Customer nvarchar(25),
	@ShipTo nvarchar(25),
	@Route nvarchar(25),
	@Stop nvarchar(25),
	@ShipToAddress1 nvarchar(50),
	@CustomerName nvarchar(50),
	@ShipToAddress2 nvarchar(50),
	@ShipToAddress3 nvarchar(50),
	@ShipToCity nvarchar(30),
	@ShipToState nvarchar(25),
	@ShipToCountry nvarchar(25),
	@ShipToPostalCode nvarchar(25),
	@ShipToPhoneNum nvarchar(50),
	@ShipToFaxNum nvarchar(50),
	@CustomerAddress1 nvarchar(50),
	@LaunchNum numeric(9),
	@WeightUm nvarchar(25),
	@VolumeUm nvarchar(25),
	@RoutingCode nvarchar(25),
	@SingleItemCartons nchar(1),
	@UserDef1 nvarchar(25),
	@UserDef2 nvarchar(25),
	@Priority numeric(3),
	@UserDef3 nvarchar(25),
	@UserDef4 nvarchar(25),
	@UserDef5 nvarchar(25),
	@UserDef6 nvarchar(25),
	@UserDef7 numeric(19,5),
	@ManuallyEntered nchar(1),
	@UserDef8 numeric(19,5),
	@UserStamp nvarchar(30),
	@ProcessStamp nvarchar(100),
	@DateTimeStamp datetime,
	@BolNumAlpha nvarchar(25),
	@ProNumAlpha nvarchar(25),
	@CustomerAddress3 nvarchar(50),
	@CustomerAddress2 nvarchar(50),
	@CustomerAttentionTo nvarchar(50),
	@CustomerCity nvarchar(30),
	@CustomerState nvarchar(25),
	@CustomerCountry nvarchar(25),
	@CustomerPostalCode nvarchar(25),
	@CustomerPhoneNum nvarchar(50),
	@CustomerFaxNum nvarchar(50),
	@CustomerEmailAddress nvarchar(50),
	@ShipToName nvarchar(50),
	@ShipToAttentionTo nvarchar(50),
	@ShipToEmailAddress nvarchar(50),
	@RequestedDeliveryDate datetime,
	@RequestedDeliveryType nvarchar(10),
	@ScheduledShipDate datetime,
	@PlannedShipDate datetime,
	@ActualShipDateTime datetime,
	@PlannedDeliveryDateTime datetime,
	@ActualDeliveryDateTime datetime,
	@QuantityUm nvarchar(25),
	@TotalFreightCharge numeric(28,5),
	@BaseFreightCharge numeric(19,5),
	@FreightDiscount numeric(19,5),
	@AccessorialCharge numeric(19,5),
	@ConsolidationAllowed nchar(1),
	@IntermediateConsignee nvarchar(25),
	@IntermediateName nvarchar(50),
	@IntermediateAddress1 nvarchar(50),
	@IntermediateAddress2 nvarchar(50),
	@IntermediateAddress3 nvarchar(50),
	@IntermediateAttentionTo nvarchar(50),
	@IntermediateCity nvarchar(30),
	@IntermediateState nvarchar(25),
	@IntermediateCountry nvarchar(25),
	@IntermediatePostalCode nvarchar(25),
	@IntermediatePhoneNum nvarchar(50),
	@IntermediateFaxNum nvarchar(50),
	@IntermediateEmailAddress nvarchar(50),
	@FreightBillTo nvarchar(25),
	@FreightBillToName nvarchar(50),
	@FreightBillToAddress1 nvarchar(50),
	@FreightBillToAddress2 nvarchar(50),
	@FreightBillToAddress3 nvarchar(50),
	@FreightBillToAttentionTo nvarchar(50),
	@FreightBillToCity nvarchar(30),
	@FreightBillToState nvarchar(25),
	@FreightBillToCountry nvarchar(25),
	@FreightBillToPostalCode nvarchar(25),
	@FreightBillToPhoneNum nvarchar(50),
	@FreightBillToFaxNum nvarchar(50),
	@FreightBillToEmailAddress nvarchar(50),
	@ErpOrder nvarchar(25),
	@InternalOrderNum numeric(9),
	@ExportTaxId nvarchar(25),
	@Parties nvarchar(100),
	@LoadingPier nvarchar(50),
	@TransportationMode nvarchar(25),
	@ExportPort nvarchar(50),
	@UnloadingPort nvarchar(50),
	@Containerized nchar(1),
	@Ftz nvarchar(25),
	@ValidatedLicense nvarchar(50),
	@LicenseExpDate datetime,
	@Eccn nvarchar(50),
	@AuthorizedEmplName nvarchar(50),
	@AuthorizedEmplTitle nvarchar(50),
	@UploadInterfaceBatch nvarchar(50),
	@CustomerResidentialFlag nchar(1),
	@ShiptoResidentialFlag nchar(1),
	@RejectionNote nvarchar(1000),
	@InterfaceRecordId nvarchar(25),
	@CustomerCategory1 nvarchar(50),
	@CustomerCategory2 nvarchar(50),
	@CustomerCategory3 nvarchar(50),
	@CustomerCategory4 nvarchar(50),
	@CustomerCategory5 nvarchar(50),
	@CustomerCategory6 nvarchar(50),
	@CustomerCategory7 nvarchar(50),
	@CustomerCategory8 nvarchar(50),
	@CustomerCategory9 nvarchar(50),
	@CustomerCategory10 nvarchar(50),
	@ConsolidationDockLocArea nvarchar(25),
	@ConsolidationDockLocPos nvarchar(25),	
	@ProcessType nvarchar(25),
	@CreationProcessStamp nvarchar(100),
	@CreationDateTimeStamp datetime,
	@ImmediateNeedsNote nvarchar(50),
	@AllocateComplete nchar(1),
	@AlternateEmailAddress nvarchar(50),
	@StopSequence numeric(9),
	@StoreDistribution nvarchar(25),
	@WeightEntered numeric(28,5),
	@VolumeEntered numeric(28,5),
	@ValueEntered numeric(28,5)
AS
	UPDATE SHIPMENT_HEADER
	   SET
		warehouse=@Warehouse,
		SHIPPING_LOAD_NUM=(CASE WHEN @ShippingLoadNum = 0 THEN NULL ELSE @ShippingLoadNum END ),
		SHIPMENT_ID=@ShipmentId,
		SHIPPER_CODE=@ShipperCode,
		LAUNCH_STEP=@LaunchStep,
		TRAILING_STS=@TrailingSts,
		TRAILING_STS_DATE=@TrailingStsDate,
		TRAILING_STS_FAILED=@TrailingStsFailed,
		ORDER_TYPE=@OrderType,
		CONSOLIDATED=@Consolidated,
		LEADING_STS=@LeadingSts,
		LEADING_STS_DATE=@LeadingStsDate,
		CARRIER=@Carrier,
		LEADING_STS_FAILED=@LeadingStsFailed,
		COMPANY=@Company,
		CARRIER_SERVICE=@CarrierService,
		CARRIER_GROUP=@CarrierGroup,
		CARRIER_TYPE=@CarrierType,
		FREIGHT_TERMS=@FreightTerms,
		LIABILITY_TERMS=@LiabilityTerms,
		CUSTOMER=@Customer,
		SHIP_TO=@ShipTo,
		ROUTE=@Route,
		STOP=@Stop,
		SHIP_TO_ADDRESS1=@ShipToAddress1,
		CUSTOMER_NAME=@CustomerName,
		SHIP_TO_ADDRESS2=@ShipToAddress2,
		SHIP_TO_ADDRESS3=@ShipToAddress3,
		SHIP_TO_CITY=@ShipToCity,
		SHIP_TO_STATE=@ShipToState,
		SHIP_TO_COUNTRY=@ShipToCountry,
		SHIP_TO_POSTAL_CODE=@ShipToPostalCode,
		SHIP_TO_PHONE_NUM=@ShipToPhoneNum,
		SHIP_TO_FAX_NUM=@ShipToFaxNum,
		CUSTOMER_ADDRESS1=@CustomerAddress1,
		LAUNCH_NUM=@LaunchNum,
		WEIGHT_UM=@WeightUm,
		VOLUME_UM=@VolumeUm,
		ROUTING_CODE=@RoutingCode,
		SINGLE_ITEM_CARTONS=@SingleItemCartons,
		USER_DEF1=@UserDef1,
		USER_DEF2=@UserDef2,
		PRIORITY=@Priority,
		USER_DEF3=@UserDef3,
		USER_DEF4=@UserDef4,
		USER_DEF5=@UserDef5,
		USER_DEF6=@UserDef6,
		USER_DEF7=@UserDef7,
		MANUALLY_ENTERED=@ManuallyEntered,
		USER_DEF8=@UserDef8,
		USER_STAMP=@UserStamp,
		PROCESS_STAMP=@ProcessStamp,
		DATE_TIME_STAMP=@DateTimeStamp,
		BOL_NUM_ALPHA=@BolNumAlpha,
		PRO_NUM_ALPHA=@ProNumAlpha,
		CUSTOMER_ADDRESS3=@CustomerAddress3,
		CUSTOMER_ADDRESS2=@CustomerAddress2,
		CUSTOMER_ATTENTION_TO=@CustomerAttentionTo,
		CUSTOMER_CITY=@CustomerCity,
		CUSTOMER_STATE=@CustomerState,
		CUSTOMER_COUNTRY=@CustomerCountry,
		CUSTOMER_POSTAL_CODE=@CustomerPostalCode,
		CUSTOMER_PHONE_NUM=@CustomerPhoneNum,
		CUSTOMER_FAX_NUM=@CustomerFaxNum,
		CUSTOMER_EMAIL_ADDRESS=@CustomerEmailAddress,
		SHIP_TO_NAME=@ShipToName,
		SHIP_TO_ATTENTION_TO=@ShipToAttentionTo,
		SHIP_TO_EMAIL_ADDRESS=@ShipToEmailAddress,
		REQUESTED_DELIVERY_DATE=@RequestedDeliveryDate,
		REQUESTED_DELIVERY_TYPE=@RequestedDeliveryType,
		SCHEDULED_SHIP_DATE=@ScheduledShipDate,
		PLANNED_SHIP_DATE=@PlannedShipDate,
		ACTUAL_SHIP_DATE_TIME=@ActualShipDateTime,
		PLANNED_DELIVERY_DATE_TIME=@PlannedDeliveryDateTime,
		ACTUAL_DELIVERY_DATE_TIME=@ActualDeliveryDateTime,
		QUANTITY_UM=@QuantityUm,
		TOTAL_FREIGHT_CHARGE=@TotalFreightCharge,
		BASE_FREIGHT_CHARGE=@BaseFreightCharge,
		FREIGHT_DISCOUNT=@FreightDiscount,
		ACCESSORIAL_CHARGE=@AccessorialCharge,
		CONSOLIDATION_ALLOWED=@ConsolidationAllowed,
		INTERMEDIATE_CONSIGNEE=@IntermediateConsignee,
		INTERMEDIATE_NAME=@IntermediateName,
		INTERMEDIATE_ADDRESS1=@IntermediateAddress1,
		INTERMEDIATE_ADDRESS2=@IntermediateAddress2,
		INTERMEDIATE_ADDRESS3=@IntermediateAddress3,
		INTERMEDIATE_ATTENTION_TO=@IntermediateAttentionTo,
		INTERMEDIATE_CITY=@IntermediateCity,
		INTERMEDIATE_STATE=@IntermediateState,
		INTERMEDIATE_COUNTRY=@IntermediateCountry,
		INTERMEDIATE_POSTAL_CODE=@IntermediatePostalCode,
		INTERMEDIATE_PHONE_NUM=@IntermediatePhoneNum,
		INTERMEDIATE_FAX_NUM=@IntermediateFaxNum,
		INTERMEDIATE_EMAIL_ADDRESS=@IntermediateEmailAddress,
		FREIGHT_BILL_TO=@FreightBillTo,
		FREIGHT_BILL_TO_NAME=@FreightBillToName,
		FREIGHT_BILL_TO_ADDRESS1=@FreightBillToAddress1,
		FREIGHT_BILL_TO_ADDRESS2=@FreightBillToAddress2,
		FREIGHT_BILL_TO_ADDRESS3=@FreightBillToAddress3,
		FREIGHT_BILL_TO_ATTENTION_TO=@FreightBillToAttentionTo,
		FREIGHT_BILL_TO_CITY=@FreightBillToCity,
		FREIGHT_BILL_TO_STATE=@FreightBillToState,
		FREIGHT_BILL_TO_COUNTRY=@FreightBillToCountry,
		FREIGHT_BILL_TO_POSTAL_CODE=@FreightBillToPostalCode,
		FREIGHT_BILL_TO_PHONE_NUM=@FreightBillToPhoneNum,
		FREIGHT_BILL_TO_FAX_NUM=@FreightBillToFaxNum,
		FREIGHT_BILL_TO_EMAIL_ADDRESS=@FreightBillToEmailAddress,
		ERP_ORDER=@ErpOrder,
		INTERNAL_ORDER_NUM=@InternalOrderNum,
		EXPORT_TAX_ID=@ExportTaxId,
		PARTIES=@Parties,
		LOADING_PIER=@LoadingPier,
		TRANSPORTATION_MODE=@TransportationMode,
		EXPORT_PORT=@ExportPort,
		UNLOADING_PORT=@UnloadingPort,
		CONTAINERIZED=@Containerized,
		FTZ=@Ftz,
		VALIDATED_LICENSE=@ValidatedLicense,
		LICENSE_EXP_DATE=@LicenseExpDate,
		ECCN=@Eccn,
		AUTHORIZED_EMPL_NAME=@AuthorizedEmplName,
		AUTHORIZED_EMPL_TITLE=@AuthorizedEmplTitle,
		UPLOAD_INTERFACE_BATCH=@UploadInterfaceBatch,
		CUSTOMER_RESIDENTIAL_FLAG=@CustomerResidentialFlag,
		SHIPTO_RESIDENTIAL_FLAG=@ShiptoResidentialFlag,
		REJECTION_NOTE=@RejectionNote,
		INTERFACE_RECORD_ID=@InterfaceRecordId,
		CUSTOMER_CATEGORY1=@CustomerCategory1,
		CUSTOMER_CATEGORY2=@CustomerCategory2,
		CUSTOMER_CATEGORY3=@CustomerCategory3,
		CUSTOMER_CATEGORY4=@CustomerCategory4,
		CUSTOMER_CATEGORY5=@CustomerCategory5,
		CUSTOMER_CATEGORY6=@CustomerCategory6,
		CUSTOMER_CATEGORY7=@CustomerCategory7,
		CUSTOMER_CATEGORY8=@CustomerCategory8,
		CUSTOMER_CATEGORY9=@CustomerCategory9,
		CUSTOMER_CATEGORY10=@CustomerCategory10,
		CONSOLIDATION_DOCK_LOC_AREA=@ConsolidationDockLocArea,
		CONSOLIDATION_DOCK_LOC_POS=@ConsolidationDockLocPos,		
		PROCESS_TYPE=@ProcessType,
		CREATION_PROCESS_STAMP=@CreationProcessStamp,
		CREATION_DATE_TIME_STAMP=@CreationDateTimeStamp,
		IMMEDIATE_NEEDS_NOTE=@ImmediateNeedsNote,
		ALLOCATE_COMPLETE=@AllocateComplete,
		ALTERNATE_EMAIL_ADDRESS=@AlternateEmailAddress,
		STOP_SEQUENCE=@StopSequence,
		STORE_DISTRIBUTION=@StoreDistribution,
		WEIGHT_ENTERED = @WeightEntered,
		VALUE_ENTERED = @ValueEntered,
		VOLUME_ENTERED = @VolumeEntered
	 WHERE INTERNAL_SHIPMENT_NUM = @InternalShipmentNum

	SET @RowsAffected = @@ROWCOUNT




