
CREATE PROCEDURE wm_IOrderHeader01
	@InternalOrderNum numeric(9) OUTPUT,
	@Warehouse nvarchar(25),
	@ErpOrder nvarchar(25),
	@Condition nvarchar(25),
	@OrderType nvarchar(25),
	@TotalShipments numeric(9),
	@ContainersShipped numeric(9),
	@WeightShipped numeric(19,5),
	@WeightUm nvarchar(25),
	@VolumeShipped numeric(19,5),
	@VolumeUm nvarchar(25),
	@ValueShipped numeric(19,5),
	@PartOfConsolidation nchar(1),
	@Company nvarchar(25),
	@UserDef1 nvarchar(25),
	@UserDef2 nvarchar(25),
	@UserDef3 nvarchar(25),
	@UserDef4 nvarchar(25),
	@UserDef5 nvarchar(25),
	@UserDef6 nvarchar(25),
	@UserDef7 numeric(19,5),
	@UserDef8 numeric(19,5),
	@UserStamp nvarchar(30),
	@ProcessStamp nvarchar(100),
	@DateTimeStamp datetime,
	@ConditionDateTime datetime,
	@Customer nvarchar(25),
	@CustomerName nvarchar(50),
	@CustomerAddress1 nvarchar(50),
	@CustomerAddress2 nvarchar(50),
	@CustomerAddress3 nvarchar(50),
	@CustomerAttentionTo nvarchar(50),
	@CustomerCity nvarchar(30),
	@CustomerState nvarchar(25),
	@CustomerCountry nvarchar(25),
	@CustomerPostalCode nvarchar(25),
	@CustomerPhoneNum nvarchar(50),
	@CustomerFaxNum nvarchar(50),
	@CustomerEmailAddress nvarchar(50),
	@ShipTo nvarchar(25),
	@ShipToName nvarchar(50),
	@ShipToAddress1 nvarchar(50),
	@ShipToAddress2 nvarchar(50),
	@ShipToAddress3 nvarchar(50),
	@ShipToAttentionTo nvarchar(50),
	@ShipToCity nvarchar(30),
	@ShipToState nvarchar(25),
	@ShipToCountry nvarchar(25),
	@ShipToPostalCode nvarchar(25),
	@ShipToPhoneNum nvarchar(50),
	@ShipToFaxNum nvarchar(50),
	@ShipToEmailAddress nvarchar(50),
	@CustomerPo nvarchar(25),
	@OrderDate datetime,
	@RequestedDeliveryDate datetime,
	@RequestedDeliveryType nvarchar(10),
	@IntermediateConsignee nvarchar(25),
	@IntermediateName nvarchar(50),
	@IntermediateAddress1 nvarchar(50),
	@IntermediateAddress2 nvarchar(50),
	@IntermediateAddress3 nvarchar(50),
	@IntermediateAttentionTo nvarchar(50),
	@IntermediateCity nvarchar(30),
	@IntermediateState nvarchar(25),
	@IntermediateCountry nvarchar(25),
	@IntermediatePostalCode nvarchar(25),
	@IntermediatePhoneNum nvarchar(50),
	@IntermediateFaxNum nvarchar(50),
	@IntermediateEmailAddress nvarchar(50),
	@FreightBillTo nvarchar(25),
	@FreightBillToName nvarchar(50),
	@FreightBillToAddress1 nvarchar(50),
	@FreightBillToAddress2 nvarchar(50),
	@FreightBillToAddress3 nvarchar(50),
	@FreightBillToAttentionTo nvarchar(50),
	@FreightBillToCity nvarchar(30),
	@FreightBillToState nvarchar(25),
	@FreightBillToCountry nvarchar(25),
	@FreightBillToPostalCode nvarchar(25),
	@FreightBillToPhoneNum nvarchar(50),
	@FreightBillToFaxNum nvarchar(50),
	@FreightBillToEmailAddress nvarchar(50),
	@Priority numeric(3),
	@ConsolidationAllowed nchar(1),
	@Carrier nvarchar(25),
	@CarrierService nvarchar(50),
	@CarrierGroup nvarchar(25),
	@CarrierType nvarchar(25),
	@PlannedShipDate datetime,
	@PlannedDeliveryDate datetime,
	@FreightTerms nvarchar(50),
	@LiabilityTerms nvarchar(25),
	@Route nvarchar(25),
	@Stop nvarchar(25),
	@RoutingCode nvarchar(25),
	@SingleItemCartons nvarchar(25),
	@CustomerResidentialFlag nchar(1),
	@ShiptoResidentialFlag nchar(1),
	@InterfaceRecordId nvarchar(25),
	@CustomerCategory1 nvarchar(50),
	@CustomerCategory2 nvarchar(50),
	@CustomerCategory3 nvarchar(50),
	@CustomerCategory4 nvarchar(50),
	@CustomerCategory5 nvarchar(50),
	@CustomerCategory6 nvarchar(50),
	@CustomerCategory7 nvarchar(50),
	@CustomerCategory8 nvarchar(50),
	@CustomerCategory9 nvarchar(50),
	@CustomerCategory10 nvarchar(50),
	@ProcessType nvarchar(25),
	@CreationProcessStamp nvarchar(100),
	@CreationDateTimeStamp datetime,
	@AlternateEmailAddress nvarchar(50)
AS
	INSERT INTO ORDER_HEADER(
		ALTERNATE_EMAIL_ADDRESS,
		CARRIER,
		CARRIER_GROUP,
		CARRIER_SERVICE,
		CARRIER_TYPE,
		COMPANY,
		CONDITION,
		CONDITION_DATE_TIME,
		CONSOLIDATION_ALLOWED,
		CONTAINERS_SHIPPED,
		CREATION_DATE_TIME_STAMP,
		CREATION_PROCESS_STAMP,
		CUSTOMER,
		CUSTOMER_ADDRESS1,
		CUSTOMER_ADDRESS2,
		CUSTOMER_ADDRESS3,
		CUSTOMER_ATTENTION_TO,
		CUSTOMER_CATEGORY1,
		CUSTOMER_CATEGORY10,
		CUSTOMER_CATEGORY2,
		CUSTOMER_CATEGORY3,
		CUSTOMER_CATEGORY4,
		CUSTOMER_CATEGORY5,
		CUSTOMER_CATEGORY6,
		CUSTOMER_CATEGORY7,
		CUSTOMER_CATEGORY8,
		CUSTOMER_CATEGORY9,
		CUSTOMER_CITY,
		CUSTOMER_COUNTRY,
		CUSTOMER_EMAIL_ADDRESS,
		CUSTOMER_FAX_NUM,
		CUSTOMER_NAME,
		CUSTOMER_PHONE_NUM,
		CUSTOMER_PO,
		CUSTOMER_POSTAL_CODE,
		CUSTOMER_RESIDENTIAL_FLAG,
		CUSTOMER_STATE,
		DATE_TIME_STAMP,
		ERP_ORDER,
		FREIGHT_BILL_TO,
		FREIGHT_BILL_TO_ADDRESS1,
		FREIGHT_BILL_TO_ADDRESS2,
		FREIGHT_BILL_TO_ADDRESS3,
		FREIGHT_BILL_TO_ATTENTION_TO,
		FREIGHT_BILL_TO_CITY,
		FREIGHT_BILL_TO_COUNTRY,
		FREIGHT_BILL_TO_EMAIL_ADDRESS,
		FREIGHT_BILL_TO_FAX_NUM,
		FREIGHT_BILL_TO_NAME,
		FREIGHT_BILL_TO_PHONE_NUM,
		FREIGHT_BILL_TO_POSTAL_CODE,
		FREIGHT_BILL_TO_STATE,
		FREIGHT_TERMS,
		INTERFACE_RECORD_ID,
		INTERMEDIATE_ADDRESS1,
		INTERMEDIATE_ADDRESS2,
		INTERMEDIATE_ADDRESS3,
		INTERMEDIATE_ATTENTION_TO,
		INTERMEDIATE_CITY,
		INTERMEDIATE_CONSIGNEE,
		INTERMEDIATE_COUNTRY,
		INTERMEDIATE_EMAIL_ADDRESS,
		INTERMEDIATE_FAX_NUM,
		INTERMEDIATE_NAME,
		INTERMEDIATE_PHONE_NUM,
		INTERMEDIATE_POSTAL_CODE,
		INTERMEDIATE_STATE,
		LIABILITY_TERMS,
		ORDER_DATE,
		ORDER_TYPE,
		PART_OF_CONSOLIDATION,
		PLANNED_DELIVERY_DATE,
		PLANNED_SHIP_DATE,
		PRIORITY,
		PROCESS_STAMP,
		PROCESS_TYPE,
		REQUESTED_DELIVERY_DATE,
		REQUESTED_DELIVERY_TYPE,
		ROUTE,
		ROUTING_CODE,
		SHIP_TO,
		SHIP_TO_ADDRESS1,
		SHIP_TO_ADDRESS2,
		SHIP_TO_ADDRESS3,
		SHIP_TO_ATTENTION_TO,
		SHIP_TO_CITY,
		SHIP_TO_COUNTRY,
		SHIP_TO_EMAIL_ADDRESS,
		SHIP_TO_FAX_NUM,
		SHIP_TO_NAME,
		SHIP_TO_PHONE_NUM,
		SHIP_TO_POSTAL_CODE,
		SHIP_TO_STATE,
		SHIPTO_RESIDENTIAL_FLAG,
		SINGLE_ITEM_CARTONS,
		STOP,
		TOTAL_SHIPMENTS,
		USER_DEF1,
		USER_DEF2,
		USER_DEF3,
		USER_DEF4,
		USER_DEF5,
		USER_DEF6,
		USER_DEF7,
		USER_DEF8,
		USER_STAMP,
		VALUE_SHIPPED,
		VOLUME_SHIPPED,
		VOLUME_UM,
		warehouse,
		WEIGHT_SHIPPED,
		WEIGHT_UM
	) VALUES (
		@AlternateEmailAddress,
		@Carrier,
		@CarrierGroup,
		@CarrierService,
		@CarrierType,
		@Company,
		@Condition,
		@ConditionDateTime,
		@ConsolidationAllowed,
		@ContainersShipped,
		@CreationDateTimeStamp,
		@CreationProcessStamp,
		@Customer,
		@CustomerAddress1,
		@CustomerAddress2,
		@CustomerAddress3,
		@CustomerAttentionTo,
		@CustomerCategory1,
		@CustomerCategory10,
		@CustomerCategory2,
		@CustomerCategory3,
		@CustomerCategory4,
		@CustomerCategory5,
		@CustomerCategory6,
		@CustomerCategory7,
		@CustomerCategory8,
		@CustomerCategory9,
		@CustomerCity,
		@CustomerCountry,
		@CustomerEmailAddress,
		@CustomerFaxNum,
		@CustomerName,
		@CustomerPhoneNum,
		@CustomerPo,
		@CustomerPostalCode,
		@CustomerResidentialFlag,
		@CustomerState,
		@DateTimeStamp,
		@ErpOrder,
		@FreightBillTo,
		@FreightBillToAddress1,
		@FreightBillToAddress2,
		@FreightBillToAddress3,
		@FreightBillToAttentionTo,
		@FreightBillToCity,
		@FreightBillToCountry,
		@FreightBillToEmailAddress,
		@FreightBillToFaxNum,
		@FreightBillToName,
		@FreightBillToPhoneNum,
		@FreightBillToPostalCode,
		@FreightBillToState,
		@FreightTerms,
		@InterfaceRecordId,
		@IntermediateAddress1,
		@IntermediateAddress2,
		@IntermediateAddress3,
		@IntermediateAttentionTo,
		@IntermediateCity,
		@IntermediateConsignee,
		@IntermediateCountry,
		@IntermediateEmailAddress,
		@IntermediateFaxNum,
		@IntermediateName,
		@IntermediatePhoneNum,
		@IntermediatePostalCode,
		@IntermediateState,
		@LiabilityTerms,
		@OrderDate,
		@OrderType,
		@PartOfConsolidation,
		@PlannedDeliveryDate,
		@PlannedShipDate,
		@Priority,
		@ProcessStamp,
		@ProcessType,
		@RequestedDeliveryDate,
		@RequestedDeliveryType,
		@Route,
		@RoutingCode,
		@ShipTo,
		@ShipToAddress1,
		@ShipToAddress2,
		@ShipToAddress3,
		@ShipToAttentionTo,
		@ShipToCity,
		@ShipToCountry,
		@ShipToEmailAddress,
		@ShipToFaxNum,
		@ShipToName,
		@ShipToPhoneNum,
		@ShipToPostalCode,
		@ShipToState,
		@ShiptoResidentialFlag,
		@SingleItemCartons,
		@Stop,
		@TotalShipments,
		@UserDef1,
		@UserDef2,
		@UserDef3,
		@UserDef4,
		@UserDef5,
		@UserDef6,
		@UserDef7,
		@UserDef8,
		@UserStamp,
		@ValueShipped,
		@VolumeShipped,
		@VolumeUm,
		@Warehouse,
		@WeightShipped,
		@WeightUm
	)
SELECT @InternalOrderNum = SCOPE_IDENTITY()



