
CREATE PROCEDURE wm_UShippingLoad01
	@RowsAffected int OUTPUT,
	@InternalLoadNum numeric(9),
	@Warehouse nvarchar(25),
	@LeadingSts numeric(3),
	@LeadingStsDate datetime,
	@LeadingStsFailed nchar(1),
	@TrailingSts numeric(3),
	@TrailingStsDate datetime,
	@TrailingStsFailed nchar(1),
	@Carrier nvarchar(25),
	@ScheduledShipDate datetime,
	@ActualShipDateTime datetime,
	@PlannedDepartureDateTime datetime,
	@ActualDepartureDateTime datetime,
	@LoadSizeDef nvarchar(25),
	@LoadClosed nchar(1),
	@SealId nvarchar(25),
	@TrailerId nvarchar(25),
	@WeightUm nvarchar(25),
	@VolumeUm nvarchar(25),
	@ManuallyEntered nchar(1),
	@UserDef1 nvarchar(25),
	@UserDef2 nvarchar(25),
	@UserDef3 nvarchar(25),
	@UserDef4 nvarchar(25),
	@UserDef5 nvarchar(25),
	@UserDef6 nvarchar(25),
	@UserDef7 numeric(19,5),
	@UserDef8 numeric(19,5),
	@UserStamp nvarchar(30),
	@ProcessStamp nvarchar(100),
	@DateTimeStamp datetime,
	@DockDoor numeric(9),
	@InConfirmation nchar(1)
AS
	UPDATE SHIPPING_LOAD
	   SET
		warehouse=@Warehouse,
		LEADING_STS=@LeadingSts,
		LEADING_STS_DATE=@LeadingStsDate,
		LEADING_STS_FAILED=@LeadingStsFailed,
		TRAILING_STS=@TrailingSts,
		TRAILING_STS_DATE=@TrailingStsDate,
		TRAILING_STS_FAILED=@TrailingStsFailed,
		CARRIER=@Carrier,
		SCHEDULED_SHIP_DATE=@ScheduledShipDate,
		ACTUAL_SHIP_DATE_TIME=@ActualShipDateTime,
		PLANNED_DEPARTURE_DATE_TIME=@PlannedDepartureDateTime,
		ACTUAL_DEPARTURE_DATE_TIME=@ActualDepartureDateTime,
		LOAD_SIZE_DEF=@LoadSizeDef,
		LOAD_CLOSED=@LoadClosed,
		SEAL_ID=@SealId,
		TRAILER_ID=@TrailerId,
		WEIGHT_UM=@WeightUm,
		VOLUME_UM=@VolumeUm,
		MANUALLY_ENTERED=@ManuallyEntered,
		USER_DEF1=@UserDef1,
		USER_DEF2=@UserDef2,
		USER_DEF3=@UserDef3,
		USER_DEF4=@UserDef4,
		USER_DEF5=@UserDef5,
		USER_DEF6=@UserDef6,
		USER_DEF7=@UserDef7,
		USER_DEF8=@UserDef8,
		USER_STAMP=@UserStamp,
		PROCESS_STAMP=@ProcessStamp,
		DATE_TIME_STAMP=@DateTimeStamp,
		DOCK_DOOR=@DockDoor,
		IN_CONFIRMATION=@InConfirmation
	 WHERE INTERNAL_LOAD_NUM = @InternalLoadNum

	SET @RowsAffected = @@ROWCOUNT


