
CREATE PROCEDURE wm_IReceiptDetail01
	@InternalReceiptLineNum numeric(9) OUTPUT,
	@LocatingRule nvarchar(25),
	@Warehouse nvarchar(25),
	@InternalReceiptNum numeric(9),
	@ReceiptId nvarchar(25),
	@Item nvarchar(50),
	@ItemDesc nvarchar(100),
	@ItemClass nvarchar(50),
	@Lot nvarchar(25),
	@Company nvarchar(25),
	@TotalQty numeric(28,5),
	@QuantityUm nvarchar(25),
	@OpenQty numeric(28,5),
	@ErpOrderNum nvarchar(25),
	@ErpOrderType nvarchar(25),
	@ErpOrderLineNum numeric(19,5),
	@ExpirationDateTime datetime,
	@ManufacturedDateTime datetime,
	@ItemWeight numeric(19,5),
	@WeightUm nvarchar(25),
	@ItemLength numeric(19,5),
	@ItemWidth numeric(19,5),
	@ItemHeight numeric(19,5),
	@ItemDimensionUm nvarchar(25),
	@VolumeUm nvarchar(25),
	@ItemDivision nvarchar(25),
	@ItemDepartment nvarchar(25),
	@Value numeric(28,5),
	@ItemSize nvarchar(25),
	@ItemColor nvarchar(25),
	@ItemStyle nvarchar(25),
	@LaunchNum numeric(9),
	@PutLoc nvarchar(25),
	@UserDef1 nvarchar(25),
	@UserDef2 nvarchar(25),
	@UserDef3 nvarchar(25),
	@UserDef4 nvarchar(25),
	@UserDef5 nvarchar(25),
	@UserDef6 nvarchar(25),
	@UserDef7 numeric(19,5),
	@UserDef8 numeric(19,5),
	@UserStamp nvarchar(30),
	@ProcessStamp nvarchar(100),
	@DateTimeStamp datetime,
	@PutZone nvarchar(25),
	@ItemListPrice numeric(19,5),
	@ItemNetPrice numeric(19,5),
	@PutListNum numeric(9),
	@ManuallyEntered nchar(1),
	@LotControlled nchar(1),
	@SerialNumReqd nchar(1),
	@CatchWeightReqd nchar(1),
	@SourceId nvarchar(25),
	@HazardousCode nvarchar(25),
	@TotalWeight numeric(28,5),
	@StatusFlowName nvarchar(25),
	@ExpectedInvSts nvarchar(50),
	@ShipFrom nvarchar(25),
	@ConversionQty numeric(19,5),
	@ConversionUm nvarchar(25),
	@Priority numeric(3),
	@CustomerOrderNum nvarchar(25),
	@ReceiptDate datetime,
	@ConversionHeight numeric(19,5),
	@ConversionWidth numeric(19,5),
	@ConversionLength numeric(19,5),
	@ConversionWeight numeric(19,5),
	@OriginalTotalQuantity numeric(28,5),
	@InterfaceRecordId nvarchar(25),
	@ItemCategory1 nvarchar(50),
	@ItemCategory2 nvarchar(50),
	@ItemCategory3 nvarchar(50),
	@ItemCategory4 nvarchar(50),
	@ItemCategory5 nvarchar(50),
	@ItemCategory6 nvarchar(50),
	@ItemCategory7 nvarchar(50),
	@ItemCategory8 nvarchar(50),
	@ItemCategory9 nvarchar(50),
	@ItemCategory10 nvarchar(50),
	@InventorySts nvarchar(50),
	@PurchaseOrderDetailId numeric(9),
	@PurchaseOrderId nvarchar(25),
	@PurchaseOrderLineNumber numeric(19,5)
AS
	INSERT INTO RECEIPT_DETAIL(
		CATCH_WEIGHT_REQD,
		COMPANY,
		CONVERSION_HEIGHT,
		CONVERSION_LENGTH,
		CONVERSION_QTY,
		CONVERSION_UM,
		CONVERSION_WEIGHT,
		CONVERSION_WIDTH,
		CUSTOMER_ORDER_NUM,
		DATE_TIME_STAMP,
		ERP_ORDER_LINE_NUM,
		ERP_ORDER_NUM,
		ERP_ORDER_TYPE,
		EXPECTED_INV_STS,
		EXPIRATION_DATE_TIME,
		HAZARDOUS_CODE,
		INTERFACE_RECORD_ID,
		INTERNAL_RECEIPT_NUM,
		INVENTORY_STS,
		ITEM,
		ITEM_CATEGORY1,
		ITEM_CATEGORY10,
		ITEM_CATEGORY2,
		ITEM_CATEGORY3,
		ITEM_CATEGORY4,
		ITEM_CATEGORY5,
		ITEM_CATEGORY6,
		ITEM_CATEGORY7,
		ITEM_CATEGORY8,
		ITEM_CATEGORY9,
		ITEM_CLASS,
		ITEM_COLOR,
		ITEM_DEPARTMENT,
		ITEM_DESC,
		ITEM_DIMENSION_UM,
		ITEM_DIVISION,
		ITEM_HEIGHT,
		ITEM_LENGTH,
		ITEM_LIST_PRICE,
		ITEM_NET_PRICE,
		ITEM_SIZE,
		ITEM_STYLE,
		ITEM_WEIGHT,
		ITEM_WIDTH,
		LAUNCH_NUM,
		LOCATING_RULE,
		LOT,
		LOT_CONTROLLED,
		MANUALLY_ENTERED,
		MANUFACTURED_DATE_TIME,
		OPEN_QTY,
		ORIGINAL_TOTAL_QUANTITY,
		PRIORITY,
		PROCESS_STAMP,
		PURCHASE_ORDER_DETAIL_ID,
		PURCHASE_ORDER_ID,
		PURCHASE_ORDER_LINE_NUMBER,
		PUT_LIST_NUM,
		PUT_LOC,
		PUT_ZONE,
		QUANTITY_UM,
		RECEIPT_DATE,
		RECEIPT_ID,
		SERIAL_NUM_REQD,
		SHIP_FROM,
		SOURCE_ID,
		STATUS_FLOW_NAME,
		TOTAL_QTY,
		TOTAL_WEIGHT,
		USER_DEF1,
		USER_DEF2,
		USER_DEF3,
		USER_DEF4,
		USER_DEF5,
		USER_DEF6,
		USER_DEF7,
		USER_DEF8,
		USER_STAMP,
		VALUE,
		VOLUME_UM,
		warehouse,
		WEIGHT_UM
	) VALUES (
		@CatchWeightReqd,
		@Company,
		@ConversionHeight,
		@ConversionLength,
		@ConversionQty,
		@ConversionUm,
		@ConversionWeight,
		@ConversionWidth,
		@CustomerOrderNum,
		@DateTimeStamp,
		@ErpOrderLineNum,
		@ErpOrderNum,
		@ErpOrderType,
		@ExpectedInvSts,
		@ExpirationDateTime,
		@HazardousCode,
		@InterfaceRecordId,
		@InternalReceiptNum,
		@InventorySts,
		@Item,
		@ItemCategory1,
		@ItemCategory10,
		@ItemCategory2,
		@ItemCategory3,
		@ItemCategory4,
		@ItemCategory5,
		@ItemCategory6,
		@ItemCategory7,
		@ItemCategory8,
		@ItemCategory9,
		@ItemClass,
		@ItemColor,
		@ItemDepartment,
		@ItemDesc,
		@ItemDimensionUm,
		@ItemDivision,
		@ItemHeight,
		@ItemLength,
		@ItemListPrice,
		@ItemNetPrice,
		@ItemSize,
		@ItemStyle,
		@ItemWeight,
		@ItemWidth,
		@LaunchNum,
		@LocatingRule,
		@Lot,
		@LotControlled,
		@ManuallyEntered,
		@ManufacturedDateTime,
		@OpenQty,
		@OriginalTotalQuantity,
		@Priority,
		@ProcessStamp,
		@PurchaseOrderDetailId, 
		@PurchaseOrderId, 
		@PurchaseOrderLineNumber,
		@PutListNum,
		@PutLoc,
		@PutZone,
		@QuantityUm,
		@ReceiptDate,
		@ReceiptId,
		@SerialNumReqd,
		@ShipFrom,
		@SourceId,
		@StatusFlowName,
		@TotalQty,
		@TotalWeight,
		@UserDef1,
		@UserDef2,
		@UserDef3,
		@UserDef4,
		@UserDef5,
		@UserDef6,
		@UserDef7,
		@UserDef8,
		@UserStamp,
		@Value,
		@VolumeUm,
		@Warehouse,
		@WeightUm
	)
SELECT @InternalReceiptLineNum = SCOPE_IDENTITY()



