------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------
/*
	Task	| By	| Date		| Modification Description
	--------------------------------------------------------------------
	204548  | DN    | 06/19/17  | Created
	259322	| VS	| 10/07/20	| Added condition to check against shipment_level so that if duplicate internal_num comes in SHIPMENT_ACCESSORIALS table for both shipment and container level accessorial,
								  then it can distinguish between them.
*/
------------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE PROCEDURE GetAccessorialDetails(
@internalNum int,
@internalNumType nvarchar(100),
@headerId int)
AS

--for edit accessorials child component binding	
IF(@headerId > 0)
BEGIN
if(UPPER(@internalNumType) = N'SHIPMENT')
BEGIN
	SELECT 
		ISNULL((SELECT OBJECT_ID FROM SHIPMENT_ACCESSORIALS WHERE INTERNAL_NUM=@internalNum AND ACCESSORIAL_DETAIL_ID = AD.OBJECT_ID AND SHIPMENT_LEVEL=N'Y'), 0) as N'ObjectId',
		AD.OBJECT_ID as N'DetailObjectId',
		AD.ACCESSORIAL_CODE,
		AD.ACCESSORIAL_SUB_CODE,
		AD.DESCRIPTION as DetailDesc, 
		AH.DESCRIPTION as HeaderDesc, 
		ISNULL((SELECT VALUE FROM SHIPMENT_ACCESSORIALS WHERE INTERNAL_NUM=@internalNum AND ACCESSORIAL_DETAIL_ID = AD.OBJECT_ID AND SHIPMENT_LEVEL=N'Y'), AD.VALUE) as N'VALUE',
		UPPER(AD.VALUE_TYPE) AS VALUE_TYPE,
		AD.ALLOW_OVERRIDE,
		ISNULL(AD.REQUIRED_FOR_RATING, N'N') AS REQUIRED
	FROM 
		SHIPMENT_HEADER SHP
		INNER JOIN
		CARRIER CR ON SHP.CARRIER=CR.CARRIER AND ISNULL(SHP.CARRIER_SERVICE, N'*') = ISNULL(CR.SERVICE, N'*')
		INNER JOIN
		ACCESSORIAL_HEADER AH ON AH.RATING_ID = CR.RATING_ID AND ISNULL(AH.RATING_SERVICE, N'*') = ISNULL(CR.RATING_SERVICE, N'*')
		INNER JOIN
		ACCESSORIAL_DETAIL AD ON AH.OBJECT_ID = AD.HEADER_ID
	WHERE AD.VALUE_TYPE NOT IN (N'Address', N'Complex') AND SHP.INTERNAL_SHIPMENT_NUM=@internalNum AND AH.OBJECT_ID=@headerId;
END
ELSE
BEGIN 
	declare @isContainerContent bit=0;
	select @isContainerContent = 1 FROM SHIPPING_CONTAINER WHERE INTERNAL_CONTAINER_NUM=@internalNum AND CONTAINER_TYPE=N'-';
	IF(@isContainerContent = 1)
	BEGIN
		SELECT 
			ISNULL((SELECT OBJECT_ID FROM SHIPMENT_ACCESSORIALS WHERE INTERNAL_NUM=@internalNum AND ACCESSORIAL_DETAIL_ID = AD.OBJECT_ID AND SHIPMENT_LEVEL=N'N'), 0) as N'ObjectId',
			AD.OBJECT_ID as N'DetailObjectId',
			AD.ACCESSORIAL_CODE,
			AD.ACCESSORIAL_SUB_CODE,
			AD.DESCRIPTION as DetailDesc, 
			AH.DESCRIPTION as HeaderDesc, 
			ISNULL((SELECT VALUE FROM SHIPMENT_ACCESSORIALS WHERE INTERNAL_NUM=@internalNum AND ACCESSORIAL_DETAIL_ID = AD.OBJECT_ID AND SHIPMENT_LEVEL=N'N'), AD.VALUE) as N'VALUE',
			UPPER(AD.VALUE_TYPE) AS VALUE_TYPE,
			AD.ALLOW_OVERRIDE,
			ISNULL(AD.REQUIRED_FOR_RATING, N'N') AS REQUIRED
		FROM 
			SHIPPING_CONTAINER SC
			INNER JOIN
			SHIPMENT_HEADER SHP ON SC.INTERNAL_SHIPMENT_NUM = SHP.INTERNAL_SHIPMENT_NUM
			INNER JOIN
			CARRIER CR ON SHP.CARRIER=CR.CARRIER AND ISNULL(SHP.CARRIER_SERVICE, N'*') = ISNULL(CR.SERVICE, N'*')
			INNER JOIN
			ACCESSORIAL_HEADER AH ON AH.RATING_ID = CR.RATING_ID AND ISNULL(AH.RATING_SERVICE, N'*') = ISNULL(CR.RATING_SERVICE, N'*')
			INNER JOIN
			ACCESSORIAL_DETAIL AD ON AH.OBJECT_ID = AD.HEADER_ID
		WHERE AD.VALUE_TYPE NOT IN (N'Address', N'Complex') AND SC.INTERNAL_CONTAINER_NUM=@internalNum AND AH.OBJECT_ID=@headerId;
	END
	ELSE
	BEGIN
		SELECT 
			ISNULL((SELECT OBJECT_ID FROM SHIPMENT_ACCESSORIALS WHERE INTERNAL_NUM=@internalNum AND ACCESSORIAL_DETAIL_ID = AD.OBJECT_ID AND SHIPMENT_LEVEL=N'N'), 0) as N'ObjectId',
			AD.OBJECT_ID as N'DetailObjectId',
			AD.ACCESSORIAL_CODE,
			AD.ACCESSORIAL_SUB_CODE,
			AD.DESCRIPTION as DetailDesc, 
			AH.DESCRIPTION as HeaderDesc, 
			ISNULL((SELECT VALUE FROM SHIPMENT_ACCESSORIALS WHERE INTERNAL_NUM=@internalNum AND ACCESSORIAL_DETAIL_ID = AD.OBJECT_ID AND SHIPMENT_LEVEL=N'N'), AD.VALUE) as N'VALUE',
			UPPER(AD.VALUE_TYPE) AS VALUE_TYPE,
			AD.ALLOW_OVERRIDE,
			ISNULL(AD.REQUIRED_FOR_RATING, N'N') AS REQUIRED
		FROM 
			SHIPPING_CONTAINER SC
			INNER JOIN
			SHIPMENT_HEADER SHP ON SC.INTERNAL_SHIPMENT_NUM = SHP.INTERNAL_SHIPMENT_NUM
			INNER JOIN
			CARRIER CR ON SHP.CARRIER=CR.CARRIER AND ISNULL(SHP.CARRIER_SERVICE, N'*') = ISNULL(CR.SERVICE, N'*')
			INNER JOIN
			ACCESSORIAL_HEADER AH ON AH.RATING_ID = CR.RATING_ID AND ISNULL(AH.RATING_SERVICE, N'*') = ISNULL(CR.RATING_SERVICE, N'*')
			INNER JOIN
			ACCESSORIAL_DETAIL AD ON AH.OBJECT_ID = AD.HEADER_ID
		WHERE AD.VALUE_TYPE NOT IN (N'Address', N'Complex') AND AD.APPLY_TO_CONTAINER_CONTENTS=N'N' AND SC.INTERNAL_CONTAINER_NUM=@internalNum AND AH.OBJECT_ID=@headerId;
	END
END
END
