
-- =============================================
-- Author:LM
-- Create date: 2016/12/20
-- Description:Updated Crystal Report during SCALE 2010-2016 upgrade
---- =============================================
CREATE PROCEDURE [dbo].[RPT_Travis_Commercial_Invoice] 
	( @INTERNAL_SHIPMENT_NUM INT )
AS
BEGIN

	SET NOCOUNT ON;

	--DECLARE @INTERNAL_SHIPMENT_NUM INT 
	--SET @INTERNAL_SHIPMENT_NUM = 3300377

	; WITH MAIN_FORM ( SHIP_TO_ADDRESS1, SHIP_TO_ADDRESS2, SHIP_TO_CITY, SHIP_TO_COUNTRY
				, SHIP_TO_NAME, SHIP_TO_POSTAL_CODE, SHIP_TO_STATE, TRANSPORTATION_MODE
				, HARMONIZED_CODE, HARMONIZED_DESC, LINE_QTY, INTERNAL_SHIPMENT_NUM, ITEM
				, COUNTRY_OF_ORIGIN, LINE_WEIGHT, CUSTOMER_PO, LIABILITY_TERMS, EXPORT_PORT
				, ERP_ORDER, VOLUME_UM, WEIGHT_UM, AUTHORIZED_EMPL_NAME, AUTHORIZED_EMPL_TITLE
				, ACCESSORIAL_CHARGE, BASE_FREIGHT_CHARGE, RECORD_TYPE, DESCRIPTION, FREIGHT_BILL_TO_ADDRESS1
				, FREIGHT_BILL_TO_ADDRESS2, FREIGHT_BILL_TO_CITY, FREIGHT_BILL_TO_STATE
				, FREIGHT_BILL_TO_POSTAL_CODE, FREIGHT_BILL_TO_COUNTRY, ITEM_NET_PRICE, ITEM_DESC
				, LINE_AMOUNT
			)	
		AS (
				SELECT SH.SHIP_TO_ADDRESS1, SH.SHIP_TO_ADDRESS2, SH.SHIP_TO_CITY, SH.SHIP_TO_COUNTRY
					, SH.SHIP_TO_NAME, SH.SHIP_TO_POSTAL_CODE, SH.SHIP_TO_STATE, SH.TRANSPORTATION_MODE
					, SD.HARMONIZED_CODE, SD.HARMONIZED_DESC, 'LINE_QTY' = CAST(SD.TOTAL_QTY As INT), SD.INTERNAL_SHIPMENT_NUM, SD.ITEM
					, SD.COUNTRY_OF_ORIGIN, 'LINE_WEIGHT' = CAST(SD.TOTAL_WEIGHT As DECIMAL(9,2)), SD.CUSTOMER_PO, SH.LIABILITY_TERMS, SH.EXPORT_PORT
					, SD.ERP_ORDER, SH.VOLUME_UM, SH.WEIGHT_UM, SH.AUTHORIZED_EMPL_NAME, SH.AUTHORIZED_EMPL_TITLE
					, 'ACCESSORIAL_CHARGE' = CAST(SH.ACCESSORIAL_CHARGE As DECIMAL(9,2)), 'BASE_FREIGHT_CHARGE' = CAST(SH.BASE_FREIGHT_CHARGE As DECIMAL(9,2))
					, GCD.RECORD_TYPE, GCD.[DESCRIPTION], WHS.FREIGHT_BILL_TO_ADDRESS1
					, WHS.FREIGHT_BILL_TO_ADDRESS2, WHS.FREIGHT_BILL_TO_CITY , WHS.FREIGHT_BILL_TO_STATE
					, WHS.FREIGHT_BILL_TO_POSTAL_CODE, WHS.FREIGHT_BILL_TO_COUNTRY, 'ITEM_NET_PRICE' = CAST(SD.ITEM_NET_PRICE As DECIMAL(9,2)), SD.ITEM_DESC
					, 'LINE_AMOUNT' = CAST((SD.TOTAL_QTY * SD.ITEM_NET_PRICE) As DECIMAL(9,2))
				FROM  ((dbo.SHIPMENT_HEADER SH WITH(NOLOCK)
							INNER JOIN dbo.SHIPMENT_DETAIL SD 
								ON SH.INTERNAL_SHIPMENT_NUM = SD.INTERNAL_SHIPMENT_NUM
							)
						INNER JOIN WAREHOUSE WHS
							ON SH.warehouse = WHS.warehouse
						) 
				LEFT OUTER JOIN dbo.GENERIC_CONFIG_DETAIL GCD 
					ON SH.SHIP_TO_COUNTRY = GCD.IDENTIFIER
				WHERE  SH.INTERNAL_SHIPMENT_NUM = @INTERNAL_SHIPMENT_NUM 
				AND GCD.RECORD_TYPE = N'COUNTRY'
			)
		, TOTALS (SHIPMENT_ID, INTERNAL_SHIPMENT_NUM, TTL_COUNT, TTL_WEIGHT, TTL_VOLUME)
		AS (
			SELECT SH.[SHIPMENT_ID], SH.[INTERNAL_SHIPMENT_NUM]
				, CAST(COUNT(sc.[CONTAINER_ID]) As INT) 'CONT_COUNT'
				, CASE WHEN SUM(SC.[WEIGHT]) IS NULL THEN (
							SELECT CAST(SUM(SD.TOTAL_WEIGHT) As DECIMAL(9,2)) 
							FROM AR_SHIPMENT_DETAIL SD WITH(NOLOCK)
							WHERE SD.INTERNAL_SHIPMENT_NUM = SH.INTERNAL_SHIPMENT_NUM
						)
					ELSE CAST(SUM(SC.[WEIGHT]) As DECIMAL(9,2)) END 'WEIGHT'
				, CASE WHEN SUM(SC.[VOLUME]) IS NULL THEN (
							SELECT CAST(SUM(SD.[TOTAL_VOLUME]) As DECIMAL(9,2)) 
							FROM AR_SHIPMENT_DETAIL SD WITH(NOLOCK)
							WHERE SD.INTERNAL_SHIPMENT_NUM = SH.INTERNAL_SHIPMENT_NUM
						)
					ELSE CAST(SUM(SC.[VOLUME]) As DECIMAL(9,2)) END 'VOLUME'
			FROM SHIPPING_CONTAINER SC WITH(NOLOCK) 
			RIGHT OUTER JOIN SHIPMENT_HEADER SH WITH(NOLOCK)
			ON SC.INTERNAL_SHIPMENT_NUM = SH.INTERNAL_SHIPMENT_NUM
			WHERE sc.INTERNAL_SHIPMENT_NUM = @INTERNAL_SHIPMENT_NUM
			AND CONTAINER_ID IS NOT NULL
			GROUP BY SH.SHIPMENT_ID, SH.INTERNAL_SHIPMENT_NUM
		)

		SELECT m.*, t.TTL_COUNT, t.TTL_WEIGHT, t.TTL_VOLUME
		FROM MAIN_FORM m
		INNER JOIN TOTALS t
			ON m.INTERNAL_SHIPMENT_NUM = t.INTERNAL_SHIPMENT_NUM

	SET NOCOUNT OFF;
END
