/*
	Task	| By	| Date		| Modification Description
	---------------------------------------------------------------
	4854	| SMS	| 06/15/07	| Created.
	41741	| SMS	| 11/25/08	| Modified GENERIC_CONFIG_DETAIL condition to select YARDLOCAREA

	Returns a rowset used for details in Yard Visibility Report.rpt
	
	Parameters:
		Warehouse - Warehouse name


	Returns:
		Rowset with Yard Location, its corresponding trailer, receipt 
		and appointment details.

*/

CREATE PROCEDURE RPT_YardVisibilityDetails
(	
	@paramwarehouse nvarchar(25)
)
AS
BEGIN
	
	SELECT
			D.DOCK_LOCATION AS N'DOCK_LOCATION', 
			T.TRAILER_LOCATION AS N'TRAILER_LOCATION', 
			CASE 
				WHEN T.TRAILER_ID IS NULL THEN N'Empty'
				WHEN T.SCHEDULED_YARD_LOCATION = D.DOCK_LOCATION THEN N'Empty'
				ELSE T.TRAILER_ID
			END N'TRAILER_ID',
			CASE 
				WHEN T.SCHEDULED_YARD_LOCATION = D.DOCK_LOCATION THEN T.TRAILER_ID
			END N'SCHEDULED_YARD_LOCATION',
			R.RECEIPT_ID N'RECEIPT_ID',
			R.INTERNAL_RECEIPT_NUM N'INTERNAL_RECEIPT_NUM', 
			A.APPT_DATE_TIME N'APPT_DATE_TIME', 
			T.CHECKED_IN_DATE_TIME N'CHECKED_IN_DATE_TIME'			
	FROM 	(
				SELECT		DOCK_LOCATION 
				FROM		DOCK_LOCATION WITH (NOLOCK)
				WHERE		WAREHOUSE = @paramwarehouse
				AND			DOCK_LOCATION_AREA IN
				(	
					SELECT	IDENTIFIER 
					FROM	GENERIC_CONFIG_DETAIL WITH (NOLOCK)
					WHERE	RECORD_TYPE = N'YARDLOCAREA'
				)
			)D 
	LEFT OUTER JOIN TRAILER_YARD_STATUS T WITH (NOLOCK)
	ON			(D.DOCK_LOCATION = T.TRAILER_LOCATION OR 
				D.DOCK_LOCATION = T.SCHEDULED_YARD_LOCATION)
	LEFT OUTER JOIN RECEIPT_HEADER R WITH (NOLOCK)
	ON			T.TRAILER_ID = R.TRAILER_ID 
	LEFT OUTER JOIN APPOINTMENT_SCHEDULE A WITH (NOLOCK)
	ON			R.INTERNAL_RECEIPT_NUM = A.INTERNAL_RECEIPT_NUM
	ORDER BY	DOCK_LOCATION
END




