CREATE PROCEDURE GetIntraDayLaborProgressWorkDetails
    @WAREHOUSE nvarchar(25),
    @WAREHOUSE_START_TIME_UTC datetime,
    @CURRENT_TIME_UTC datetime,
	@INTERNAL_NUM_TYPES NVARCHAR(MAX),
	@INSTRUCTION_TYPE nvarchar(25),
	@CONDITION nvarchar(25),
	@IS_WORK_TYPE_ACTIVE nchar(1)
AS
BEGIN
    SET NOCOUNT ON;
	DECLARE @InternalNumTypes TABLE (INTERNAL_NUM_TYPE NVARCHAR(100) PRIMARY KEY);
	DECLARE @WAVE_HOLD_CODE nvarchar(200);

	INSERT INTO @InternalNumTypes (INTERNAL_NUM_TYPE)
	SELECT LTRIM(RTRIM(value))
	FROM STRING_SPLIT(@INTERNAL_NUM_TYPES, N',');

	SELECT TOP (1)
		@WAVE_HOLD_CODE = SYSTEM_VALUE
	FROM SYSTEM_CONFIG_DETAIL
	WHERE RECORD_TYPE = N'Work Setup'
		AND SYS_KEY = N'Wave Hold'
		AND (WAREHOUSE = @WAREHOUSE OR WAREHOUSE IS NULL)
	ORDER BY CASE WHEN WAREHOUSE = @WAREHOUSE THEN 0 ELSE 1 END;

    -- Get tasked units from WORK_INSTRUCTION (open/in process shipments)
    ;WITH TaskedWorkOpen AS (
        SELECT 
            WI.WORK_TYPE,
            WI.WORK_GROUP AS WORK_GROUP,
			WT.LABOR_GROUP as LABOR_GROUP,
			WI.INTERNAL_NUM_TYPE AS INTERNAL_NUM_TYPE,
            CASE 
				WHEN WI.INTERNAL_NUM_TYPE = N'Dock Management'
				THEN COUNT(DISTINCT WI.TREE_UNIT_ID)
				ELSE 
				SUM(ISNULL(WI.CONVERTED_QTY, 0))
			END AS OPEN_TASKED_UNITS,

			COUNT(DISTINCT 
			CASE 
				WHEN WI.INTERNAL_NUM_TYPE = N'Shipment' 
				THEN WI.CONVERTED_QTY_UM
			END) AS OPEN_UOM_COUNT,

			MIN(
			CASE 
				WHEN WI.INTERNAL_NUM_TYPE = N'Shipment' 
					THEN WI.CONVERTED_QTY_UM
			END) AS OPEN_MIN_UOM
        FROM 
            WORK_INSTRUCTION_VIEW WI
        INNER JOIN 
            WORK_TYPE WT ON WI.WORK_TYPE = WT.WORK_TYPE
        WHERE 
            WT.ACTIVE = @IS_WORK_TYPE_ACTIVE
            AND WI.INTERNAL_NUM_TYPE IN (SELECT INTERNAL_NUM_TYPE FROM @InternalNumTypes)
            AND WI.INSTRUCTION_TYPE = @INSTRUCTION_TYPE
            AND (WI.CONDITION <> @CONDITION OR (WI.CONDITION = @CONDITION AND WI.END_DATE_TIME > @CURRENT_TIME_UTC and WI.END_DATE_TIME < GETUTCDATE()))
            AND WI.FROM_WHS = @WAREHOUSE
			AND AGING_DATE_TIME<= @CURRENT_TIME_UTC
			AND (WI.HOLD_CODE IS NULL OR @WAVE_HOLD_CODE IS NULL OR WI.HOLD_CODE <> @WAVE_HOLD_CODE)
        GROUP BY 
            WI.WORK_TYPE,
			WI.WORK_GROUP,
			WT.LABOR_GROUP,
			WI.INTERNAL_NUM_TYPE
    ),
    -- Get completed units from closed detail records in WORK_INSTRUCTION
    CompletedWorkInstruction AS (
        SELECT 
            WI.WORK_TYPE,
            WI.WORK_GROUP AS WORK_GROUP,
			WT.LABOR_GROUP AS LABOR_GROUP,
			WI.INTERNAL_NUM_TYPE AS INTERNAL_NUM_TYPE,
            CASE 
				WHEN WI.INTERNAL_NUM_TYPE = N'Dock Management'
				THEN COUNT(DISTINCT WI.TREE_UNIT_ID)
				ELSE 
				SUM(ISNULL(WI.CONVERTED_QTY, 0))
			END AS COMPLETED_UNITS,

			COUNT(DISTINCT 
			CASE 
				WHEN WI.INTERNAL_NUM_TYPE = N'Shipment' 
				THEN WI.CONVERTED_QTY_UM
			END) AS CLOSED_UOM_COUNT,

			MIN(
			CASE 
				WHEN WI.INTERNAL_NUM_TYPE = N'Shipment' 
					THEN WI.CONVERTED_QTY_UM
			END) AS CLOSED_MIN_UOM
        FROM 
            WORK_INSTRUCTION_VIEW WI
        INNER JOIN 
            WORK_TYPE WT ON WI.WORK_TYPE = WT.WORK_TYPE
        WHERE 
            WT.ACTIVE = @IS_WORK_TYPE_ACTIVE
            AND WI.INTERNAL_NUM_TYPE IN (SELECT INTERNAL_NUM_TYPE FROM @InternalNumTypes)
            AND WI.INSTRUCTION_TYPE = @INSTRUCTION_TYPE
            AND WI.CONDITION =  @CONDITION
            AND WI.FROM_WHS = @WAREHOUSE
            AND WI.END_DATE_TIME >= @WAREHOUSE_START_TIME_UTC
            AND WI.END_DATE_TIME <= @CURRENT_TIME_UTC
        GROUP BY 
            WI.WORK_TYPE,
			WI.WORK_GROUP,
			WT.LABOR_GROUP,
			WI.INTERNAL_NUM_TYPE
    ),
	-- CONSOLIDATED LABOR QUERY: Get completed hours and FTE calculation
	LaborSummary AS (
		SELECT 
			LMD.ACTIVITY_TYPE AS WORK_TYPE,
			LMD.WORK_GROUP,
			LMD.USER_NAME,
			LMD.TOTAL_ACTIVITY_TIME,
			MAX(LMD.ACTIVITY_END_TIME) AS LATEST_END_TIME
		FROM 
			LABOR_MGMT_DETAIL_CONSOLIDATION LMD
		INNER JOIN 
			WORK_TYPE WT ON LMD.ACTIVITY_TYPE = WT.WORK_TYPE
		WHERE 
			WT.ACTIVE = @IS_WORK_TYPE_ACTIVE
			AND LMD.WAREHOUSE = @WAREHOUSE
			AND LMD.ACTIVITY_START_TIME >= @WAREHOUSE_START_TIME_UTC
			AND LMD.ACTIVITY_END_TIME <= @CURRENT_TIME_UTC
		GROUP BY 
			LMD.ACTIVITY_TYPE,
			LMD.WORK_GROUP,
			LMD.USER_NAME,
			LMD.TOTAL_ACTIVITY_TIME
	),

		CompletedHours AS (
		SELECT 
			WORK_TYPE,
			WORK_GROUP,
			SUM(
				CASE 
					WHEN TOTAL_ACTIVITY_TIME LIKE N'%:%:%' THEN
						-- Parse d.HH:mm:ss format
						CAST(SUBSTRING(TOTAL_ACTIVITY_TIME, 1, CHARINDEX(N'.', TOTAL_ACTIVITY_TIME) - 1) AS INT) * 24 * 60 + -- Days to minutes
						CAST(SUBSTRING(TOTAL_ACTIVITY_TIME, CHARINDEX(N'.', TOTAL_ACTIVITY_TIME) + 1, 2) AS INT) * 60 + -- Hours to minutes
						CAST(SUBSTRING(TOTAL_ACTIVITY_TIME, CHARINDEX(N'.', TOTAL_ACTIVITY_TIME) + 4, 2) AS INT) + -- Minutes
						CAST(SUBSTRING(TOTAL_ACTIVITY_TIME, CHARINDEX(N'.', TOTAL_ACTIVITY_TIME) + 7, 2) AS DECIMAL(10,2)) / 60 -- Seconds to minutes
					ELSE 0
				END
			) / 60.0 AS COMPLETED_HOURS
		FROM 
			LaborSummary
		GROUP BY 
			WORK_TYPE,
			WORK_GROUP
	),
	-- Filter users within inactivity threshold for FTE calculation
	-- Count each user only once against their most recent work type
	ActiveUsers AS (
		SELECT 
			LS.WORK_TYPE,
			LS.WORK_GROUP,
			LS.USER_NAME
		FROM 
			LaborSummary LS
		INNER JOIN (
			-- Get the latest activity per user across all work types
			SELECT 
				USER_NAME,
				MAX(LATEST_END_TIME) AS MAX_END_TIME
			FROM 
				LaborSummary
			GROUP BY 
				USER_NAME
		) LatestActivity ON LS.USER_NAME = LatestActivity.USER_NAME 
						AND LS.LATEST_END_TIME = LatestActivity.MAX_END_TIME
		INNER JOIN 
			WORK_TYPE WT ON LS.WORK_TYPE = WT.WORK_TYPE
		LEFT JOIN 
			LABOR_GROUP LG ON WT.LABOR_GROUP = LG.LABOR_GROUP
		WHERE 
			DATEDIFF(MINUTE, LS.LATEST_END_TIME, @CURRENT_TIME_UTC) <= ISNULL(LG.HEEL_TO_TOE_TOLERANCE, 30)
	),
	-- Count distinct active users (FTE) per work type and work group
	FTECalculation AS (
		SELECT 
			WORK_TYPE,
			WORK_GROUP,
			COUNT(DISTINCT USER_NAME) AS FTE_COUNT
		FROM 
			ActiveUsers
		GROUP BY 
			WORK_TYPE,
			WORK_GROUP
	),
	-- Union of distinct work type/group/internal_num_type keys from both open and completed work
	AllWorkTypes AS (
		SELECT WORK_TYPE, WORK_GROUP, LABOR_GROUP, INTERNAL_NUM_TYPE FROM TaskedWorkOpen
		UNION
		SELECT WORK_TYPE, WORK_GROUP, LABOR_GROUP, INTERNAL_NUM_TYPE FROM CompletedWorkInstruction
	)

    -- Combine all results and calculate % complete
    SELECT 
        AWT.WORK_TYPE,
        AWT.WORK_GROUP,
		AWT.INTERNAL_NUM_TYPE,
        ISNULL(TOW.OPEN_TASKED_UNITS, 0) + ISNULL(CWI.COMPLETED_UNITS, 0) AS TOTAL_TASKED_UNITS,		
		ISNULL(CWI.COMPLETED_UNITS, 0) AS COMPLETED_UNITS,
		CASE 
			WHEN (ISNULL(TOW.OPEN_TASKED_UNITS, 0) + ISNULL(CWI.COMPLETED_UNITS, 0)) > 0 THEN 
				ROUND(ISNULL(CWI.COMPLETED_UNITS, 0) * 100.0 / 
					  (ISNULL(TOW.OPEN_TASKED_UNITS, 0) + ISNULL(CWI.COMPLETED_UNITS, 0)), 2)
			ELSE 
				0
		END AS PERCENT_COMPLETE,
		ISNULL(FTE.FTE_COUNT, 0) AS FTE_COUNT,
		ROUND(ISNULL(CH.COMPLETED_HOURS, 0), 2) AS COMPLETED_HOURS,
		-- Calculate Total Tasked Hours: Total Tasked Units / Expected Throughput (units/hour)
		ROUND(
			CASE 
				WHEN ISNULL(LG.EXPECTED_THROUGHPUT, 0) > 0 THEN 
					(ISNULL(TOW.OPEN_TASKED_UNITS, 0) + ISNULL(CWI.COMPLETED_UNITS, 0)) / LG.EXPECTED_THROUGHPUT
				ELSE 
					0
			END, 2
		) AS TOTAL_TASKED_HOURS,
		-- Calculate Remaining Hours: Total Tasked Hours - Completed Hours
		ROUND(
			CASE 
				WHEN ISNULL(LG.EXPECTED_THROUGHPUT, 0) > 0 THEN 
					((ISNULL(TOW.OPEN_TASKED_UNITS, 0) + ISNULL(CWI.COMPLETED_UNITS, 0)) / LG.EXPECTED_THROUGHPUT) - ISNULL(CH.COMPLETED_HOURS, 0)
				ELSE 
					0
			END, 2
		) AS REMAINING_HOURS,
		-- Detect UOM: Return single UOM if all open and closed work have same UOM, else NULL
		CASE 
			-- If both have same single UOM → return it
			WHEN ISNULL(TOW.OPEN_UOM_COUNT, 0) = 1 AND CWI.CLOSED_UOM_COUNT = 1 
				 AND TOW.OPEN_MIN_UOM = CWI.CLOSED_MIN_UOM THEN TOW.OPEN_MIN_UOM
			-- If either open or closed has multiple UOMs internally → mixed
			WHEN ISNULL(TOW.OPEN_UOM_COUNT, 0) > 1 OR ISNULL(CWI.CLOSED_UOM_COUNT, 0) > 1 THEN NULL
			-- If both exist and UOMs differ → mixed
			WHEN TOW.OPEN_MIN_UOM IS NOT NULL AND CWI.CLOSED_MIN_UOM IS NOT NULL 
				 AND TOW.OPEN_MIN_UOM <> CWI.CLOSED_MIN_UOM THEN NULL
			-- If only open work exists with single UOM → return it
			WHEN ISNULL(TOW.OPEN_UOM_COUNT, 0) = 1 AND CWI.CLOSED_MIN_UOM IS NULL THEN TOW.OPEN_MIN_UOM
			-- If only closed work exists with single UOM → return it
			WHEN CWI.CLOSED_UOM_COUNT = 1 AND TOW.OPEN_MIN_UOM IS NULL THEN CWI.CLOSED_MIN_UOM
			ELSE NULL
		END AS CONVERTED_QTY_UM
    FROM 
        AllWorkTypes AWT
	LEFT JOIN
		TaskedWorkOpen TOW ON AWT.WORK_TYPE = TOW.WORK_TYPE AND AWT.WORK_GROUP = TOW.WORK_GROUP AND AWT.INTERNAL_NUM_TYPE = TOW.INTERNAL_NUM_TYPE
	LEFT JOIN 
		LABOR_GROUP LG ON AWT.LABOR_GROUP = LG.LABOR_GROUP
    LEFT JOIN 
        CompletedWorkInstruction CWI ON AWT.WORK_TYPE = CWI.WORK_TYPE AND AWT.WORK_GROUP = CWI.WORK_GROUP AND AWT.INTERNAL_NUM_TYPE = CWI.INTERNAL_NUM_TYPE
	LEFT JOIN 
		FTECalculation FTE ON AWT.WORK_TYPE = FTE.WORK_TYPE AND AWT.WORK_GROUP = FTE.WORK_GROUP
	LEFT JOIN 
		CompletedHours CH ON AWT.WORK_TYPE = CH.WORK_TYPE AND AWT.WORK_GROUP = CH.WORK_GROUP
    ORDER BY 
        AWT.WORK_TYPE;

END