
CREATE PROCEDURE wm_IShippingLoad01
	@InternalLoadNum numeric(9) OUTPUT,
	@Warehouse nvarchar(25),
	@LeadingSts numeric(3),
	@LeadingStsDate datetime,
	@LeadingStsFailed nchar(1),
	@TrailingSts numeric(3),
	@TrailingStsDate datetime,
	@TrailingStsFailed nchar(1),
	@Carrier nvarchar(25),
	@ScheduledShipDate datetime,
	@ActualShipDateTime datetime,
	@PlannedDepartureDateTime datetime,
	@ActualDepartureDateTime datetime,
	@LoadSizeDef nvarchar(25),
	@LoadClosed nchar(1),
	@SealId nvarchar(25),
	@TrailerId nvarchar(25),
	@WeightUm nvarchar(25),
	@VolumeUm nvarchar(25),
	@ManuallyEntered nchar(1),
	@UserDef1 nvarchar(25),
	@UserDef2 nvarchar(25),
	@UserDef3 nvarchar(25),
	@UserDef4 nvarchar(25),
	@UserDef5 nvarchar(25),
	@UserDef6 nvarchar(25),
	@UserDef7 numeric(19,5),
	@UserDef8 numeric(19,5),
	@UserStamp nvarchar(30),
	@ProcessStamp nvarchar(100),
	@DateTimeStamp datetime,
	@DockDoor numeric(9),
	@InConfirmation nchar(1)
AS
	INSERT INTO SHIPPING_LOAD(
		ACTUAL_DEPARTURE_DATE_TIME,
		ACTUAL_SHIP_DATE_TIME,
		CARRIER,
		DATE_TIME_STAMP,
		IN_CONFIRMATION,
		LEADING_STS,
		LEADING_STS_DATE,
		LEADING_STS_FAILED,
		LOAD_CLOSED,
		LOAD_SIZE_DEF,
		DOCK_DOOR,
		MANUALLY_ENTERED,
		PLANNED_DEPARTURE_DATE_TIME,
		PROCESS_STAMP,
		SCHEDULED_SHIP_DATE,
		SEAL_ID,
		TRAILER_ID,
		TRAILING_STS,
		TRAILING_STS_DATE,
		TRAILING_STS_FAILED,
		USER_DEF1,
		USER_DEF2,
		USER_DEF3,
		USER_DEF4,
		USER_DEF5,
		USER_DEF6,
		USER_DEF7,
		USER_DEF8,
		USER_STAMP,
		VOLUME_UM,
		warehouse,
		WEIGHT_UM
	) VALUES (
		@ActualDepartureDateTime,
		@ActualShipDateTime,
		@Carrier,
		@DateTimeStamp,
		@InConfirmation,
		@LeadingSts,
		@LeadingStsDate,
		@LeadingStsFailed,
		@LoadClosed,
		@LoadSizeDef,
		@DockDoor,
		@ManuallyEntered,
		@PlannedDepartureDateTime,
		@ProcessStamp,
		@ScheduledShipDate,
		@SealId,
		@TrailerId,
		@TrailingSts,
		@TrailingStsDate,
		@TrailingStsFailed,
		@UserDef1,
		@UserDef2,
		@UserDef3,
		@UserDef4,
		@UserDef5,
		@UserDef6,
		@UserDef7,
		@UserDef8,
		@UserStamp,
		@VolumeUm,
		@Warehouse,
		@WeightUm
	)
SELECT @InternalLoadNum = SCOPE_IDENTITY()




