/*
	Task	| By	| Date		| Modification Description
	--------------------------------------------------------------------
	207165	| RJR	| 06/20/17	| Created
*/

CREATE PROCEDURE MetaTrans_GetReceiptFromPO(
@internalNum numeric(9),
@culture nvarchar(10))
AS
	SET NOCOUNT ON;

SELECT N'SCALAR' AS N'EntityType',
	N'PurchaseOrder' AS N'EntityName',
	PURCHASE_ORDER_HEADER.OBJECT_ID AS N'ObjectId', 
	PURCHASE_ORDER_HEADER.PURCHASE_ORDER_ID AS N'PurchaseOrderId',
	N'' AS N'ReceiptId', 
	PURCHASE_ORDER_HEADER.SOURCE_ID AS N'SourceId', 
	PURCHASE_ORDER_HEADER.SOURCE_ATTENTION_TO AS N'SourceAttentionTo', 
	PURCHASE_ORDER_HEADER.SOURCE_NAME AS N'SourceName', 
	PURCHASE_ORDER_HEADER.SOURCE_PHONE_NUM AS N'SourcePhoneNum', 
	PURCHASE_ORDER_HEADER.SOURCE_ADDRESS1 AS N'SourceAddress1', 
	PURCHASE_ORDER_HEADER.SOURCE_ADDRESS2 AS N'SourceAddress2', 
	PURCHASE_ORDER_HEADER.SOURCE_ADDRESS3 AS N'SourceAddress3', 
	PURCHASE_ORDER_HEADER.SOURCE_FAX_NUM AS N'SourceFaxNum', 
	PURCHASE_ORDER_HEADER.SOURCE_EMAIL_ADDRESS AS N'SourceEmail', 
	PURCHASE_ORDER_HEADER.SOURCE_CITY AS N'SourceCity', 
	PURCHASE_ORDER_HEADER.SOURCE_STATE AS N'SourceState', 
	PURCHASE_ORDER_HEADER.SOURCE_COUNTRY AS N'SourceCountry', 
	PURCHASE_ORDER_HEADER.SOURCE_POSTAL_CODE AS N'SourceZip', 
	PURCHASE_ORDER_HEADER.COMPANY AS N'Company',
	PURCHASE_ORDER_HEADER.Warehouse AS N'Warehouse'

FROM PURCHASE_ORDER_HEADER
WHERE PURCHASE_ORDER_HEADER.OBJECT_ID = @internalNum;