
CREATE PROCEDURE wm_IWarehouseAlert01
	@InternalAlertNum numeric(9) OUTPUT,
	@AlertType nvarchar(25),
	@Priority numeric(3),
	@Action nvarchar(25),
	@Message nvarchar(2000),
	@EmailTemplate nvarchar(500),
	@WebDescription nvarchar(50),
	@Active nchar(1),
	@SystemCreated nchar(1),
	@UserDef1 nvarchar(25),
	@UserDef2 nvarchar(25),
	@UserDef3 nvarchar(25),
	@UserDef4 nvarchar(25),
	@UserDef5 nvarchar(25),
	@UserDef6 nvarchar(25),
	@UserDef7 numeric(19,5),
	@UserDef8 numeric(19,5),
	@UserStamp nvarchar(30),
	@ProcessStamp nvarchar(100),
	@DateTimeStamp datetime,
	@Title nvarchar(50),
	@Description nvarchar(50)
AS
	INSERT INTO WAREHOUSE_ALERT(
		ACTION,
		ACTIVE,
		ALERT_TYPE,
		DATE_TIME_STAMP,
		DESCRIPTION,
		EMAIL_TEMPLATE,
		MESSAGE,
		PRIORITY,
		PROCESS_STAMP,
		SYSTEM_CREATED,
		TITLE,
		USER_DEF1,
		USER_DEF2,
		USER_DEF3,
		USER_DEF4,
		USER_DEF5,
		USER_DEF6,
		USER_DEF7,
		USER_DEF8,
		USER_STAMP,
		WEB_DESCRIPTION
	) VALUES (
		@Action,
		@Active,
		@AlertType,
		@DateTimeStamp,
		@Description,
		@EmailTemplate,
		@Message,
		@Priority,
		@ProcessStamp,
		@SystemCreated,
		@Title,
		@UserDef1,
		@UserDef2,
		@UserDef3,
		@UserDef4,
		@UserDef5,
		@UserDef6,
		@UserDef7,
		@UserDef8,
		@UserStamp,
		@WebDescription
	)
SELECT @InternalAlertNum = SCOPE_IDENTITY()


