/*
	Task	| By	| Date		| Modification Description
	--------------------------------------------------------------------
	197610	| SO	| 02/06/17	| Created
	198543	| SO	| 02/14/17	| Modified
*/

CREATE PROCEDURE MetaTrans_GetShipmentForCreateReceipt(
@internalShipmentNum numeric(9),
 @culture nvarchar(10))
AS
	SET NOCOUNT ON;

SELECT N'SCALAR' AS N'EntityType',
	N'ShipmentHeaderView' AS N'EntityName',
	SHIPMENT_HEADER.INTERNAL_SHIPMENT_NUM AS N'InternalShipmentNum', 
	SHIPMENT_HEADER.SHIPMENT_ID AS N'ShipmentId',
	SHIPMENT_HEADER.CARRIER AS N'Carrier',
	SHIPMENT_HEADER.CARRIER_SERVICE AS N'CarrierService',	
	SHIPMENT_HEADER.COMPANY AS N'Company' ,
	SHIPMENT_HEADER.Warehouse AS N'Warehouse' ,
	SHIPMENT_HEADER.SCHEDULED_SHIP_DATE AS N'ScheduledShipDate' ,
	SHIPMENT_HEADER.CUSTOMER_NAME AS N'CustomerName',
	SHIPMENT_HEADER.SHIP_TO AS N'ShipTo',
	SHIPMENT_HEADER.SHIP_TO_NAME AS N'ShipToName',
	SHIPMENT_HEADER.SHIP_TO_ADDRESS1 AS N'ShipToAddress1',
	SHIPMENT_HEADER.SHIP_TO_ADDRESS2 AS N'ShipToAddress2',
	SHIPMENT_HEADER.SHIP_TO_ADDRESS3 AS N'ShipToAddress3',
	SHIPMENT_HEADER.SHIP_TO_CITY AS N'ShipToCity',
	SHIPMENT_HEADER.SHIP_TO_STATE AS N'ShipToState',
	SHIPMENT_HEADER.SHIP_TO_POSTAL_CODE AS N'ShipToPostalCode',
	SHIPMENT_HEADER.SHIP_TO_COUNTRY AS N'ShipToCountry',
	SHIPMENT_HEADER.ACTUAL_SHIP_DATE_TIME AS N'ActualShipDate',
	SHIPMENT_HEADER.SHIP_TO_ATTENTION_TO AS N'ShipToAttentionTo', 
	SHIPMENT_HEADER.SHIP_TO_PHONE_NUM AS N'ShipToPhoneNum', 
	SHIPMENT_HEADER.SHIP_TO_FAX_NUM AS N'ShipToFaxNum', 
	SHIPMENT_HEADER.SHIP_TO_EMAIL_ADDRESS AS N'ShipToEmailAddress'

FROM SHIPMENT_HEADER
WHERE SHIPMENT_HEADER.INTERNAL_SHIPMENT_NUM =@internalShipmentNum
