/*
	Task	| By	| Date		| Modification Description
	--------------------------------------------------------------------
	216762	| SKT	| 02/19/20	| Created
	247808	| SKT	| 03/06/20	| Added Source Fields
*/

CREATE PROCEDURE MetaTrans_GetTpmReceiptFromPO(
@internalNum numeric(9),
@culture nvarchar(10))
AS
	SET NOCOUNT ON;

SELECT N'SCALAR' AS N'EntityType',
	N'PurchaseOrder' AS N'EntityName',
	PURCHASE_ORDER_HEADER.OBJECT_ID AS N'ObjectId', 
	PURCHASE_ORDER_HEADER.PURCHASE_ORDER_ID AS N'PurchaseOrderId',
	N'' AS N'ReceiptId', 
	PURCHASE_ORDER_HEADER.SOURCE_ID AS N'SourceId',
	PURCHASE_ORDER_HEADER.SOURCE_ATTENTION_TO AS N'SourceAttentionTo', 
	PURCHASE_ORDER_HEADER.SOURCE_NAME AS N'SourceName', 
	PURCHASE_ORDER_HEADER.SOURCE_PHONE_NUM AS N'SourcePhoneNum', 
	PURCHASE_ORDER_HEADER.SOURCE_ADDRESS1 AS N'SourceAddress1', 
	PURCHASE_ORDER_HEADER.SOURCE_ADDRESS2 AS N'SourceAddress2', 
	PURCHASE_ORDER_HEADER.SOURCE_ADDRESS3 AS N'SourceAddress3', 
	PURCHASE_ORDER_HEADER.SOURCE_FAX_NUM AS N'SourceFaxNum', 
	PURCHASE_ORDER_HEADER.SOURCE_EMAIL_ADDRESS AS N'SourceEmail', 
	PURCHASE_ORDER_HEADER.SOURCE_CITY AS N'SourceCity', 
	PURCHASE_ORDER_HEADER.SOURCE_STATE AS N'SourceState', 
	PURCHASE_ORDER_HEADER.SOURCE_COUNTRY AS N'SourceCountry', 
	PURCHASE_ORDER_HEADER.SOURCE_POSTAL_CODE AS N'SourcePostalCode',
	PURCHASE_ORDER_HEADER.SHIP_FROM AS N'ShipFrom', 
	PURCHASE_ORDER_HEADER.SHIP_FROM_ATTENTION_TO AS N'ShipFromAttentionTo', 
	PURCHASE_ORDER_HEADER.SHIP_FROM_NAME AS N'ShipFromName', 
	PURCHASE_ORDER_HEADER.SHIP_FROM_PHONE_NUM AS N'ShipFromPhoneNum', 
	PURCHASE_ORDER_HEADER.SHIP_FROM_ADDRESS1 AS N'ShipFromAddress1', 
	PURCHASE_ORDER_HEADER.SHIP_FROM_ADDRESS2 AS N'ShipFromAddress2', 
	PURCHASE_ORDER_HEADER.SHIP_FROM_ADDRESS3 AS N'ShipFromAddress3', 
	PURCHASE_ORDER_HEADER.SHIP_FROM_FAX_NUM AS N'ShipFromFaxNum', 
	PURCHASE_ORDER_HEADER.SHIP_FROM_EMAIL_ADDRESS AS N'ShipFromEmail', 
	PURCHASE_ORDER_HEADER.SHIP_FROM_CITY AS N'ShipFromCity', 
	PURCHASE_ORDER_HEADER.SHIP_FROM_STATE AS N'ShipFromState', 
	PURCHASE_ORDER_HEADER.SHIP_FROM_COUNTRY AS N'ShipFromCountry', 
	PURCHASE_ORDER_HEADER.SHIP_FROM_POSTAL_CODE AS N'ShipFromPostalCode', 
	PURCHASE_ORDER_HEADER.COMPANY AS N'Company',
	PURCHASE_ORDER_HEADER.WAREHOUSE AS N'Warehouse'

FROM PURCHASE_ORDER_HEADER
WHERE PURCHASE_ORDER_HEADER.OBJECT_ID = @internalNum;