	
CREATE FUNCTION SHIPCONTfn_RtrvItemContentsCount(@internalcontainernum numeric(9)) 
RETURNS INT
  BEGIN 
      -- LOCAL VARIABLES. 
      DECLARE @ITEMCONTENTS_COUNT INT; 

	  SELECT @ITEMCONTENTS_COUNT= COUNT(*) FROM SHIPPING_CONTAINER WHERE (PARENT=@internalcontainernum AND INTERNAL_SHIPMENT_LINE_NUM > 0 AND CONTAINER_TYPE = N'-') OR ( INTERNAL_CONTAINER_NUM=@internalcontainernum AND INTERNAL_SHIPMENT_LINE_NUM > 0 AND CONTAINER_TYPE <> N'-');

	  RETURN @ITEMCONTENTS_COUNT;
    
  END -- END SHIPCONTfn_RtrvItemContentsCount 
